### ISSUE TITLE
Incorrect recipe for ExtraUtils Resonator

### ISSUE THREAD

**Issue by Wafflous** [NillerMedDild/Enigmatica2Expert#1]
#### Issue Description
When attempting to crafting the resonator, the coal coke block required is from Chisel rather than Immersive Engineering. The Immersive Engineering coal coke can not be chiseled.

#### What happens
See above.

#### What you expected to happen
To craft the Extra Utilities 2 Resonator

#### Modpack version (Do not use "latest")
0.02(Beta)

#### Your most recent log file where the issue was present
---
[pastebin/gist/etc link here]
https://imgur.com/a/34MpD

**Comment by NillerMedDild** [comment]
Adding the Immersive Engineering Block of Coal Coke to ore:blockCoalCoke, that should fix it.

Thanks for the report.
