### ISSUE TITLE
1.05 server startup crashes with sponge

### ISSUE THREAD

**Issue by morrissimo** [NillerMedDild/Enigmatica2Expert#10]
This isn't really a problem with the modpack, but figured I'd post some easier-to-find breadcrumbs here on the off chance that anyone *else* runs into it. Feel free to close if you'd rather not have this issue-but-not-your-issue hanging around :)

Also reported on the affected mod's issue tracker:
https://gitlab.com/the_real_farfetchd/QuackLib/issues/5

#### Issue Description
Dedicated server crashes on startup when [sponge](https://www.spongepowered.org) is present

#### What you expected to happen
Normal server startup

#### Modpack version (Do not use "latest")
Dedicated server v1.05

#### Your most recent log file where the issue was present
https://pastebin.com/way02wua

**Comment by NillerMedDild** [comment]
I'll keep it open for a while, thank you :)

**Comment by bryanbecker** [comment]
This crashes with optifine/shaders, as well.  I had to disable quacklib and rswires to run the pack.  Otherwise opening JEI crashes with a rendering error

**Comment by NillerMedDild** [comment]
Fingers crossed he'll fix the issues soon, otherwise I'll remove QuackLib and RSWires.

**Comment by NillerMedDild** [comment]
On second thought, I'm removing QuackLib and RSWires, and will readd them if he fixes the crashes.

**Comment by NillerMedDild** [comment]
Version 1.08 should launch on Sponge servers - Could you test and get back to me please?

**Comment by NillerMedDild** [comment]
(and no longer crash with Optifine)

**Comment by NillerMedDild** [comment]
Closed due to lack of feedback.
