### ISSUE TITLE
RF Cost to Empower Void Crystal Suspect

### ISSUE THREAD

**Issue by lachian** [NillerMedDild/Enigmatica2Expert#100]
#### Issue Description
The RF Cost to Empower Void Crystals seem out of place with the rest of the RF cost to empower the other crystals.

Example: Restonia takes 100k rf, Palis Crystal takes 100k rf, Diamantine Crystal takes 200k rf
and Void Crystal takes ... 1 million rf

Looking at what empowered void crystals can make, I don't see the justification to have it take so much rf to empower. So reporting this to confirm if this is a bug or not.

#### Modpack version (Do not use "latest")
Modpack version: 1.26c, Forge version: 14.23.4.2707

**Comment by NillerMedDild** [comment]
It is on purpose :)
