### ISSUE TITLE
Ticking World Crash

### ISSUE THREAD

**Issue by Coolfox24** [NillerMedDild/Enigmatica2Expert#1001]
**Modpack version**
1.58

**Can the issue be reproduced?**
Kinda, unsure whats causing the crash but if I load a backup up and wait the ticking world exception reoccurs.

**Logs**
https://pastebin.com/ivt6gLXv

**Issue**
Game crashes from seemingly nothing. Upon reloading the game I have ~5s of play before I get the same crash.

Reverting to a previous save results in the crash occurring at roughly the same amount of time later.

**Comment by Coolfox24** [comment]
Update.
Deleting the deep dark dimension stops my crashing & re-adding it back in resumes the crashing.
Currently only have an rftools builder in the deep dark quarrying out an area - however it had been running for a few hours prior to this crashing occuring.

**Comment by NillerMedDild** [comment]
Looks like the builder may have malfunctioned in there. Does the crash still occur if you remove the Deep Dark, and then set the builder up again? I have a feeling this will be hard/impossible to reproduce.

**Comment by Coolfox24** [comment]
I ended up having enough time between the crashes to get into the deep dark & grab my builder. The crashes still occurred without the builder present, but once I had the block & got out I deleted the dimension and spawned a new one.

**Comment by NillerMedDild** [comment]
And that fixed it?

**Comment by Coolfox24** [comment]
Yeah, that fixed the crashing.

**Comment by NillerMedDild** [comment]
Sweet!
