### ISSUE TITLE
Crash with mekanism advanced solar panel in Dank null

### ISSUE THREAD

**Issue by RasiergummiBlei** [NillerMedDild/Enigmatica2Expert#1002]
**Modpack version**
1.58

**Can the issue be reproduced?**
Yes

**Logs**
https://pastebin.com/iLRmf1TE

**Issue**
World crash on loading world if u have put a advancel solar panel by mekanism in a dank null.
works on multiplayer too.

**Comment by NillerMedDild** [comment]
Duplicate of #345
