### ISSUE TITLE
Feature request: VanillaFix

### ISSUE THREAD

**Issue by GloriousYellow** [NillerMedDild/Enigmatica2Expert#1004]
[VanillaFix](https://github.com/DimensionalDevelopment/VanillaFix) has a dynamic model loading system, which reducec memory usage to 2-3 GB. I tested it in a singleplayer world but it crashes after a minute. 

Could it be beneficial to explore possible compatibility with VanillaFix?

**Comment by NillerMedDild** [comment]
It's too unstable I'm afraid :/
