### ISSUE TITLE
Twicth client not compatible with server 

### ISSUE THREAD

**Issue by gzcwnk** [NillerMedDild/Enigmatica2Expert#1006]
**Modpack version**
Input version here

1.62

**Can the issue be reproduced?**
Yes/no/unknown
 not known

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Issue**
Input short description of the issue here

Trying to join server 1.62 with twitch client pack disconnects with message of missing mods.

If this is a feature request, feel free to delete the template.

[20:01:00] [Server thread/INFO] [minecraft/NetHandlerPlayServer]: gzcwnk lost connection: Server Mod rejections:
Ancient Warfare Automation: Requires version 1.12.2-2.7.0.574 but mod is not found on client.
Ancient Warfare Core: Requires version 1.12.2-2.7.0.574 but mod is not found on client.
Ancient Warfare NPCs: Requires version 1.12.2-2.7.0.574 but mod is not found on client.
Ancient Warfare Structures: Requires version @VERSION@ but mod is not found on client.
Ancient Warfare Vehicles: Requires version 1.12.2-2.7.0.574 but mod is not found on client.
Binnie Core: Requires version 2.5.1.188 but mod is not found on client.
Binnie's Botany: Requires version 2.5.1.188 but mod is not found on client.
Binnie's Design: Requires version 2.5.1.188 but mod is not found on client.
Binnie's Extra Bees: Requires version 2.5.1.188 but mod is not found on client.
Binnie's Extra Trees: Requires version 2.5.1.188 but mod is not found on client.
Binnie's Genetics: Requires version 2.5.1.188 but mod is not found on client.
Construct's Armory: Requires version 1.2.3 but mod is not found on client.
Embers Rekindled: Requires version 1.12 but mod is not found on client.
Extra Bit Manipulation: Requires version 1.12.2-3.4.1 but mod is not found on client.
Extra Rails: Requires version 1.3.0 but mod is not found on client.
Farseek: Requires version 2.3.1 but mod is not found on client.
Funky Locomotion: Requires version 1.0 but mod is not found on client.
Garden Stuff: Requires version 1.12-2.1.1 but mod is not found on client.
Grass Burner: Requires version 0.1.0 but mod is not found on client.
LibrarianLib: Requires version 4.15 but mod is not found on client.
LibrarianLib Stage 2: Requires version 4.15 but mod is not found on client.
MagicBees: Requires version 1.0 but mod is not found on client.
MalisisCore: Requires version 1.12.2-6.5.1-SNAPSHOT but mod is not found on client.
MalisisDoors: Requires version 1.12.2-7.3.0 but mod is not found on client.
MeeCreeps: Requires version 1.2.3 but mod is not found on client.
MekanismTools: Requires version 9.4.11 but mod is not found on client.
MineColonies: Requires version 1.12.2-0.10.68-RELEASE but mod is not found on client.
Modular Routers: Requires version 1.12.2-3.2.1 but mod is not found on client.
Natura: Requires version 1.12.2-4.3.2.66 but mod is not found on client.
Not Enough Wands: Requires version 1.7.3 but mod is not found on client.
Patchouli: Requires version 1.0-18 but mod is not found on client.
PneumaticCraft: Repressurized: Requires version 1.12.2-0.9.3-324 but mod is not found on client.
Roots 2: Requires version 0.104 but mod is not found on client.
ShadowMC: Requires version 3.8.0 but mod is not found on client.
Streams: Requires version 0.4.4 but mod is not found on client.
Thermal Innovation: Requires version 0.3.2 but mod is not found on client.
TorchMaster: Requires version 1.7.1.74 but mod is not found on client.
Wizardry: Requires version 0.9.9 but mod is not found on client.
careerbees: Requires version 1.0 but mod is not found on client.
[20:01:00] [Server thread/INFO] [minecraft/DedicatedServer]: gzcwnk left the game
>

Issues,

a) no install instructions, pointing to twitch which is often broken is  a bad idea.  eg Twitch lists 1.58 client when the latest server is 1.62 provided ergo client needs an update. 
b) provide a manual method of installing or a link to same to avoid twitch.

**Comment by NillerMedDild** [comment]
You're trying to join an Enigmatica 2 world with an Enigmatica 2: Expert client, that is not possible.
