### ISSUE TITLE
vienminer not working

### ISSUE THREAD

**Issue by gzcwnk** [NillerMedDild/Enigmatica2Expert#1007]
**Modpack version**
Input version here

1.62

**Can the issue be reproduced?**
Yes/no/unknown
 not known

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Issue**
Input short description of the issue here

vienminer does not function

If this is a feature request, feel free to delete the template.

**Comment by NillerMedDild** [comment]
It works for me :)
Make sure the keybinding isn't conflicting, have something in your hand, and hold the keybinding.
