### ISSUE TITLE
Treasure altars not working 

### ISSUE THREAD

**Issue by XavierNero** [NillerMedDild/Enigmatica2Expert#101]
#### Issue Description
Ores not being dropped by treasure shrine
#### Modpack version (Do not use "latest")
1.26c
#### Further description
The treasure altar from astral sorcery that drops up to 250 Ores in other Modpack drops nothing, the materials are mine able and new blocks spawn, but breaking the blocks yields nothing

**Comment by NillerMedDild** [comment]
What did you break it with?

**Comment by tyler489** [comment]
Ihad this issue with a tconstruct pickaxe..  tested multiple times with obsidian manulyn osgloglass and supremium pick head none worked

**Comment by XavierNero** [comment]
Same, I tried with tinkers pickaxe and am about to to try with infused, will report results back, but tried manyllum pickaxe with silk touch and without

**Comment by XavierNero** [comment]
Infused pickaxe from astral sorcery, about to unlock it and it seems more thematic to the weapon

**Comment by XavierNero** [comment]
thematic to the ore *

**Comment by NillerMedDild** [comment]
I've reset the config for it, hopefully that'll do the trick :)

**Comment by randomlypickedname** [comment]
I'd like to chime in here and say I've confirmed this bug on my server yesterday on ver. 1.26c and just now on ver. 1.29. I've even gone as far as trying to use a Cardboard Box from Mek on it and the item was consumed, no box appeared, and the ore changed. Seems to be the same issue that's happening in HellFirePvP/AstralSorcery#565 and I'm working on narrowing it down now.

**Comment by randomlypickedname** [comment]
So it seems Tool Progression is the cause of this bug, at least for me (I know I'm in creative, but you can see the difference):
Without: https://imgur.com/a/vDKf4fc 
With: https://imgur.com/a/MVeWDN2

**Comment by NillerMedDild** [comment]
It doesn't look like we'll be getting a fix, I'm going to turn this feature off.
