### ISSUE TITLE
Rftools screens dupe

### ISSUE THREAD

**Issue by tonalom** [NillerMedDild/Enigmatica2Expert#1010]
**Modpack version**
1.58

**Can the issue be reproduced?**
Yes

**Issue**
When a screen or creative screen from rftools is shift+right clicked with a crescent hammer it will duplicate into two separate screens with different NBT data (One will have a blank NBT tag while the other will be registered to the owner). This duplication only works while playing on multiplayer.

**Comment by MaxNeedsSnacks** [comment]
If someone else could also confirm this issue on their instance, that'd be great
