### ISSUE TITLE
Primordial Pearl

### ISSUE THREAD

**Issue by BanzaiRun** [NillerMedDild/Enigmatica2Expert#1011]
**Feature request**
Could we possibly have a ridiculously expensive crafting recipe for the primordial pearl.
(it's a bit of a grind for us unlucky SOBs)

**Comment by NillerMedDild** [comment]
Possibly :)

**Comment by BanzaiRun** [comment]
Keeping my fingers crossed ;)

**Comment by Frikkle** [comment]
+1

**Comment by ben-mkiv** [comment]
Just empty like 20-30 Jars full of Essentia far away from your base after that collapse the first rift and a from then on large rifts will spawn which have a higher chance of dropping one. So i got a bunch of primordial things within few minutes

**Comment by Frikkle** [comment]
Then RNGsus must love you :) I spent about six hours to get just one primordial mote doing exactly what you described. I ended up with a complete crater landscape and 12 large rifts chilling around.

**Comment by BanzaiRun** [comment]
Ditto, Frikkle and I are unlucky SOABs.

It was the last unfinished quest in my book....I cheated it in #NoRagrets

**Comment by Frikkle** [comment]
Love for the bond I feel, sadness for you cheating it in.

**Comment by NillerMedDild** [comment]
I don't have time to implement this I'm afraid.
