### ISSUE TITLE
Crash on World Load

### ISSUE THREAD

**Issue by Kirby1844** [NillerMedDild/Enigmatica2Expert#1012]
**Modpack version**
1.58

**Can the issue be reproduced?**
Yes, every time I start up a world.

**Logs**
https://pastebin.com/Ex7tA9Zp

**Issue**
So, uh, every time I start up a world now, the game just quickly goes to "shutting down internal server" before I have the chance to make any input, and then, after about 30 seconds, just disappears, and I'm back at the Minecraft launcher, which tells me there was an unexpected error. Now, I'm not the best at this, so I might be missing something. Oh, and also, I looked at the crash log, and while I'm not sure, it looks like it has something to do with Dank Null rendering.

Thanks for the help! I hope you have a nice day!

**Comment by MaxNeedsSnacks** [comment]
Do you have any idea what items were inside that /dank/null? And does removing the dank null with an NBT editor (or alternatively deleting your playerdata file entirely) fix the issue?

**Comment by Kirby1844** [comment]
On the first point: yes and no. I have four dank nulls in my inventory, one contains mining junk, another, building blocks, another, mob drops, and the fourth has crop harvests. 

I'll have to look into a NBT editor/playerdata file, since that's a little beyond my knowledge right now.

**Comment by Kuktar** [comment]
@kirby there is a setting in the forge mod loader config called #remove
erroring entity's.

If you enable that it's a super easy fix if you dont know NBT explorer's.

Let me know if this isnt an option for you. It's the thing I do when I'm
lazy lol

Christopher Kuhn,
Semper Fidelis

**Comment by NillerMedDild** [comment]
That config would not help in this case unfortunately, as it's not an entity that's causing the crash.

**Comment by Kuktar** [comment]
Oh I thought dank nulls were entities. This is why we have smart crafters
lol

Christopher Kuhn,
Semper Fidelis

**Comment by MaxNeedsSnacks** [comment]
@Kirby1844 could you maybe send me your playerdata file? This way I could see what exactly is inside the /dank/nulls

**Comment by Kirby1844** [comment]
https://drive.google.com/file/d/1q6aKo3U5rEtcH8YrqZwHKRRo9L-PE_3E/view?usp=sharing
Sure! I made an attempt on a different copy, thought it would be the Danknull with the architecturecraft items and thaumcraft lamps, but no, apparently not.

**Comment by MaxNeedsSnacks** [comment]
That's your Cyclic inventory, isn't the /dank/null that's causing the crash in your main one?

**Comment by MaxNeedsSnacks** [comment]
The file for that would be bdc018c2-5c67-4cd9-a7a2-f6ffdbfd8004 if your ingame name is kirby1844
