### ISSUE TITLE
Metallurgic Infuser not being recognized by Quest book

### ISSUE THREAD

**Issue by StratCat00** [NillerMedDild/Enigmatica2Expert#1013]
**Modpack version**
1.58

**Can the issue be reproduced?**
Unknown

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Issue**
Metallurgic Infuser not being recognized by the quest book under the Mekanism Chapter.  Quest will not complete.

If this is a feature request, feel free to delete the template.

**Comment by NillerMedDild** [comment]
Duplicate. Update :)
