### ISSUE TITLE
Advanced Inscribers have no recipes associated with them

### ISSUE THREAD

**Issue by AGamerNamedTom** [NillerMedDild/Enigmatica2Expert#1014]
**Modpack version**
1.58

**Can the issue be reproduced?**
Yes

**Issue**
Advanced inscribers are unable to craft anything as there seems to be no recipes associated with them. Items can no longer be inserted into the inscribers.

**Comment by Kuktar** [comment]
Did you look at JEI. Alot of recipes especially advanced stuff has been changed. It's best to say what you cant specifically craft :) it could be a bug but definitely look at jei just in case

**Comment by AGamerNamedTom** [comment]
First thing I checked. Normal inscribers have recipes, but not so with the advanced inscribers.

**Comment by Kuktar** [comment]
Oh I miss read that. Dang I'm getting old lol

Christopher Kuhn,
Semper Fidelis

**Comment by Coolfox24** [comment]
Also getting this issue after updating to the most recent version of the pack.

**Comment by NillerMedDild** [comment]
That is super weird, I have no idea what could be causing this atm. And you're certain this started in 1.58 @AGamerNamedTom ?

**Comment by AGamerNamedTom** [comment]
I can check the previous version, but I am pretty sure that I was playing that a couple of days ago, and it was definitely working then.

**Comment by MaxNeedsSnacks** [comment]
This may have to do with #1016 and NuclearCraft assigning radiation nbt to the items

**Comment by MaxNeedsSnacks** [comment]
Can someone reproduce this on an instance without NC?

**Comment by AGamerNamedTom** [comment]
Ok, just tested in the previous version, still no jei recipes showing up, but the advanced inscriber does work. Something definitely changed between the previous version and this one.

**Comment by MaxNeedsSnacks** [comment]
Can you make a new instance that ONLY has AE2 Stuff (and its requirements) installed and see whether the Advanced Inscriber works there?

And then perhaps add NuclearCraft (the newest version) and test with that as well?

**Comment by MaxNeedsSnacks** [comment]
Confirmed that NuclearCraft was the mod that borked the Advanced Inscribers.

Therefore merging into #1016
