### ISSUE TITLE
Dupe bug with /dank/null

### ISSUE THREAD

**Issue by SweetestPumpkin** [NillerMedDild/Enigmatica2Expert#1015]
**Modpack version**
1.58

**Can the issue be reproduced?**
Yes

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Issue**
When using /dank/null  in "extract akk but 1/16/64" , and removing items from it using GUI , they get duped. 

a video to show how this works : https://www.youtube.com/watch?v=SxVoCoY9Y8k&t=47s

Im not sure if this goes here or in issues for mod dank null , it would be great if someone could tell me.

If this is a feature request, feel free to delete the template.

**Comment by NillerMedDild** [comment]
Thanks for the report, I'll relay it to the DankNull issue tracker :)

**Comment by NillerMedDild** [comment]
Ah it has been fixed, but the latest version has other issues so we're forced to stay on an old version.
https://github.com/p455w0rd/DankNull/issues/143

**Comment by MorganSimic** [comment]
/dank/null had an update recently. Wich version is 1.65 of E2E running? It's really hard to find that out without having it installed. I think it fixes the weirdness we were experiencing with p455w0rd/DankNull#159.
So it would probably be safe to update if not done already.

**Comment by NillerMedDild** [comment]
DankNull-1.12-1.4.43 - I'll update now.

**Comment by NillerMedDild** [comment]
The issue was marked as blocked due to Password labeling the updates as incompatible with old worlds iirc, just fyi.

**Comment by Frikkle** [comment]
I'll report back if it broke after upgrading.

**Comment by Frikkle** [comment]
I still have my /dank/null and all of its contents after upgrading to 1.65a.

**Comment by NillerMedDild** [comment]
YAY!

**Comment by Frikkle** [comment]
Of course I have validated this with only one type of /dank/null, being the Emerald tier.

**Comment by NillerMedDild** [comment]
Should be the same logic across the board, I deem it safe :P

**Comment by Frikkle** [comment]
As an old Chinese saying told us "Assumptions are the mother of all f*ck-ups". So you're a brave man.

**Comment by NillerMedDild** [comment]
Grade A proverb!
