### ISSUE TITLE
NuclearCraft NBT issues (TCon Patterns, Adv Inscribers, etc.)

### ISSUE THREAD

**Issue by NillerMedDild** [NillerMedDild/Enigmatica2Expert#1016]
**Modpack version**
1.59

**Can the issue be reproduced?**
Yes

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Issue**
Tinkers' Construct Blank Patterns output nothing in the Stencil Table. Cannot reproduce with only TConstruct, Mantle and JEI.

**Comment by lynxnot** [comment]
Another issue with tinkers is that is not possible to pour metals into casts anymore.

**Comment by NillerMedDild** [comment]
Thanks for the info. Sounds like we need to downgrade.

**Comment by ALD76** [comment]
The newest version of Nuclearcraft has been causing issues with tinkers.

**Comment by MaxNeedsSnacks** [comment]
Just looked into it, it has to do with the new radiation nbt tag that was added. The best hotfix would be to just downgrade to 2.13.* for now until a solution has been pushed.

**Comment by MaxNeedsSnacks** [comment]
See turbodiesel4598/NuclearCraft#488 for updates on this.

**Comment by NillerMedDild** [comment]
Excellent, thanks a ton Max.

**Comment by turbodiesel4598** [comment]
Think I've sorted the problem - sorry for the issues :P
[Here's a build if you want to test it out.](https://www.dropbox.com/s/aqz99zshvdabxs3/NuclearCraft-2.14c-1.12.2.jar?dl=0)

**Comment by MaxNeedsSnacks** [comment]
Works fine now, thanks Tom!
![image](https://user-images.githubusercontent.com/12750501/54883322-1efbe980-4e65-11e9-9fce-f54d2c83ec63.png)

**Comment by turbodiesel4598** [comment]
Awesome - thanks for testing!
