### ISSUE TITLE
TC's Casting Table not working

### ISSUE THREAD

**Issue by tbotter** [NillerMedDild/Enigmatica2Expert#1017]
**Modpack version**
1.59

**Can the issue be reproduced?**
unknown?

**Logs**
Not a crash.

**Issue**
Draining liquid from a TC smeltery into a casting table doesn't work. Casting basin still work.
![javaw_2019-03-24_19-55-26](https://user-images.githubusercontent.com/39246308/54884310-9d5d8900-4e6f-11e9-910e-9c4e24477530.png)
![javaw_2019-03-24_19-49-43](https://user-images.githubusercontent.com/39246308/54884311-9d5d8900-4e6f-11e9-85f1-eae109778274.png)

**Comment by MorganSimic** [comment]
See #1016
