### ISSUE TITLE
Crash when shift-clicking blueprint into Engineer's Workbench

### ISSUE THREAD

**Issue by TheMCProf** [NillerMedDild/Enigmatica2Expert#1019]
**Modpack version**
1.58

**Can the issue be reproduced?**
Unknown.

**Logs**
https://pastebin.com/eW5CNLum

**Issue**
When I shift-clicked a blueprint into the Engineer's Workbench, my game crashed and closed Minecraft. When I tried to reload the game and open the world, it crashed again, I had to go into MCEdit and delete the workbench before being able to open the world again. 
I spawned in a new workbench after that and the game didn't crash again.

**Comment by MorganSimic** [comment]
For me that looks like your Java did crash for whatever reason. IE was involved for sure but more i can't tell.

**Comment by MaxNeedsSnacks** [comment]
Can you update your Java version and see whether that fixes anything?

**Comment by TheMCProf** [comment]
My Java is already at the latest version.

**Comment by Kuktar** [comment]
Your crashlog says your on _51 and _201 is the latest. Make sure you use
the provided java arguments that are bundled with the modpack.


   1.
   # JRE version: Java(TM) SE Runtime Environment (8.0_51-b16) (build
   1.8.0_51-b16)
   2. # Java VM: Java HotSpot(TM) 64-Bit Server VM (25.51-b03 mixed mode
   windows-amd64 compressed oops)



That was what your crashlog contained. That version is the old version that
is default for twitch launcher / minecraft launcher.


Christopher Kuhn,
Semper Fidelis

**Comment by NillerMedDild** [comment]
There are no java arguments bundled with the modpack.

In Twitch go to Settings > Minecraft, then add this to the Additional java parameters: `-version:1.8+`

**Comment by Kuktar** [comment]
Sorry I miss spoke. I ment the mod "old java warning" was in it for this
exact reason. Its 4am what the heck are you doing lol

Christopher Kuhn,
Semper Fidelis

**Comment by MaxNeedsSnacks** [comment]
It's almost 12am in Europe ^^

**Comment by Kuktar** [comment]
Oh nice. That makes sense. I forgot America isnt the only place people
live.

#stupidamericans

Lol

You guys are really dedicated none the less.

Ok thread jacking over.

Also PM me max with your donation link. You deserve it. I managed to send
Niller a coffee or whatever he chooses for poison lol

Christopher Kuhn,
Semper Fidelis

**Comment by MaxNeedsSnacks** [comment]
Oh I actually don't have a kofi or anything I do most of this for fun :P But uh, sure I'll try to get something setup if you really want to ^^

Actually getting back on track though - @TheMCProf, did you update to 1.59a? And if yes, did that fix it?

**Comment by TheMCProf** [comment]
Yes, I've updated to 1.59a and Minecraft is now using the latest Java version and haven't had any crashes anymore. Seemed to be a one-off thing.

**Comment by Kuktar** [comment]
Yes I would love to buy you a steak or somthing in that regard. You and
Niller are the bread and butter of minecraft for me.

Christopher Kuhn,
Semper Fidelis

**Comment by Kuktar** [comment]
What do you two donington the UK then. Us Americans just do coffee and
alcohol lol.

Christopher Kuhn,
Semper Fidelis
