### ISSUE TITLE
In the quest book there are some quests that change their Icon to a netherstar and the complete because they don't have a quest anymore. It are always the same Quests.

### ISSUE THREAD

**Issue by dragonriderworld** [NillerMedDild/Enigmatica2Expert#102]
In the quest book there are some quests that change their Icon to a netherstar and the complete because they don't have a quest anymore. It are always the same Quests

Modpack version: 1.27

No Crash Report

**Comment by NillerMedDild** [comment]
Please do not use version 1.27, I took it down for a reason. The last stable version is 1.26c

Reloading several times made it work for me, did that not work for you?

The command is `/bq_admin default load`

**Comment by dragonriderworld** [comment]
Nope it always comes back

**Comment by dragonriderworld** [comment]
So i should use Version 1.26c

**Comment by NillerMedDild** [comment]
Correct, I doubt that would fix it though. But as far as I know, this is a known issue when you have 600+ quests, I'm afraid.
