### ISSUE TITLE
Can not craft forestry farm parts

### ISSUE THREAD

**Issue by Alareg** [NillerMedDild/Enigmatica2Expert#1021]
**Modpack version**
1.59A

**Issue**
Forestry farm parts will not craft even when all the components are in the inventory.  The only block that will craft is the farm block itself.

If this is a feature request, feel free to delete the template.

**Comment by MaxNeedsSnacks** [comment]
Please provide more information.

1) What kind of farm part were you trying to craft?
2) Have you tried crafting it with cheated items / items without NBT?
3) Did you change anything about the pack's scripts?

**Comment by Alareg** [comment]
Thanks for the quick response.  I just re-updated the pack and now the
recipies are working. It was when trying to craft the components for the
quest.

The finished product of the gear box, valve etc were not showing up.    I
had not modified the pack in any way, and I had not tried cheating the
components in.  Not sure what the problem was, bit it's good now.

**Comment by MaxNeedsSnacks** [comment]
That's interesting... I'm gonna have to check that out on my own instance later. Thanks for reporting!
