### ISSUE TITLE
typo in Chaotic Sharpening Kit quest description

### ISSUE THREAD

**Issue by oOMitchOo** [NillerMedDild/Enigmatica2Expert#1022]
**Modpack version**
1.59a

There is a small typo in the "Chaotic Sharpening Kit" quest in the "Getting Stared" quest line.
I just wanted to let you know, since you probably won't notice any other way.

The "and" in the quest description should've been an "are".

And I got a question. A little off topic, but the quest descriptions don't give much info. What are Awakened Draconium and Chaotic harvest levels needed for?
Is this just a completion thing, or do I actually need those mining levels for anything?

And btw: Good work with the modpack!

**Comment by oOMitchOo** [comment]
Nevermind my question. I found the Tool Progression config files.

I still think, it would be nice, if those quests would have a little more information about for which ores / blocks you'll need those mining levels.
Or maybe an info page in JEI?

**Comment by MaxNeedsSnacks** [comment]
The CurseForge page has a spreadsheet with all the ores / mining levels on it (it's probably out of date, but still)

**Comment by MaxNeedsSnacks** [comment]
Fixed this locally, gonna commit that later when my PR has been closed.
