### ISSUE TITLE
JEI Resources - World Gen tab not showing

### ISSUE THREAD

**Issue by sashimipenguin** [NillerMedDild/Enigmatica2Expert#1024]
**Modpack version**
1.59a

**Can the issue be reproduced?**
Yes - Create new instance and new game with MultiMC using file downloaded from curseforge.

**Issue**
In 1.58 I was able to see the "World Gen" tab for ore generation statistics.  In 1.59a it does not display for any ores.

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by MaxNeedsSnacks** [comment]
I unfortunately can't because CurseForge apparently borked my Enigmatica instance and I need to reinstall and reconfigure it... ouch

**Comment by NillerMedDild** [comment]
Oh rip ><

**Comment by sashimipenguin** [comment]
I reverted JER from 0.9.0.52 back to 0.8.10.50 and that solved the problem for my 1.59a installation.  It looks like JER is adding a configuration to hide various tabs (like worldgen), and perhaps the default is to hide, but I'm not sure.

**Comment by MaxNeedsSnacks** [comment]
So JER *did* add that as a new feature, but I don't see anything that should actually hide its categories from view rn... weird.

https://github.com/NillerMedDild/Enigmatica2Expert/blob/f6226b5c53a4251016126f2527e690ea4beccd16/config/jeresources/jeresources.cfg#L21-L23

**Comment by NillerMedDild** [comment]
I hope downgrading JEI will fix this issue, we'll see in a few hours. If anyone has time to test it before me I wouldn't be opposed :D

**Comment by triasinformatica-gabe** [comment]
Evening all, I found this issue in the JER repo and commented on it there to get its cause narrowed down: https://github.com/way2muchnoise/JustEnoughResources/issues/180

It's just been merged. Some code was rewritten to fix it and the minimum Forge requirement has been bumped to 14.23.5.2779 (which is fine for this pack). So upgrading JER to 1.12.2-0.9.0.53 should also fix the issue.

**Comment by triasinformatica-gabe** [comment]
Just updated my local JER to 0.9.0.53 on Enigmatica2Expert v1.59a and the World Gen tab shows up again.

**Comment by NillerMedDild** [comment]
Cool, thanks!

**Comment by mitchej123** [comment]
I've had similar issues with them not loading, here's the relevant issues and my (local) fixes:

https://github.com/Buuz135/Thaumic-JEI/issues/50
https://github.com/way2muchnoise/JustEnoughResources/issues/181

I'm running locally with a few mods updated, so that might be contributing to my issues, but I've at least got them both working.  :man_shrugging:
