### ISSUE TITLE
Space Layer Problem

### ISSUE THREAD

**Issue by DSLM** [NillerMedDild/Enigmatica2Expert#1025]
**Modpack version**
1.58

**Can the issue be reproduced?**
Yes

**Issue**
I'm using the space layer on the planet Stella to mine the Destabilised Redstone, and I found the following problems:
1. an error rftool ore is mined by the layer: https://imgur.com/a/UiEhZF1
2. I get Starmetal Ore but not Destabilised Redstone from the layer; JEI shows that Destabilised Redstone on the Stella and Starmetal Ore not.

**Comment by NillerMedDild** [comment]
The Space Laser doesn't mine the planet's ores, it generates them from a list of possible ores.
