### ISSUE TITLE
V1.59a Can't unlock Thaumic Tinker items

### ISSUE THREAD

**Issue by Avallach160** [NillerMedDild/Enigmatica2Expert#1026]
**Modpack version**
1.59a (maybe earlier)

**Can the issue be reproduced?**
Yes

**Logs**
Save file: https://drive.google.com/open?id=1uCLn-46C0XzN4IW33EI3lDMx3qNCDYTJ

**Issue**
I'm not sure if this started earlier as I didn't realize Thaumic Tinkerer was in the top right of the thauminomicon but when I try to unlock  any of the starting recipes (except essentia funnel) the complete button changes to complete.... but doesn't update further. Closing and reopening the thauminomicon doesn't fix it nor does restarting the game.

**Comment by MorganSimic** [comment]
Thaumic Tinkerers research doesn't complete at all. That is a longstanding bug with the mod. There is a fixed being work on but has to be released yet afaik.

**Comment by MorganSimic** [comment]
Thaumic-Tinkerer/ThaumicTinkerer#937

**Comment by Avallach160** [comment]
Thanks for the update.

**Comment by Frikkle** [comment]
The related issue's PR has just been merged.

**Comment by Frikkle** [comment]
After a poke, https://github.com/Thaumic-Tinkerer/ThaumicTinkerer/issues/937 has been closed.

**Comment by NillerMedDild** [comment]
Yaaas! Do you know if there's a new version out yet?

**Comment by Frikkle** [comment]
There's no new version on curseforge yet, but there is activity on GitHub. All tasks which aren't enhancements or low-priority have been completed. But I don't know if that means there would be a new release any time soon.

I'll keep an eye out and do some more poking if there's no release in the next few days.
