### ISSUE TITLE
Mekanism Digital Miner can be manipulated to get specific TC crystal

### ISSUE THREAD

**Issue by dominik246** [NillerMedDild/Enigmatica2Expert#1028]
**Modpack version**
1.58

**Can the issue be reproduced?**
Yes, both in SP and MP

**Logs**
not-applicable

**Issue**
Placing a Mekanism Digital Miner in the configured vicinity of any Thaumcraft crystal allows you to change the crystal to any other form when mined with the Digital Miner. E.g. you place the digital miner by some earth crystals and you configure the Miner to mine any crystal (oreDict filter -> oreCrystal*), but you place a fire crystal in the first slot of the digital miner, it will convert all the mined crystals to fire crystal. When you get the full stack, it will randomly choose another crystal until the stack is also complete or until all the crystals are mined.

**Comment by MaxNeedsSnacks** [comment]
That’s some weird mod interaction going on then. @dizzyd Do you think this is an error on mekanica‘s side or is the ball in Azanor‘s court here?

**Comment by MorganSimic** [comment]
I think this can't be fixed so easily and needs to be reported to Mekanica. It's probably the handling of nbt data on the crystals. I have seen a lot of things going weird with the TC crytals, because machines can not tell them apart very well.

**Comment by dizzyd** [comment]
What version of Thaumcraft, please? I'll take a look tomorrow and see what I can do.

**Comment by MaxNeedsSnacks** [comment]
According to my Twitch Client, that'd be Thaumcraft-1.12.2-6.1.BETA26.jar

**Comment by pupnewfster** [comment]
I haven't tested to check if the issue with TC crystals is fixed, but my guess is that in the latest version 9.7.4 of mekanism it is fixed. As I believe it was the same issue as https://github.com/mekanism/Mekanism/issues/5449 which was due to the digital miner not properly checking NBT data for seeing if two items could stack.
