### ISSUE TITLE
Crash on startup 1.59a

### ISSUE THREAD

**Issue by ashaman16** [NillerMedDild/Enigmatica2Expert#1029]
**Modpack version**
1.59a

**Can the issue be reproduced?**
Yes

**Logs**
https://pastebin.com/zB6GHuZP

**Issue**
Crash on startup.  No issues on 1.58.

**Comment by NillerMedDild** [comment]
Re-download the modpack, set Twitch to use your latest Java by setting the launch method to Jar. Updating your graphic drivers would also be a good idea.
