### ISSUE TITLE
Questions About Mob Spawning System...

### ISSUE THREAD

**Issue by WhirlyZaph** [NillerMedDild/Enigmatica2Expert#103]
1. Vanilla Mob Spawning Room (Dark room with water and tall drop) doesn't spawn ANY mobs whatsoever. Do you have to use actual spawners?
2. Is this intended, or you have to use other methods because I waited for so long and no wither skeletons spawned in the nether fortress... Other intended mobs do spawn though.

Modpack Version: 1.26c

No Crash Reports.

**Comment by NillerMedDild** [comment]
That is not intended. Wither Skeletons should spawn in Nether Fortresses, you may have been unlucky?
How far were you from the Spawner?

**Comment by WhirlyZaph** [comment]
1. My spawning room is exactly a chunk big and my base is just directly or 2 chunks away from it.
2. I'll try to wait for an hour in the game and if there's no wither skeletons spawning can you give me a solution?

Extra question to make things clear, does overworld hostile mobs have lower spawning rate or the same? That might suggest a problem with either the pack or my device.

**Comment by NillerMedDild** [comment]
That's not intended, but it's not something I configured in any way.
Is it lit up, are there dark caves nearby?

**Comment by WhirlyZaph** [comment]
Nope, it's not lit up and my base is floating in the middle of an ocean.
I am kinda rushing on Ender IO in hopes to get the spawner working, so I think it would compensate for it.

**Comment by NillerMedDild** [comment]
Putting some Cursed Earth in there might do the trick aswell. I'm going to close this, as I think it's vanilla quirkiness.
