### ISSUE TITLE
Mekanism Electrolytic Separator Quest Data

### ISSUE THREAD

**Issue by MayhemGang** [NillerMedDild/Enigmatica2Expert#1030]
**Modpack version**
1.59
**Can the issue be reproduced?**
Yes

Mekanism still not working, Electrolytic separator NBT data still wrong.

If this is a feature request, feel free to delete the template.

**Comment by MaxNeedsSnacks** [comment]
Did you reload quests? `/bq_admin default load`

**Comment by MayhemGang** [comment]
Nevermind, ran the command and rebooted: it worked!
