### ISSUE TITLE
FOV changes

### ISSUE THREAD

**Issue by Old-Man-D** [NillerMedDild/Enigmatica2Expert#1031]
**Modpack version**
1.59a

**Can the issue be reproduced?**
unknown

**Logs**
No crash

**Issue**
FOV changes (zooms out) when entering commands.  This is unaffected by the FOV slider or any other FOV settings. Doing things like switching from survival to creative a few times will cause the FOV to change to the point where there is a whole pickaxe floating in space on the screen.  Reloading the client fixes it.

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by Old-Man-D** [comment]
ok, it was my dumb mistake, it was simply a keybind issue.  Please close this if you would.
