### ISSUE TITLE
Enable Mystical Agriculture Brass Seeds?

### ISSUE THREAD

**Issue by ConnorMiner** [NillerMedDild/Enigmatica2Expert#1033]
**Modpack version**
1.59a

**Issue**
There are Mystical Agriculture seeds for Thaumium and Void Metal, though Brass Seeds (correspondent to Alchemical Brass) are disabled. It would be helpful for mass production of Alchemical Brass for such seeds to be enabled (if at all possible)

**Comment by NillerMedDild** [comment]
I want the user to automate Alchemical Brass the "correct" way, so I'm afraid I will not be enabling the seeds.
