### ISSUE TITLE
[1.59, 1.59a] Import into MultiMC Issue

### ISSUE THREAD

**Issue by WittyWhiscash** [NillerMedDild/Enigmatica2Expert#1035]
**Modpack version**
1.59, 1.59a

**Can the issue be reproduced?**
Yes

**Issue**
Attempting to import pack zips 1.59 and 1.59a in MultiMC fails to import with the error "*Archive does not contain a recognized modpack type*"

![image](https://user-images.githubusercontent.com/21300678/55180488-557c8180-514f-11e9-86db-e5c9cb57fe8e.png)

**Comment by NillerMedDild** [comment]
May I have a direct download link to the files you used please?

**Comment by WittyWhiscash** [comment]
[Enigmatica2Expert-1.59.zip](https://github.com/NillerMedDild/Enigmatica2Expert/files/3019565/Enigmatica2Expert-1.59.zip)
[Enigmatica2Expert-1.59a.zip](https://github.com/NillerMedDild/Enigmatica2Expert/files/3019566/Enigmatica2Expert-1.59a.zip)

**Comment by NillerMedDild** [comment]
You cannot import those zips into MultiMC, you need the CurseForge manifest.
