### ISSUE TITLE
Crash due to problem with block rendering

### ISSUE THREAD

**Issue by dnarik** [NillerMedDild/Enigmatica2Expert#1036]
**Modpack version**
1.58

**Can the issue be reproduced?**
Yes

**Logs**
https://pastebin.com/W3gEbUtq

**Issue**
"LLC (or smth) has detected a problem rendering a block" and then, after a few seconds, game crashes. Tried using the same world with a new copy of modpack - didn't help. Quite a long time ago had problems with rendering sand in the TiC smeltery - I dumped a bunch in there, and it didn't all smelt due to insufficient fluid capacity of my smeltery, and after that sand started glithcing inside the smeltery (both the smeltery interface and, you know, The Smeltery), but it didn't affect anthing, so I was, like "nah, whatever".

**!!P.S.!!** I've seen an issue of "coduaha", and I WAS crafting Mekanism tanks, and my Crafting Table from TiC does not render when the world loads, but it still crashes afterwards, presumeably because Mekanism tank is render in the crafting grid on the Crafting Table. Should I just delete the crafting table via WorldEdit?

**Comment by NillerMedDild** [comment]
I recommend that you try updating to 1.59a first, but if that doesn't work, yes delete the Crafting Station :)
Please let me know how it works out.

**Comment by dnarik** [comment]
Sorry for a stupid quextion, but is there an easy way to update using MultiMC? Or my only option is downloading 1.95a and copying my world? Will I then lose my JourneyMap markers? I remember that being an issue

**Comment by dnarik** [comment]
Updating fixed the issue - now Basic Fluid Tank from Mekanica is just a purply-black cube on a Crafting Station. Had to restore my settings manually tho - kinda sucks

**Comment by NillerMedDild** [comment]
You can just move the new config, mods and script folders into your old instance, after deleting the old versions of those folders.
