### ISSUE TITLE
Three issues

### ISSUE THREAD

**Issue by dnarik** [NillerMedDild/Enigmatica2Expert#1038]
1.59a
So, first issue is that you can make steel in NuclearCraft Alloy Furnace, allowing you to skip the Blast Furnace, but maybe it's intended.

Second issue is that you can get infinite sulfur from one piece of coal. I guess, you use power to do it, but it just doesn't feel right - squeezing it over and over again. You have to put coal in a pulveriser, then Pulverized Coal into Magma Crucible, put the Liquifacted Coal into TiC smeltery and you got your coal back.

The final issue is quite minor - there are two kinds of Uranium 238, one from IC2 and the other from NuclearCraft, but IC2 Uranium238 is ingotUranium, and NuclearCraft Uranium238 is ingotUranium238. So, basically, they are called the same, but are completely different in terms of oredictionary

**Comment by NillerMedDild** [comment]
All of those things are known and intended :)
