### ISSUE TITLE
Mekanism Enrichment Chamber Quest Line #938?

### ISSUE THREAD

**Issue by gzcwnk** [NillerMedDild/Enigmatica2Expert#1039]
**Modpack version**
1.58 multiplayer

**Can the issue be reproduced?**
 /unknown

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Issue**
Input short description of the issue here

enrichment chamber not detected in quests on multiplayer server, as per other closed issues, problem not fixed?

If this is a feature request, feel free to delete the template.

**Comment by gzcwnk** [comment]
Quest says 0/1 so why the zero? shouldnt it be 1/1?  (actually I made 2 to try so it should be 1/2?)  Also re-positioned chamber, no change

**Comment by NillerMedDild** [comment]
Update and run the quest update command `/bq_admin default load`
And use the search function, this is like the 6th duplicate issue.

**Comment by gzcwnk** [comment]
Tried using the search function get no returns

**Comment by NillerMedDild** [comment]
You need to look at closed issues too.

**Comment by gzcwnk** [comment]
Have done I see nothing that looks right, also why is it closed if there is still an issue?

**Comment by NillerMedDild** [comment]
My search finds several related issues. It's closed because the issue is fixed, you just haven't updated the modpack.
