### ISSUE TITLE
Bug on quests

### ISSUE THREAD

**Issue by SrBiscoito** [NillerMedDild/Enigmatica2Expert#1041]
**Modpack version**
1.59a

Hello, I wanted to report a bug (I do not know if it's really a bug), but it's like this:
When I get the loot chest of reward from the quest and I'm going to open it. Only loot dungeon comes, not another loot, this is a very sad thing, happened also in version 1.58. If it is a bug please fix it. Thank you 👍

**Comment by NillerMedDild** [comment]
Use the command "/bqs_loot default load" :)

**Comment by SrBiscoito** [comment]
Thank you very much
