### ISSUE TITLE
Unable to craft creative builders wand

### ISSUE THREAD

**Issue by koolcat23** [NillerMedDild/Enigmatica2Expert#1043]
**Modpack version**
1.59a

**Can the issue be reproduced?**
Yes

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Issue**
When I go to craft the creative wand I can place all the items in the crafting grid, the wand shows up in the output but when I click it to remove it the wand snaps back into the output and then dissapears without consuming the items used to craft.  When I remove and replace an item the creative wand appears again in the output.
![wand](https://user-images.githubusercontent.com/48005959/55272792-1187a900-5316-11e9-861c-903542539e6a.jpg)

**Comment by NillerMedDild** [comment]
Does a restart fix it? I cannot reproduce the issue sadly.

**Comment by NillerMedDild** [comment]
Tell you what, I'll just change the recipe entirely.

**Comment by ben-mkiv** [comment]
afaik the output is only invisible, try to pull it out of the output slot, that might work

**Comment by koolcat23** [comment]
tried that, just snaps back into the output

**Comment by NillerMedDild** [comment]
It works now :)

**Comment by md5i** [comment]
This appears to not be working again. Version 1.70. The unbreakable wand is not being accepted. This appears to be due to a metadata mismatch The recipe wants #12213/0, but the craftable ones are #12213/12, #12213/13, and #12213/14, respectively.

**Comment by md5i** [comment]
I've verified that Creative.z3 says <betterbuilderswands:wandunbreakable:12>, so I don't know why this wouldn't work.

**Comment by NillerMedDild** [comment]
Are you using an Extended Crafting Crafting table?

**Comment by md5i** [comment]
I am.

**Comment by NillerMedDild** [comment]
Dammit :P Do you happen to know if it worked on 1.69?

**Comment by md5i** [comment]
I still had a 1.69 instance sitting around, so I tried.  It worked there.

**Comment by NillerMedDild** [comment]
Thank you, I'll just downgrade Extended Crafting then.

**Comment by md5i** [comment]
Still buggy, I'm afraid.  In a very weird way, though.  I've uploaded a video deomonstrating the buggy behavior:
https://youtu.be/FIzkYHdWPJc

**Comment by md5i** [comment]
Just to be clear, this is from 1.71.

**Comment by koolcat23** [comment]
dude please make a new post rather than bumping a necro'ed one, I am getting spammed by notifications from this and cannot unsubscribe

**Comment by NillerMedDild** [comment]
Unsubscribe button is on the right under labels etc.
