### ISSUE TITLE
Modular Machines don't actually require a Blueprint

### ISSUE THREAD

**Issue by MaxNeedsSnacks** [NillerMedDild/Enigmatica2Expert#1046]
As it stands right now, the modular machines can just be built using Structure Previews in JEI and don't actually require their blueprint to function (even though there IS an option for that).

Is that intentional?

**Comment by NillerMedDild** [comment]
No that is not intentional :o I thought they required blueprints.

**Comment by MaxNeedsSnacks** [comment]
There is a config option that you can toggle on each machine for that, though, see for example

https://github.com/MaxNeedsSnacks/AdAstra/blob/48fd207d630b2ab137dcddee6756ba37f644009e/config/modularmachinery/machinery/molecular_transformer.json#L1-L5

**Comment by NillerMedDild** [comment]
Thanks for the info :D It doesn't matter much though to be honest, the structures are pretty expensive.

**Comment by MaxNeedsSnacks** [comment]
You're right, it just makes the blueprint recipes unneccessary ^^
