### ISSUE TITLE
Industrial Foregoing BlackHole Controller Dupe Bug

### ISSUE THREAD

**Issue by VerdExNeon** [NillerMedDild/Enigmatica2Expert#1048]
**Modpack version**
1.59a

**Can the issue be reproduced?**
Yes

**Logs**
N/A

**Issue**
Piping items into a Black Hole Controller from IF will replace whatever item is in the Blackhole Unit with the piped item.

https://imgur.com/a/sSIWrYn

**Comment by NillerMedDild** [comment]
The Black Hole Controller is currently being rewritten, so this will hopefully be fixed in the near-ish future :)
