### ISSUE TITLE
Ender Book CTD

### ISSUE THREAD

**Issue by Jestyr22** [NillerMedDild/Enigmatica2Expert#105]
#### Crash Report

https://hastebin.com/akawefegiv.sql

**Comment by PrinceOfAmber** [comment]
Is that crash long from when it first crashed, or from when you are now loading the world.

second question.  Do you recall if the waypoints were far away like thousands of blocks?  Im trying to think if this is related to loading unloaded chunks

**Comment by Jestyr22** [comment]
That's the crashlog from when I first crashed. There may be a different log for loading in the world, but I don't have it I'm afraid.
I don't think it was thousands of blocks, but far enough away that unloaded chunks is a possibility?
It isn't an issue any more, I loaded up a backlog, but if there's a fix it may help people in the future
