### ISSUE TITLE
Minecraft with lag

### ISSUE THREAD

**Issue by SrBiscoito** [NillerMedDild/Enigmatica2Expert#1050]
**Modpack version**
1.59

**Can the issue be reproduced?**
I think so

Please, I really want to play. If anyone knows some method of removing the lag I thank you very, very much. It keeps locking until one hour it stops responding and I unfortunately have to close it and open again

**Comment by NillerMedDild** [comment]
It sounds like you don't have enough RAM allocated to the game, 6GB is recommended.
