### ISSUE TITLE
Thermal Expansion JEI plugin not working

### ISSUE THREAD

**Issue by domi1819** [NillerMedDild/Enigmatica2Expert#1052]
**Modpack version**
1.59a

**Can the issue be reproduced?**
Yes

**Logs**
Not applicable

**Issue**
In 1.59 you cannot see any TE processing recipes in JEI. They appear as expected in 1.58.
Inside the machines, the "show recipe" area also doesn't exist.

Example:
![image](https://user-images.githubusercontent.com/1492543/55282563-6511eb00-5346-11e9-96a6-df0b8b3117a6.png)
(The tab is completely missing in 1.59)

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.
Kinda duplicate of #1045

**Comment by NillerMedDild** [comment]
Closing this and merging with #1024

**Comment by domi1819** [comment]
Turns out it's not the same issue. In this case it's a chain of bad mod interactions.

1) Building Gadgets 2.6.7 adds a Pulverizer recipe that need less energy than what's provided in one tick
2) Thermal Expansion rounds the processing time down to 0 ticks and passes that value to JEI
3) JEI doesn't like 0 ticks and disables the entire TE-JEI plugin

The recipe has been fixed in Building Gadgets 2.6.8.
