### ISSUE TITLE
Crash on boot. 

### ISSUE THREAD

**Issue by gzcwnk** [NillerMedDild/Enigmatica2Expert#1053]
**Modpack version**
1.59a 

**Can the issue be reproduced?**
Yes/no/unknown

yes

**Logs**
Input pastebin link to crash-report or latest log, if applicable

https://pastebin.com/VF7PT0RB

**Issue**
Input short description of the issue here

minecraft crashes while booting

If this is a feature request, feel free to delete the template.

**Comment by gzcwnk** [comment]
I am wondering if this is because I have an openGL GPU (Quadro K2000)  and not a directX one?   If it boots Ok game runs fine in single player but fails to join a multiplayer server after 3mins.

**Comment by NillerMedDild** [comment]
You need to allocate far more RAM. 6GB is recommended. You're also using outdated Java, you should switch to the jar launcher option in Twitch, found under Minecraft settings.

**Comment by gzcwnk** [comment]
Its the latest java installed on Friday and there are no new updates I just checked.

**Comment by NillerMedDild** [comment]
You're not using your latest java. As I said, you should switch to the jar launcher option in Twitch, found under Minecraft settings.
