### ISSUE TITLE
osmium compresser quest dont detect the item

### ISSUE THREAD

**Issue by niklas2233** [NillerMedDild/Enigmatica2Expert#1054]
**Modpack version**
Input version here
1.59a
**Can the issue be reproduced?**
Yes/no/unknown
yes
**Issue**
Input short description of the issue here
when you have the osmium compressor in the inventory the quest dont detect it
![2019-03-31_20 52 10](https://user-images.githubusercontent.com/33903786/55293445-f5a80400-53f6-11e9-8ca8-438f591d19d1.png)

**Comment by NillerMedDild** [comment]
Use the command "/bq_admin default load"
This was fixed in 1.59a
