### ISSUE TITLE
Astral sorcery starmetal ore not changing from iron ore

### ISSUE THREAD

**Issue by JustaRandom** [NillerMedDild/Enigmatica2Expert#1058]
**Modpack version**
1.59a

**Can the issue be reproduced?**
Yes tried different lens still persist

**Issue**
As the title describe the iron ore does not convert to starmetal ore.

The Floating crystal has access to sky and to make sure the lens and the ore as well. The lens specs are Size: 232 Purity: 87% Cutting: 62%. The chunk is loader and stayed next to the crystal to make sure for at least 2 minecraft days, just idling .
Tried to break and replace ore and lens still no change.

When spawn a crystal in creative it works but it is attuned so maybe it is a base crystal problem
Does anyone else has this problem or I must just find a new astral structure?

**Comment by NillerMedDild** [comment]
It's rare that a worldgen lens doesn't work, but it does happen occasionally.
You don't need a lens FYI, just link the crystal directly.

I think you should try to find a new one. Could you let me know whether that works out please?

**Comment by JustaRandom** [comment]
Ok so linking the crystal straight to the iron ore did not work.

Went to a different world gen structure and it worked with and without lens.

So few hypothesis since I did update from 1.58 to 1.59a maybe the crystal next to me bugged or finite amount of light in crystal? do not know.

It is perplexing.... anyway thanks for the quick answer.

**Comment by NillerMedDild** [comment]
Sure thing.
