### ISSUE TITLE
Can u bring your Modpack to Nitrado

### ISSUE THREAD

**Issue by dragonriderworld** [NillerMedDild/Enigmatica2Expert#106]
I want to make a server with my friends but im using Nitrado. The aklitz server is to expensive for me.
So would you pls bring the Modpack to Nitrado.

**Comment by dragonriderworld** [comment]
ANd on aklitz is no Enigmatica 2 Expert only the Enigmatica 2 server aviable

**Comment by NillerMedDild** [comment]
Did you check or did you just look at the short list?

**Comment by dragonriderworld** [comment]
short list??

**Comment by NillerMedDild** [comment]
Did you look at this list? https://www.akliz.net/modpacks
