### ISSUE TITLE
ExU2 creative mil cant be mined

### ISSUE THREAD

**Issue by ben-mkiv** [NillerMedDild/Enigmatica2Expert#1060]
**Modpack version**
1.59a

**Can the issue be reproduced?**
yes

**Issue**
The creative mil isnt harvestable, once placed it cant be mined, neither picked up with e.g. cardboard boxes

the pick im holding has chaotic mining level
![](https://i.imgur.com/KgUFQY9.png)

**Comment by MaxNeedsSnacks** [comment]
TODO:

The block hardness needs to be set to something other than -1 for this one.

See [IBlockDefinition](https://crafttweaker.readthedocs.io/en/latest/#Vanilla/Blocks/IBlockDefinition/#set-the-blocks-harvest-level)

**Comment by NillerMedDild** [comment]
XU2 has a config option to make it harvestable, but we already enabled that. Did you try with a XU2 wrench OP?

**Comment by ben-mkiv** [comment]
Just tried the wrench and it doesnt work either

**Comment by NillerMedDild** [comment]
Mkay, we'll have a look :)

**Comment by MaxNeedsSnacks** [comment]
Just made it breakable on the dev branch, see 5a8d7d3e

**Comment by NillerMedDild** [comment]
And that fix works? I'm a little surprised there isn't any added security tbh.

**Comment by MaxNeedsSnacks** [comment]
Well, making something "Unbreakable" isn't really much more than setting its hardness to -1 from what I recall

**Comment by NillerMedDild** [comment]
Changing it's hardness does nothing, we need the config to actually work.

**Comment by NillerMedDild** [comment]
https://github.com/rwtema/Extra-Utilities-2-Source/issues/308

**Comment by MaxNeedsSnacks** [comment]
Really? Damn, that sucks then
