### ISSUE TITLE
Certus quartz is cobalt mining level (7)

### ISSUE THREAD

**Issue by ofek256** [NillerMedDild/Enigmatica2Expert#1063]
**Modpack version**
1.59a
**Can the issue be reproduced?**
Most Likely

**Issue**
Can't advance to mining level 3 because copper can't dig certus quartz. Is this fixable in the game's config file somehow? Thanks.

If this is a feature request, feel free to delete the template.

**Comment by NillerMedDild** [comment]
Did you resolve your issue?

**Comment by ofek256** [comment]
> Did you resolve your issue?

My issue was stupidity... Charged is level 7 while regular is 2 and I tried to mine charged certus.

**Comment by NillerMedDild** [comment]
Happens :P
