### ISSUE TITLE
GenDustry recipes are gone from JEI, and none of the machines are craftable.

### ISSUE THREAD

**Issue by BattleNachos** [NillerMedDild/Enigmatica2Expert#1070]
1.59a

As the title says I cannot craft any GenDustry machine block (Labware, Mutatron, Industrial Apiary, DNA Extractor, Transposer, Replicator etc.) and JEI doesn't displays their recipes.

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by BattleNachos** [comment]
Is this one just me?  Maybe I need to reinstall?

**Comment by NillerMedDild** [comment]
I think so, so worth a shot :)

**Comment by BattleNachos** [comment]
I reinstalled.  It's fixed.  Sorry to bother you.

**Comment by NillerMedDild** [comment]
No worries, glad it's fixed :)
