### ISSUE TITLE
Can't get vanilla Mooshroom for peaceful rftools env controller upgrade

### ISSUE THREAD

**Issue by phlaxyr** [NillerMedDild/Enigmatica2Expert#1072]
**Modpack version**
1.58

**Issue**
I believe that there is no way to get a vanilla Mooshroom for the peaceful rftools environmental controller upgrade. There is no bait for vanilla Mooshrooms and I haven't seen any vanilla mooshrooms spawn in the mushroom biome; only Animania mooshrooms.

**Comment by NillerMedDild** [comment]
We'll make Mooshroom essence craftable, thanks for the report :)

**Comment by IC-SubiX** [comment]
I reloaded (via teleportation) the chunks a couple times and than they spawend. You might want to try that. ;)
