### ISSUE TITLE
Feature request Mekanism Chemical Infuser

### ISSUE THREAD

**Issue by IC-SubiX** [NillerMedDild/Enigmatica2Expert#1073]
**Feature request**

So if you insert the wrong gas by accident, you might have no idea to reset it. There is the “Gauge Dropper“ to clear gases, but not everyone knows that.
My idea is to add a tool-tip or an item information in NEI. That might also be an interesting tip for the loading screen.

greetings IC_SubiX

**Comment by NillerMedDild** [comment]
Good idea, I'll get that done :)
