### ISSUE TITLE
Horn of the Canopy using Slimy Leaves

### ISSUE THREAD

**Issue by triasinformatica-gabe** [NillerMedDild/Enigmatica2Expert#1074]
**Modpack version**
1.59a

**Can the issue be reproduced?**
Yes

**Logs**
Not applicable

**Issue**
When attempting to create the Horn of the Canopy using a Horn of the Wild (received as a quest reward, functioning item, no reason to assume it's different from a crafted version) and Tinker's Constuct's Slimy Leaves, the crafting is bugged.

**Observations**
- When crafting inventory 2x2 grid, no resulting item is shown.
- When crafting in workbench (using JEI's "Move Items" function or regular item placement) the resulting item "Horn of the Canopy" is rendered as output, but cannot be picked up. When shift+clicking it into you inventory, it appears in the player's inventory until interacted with or exiting the workbench, the item then disappears and the ingredients jump back to the crafting table.
- Tried the recipe with leaves from an Oak tree and then everything works as expected.

**Thoughts**
- This recipe does not work with Slimy Leaves? The recipe however states "Accepts any: treeLeaves", which Slimy Leaves are as well.
- This might be a mod interoperability issue and not related to this pack. If so, let me know and I'll create an issue in the Botania tracker. There's no issue present there.

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
It works just fine for me I'm afraid. Maybe a restart would've fixed it?

**Comment by triasinformatica-gabe** [comment]
I'm fine closing this since there are plenty of alternative ways of getting the item :)

Just some additional info:
- Just tested this in my updated (1.59a -> 1.60) server and several restarts, but the recipe stays broken.
- Also tested this is a fresh install of both 1.59a and 1.60 single player survival world and there it actually works with slimy leaves... weird.

Again, I'm fine leaving this closed since it's minor and just weird.
