### ISSUE TITLE
Creative gas tank recipe needs 512000/32000 tanks?

### ISSUE THREAD

**Issue by phlaxyr** [NillerMedDild/Enigmatica2Expert#1075]
**Modpack version**
1.58
**Can the issue be reproduced?**
Probably?

**Logs**
N/A
**Issue**
In JEI, the recipe for the creative gas tanks says that it needs a portable tank with 512000/32000 UU-Matter (even though a basic portable tank can only hold 32000)

**Comment by NillerMedDild** [comment]
That's odd. You need to upgrade the tank, but I'll see if I can fix it in JEI.
