### ISSUE TITLE
Pressing any key will move items up one row in inventory.

### ISSUE THREAD

**Issue by phshy0607** [NillerMedDild/Enigmatica2Expert#1076]
**Modpack version**
1.59a

**Can the issue be reproduced?**
Yes.

**Issue**
Sometimes pressing any key will move items up one row in inventory.
It happens 80% of the time I played. I don't know how to constantly reproduce it.
I've checked with key binding, found nothing.

Please help or at least give some clues, thank you.

**Comment by NillerMedDild** [comment]
https://github.com/Lothrazar/Cyclic/issues/972

**Comment by phshy0607** [comment]
FYI, I'm a Chinese user and it mostly happened when I had mandarin input method enabled. Currently my way of fixing this is switch back to English input method and do an alt+tab, everything will be fine then. And I haven't experience this issue on other modpacks.

**Comment by NillerMedDild** [comment]
I've experienced this with English input, but thank you for the extra info.
