### ISSUE TITLE
Botania Metals can't block cast from Tinkers

### ISSUE THREAD

**Issue by wb808tec** [NillerMedDild/Enigmatica2Expert#1077]
**Modpack version**
1.58

**Can the issue be reproduced?**
Yes

**Logs**

**Issue**
Bitania metals Mana Steel, Elementium, Terrasteel when malted aren't cast able into blocks from
Tinker Smeltery or Tinker I/O Smart Output. Feel free to ignore if this is intended. 

If this is a feature request, feel free to delete the template.

**Comment by NillerMedDild** [comment]
I'll get that fixed, thanks for the report :)
