### ISSUE TITLE
Infinity Drill has too low mining level

### ISSUE THREAD

**Issue by Fargoth8624** [NillerMedDild/Enigmatica2Expert#1079]
**Modpack version**
1.59a

**Can the issue be reproduced?**
Yes

**Issue**
Infinity Drill appears to have a mining level of 3, not enough to actually harvest emerald ore and others.

**Comment by MaxNeedsSnacks** [comment]
I just noticed uhm - The PR has never been merged into master, only dev.

**Comment by NillerMedDild** [comment]
Oh, Woops xD
