### ISSUE TITLE
Charged Draconium Block can be made using 0 RF

### ISSUE THREAD

**Issue by coledot** [NillerMedDild/Enigmatica2Expert#108]
#### Issue Description

Create a resonant-tier Energetic Infuser and put 4 Auxiliary Reception Coil augments into it. Charge the infuser to full power. Insert a block of draconium into the infuser. The infuser instantly charges the block and uses 0 RF in the process, instead of the expected 1 billion RF. The bug can be triggered with just 2 or 1 ARC augments as well. However, the infuser appears to actually use RF to charge the block if exactly 3 or 0 ARC augments are present.

Just a hunch: I think that because the ARC augments increase the power required (5x w/ 4 augments, according to the COFH wiki), and that the base power required is 1 billion, that the actual power needed ends up exceeding 4.29 billion (i.e. UINT32_MAX) and weird things happen as a result of the overflow. 

#### Modpack version (Do not use "latest")

1.26c

**Comment by NillerMedDild** [comment]
I've been unable to replicate this, but this is the second report of it, so I'll remove the recipe. Thank you :)
