### ISSUE TITLE
Cannot Download the pack

### ISSUE THREAD

**Issue by mthp1999** [NillerMedDild/Enigmatica2Expert#1080]
**Modpack version**
1.60

**Can the issue be reproduced?**
Yes

**Logs**

**Issue**
My current version of the pack will not even start to launch, wont even open the loading screen. So I tried to download a new version and it says missing dependency 275300. All happened when I updated from version 1.59a to 1.60

If this is a feature request, feel free to delete the template.

**Comment by MaxNeedsSnacks** [comment]
The problematic addon is Albedo, a dependency for Botania. Idk why it wouldn't download though.

**Comment by GoldenKeyboard** [comment]
Please try updating the pack to a new profile.

**Comment by mthp1999** [comment]
Updating to a new profile did fix it, and my issue with the pack not launching was due to the mod itemphysc which I added personally, so all good.
