### ISSUE TITLE
Astral Sorcery Lucerna Ritual Fails to prevent mob spawns

### ISSUE THREAD

**Issue by Riathel** [NillerMedDild/Enigmatica2Expert#1082]
**Modpack version**
1.60

**Can the issue be reproduced?**
unknown - reproduced in my own save, a testing world, and a newly created 1.60 world.

**Logs**
N/A

**Issue**
Astral Sorcery ritual with a Lucerna attuned gem does not prevent mob spawn.

**Comment by Meryl** [comment]
Can confirm, doesn't work for me either.

**Comment by MaxNeedsSnacks** [comment]
Confirmed on 1.59a, still need to update but I'm preeeetty sure it's also gonna be on 1.60, so yeah.

Probably an Astral Sorcery mod issue.

**Comment by Meryl** [comment]
> 
> 
> Confirmed on 1.59a, still need to update but I'm preeeetty sure it's also gonna be on 1.60, so yeah.
> 
> Probably an Astral Sorcery mod issue.

This might muddy the water a bit, but for me it was actually working fine on 1.59a and stopped working on 1.60..

**Comment by MaxNeedsSnacks** [comment]
Okay, quick question. Can you try cheating in a new Celestial Crystal that's bound to Lucerna?

**Comment by MaxNeedsSnacks** [comment]
Oh yeah and also the other thing that **might** fix it might be replacing the entire ritual multiblock (or at least the pedestal). I recall that being a fix for my Aevitas ritual not working

**Comment by Meryl** [comment]
Replacing the entire multiblock didn't really work, gonna try cheating in a new crystal now. Any way beyond just copying the entire NBT-tag over manually, from the existing crystal?

**Comment by Riathel** [comment]
I also tried with replacing the whole structure and using both kinds of attuned gems.

**Comment by NillerMedDild** [comment]
Can you guys get other rituals to work?

**Comment by MaxNeedsSnacks** [comment]
Well, my Aevitas WAS working after I replaced the entire multiblock structure *and* cheated in a new crystal, but it stopped working again a couple of minutes later.

**Comment by NillerMedDild** [comment]
Sounds like I need to report it, thanks for the confirmation.

**Comment by NillerMedDild** [comment]
@MaxNeedsSnacks could you answer Doomgulls question in the linked thread please? I haven't made the test setup yet.

**Comment by MaxNeedsSnacks** [comment]
Done (except for the screenshot)

**Comment by NillerMedDild** [comment]
Answer from the mod developer:

> A few things:

    Status effect rituals such as vicio and lucerna require at least 1 effect-tick to go off per tick to do their effect. Getting that one consistently might require a good amount of ritual acceleration, so i'll be changing that to allow for a more consistent effect without needing a lot of acceleration.
    Rituals do get weaker during daylight, as expected. So if an unaccelerated slows down to almost a complete halt during daytime does not mean it doesn't function anymore.

That being said, there are some reports suggesting that some tiles requiring a multiblock structure invalidate that structure eventhough there are no changes. As i'm still investigating that issue and cannot find a clear reason for it, i can't say more to that than it could be related.

**Comment by NillerMedDild** [comment]
Has this been resolved in version 1.61?
