### ISSUE TITLE
I think Ender IO is causing server lag on a singleplayer world 

### ISSUE THREAD

**Issue by Basedgod199** [NillerMedDild/Enigmatica2Expert#1083]
**Modpack version**
Version 1.60

**Can the issue be reproduced?**
unkown

**Logs**
n/a

**Issue**
Having weird server lag, except I'm playing on a singleplayer world. I installed laggoggles to see what was causing it, though i'm not entirely sure what to make of it (see screenshot)
I think it would be something to do with Ender IO as its value in the Event subscribers list is far higher than all the others combined. The lag first started happening around the time that i placed down a simple alloy furnace and simple sag mill. Can't be sure they're the cause as i've removed the blocks and the issue persists.

![2019-04-11_16 36 25](https://user-images.githubusercontent.com/32063145/56003250-93fb5b80-5c7a-11e9-94a8-bf7d7c88ec2f.png)

**Comment by NillerMedDild** [comment]
Do you use a lot of Ender IO cables? Does the issue persist if all Ender IO machines on the server are broken?

**Comment by Basedgod199** [comment]
So a lot of testing later, i've removed all enderio machines, and all enderio conduits, and the problem has since faded, i'll do a bit more testing to see if i can narrow down exactly what the issue was.

**Comment by Basedgod199** [comment]
Ok i think i've identified the cause. It appears to be a bad interaction with an extra utilities trash can, when it has a filter inside it. However its not always causing lag, it only happens when all the containers (see screenshot) are full, and there are no items that the filter will allow into the trash can.
Also the lag is significantly worse the more items in the filter, and I had multiple filters nested in the filter in the trash can. 


![2019-04-12_05 10 38](https://user-images.githubusercontent.com/32063145/56036484-cb512300-5ce1-11e9-91d5-03cb870a67a8.png)

**Comment by NillerMedDild** [comment]
I see, nice catch!
