### ISSUE TITLE
Automated User uncraftable

### ISSUE THREAD

**Issue by zapl** [NillerMedDild/Enigmatica2Expert#1084]
**Modpack version**
1.60

**Can the issue be reproduced?**
Yes, hopefully

**Logs**
if needed

**Issue**
The CC: Tweaked Turtle in the Cyclic Automated User recipe seems to have changed and is uncraftable now. The recipe demands a `computercraft:turtle` (id 11620/0) but the basic craftable turtle is now a `computercraft:turtle_expanded` (id 11621/0).

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.
