### ISSUE TITLE
Extended crafting Automation Interface doesn't detect table below

### ISSUE THREAD

**Issue by Lordkeren** [NillerMedDild/Enigmatica2Expert#1085]
**Modpack version**
1.60

**Can the issue be reproduced?**
think so

**Logs**
if needed

**Issue**
when place, Automation interface mark "x" the table spot with any crafting table, so is useless 

If this is a feature request, feel free to delete the template.

**Comment by jmarler** [comment]
I can confirm this as well. Existing tables are unaffected, but new tables show this behavior. Trying to see if I can find a workaround.

**Comment by jmarler** [comment]
Restarting the server did not fix the automation interface. I also created creative and survival single-player worlds which exhibited the same behavior.

**Comment by NillerMedDild** [comment]
Thanks for the report and confirmation, I reported the issue here: https://github.com/BlakeBr0/ExtendedCrafting/issues/64
