### ISSUE TITLE
Blood Magic Soul Fray debuff super short.

### ISSUE THREAD

**Issue by wb808tec** [NillerMedDild/Enigmatica2Expert#1086]
**Modpack version**
1.60

**Can the issue be reproduced?**
Yes

**Logs**
https://drive.google.com/file/d/19uwCvYxKklxIMc2e0f3MSIL5w6z0dS3_/view?usp=sharing

**Issue**
Soul fray seems really short, about a second or less.  Almost spamable.

If this is a feature request, feel free to delete the template.

**Comment by NillerMedDild** [comment]
You got the debuff from dying, right? Just making sure :P

**Comment by NillerMedDild** [comment]
Would you mind trying to reproduce the issue with only Blood Magic?

**Comment by wb808tec** [comment]
Minecraft + forge 14.23.5.2781 + BloodMagic 1.12.2-2.4.0-102 Soul Fray about 20 Seconds.

E2E Fresh world Soul Fray is also working properly. 

So I'm not sure, maybe I broke something during my update?

**Comment by NillerMedDild** [comment]
Thank you very much for checking.

Maybe your player has some kind of resistance to debuffs?
