### ISSUE TITLE
Keybinding For Fullscreen - Disabled Fullscreen Borderless by default, can be changed by the player

### ISSUE THREAD

**Issue by IC-SubiX** [NillerMedDild/Enigmatica2Expert#1089]
**Modpack version**
1.60
**Can the issue be reproduced?**
Yes

**Logs**
-/-

**Issue**
I wanted to open Wireless-Crafting-Terminal and instantly crashed (i opend it cuple times before, and nothing happend). It's even more strange, because ther is no crash file in the MC folder!
After a restart and i tryed to open WCT again. My hotkey is "<" on the german keybord its next to left shift. And that key got somehow bound to toggle Fullscreen after restart but in the options its not bound to any key... and it crashed again (no crash file).

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by gustavosouza1997** [comment]
Having a similar issue, when pressing '\','|' or '/' button (on a pt-br keyboard) while there is the option to write causes the game to enter/leave fullscreen mode. The keybind don't show as asigned in controls, I'm currently playing on a server with the 1.60 version, but the game don't crash/restart as happened to IC-SubiX.

**Comment by mvdstam** [comment]
Just wanted to check in and confirm this issue. Firing `KEY_PRESSED` events with keycodes `219` (meta/windows key) and/or `43` (backslash/pipe) causes the game to toggle fullscreen mode. Doesn't happen until after the main loading screen has completed.

Tested and reproduced on a fresh install of the modpack. No crashing here though, just the game switching to and from fullscreen mode.

**Comment by mvdstam** [comment]
I've found the issue. It's [this](https://github.com/NillerMedDild/Enigmatica2Expert/blob/master/config/fw.cfg#L26) line which causes the behaviour myself and @gustavosouza1997 are experiencing, and will likely effect @IC-SubiX as well.

## Workaround

In `config/fw.cfg`, set the `enableFullscreenWindowed` setting to `false`:

```
(..)

general {
    # Enable Fullscreen Windowed (replaces Minecraft Fullscreen)
    B:enableFullscreenWindowed=false

(..)
```

It seems to be a bug/known/unknown behaviour of the "Fullscreen-Windowed-Minecraft"-mod which causes this. Disabling the mod functionality with the above setting fixes these issues for now. As this is a client-side problem, server configs need not to be touched.

**Comment by NillerMedDild** [comment]
That's not a fix though, it's just disabling the mod.

**Comment by NillerMedDild** [comment]
But I guess that's the best option, thanks mvdstam  :)

**Comment by gustavosouza1997** [comment]
Sorry for reopening the thread, but seems like the 'Toggle Fullscreen' didn't have any key assigned to it by default, when I added a key (in my case I put it on 'F11') and the bug stopped. So there is no need to remove/disable the mod.

**Comment by NillerMedDild** [comment]
Cool :)

**Comment by IC-SubiX** [comment]
Thx for that info! :D
