### ISSUE TITLE
Universal Cables uncraftable

### ISSUE THREAD

**Issue by Babbie** [NillerMedDild/Enigmatica2Expert#109]
#### Issue Description
There seems to be no recipe at all for Advanced Universal Cable, Elite Universal Cable and Ultimate Universal Cable. Besides this, one of the ingredients for Basic Universal Cable (the Redstone-Iron Wiring) is uncraftable itself, making the Basic Universal Cable uncraftable as well.
#### Modpack version (Do not use "latest")
1.28

**Comment by NillerMedDild** [comment]
I made a lot of mistakes during the development of 1.28 it seems, update 1.29 should be available within 3 hours. Thank you for the report.

**Comment by Babbie** [comment]
Alright! Thanks for the speedy answer and fix.
