### ISSUE TITLE
Item Transport through Chunkborder

### ISSUE THREAD

**Issue by IC-SubiX** [NillerMedDild/Enigmatica2Expert#1090]
**Modpack version**
1.60 and earlier
**Can the issue be reproduced?**
Yes

**Logs**
-/-

**Issue**
Extra Utility and EnderIO item transport system seem to have big broblems to insert items into a drawer through a chunk border. It's not working at all! (the chunks are loaded via IC2 chunk loader, and also playerloaded)

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
![billede](https://user-images.githubusercontent.com/21295394/56096775-e0e66880-5eec-11e9-9a0d-ef76720438c4.png)
It works just fine for me.

**Comment by IC-SubiX** [comment]
Sorry for reopening, but i think you got that wrong. The Drawer has to touch the chunkborder, so no pipes run through it. I think i heard there is a problem with vanilla mc for chunk updating order. If the pipes ore conduits are connected throgh a border its just fine. But if its basicly inserting into a other chunk its not working.

**Comment by NillerMedDild** [comment]
Alright, I'll do another test :)

**Comment by NillerMedDild** [comment]
![billede](https://user-images.githubusercontent.com/21295394/56233229-e970a780-6082-11e9-8be7-ed4378d243b2.png)
It still works just fine. Is the above the correct setup?

**Comment by IC-SubiX** [comment]
Yes looks like it's the correct setup now. Strange... The last reason i could think of is my chunkborder is the border of the spawnchunks.
Anyway, it's easy to fix (move everything into one chunk) and hard to reproduce.
Thanks for investigating.

**Comment by NillerMedDild** [comment]
Sure thing.
