### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by IC-SubiX** [NillerMedDild/Enigmatica2Expert#1091]
**Feature request**

1. More endgame items e.g.(creative flux sponge from thaumcraft)
2. Usefull or fun (extra)-items ONLY aviable with UU matter. (e.g. IC2 p2p tunnel)
3. resetable consuming quests to get loot chests (e.g. ultimate ingot = loot chest)
4. Is it posible to add new fusion fuels? it would be amazing to be able to create more rf/t. I would use UU matter and neutron fluid at a very high tempreture (you need a good cooling setup) to generate insane amount of rf.
5. Secrets like a 128^3 special storage cell with something in it. So the players could build a special pylon chamber to unlock it. (like the 1.7.10 FTB materials energy 4 map) This system is so underrated and would be so cool to add again. A reference to modmakers or youtubers and credits to you in the secrets would be super cool!

**Comment by NillerMedDild** [comment]
I'm sorry but I will not be working on this.
