### ISSUE TITLE
Advanced Rocketry space station not working

### ISSUE THREAD

**Issue by wased321** [NillerMedDild/Enigmatica2Expert#1096]
**Modpack version**
1.63a

**Can the issue be reproduced?**
unknown

**Logs**

**Issue**
Me and my friend cant get a space station to appear, we've done everything right but when we launch ourselves into space with the space station container, it doesn't appear. (we've also tried launching the container first and then launching ourselves but that doesn't work either)

I'm playing on MineWonderLand server MC version 1.12

**Comment by niklas2233** [comment]
1.63a isn't released yet?

**Comment by wased321** [comment]
oops, didn't see this was enigmatica 2 expert
