### ISSUE TITLE
Relog makes space station go back to earth

### ISSUE THREAD

**Issue by niklas2233** [NillerMedDild/Enigmatica2Expert#1097]
**Modpack version**
1.60

**Can the issue be reproduced?**
unknown

**Issue**
whenever i log out and back in on my singel player world my space station gets moved back to earth when i have moved it with the warp controller and it dosnt use any fuel to move to a different planet

**Comment by NillerMedDild** [comment]
The issue has been reported to the mod developer, thank you :)
