### ISSUE TITLE
Still will not start.

### ISSUE THREAD

**Issue by Chopper989** [NillerMedDild/Enigmatica2Expert#1098]
**Modpack version**
1.60

**Can the issue be reproduced?**
Yes

**Logs**
https://pastebin.com/ziKGHqjB

**Issue**
It will not start, even after reinstalling multiple times. I am using the twitch launcher. It randomly started happening.

**Comment by NillerMedDild** [comment]
Try setting Twitch to use your latest java:

Go to Twitch Settings > Minecraft settings, at the very bottom you can input additional java parameters, write `-version:1.8+`

Please let me know if that helps.

**Comment by Chopper989** [comment]
I tried this, and it still did not work. 
https://pastebin.com/WB4H8kvW

**Comment by Discomanco** [comment]
In that case you didn't do it correctly, because it still shows you as using Java 1.8.0_51 (the one Twitch ships)
