### ISSUE TITLE
[1.60] Mekanica jetpack

### ISSUE THREAD

**Issue by ManasCZ** [NillerMedDild/Enigmatica2Expert#1099]
**Modpack version**
1.60

**Can the issue be reproduced?**
Yes

**Logs**
https://pastebin.com/2TcPWJYN

**Issue**
After equipping the jetpack from Mekanica mod there is a problem with starting the game. Will you help me fix the problem please?

**Comment by NillerMedDild** [comment]
Deleting the options.txt file from your instance should do the trick :) Please let me know if it doesn't help.
