### ISSUE TITLE
Reinforced Cell Frame (Full) fluid transposer recipe not working

### ISSUE THREAD

**Issue by KitanaShaw** [NillerMedDild/Enigmatica2Expert#11]
#### Issue Description
trying to craft Reinforced Cell Frame (Full) with the fluid transposer recipe doesnt work 
here is a gif : https://i.imgur.com/u8sfa7b.gifv
#### What you expected to happen
to get the Reinforced Cell Frame (Full)
#### Modpack version (Do not use "latest")
1.07

**Comment by NillerMedDild** [comment]
You need to upgrade the Fluid Transposer, as it needs more energy capacity to craft the Reinforced Cell Frame (Full).

**Comment by KitanaShaw** [comment]
oh i didnt look at the energy derp
thanks for pointing it out xD

**Comment by NillerMedDild** [comment]
Sure thing, I'll add some text to make it clearer in the future :)
