### ISSUE TITLE
java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Boolean (Ice and Fire Dragon Client crash)

### ISSUE THREAD

**Issue by Babbie** [NillerMedDild/Enigmatica2Expert#110]
#### Issue Description
Client crashes when near a dragon corpse. Seems the Thaumcraft downgrade did not help...
#### Modpack version (Do not use "latest")
1.29
#### Crash Report
https://gist.github.com/Babbie/62993cc3139b67e8afe5a20a91944f9b

As a temporary fix, run these right after crashing TWICE (warning, this kills all dragons!):
/kill @e[type=iceandfire:firedragon]
/kill @e[type=iceandfire:icedragon]

**Comment by NillerMedDild** [comment]
I know :/ Downgrading Thaumcraft was the best of several awful options. The Thaumcraft dev is aware of the issue however, I'm hoping it'll be fixed soon.

**Comment by NillerMedDild** [comment]
Duplicate of #83
