### ISSUE TITLE
Items disappearing without dropping when mining

### ISSUE THREAD

**Issue by MayhemGang** [NillerMedDild/Enigmatica2Expert#1100]
1.60 to 1.58

**Can the issue be reproduced?**
unknown

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Issue**
I have no idea why, but when I started using other pickaxes, I noticed that the mining level was capped. So I went back to my normal tinkers pickaxe, but the blocks broken don't usually drop items. Like if I break a quartz block it doesn't drop me anything. It seems that it thinks the mining levels are broken, I have no idea.

If this is a feature request, feel free to delete the template.

**Comment by triasinformatica-gabe** [comment]
I just experienced the same issue when trying to remove Immersive Engineering Conveyor Belts with a Tinkers pickaxe/IE Hammer/IE Cutter thing/Empty hand.

I'm running modpack version 1.60; I'll check if it worked in my old local 1.59 setup and report back on it.
