### ISSUE TITLE
Quest book doesn't detect lead ore

### ISSUE THREAD

**Issue by lotsOfSnow** [NillerMedDild/Enigmatica2Expert#1101]
**Modpack version**
1.60

**Can the issue be reproduced?**
Yes/no/unknown
yes

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Issue**
Quest book does not detect that I have gathered lead ore, nor does it detect silver ore
@sorry, actually it lets me complete the quest once I clicked an item to claim but it still had 'Incomplete' under lead ore image

![gh](https://user-images.githubusercontent.com/28030565/56087926-9c6bb600-5e75-11e9-9394-6919684a2860.png)

**Comment by NillerMedDild** [comment]
Easy mistake to make TBH :)
