### ISSUE TITLE
architecture Craft in a /dank/null/MK IV crash minecraft on select

### ISSUE THREAD

**Issue by www2000** [NillerMedDild/Enigmatica2Expert#1103]
**Modpack version**
1.60

**Can the issue be reproduced?**
Yes

**Logs**
https://paste.ee/p/oe00h (log)
https://www100.zippyshare.com/v/sf1Qpo6u/file.html (world save)

**Issue**
Loading my save (see attachment) crashing minecraft.
I believe the problem lies in architecture Craft object is select in a /dank/null/MK IV

If this is a feature request, feel free to delete the template.

**Comment by NillerMedDild** [comment]
You are correct! You can either use NBTExplorer to edit the blocks out of your Dank/Null/, or just remove and re-add the mod. The issue has been reported to the mod dev.

**Comment by www2000** [comment]
Thanks can i get the link to the bugreport?

**Comment by NillerMedDild** [comment]
Here you go: https://github.com/p455w0rd/DankNull/issues/155
