### ISSUE TITLE
Mekanism DMiner has hard time with Tin in the Deep Dark

### ISSUE THREAD

**Issue by metnavman** [NillerMedDild/Enigmatica2Expert#1104]
**Modpack version**
1.59a

**Can the issue be reproduced?**
Yes/

**Issue**
Digital Miner doesn't seem to like mining for Tin in the Deep Dark. Attempting to set the Radius causes it to fail to register any of the ore, but only for Tin. Dropping the Radius down to "25" from "32" works sometimes, other times, the Radius has to get dropped down to "18" or "15" or lower. At that point, it will find and mine the Tin, but anything over a specific number towards max, and it completely fails to find it. Only Tin though....

**Comment by NillerMedDild** [comment]
Could you try with oreCopper as well please? :)

**Comment by metnavman** [comment]
Hiya! oreCopper works perfectly. I actually didn't notice the issue until the Miner only pulled Copper and Iron, while skipping Tin completely when set to the "32" radius. That's what led me to the initial troubleshooting.

**Comment by NillerMedDild** [comment]
Could you provide screenshots of the DM's configuration please? :)

**Comment by metnavman** [comment]
https://imgur.com/a/d9yTb0c

It's very strange. I'd expect it to have the opposite problem, where it doesn't find Tin when you shrink the Radius, instead of pushing the Radius higher. I don't get it!

**Comment by NillerMedDild** [comment]
Linking for good meassure: https://github.com/mekanism-mod/Mekanism/issues/5398

**Comment by NillerMedDild** [comment]
I have no idea what to do here :P

**Comment by xerses007** [comment]
Having the same issue, for me the range doesn't seem to affect it, i can still get tin using oredict for ore* but not oreTin or oreT*. searching by modID for thermal foundation also gets tin alongside all the other ores. This had previously worked before updating to 1.59a

**Comment by metnavman** [comment]
Ca

**Comment by xerses007** [comment]
So I've done some more testing and the issue occurs when there's a thermal foundation oil shale block within the search range of the miner (still can't reproduce this in the overworld though)

**Comment by NillerMedDild** [comment]
Do you happen to know if the issue persists on version 1.63a?

**Comment by xerses007** [comment]
Haven't had a chance to update yet, might get around to it this weekend
though. Will let you know when I do.

**Comment by NillerMedDild** [comment]
I was able to reproduce this issue, but only with `oreCopper`

**Comment by Frikkle** [comment]
I just tried to replicate this issue on 1.64d with a Digital Miner in the Deep Dark using the following filters:

- `*ore*`
- `*oreTin*`
- `oreTin`
- `*oreT*`
- `oreCopper`
- `*oreCopper*`
- `*oreC*`

All of them result in it mining the ores I expect.

**Comment by NillerMedDild** [comment]
Fingers crossed that it was fixed for reals then!

**Comment by Frikkle** [comment]
If there's anything else to test or try, let me know :)
