### ISSUE TITLE
ender io and thermal dynamics energy cables incompatibility 

### ISSUE THREAD

**Issue by niklas2233** [NillerMedDild/Enigmatica2Expert#1105]
**Modpack version**
1.60

**Can the issue be reproduced?**
unknown

**Issue**
check image. they dont connect after update

![2019-04-14_21 28 49](https://user-images.githubusercontent.com/33903786/56098650-a982b680-5f02-11e9-8e8f-2ca3f5f71618.png)

**Comment by NillerMedDild** [comment]
Ender IO no longer has RF support I believe, which causes this.
