### ISSUE TITLE
Crashing when breaking EnderIO machines

### ISSUE THREAD

**Issue by MrLaney360** [NillerMedDild/Enigmatica2Expert#1108]
**Modpack version**
1.60

**Can the issue be reproduced?**
Yes

**Logs**
https://pastebin.com/M80uAY2F

**Issue**
Breaking EnderIO machines with either a pick or the Yeta Wrench causes the game to crash

**Comment by NillerMedDild** [comment]
Take off your Magnet good sir :) Known issue, will be fixed soon.
