### ISSUE TITLE
Extended Crafting Automation Interface Not Recognizing Table

### ISSUE THREAD

**Issue by blichte1** [NillerMedDild/Enigmatica2Expert#1109]
**Modpack version**
1.60

**Can the issue be reproduced?**
Yes

**Logs**
NA

**Issue**
(Not only an issue but also solved) When attempting to automate extended crafting tables using the mod's automation interface, the interface fails to recognize the associated table... Even in a fresh world. I replaced the mod with the latest update and the issue was resolved.

**Comment by NillerMedDild** [comment]
I know, I reported the issue myself :P it's fixed in version 1.61, which has been out for two days.
