### ISSUE TITLE
Mekanism crash

### ISSUE THREAD

**Issue by omia** [NillerMedDild/Enigmatica2Expert#1110]
**Modpack version**
1.61

**Can the issue be reproduced?**
yes

**Logs**
https://pastebin.com/pqRK3KsG

**Issue**
Mekanism null pointer exception
--> fixed in Mekanism-1.12.2-9.7.1.371.jar
(https://minecraft.curseforge.com/projects/mekanism/files/2699534)

**Comment by NillerMedDild** [comment]
Thanks for the report :)

**Comment by NillerMedDild** [comment]
Can you avoid this crash, or would a hotfix be nice?

**Comment by omia** [comment]
I can't start the World anymore because it crashes instantaneously.
I tried updating Mekanism on my own but then strange things happened(like some items aren't craftable anymore), so a fix would be nice.

**Comment by NillerMedDild** [comment]
Mkay, fixing it now.
