### ISSUE TITLE
Crafted AE2 Seeds are not accepted by Enrichment Chamber or Phytogenic Insolator

### ISSUE THREAD

**Issue by bluebuiy** [NillerMedDild/Enigmatica2Expert#1114]
**Modpack version**
1.60

**Can the issue be reproduced?**
unknown

**Logs**

**Issue**
Crafted Certus Quartz Seeds, Nether Quartz Seeds, and Fluix Seeds are not accepted by the enrichment chamber.  When they are put in manually, they are returned to inventory when ui is closed.  However, seeds that are spawned in through jei work fine.  Seeds that are spawned through jei do not stack with crafted seeds (they stack, but when ui is closed they become unstacked).  

This behavior does not happen in a single player world.

We just upgraded our server to 1.60 from 1.50a

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by bluebuiy** [comment]
Dropping the crafted seed on the ground causes it to stack like the spawned in ones.  Makes it difficult to see if the nbt data is messed up.

**Comment by bluebuiy** [comment]
May be related:
https://github.com/mekanism-mod/Mekanism/issues/5241

**Comment by NillerMedDild** [comment]
I believe it is yes.
