### ISSUE TITLE
Flux Plug not sending power

### ISSUE THREAD

**Issue by Fikibreaker** [NillerMedDild/Enigmatica2Expert#1115]
**Modpack version**
1.62
**Can the issue be reproduced?**
Dont know

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Issue**
I just updated from 1.59a to 1.62.

My Flux Plug from my power storage isnt outputing any power to the flux points.

If this is a feature request, feel free to delete the template.

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by Fikibreaker** [comment]
The current system I have is Solar Panels on Flux Plugs sending power on a yellow channel to a Mekanism Induction Matrix which is then sending it on a red channel to wherever I need it. 

As I logged on my Personal Nano Bot Beacon was not working due to not receiving power. 
I thought it was the induction matrix acting funny so I assembled a draconic energy core and it worked for a couple of minutes then went back to not sending power.

**Comment by MaxNeedsSnacks** [comment]
Do you have any Modular Machinery inputs connected to your Flux Network by any chance?

There was (probably, we still don't 100% know) an issue with a Modular Machinery update so players updating from 1.58 or older might need to replace any Energy Input Hatches they had on their modular machines (see #973).

This isn't a 100% for-sure fix, but it may be worth a try ^^

**Comment by Fikibreaker** [comment]
I did have that yea. Will check.

**Comment by Fikibreaker** [comment]
I broke and replaced all the energy input hatches and it fixed my problems.
Thanks!

Also one note can you increase the power input on the normal energy input
hatch to more than 100kRf/t because the compact machines struggle to get
enough power to craft.

Thanks again!

**Comment by NillerMedDild** [comment]
It already is 1.000.000RF/t.
