### ISSUE TITLE
IC2 Universal Cable not connecting.

### ISSUE THREAD

**Issue by TParish96** [NillerMedDild/Enigmatica2Expert#1116]
**Modpack version**
Version 1.62 (Stock no config changes)
![2019-04-18_00 37 22](https://user-images.githubusercontent.com/49725315/56299019-5dd64400-6172-11e9-91f9-31801cc62012.png)

**Can the issue be reproduced?**
unknown

**Logs**
N/A

**Issue**
IC2 Machines, in this case the Metal Former won't connect to Advanced Universal Cable, They appear to but as soon as they draw any power it immediately disconnects and stays disconnected unless you relaunch and the same loop happens. Replacing cable does nothing neither replacing machine. AE2 recognises and uses the IC2 machine.

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by MirrorImageQS** [comment]
Adding to this, I have seen this happen over the past several versions (at least 1.57, but I think earlier). Usually, I have to restart the entire client to get them to fix (exiting to main menu and reloading doesn't work). Breaking and re-placing either the machines or the cables doesn't fix it.

I have also seen this happen with IC2's own cables as well. I don't know that it's necessarily the Mekanism / IC2 cables at issue, because I've got MFSUs directly pointed at my IC2 machines, and when this happens, the machines stop drawing power from the full MFSUs as well. They'll run down their internal buffers, but then they're entirely stop accepting energy. When it happens, it applies to all IC2 machines, not just any one particular one.

Anecdotally, this seems to happen after some sort of major lag spike that causes my player to stop ticking (can't interact with any machines, my Time in a Bottle stops ticking up, etc.). I have no insight into what causes that spike, and it may be entirely unrelated, but there is an open bug on the IC2 bug tracker that has what I describe with IC2 cables, and it was opened back in February: https://bt.industrial-craft.net/view.php?id=2490

If I come up with any more information, I'll add it, but I think this is an IC2 issue, not a Mekanism issue.

**Comment by NillerMedDild** [comment]
I agree. Could you check if the bug occurs after travelling between dimensions?

**Comment by dmansdminer** [comment]
I've had the same experiences as MirrorImageQS.  For some more anectodal information, I've noticed it consistently happens after an extended period of time in-game (IE a couple of hours).  Whether I afk for a while or am active, eventually I find my IC2 machines unpowered and my crafting comes to a halt.  The only solution is restarting the client fully.

**Comment by MirrorImageQS** [comment]
> 
> 
> I agree. Could you check if the bug occurs after travelling between dimensions?

Travel to the Nether, End, or Twilight Forest via their respective portals does not seem to trigger the bug on their own. I also tried the Moon, Mercury, Mars, Stella, and Kepler 0119 via my RF Tools Matter Transporter, and did not recreate it there either.

**Comment by TParish96** [comment]
I think the IC2 machines are broken, I put an IC2 generator next to a macerator and it won't take power. the macerator won't connect to IC2 cables either! bloody IC2 is an old broken mod...

I can confirm with testing that a full client restart appears to temporarily fix the issue. I also have experienced the issue forming after hours of being in game. 

I don't clearly understand why it happens after a long time in game and what closing the client vs going to menu screen would do?

**Comment by MirrorImageQS** [comment]
Think I just found something. The bug might be triggered by exiting an entire world and re-entering it. That could help explain why "a long time" causes this to happen, as that might imply a session with a brief return to main menu at some point for some reason, and would also explain why a full client restart is required to fix.

Doing more research. Will update when I have some steps. This definitely makes it an IC2 issue I believe though.

**Comment by TParish96** [comment]
@MirrorImageQS I haven't been to The End yet and I have the same issues.

**Comment by MirrorImageQS** [comment]
Are you at least able to recreate the issue by save/quitting and re-entering your world? If we can at least confirm that that's the trigger, it's a starting point.

**Comment by TParish96** [comment]
confirmed, I was playing for a while like 2 hours, went to the main menu while I went to dinner came back 2 hours later logged in played for an hour then went to use IC2 machine and it was disconnected...

Relaunching full game engine fixed it. What does full game engine launch do vs the main menu?

**Comment by MirrorImageQS** [comment]
At risk of going technical here, my theory is that IC2 wasn't written to account for the possibility of the "Unloaded world" issue (which I believe was a reasonable assumption, but that's another conversation). Basically, it means your game client is trying to run two game worlds at the same time, or at least parts of that second world that refused to shut down when you quit back to the main menu.

Something with how IC2 was written means it's not running all of its code against the correct world. In this context, the "Unloaded world" is receiving the calls to connect cables and make the machines interact with other blocks, while the "loaded world" (the one you are actually in) doesn't get those updates, and they stay disconnected.

When you do a full reboot of the game, exiting the client finally makes that Unloaded world close out completely. When you launch your world after that, it's now the only world running in that instance of your client, so the calls go to the expected place.

**Comment by TParish96** [comment]
yeah I understand you. I assume IC2 was written in the Modding Minecraft caveman ages and is barely updated since. If its so broken / old and incompatible why don't modpacks start removing / finding alternatives for it.

**Comment by MirrorImageQS** [comment]
Think I'm on to something. Looks like this might be related to shenanigans with how Applied Energistics chunk loads things. I've now got a test world that has this issue, I just need to refine down the minimum steps involved to recreate.

Short explanation of what I did was I set up an AE2 controller in one chunk, then connected it to an IC2 machine in an adjacent chunk with an interface, plus a handful of terminals, crafting CPUs, etc. to make a modicum of a "network". After setting that up, exiting and re-entering the world triggers the "wrong world in grid update" errors, and the cables begin misbehaving.

I stumbled upon this while researching how to optimize chunk loading for a sprawling AE system and came across this bug report, which is admittedly 4 years old and claims to be fixed, but the scenario it describes exactly matches the setup I used.
https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/1656

**Comment by MirrorImageQS** [comment]
I've got a little more information, but not enough to be conclusive yet. What I have determined is that once you save/quit a world that triggers this issue, any other world you join after that will have the issue, even if that world did not have the issue itself. I've been able to trigger the issue on the attached world, but I'm not sure what the precise steps were. However, if this gets forwarded along to the relevant dev teams, they might be able to debug it.
[Cable Test World 2.zip](https://github.com/NillerMedDild/Enigmatica2Expert/files/3110078/Cable.Test.World.2.zip)

There is a small setup around coordinate 550/80/230 containing an AE system. I've tried recreating that same system on other worlds, but that alone hasn't triggered the issue.

**Comment by valuial** [comment]
I don't think this is specifically AE related, in my current playthrough the bug happened before I set up AE at all.
It did occur the first time reasonably close to the first time I connected Mekanisms cables to the IC2 power grid.
As for dimensions: The only one I ever visited was the Nether - no End or planets, not even compact machines.

**Comment by draksterau** [comment]
IC2 doesn't appear to support world unloading, even though its a forge feature.
If a World unloads and reloads after a cable is placed it doesn't work.

**Comment by NillerMedDild** [comment]
I don't think IC2 will be getting any fixes sadly.

**Comment by Irgendwer01** [comment]
Its an issue how IC2 tries to get the world, it thinks that this world is wrong and unloads it to prevent issues and prevent any new energy connections in that world/dimension

**Comment by Bysokar** [comment]
IC2 Classic doesnt have the same issues. But it does have stricter requirements on its api to work properly. You could consider updating.

**Comment by Irgendwer01** [comment]
> 
> 
> IC2 Classic doesnt have the same issues. You could consider migrating. It isnt quite as widely supported though, for integrations. It has stricter API requirements.

@Bysokar Well, migrating wouldn't be the best since all IC2 progression would be gone for all players, scripts needed to be rewritten and the Universal Cables conversion would be gone which would mean **no RF to EU conversion**.

**Comment by Bysokar** [comment]
@Irgendwer01 Configuring universal cables to pull or push with the configurator thing works with IC2 Classic.

But yes youll lose progress.

IC2 is long dead.

**Comment by Porcy** [comment]
Ok, investigating the (same?) issue, with E2Eu and NuclearCraft this time. 
![NCWrongWorldGridUpdateSpam](https://github.com/EnigmaticaModpacks/Enigmatica2Expert/assets/8096340/d7c4a6e8-e136-4ef0-8b4e-cf2bb3311263)
And it also trigger the IC2 cables not connecting bug. All happens in compact machines dimensions and not in overworld. So, it's not specific to IC2. This started to happen after a power outage after restarting my server. But it doesn't go away after another restart.
