### ISSUE TITLE
Certain tinker weapons turn unusable after a couple of uses

### ISSUE THREAD

**Issue by EnderSam** [NillerMedDild/Enigmatica2Expert#112]
#### Issue Description

Tinker construct weapons will go from valid weapons to invalid when used in the main hand. I've lost two broadswords and my shuriken after using them in the main hand. The broadswords I lost when paired with the shuriken in my off hand trying to get fortune 3.

#### Modpack version (Do not use "latest")

version 1.29

**Comment by NillerMedDild** [comment]
https://github.com/PrinceOfAmber/Cyclic/issues/853

**Comment by Discomanco** [comment]
Fixed with version 1.30.
