### ISSUE TITLE
Difficulty Persistence Anomaly?

### ISSUE THREAD

**Issue by phlaxyr** [NillerMedDild/Enigmatica2Expert#1120]
**Modpack version**
1.58

**Can the issue be reproduced?**
Unknown

**Logs**
N/A

**Issue**
This is a really weird one.
So I first noticed this problem when I would keep coming back to my world with the difficulty being set to peaceful. I changed the difficulty back to hard; however, when I relogged, the difficulty would be reset back to peaceful. 
I tried locking the difficulty to hard; however, once I relogged, the difficulty would once again be set to peaceful, however this time it would be locked on peaceful.
Then I did the same on a test world (which was the second world that I had created). This one I had set to easy mode for a dragon fight. Lo and behold, if I tried changing the difficulty, if I relogged, it would reset to easy.
Then I created a third world (normal terrain generation). THis time it was locked to normal difficulty.
Then I created a fourth world (superflat). At first the difficulty was set at normal and seemed to stay there, so I thought that the problem was in the normal terrain generation. However once I set the difficulty to hard, the difficulty would stay there and would resist attempts to change it through relogging.

Finally, I created a fifth world (superflat). I was able to set the difficulty from normal to easy to normal to hard to peaceful to easy, with the difficulty persisting through relogs. 

After I had created his fifth world, all of the other worlds were fixed.

It seems that this anomaly affects an entire instance folder, and that
After the 5th world was created, everything went back to normal.

EDIT: aaand, things started to be weird for me again. I set the difficulty for world 2 from easy to normal, and that persisted. But that somehow caused the difficulty for world 1 to go from hard to normal. Suddenly, world 1 is stuck on normal.

(Also I see the irony between this and my previous issue report.)

**Comment by NillerMedDild** [comment]
I'll see if I can reproduce this :P

**Comment by NillerMedDild** [comment]
I errr.. can't.
