### ISSUE TITLE
Game crashes 

### ISSUE THREAD

**Issue by sinasystem** [NillerMedDild/Enigmatica2Expert#1121]
**Modpack version**
1.62

**Can the issue be reproduced?**
Yes

**Logs**
https://pastebin.com/Pk5Fjb1K

**Issue**
When I click the play button in launcher, the launcher closes and reopens after a couple of seconds with the game crash popup.

**Comment by NillerMedDild** [comment]
Why did you close the issue? :)

**Comment by sinasystem** [comment]
I just wanted to check if someone had this issue before :D
Forgot to reopen it!

**Comment by NillerMedDild** [comment]
Which launcher do you use?

**Comment by sinasystem** [comment]
I use Twitch client with native launcher.

**Comment by NillerMedDild** [comment]
Could you try re-installing and setting the launch method to jar please? The launch method can be changed under the Twitch Minecraft settings.

**Comment by sinasystem** [comment]
I get this error using jar launcher:

Error: Could not find or load main class c
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option PermSize=256m; support was removed in 8.0

**Comment by NillerMedDild** [comment]
It sounds like you don't have java installed, if installing java and using jar launcher doesn't fix your issues, please ask for support on the Discord linked above.

**Comment by sinasystem** [comment]
I unistalled java and installed the latest version of JRE 8 and it's fixed. Thanks for your help
