### ISSUE TITLE
Suggestion: Crafting Table Tweak

### ISSUE THREAD

**Issue by RegulusImpact99** [NillerMedDild/Enigmatica2Expert#1122]
I don't know what the mod is but there is one that lets you click on a button and it spreads items out in a 3x3 evenly in the crafting table. Would be helpful instead of having to click and drag everytime I want to 3x3 the same item.  For example turning nuggets into ingots

**Comment by NillerMedDild** [comment]
It's called Crafting Tweaks, and has been suggested many times. Please search for similar requests before opening new ones.
