### ISSUE TITLE
Thermal Expansion Cache not working properly when broken with pickaxe

### ISSUE THREAD

**Issue by keux00** [NillerMedDild/Enigmatica2Expert#1125]
**Modpack version**
1.60

**Can the issue be reproduced?**
Yes
**Logs**

**Issue**
I recently crafted a Cache (Basic) from Thermal Expansion, so i figured out if you input items and then break the block (Cache) it gives you the block but not the items that were inside, same goes to upgrades, got a Resonant Conversion applied to it and when i broke the block it gave me the Cache but in its Basic form, not Resonant. It didn't give me the Conversion item, so don't know what to use as a large storage for one item, of course, being cheap cause i wont craft much Black Hole Units because of their high cost.

Btw sorry if I have not expressed myself well because my main language isn't english.

EDIT: Don't know if this matters but i'm actually playing on a 1.60 server, not on singleplayer

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by MorganSimic** [comment]
I expierenced this behaviours aswell but i think it may be intended. The intended tool to pick them up is the Crescent Hammer. Shift +rightclicking a cache picks it up with all its contents and upgrades. I tried to find out real quick if you can even mine the cache under vanilla thermal conditions but couldn't come up with an answer.

**Comment by MorganSimic** [comment]
I'm dumb, found it CoFH/Feedback#1066. So you should not be able to mine them at all by normal means, wich means another mod is interfering. A guess would be Tool Progression assigning a harvest level to caches.

**Comment by MaxNeedsSnacks** [comment]
One way to make them unbreakable could be to set their hardness to -1 with CrT

**Comment by NillerMedDild** [comment]
Good call, let's do that. It will need a tooltip as well.

**Comment by MaxNeedsSnacks** [comment]
This may have to do with the "Material" settings in Tool Progression - I tried making the caches unbreakable with CrT but Tool Progression seems to override this

**Comment by NillerMedDild** [comment]
Unable to make the Cache unbreakable, added a tooltip instead.
