### ISSUE TITLE
Extra Cells 2 Gas storage seems to cause massive input lag in AE terminals

### ISSUE THREAD

**Issue by gregtaole** [NillerMedDild/Enigmatica2Expert#1126]
**Modpack version**
1.62

**Can the issue be reproduced?**
Unknown (I haven't tried to reproduce on a proper AE system yet)

**Issue**
I was playing around with the Extra Cells gas storage system but I noticed massive input lag whenever accessing AE terminals after finishing a setup with multiple import/export/storage buses. I tried disconnecting this particular setup from my network and the lag disappeared. Reconnecting it makes the lag come back.

I tried reproducing this in a creative world but only on a tiny system, but the issue didn't occur. I'll try to test this on a bigger system later.

**Comment by NillerMedDild** [comment]
Kinda tied to #235, Extra Cells is being rewritten ATM :)
