### ISSUE TITLE
crash on eating certain foods

### ISSUE THREAD

**Issue by ngdrex** [NillerMedDild/Enigmatica2Expert#1127]
**Modpack version**
1.62

**Can the issue be reproduced?**
Yes

**Logs**
Log 1: https://pastebin.com/GTmaN01m
Log 2: https://pastebin.com/Uxeuf9Ft
Log 3: https://pastebin.com/V6uXLmCL
Log 4 : https://pastebin.com/qsUPPkgc

**Issue**
so when i eat blue slime balls, raw chevron or one of the of the other raw animania meats (i dont remember which sorry) it causes a crash. ambrosia, raw chicken, and spider eyes do not crash the game though.

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by Frikkle** [comment]
I just ate some Raw Chevon, Raw Prime Chevon and the Blue slimeballs on modpack version 1.62 stock without changes. Cannot reproduce this issue.

**Comment by NillerMedDild** [comment]
Thank you @Frikkle !

**Comment by NillerMedDild** [comment]
I recommend a reinstall OP :)
