### ISSUE TITLE
Extra utilities 2

### ISSUE THREAD

**Issue by lithismh1** [NillerMedDild/Enigmatica2Expert#1128]
**Modpack version**
1.62

**Can the issue be reproduced?**
/unknown

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Issue**
Since the new update extra utilities 2 says grid power over loaded with only one machine on the system

If this is a feature request, feel free to delete the template.

**Comment by NillerMedDild** [comment]
Have you tried breaking and replacing the machine and GP producers? Please provide a screenshot of your GP as well.

**Comment by lithismh1** [comment]
I just went through and broke and replaced my gp producers.  I am still receiving the issue.
![2019-04-20_10 56 25](https://user-images.githubusercontent.com/49774429/56460709-d4826580-635b-11e9-80d6-af141a582ede.png)

**Comment by NillerMedDild** [comment]
May I see a screenshot of the overload as well please?

**Comment by lithismh1** [comment]
![2019-04-20_12 59 14](https://user-images.githubusercontent.com/49774429/56461715-34810800-636c-11e9-94aa-e82128460e11.png)

**Comment by NillerMedDild** [comment]
Well that sucks.
I think you should try to remove your Extra Utils data from the world:
Backup and then delete the file `saves\WorldName\data\XU2SaveData.dat`

**Comment by lithismh1** [comment]
I probally should have mentioned this early sorry but it is on a server would this be local or on the server?

**Comment by NillerMedDild** [comment]
No worries, it would be on the server.
