### ISSUE TITLE
Crash on Boot

### ISSUE THREAD

**Issue by SlimeTech** [NillerMedDild/Enigmatica2Expert#1129]
**Modpack version**
1.62

**Can the issue be reproduced?**
unknown

**Logs**
[https://pastebin.com/hVTZUYX9](https://pastebin.com/hVTZUYX9)

**Issue**
My game crashes mid-launch sometimes. I've looked into things to fix it based on the "failed to write core dump. minidumps are not enabled by default on client versions of windows" part of the error, but haven't been able to find anything that works, so I though it might be specific to this modpack. I'd really appreciate some help.

**Comment by NillerMedDild** [comment]
You're using outdated Java, set the Twitch launcher to use jar launcher instead.
