### ISSUE TITLE
IC2 Machines not Dropping with Tools

### ISSUE THREAD

**Issue by KingCookiee** [NillerMedDild/Enigmatica2Expert#1131]
**Modpack version**
1.62 (previously 1.59a)

**Can the issue be reproduced?**
Yes, single player and server wide

**Logs**
Not Applicable 

**Issue**
Simple enough IC2 machines do not drop without the wrench from the mod. The Mod Ignores the the config pasted below. https://imgur.com/a/K8f9K2E

If this is a feature request, feel free to delete the template.

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by MaxNeedsSnacks** [comment]
I can't seem to reproduce this on my instance. Anybody else have any luck?

**Comment by Tama1618** [comment]
I just updated to version 1.62 and I am having the same issue.

**Comment by Scorch-Mechanic** [comment]
I'm on 1.62 (singleplayer) and experiencing the same issue. I just confirmed in the mod configuration that the option is enabled. It simply doesn't work with, so far, my tinker's pickaxe (manyullun) nor a thaumium pickaxe.

**Comment by SjetCraft** [comment]
Can confirm issue in new worlds and existing worlds with modpack v. 1.62.

Issue did not go away when upgrading IC2 to version '2.8.112-122'.
Issue went away when I downgraded IC2 to '2.8.112'.

Apparently a new wrench was added to IC2 in version 2.8.113 which might be causing this bug.
`jenkins-IC2_112-113
New wrench and wrench functionality (estebes)`

**Comment by SjetCraft** [comment]
Can confirm issue when upgrading pack to v 1.63.
Using 'industrialcraft-2-2.8.133-ex112.jar'.
