### ISSUE TITLE
Invalid Craftings on Precision Assembler

### ISSUE THREAD

**Issue by gustavosouza1997** [NillerMedDild/Enigmatica2Expert#1132]
**Modpack version**
1.62

**Can the issue be reproduced?**
Yes

**Issue**
The Biome Changer and the Atmosphere Analyzer from Advanced Rocketry requires 5 items on the Precision Assembler, but the input hatch only accept 4 items.

Atmosphere Analyzer: https://i.imgur.com/ht35iSN.png
Biome Changer: https://i.imgur.com/esQpzJJ.png

If this is a feature request, feel free to delete the template.

**Comment by NillerMedDild** [comment]
You can place several input hatches in the multiblock.
