### ISSUE TITLE
Cant login to server (recipe error?)

### ISSUE THREAD

**Issue by Frexor** [NillerMedDild/Enigmatica2Expert#1133]
**Modpack version**
1.62 (update from 1.59a)

**Can the issue be reproduced?**
Yes

**Logs**
https://pastebin.com/y9LHa8F5
https://imgur.com/a/ML7LoA7

**Issue**
I update client and server to 1.62 from 1.59a, and cant log in. 
I also tried to delete all files and run clean server - no changes

**Comment by NillerMedDild** [comment]
Reinstall the client :)

**Comment by Frexor** [comment]
Thanks, nvm. Twitch had problems yesterday and he was improperly downloading some mods. Today everything is ok.

**Comment by NillerMedDild** [comment]
Great :)
