### ISSUE TITLE
Mecanica Fusion Reactor keeps turning off randomly

### ISSUE THREAD

**Issue by MayusYT** [NillerMedDild/Enigmatica2Expert#1136]
**Modpack version**
1.60

**Can the issue be reproduced?**
unknown

**Logs**
/

**Issue**
My Mecanica Reactor keeps turning off randomly. It has enough fuel and neither a injection rate of 6 does work, nor does 98,

The reactor is built within one chunk.
Other players on the same server, but different worlds do not experience this issue.

**Comment by NillerMedDild** [comment]
Can you reproduce this in 1.62?

**Comment by MayusYT** [comment]
Sorry, it turned out that it hadn't enough fuel but I couldn't notice that as it had enough fuel again every time I checked the reactor. I'm closing this now.
