### ISSUE TITLE
Error while updating

### ISSUE THREAD

**Issue by miscillo** [NillerMedDild/Enigmatica2Expert#1137]
**Modpack version**
1.60

**Can the issue be reproduced?**
Yes

**Issue**
When I try to update te pack from the twitch client, it starts downloading but suddenly stops and revert. After that it shows this message: _Unable to get Addon: CraftStudio API (268704) - File ID: 2661859_
![Annotazione 2019-04-22 022727](https://user-images.githubusercontent.com/6881110/56477472-351db980-64a6-11e9-816e-8d1a58b5d2d5.png)

**Comment by NillerMedDild** [comment]
This error usually fixes itself, could you please try again?

**Comment by Frikkle** [comment]
I've had this issue when updating from 1.59 to 1.60 and for me it seemed Twitch related. What I ended up doing is grabbing a backup from my personal files (journeymap and the like); doing a fresh install and pasting the personal files back in.

A lot of people on the public forums suggest to keep trying to update the modpack; every time it fails it will most likely fail on a different mod. Keep trying and eventually it pops through (source: https://www.reddit.com/r/feedthebeast/comments/67ahks/twitchcurse_app_mod_pack_downloading_error/)

**Comment by miscillo** [comment]
> This error usually fixes itself, could you please try again?

I've tried a lot in the last week, but always the same error result. Today worked and the update goes fine... so nevermind :D
Thank you all

**Comment by albintech1** [comment]
the modpack didnt work and this happend:Failed to download file, the file contents differ from what was expected.
Name: jopt-simple-5.0.3.jar
URL: https://libraries.minecraft.net/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
Filename on disk: jopt-simple-5.0.3.jar
Path: C:\Users\ALBIN\Twitch\Minecraft\Install\libraries\net\sf\jopt-simple\jopt-simple\5.0.3\jopt-simple-5.0.3.jar
Exists: File

**Comment by NillerMedDild** [comment]
Please don't attach your issue to an existing one, they're not the same. Try redownloading the pack, sounds like the Forge download messed up.
