### ISSUE TITLE
Cyclic Wireless Transmitter next to Redstone Tunnel in Compact Machine causes NullPointerException

### ISSUE THREAD

**Issue by Frikkle** [NillerMedDild/Enigmatica2Expert#1139]
**Modpack version**
1.62

**Can the issue be reproduced?**
unknown (and unable to test since client is bricked)

**Logs**
[here](https://pastebin.com/hcAbdY0T)

**Issue**
When inside a Compact Machine (5x5x5 in this case); having a Redstone Tunnel set to input mode (direction: top) and placing a Wireless Transmitter (from Cyclic) directly against it causes the client to crash and brick it. Every reconnect force quits the client afterwards when joining the server.

I already reported this [issue](https://github.com/thraaawn/CompactMachines/issues/390) in the CompactMachines Issue tracker but I want to have it here as well for future reference for others.

**Comment by NillerMedDild** [comment]
Thank you for the report.

**Comment by Frikkle** [comment]
Update: Cannot reproduce in SP local setup with only CompactMachines and Cyclic. Can reproduce on MP Enigmatica2Expert stock config.

Forked CompactMachines, fixed the NPE issues, compiled it and ran the result in Enigmatica2Expert 1.62 with success and no more crashes. About to create a pull request in Compact Machines.

**Comment by NillerMedDild** [comment]
Damn, sweet!

**Comment by Frikkle** [comment]
Let's hope they accept the PR. Fat chance other parts of the code should go through similar changes; but hey, I'll fix those when it crashes again ;-)

**Comment by Frikkle** [comment]
It's been accepted and merged; no release yet.

**Comment by MaxNeedsSnacks** [comment]
Currently waiting for the next release of CM3 that should fix this issue.
Awesome work by the way, Frikkle!

**Comment by Frikkle** [comment]
I'm also having a few other issues with CM; specifically with getting vanilla signals in and out of them. I could look into them if it makes people happy. Though I think I'm abandoning CMs for now and focus on actually playing E2E for a bit :)

**Comment by NillerMedDild** [comment]
Good idea :D
