### ISSUE TITLE
Broken things after updating.

### ISSUE THREAD

**Issue by Confluxes** [NillerMedDild/Enigmatica2Expert#114]
#### After updating the pack a bunch of the quests are now broken and just have nether stars as their icon. Also my shuriken is just some weird default thing that does 1 damage now as well. 

Edit: I've been trying to fix the quests with the commands to reset specific quests and it just ends up breaking even more quests.

#### Not a crash

Broken quests : https://gyazo.com/18f1fad9c5ccb2cea4bc2ecc227defdf

Shuriken before update : https://gyazo.com/39b4f6a9e8fec577d33d0131cc5badd7

Shuriken after update : https://gyazo.com/f3725a5f8c6efd3be560dd0e8950d5c2

**Comment by NillerMedDild** [comment]
Please make seperate issues for seperate issues.
Partly duplicate of #112 
The quest issue has been reported to BQ:
https://github.com/Funwayguy/BetterQuesting/issues/404

Using `/bq_admin default load` several times tends to fix the broken quests, you could also try reinstalling the pack.

**Comment by Confluxes** [comment]
Thanks and my bad on putting two issues in one post, I'll make sure to do separate posts in the future if anything else comes up.

**Comment by NillerMedDild** [comment]
Thank you :)
