### ISSUE TITLE
Crash while trying to put lapis through a enrichment factory

### ISSUE THREAD

**Issue by Mihnea229** [NillerMedDild/Enigmatica2Expert#1140]
**Modpack version**
1.62

**Can the issue be reproduced?**
Yes
**Logs**
https://pastebin.com/rXiAbNxk

**Issue**
I was trying to make lapis dust, so i tried putting lapis in a enrichemnt factory, and it crashed.

If this is a feature request, feel free to delete the template.

**Comment by NillerMedDild** [comment]
Does it happen every time?

**Comment by Frikkle** [comment]
Just tested this with both the Enrichtment Chamber and the Basic Enriching Factory (tier 1 factory); when putting in lapis or lapis blocks, nothing happens (as expected). When putting in Lapis ore it processes them into 12 lapis in both machines.

**Comment by NillerMedDild** [comment]
Thanks Frikkle :)

**Comment by MaxNeedsSnacks** [comment]
Can't reproduce this either, sorry. Might've been a one-off.
