### ISSUE TITLE
Compact Machines crash when changing its name.

### ISSUE THREAD

**Issue by Frikkle** [NillerMedDild/Enigmatica2Expert#1142]
**Modpack version**
1.62

**Can the issue be reproduced?**
Yes, in MP; SP is fine.

**Logs**
Server side logs [here](https://pastebin.com/qCa5tgXS).

**Issue**
An issue I did come across is that if you try to change the Compact Machine's name; and click the checkmark box, the server kicks you with a "Connection Lost. - A fatal error has occured, this connection is terminated" error. See attached server side logs.

This happens only in MP as far as I could determine.

**Comment by NillerMedDild** [comment]
Thanks for making a new issue about this :) I'll investigate as soon as I can.

**Comment by Frikkle** [comment]
No hurry; it's not severe. Just a server disconnect. No other players are affected and you can immediately connect again. Client does not crash; neither does the server.

**Comment by Frikkle** [comment]
Investigated this a little further; some notes:
- Clean Forge install with stock CM --> not reproducable. Name changing works as expected.
- On E2E it crashes my client; while @stefancdr on the same server cannot reproduce it.

**Comment by Frikkle** [comment]
I created a whole bunch of compact machines and tried reproducing this issue together with @stefancdr but to no avail. I think the issue can be closed, but it stay weird..

Some final remark:
- I now cannot get the name tag button (top right corner of the preview screen) to show at all.
- In stock Forge + CM the name tag button shows and works as expected.
- It seems the renaming of compact machines (via the interface button) is disabled completely.
