### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by Lordkeren** [NillerMedDild/Enigmatica2Expert#1143]
Add a recipe to the nuclearcraft melter that turns coagulated blood from tinkers into biomes blood for an easy pig iron automation (just like it has for purple slime), or even rotten flesh

**Comment by NillerMedDild** [comment]
Good idea.

**Comment by MaxNeedsSnacks** [comment]
The purple slime Melter recipe comes from regular NC, right? I feel like this should just be part of its regular integration then ^^

**Comment by MaxNeedsSnacks** [comment]
I think Rotten Flesh would be the better option here, since there *is no way* to get Coagulated Blood besides already having coagulated blood in the first place (plus this would be more in line with TCon's current smeltery recipes)
