### ISSUE TITLE
Cannot pickup storage drawer with cardboard box

### ISSUE THREAD

**Issue by Old-Man-D** [NillerMedDild/Enigmatica2Expert#1144]
**Modpack version**
1.62

**Can the issue be reproduced?**
Yes

**Logs**
no crash

**Issue**
I can no longer pickup storage drawer's using mekanism's cardboard boxes.  This worked in 1.59 under mekanica.

**Comment by Frikkle** [comment]
I can confirm that you cannot pick up Storage Drawers with a Cardboard box in 1.62.

**Comment by NillerMedDild** [comment]
I'm guessing this is intentional, since Storage Drawers has Packing Tape.
