### ISSUE TITLE
IC2 Quest Progression Bug: wrong type of cable accepted

### ISSUE THREAD

**Issue by stefancdr** [NillerMedDild/Enigmatica2Expert#1145]
**Modpack version**
1.62

**Can the issue be reproduced?**
Yes, both in SP and MP.

**Logs**
Not applicable.

**Issue**
IC2 BatBox, LV, MV, HV quests all list various types of 'insulated' cables to be required, but they all accept non-insulated cables. This might be the intended behavior, but then the quest listing should be amended to say that any tin/copper/gold/hv cable is accepted. Especially since triple-insulated cable requires quite a bit of rubber, this might not be the intended behaviour. I have tried adjusting the DefaultQuests.json file myself, setting the NBT type and insulation tag (for, in this case, HV) to 3b and 3b (as that's what 3x ins. cable seems to have according to JEI), but that did not fix the issue. It's probably an easy bug to fix, if you know your way around BetterQuesting (which I do not, yet). Thanks.

**Comment by Frikkle** [comment]
I can confirm this issue; debugged it together with @triasinformatica-stefan

**Comment by NillerMedDild** [comment]
I know, IC2 NBT data can be a bit wonky, it's an effort to ensure that the quests trigger with the minimum requirements. Disabling NBT fuzziness will prevent these quests from triggering on the correct items.
