### ISSUE TITLE
Creative Powercell Quest Text

### ISSUE THREAD

**Issue by MaxNeedsSnacks** [NillerMedDild/Enigmatica2Expert#1146]
Just noticed sth in Dire's E2E playthrough, the description of the Creative RFTools Powercell hasn't been updated yet. Might need confirmation, gonna go through the quests in a sec

**Comment by MorganSimic** [comment]
Just keep in mind, Dire doesn't run the latest version. Not sure wich version he runs but not the latest.

**Comment by MaxNeedsSnacks** [comment]
Yeah it's still currently on master tho so I should look into fixing that lol

**Comment by MaxNeedsSnacks** [comment]
@NillerMedDild how many rf/t was it again? 1MRF?
