### ISSUE TITLE
Optifine problem

### ISSUE THREAD

**Issue by kristu** [NillerMedDild/Enigmatica2Expert#115]
#### Issue Description
Game disconect when loggin, new world too, with OptiFine 1.12.2 HD U D3, works normal without.
 i play the game fine without problems until version 1.26, but after that i have this issue unfortunately.

#### Modpack version
1.30

**Comment by NillerMedDild** [comment]
May I see your `latest.log` please?

**Comment by kristu** [comment]
@NillerMedDild 

Sorry for the delay and thanks for the quick answer.
[latest.log](https://github.com/NillerMedDild/Enigmatica2Expert/files/2116927/latest.log)

**Comment by NillerMedDild** [comment]
There's nothing that really stands out in the log. Did you tab out while joining your world?

**Comment by Discomanco** [comment]
Seeing IC2 machines are the Error Texture on login is normal, even without Optifine. It just has that until the world has properly loaded in, which obviously doesn't happen if you get disconnected after the first few frames

**Comment by NillerMedDild** [comment]
Try reinstalling the instance, or just leave out Optifine :)

**Comment by Barhandar** [comment]
OptiFine_1.12.2_HD_U_D1 works.
