### ISSUE TITLE
Missing tinker's smeltery recipes for IC2's "purified" (washed in the IC2 ore washing machine) ores.

### ISSUE THREAD

**Issue by Scorch-Mechanic** [NillerMedDild/Enigmatica2Expert#1153]
**Modpack version**
1.62

**Can the issue be reproduced?**
Yes

**Issue**
As title. Can't melt purified crushed ores in the tinker's smeltery, even though the ordinary unpurified crushed ore smelts fine.

**Comment by NillerMedDild** [comment]
They can't be processed in a furnace can they?

**Comment by Scorch-Mechanic** [comment]
They do (I'm using an IC2 electric furnace), but it looks like they work in any furnace except the Tinker's Smeltery (or melter). It's only because I see the ordinary unwashed crushed ore has a smeltery recipe (along with the "pulverized" ores) that makes me think this is an oversight rather than a design choice. 

On April 26, 2019 9:59:37 PM PDT, "Niels Pilgaard Grøndahl" <notifications@github.com> wrote:
>They can't be processed in a furnace can they?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/NillerMedDild/Enigmatica2Expert/issues/1153#issuecomment-487255240

-- 
Sent from my cellphone.

**Comment by NillerMedDild** [comment]
We'll look into it :)

**Comment by NillerMedDild** [comment]
I don't have time to implement this, as you have probably guessed :P
