### ISSUE TITLE
Server crashes in twilight forest

### ISSUE THREAD

**Issue by CorenMajere** [NillerMedDild/Enigmatica2Expert#1155]
**Modpack version**
1.58

**Can the issue be reproduced?**
Yes

**Logs**
[crash report](https://pastebin.com/Cvjukht3)

**Issue**
I've had numerous hangs while exploring the Twilight Forest in single player, usually near hollow hills.  I originally thought I was just running into out-of-memory issues, but after killing the client on the most recent one, I noticed in the logs that the server was actually crashing with an error relating to swarm spiders (see pastebin link above for full crash report):

```
Description: Exception ticking world
 
java.lang.BootstrapMethodError: java.lang.IllegalAccessError: Class 'twilightforest.entity.EntityTFSwarmSpider' no access to: class 'net.minecraft.entity.ai.EntityAITasks$EntityAITaskEntry'
```

**Comment by NillerMedDild** [comment]
This issue is caused by the Java you're using. Switching to standard JRE fixes it.
