### ISSUE TITLE
Villager Market client crash upon interacting

### ISSUE THREAD

**Issue by Frikkle** [NillerMedDild/Enigmatica2Expert#1156]
**Modpack version**
1.62

**Can the issue be reproduced?**
Yes

**Logs**
[Here](https://pastebin.com/FpLJHSEF)

**Issue**
From a loot box I received a Villager Market; which I placed in a village and upon interacting with the market, the client crashed with attached log message. It crashed upon opening the block; it shows the interface for a few seconds (probably whilst loading the recipes that should be shown) before crashing.

**Comment by Frikkle** [comment]
Some additional information about villagers around:
- Machinist
- Sage
- Redstone Mechanic (multiple)
- Druid
- Armorer (multiple)
- Apiarist
- Structural Engineer
- Outfitter
- Electrician
- Jamguy

Maybe it's the case that one of these villager classes is implemented in such a way that they share their recipes between multiple instances of that village class. Whilst iterating through them something might break. Not sure though since I'm not too familiar with the implementation of the villagers.

**Comment by Frikkle** [comment]
Never mind; this might have been a timing issue or random one-off. The second time when interacting with the item (after a reload) everything works as expected.

However if someone would want to try reproduce this; that would be great.

**Comment by MaxNeedsSnacks** [comment]
This may actually not be a one-off, I remember crashing on an older version under pretty much the exact same circumstances

**Comment by Frikkle** [comment]
Hmm, in that case, here's exactly what I did:

1. Place the market down in my own base (with no villagers around). I did have a Cooking For Blockheads market near there; not sure if related. It's recipes didn't show up in the Villager Market.
2. Picked up the Villager Market and place it in the village.
3. Interacted with the Villager Market.

I'll try these steps again and see what happens.

**Comment by Frikkle** [comment]
While doing some trading and interacting a few times with the block (without picking it up and placing it down again) it crashed again. So there's definitely something fishy here...

**Comment by Frikkle** [comment]
Additionally I notice that when interacting with the market, it does not always correctly notice available items in your inventory. You then first have to put them in your hand so it will know the items are available for trade.

**Comment by NillerMedDild** [comment]
This is the second time I've heard about this issue, did any of the villagers trade Iron Ingots?

**Comment by Frikkle** [comment]
Yes, Iron Ingots are provided.

Here's a list of all the traded items provide by the villagers; (3x) denotes it's offered by three villagers:
- KuBaRa-Jam
- GraKiBa-Jam
- Common Shader Grabbag
- Cooked Fish (3x)
- Apple (3x)
- Beetroot (3x)
- Feather (3x)
- Seeds (3x)
- Poisonous Potato (3x)
- Mushroom (brown) (3x)
- Mushroom (red) (3x)
- Raw Beef (2x)
- Raw Rabbit (2x)
- Raw Chicken (2x)
- Copper Wire
- LV Wire Coil
- Treated Stick
- Treated Wood Scaffolding
- Balloon
- Iron Rod
- Steel Scaffolding
- Aluminium Scaffolding
- Steel Rod
- Slag
- Concrete
- Coal
- Iron Helmet
- **Iron Ingot**
- Iron Chestplate
- Diamond
- Diamond Chestplate
- Raw Fish
- Spider Eye
- Resonating Redstone Crystal (4x)
- Gunpowder
- Netherwart
- Bone
- Raw Mutton
- Padauk Wood Planks
- Red Spruce Sapling
- Wrench (extra utils)
- Coal Coke
- Engineer's Hammer
- Copper Ingot (immersive)
- Aluminium Ingot (immersive)
- Steel Mechanical Component
- Engineer's toolbox
- Waterwheel Segment
- Engineer's Blueprint: Projectiles
- Iron Drill Head
- Ear Defenders
- Steel Drill Head
- Engineer's Blueprint: Electrodes
- Mossy Comb
- Dripping Comb
- Silky Comb
- Frozen Comb
- Simmering Comb
- Stringy Comb
-

**Comment by valuial** [comment]
I do remember having that crash back in 1.59a.
Also placed the market in my base first (blockheads market also present), broke it and placed it in the village.
First time accessing it there I got the crash.
Reloaded the world and it was fine since.

I'm not sure if it is related, but before the crash, MineCraft was running (in the Title screen, I believe) for several hours (didn't want to wait for all the mods to load when coming home).

**Comment by NillerMedDild** [comment]
I was not able to reproduce this issue by any means.
