### ISSUE TITLE
Crash on Load

### ISSUE THREAD

**Issue by sylviapossenau** [NillerMedDild/Enigmatica2Expert#1158]
**Modpack version**
1.62

**Can the issue be reproduced?**
unknown

**Logs**
Description: Initializing game
 
java.lang.RuntimeException: java.lang.RuntimeException: java.lang.IllegalStateException: Corrupted loading model stack: appliedenergistics2:item/facade_base != appliedenergistics2:item/dummy_fluid_item_base

https://pastebin.com/EReQ7uTN

**Issue**
Game randomly crashed on start up, was able to successfully load pack before and immediately after. Since it fixed itself, this can probably be treated more as an FYI-issue.

**Comment by Frikkle** [comment]
I had the same issue once yesterday; the first (and for me only) time it occurred since installing the pack. This seems to be a coincidental crash which sometimes occurs due to the loading order of things.

**Comment by MaxNeedsSnacks** [comment]
I've never had this crash, personally, but according to a lot of people, it seems to be happening across a broad span of different packs. This leads me to believe that it's just some unresolved mod issue, most likely sth along the lines of what @Frikkle mentioned concerning the loading order of mods.
