### ISSUE TITLE
Placing bits from chisels&bits causes client to crash.

### ISSUE THREAD

**Issue by NerevarDZN** [NillerMedDild/Enigmatica2Expert#1159]
**Modpack version**
Input version here 1.62

**Can the issue be reproduced?**
Yes

**Logs**
https://pastebin.com/V761EEKL

[crash-2019-04-28_15.55.10-client.txt](https://github.com/NillerMedDild/Enigmatica2Expert/files/3125057/crash-2019-04-28_15.55.10-client.txt)

**Issue**
Input short description of the issue here
Any attempt to place bits from chisels&bits causes client crash . This does not apply to placed bits with designs.
Error: java.lang.ArrayIndexOutOfBoundsException: 36

**Comment by Frikkle** [comment]
I just created various form and size bits from Astral Sorcery Marble (which I happened to have in my hand) using the Diamond Bit Saw. Then plac
![image](https://user-images.githubusercontent.com/9324165/56865701-169d4e00-69d1-11e9-89a6-66fd78314fb7.png)
ed them in the world. Could not reproduce the crash.

Were they bits in any specific shape or material? Or all of them?

**Comment by NerevarDZN** [comment]
I'm placing bits that i have in my hand, any shape placing/cutting bits causes crashing. Tried with every bits type that i got on me sonte, glass, iron ..., even using chisel with clean inventory.

Error: java.lang.ArrayIndexOutOfBoundsException: 36

**Comment by Frikkle** [comment]
I that case I cannot reproduce it. Does it persist through a client restart?

**Comment by NerevarDZN** [comment]
I assuming that issues is on my side, and i need some direction what causing it,

**Comment by NerevarDZN** [comment]
Root of the issue found. 
Somehow C&B thinks that Thermal Expansion's Satchels are valid place for storing and pulling out bits

**Comment by MaxNeedsSnacks** [comment]
Aaaaand this is the point where I'm almost certain I know the culprit for #1138

**Comment by NillerMedDild** [comment]
Merging with #1138

**Comment by Frikkle** [comment]
That also explains why I couldn't get it reproduced ^^
