### ISSUE TITLE
Advanced rocketry mod errors

### ISSUE THREAD

**Issue by Swiloga** [NillerMedDild/Enigmatica2Expert#116]
#### Issue Description
found many errors on this mod:
- data cable - not crafting and therefore there are no alternatives for connecting machines
- observatory (multiblock) - fist search all asteroids empty
- satellite terminal - wrong player inventory if use this in work
- chest in rocket not openning (if you create a rocket for the asteroid mining, It is necessary to disassemble the rocket and after that to extract resources from the chest)
#### Modpack version (Do not use "latest")
1.29

**Comment by NillerMedDild** [comment]
All known issues, they should be fixed by the Advanced Rocketry dev eventually. Thanks for the report.
