### ISSUE TITLE
Random Crashing while moving

### ISSUE THREAD

**Issue by TheMCProf** [NillerMedDild/Enigmatica2Expert#1162]
**Modpack version**
1.62

**Can the issue be reproduced?**
Unknown

**Logs**
https://pastebin.com/1E18D1hz

**Issue**
Whenever I'm walking/flying around the world, I would randomly freeze and crash and this has happened more than once. VanillaFix says that the mods causing it are Biomes O' Plenty and Recurrent Complex.
I can open the world immediately after the crash and continue playing without any problems though.

If this is a feature request, feel free to delete the template.

**Comment by NillerMedDild** [comment]
Can you reproduce this without VanillaFix?

**Comment by TheMCProf** [comment]
I'll try.
