### ISSUE TITLE
Quark Dropoff Button doesn't work on Iron Chests in 1.63

### ISSUE THREAD

**Issue by Scorch-Mechanic** [NillerMedDild/Enigmatica2Expert#1165]
**Modpack version**
1.63

**Can the issue be reproduced?**
Yes

**Issue**
The "merge to nearby inventories" button no longer works on iron chests in quark. Easy fix though, just add the relevant entry "ironchest:iron_chest" to the configuration file under the "        # Blocks with inventories which do not explicitly accept dropoffs, but should be treated as though they do." heading. I just did it with forge's ingame mod configuration menu and fixed the problem straightaway (Quark->Management->Chest Buttons and add an entry to "Dropoff Enabled Blocks").

Someone raised exactly this issue on the quark github yesterday, which is where I discovered the fix: https://github.com/Vazkii/Quark/issues/1230

**Comment by NillerMedDild** [comment]
Thanks for the report and fix :D

**Comment by Frikkle** [comment]
Quark seems to have released :)

**Comment by NillerMedDild** [comment]
No?

**Comment by Frikkle** [comment]
Wait, what are we waiting for exactly with this issue? For the Quark team to implement built-in Iron Chest support for the inventory button? If so, wouldn't a config change suffice in the meantime? Or do you prefer not changing the configs?

**Comment by NillerMedDild** [comment]
We're waiting for them to push a new build to fix two new crash bugs introduced in the last update.

**Comment by Frikkle** [comment]
Ah, that explains; sorry for my derp :)

**Comment by NillerMedDild** [comment]
No worries :)
