### ISSUE TITLE
Weird hovering issue after update

### ISSUE THREAD

**Issue by Basedgod199** [NillerMedDild/Enigmatica2Expert#1166]
**Modpack version**
1.63

**Can the issue be reproduced?**
Yes

**Logs**
N/A

**Issue**
After updating to 1.63, i opened my ae2 crafting terminal, hovered over something and all the items in my terminal highlighted red.(see screenshot) I've never run into a problem like this so i have no idea what would cause it.

![2019-05-02_10 43 43](https://user-images.githubusercontent.com/32063145/57095600-24e8b400-6cc8-11e9-9f13-124a9c4eb140.png)

**Comment by Basedgod199** [comment]
I found the cause. In Quark's client configs, there's an option to show invalid slots, which was turned on. Perhaps it only happened to me, but in any case it should probably be turned off by default.

**Comment by NillerMedDild** [comment]
That's.. odd. I turned it off, thanks for the report.

**Comment by NillerMedDild** [comment]
I re-opened the issue to check if others are experiencing the same thing. So if you're reading this, and can confirm that this issue happens in 1.63, please comment :)

**Comment by Frikkle** [comment]
Can confirm; fixed as well by the indicated steps.

**Comment by NillerMedDild** [comment]
Thanks, I'll roll out hotfixes.
