### ISSUE TITLE
NuclearCraft Chemical Reactor crash creating Sulfur Dioxide

### ISSUE THREAD

**Issue by MirrorImageQS** [NillerMedDild/Enigmatica2Expert#1168]
**Modpack version**
1.63a

**Can the issue be reproduced?**
Yes

**Logs**
https://pastebin.com/TU3UGHzX

**Issue**
A NuclearCraft Chemical Reactor fed with Molten Sulfur (from a NuclearCraft Melter of Sulfur) and Liquid Oxygen (from a Mekanism Electrolytic Separator of Water) causes a crash when it attempts to generate Sulfur Dioxide. The crash happens on the tick it would create the product - the processing ticks leading up to it are just fine.

I was able to recreate this in a brand new creative world with nothing else but those machines. This crash did not happen in 1.62.

**Comment by NillerMedDild** [comment]
Thanks for the report, it has been reported to the NC tracker here: https://github.com/turbodiesel4598/NuclearCraft/issues/507

**Comment by turbodiesel4598** [comment]
Soz about it taking a while fellas - will try to get a build out soon!

**Comment by NillerMedDild** [comment]
No worries, good luck with your mock-exams!

**Comment by turbodiesel4598** [comment]
Fixed with [version 2.16f](https://minecraft.curseforge.com/projects/nuclearcraft-mod/files/2707577) ;)

**Comment by NillerMedDild** [comment]
I just saw, thanks!

**Comment by arcreigh** [comment]
Hey turbo/niller should it be safe to drop in the update for e2e on our own or should we wait for the official update?

**Comment by turbodiesel4598** [comment]
Should be fine to do it manually I imagine, as nothing else about the rest of the mod has changed ;)

**Comment by NillerMedDild** [comment]
If you don't use XNet using 1.63a with updated NuclearCraft is safe.

**Comment by arcreigh** [comment]
Cool deal thanks I'll go ahead and push this to our server, if anything comes up i'll be sure to send an issue your alls way.

**Comment by arcreigh** [comment]
OH and is this just a server side fix or will clients also need to update?

**Comment by arcreigh** [comment]
OK so this requires a client side update, @NillerMedDild would you mind pushing an update to 1.63a?

**Comment by NillerMedDild** [comment]
I'm afraid I won't update before YNot updates.

**Comment by arcreigh** [comment]
Roger that. I'll update my community.

**Comment by NillerMedDild** [comment]
Thanks for understanding ^^

**Comment by arcreigh** [comment]
Absolutely!
Thanks for the great pack!
