### ISSUE TITLE
Language change errors

### ISSUE THREAD

**Issue by Swiloga** [NillerMedDild/Enigmatica2Expert#117]
#### Issue Description
if i change language to russian and connect to server (local to my PC or multi in internet) then I play without problems. However, it does not give a second connection. I have to download the build again and so every time you connect.
Version 1.23 work fine. The problem has appeared since version 1.24

#### Modpack version (Do not use "latest")
1.24, 1.26, 1.29, 1.30

**Comment by NillerMedDild** [comment]
Which message do you get on the second connect?

**Comment by NillerMedDild** [comment]
Which forge version are you using?

**Comment by Swiloga** [comment]
as indicated in the description of the mod
forge 1.12.2-14.23.4.2708
Version 1.23 work fine. The problem has appeared since version 1.24

**Comment by NillerMedDild** [comment]
Hmm the log doesn't say anything useful. What about the client `latest.log`?

**Comment by Swiloga** [comment]
[latest.log](https://github.com/NillerMedDild/Enigmatica2Expert/files/2120900/latest.log)
1.2Mb

**Comment by NillerMedDild** [comment]
I'm fairly certain this is a bug with Forge, I'll report it in the morning, thanks for the report.

**Comment by NillerMedDild** [comment]
Does this issue still occur?
