### ISSUE TITLE
XNet (filtered) mekanism gas channel server crash

### ISSUE THREAD

**Issue by stefancdr** [NillerMedDild/Enigmatica2Expert#1170]
**Modpack version**
1.63a

**Can the issue be reproduced?**
Yes

**Logs**
https://pastebin.com/djMBU20Z (server log, SMP)
https://pastebin.com/ny9T50gz (server log, SP)

**Issue**
When using mekanism gas channels, the server crashes as soon as gas is moved (the entity is ticked). This is most likely caused by the update to the new backwards-compatibility breaking versions of McJty's mods; YNot hasn't seen an update in a year (according to GitHub) and so probably isn't compatible.

Xnet's commit that broke this is this: https://github.com/McJtyMods/XNet/commit/bad22738a2926b92deba7c2994cbede416bc33bc#diff-ccdebad88af10ecb4fad7ab360007b5e

YNot should be updated to link to mcjty.xnet.config.ConfigSetup instead of GeneralConfiguration, but I can't seem to find the source code for 0.2.3, only 0.2.2 is available on GitHub, otherwise I'd fork it and fix it myself :-).

**Comment by Frikkle** [comment]
+1 debugged this with @stefancdr. This issue caused our server to crash when updating from 1.62 to 1,63(a).

In case any other server admin bumps into this; simply change the forge.cfg file to set the "removeErroringTileEntity" flag to true. This will remove the issue-throwing Xnet connectors and get your server started again.

Please do note that this might influence other stuff as well if you have any other tile entities that are being a dick. So be sure to have a backup of your server!

**Comment by Frikkle** [comment]
Just found the correct repo for Ynot @ https://git.asie.pl/asie-minecraft/YNot

I might look into this tomorrow and see if we can get a fix in place and PR'ed

**Comment by stefancdr** [comment]
Pull request made (https://github.com/asiekierka/YNot/pull/13), let's hope I didn't make any silly coding mistakes. (this version works locally)

**Comment by NillerMedDild** [comment]
Great work!

**Comment by stefancdr** [comment]
0.2.4 is now available :-).
