### ISSUE TITLE
Crash when hovering mekanism crushing factory slot.

### ISSUE THREAD

**Issue by AxelMontini** [NillerMedDild/Enigmatica2Expert#1171]
**Modpack version**
1.63a

**Can the issue be reproduced?**
Yes, every time.

**Logs**
[Pastebin](https://pastebin.com/qDFUg21m)

**Issue**
When hovering any slot in a crushing factory, the game hangs and then crashes.  
It didn't happen in previous versions (tested 1.62).

**Comment by NillerMedDild** [comment]
Will be fixed in the next update.
