### ISSUE TITLE
Server crash when making sulfuric acid in a Chemical Reactor

### ISSUE THREAD

**Issue by arcreigh** [NillerMedDild/Enigmatica2Expert#1172]
**Modpack version**
1.63a

**Can the issue be reproduced?**
Yes

**Logs**
https://pastebin.com/k4XjrJ8G
**Issue**
Server crash when making sulfuric acid in a Chemical Reactor

**Comment by NillerMedDild** [comment]
duplicate of #1168

**Comment by NillerMedDild** [comment]
Oh, and sorry for the inconvinience :/

**Comment by arcreigh** [comment]
All good thanks Niller!
