### ISSUE TITLE
[1.62] Thaumcraft aspects not working in JEI

### ISSUE THREAD

**Issue by Bucket777** [NillerMedDild/Enigmatica2Expert#1173]
**Modpack version**
1.62

**Can the issue be reproduced?**
Yes

**Issue**
This is the same issue as [This](https://github.com/NillerMedDild/Enigmatica2Expert/issues/1092)
**However:**
That one was closed without any indication as to what/when it was/will be fixed.
As well as only referring to versions [60,61].

The point of research mentioned there does not stand, as I have unlock 50% of alchemy and crafted Thaumium, but cannot look up where to get Praecantatio in JEI as with previous versions.
Also scanned every item in every inventory, having 25 observation points in alchemy.

**Comment by NillerMedDild** [comment]
My apologies, it was fixed in 1.63 but that version was rolled back, it should fixed again within a few days, in version 1.63b
