### ISSUE TITLE
Dimensional Shard Recipe removed in 1.63a?

### ISSUE THREAD

**Issue by sylviapossenau** [NillerMedDild/Enigmatica2Expert#1177]
**Modpack version**
1.63a / 1.62

**Can the issue be reproduced?**
Yes

**Logs**
--

**Issue**
In 1.62 dimensional shards from RFTools were craftable and it seems this recipe is not available in 1.63(a). Was this intentional as I cannot find any mention in the changelog?

**Comment by NillerMedDild** [comment]
The recipe has never been intentional :)

**Comment by Frikkle** [comment]
#sadface That moment when you spent an entire day working on getting D-T Fuel production set-up and properly (and aesthetically pleasingly) automated and only then you find out you need an RF Tools Infused diamond :< using dimensional shards...

Anyway, did you want to have the Mekanism Fusion Reactor gated that far to the back of the pack?

**Comment by NillerMedDild** [comment]
God yes, nothing can beat that thing :P

**Comment by Frikkle** [comment]
I guess I should grow a proper set of eyes first then before I start crafting all kinds of stuff hoping it will work out in the end. The Fusion Reactor itself, including lasers and such does not seem expensive at all. Which might be part of my downfall in this.

**Comment by NillerMedDild** [comment]
Hmm maybe the reactor should require the shards as well...
