### ISSUE TITLE
Advanced Rocketry shift right click crash (rocket)

### ISSUE THREAD

**Issue by psykoe** [NillerMedDild/Enigmatica2Expert#118]
#### Crash Report
https://pastebin.com/239LJXSN

No additional mods added or anything, this is also on a multiplayer server. Something to note is sometimes I TP home (to overworld) then come back using a RFTools teleporter that I have been setting up on every planet, but this crash happens nearly every other time as soon as I open the rocket GUI and click the nav computer to swap the Planet ID chip with my Space Stations ID chip to get the craft back to the space station.

**Comment by NillerMedDild** [comment]
Would you be able to give [this build](https://github.com/zmaster587/AdvancedRocketry/files/2126344/AdvancedRocketry-1.12.2-1.4.0-universal.jar.zip) a shot and see if the crashing continues?
