### ISSUE TITLE
Fluid duplication

### ISSUE THREAD

**Issue by JonasSiuksteris** [NillerMedDild/Enigmatica2Expert#1180]
**Modpack version**
1.63a

**Can the issue be reproduced?**
Yes

**Issue**
Used fluid placer from cyclic connected to thermal expansion portable tank(tested basic and enderium) via enderio basic fluid conduit. Machine uses 500mB for one block. You can pick it up with bucket place it in a tank and repeat the process(probably it is possible to automate this as well).

**Comment by NillerMedDild** [comment]
This should be fixed in 1.64, thanks for the report.
