### ISSUE TITLE
Tinkers' Construct Item Rack is uncraftable

### ISSUE THREAD

**Issue by kaikue** [NillerMedDild/Enigmatica2Expert#1182]
**Modpack version**
1.62

**Can the issue be reproduced?**
Yes

**Logs**
N/A

**Issue**
The Item Rack from Tinkers' Construct appears in JEI but is uncraftable. It's useful as a single-item inventory so it would be nice if I could craft it. I saw it was removed in https://github.com/NillerMedDild/Enigmatica2Expert/commit/7e2a69fae0e958c27668528dec1ebac1978e1928#diff-1a9aedc131316a77bf589e09608cabab but I'm unsure why that is; I couldn't find any reported bugs with it (and I had crafted & used it previously with no issues).

**Comment by NillerMedDild** [comment]
It was removed due to a recipe conflict iirc, and the fact that the Drying Rack can do the same thing.
