### ISSUE TITLE
Advanced Carpenter recipe is missing a block of cryotheum

### ISSUE THREAD

**Issue by kaikue** [NillerMedDild/Enigmatica2Expert#1183]
**Modpack version**
1.62

**Can the issue be reproduced?**
Yes

**Logs**
N/A

**Issue**
The recipe for the Advanced Carpenter requires 7 blocks of Gelid Cryotheum on the second layer, forming a ring around the center, and one empty block which seems like an oversight. You might not actually want to fix this one in case it invalidates everyone's structure for a very hard-to-debug reason.

![2019-05-12_01 09 09](https://user-images.githubusercontent.com/2455512/57578047-f3ec4a00-7452-11e9-95e6-9bdc75d2546f.png)

**Comment by NillerMedDild** [comment]
Thanks for the report. I'm aware of the issue, it was an oversight, and you are correct that I won't fix it due to structure invalidation :)
