### ISSUE TITLE
Server problem 

### ISSUE THREAD

**Issue by WujcioKarol** [NillerMedDild/Enigmatica2Expert#1186]
*Modpack ver.*
1.62
*Issue*
Server crash when try to start it with world generated on biomes o plenty, but starts without any issues when on normal generation
Logs
I cant put in in pastebin because it was too big
https://mclo.gs/mqkeiXL 
*reproducable*
Yes

**Comment by Frikkle** [comment]
Is this reproducable?

-- sent from my mobile device

**Comment by WujcioKarol** [comment]
Yes it crash everytime

**Comment by MaxNeedsSnacks** [comment]
Please update your server to v1.64 and see whether the issue persists

**Comment by NillerMedDild** [comment]
There is no crash in the log you supplied.

**Comment by WujcioKarol** [comment]
this is true it dont make full config but i use free hosting aternos and it dont want to give me full log :(

**Comment by WujcioKarol** [comment]
[crash.txt](https://github.com/NillerMedDild/Enigmatica2Expert/files/3178930/crash.txt)

**Comment by MaxNeedsSnacks** [comment]
Looks like you accidentally revealed some personal info for there, I'm gonna remove the lines and then reupload the crashlog, don't worry

**Comment by MaxNeedsSnacks** [comment]
Alright, so this log only shows the server stopping, but there's no actual crash happening? Does any crash report generate inside the crash-reports folder or something?

**Comment by NillerMedDild** [comment]
Please supply the server's latest.log instead.

**Comment by WujcioKarol** [comment]
I use aternos hosting so i dont know where is latest.log i only have crash.txt that i copy it from website log

**Comment by NillerMedDild** [comment]
I'm sorry but we cannot help you with that little information. We can tell you that server version 1.62 does not crash if set up correctly.
