### ISSUE TITLE
Storage scanner and tablet issue

### ISSUE THREAD

**Issue by Nila24** [NillerMedDild/Enigmatica2Expert#1187]
**Modpack version**
1.63a

**Can the issue be reproduced?**
Yes

**Logs**
Sort of. Problem is with RFTools tablet and modpack can crash while fiddling with it, but first problem in crash log for some reason is quark. https://pastebin.com/6wL43R77

**Issue**
Storage scanner "Export to first routable container" setting can not be changed / switched off neither locally neither via tablet remotely.

Tablet with Storage control screen module is able to retrieve items, but not push any items into inventories connected to storage scanner. The items would just sit in input slot. Depositing items directly on storage scanner works as intended.

Tablet also works properly (can retrieve and deposit items) with remote storage module or local storage module attached.

Steps to reproduce:
Just new world, plop scanner, modular storage, get tablet and module.

I did for some reason registered a ticket with Rftools first. Both McJty and you are super nice guys with way too much work and I hate bothering any of you. The issue is here https://github.com/McJtyMods/RFTools/issues/1948

**Comment by Nila24** [comment]
1.64 seem to not be on Twitch launcher yet for me, so I can not test with that (saw you mention rftools in changelog)  .

**Comment by NillerMedDild** [comment]
D'aww thanks for that last part :P

1.64 has not been released yet, it'll be a little while still. I hope to have this issue sorted by that time, but we'll see.

**Comment by NillerMedDild** [comment]
and thanks for the report.

**Comment by Nila24** [comment]
No pressure, take your time. Love the modpack btw!

**Comment by NillerMedDild** [comment]
> Storage scanner "Export to first routable container" setting can not be changed / switched off neither 
> locally neither via tablet remotely.

For some reason, you can only change that setting by pressing both right and left mouse buttons at the same time.

I was not able to reproduce the other issues, everything works as expected.

**Comment by Nila24** [comment]
Spot on with two mouse buttons at a time - thanks! 

As for tablet remote insert problem:
-Tried downloading new instance of 1.62 - no problems
-Tried to create one more world with same 1.63a instance - problem still exists
-Updated 1.63a instance to 1.64a version - problem gone. Go figure. 

I am not a fan in general of problems resolving themselves with no cause ever known, because problems can re-appear again. But hey - now it works, I do not expect to go back to 1.63a so that is good enough for me as a player. Thanks!  

Btw: xnet gas transfer broken that was broken in 1.63 now works again once more in 1.64a, so - yay for that as well!

Onwards to experiment with remaining stuff in the Enigmatica! Only 999'999 items left to try!
