### ISSUE TITLE
Crashing while launching.

### ISSUE THREAD

**Issue by chicklick** [NillerMedDild/Enigmatica2Expert#1188]
**Modpack version**
1.62

**Can the issue be reproduced?**
Yes

**Logs**
https://pastebin.com/dKhew46n

**Issue**
Often when I try to launch the game it crashes at phase 3 but it doesnt always do this. I also noticed that my CPU spikes to 100% usage right before it crashes, tried to reinstall, upgrade drivers and changed some settings but nothing seems to work. I've played this pack twice now and it has never happend before and just started a couple days ago and I don't know what the cause is.

**Comment by NillerMedDild** [comment]
Your java is outdated:

Make sure you have the newest Java 8 64-bit installed on your PC
Go to Twitch Settings and add -version:1.8+ to the Additional Arguments, or switch to the Jar Launcher, and then try again

**Comment by chicklick** [comment]
Added the -version:1.8+ and this came up.

https://gyazo.com/702e7d7d4965078c2d4fd531341b9515

**Comment by NillerMedDild** [comment]
Refer to step one, Make sure you have the newest Java 8 64-bit installed on your PC :P

**Comment by chicklick** [comment]
Do I need to download that from the internet? I already tried to update it via java and it said I had the latest version.

**Comment by NillerMedDild** [comment]
I'm guessing you installed 32-bit by accident. Use this link to get the correct version: https://javadl.oracle.com/webapps/download/AutoDL?BundleId=238729_478a62b7d4e34b78b671c754eaaf38ab

**Comment by chicklick** [comment]
I recently did wipe my entire computer so that's most likely the case. Will get back once i've tried this.

**Comment by chicklick** [comment]
I'm pretty sure this fixed the crashing so thank you!

**Comment by NillerMedDild** [comment]
Sure thing, glad I could help.
