### ISSUE TITLE
Periodic Memory Leaks

### ISSUE THREAD

**Issue by GreenMarine** [NillerMedDild/Enigmatica2Expert#1189]
**Modpack version**
1.62

**Can the issue be reproduced?**
Yes

**Logs**
https://pastebin.com/SNY9Ezn3

**Issue**
After upgrading to 1.62 from 1.51a, the log spews periodic memory leak tracking data.
It's unclear if this poses an actual problem for long term server operation: memory utilization doesn't seem to be ballooning after several days. This does cause some server TPS spikes when the reporting happens. And, it's not great to be in a place where things like this periodically fire off.

**Comment by NillerMedDild** [comment]
Thanks for the report - Do you mind checking if this happens on 1.64a?

**Comment by GreenMarine** [comment]
Sure, I can upgrade the server tonight and run it through the paces. It'll be about 12 hours (I'm on west coast US time and currently at work).

**Comment by NillerMedDild** [comment]
Sounds good, I will be available in 14-15 hours hopefully.

**Comment by GreenMarine** [comment]
I upgraded to 1.64a, the upgrade went smoothly. This problem did appear once I logged in. I let the server sit for a bit (about 20 minutes) before connecting and once I connected, I started to see periodic leaks. Log of the leak spew here:

https://pastebin.com/KDYiSCJ2

**Comment by NillerMedDild** [comment]
I don't know what to make of this to be honest, there's not really any helpful information in the log.

**Comment by MaxNeedsSnacks** [comment]
This leak seems to be related to OpenComputers, just in case that may help out

**Comment by GreenMarine** [comment]
We do have two OpenComputers systems in the base. I can take them down and see if it results in a change. I can also look into the OpenComputers open bugs / version info and see if I discover anything.
