### ISSUE TITLE
Ender IO Conduits: High CPU utilization.

### ISSUE THREAD

**Issue by GreenMarine** [NillerMedDild/Enigmatica2Expert#1190]
**Modpack version**
1.62

**Can the issue be reproduced?**
Yes

**Logs**
https://pastebin.com/ejRagWAi

**Issue**
Reporting this here as a first step, might be escalated to Ender IO.

In E2E 1.51a (and continuing after an upgrade to 1.62), Ender IO conduit entities consume a larger than expected portion of CPU time. In this case, the blockEntity tick spends 70% of its time updating the conduit network.

The attached profiler dump shows the distribution of work over 37734ms, which is representative of any slice of server activity I've found. You can also see this is a large base with many entities, none of which have subsystems contributing to such a degree of resource utilization.

**Comment by GreenMarine** [comment]
To be clear: this was noted in 1.51a and also noted (with no change) in 1.62.

**Comment by NillerMedDild** [comment]
Wow, those are some hungry conduits. How many would you say there approximately are? Would it be possible to supply screenshots of them, in an effort to find the less performant conduits, if there are any?

**Comment by GreenMarine** [comment]
I used the mod tell-me to count the number of conduits:

enderio:block_conduit_bundle, meta 0, 637
enderio:block_conduit_bundle, meta 1, 405

So, 1042 total. I don't know what metas 0 and 1 indicate.

While taking screenshots, I found one of our players had created this:

https://filedn.com/lD47MkPDxpzLREeay928LHm/Debugging/2019-05-15_20.25.11.png

Removing it reduced the number of meta 1 conduits to 261, but to my surprise didn't significantly change the profile.

I've taken some more screenshots and I'm trying to get a sense of where all the conduits are.

They are here:

https://filedn.com/lD47MkPDxpzLREeay928LHm/Debugging/

I'm breaking for food and then I'll keep investigating.

**Comment by GreenMarine** [comment]
I spent a bunch of time systematically destroying conduits. I found no smoking gun, after destroying 90% of the conduits. The performance improved linearly. This suggests to me that these conduits are just slow.

**Comment by NillerMedDild** [comment]
I agree, I think you should report your findings to the Ender IO team.

**Comment by GreenMarine** [comment]
K, I will do that. Thanks.
