### ISSUE TITLE
Exception while ticking world

### ISSUE THREAD

**Issue by Atadele** [NillerMedDild/Enigmatica2Expert#1191]
**Modpack version**
1.64a

**Can the issue be reproduced?**
unknown

**Logs**
https://pastebin.com/Rzg95XKZ

**Issue**
This started happening after I upgraded to 1.64. I think it is a forge issue as I have seen this exception on other forums. Usually when entering the nether the game crashes and has a exception while ticking world. It crashes in the nether and I cant open the world in mcedit to check.

**Comment by NillerMedDild** [comment]
Thanks for the report. Can you please remove Optifine and make sure you're using newer java, and see if the issue persists?

**Comment by Atadele** [comment]
Removed Optifine and using java version 8 update 211, but i still crash after about 30 seconds.

https://pastebin.com/X0f1JG5g

**Comment by Atadele** [comment]
I changed the java version on twitch launcher and it is still crashing

**Comment by Atadele** [comment]
Deleted dim 2 and reverting to backup and using new forge 2836 seems to have solved my problem

**Comment by NillerMedDild** [comment]
That's odd, dim 2 isn't the Nether, but great.

**Comment by AssB0ys** [comment]
Why is this closed and the new version of enigmatica is still released with the problematic version of forge(2831)? They didn't fix this untill 2836 - https://www.minecraftforge.net/forum/topic/70010-forge-1122-142352835-exception-ticking-world-crash/?tab=comments#comment-338899

**Comment by NillerMedDild** [comment]
Because I wasn't aware of it being an actual Forge issue, and the OP reported it resolved. Are you having the same issue?

**Comment by AssB0ys** [comment]
I haven't tested the 1.64b version of the pack yet. But I am positive that this version of forge causes ticking world exception, I have been struggling at that time with my own pack because of this. This exception may occur regardless of the mods installed as people state on that same forum thread, although I haven't tested it personally.

**Comment by NillerMedDild** [comment]
Alright, I'll hotfix immediately, thank you.

**Comment by SomeKindaMech** [comment]
> Alright, I'll hotfix immediately, thank you.

1.64c is still downloading 2831, FYI.

**Comment by NillerMedDild** [comment]
Oh no...

**Comment by Atadele** [comment]
It did stop for me when Used later forge but optifine was my initial problem.
