### ISSUE TITLE
Xnet Energy Channel max transfer rate text shows object hashcode instead

### ISSUE THREAD

**Issue by Frikkle** [NillerMedDild/Enigmatica2Expert#1192]
**Modpack version**
1.64a

**Can the issue be reproduced?**
By me, yes. It persists through restarts

**Logs**
Not applicable.

**Issue**
When hovering over an Xnet Energy Channel's Rate input box, the tooltip does not show the maximum transfer rate, but rather displays an object hashcode. This is the case for both input and output connectors.

Transfer rates for Fluids, Gas (Ynot), items, etc. are displayed fine.
![translation](https://user-images.githubusercontent.com/9324165/57939541-d8f25d80-78ca-11e9-91c2-2149e2fc9cce.png)

**Comment by MaxNeedsSnacks** [comment]
This might be similar to the RFTools config issue, can you try deleting and letting the XNet (and YNot, just to be safe) config values and then see whether this persists?

ᵃˡˢᵒ ᵗʰᵃᵗˢ ⁿᵒᵗ ᵗʰᵉ ᵐᵉᵐᵒʳʸ ᵃᵈᵈʳᵉˢˢ, ᵗʰᵃᵗˢ ᵗʰᵉ ᵒᵇʲᵉᶜᵗ'ˢ ʰᵃˢʰᶜᵒᵈᵉ

**Comment by NillerMedDild** [comment]
I believe I found the issue, will PR it to XNet.

**Comment by Frikkle** [comment]
Cool thanks, and sorry for not digging into it myself. Had to go out and wanted to have it written down somewhere so I wouldn't forget.

**Comment by NillerMedDild** [comment]
No worries, it's nice to do a PR for a change :P

**Comment by Frikkle** [comment]
@MaxNeedsSnacks thanks ;-)

**Comment by NillerMedDild** [comment]
https://github.com/McJtyMods/XNet/pull/346
