### ISSUE TITLE
Powered Diamond Anvil Non-Functional

### ISSUE THREAD

**Issue by GreenMarine** [NillerMedDild/Enigmatica2Expert#1193]
**Modpack version**
1.64a

**Can the issue be reproduced?**
Yes

**Logs**
N/A

**Issue**
As far as we can tell, the powered diamond anvil now pushes items to the output immediately without repairing them.

**Comment by NillerMedDild** [comment]
Are you attempting to repair Tinkers' Tools?

**Comment by GreenMarine** [comment]
Yes. This worked in 1.51, was that removed?

**Comment by NillerMedDild** [comment]
Yep :)
