### ISSUE TITLE
IC2 Semifluid generator no JEI recipes

### ISSUE THREAD

**Issue by FlyingThunder** [NillerMedDild/Enigmatica2Expert#1195]
**Modpack version**
1.62

**Can the issue be reproduced?**
Yes

**Issue**
The IC2 semifluid generator has no fuel recipes in JEI, the inputs still work though (tested with forestry biomass) 

![image](https://user-images.githubusercontent.com/39583733/57976222-2362ff80-79db-11e9-9619-6b43dfe12486.png)

**Comment by NillerMedDild** [comment]
Which recipes are you expecting to appear? :)

**Comment by FlyingThunder** [comment]
Well, i dont know which fluids the semifluid is supposed to accept - im guessing it should take the same fluids like the TE compression dynamo and the EIO combustion generator (as seen in the screenshot), but at the very least the 5 fluids that are named in the quest description (IC2 Biogas, Forestry Biomass, Oil, Forestry Ethanol and Fuel) - id add them myself, but i have no idea where the recipes are in this repo, and IC2 itself isnt open source...

**Comment by MorganSimic** [comment]
I think the semi-fluid generator does not have JEI at all. So there is no way to add recipes for that. And yes that is bad. Everything should have JEI integration. Maybe someone of the smart guys around here correct me if i'm wrong.

**Comment by NillerMedDild** [comment]
Morgan is correct :( nothing we can do here.

**Comment by FlyingThunder** [comment]
By the way, regarding IC2 and missing recipes - Distilled Water from IC2 also has no recipes (except, of course, squeezer and fluid transposer, but you know what i mean) - ill try to ask aroma directly regarding this, i guess; IC2 is already unattractive enough to many people x)

**Comment by osirisgothra** [comment]
I just wish someone could tell us if there are any _other_ fuels the SF generator can use. I know the defaults from the IC2 wiki, but modpacks tend to add more fuels that are similar or intended as an enhancement, it'd be nice to know since the questline makes you build one.
