### ISSUE TITLE
Quark Stonelings EnderIO spawner crash

### ISSUE THREAD

**Issue by EdyMarin** [NillerMedDild/Enigmatica2Expert#1197]
**Modpack version**
1.64d

**Can the issue be reproduced?**
Yes

**Logs**
https://pastebin.com/KGqAWFpt

**Issue**
Game crashes when using EnderIO mob spawner set to Stoneling from Quark. 

If this is a feature request, feel free to delete the template.

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
When exactly does it crash?

**Comment by NillerMedDild** [comment]
Could you please supply the latest log as well?

**Comment by EdyMarin** [comment]
It crashed when I put an octadic capacitor in the spawner (the spawner was powered before I put the capacitor in it)
Here's the latest log (unfortunately I cant use pastebin for it because it exceeded the size limit)
[latest.log](https://github.com/NillerMedDild/Enigmatica2Expert/files/3197593/latest.log)
)

**Comment by EdyMarin** [comment]
I tried to spawn stonelings using enderIO in a fresh world and it still crashed.
Here's the new crash log, maybe it helps
https://pastebin.com/HCx04js5

**Comment by NillerMedDild** [comment]
Thank you - the developers have found the issue I believe :)
