### ISSUE TITLE
Unable to attune Mantle of Stars

### ISSUE THREAD

**Issue by Basedgod199** [NillerMedDild/Enigmatica2Expert#1198]
**Modpack version**
1.64d

**Can the issue be reproduced?**
yes

**Logs**
N/A

**Issue**
While making the Mantle of Stars itself worked fine, i am unable to attune it to any constellation.
I've tried using both attuned rock crystals and celestial crystals, neither seem to make a difference.

![2019-05-19_16 17 15](https://user-images.githubusercontent.com/32063145/57989589-afb00980-7a51-11e9-880a-d8f362c32dfe.png)

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
I can't remember whether the constellation you're attuning the Mantle to needs to be present in the sky - Could you skip a few nights to verify?

**Comment by Basedgod199** [comment]
I tried it with the constellation in the sky and without, both don't seem to work

**Comment by NillerMedDild** [comment]
Damn. What about breaking and replacing the altar? Did you craft the mantle yourself?

**Comment by Basedgod199** [comment]
breaking and replacing the altar didn't do anything, and yes i did craft the mantle myself.

**Comment by Basedgod199** [comment]
Okay, three things to note:
1. the un-attuned mantle of stars doesn't show up in JEI (which idk if that's actually important but i thought i'd mention it)
2. cheating in an un-attuned mantle of stars also didn't work.
3. I crashed while messing around with this, and when i came back into the game, the mantle of stars was now attunable. however it only worked once. That being said i did close my game and relaunch and when i came back into the game i was again able to attune it. but again only once.

**Comment by NillerMedDild** [comment]
That's weird af. May I see the crash report?

**Comment by Basedgod199** [comment]
It happened just after i went to use my slimesling

https://pastebin.com/a4VG7SRR

**Comment by NillerMedDild** [comment]
That is unrelated unfortunately, thanks anyway.

**Comment by Kzorith** [comment]
I can confirm Basedgod199's observations with one exception.  The base Mantle doesn't show up in JEI, but you can get to the recipe if you select one of the others and click on the Mantle in the middle of that recipe.

I was able to create the base Mantle in the table with no issues.

I have tried creating the attuned versions with three different attuned crystals (and required materials) and none of them give me the option to craft it.

I did look into the astralsorcery.zs and there doesn't appears to be anything mentioned about modifying the Mantle recipes.

Kz

**Comment by NillerMedDild** [comment]
May I have a latest.log from an attempt at crafting the attuned Mantle please? :)

**Comment by NillerMedDild** [comment]
Did you input the ingredients with the JEI plus?

**Comment by Basedgod199** [comment]
Okay I've found a solution. It appears that equipping the mantle (to your chestplate slot) and then attuning it will work. tested it with vicio, mineralis, and aevitas, And tried rock and celestial crystals, all seem to work. I still don't know what would cause this, as the mantle appeared unchanged after equipping it (no metadata changes or nbt changes that i could see, anyway)

**Comment by Kzorith** [comment]
There was no crash on attempt, it just would not display the item to be crafted, so the crafting of it could not begin.  I'm not sure there would be a log of that to present to you.  I can maybe try it again this evening to see if there is anything in the server log.

My first attempts I had put them in using JEI plus, but I visited the Astral Sorcery Discord and performed a search where I saw someone say not to use JEI.  So I shut down Minecraft completely, launched it again and put the ingredients into the altar manually.  That also didn't work with the same lack of display of the item to be crafted. 

That generally indicates a problem with the recipe or the altar, but my altar crafted the base Mantle just fine so it's not the altar. The recipe I used agrees with JEI and the Astral Tome, so I'm at a loss as to where the issue lies.

**Comment by NillerMedDild** [comment]
Did you try @Basedgod199's fix?

**Comment by Kzorith** [comment]
No. I have not since he posted his fix about 20 seconds before I posted my reply.
I will try it this evening after I get home.

**Comment by NillerMedDild** [comment]
Sounds good :)

**Comment by NillerMedDild** [comment]
No need @Kzorith it was confirmed by someone else, thanks anyway.

**Comment by chicklick** [comment]
This also happend to me when I was trying to make a irradiant star but after a relog/restart (cant rememeber which) it worked.

**Comment by Frikkle** [comment]
I don't know if this is any help but I crafted some attuned mantles yesterday as well as a few irradiant stars attuned to a constellation. Using 1.64d. In all cases I have the JEI "plus" method to add all items into the crafting table.

Just like @Kzorith says, the to-be-crafted item did not show, like there would not be enough starlight available or something like that. When hitting the altar with my wand, the process would start however and request the additional items to be placed on the spectral relays.

**Comment by IyaTaisho** [comment]
I tested what Basedgod199 said to try and it worked out for me.  I was having the same issue and couldn't figure out what was wrong.  After I slipped on the Mantle of the Stars, it recognized it.

**Comment by Frikkle** [comment]
Just talked to someone else on Discord with this problem; for them, wearing the unattuned mantle and then trying to attune it also solved the issue.

**Comment by Frikkle** [comment]
Also, this has been solved in AS 1.10.19 (released on May 27) any reason we're not upgrading this one yet?

**Comment by NillerMedDild** [comment]
We have updated actually.
