### ISSUE TITLE
zirconium dust recipe issue

### ISSUE THREAD

**Issue by KitanaShaw** [NillerMedDild/Enigmatica2Expert#12]
#### Issue Description
zirconium dust recipe using the metallurgic infuser in jei shows an invisible (This Item Is Disabled) and cant really tell which item is required to complete the craft 
screenshot: https://i.imgur.com/NqCdBrv.png
#### Modpack version (Do not use "latest")
1.07

**Comment by jsorrell** [comment]
I think the item is supposed to be nether quartz dust due to the line 
```
mods.mekanism.infuser.addRecipe("DIAMOND", 20, <appliedenergistics2:material:3>, <nuclearcraft:dust:10>);
```
in `scripts/NuclearCraft.zs`. The problem is actually additions nether quartz dust is used instead of the ae2 version. A quick fix is to change the line to use the actually additions version:
```
mods.mekanism.infuser.addRecipe("DIAMOND", 20, <actuallyadditions:item_dust:5>, <nuclearcraft:dust:10>);
```

**Comment by NillerMedDild** [comment]
I see Applied Energistics 2 Quartz Dust was disabled for some reason, moving over to Actually Additions as you suggested, thank you.
