### ISSUE TITLE
Universal Fluid Cells are hidden in JEI

### ISSUE THREAD

**Issue by XxZajoZzO** [NillerMedDild/Enigmatica2Expert#1200]
**Modpack version**
1.64d

**Can the issue be reproduced?**
Yes

**Issue**
Universal Fluid Cells are hidden in JEI
If you enable item hiding mode they show up as hidden
![2019-05-20_20 36 24](https://user-images.githubusercontent.com/13818400/58044138-532b1800-7b3f-11e9-8232-7b44bba66429.png)
![2019-05-20_20 36 17](https://user-images.githubusercontent.com/13818400/58044145-59b98f80-7b3f-11e9-8f81-7241eb27f7ae.png)

**Comment by cridenour** [comment]
There is a note in the questbook discussing why this is.
