### ISSUE TITLE
A crash upon logging in

### ISSUE THREAD

**Issue by johnch18** [NillerMedDild/Enigmatica2Expert#1201]
**Modpack version**
1.6.2
**Can the issue be reproduced?**
I'm not sure how reproducable it is, but every time I load my survival world, it crashes.

**Logs**
https://pastebin.com/index.php?e=1
**Issue**
It caused me to log out, I've reached almost "Bragging Rights"

If this is a feature request, feel free to delete the template.

**Comment by NillerMedDild** [comment]
Your pastebin link is empty, try using gist.github.com instead

**Comment by johnch18** [comment]
My apologies, I was a bit otherwise involved. I attempted loading the world one more time, and here is that crash report. https://gist.github.com/johnch18/2b6a565c88299f4ac89a153deda4ad95 . Tomorrow when I get back from things I need to do, I'll try reloading a backup prior to the crash and see if I can duplicated the crash from there.

**Comment by NillerMedDild** [comment]
Looks like an item in your inventory (Blood Magic Snare) has errored in some way. Edit it out of your playerdata, or delete it entirely to fix it :)
