### ISSUE TITLE
Game crashed to desktop when skipping through steel ingot recipes

### ISSUE THREAD

**Issue by FlyingThunder** [NillerMedDild/Enigmatica2Expert#1204]
**Modpack version**
1.64d

**Can the issue be reproduced?**
only happened once up to now, not 100% sure if the recipes were actually the cause though, just happened at the exact moment i clicked

**Logs**
https://pastebin.com/k6Qhjfjh

**Issue**
The game suddenly crashed after doing this:
Was in the GUI of the crafting station with an attached diamond chest and had the usage-recipes for the steel ingot opened. the game crashed when i clicked on the arrow to go to the second page of the recipes

If this is a feature request, feel free to delete the template.

**Comment by MaxNeedsSnacks** [comment]
Do you use any sort of special Garbage Collector settings?

**Comment by MaxNeedsSnacks** [comment]
Regardless of that first question, your Java seems to be out of date (you're running 8u51, newest is 8u212)

**Comment by NillerMedDild** [comment]
As Max says, the issue here is outdated java.

* Make sure you have the latest 64-bit Java installed
* Go to the Twitch Minecraft settings
* Add `-version:1.8+` to the Additional Arguments

**Comment by Frikkle** [comment]
In additions to the Max and Niller, I've tried to reproduce this issue as described, just for the sake of trying. Wasn't able to.

**Comment by XxZajoZzO** [comment]
I just got the same crash (https://pastebin.com/xBDGr019) but I have Java 1.8.0_202-b08.

**Comment by NillerMedDild** [comment]
I'm not familiar with that Java version, could you try updating to the latest please?

**Comment by XxZajoZzO** [comment]
It crashed again so I updated Java to 1.8.0_211. I will see if it's crashing now

**Comment by XxZajoZzO** [comment]
Not crashing anymore

**Comment by FlyingThunder** [comment]
Hey, i got a random crash again - this time standing in front of the metal press picking up stuff for a while, and the log shows IE as the reason again: https://pastebin.com/SWCGvRzn
Im on java 1.8.0_211-b12

**Comment by XxZajoZzO** [comment]
your java version is 1.8.0_51-b16 not 211

**Comment by NillerMedDild** [comment]
You may have Java 1.8.0_211-b12 on your PC, but that's not what Minecraft is using. Please follow my initial instructions.
