### ISSUE TITLE
Error When Loading the Modpack: "Mod IDs can't be resolved"

### ISSUE THREAD

**Issue by Dory05** [NillerMedDild/Enigmatica2Expert#1206]
**Modpack version**
Enigmatica 2 Expert 1.64d

**Can the issue be reproduced?**
Yes, has happened at least 3 times on my computer.

**Issue**
When trying to load the modpack through MultiMC, the program shows the error
 _"Unable to resolve mod IDs:
Some mod ID resolving tasks failed."_

This is on the latest version of MultiMC.

**Comment by NillerMedDild** [comment]
I'm aware of the issue, there has been a change with CurseForge that has deprecated the way MultiMC accesses some mods. I recommend you use CFMPDL until it's fixed :)
