### ISSUE TITLE
Goats won't breed, so goat milk is unattainable?

### ISSUE THREAD

**Issue by AwesomeLikeThis** [NillerMedDild/Enigmatica2Expert#1207]
**Modpack version**
1.6.4d

**Can the issue be reproduced?**
yes

**Logs**
none

**Issue**

So goat milk is needed for the creative fluid tank, and the goats I'm using (in this case the fainting doe and fainting buck) will not breed.
In order to get the milk the does need to have a kid and then I can milk it. But, it has been hours of me waiting for them to mate while giving them wheat and water and nothing has happened.

All I've found was a thread a couple months old referring to some other person having the same issue, but no one was able to give a fix. 
Here's a [link](https://www.reddit.com/r/feedthebeast/comments/at4pa4/animania_mod_issue_goats_refusing_to_mate/)

Now I'm supposing this is a bug on Animania's end but I was hoping a new recipe for goat milk could be added.

**Comment by NillerMedDild** [comment]
The goats need to be either in love or "single" for them to breed, try replacing one or both. Finding male and female pairs in the wild usually works.
Please let me know if that fixes the issue :)

**Comment by AwesomeLikeThis** [comment]
Okay, I now have 3 sets of goats that I found in the wild who still wont breed. Any other ideas?

**Comment by AwesomeLikeThis** [comment]
well after another hour or two and a few stacks of wheat, still nothing

**Comment by NillerMedDild** [comment]
Sounds like we need to have a look at this as well :)

**Comment by NillerMedDild** [comment]
So I was able to get Goats to breed, but it was a hassle to say the least. I had to give them water, grass, wheat, carrots and poppies. Then it took about 10 minutes.
