### ISSUE TITLE
Liquid Chlorine not removable from ME storage.

### ISSUE THREAD

**Issue by GreenMarine** [NillerMedDild/Enigmatica2Expert#1208]
**Modpack version**
1.64

**Can the issue be reproduced?**
Yes

**Logs**
N/A

**Issue**
There is no bucket form of Liquid Chlorine. This means that once it is inserted into the ME system it can never be removed, AFAIK. AE2 requires all liquids have some bucket-like item that can be placed in the Fluid Export Interface's filter slot to enable extraction.

While liquid chlorine is not stable at room temperature and so a bucket of it is unrealistic, it would be helpful for things like Titanium automation to be able to use a bucket for filtering. (The workaround, for now, is to store brine in the ME system and do the electrolytic processing at the point of consumption.

There are other containers that can hold any fluid, such as the Mekanism ultimate fluid container, but these aren't accepted by AE2 as filter providers.

I don't know if this counts as a modpack bug. It could be solved for this modpack, but it's likely an intersection of several mods that results in this oversight.

**Comment by NillerMedDild** [comment]
I see how that is annoying, but it's ultimately up to Mekanism whether they want a bucket form of a liquid or not. I can't solve on a modpack level.
