### ISSUE TITLE
IC2 batch crafter creates several times more items than it should with overclocker upgrade

### ISSUE THREAD

**Issue by eutropius225** [NillerMedDild/Enigmatica2Expert#1209]
**Modpack version**
1.58

**Can the issue be reproduced?**
Yes

**Issue**
When the "Batch Crafter" from IC2 has a lot of overclocker upgrades (I used 20), each craft produced ~32 times as many items as it should have, using less than the items required for the craft. (e.g. 9x The Ultimate Ingot produced 32 Blocks of the Ultimate) Needless to say, it's game breaking.

Presumably, it's the IC2 crafters themselves that are bugged fundamentally, but I haven't found the issue reported for this pack before.

**Comment by NillerMedDild** [comment]
Holy O_O thanks for the report!

**Comment by AwesomeLikeThis** [comment]
I can confirm, this actually happens.
![image](https://user-images.githubusercontent.com/18647702/58209030-25b3ab00-7cb4-11e9-880a-6b67d59ed6a9.png)

![image](https://user-images.githubusercontent.com/18647702/58209041-2d734f80-7cb4-11e9-94c3-880a09885b66.png)
