### ISSUE TITLE
Missing Recipe(s) for the EU2 Echanter/Chisel

### ISSUE THREAD

**Issue by Aquintus** [NillerMedDild/Enigmatica2Expert#121]
Recipe(s) missing: You can use bookshelves in the Extra Utilities 2 Enchanter to craft magical wood, but only chisel ones, not quark ones. 

It's also not possible to chisel the quark bookshelves.

#### Modpack version
1.26c

**Comment by Aquintus** [comment]
I just found out that you can use the Quark bookshelves to increase the enchanting power of the EU2 Enchanter (see attached image, so it is getting recognized as an actual bookshelf. ^^)

![image](https://user-images.githubusercontent.com/40473897/41741165-9b5756b2-759a-11e8-9d8f-1faa28b48ffa.png)

**Comment by Barhandar** [comment]
Enchanting power of blocks is entirely unrelated to itemstack behaviors.

**Comment by NillerMedDild** [comment]
Sounds like a missing oredict.

**Comment by NillerMedDild** [comment]
They seem to work for me.
