### ISSUE TITLE
[Suggestion] Add Mob Grinding Utils

### ISSUE THREAD

**Issue by niklas2233** [NillerMedDild/Enigmatica2Expert#1210]
Hey it would be nice if you could add the Mob Grinding Utils mod so that servers will have less problems with wither auto killers and that kind of stuff would also just be a nice thing to have. dont really know if it will cause any balance issues. im just thinking about the boss mufflers

https://minecraft.curseforge.com/projects/mob-grinding-utils

**Comment by NillerMedDild** [comment]
Bosses are already muffled by a different mod, and Mob Grinding Utils doesn't add any items, blocks or functionalities that aren't already available. So I'm afraid it's a no.

**Comment by niklas2233** [comment]
but what about the boss bar?

**Comment by NillerMedDild** [comment]
Ah Mob Grinding Utils can get rid of that as well?
