### ISSUE TITLE
crashing after sometime

### ISSUE THREAD

**Issue by rjzvara** [NillerMedDild/Enigmatica2Expert#1212]
**Modpack version**
Version 1.64d with forge-14.23.5.2836 

**Can the issue be reproduced?**
unknown

**Logs**
https://pastebin.com/97wKfpbW

**Issue**
seems to crash out of nowhere

**Comment by Frikkle** [comment]
Could you elaborate a little bit about what you were doing when it crashed? Might help direct us a little in debugging

**Comment by NillerMedDild** [comment]
There is no crash in that log, please give us the crash report.

**Comment by rjzvara** [comment]
> There is no crash in that log, please give us the crash report.

That's just it. it crashes out of the blue and jets me out back to the jar launcher

> Could you elaborate a little bit about what you were doing when it crashed? Might help direct us a little in debugging

i'm usually just wandering around the world. it might be the chunk loading.

**Comment by NillerMedDild** [comment]
Which log is the one you supplied? Is your crash-reports folder is empty?

**Comment by rjzvara** [comment]
Find a previous report. https://pastebin.com/s8dvdfFh

**Comment by rjzvara** [comment]
still the same type of situation

**Comment by NillerMedDild** [comment]
You're using Forge 2838, 2836 is the one I recommend. 
It looks like the game dislikes one of the keybindings you've changed, deleting the options.try will probably fix it.
