### ISSUE TITLE
UU Matter Values - Request

### ISSUE THREAD

**Issue by Ser-Luke** [NillerMedDild/Enigmatica2Expert#1213]
**Modpack version**
1.64d

**Can the issue be reproduced?**
Feature Request

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Issue**
While it isn't completely necessary, it would be nice to have UU Matter Values defined for Simple Machine Chassis (Ender IO), as well as, Draconic Cores (Draconic Evolution), and Elite Plating (Nuclearcraft), despite all of these being automate-able, UU Matter Provides a quick way of producing certain resources, of which these being included could be helpful to the player.

If this is a feature request, feel free to delete the template.

**Comment by NillerMedDild** [comment]
They're not replicable by design :)
