### ISSUE TITLE
Summoning mini me from golden egg creates block that crashes on render

### ISSUE THREAD

**Issue by kurtmueller42** [NillerMedDild/Enigmatica2Expert#1214]
**Modpack version**
Enigmatica2Expert-1.62

**Can the issue be reproduced?**
unknown

**Logs**
https://pastebin.com/THzsfD2L

```
 Entity being rendered --
Details:
    Entity Type: openmods:block (openmods.entity.EntityBlock)
    Entity ID: 66957562
    Entity Name: entity.Block.name
    Entity's Exact location: -20.50, 71.07, 294.50
```

**Issue**
Got a golden egg from a random quest reward. Upon trying to summon the mini me created a block that repeatedly crashes on load. The crash is reproducible on our server but it's unclear if using a golden egg always leads to this or if there was some other circumstance.

**Comment by NillerMedDild** [comment]
Thanks for the report. Can you verify the bug on the latest release?

**Comment by Darkere** [comment]
Confirmed still an issue on 1.65b
https://pastebin.com/pxvpYTVB

**Comment by NillerMedDild** [comment]
Did you place it near some XNet Cable?

**Comment by Darkere** [comment]
Middle of my base. Xnet, RS, Thermal machines and more nearby. Had to go into NBTExplorer to delete the entities since it continued crashing.

**Comment by NillerMedDild** [comment]
I reported the issue here: https://github.com/OpenMods/OpenBlocks/issues/973
