### ISSUE TITLE
Crash on pack load since updating to 1.64d.

### ISSUE THREAD

**Issue by MBlore** [NillerMedDild/Enigmatica2Expert#1215]
**Modpack version**
1.64d

**Can the issue be reproduced?**
Yes

**Logs**
https://pastebin.com/PYVF6sAF

**Issue**
Instant crash on load.

**Comment by Mx772** [comment]
Same Problem here

**Comment by NillerMedDild** [comment]
Try re-installing please :)

**Comment by MBlore** [comment]
Performed a clean install and copied over the "saves" folder from the previous instance. Confirmed all working fine now, thanks :).

**Comment by NillerMedDild** [comment]
Sweet!
