### ISSUE TITLE
[Astral sorcery] Floating crystal wont interact at all with my crafting table 

### ISSUE THREAD

**Issue by IceyFoxy** [NillerMedDild/Enigmatica2Expert#1216]
Modpack version
Enigmatica 2 expert version: 1.64d

Can the issue be reproduced?
For me it can be reproduced at any shrine in my serverworld (and singleplayer world?)

Logs
This is my pastebin, i could not copy the entire log for some reason..  https://pastebin.com/60nBNSif

Issue
Okay so, i am currently playing the enigmatica 2 expert modpack on the latest version (1.64d) and i wanted to continue with my next tree(gate) called astral sorcery which seems like a very pretty mod. I am already pretty far in the game so i had a ton of resources already available to me like aquamarine gems and enderpearls to make the resonating wand, I went to one of my waypointed locations were i found a white crystal floating in the basement of this (big) structure.. I opened the roof and drained the fountain while i was doing it so the crystal could get starlight which is one of the factors to get going with this mod and i placed a vanilla crafting table but i am now seeing that it wont emit an faint beam of light and i am clueless what to do next.. i followed the astral tome's like line directions so first the crystal and then the wand before i get to crafting the bench but even then i need to get that ray of light when the crystal is getting starlight so... i am stuck.. i really do not know what to do next and even if i want to wait with astral sorcery i still need it for botania so yea.. The strange thing is that i am seeing videos of enigmatica 2 expert and the people of those videos are just doing it fine while i am not getting any results..

I tried cheating in an luminous crafting table in my test world and with it i tried crafting a petal apothecary but that wont even work so my guess is that interaction may not be working? i really do not know it anymore.. i tried reseting my game and even reinstalling my game but that did not work either ;I

I am also hosting a server which could be a problem factor but i am not sure at all about that since i tried doing astral sorcery with my singleplayer world and it did not work either..

Any help would be very appriciated!

![2019-05-26_16 32 29](https://user-images.githubusercontent.com/51053303/58383608-2496bc80-7fd9-11e9-8a26-5b19af990d47.png)

**Comment by NillerMedDild** [comment]
The Luminous Crafting Table can only be used if you have crafted one at some point, so that explains one of the issues.

As for the Crystal not working, sometimes they simply don't work because of calculations I don't really understand :P Have you tried other structures?

**Comment by IceyFoxy** [comment]
Maybe unloaded structures? like very very far off from my base since i did travel a bit.. gonna try that out soon, thanks for responding tho <3

**Comment by IceyFoxy** [comment]
It worked! All i had to do is to find a structure that was not loaded in yet, its cause is probably cause the world i am playing on is partially an old and new world (generation wise) so thats why it went wrong cause the crystal was most likely from the old world. Anyhow thank you for giving me the idea to find new structures <3
![2019-05-26_19 56 26](https://user-images.githubusercontent.com/51053303/58385415-654e0000-7ff0-11e9-8b6a-124be3ac222f.png)

**Comment by NillerMedDild** [comment]
Nice! :D
