### ISSUE TITLE
Astral Sorcery light beam from nowhere

### ISSUE THREAD

**Issue by Atadele** [NillerMedDild/Enigmatica2Expert#1217]
**Modpack version**
1.64d

**Issue**
Having a problem where this beam of light comes from nowhere. It is only on the horologium ritual. I have tried deleting the save data for astral, but it wont go away.

![2019-05-26_15 53 48](https://user-images.githubusercontent.com/50717541/58386543-3d9a7000-7fcf-11e9-9d06-c266f8f0656a.png)

If this is a feature request, feel free to delete the template.

**Comment by NillerMedDild** [comment]
Did you figure it out?

**Comment by Atadele** [comment]
Yeah sorry that was what is supposed to happen. My mistake, I didn't find anything in the Astral tome so I thought it was an issue.
