### ISSUE TITLE
Infinity booster card wont work.

### ISSUE THREAD

**Issue by chicklick** [NillerMedDild/Enigmatica2Expert#1218]
**Modpack version**
1.64d

**Can the issue be reproduced?**
Yes

**Issue**
I can open it and it takes a while for it to load all items and I can use it for a bit but then after like 20 seconds it just shows craftable items. I have 18 dense energy cells with a flux point connected to four of the energy cells with pretty much unlimited power. Sometimes it also says "No network power". I had 8 energy cells and added 10 more but the issue was still there.

**Comment by NillerMedDild** [comment]
Sounds like you need to chunkloaded your AE network.

**Comment by NillerMedDild** [comment]
Err also, I don't think putting Flux Points on the AE Energy Cells does anything, you need to power it through a Controller or Energy Acceptor.

**Comment by chicklick** [comment]
Its chunk loaded also I do have a flux point on the controller.

**Comment by NillerMedDild** [comment]
You're sure the entire network is chunkloaded? That includes Quantum Bridges.

**Comment by chicklick** [comment]
I dont have any quantum bridges and everything is chunkloaded except some crafting cpus

**Comment by NillerMedDild** [comment]
Well try chunkloading them as well. But I'll reopen and investigate when I get time.

**Comment by chicklick** [comment]
I chunkloaded the last cpu and broke the security teminal to relink it and also put 50 booster cards and now it seems to be working. It was probably because I didnt have any normal booster cards in the wireless access point.
