### ISSUE TITLE
Advanced rocketry bug(s)

### ISSUE THREAD

**Issue by gzcwnk** [NillerMedDild/Enigmatica2Expert#1219]
**Modpack version**
Input version here
1.62

**Can the issue be reproduced?**
unknown

**Logs**
Input pastebin link to crash-report or latest log, if applicable

none

**Issue**
Input short description of the issue here

a) Built a rocket and it sort of launched and then immediately landed back on earth (it was programmed for luna).  From then on when I launched it it didnt actually take off but the fuel drained away as if it had, rocket stayed on pad though.
b) Tried re-scanning and rebuilding and the guidence computer was not seen.  Broke unit, removed and re-added guidence computer then it was seen.  
c) restarted server however on restart rocket has gone invisible but still exists on the pad as I cant walk onto the platform I hit an "invisible force field" ie the blocks seem to be there sort of.
d) pressing E for inventory swapping from quantum armour chestplate to space suit chest plate while launched and climbing sees spacesuit chestplate disappear.
e) I used a layer of ali scaffold, as the base of the rocket's compartment this didnt render when the rocket was built but dis-appeared. This might have caused a, b and c?

If this is a feature request, feel free to delete the template.

**Comment by gzcwnk** [comment]
c) Restarted client a second time, rocket now visible on pad

**Comment by NillerMedDild** [comment]
Did you use the Aluminum Scaffolding from Immersive Engineering for the rocket?

**Comment by gzcwnk** [comment]
attempted to lift off again, rocket doesnt move but fuel drains away.

**Comment by NillerMedDild** [comment]
How long did you stay in the rocket after starting the lift off? Maybe it was moving without showing it, somehow.

**Comment by gzcwnk** [comment]
Yes I did going to remove it

**Comment by gzcwnk** [comment]
long enough to watch the fuel drop to zero

**Comment by gzcwnk** [comment]
rocket still on pad, I would have lost it if I'd exited?

**Comment by gzcwnk** [comment]
replacing ali scaffold with glass no change, same symptom, no movement but fuel empties.

**Comment by NillerMedDild** [comment]
Please try to rebuild the entire structure and rocket.

**Comment by gzcwnk** [comment]
total rebuild worked, thanks
