### ISSUE TITLE
Downgrade the modpack

### ISSUE THREAD

**Issue by Angelos33** [NillerMedDild/Enigmatica2Expert#122]
#### Issue Description
I would like to downgrade the modpack to 1.26c version but it doesn't let me. Is this on purpose or it's a twitch error?
#### Modpack version (Do not use "latest")
1.28

**Comment by XavierNero** [comment]
It's a twitch error, due to levels no longer existing however if you import this profile it will work as desired https://www.dropbox.com/s/oysof9gcq7o0kqz/Enigmatica%202%20Expert-1.26c.zip?dl=0

**Comment by Angelos33** [comment]
Thank you very much! How do i import it with the twitch app?

**Comment by XavierNero** [comment]
When you go into twitch go to mods, minecraft and there should be an option on the far right to create a custom Modpack,when you click this there should be an import option in blue text, click this then select the profile I sent you (should be in downloads) make sure you're not adding or changing other Modpack when you try to do this or it won't work

**Comment by XavierNero** [comment]
No problem

**Comment by NillerMedDild** [comment]
Thank you Xavier :)

**Comment by XavierNero** [comment]
No problem, I've opened enough issues to justify trying to help close at least one
