### ISSUE TITLE
Unable to craft Chemical Washer from Mekanism.

### ISSUE THREAD

**Issue by zach2045** [NillerMedDild/Enigmatica2Expert#1221]
**Modpack version**
1.62
**Can the issue be reproduced?**
Yes

**Logs**
N/a

**Issue**
I have discovered that players on our server are seemingly unable to craft the Chemical Washer from Mekanism. The recipe shows up in JEI however when the ingredients are placed into a crafting table there is no output. I have tried in every crafting bench I can think or but still can get it to craft the machine. I haven't ran into this issue with any other machines from the mod so far, I figured I would say something about it here to see if anyone might know how to fix this or if I am just missing something. 
https://gyazo.com/4c04514a40480e9158f2ef37c2f0759e

**Comment by zach2045** [comment]
I should also add that I discovered the Chemical Crystallizer has this same issue.

**Comment by Frikkle** [comment]
Can confirm this on 1.64d for the Chemical Washer.

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by Debonairesnake6** [comment]
I have also ran into this bug for a number of recipes that have been modified by crafttweaker, including the coke bricks and the vanilla chest. I have tried updating crafttweaker to the latest version however this did not resolve the issue. I am running the 1.64d version of the pack.

**Comment by NillerMedDild** [comment]
@Debonairesnake6 Sounds like the server is missing the scripts tbh.

**Comment by Debonairesnake6** [comment]
The server always had the scripts since I used the server pack files that were provided. I have also overwrote the scripts that were on the server with the ones from my client, however, the issue still remained. I can still make the recipes the vanilla way. I am using the McMyAdmin service for my server, however, I doubt that would be the cause of the issue since I have used multiple other modpacks with scripts set up the same way and have not had the issue.

**Comment by NillerMedDild** [comment]
Did you happen to disable AE channels?

**Comment by zach2045** [comment]
I am actually unable to craft them using both the modified and vanilla recipes. As far as I know we haven't disabled AE channels.

**Comment by NillerMedDild** [comment]
Oh sorry @zach2045, my question was directed at @Debonairesnake6 - I'll stop hijacking your issue now :P

You only have issues crafting those 2 Mekanism machines that you know of, right Zach?

**Comment by zach2045** [comment]
Oh no worries. I appreciate the feedback. As far as I know yes those are the only machines that I haven't been able to craft. That being said I don't think I have tried the machines I had already crafted before updating to 1.62. I will go through and see if I can find any others that have this same issue just in case.

**Comment by Frikkle** [comment]
I haven't experienced any crafting problems with Mek stuff as of late. Except for the Washer mentioned by @zach2045. But then again, I mainly progressed through all the quests, not that much beyond.

**Comment by Debonairesnake6** [comment]
I have disabled the AE channels, and sorry I thought this was the same issue otherwise I would have started a new ticket

**Comment by NillerMedDild** [comment]
No worries @Debonairesnake6 - disabling AE channels kills about 90% of the scripts, re-enable them to fix it, or remove the channel related recipes

**Comment by DarthCrater** [comment]
I'm still unable to craft the Chemical Washer in 1.65d. The recipe can be clicked in with JEI but does not function. All parts were freshly crafted.

I have not modified any scripts or config files. 

https://imgur.com/OzYerLQ

**Comment by NillerMedDild** [comment]
Dammit, thanks for letting me know.

**Comment by NillerMedDild** [comment]
Sigh, the old recipe works now :P I think the Mekanism components had some data they shouldn't, and that got patched in the latest Mekanism update.

**Comment by Libright1558** [comment]
This problem still persists,neither old recipe nor new recipe works.

**Comment by Frikkle** [comment]
What version have you tried this on? Afaik this has not been rolled out yet since 1.65d?

**Comment by NillerMedDild** [comment]
The recipe worked just fine for me in 1.65d.

**Comment by Frikkle** [comment]
-crawls behind his pc to build one-

**Comment by Libright1558** [comment]
I am using 1.65d version modpack,i will try to reinstall the modpack and test again.

**Comment by NillerMedDild** [comment]
Yup, my bad, it doesn't work. I don't know how it isn't working tbh - I'm reverting the recipe to default.

**Comment by Libright1558** [comment]
Chemical Crystallizer are also uncraftable,the recipe doesnt work.

**Comment by NillerMedDild** [comment]
Right, that is back to default as well :)

**Comment by DarthCrater** [comment]
For what it's worth, I applied the fix from e4a6211 to my 1.65d install and the crafting works perfectly since then.

**Comment by Libright1558** [comment]
> For what it's worth, I applied the fix from [e4a6211](https://github.com/NillerMedDild/Enigmatica2Expert/commit/e4a62112400bde9c37fe1578cddf969943e952e3) to my 1.65d install and the crafting works perfectly since then.

It doesnt work to me.

**Comment by NillerMedDild** [comment]
It worked for me too DarthCrater, but several others have issues with it, so default recipe it is :(

**Comment by Frikkle** [comment]
> What version have you tried this on? Afaik this has not been rolled out yet since 1.65d?

-coughs slightly-

**Comment by Libright1558** [comment]
> It worked for me too DarthCrater, but several others have issues with it, so default recipe it is :(

I just test the DarthCrater's way and it works,so it isnt necessary to return to default recipe.

**Comment by Frikkle** [comment]
The recipe was patched by Niller last night to work again. He fixed the recipe after the 1.65 releases. The change will be added next patch/release.

Thanks for confirming though.
