### ISSUE TITLE
 problem with the mod Enigmatica2Expert pleas help 

### ISSUE THREAD

**Issue by aboamer99** [NillerMedDild/Enigmatica2Expert#1222]
i have a problem with enigmatica 2 expert. There are some problems and I do not know why. When I log in, it tells me that only 186 Modes have been installed from the 268 and whenever I need to run the game I have to wait to install all the modules every time. The computer has 12 RAM and I use the game 6 RAM. I do not know where the problem is. I downloaded it from the site and the latest version of Modus 1.62 (enigmatica 2 expert)
These is some picture for problems

[https://imgur.com/2euk0SH](url)
[https://imgur.com/rOQR6lH](url)
[https://imgur.com/S47NpDY](url)
[https://imgur.com/byF0lfN](url)

I hope you have a solution

**Comment by NillerMedDild** [comment]
Where did you download that? It's not Enigmatica 2 Expert.
You say you downloaded the latest version of Modus, what is that?

The correct place to download the modpack is through the Twitch App.

**Comment by aboamer99** [comment]
[image: سيبسيب.png]
[image: سيب.png]
I downloaded it from Twitch I did not downloaded it from elsewhere

‫في الجمعة، 31 مايو 2019 في 8:54 ص تمت كتابة ما يلي بواسطة ‪Niels Pilgaard
Grøndahl‬‏ <‪notifications@github.com‬‏>:‬

**Comment by NillerMedDild** [comment]
Redownload it.
