### ISSUE TITLE
game crash

### ISSUE THREAD

**Issue by gzcwnk** [NillerMedDild/Enigmatica2Expert#1223]
**Modpack version**
Input version here

1.62

**Can the issue be reproduced?**
Yes/no/unknown

**Logs**
Input pastebin link to crash-report or latest log, if applicable

https://pastebin.com/zkHv9Czn

**Issue**
Input short description of the issue here

game crash,
===
The game crashed whilst rendering ingredient
The game crashed whilst rendering ingredient
Error: java.lang.NullPointerException: Rendering ingredient
===

If this is a feature request, feel free to delete the template.

**Comment by NillerMedDild** [comment]
Could you please provide some context? What were you doing when it happened?

**Comment by gzcwnk** [comment]
I was in a ME crafting terminal window, not 100% sure what I was doing at the time.

**Comment by NillerMedDild** [comment]
Can you play, or does it crash when you log in?

**Comment by gzcwnk** [comment]
No, runs fine, this is the first crash in a long time

**Comment by NillerMedDild** [comment]
In that case I'll close this issue, it looks like a random JEI crash. Feel free to reopen if it happens again.
