### ISSUE TITLE
Problems with book quest

### ISSUE THREAD

**Issue by aboamer99** [NillerMedDild/Enigmatica2Expert#1224]
**Modpack version**
1.64d

**Can the issue be reproduced?**
unknown

**Logs**
There is no
**Issue**
I have some problems in the  book quest where I can not see what's inside and my starting page looks different from the rest of the players

[https://imgur.com/rOQR6lH](url)

[https://imgur.com/s506lkn](url)

[https://imgur.com/2euk0SH](url)

**Comment by aboamer99** [comment]
I downloaded it from Twitch

**Comment by NillerMedDild** [comment]
Not sure why you would open another issue, but again, redownload the pack. You're missing all the non-default configs.

**Comment by aboamer99** [comment]
i am sorry i dont see your message
