### ISSUE TITLE
Update Common Capabilities to fix Int Dynamics / Tunnels Crash

### ISSUE THREAD

**Issue by scotty9090** [NillerMedDild/Enigmatica2Expert#1225]
E2E version: 1.64d

I was running into the crash below when using Integrated Tunnels:

https://github.com/CyclopsMC/IntegratedDynamics/issues/735

Per the ID mod author, this is fixed in newer versions of Common Capabilities.  The pack is on 2.2.1, and from what I can tell this looks like it's fixed in either 2.4.0 or 2.4.1.  I haven't had time to update myself and test it but assumed you'd want to know.

**Comment by NillerMedDild** [comment]
Thanks, I'll get that updated :)
