### ISSUE TITLE
Empowered Void Crystal (Block) recipe doesnt seem to make sense

### ISSUE THREAD

**Issue by FlyingThunder** [NillerMedDild/Enigmatica2Expert#1226]
**Modpack version**
1.64d

**Can the issue be reproduced?**
yes

**Issue**
the JEI recipe for empowered void crystal (blocks) makes no sense
(see here: https://imgur.com/a/lqoiigC)

both recipes are working (i tested, the infusion started), but you would lose 8 black iron ingots and 3 black quartz pieces if you would use the recipe for the single crystal and not the one for the block, not really an issue but this probably screws over a lot of people who dont carefully check both recipes first, i only noticed because i was suprised that one empowered void crytal takes a full block of black iron

**Comment by Discomanco** [comment]
It is really just following the trend that Actually Additions has going. The default recipes does the same thing, only difference is the energy cost
