### ISSUE TITLE
Compact Machines endless crafting loop

### ISSUE THREAD

**Issue by zach2045** [NillerMedDild/Enigmatica2Expert#1231]
**Modpack version**
1.62

**Can the issue be reproduced?**
Yes

**Logs**
N/a
**Issue**
After updating our server to v1.62 of the pack, whenever someone attempts to craft the 13x13 compact machine it will craft an infinite amount of said machine. It just continues to spit out copies of the machine and was only stopped after restarting the server. I was able to craft these fine on the previous version (1.59a) but this seems to happen every time I attempt to craft one of these machines. I have not yet tested the other machine sizes but I do know this happens consistently with the 13x13.

If this is a feature request, feel free to delete the template.

**Comment by NillerMedDild** [comment]
Please update to 1.64d (latest at the time of writing this) and see if the issue persists.

**Comment by saovenn** [comment]
In an older version of Spongeforge 2768, there was a problem with Compact machines where objects were infinitely crafted (infinitely dropped). This problem has been solved with the version spongeforge-1.12.2-2768-7.1.6-RC3643.jar on our servers

**Comment by zach2045** [comment]
Sorry for the late reply I was just able to get back to my pc. I tried updating spongeforge and that fixed the issue. Thank you so much for the help!
