### ISSUE TITLE
Most crafting table recipes that require iron plates require 9 instead of 1.

### ISSUE THREAD

**Issue by truehunterethan** [NillerMedDild/Enigmatica2Expert#1232]
Modpack version
1.64d

Can the issue be reproduced?
unknown

Logs
not applicable

Issue
Recipes like cauldrons require 9 iron plates each slot (so 63 total) instead of 7 total.

https://imgur.com/a/KVAWKXF
If this is a feature request, feel free to delete the template.

**Comment by MaxNeedsSnacks** [comment]
In most cases where there are iron plates on your end, there's supposed to be Dense Iron Plates instead. (for example with the armour or the Iron Chests upgrades).

I'm not sure about the Weighted Pressure Plate or Cauldron though... that's a bit of a weird one

**Comment by NillerMedDild** [comment]
Does the issue persist if you reinstall the modpack? Or even restart?

**Comment by truehunterethan** [comment]
I'll try to reinstall it, but it does persist after restart.

**Comment by NillerMedDild** [comment]
Are you sure all the ingredients are actually used? I'm thinking this is a visual bug in JEI.

**Comment by truehunterethan** [comment]
I can craft a cauldron with only 7 plates, but if i encode a pattern for a cauldron, it takes the 54 plates and uses all of them, even if manually encoded ( not using the JEI +) so it's fairly important. It does not go away after restart, reinstallation of modpack, and happens across all worlds.

**Comment by NillerMedDild** [comment]
Alright, damn, I'll have a look as soon as I get time, it might be a while though :/

**Comment by truehunterethan** [comment]
I FOUND IT. I forgot to add i added refined storage :p. asked reddit, heres the solution https://www.reddit.com/r/feedthebeast/comments/bw5lc2/a_lot_of_crafting_table_recipes_need_more_than/.

closed.
