### ISSUE TITLE
Cyclic Inventory Upgrade / Ice & Fire Hippogryph Conflict

### ISSUE THREAD

**Issue by TimBobWe** [NillerMedDild/Enigmatica2Expert#1233]
Minecraft Version: 
1.12.2

Forge Version: 
14.23.5.2836

Mod Version: 
Cyclic: 1.12.2-1.19.9
Ice & Fire: 1.7.1-1.12.2
Enigmatica 2: Expert 1.64d

Single Player or Server: Both

If you have eaten an Inventory Upgrade from Cyclic, thus unlocking the extra inventory slots and functionality, riding a Hippogryph from Ice & Fire breaks the player inventory. No items can be picked up and the player is unable to interact with Crafting Tables. Hippocampus do not seem to cause the same issue. All other mobs are untested.

Player is forced to Relog.

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by TimBobWe** [comment]
Upon retesting right now I am finding the bug to be less consistent than previously experienced.
The most consistenly unusable non-player inventory is the "Crafting Station" from Tinker's Construct.

The bug occurs after dismounting, not sporadically while mounted. This is a major oversight in my original description. My apologies.

**Comment by NillerMedDild** [comment]
No worries, thanks for the added info.

**Comment by Frikkle** [comment]
I just did a bunch of testing this on 1.64d and I did not manage to reproduce. I tried several scenarios both in SP and MP using creative and survival. I tried the inventory upgrade as well as several other crafting grids, to no avail.

There might be something else being of influence and causing this.

Could you:
1. Try to reinstall the pack?
2. Try reproduce the issue in a clean world and post the reproduction instructions here for us to test?
