### ISSUE TITLE
Items disappear when auto crafted with ae 2

### ISSUE THREAD

**Issue by Zacuis** [NillerMedDild/Enigmatica2Expert#1234]
**Modpack version**
Latest release. But this has been present at least the last 2 versions

**Can the issue be reproduced?**
You would be welcome to my save game. It's currently 600mb. But I'm unsure of the cause

**Issue**
At start up there are no issues.

(Actually that's not completely true. The crafting terminal remains without power until I break and replace the cable attaching it to the controller. But I think that unrelated to the issue that's game breaking for me)

Then after 10 to 15 minutes any item that is auto crafted deletes as it enters the system I've sat and watch the process take place but he newly crafted item never appears in the system. This is true weather it's a crafting assembler or a process with a machine. The items are exported and crafted fine but as they enter the system they disappear. I've not tested if items disappear if I manually throw them into an interface. But i will.

I've read that this used to be caused by deep storage units but I'm not using any. 
I've tried saving and re entering the game and this used to fix the problem for a further 10 - 15 minutes but now I have to reload the full pack.

Please help

If this is a feature request, feel free to delete the template.

**Comment by NillerMedDild** [comment]
I'm fairly certain that this isn't a bug, since this is the first I've ever heard of it. I'm going to redirect you to support, in the hope that the good folks there can help you out, because I don't currently have time to troubleshoot your setup with you. Please provide a link to this issue when you ask for support in the Discord linked below.
