### ISSUE TITLE
Can't pump seed oil or olive oil into Carpenter

### ISSUE THREAD

**Issue by Paceboy77** [NillerMedDild/Enigmatica2Expert#1236]
**Modpack version**
1.64d

**Can the issue be reproduced?**
Yes

**Issue**
I cannot pump seed oil or olive oil into the carpenter despite the recipe for treated sticks using it.  I am making sure to use the forestry seed oil.  I cannot pump the liquid in, cannot right click in it with a bucket, and cannot use the fluid fill (from item) slot to fill the internal tank.  This makes impregnated sticks impossible to craft.
![2019-06-04_20 26 54](https://user-images.githubusercontent.com/11807943/58922196-e5b6e400-8707-11e9-9d2c-93beede1060f.png)

If this is a feature request, feel free to delete the template.

**Comment by NillerMedDild** [comment]
Please restart the game and try again.
