### ISSUE TITLE
Thermal Dynamics takes too much tick time when connected with IC2 machines

### ISSUE THREAD

**Issue by Noodlebrain** [NillerMedDild/Enigmatica2Expert#1237]
**Modpack version**
1.64d

**Can the issue be reproduced?**
Yes

**Logs**
Screenshot using Lag Goggles (added into the pack for debugging purposes):
[Link. See "Event subscribers" column](https://cdn.discordapp.com/attachments/342128483377348623/585652689958993950/unknown.png)

**Issue**
With the version of Thermal Dynamics in version 1.64d, if ducts are connected to an IC2 machine,
unexpected behavior occurs and causes a massive amount of tick time; in my case, I have noticed server TPS going below 20.

The bug has already been fixed in a [more recent version of Thermal Dynamics.](https://github.com/CoFH/Version/blob/master/thermaldynamics_changelog.txt)

**Comment by Noodlebrain** [comment]
Never mind, TPS issues appear to be coming from a different cause.

**Comment by Frikkle** [comment]
Which cause? :) Just curious

**Comment by Noodlebrain** [comment]
About 15,000 villagers concentrated into 9 chunks.
