### ISSUE TITLE
Teleporting mobs - What?

### ISSUE THREAD

**Issue by Alexus13** [NillerMedDild/Enigmatica2Expert#1238]
**Modpack version**
1.64d

**Can the issue be reproduced?**
unknown

**Logs**
-

**Issue**
What mod or option make all mobs (zombies, skeletons, spiders, even TF nagas and others) random teleports after hit me?
How turn this thing off?

If this is a feature request, feel free to delete the template.

**Comment by Frikkle** [comment]
Are you running 1.64d stock? Did you do anything specific which might have caused this issue? Does the issue persist through server/client restarts? Are other players experiencing this issue as well? Is there anything noteworthy happening in the changelog?

I have not seen this before on 1.64d, so I would not know where to begin.

**Comment by NillerMedDild** [comment]
There is nothing in the pack that *should* cause that behaviour. Could it be server lag?

**Comment by MaienM** [comment]
There is an enchantment that will (randomly) teleport mobs that hit you away. It is called Repellent, and is added by Ender IO. Is it possible some of your armor has this enchantment on it?
