### ISSUE TITLE
server joining bug

### ISSUE THREAD

**Issue by LONELY05** [NillerMedDild/Enigmatica2Expert#1239]
enigmatica 2 expert 1.64d

Can the issue be reproduced?
unknown

![asdf](https://user-images.githubusercontent.com/51457078/59054752-0f554400-889d-11e9-86f4-5b8df30b4a3d.png)
issue
when i try to join a server it says
the server you were previously on went down, you have been connected to a fallback server i tried many times restart game in many hours

If this is a feature request, feel free to delete the template.

**Comment by NillerMedDild** [comment]
That doesn't seem like a modpack issue at all. Contact the server admin.

**Comment by LONELY05** [comment]
Okay

**Comment by MaxNeedsSnacks** [comment]
That's an issue with the server owner's... BungeeCord, I'm assuming (or Waterfall).

They're trying to send you from a hub server to the dedicated server, but the dedicated server seems to be down.

**Comment by LONELY05** [comment]
Ok thanks
