### ISSUE TITLE
serve problem

### ISSUE THREAD

**Issue by shordinger1** [NillerMedDild/Enigmatica2Expert#1241]
**Modpack version**
1.64d

**Can the issue be reproduced?**
yes，I‘ve produced these many times

**Logs**
![0@9DI EUTR3}X~8J2 K1N1R](https://user-images.githubusercontent.com/51524180/59155163-f8d60500-8ab5-11e9-8119-a788bb22fde5.png)

**Issue**

these is a problem with my serve.the serve and local game both installed succeed,but they can't connect withe each other.

If this is a feature request, feel free to delete the template.

**Comment by NillerMedDild** [comment]
The server and client are using different modpack versions.

**Comment by shordinger1** [comment]
I‘ve download your servepack from curseforge and it run successflly.but my local logs said"[11:54:07] [Netty Client IO #1/INFO]: Rejecting connection SERVER: Ender IO: Failed mod's custom NetworkCheckHandler FMLMod:enderio{5.0.44}
Ender IO Applied Energistics Conduits: Failed mod's custom NetworkCheckHandler FMLMod:enderioconduitsappliedenergistics{5.0.44}
Ender IO Conduits: Failed mod's custom NetworkCheckHandler FMLMod:enderioconduits{5.0.44}
Ender IO Integration with Forestry: Failed mod's custom NetworkCheckHandler FMLMod:enderiointegrationforestry{5.0.44}
Ender IO Integration with Tinkers' Construct: Failed mod's custom NetworkCheckHandler FMLMod:enderiointegrationtic{5.0.44}
Ender IO Integration with Tinkers' Construct: Failed mod's custom NetworkCheckHandler FMLMod:enderiointegrationticlate{5.0.44}
Ender IO Machines: Failed mod's custom NetworkCheckHandler FMLMod:enderiomachines{5.0.44}
Ender IO Open Computers Conduits: Failed mod's custom NetworkCheckHandler FMLMod:enderioconduitsopencomputers{5.0.44}
Ender IO Powertools: Failed mod's custom NetworkCheckHandler FMLMod:enderiopowertools{5.0.44}
Ender IO Refined Storage Conduits: Failed mod's custom NetworkCheckHandler FMLMod:enderioconduitsrefinedstorage{5.0.44}
Recurrent Complex: Failed mod's custom NetworkCheckHandler FMLMod:reccomplex{1.4.8.2}
[11:54:07] [Netty Client IO #1/ERROR]: Network Disconnect: Server Mod rejections:
Ender IO: Failed mod's custom NetworkCheckHandler FMLMod:enderio{5.0.44}
Ender IO Applied Energistics Conduits: Failed mod's custom NetworkCheckHandler FMLMod:enderioconduitsappliedenergistics{5.0.44}
Ender IO Conduits: Failed mod's custom NetworkCheckHandler FMLMod:enderioconduits{5.0.44}
Ender IO Integration with Forestry: Failed mod's custom NetworkCheckHandler FMLMod:enderiointegrationforestry{5.0.44}
Ender IO Integration with Tinkers' Construct: Failed mod's custom NetworkCheckHandler FMLMod:enderiointegrationtic{5.0.44}
Ender IO Integration with Tinkers' Construct: Failed mod's custom NetworkCheckHandler FMLMod:enderiointegrationticlate{5.0.44}
Ender IO Machines: Failed mod's custom NetworkCheckHandler FMLMod:enderiomachines{5.0.44}
Ender IO Open Computers Conduits: Failed mod's custom NetworkCheckHandler FMLMod:enderioconduitsopencomputers{5.0.44}
Ender IO Powertools: Failed mod's custom NetworkCheckHandler FMLMod:enderiopowertools{5.0.44}
Ender IO Refined Storage Conduits: Failed mod's custom NetworkCheckHandler FMLMod:enderioconduitsrefinedstorage{5.0.44}
Recurrent Complex: Failed mod's custom NetworkCheckHandler FMLMod:reccomplex{1.4.8.2}
It seems that enderio has some problem with custom mods.

**Comment by shordinger1** [comment]
sorry,i can't log on to this support channel.i am in china.

**Comment by NillerMedDild** [comment]
I've never seen that message before, but I think it can be a few things:
The client or server may be installed incorrectly, or they're on different versions.
Your server may be behind a firewall
Did you pay for your Minecraft account?

**Comment by shordinger1** [comment]
well，i do.
I copied your files straightly into .minecraft in a serve.I used to play mods with this.or i have to click servestart.bat to launch it?
 



------------------ 原始邮件 ------------------
发件人: "Niels Pilgaard Gr&#xF8;ndahl"<notifications@github.com>; 
发送时间: 2019年6月9日(星期天) 中午1:51
收件人: "NillerMedDild/Enigmatica2Expert"<Enigmatica2Expert@noreply.github.com>; 
抄送: "包子"<1690809117@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [NillerMedDild/Enigmatica2Expert] serve problem (#1241)




I've never seen that message before, but I think it can be a few things:
 The client or server may be installed incorrectly, or they're on different versions.
 Your server may be behind a firewall
 Did you pay for your Minecraft account?

**Comment by NillerMedDild** [comment]
Don't copy the server files to .minecraft, it needs to be in a new folder. Use the ServerStart.bat to launch it.

**Comment by shordinger1** [comment]
well，that may caused problem. Thanks for your help.In fact, I have play your game in my pc. It’s really a perfect mod pack.that’s why I
Introduced it to my classmates and build this serve.anyway,thank you for your game and help




发自我的iPhone

------------------ Original ------------------

**Comment by shordinger1** [comment]
I'm sorry to bother you.But here 's another problem about your modpack.
My server was in low tick rate.or ,the server warn me that "can't keep up!,did the system time changed or the server overloded?the server running ***ms behind,skipping ***ticks."


At first I thought the cpu or ram was not enought.But cpu utilization was less than 20%,and ram cost only 3G.I don't think it is caused by my server. 


What should I do to get a better environment in your modpack?I need your help, thank you
