### ISSUE TITLE
Feature Request: Ultimate Stew/ Cosmic Meatballs Nutrition

### ISSUE THREAD

**Issue by UnbreakableHoe** [NillerMedDild/Enigmatica2Expert#1242]
In the pack, both Ultimate Stew and Cosmic Meatballs have no nutritional benefits for Spice Of Life.
I think that nutrition should be added to both so as to make them have an actual, practical use, being edible, seeing as they are food items. Making late-game items is the only use I can see here, but if nether star on toast, a much easier item to make, in my opinion, has nutrition, shouldn't ultimate stew?. Thanks for hearing me out!

**Comment by NillerMedDild** [comment]
It totally should, I'll get that done - Thanks for the suggestion :)
