### ISSUE TITLE
Cyclic Piston Scepter duplicates Flux Points and Plugs

### ISSUE THREAD

**Issue by kaikue** [NillerMedDild/Enigmatica2Expert#1243]
**Modpack version**
1.64d

**Can the issue be reproduced?**
Yes

**Logs**
N/A

**Issue**
Shift-right-clicking a Flux Point or Plug from Flux Networks with a Cyclic Piston Scepter in Push or Pull mode will cause it to shift over by a block (as expected) but also drop a copy as an item. This isn't gamebreaking since the recipes are quite cheap anyway after getting the first core, but it is a dupe bug.

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by Frikkle** [comment]
Can confirm this.

**Comment by Frikkle** [comment]
Since you closed this at Cyclic, should we adjust labeling here?

**Comment by NillerMedDild** [comment]
Yep, I totally forgot ^^'
