### ISSUE TITLE
Sounds Cut Off

### ISSUE THREAD

**Issue by Azel0us** [NillerMedDild/Enigmatica2Expert#1247]
**Modpack version**
1.62

**Can the issue be reproduced?**
unknown

**Logs**
https://pastebin.com/RpBm0GDG

**Issue**
Sounds that play are cut off less than a second after starting. Does not occur on new profiles, started on the new profile on a server when I applied the Sphax Resource packs. Does not occur on new single player worlds on affected profiles.

**Comment by NillerMedDild** [comment]
That sounds completely like a Sphax issue to be honest.

**Comment by Azel0us** [comment]
Occurs when Sphax is no longer applied on the affected profile.

**Comment by NillerMedDild** [comment]
But it doesn't happen on new instances without Sphax, and only occurs after Sphax has been loaded?

**Comment by Azel0us** [comment]
Only tested this interaction once, but so far yes. Doesn't occur on a new singleplayer with Sphax loaded. Haven't done very rigorous testing, as it takes a significant amount of time to simply load a profile, as well as a texture pack.

**Comment by NillerMedDild** [comment]
Tell me about it, I can't even run it anymore.

**Comment by Azel0us** [comment]
Just loaded up a new profile, logged onto the server, adjusted no settings, applied no resource pack. Same issue.

**Comment by NillerMedDild** [comment]
Alright, did anything seem to trigger it, or did it happen immediately?

**Comment by NillerMedDild** [comment]
Btw, Shift+F8 reloads sounds by default.

**Comment by Azel0us** [comment]
It appears to be location based. In the process of moving, so shouldn't be a problem for too much longer (hopefully). Others in the same location do not seem to have an issue with it. We've removed almost every single machine, except a fusion reactor and a small enchantment setup.

**Comment by NillerMedDild** [comment]
Cool. Otherwise, updating to the latest modpack version might do the trick.

**Comment by osmanosman88** [comment]
I have this exact same issue. I have not had any resource packs which I'm planning to try a resource pack to see if that helps or not.
