### ISSUE TITLE
CRASH

### ISSUE THREAD

**Issue by BlackHoleTON618** [NillerMedDild/Enigmatica2Expert#1248]
**Modpack version**
latest

**Can the issue be reproduced?**
unknown

**Logs**
[hs_err_pid4032.log](https://github.com/NillerMedDild/Enigmatica2Expert/files/3304882/hs_err_pid4032.log)

**Issue**
when i use schematics it crash

**Comment by Frikkle** [comment]
By the looks of it you're using the Java version that comes pre-packaged with Twitch. This version is very old and causes issue with the recent forge version.

If you visit the E2E discord #support channel, there's instructions in a pinned message on how to solve this issue. (I'm on the road so not able to provide it here)

**Comment by Frikkle** [comment]
![image](https://user-images.githubusercontent.com/9324165/59763769-8fff4180-929a-11e9-96bf-f062be4a1291.png)
