### ISSUE TITLE
Feature request : Rock/Celestial crystals in fluid transposer

### ISSUE THREAD

**Issue by UnbreakableHoe** [NillerMedDild/Enigmatica2Expert#1249]
Hi, I thought this could be an interesting idea. Basically, it'd have the same function as dropping in fluid. You could decrease the processing speed too, it would just mean that on servers items would not despawn. I'm not sure if this is possible or worth it, and splitting would be difficult if at all doable to configure. Thanks for hearing me out anyways!

**Comment by Frikkle** [comment]
Interesting idea. As far as I know, E2E has been configured to not have items despawn by default, causing the rock crystals to be there in the morning if you leave them in a loaded over night.

**Comment by UnbreakableHoe** [comment]
Yes, but once they split they can despawn, being the reason I'd like to make it so you can only grow them without them despawning

**Comment by UnbreakableHoe** [comment]
My bad - I didn't specify that I meant servers with clearlag, as is often necessary.

**Comment by NillerMedDild** [comment]
I'm afraid that wouldn't be possible, complex recipes that randomly change NBT data cannot be made for the Fluid Transposer. It doesn't accept function recipes at all.
