### ISSUE TITLE
Cannot add admin settings to fix mekanism quest

### ISSUE THREAD

**Issue by DerpasaurusX** [NillerMedDild/Enigmatica2Expert#1250]
**Modpack version**
1.6.0

**Can the issue be reproduced?**
Yes

**Logs**
N/A

**Issue**
The quest for mekanism for the enrichment chamber won't complete (as I have seen other users facing the same problem), but when I go to use the /bq_admin complete <quest id> it won't let me saying I don't have permission to use the command. I also do not know how to find the quest ID or other data for quests and items.

**Comment by NillerMedDild** [comment]
You need to be OP to use `/bq_admin` commands.
You can find the quest ID by enabling advanced tooltips (F3+H) and hovering over the quests.

**Comment by DerpasaurusX** [comment]
It says that the /op <username> command is unknown? is there something I'm missing that isn't allowing me to op myself on my local offline server. I'm running the modpack through twitch and don't know that there is a different way to perform that action or what. Any help would be appreciated thanks.

**Comment by NillerMedDild** [comment]
You need to have cheats enabled. You can override it by opening the world to LAN and enabling it there.
