### ISSUE TITLE
Can't op myself in local twitch server

### ISSUE THREAD

**Issue by DerpasaurusX** [NillerMedDild/Enigmatica2Expert#1251]
**Modpack version**
1.6.0

**Can the issue be reproduced?**
Yes

**Logs**
N/A

**Issue**
I have tried making myself an op on my local minecraft server and it says the command is unknown. I am running the modpack through Twitch so I am not sure if there is a different way that I am supposed to do this process because I can't find any file in the game folder called ops or be able to do the command in game. It is just a local server not open to LAN or not multiplayer, but I need to be an op so I can implement a fix for better questing. Thank you in advance.

**Comment by NillerMedDild** [comment]
Weird that you decided to open a new issue for a question you already asked. You need cheats enabled.

**Comment by Frikkle** [comment]
Oh noes, I came out of bed to tackle this one. Either way: if you're not sure how to get cheats enabled on LAN, use google, or read the docs: https://minecraft.gamepedia.com/Commands It's all in there.

**Comment by DerpasaurusX** [comment]
Well that is the problem, I know how to use google search to look up how to make yourself an op, and I turned to LAN to enable cheats but it still won't let me op myself due to it being "an unknown command", which is why I am asking if there is something that you guys may have experienced that is different with having myself go through twitch for my modpack or what. I also created a new issue because I don't know if you visit comments after you close the issue, my apologies.

**Comment by NillerMedDild** [comment]
You don't have to OP yourself in a single player world with cheats enabled, the OP command is only available on servers. Just use the  `/bq_admin` command you want to after enabling cheats.
