### ISSUE TITLE
Advanced Rocketry Space station cannot be used by multiple players

### ISSUE THREAD

**Issue by AnotherRandomBugReporter** [NillerMedDild/Enigmatica2Expert#1252]
**Modpack version**
1.64d

**Can the issue be reproduced?**
Yes
To reproduce, build and go in a space station, the player who created the space station can walk freely on it, but others will get invisible wall bug and teleportation on certain parts of the station.

**Logs**
https://pastebin.com/M5u9VKCn
Short video that shows the problem : https://youtu.be/ErB_7-yAYPY

**Issue**
There is a bug that prevent multiplayer on space stations, if a player create a space station he can move freely but the others can't because of invisible walls and strange teleportation, the space station is not usable for these players and they do not see the planets above. The bugged players doesn't see the stations the same way as the player who launch the space station see it. For the bugged players the player who launch the space station walk in the void. We have tested to reproduce this bug in a fresh created server and it happens again, but with only advanced rocketry it does not happen. We have also tested a lot of methods to launch the space station even to go in the same rocket at the same time but every attempts is a failure.

**Comment by NillerMedDild** [comment]
Thanks for the report, I'll look into it. 
Your server is a dedicated server without SpongeForge, correct? :)

**Comment by AnotherRandomBugReporter** [comment]
Yes it's the server provided by CurseForge with no changes :  https://minecraft.curseforge.com/projects/enigmatica2expert/files/2712606

**Comment by Frikkle** [comment]
Just a small question: does this manifest itself on a client-server setup? Or are you perchance running a LAN-hosted instance? I suspect it's the former; but we have seen rendering issues with LAN-setups recently (#1244).

**Comment by AnotherRandomBugReporter** [comment]
This appears on a client-server setup, I did not try with LAN setup. I tried with the CurseForge server without any modifications.

**Comment by Frikkle** [comment]
Thanks for the reply. I'll have a look at it on our server tonight.

**Comment by Frikkle** [comment]
@stefancdr could you ping me tonight to test this out on my space station?

**Comment by Frikkle** [comment]
Just tested this with @stefancdr on my space station. Stefan was able to see all the blocks as I would expect and I could see him as well as him seeing me. So I cannot reproduce this.

**Comment by AnotherRandomBugReporter** [comment]
This is fixed in the latest version of the modpack.
Everything is working as excepted this time, the only thing I did is reset the space dimension by removing the "advRocketry" folder in the world save.

Thanks for you help !

**Comment by Frikkle** [comment]
No problem, happy to hear this has been resolved.
