### ISSUE TITLE
Rendering screen - Out of index - Main Menu

### ISSUE THREAD

**Issue by dnulho** [NillerMedDild/Enigmatica2Expert#1253]
**Modpack version**
1.64d

**Can the issue be reproduced?**
Unknown

**Logs**
[Rendering screen crash.txt](https://github.com/NillerMedDild/Enigmatica2Expert/files/3332915/Rendering.screen.crash.txt)

**Issue**
I was playing along, and tried to do a JEI Search using the '|' (Shift+\)  symbol. When I typed that, my game switched between Full-Screen and windowed mode. I tried several times, and then went into settings/controls to try to determine what was causing it and to disable the offender. On typing that key into the search bar, my game froze and crashed. On trying to boot back into the game it crashes with a rendering screen/out of index error. I did have optifine on while playing, but the crash is continuing even after i removed optifine.

**Comment by NillerMedDild** [comment]
Deleting your options.txt file should fix this :)

**Comment by dnulho** [comment]
I ended up doing a full reinstall of the pack...

**Comment by NillerMedDild** [comment]
And that worked?

**Comment by dnulho** [comment]
Other then apparently losing my /resources folder, (#1254) which I have had happen to about 3/4 of my installs of this pack...
