### ISSUE TITLE
Missing/Broken Main Menu and Quest Book Textures

### ISSUE THREAD

**Issue by dnulho** [NillerMedDild/Enigmatica2Expert#1254]
**Modpack version**
1.64d

**Can the issue be reproduced?**
Yes, this issue is happening on multiple stations, including Ubuntu 18.04, Win 7, Win 10, and MacOS v?. 

**Logs**
NA

**Issue**
Main menu and questbook textures are broken.
![E2-E Main Menu](https://user-images.githubusercontent.com/5905416/60241289-67111a80-985f-11e9-93a1-8e350dd4f039.png)
![Questbook Texture](https://user-images.githubusercontent.com/5905416/60241548-09310280-9860-11e9-8985-f4ac0e3cb10e.png)

**Comment by NillerMedDild** [comment]
You're missing the resources folder.

**Comment by dnulho** [comment]
Is there a location that I can get a copy of the resources folder?

**Comment by NillerMedDild** [comment]
https://www.curseforge.com/minecraft/modpacks/enigmatica2expert/download/2712599
It's under the overrides folder.
