### ISSUE TITLE
[1.65] Exception ticking world caused by Advanced Rocketry

### ISSUE THREAD

**Issue by Frikkle** [NillerMedDild/Enigmatica2Expert#1258]
**Modpack version**
1.65

**Can the issue be reproduced?**
Yes

**Logs**
See referenced issue for log examples; mine were similar. Deleted my 1.65 instance already so don't have the log at hand anymore.

**Issue**
After updating from 1.64d to 1.65, our server won't start anymore and throws a ticking world exception caused by `java.lang.NoSuchFieldException: delegate` in Advanced Rocketry. There has been an issue created at the official repo (https://github.com/zmaster587/AdvancedRocketry/issues/1611).

~~Status at the AR repo is still "Unconfirmed Bug".~~ No known workaround found so far.

Status has been updated to "bug" by the mod author.

**Comment by Frikkle** [comment]
Might be worth noting that we've had players go to space already. I would not be surprised if this issue doesn't show when that's not the case.

**Comment by Frikkle** [comment]
Fixed and released in new version. I'll check with a local install if it resolves the issue in E2E.

**Comment by Frikkle** [comment]
After updating Advanced Rocketry from `AdvancedRocketry 1.12.2-1.6.0-149-UNSTABLE` to `AdvancedRocketry 1.12.2-1.6.0-150-UNSTABLE` the server does start as expected without this issue.

**Comment by Frikkle** [comment]
At a glance our server does what it's supposed to do. If there are issues they are 1.65 issues and unrelated to this AR patch.

@NillerMedDild I think this can be patched/hotfixed.

**Comment by NillerMedDild** [comment]
Perfect, thanks.
