### ISSUE TITLE
Modpack freezes so when hovering over the bottom item slot of an Integrated Dynamics Machine Reader.

### ISSUE THREAD

**Issue by skyboy1963** [NillerMedDild/Enigmatica2Expert#1259]
**Modpack version**
1.65a

**Can the issue be reproduced?**
Yes

**Logs**
https://pastebin.com/XCPLFLpR

**Issue**
When hovering over the item slot in the bottom selection of the machine reader from integrated dynamics, the game freezes and I have to force close it. Don't know if this was an issue before since I just made the machine reader, but it seems very gamebreaking.

**Comment by Frikkle** [comment]
Thank you for the report, We will investigate the issue.

**Comment by NillerMedDild** [comment]
What is the Machine Reader connected to?

**Comment by Frikkle** [comment]
I tried several simple setups with vanilla Furnaces and Chests as well as some Thermal Expansion machines; can't get it to crash so far. So we would definitely need some more information about your setup.

**Comment by skyboy1963** [comment]
Here is the setup: https://imgur.com/a/bHOsOR9

**Comment by Frikkle** [comment]
I reproduced the bug as follows:

1. Place a Mechanical Squeezer.
2. Place a Machine Reader against one of its sides.
3. Place a piece of Logic cable against the reader.
4. Open the reader interface.
5. Crash.

See logs [here](https://paste.dimdev.org/acacunezuc.mccrash)

**Comment by Frikkle** [comment]
Before reporting this to the mod owner I would like to test this in an Integrated Dynamics only modded server. I'll do that in the morning; afterwards I will report it to the mod author if need be.

**Comment by Frikkle** [comment]
Just reproduced this with just `IntegratedDynamics`, `CommonCapabilities` and `CyclopsCore`.

**Comment by Frikkle** [comment]
Apparently this has been fixed a while ago; updating to the latest versions of `CommonCapabilities`, `CyclopsCore` and `Integrated Dynamics` should fix it.

**Comment by NillerMedDild** [comment]
I just updated all the ID mods though. They should be on latest. Will verify tonight.

**Comment by Frikkle** [comment]
I just checked; in 1.65b they are at:

- `CommonCapabilities-1.12.2-2.4.3`
- `CyclopsCore-1.12.2-1.4.0`
- `IntegratedDynamics-1.12.2-1.0.16`
