### ISSUE TITLE
[1.65a] Extreme server lag caused by Advanced Rocketry

### ISSUE THREAD

**Issue by Frikkle** [NillerMedDild/Enigmatica2Expert#1260]
**Modpack version**
1.65a

**Can the issue be reproduced?**
unknown (but experienced and reported by other people on the internet as well)

**Logs**
n/a

**Issue**
After upgrading our server from 1.64d to 1.65a, the server performance went down horribly. From 20tps steady (with small fluctuations when exploring) to 6-8 tps continuously.

[Screenshots](https://imgur.com/a/tZ546Wk) indicating the server tps as well as the LagGoggles analysis showing incredibly high load on the AdvancedRocketry Event Subscribers. This hasn't been the case on 1.64d.

This issue was already reported by on the Advanced Rocketry issue tracker (see https://github.com/zmaster587/AdvancedRocketry/issues/1614).

Current issue status is "Unconfirmed Bug".

**Comment by NillerMedDild** [comment]
Downgraded Advanced Rocketry and Lib Vulpes, bumped version to 1.65b

**Comment by Frikkle** [comment]
Shall we leave this issue here to keep monitoring it? We can then update AR on a next release.

**Comment by NillerMedDild** [comment]
Yeah let's :)

**Comment by Hextical** [comment]
I can also confirm downgrading Advanced Rocketry and Lib Vulpes fixed my server tick lag.

**Comment by Frikkle** [comment]
This has been fixed in build 154+. We would need to do some testing with it.
