### ISSUE TITLE
[1.65] Positive Coal loop using EnderIO

### ISSUE THREAD

**Issue by KaseiFR** [NillerMedDild/Enigmatica2Expert#1261]
**Modpack version**
1.65

**Can the issue be reproduced?**
Yes

**Issue**
I'm not sure if this is intended or not, but there is a positive Coal loop using EnderIO: grinding Coal in a Sag Mill has a 10% chance (even without grinding balls) to yield a second Pulverized Coal, which can be turned into Coal again using several other machines.

Since Coal is very common, you can already make it from Charcoal, and you should have automatic mining by the time you get to EnderIO, this is not a very serious issue.

 PS: the Octadic Capacitor recipe is pure evil

**Comment by NillerMedDild** [comment]
It isn't intended, but I don't mind either :)

And thank you :P
