### ISSUE TITLE
[1.65c] /dank/null crash after upgrading, downgrading and then upgrading

### ISSUE THREAD

**Issue by stefancdr** [NillerMedDild/Enigmatica2Expert#1262]
**Modpack version**
1.65c

**Can the issue be reproduced?**
Yes (in SMP), no (in creative SP)

**Logs**
https://paste.dimdev.org/mihixamege.mccrash

**Issue**
After upgrading to 1.65b and moving the /dank/null from inventory to quickbar, the game immediately crashes. Also, the texture of the /dank/null (emerald one, in this case) is broken (pink/black).

This appears to be fixed in an (unreleased) 1.74 version of /dank/null, but as I said, that's an unreleased version :-).

Cannot reproduce in SP when creating a new (empty) emerald  /dank/null, so it's probably a problem with some form of item in the /dank/null.

**Comment by Frikkle** [comment]
This issue has already been reported at the mod's issue tracker; see https://github.com/p455w0rd/DankNull/issues/181

**Comment by Frikkle** [comment]
Side-effects from this issue are that the affected player cannot log in anymore. You would need to edit the /dank/null out of the player's inventory manually.

The bug doesn't manifest itself for all players; on the same server my (also Emerald tier) Dank Null worked fine after the upgrade. It did however have rendering issues.

**Comment by NillerMedDild** [comment]
Dammit, I guess 1.65c will be the release then :P

**Comment by stefancdr** [comment]
Not to necro this, but even in 1.65c, switching the 'active' item in the /dank/null (using alt+click) crashes the /dank/null due to an error in ItemUtils. I would deem it likely this is a version mismatch in E2E; did you perchance rollback /dank/null to an earlier version, but not rollback 'password' util? (I can't spell that name properly, sorry :-)).

This [commit](https://github.com/p455w0rd/p455w0rds-Library/commit/1f15894d076060072ba4853e28b2d2f1f2d11bb1#diff-6d66e818bbd33fdfa68c2303d79eb734) seems to have changed it from 'areItemStacksEqual' to 'areItemsEqual', hence why a newer/older version of /dank/null might expect the one method rather than the other.

**Comment by NillerMedDild** [comment]
God dammit I may have, double checking.

**Comment by NillerMedDild** [comment]
and I'm guessing the new Wireless AE mods from Password need version 151 >_<

**Comment by NillerMedDild** [comment]
1.65d going up now, sorry about that.

**Comment by stefancdr** [comment]
Can confirm 1.65d fixes my issues.

For future reference: to test if this crashes, try switching active block of the /dank/null with alt+click when having it open, this crashed it in 1.65c.
