### ISSUE TITLE
Crash when trying to type  '&$§ or #' in applied energistics crafting grid

### ISSUE THREAD

**Issue by SeseMueller** [NillerMedDild/Enigmatica2Expert#1263]
**Modpack version**
Newest, launched from Twitch

**Can the issue be reproduced?**
Easily, on a German Keyboard (I don't know whether that's important)

**Issue**
The game crashes, when you try to write '&%§ or #'(the key for jei oreDict etc. searching)  in the crafting grid of a ME System (AE). This occurs while using a non-english (a German) keyboard. 

**Hint**
Unlike other crashes, the game simply doesn't respond (windows immediately detects the crash) and the CPU and GPU usage instantly goes to 0. 
The logs don't say anything from around the time the game crashed.

**Comment by Frikkle** [comment]
We just tried to reproduce this using several characters, it does indeed cause the game to hang and seem non-repsonsive, but it does recover after a minute or so.

**Comment by Frikkle** [comment]
In trying to reproduce the issue I noticed that this only happens to the crafting terminal; pattern terminal is unaffected. Additionally, after it happens once and you wait out the lag/freeze, it won't happen again.
