### ISSUE TITLE
[Suggestion] Allow the Immersive Engineering Metal Press to make Uranium Plate

### ISSUE THREAD

**Issue by KaseiFR** [NillerMedDild/Enigmatica2Expert#1264]
**Modpack version**
1.65

**Can the issue be reproduced?**
Yes

**Issue**
The Metal press can make most of the plates, and is fun to automate, but it cannot make Uranium Plate. I don't think it would be a gating issue since the plates can be made in a Casting Table too.

If this is a feature request, feel free to delete the template.

**Comment by NillerMedDild** [comment]
Woops, that's an oversight :)
