### ISSUE TITLE
Custom recipes using Rock Crystals should accept any rock crystal

### ISSUE THREAD

**Issue by iNko97** [NillerMedDild/Enigmatica2Expert#1267]
**Modpack version**
1.64d

**Feature Request**
The custom recipes for:
Celestial Altar, Starlight Crafting altar, Runic Altar, Mana Pool, Block of Prosperity, Golemancer's Bell should use the Oredict crystalAstralAny (as it is in all the other recipes native to Astral Sorcery). 
The oredict alternatives this would introduce are the Attuned version of rock crystals, and the celestials, so nothing game breaking as they are more work to obtain.

It is quite tedious having to either mine or keeping a second crystal splitter different from celestial just for the custom rock crystal recipes, since in all of the other normal Astral sorcery you can use the more complex alternatives.

**Comment by NillerMedDild** [comment]
I understand your frustration, but I've attempted this time and time again, it doesn't seem to be possible. The Crystal oredict doesn't work, and I haven't been able to get the custom crystal CraftTweaker method to work either.
