### ISSUE TITLE
[1.65c] /dank/null crash due to linkage issue with p455w0rdslib

### ISSUE THREAD

**Issue by shellbj** [NillerMedDild/Enigmatica2Expert#1268]
**Modpack version**
1.65c

**Can the issue be reproduced?**
Unknown

**Logs**
https://paste.dimdev.org/okepinasic.mccrash

**Issue**
Newly created /dank/null, setting oredict modes for inputs causes a crash when open (or closing?) the GUI.

The method's signature was changed in this commit: https://github.com/p455w0rd/p455w0rds-Library/commit/7f1ff3ef88da5c874f69c50f4bf44cf1f20aa60f#diff-6d66e818bbd33fdfa68c2303d79eb734

Current version of /dank/null is 1.5.71
Pack's version is 1.4.43

p455w0rdlib is latest in the pack.

**Comment by NillerMedDild** [comment]
Updating to 1.65d should fix this :)
