### ISSUE TITLE
Fusion Reactor / Flux Networks Bug Produces Insane Amount of Energy

### ISSUE THREAD

**Issue by BobACanOfKoosh** [NillerMedDild/Enigmatica2Expert#1271]
**Modpack version**
1.64d

**Can the issue be reproduced?**
unknown

**Logs**

**Issue**
So a simple fusion reactor with a toroid size of 4 combining liquid tritium and lithium-7 is producing 1000x more energy than it should.

The problem apparently was that I had a flux point connected to the top of the fusion reactor, and had a flux plug taking the output power from the reactor. They were both on different networks, connected to an induction cell from mekanism. When the flux point was on the top, the output was ~30m RF/t, and it wasnt just a short circuit loop of the input also being 30m RF. I was inputting 10m RF/t into the fusion reactor and out came 30m RF/t. I fixed it by simply removing the flux point, and the output became normal.
![2019-07-11_14 37 25](https://user-images.githubusercontent.com/52800205/61087948-acefe600-a3fc-11e9-843e-d067f313f3c4.png)

![2019-07-11_14 28 38](https://user-images.githubusercontent.com/52800205/61087952-b37e5d80-a3fc-11e9-875e-d94fd003eb88.png)
![2019-07-11_14 24 29](https://user-images.githubusercontent.com/52800205/61087966-bbd69880-a3fc-11e9-8890-05b3a74ef416.png)

![2019-07-11_14 17 42](https://user-images.githubusercontent.com/52800205/61087985-c8f38780-a3fc-11e9-8232-d14663a1313a.png)

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by stefancdr** [comment]
@BobACanOfKoosh : how long did this peak last? The fusion reactor does have a fairly large internal buffer, perhaps you were draining that? (in your first screenshot, it's internal buffer is full-ish).
