### ISSUE TITLE
[SOLVED] Crash on Startup after Update 1.56 to 1.65d: Mixin config mixins.phosphor.json requires mixin subsystem version 0.7.10

### ISSUE THREAD

**Issue by BuggaNoia** [NillerMedDild/Enigmatica2Expert#1272]
**Modpack version**
1.65d just updated from 1.56

**Can the issue be reproduced?**
Yes: Happens on every startup at "Start" in Launcher

**Logs**
[latest.log](https://pastebin.com/kXJJCRf5)
Guess the following line shows the issue:

> Mixin config mixins.phosphor.json requires mixin subsystem version 0.7.10 but 0.7.5 was found. The mixin config will not be applied.

Then:
> [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.mixin.transformer.MixinConfig.checkVersion(MixinConfig.java:417)

**Issue**
Minecraft crashes just on start in the launcher

**Comment by NillerMedDild** [comment]
Deleting the `memory_repo` folder from your mods folder should do the trick :)

**Comment by BuggaNoia** [comment]
Didn't work :( 
Exactly the same exception in latest.log

**Comment by BuggaNoia** [comment]
Found it!:

I added 

> LagGoggles-FORGE-1.12.2-4.1.jar 

to v1.56 what was working there.

> LagGoggles-FAT-1.12.2-4.6.jar 

is working with v1.65d / Forge #2836. Both older versions failed.

So: Solved

**Comment by NillerMedDild** [comment]
Remember to say when you've changed the pack please :)
