### ISSUE TITLE
Shulker Crash

### ISSUE THREAD

**Issue by SteamFi** [NillerMedDild/Enigmatica2Expert#1273]
**Modpack version**
Input version here
1.65d (Version I actually used shulkers on)
**Can the issue be reproduced?**
Yes/no/unknown
Yes
**Logs**
Input pastebin link to crash-report or latest log, if applicable
https://pastebin.com/FBtfPq47
**Issue**
Input short description of the issue here
Whenever you hover an item above a shulker (I've done so with just a crystal) you'll be able to right click to place said item into the hovered shulker without needing to place it. This WILL crash your game and any other time at all that you hover your cursor over the shulker.

SOLUTION FOR THOSE WHO SUFFER: Took me like 2 hours to find out specifically why and I used a player interface from Actually Additions with a hopper and a chest to fully remove all my items from my inventory (except the Cyclic extended inventory) and then proceeded to give myself all my items back, placed those into another chest, and broke the original chest with the shulker in it so it'd be in my hotbar. I then placed the shulker and punched it out of this corporeal realm and deleted the chest. I was then able to play again with no more crashes. I now avoid shulker boxes just to be safe.

If this is a feature request, feel free to delete the template.

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
Fixed in a new version of Quark :)

**Comment by MorganSimic** [comment]
Until fixed, a known workaround is disabling the shulker box tooltip option in quark.

**Comment by SteamFi** [comment]
Thanks and I didn't know that was from quark either so thanks x2, lol.

**Comment by Frikkle** [comment]
@NillerMedDild this has just been reported happening on 1.69b in Normal as well. Could you investigate?

**Comment by NillerMedDild** [comment]
Sure, I disabled the config on normal, so fixed in dev. It should be fixed by Quark though.
