### ISSUE TITLE
Enchantment Duplication

### ISSUE THREAD

**Issue by osmanosman88** [NillerMedDild/Enigmatica2Expert#1274]
**Modpack version**
1.65d

**Can the issue be reproduced?**
Yes

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Issue**
I tried this with diamond mesh (may be applicable to other mesh's) on a server. I put my mesh's (3 of em) in the Enchantment Applicator,and put sieve effiency v on them and realised that it enchanted the whole stack. With this you can duplicate enchants that go on there like soulbound and etc... Not too sure of what you can do for this if it has a config to disable stacked items in there or what. Thank you for reading.

**Comment by NillerMedDild** [comment]
Yeah I know, it's a side effect of increasing their stack size. Let's call it a feature :P
