### ISSUE TITLE
RFTools Builder Exception Ticking World

### ISSUE THREAD

**Issue by Frikkle** [NillerMedDild/Enigmatica2Expert#1277]
**Modpack version**
1.65d

**Can the issue be reproduced?**
Yes

**Logs**
[Here](https://puu.sh/DUqAx/4a116d6782.txt)

**Issue**
This issue was reported by a user on Discord running into a crash when using the RFTools Builder's preview function while using a shape card. The issue was already reported to McJty and is known there; though the cause is unknown.

I asked the user on Discord to try and reproduce this in an instance with just RFTools in there and provide us with an additional log.

For reference: https://github.com/McJtyMods/RFTools/issues/1961

**Comment by Frikkle** [comment]
After testing (by the reporting user) with an instance using just RFTools, and McJtyLib it is reproducible. Rendering the first preview goes fine; the second one crashes the game.

Corresponding logs: [here](https://pastebin.com/M5DZA57m)

**Comment by Frikkle** [comment]
The issue was reproduced, found and fixed by McJty and will be fixed in the next release.

**Comment by MaxNeedsSnacks** [comment]
As Frikkle said, this was fixed by McJty and the mod has since been updated in version 1.66c (commit 0b33096) ^^
