### ISSUE TITLE
Rustic config bug

### ISSUE THREAD

**Issue by vtecem** [NillerMedDild/Enigmatica2Expert#1278]
**Modpack version**

1.65d

**Can the issue be reproduced?**

Yes

**Issue**

Rustic's armor and toughness configuration interfere with the extra mods which allow the bars to overlap (overpoweredarmorbar & toughnessbar).

**Resolution**

Update to the following in Rustic.cfg

        B:"Extra Armor HUD"=false

        B:"Armor Toughness HUD"=false

**Comment by Frikkle** [comment]
Thank you for reporting.

This is known, but it was forgotten in the release. It's scheduled to be patched/rolled out next release.

**Comment by MaxNeedsSnacks** [comment]
Fixed in 0ee573e
