### ISSUE TITLE
[Quality of Life Feature Request] AE2 Smart Dense Cable from 4x Smart Cable

### ISSUE THREAD

**Issue by rux616** [NillerMedDild/Enigmatica2Expert#1279]
**Modpack version**
1.65d

**Request**
Currently, AE2 dense smart cables can only be made from dense covered cables. I propose that a new crafting recipe be added so they can be made from 4x smart cables with the same recipe layout as dense covered cables made from 4x covered cables.

**Comment by NillerMedDild** [comment]
Thanks for the request, I'll look into it :)
