### ISSUE TITLE
Mod Feature Request: Oversaturation

### ISSUE THREAD

**Issue by jaxx050** [NillerMedDild/Enigmatica2Expert#1280]
https://www.curseforge.com/minecraft/mc-mods/oversaturation

Simple mod. Lets you actually have a use for all the high-end foods that mods like Pam's and Avaritia can add by making saturation points above 20 not be useless.

**Comment by NillerMedDild** [comment]
I like the mod idea, but I'm reluctant to add it because of this issue: https://github.com/truenachtara/Oversaturation/issues/6

**Comment by jaxx050** [comment]
Aahhh. That's really unfortunate, given that AppleCore is pretty much standard now. Hopefully they get it resolved, if the developer is still active.
