### ISSUE TITLE
Biogas Generates Twice as Much HU as it Should

### ISSUE THREAD

**Issue by Wfb282** [NillerMedDild/Enigmatica2Expert#1283]
**Modpack version**
IC2

**Can the issue be reproduced?**
Yes

**Issue**
Biogas burns twice as long when it's used it a Liquid Firebox. It burns for 1000 tics in Semi-Fluid Generator but 2000 tics in Liquid Firebox. As a result, Liquid Firebox + Stirgind Generator  generates 32kEu in total compared to 16kEu from Semi-Fluid Generator

**Comment by NillerMedDild** [comment]
That is intended.
