### ISSUE TITLE
EU2 Coils not able to be used as fuel (Same as #651)

### ISSUE THREAD

**Issue by Mx772** [NillerMedDild/Enigmatica2Expert#1284]
**Modpack version**
1.65d

**Can the issue be reproduced?**
Yes

**Logs**
Logs show no log output

**Issue**
When inserting into the fuel slot of vanilla furnace, mystical agriculture Ultimate Furnace, tinker's construct Heater, cooking for blockheads Oven it gets dropped on ground or returned to inventory.

--Breaking Block & rebooting server did not fix

Gif:
https://media.giphy.com/media/RGplFfPE0P2KHLpAuz/giphy.gif

Looks like this happened in #651 but breaking the block resolved it. Unfortunately not so in this scenario.

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by Melodeiro** [comment]
Happens only if you don't have Wireless RF Battery nearby. Not intuitive behaviour, but i guess, thats not a bug.
