### ISSUE TITLE
Expert Java not responding

### ISSUE THREAD

**Issue by rjzvara** [NillerMedDild/Enigmatica2Expert#1285]
**Modpack version**
Expert 1.65d

**Can the issue be reproduced?**
unknown

**Logs**
https://pastebin.com/Y1Fa42R3

**Issue**
game seems to hang and checking network I/O waiting a sub thread seems to be stuck then java usually crashing within a few a seconds

**Comment by rjzvara** [comment]
and it is usually when im moving and jumping alot

**Comment by Frikkle** [comment]
You provided a (part of) your latest.log file it seems. Does that mean that no crash-report was created by the server?

Additionally, in the log file you provided I see this `Memory: 4619MB total, 1382MB free`. The Expert pack needs a minimum of 6G ram to properly run.

If there was no crash-report generated this matches the not enough memory suspicion. When a minecraft server runs out of resources it tries to shut down gracefully.

Could you:
- confirm that you're running the server with enough RAM assigned?
- provide a crash-report

**Comment by rjzvara** [comment]
in the twitch launcher under java settings i have this Java Settings
Java Version 1.8.0.221 64-bit

Allocated Memory
Allocated: 8192 MB


Additional Arguments
-Xms64M

**Comment by rjzvara** [comment]
also i am playing in single-player

**Comment by NillerMedDild** [comment]
I recommend you remove those additional arguments, and add these: `-version:1.8+ -XX:+UseG1GC -Dsun.rmi.dgc.server.gcInterval=2147483646 -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M`

**Comment by NillerMedDild** [comment]
Please let me know if changing that helps :)

**Comment by rjzvara** [comment]
games seems to run fine now i dont know if it will pop up again
