### ISSUE TITLE
[Item Deletion]Time in a Bottle on a External Heater powered FastFurnace deletes items.

### ISSUE THREAD

**Issue by Moleculor** [NillerMedDild/Enigmatica2Expert#1286]
**Modpack version**
Enigmatica 2: Expert v1.65d

**Can the issue be reproduced?**
Yes

**Logs**
I reproduced the bug multiple times in the last five minutes, but the logs for the last two hours are just server backups, so nothing about this shows up in the logs.

**Issue**
Apply a [Random Things v4.2.7.1] Time In A Bottle item to a [FastFurnace v1.3.1] Furnace (the one that looks like a vanilla furnace) while that Furnace is heated by an [Immersive Engineering v0.12-89] External Heater.

The furnace will eventually 'blink' off (sometimes rapidly like it's in a rave), deleting input and output contents of the furnace. 

Two applications of the bottle *risk* creating this issue. Three applications almost guarantee it. Four applications of the bottle definitely guarantee it. 

I'm providing links to the issues I've opened in the respective mods just to help everyone out.

[Enigmatica 2: Expert](https://github.com/NillerMedDild/Enigmatica2Expert/issues/1286)
[Random Things](https://github.com/lumien231/Random-Things/issues/432)
[FastFurnace](https://github.com/Shadows-of-Fire/FastFurnace/issues/13)
[Immersive Engineering](https://github.com/BluSunrize/ImmersiveEngineering/issues/3526)

**Comment by NillerMedDild** [comment]
Thanks for letting me know.

**Comment by LelouBil** [comment]
Why is this closed ?

**Comment by NillerMedDild** [comment]
Because the developers of IE and FastFurnace won't fix it, there's nothing more we can do about it I'm afraid.
