### ISSUE TITLE
Precision Sawmill Auto-Crafting (ME Controller Input/Output) issue

### ISSUE THREAD

**Issue by MasonWandersee** [NillerMedDild/Enigmatica2Expert#1287]
**Modpack version**
1.66c

**Can the issue be reproduced?**
Yes

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Issue**
Precision Sawmill Auto-Crafting.
There is absolutely no way to change the sawmill config to input the items from a ME Controller then output back up to it automatically. I think this is a bug unless perhaps there is some sneaky way to get this to work. I'm trying to craft 6 sticks with a wood plank automatically. Thank you kindly as I really wish to get my auto-crafting recipes all set up fluently 100%! - Vuz

If this is a feature request, feel free to delete the template.

**Comment by MasonWandersee** [comment]
It can be manually done by Changing its top block output/input to first be the red square(input) then dark blue square(output). Not sure if this helps. Thanks again!

**Comment by MasonWandersee** [comment]
By the way, shouts out to NillerMedDild for the most amazing mod-pack. Its my second time running thru it. Can't get enough :)

**Comment by NillerMedDild** [comment]
Glad you like it :D 

Mekanism machines do not allow input and output from the same side. You can simply take input from an ME Interface and then pipe the output from another side into the ME Interface.

**Comment by Frikkle** [comment]
As an additional side note, the ME Interface you pipe the crafted items into doesn't have to be the same interface that put the items into the machine in the first place. Any ME Interface (within the same network) would suffice.
