### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by A47C** [NillerMedDild/Enigmatica2Expert#1289]
**Modpack version**
1.66c

**Can the issue be reproduced?**
No?

**Logs**
https://pastebin.com/EdcxKqXn

**Issue**
It always takes a few crashes before I finally can launch the modpack. Today it crashed 4 times, yesterday - 3. I'm scared I'll have to go through 5 crashes next time I wanna play xD. 
Thank you~

**Comment by Discomanco** [comment]
You appear to be using outdated Java. This is often caused by Twitch defaulting to an older version than you have available. Follow these steps to update.

* Make sure you have the latest 64-bit Java installed
    https://www.java.com/en/download/manual.jsp Windows Offline (64-bit) is the one you need
* Go to the Twitch Minecraft settings
* Add -version:1.8+ to the Additional Arguments

**Comment by A47C** [comment]
Oh, apparently twitch uses the Java version (1.8.0.51 64-bit) it installs itself in [twitch app]/Install/runtime/jre-x64 directory. It can't be changed in twitch app settings (it's not clickable) but it's possible to make a modpack use any other java version in mojang's launcher. I'll try to do exactly that, thanks.

**Comment by A47C** [comment]
Seems to work just fine now! Thank you for help.

**Comment by NillerMedDild** [comment]
The last step Disco said changes Java version, I recommend you do that instead of through the launcher.
