### ISSUE TITLE
Server blocks indestructible after updating to 1.66c

### ISSUE THREAD

**Issue by themaster402** [NillerMedDild/Enigmatica2Expert#1291]
**Modpack version**
1.66c

**Can the issue be reproduced?**
Unknown

**Logs**
https://drive.google.com/file/d/1EEta31rQSbXy_3dRVd53qOFYyxSHak2i/view?usp=sharing

**Issue**
Upon updating the server from 1.65d to 1.66c, tile entities become indestructible by players. They can be moved with sacks of holding. Dirt cannot be destroyed without an IC2 drill. Other blocks cannot be destroyed at all.

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by Frikkle** [comment]
I have upgraded our servers from 1.65d to 1.66c yesterday and everyone has been playing as expected. I wouldn't know where to start debugging this without more information.

**Comment by themaster402** [comment]
Downgrading to 1.65d allows the server to function as usual. I was running SpongeForge-2838-7.1.7-RC3859 along with the Nucleus, LuckPerms, CatClearLag, and MagiBridge plugins. No anomalies appear in the server or client console upon attempting to break a block.
I've also discovered that mobs, after being hit once, cannot be hit anymore.

I've tried removing Sponge, but the issue is still extant.

**Comment by Frikkle** [comment]
That's quite the deviation from the stock setup; does the issue also manifest itself when using stock E2E? I don't have a Sponge setup with the additional plugins, so I can't reproduce this.

**Comment by themaster402** [comment]
Seems to have been fixed in https://github.com/SpongePowered/SpongeForge/commit/156f70c86b6e4ce55ca270ccde9be875f246060f. I launched the server adding the updated Sponge and all issues have been reversed. Thanks and apologies for any inconvenience.
