### ISSUE TITLE
Feature request: crafttweaker recipe addition

### ISSUE THREAD

**Issue by jaxx050** [NillerMedDild/Enigmatica2Expert#1292]
Feature request: the colored AE2 cablings of normal and dense variety can't have their colors removed, except by using a single bucket of water on a single cable, making it unbearably tedious to uncolor cables you want to reuse. Idea is to add either an oredict option for the water so you can use something like Pam's fresh water to batch craft them, or give them an 8 to 1 ratio craft like how you color them initially so you can remove the dye 8 at a time instead of 1.

**Comment by NillerMedDild** [comment]
I'll think about it :)

**Comment by NillerMedDild** [comment]
It's still incompatible with E2E
