### ISSUE TITLE
Crafting amount imbalance, easy duping

### ISSUE THREAD

**Issue by jaxx050** [NillerMedDild/Enigmatica2Expert#1293]
**Modpack version**
1.65d

**Can the issue be reproduced?**
Yes

**Logs**
No logs.

**Issue**
Crafting the Amber Block from Thaumcraft can be done by either TC's amber, or BoP's amber, however, when you craft it, the return recipe actually gives you 9 of the BoP amber, even though it only costs 4 to craft, allowing you to infinitely craft duplicate it for free.

**Comment by NillerMedDild** [comment]
Update.
