### ISSUE TITLE
Schematica error

### ISSUE THREAD

**Issue by BlackHoleTON618** [NillerMedDild/Enigmatica2Expert#1294]
**Modpack version**
1.66c

**Can the issue be reproduced?**
unknown

**Logs**
[crash-2019-07-31_09.55.26-client.txt](https://github.com/NillerMedDild/Enigmatica2Expert/files/3450235/crash-2019-07-31_09.55.26-client.txt)

**Issue**
when i use schematica it doesnt shows the blocks and mc crashes

**Comment by Frikkle** [comment]
According to the logs you are running Minecraft with the embedded JRE that comes with Twitch. This is a very old java version that causes a lot of issues and crashes.

Your problems most likely will be fixed when you:
1. Make sure you have a recent 64-bit Java installed and accessible through in your environment variables.
2. Go to the Twitch global settings page, then the Minecraft tab and then add a JVM argument ``

**Comment by BlackHoleTON618** [comment]
it says error unable to locate jre meeting specifation 1.8+

**Comment by BlackHoleTON618** [comment]
now its not opening anymore

**Comment by Frikkle** [comment]
Did you install 64-bit Java 8 and added it to your path? Your system apparently cannot detect any Java installation.

Check https://www.java.com/en/download/help/path.xml for instructions on how to do this.

**Comment by BlackHoleTON618** [comment]
i downloaded latest java and its not even launching anymore and your code cant be deleted  how you gonna fix that

**Comment by BlackHoleTON618** [comment]
Error could not crate the Java virtual machine Error a fatal exception has occurred  Program will exit

**Comment by Frikkle** [comment]
I don't understand your comments. If you cannot get Java installed on your system and the path environment set up correctly I suggest you take a look at other means of installing the pack. This can be achieved through MultiMC or installing it by hand.

**Comment by NillerMedDild** [comment]
Keep in mind you need 64-bit Java.

**Comment by BlackHoleTON618** [comment]
i did all you said BUT my mc is broken and i cant open any modpacks now you corrupted my mc please fix it

**Comment by NillerMedDild** [comment]
Continuing this on Discord.
