### ISSUE TITLE
Crashes during startup - Phosphor

### ISSUE THREAD

**Issue by TheMCProf** [NillerMedDild/Enigmatica2Expert#1295]
**Modpack version**
1.66c

**Can the issue be reproduced?**
Yes. By disabling and enabling Phosphor.

**Logs**
https://pastebin.com/cN0rFTZW

**Issue**
The pack crashes during startup. The minecraft loading screen wouldn't even load.

**Comment by NillerMedDild** [comment]
Did you modify the pack in any way? Add mods, change config etc.

**Comment by TheMCProf** [comment]
I added a couple: LagGoggles, VanillaFix, Optifine, InGameTime(r). Didn't change any configs

**Comment by Frikkle** [comment]
@NillerMedDild: I am also running with LagGoggles and VanillaFix. Those work fine for me.

@TheMCProf: Optifine does cause crashes for me at times. So I stopped using it.
Additionally, are you using Sponge?

**Comment by TheMCProf** [comment]
No, I don't use Sponge.
Also, I found out what was causing the problem - LagGoggles. I could load the modpack again after disabling it, but it worked fine in previous versions of the pack.

**Comment by Frikkle** [comment]
Without knowing which versions you're running I can't check if I can reproduce it. I am running our servers and clients with LagGoggles installed and it works flawlessly with version 4.6.

Either way, glad to hear you have resolved your issue. I'm closing this for now.
