### ISSUE TITLE
Pattern Terminal Autofilling Sag Mill Recipes Crash

### ISSUE THREAD

**Issue by KrakenG7** [NillerMedDild/Enigmatica2Expert#1296]
**Modpack version**

1.66c

**Can the issue be reproduced?**
Yes, just by trying to autofill a sag mill recipe in an AE2 pattern terminal

**Logs**
https://pastebin.com/c2JDBq7d

**Issue**
The client crashes whenever I try to create any sag mill recipe pattern

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by Frikkle** [comment]
Just tried to reproduce this with both the Simple SAG Mill and the SAG Mill in an ME Pattern Terminal. Anything I could have overlooked?

Does this issue occur in a single player world as well? And/or does it persist through client/server restarts?

**Comment by jaxx050** [comment]
Confirming this happens for me as well, MP as well, consistent crash. I'm on 1.65d currently but didn't see any patch notes about this being fixed so adding here.

**Comment by KrakenG7** [comment]
> Just tried to reproduce this on 1.66c with both the Simple SAG Mill and the SAG Mill in an ME Pattern Terminal. Anything I could have overlooked?
> 
> Does this issue occur in a single player world as well? And/or does it persist through client/server restarts?

did you try to... craft the sag mill itself?

I'm talking about the processing patterns for sag mill recipes

I only know it crashes in singleplayer, and it does persist through both client and server restarts

**Comment by Frikkle** [comment]
@jaxx050 Could you give me some more details/steps to reproduce? Are you using stock E2E or do you have other mods/configs/sponge installed?

**Comment by Frikkle** [comment]
@KrakenG7 ah, that explains. I was doing the sag mill itself. I have it autocrafted last night. But I will try a processing pattern.

**Comment by NillerMedDild** [comment]
The bug needs to be reposted here: https://github.com/p455w0rd/JustEnoughEnergistics/issues
I'll do it eventually unless one of you beat me to it, hint hint :P

**Comment by Frikkle** [comment]
Kraken already did this morning; I added some additional information and I'll try to reproduce it tonight.
