### ISSUE TITLE
Creative Builder's Wand not craftable

### ISSUE THREAD

**Issue by TheIvyX** [NillerMedDild/Enigmatica2Expert#1298]
**Modpack version**
Enigmatica 2 Expert 1.65d

**Can the issue be reproduced?**
Yes

**Logs**
N/A

**Issue**
The Unbreakable Wand used in the recipe for the Creative Builder's Wand has a metadata of 0 and has no recipe whereas the craftable one has a metadata of 12. The Creative Wand therefore cannot be crafted.

![image](https://user-images.githubusercontent.com/17356752/62251237-1a1fe700-b3bd-11e9-8f49-05bb12ae12c7.png)

![image](https://user-images.githubusercontent.com/17356752/62251239-1db36e00-b3bd-11e9-8659-9dd05e2fbcb6.png)

**Comment by NillerMedDild** [comment]
It's set to accept any metadata.
