### ISSUE TITLE
Unexpected Crash After New Update

### ISSUE THREAD

**Issue by OpusTheMoose** [NillerMedDild/Enigmatica2Expert#13]
Issue Description
When logging into my world, I experienced an unexpected crash. This happened after I updated to the latest version of the game. 
What you expected to happen
I expected to log in normally, just like every other time I've been able to log in. I was successfully able to log back into my world when I downgraded to version 1.06. 
 Modpack version (Do not use "latest")
Version 1.07
 Your most recent log file where the issue was present
https://pastebin.com/7MH3sYpJ

**Comment by NillerMedDild** [comment]
The crash seems to be caused by a food item incorrectly registering it's data. If you put all your inventory items in a chest, and then update, you should be fine. 

Alternatively, you can use NBTExplorer to remove items from your player.data, but that's more of a hassle.

Please let me know if it works.

**Comment by NillerMedDild** [comment]
Any update?

**Comment by OpusTheMoose** [comment]
Soo sorry for getting back to you so late. I put my items in a chest, and the game is still experiencing a crash. At this point, I'm not really sure what could be causing it. (Crash report below)
https://pastebin.com/rDGNPL1w
I'll try to get back to you faster next time.

**Comment by NillerMedDild** [comment]
No worries.
I think you should delete your player.data, that ought to do the trick.

**Comment by OpusTheMoose** [comment]
Alright, as a bit of an update, I deleted me player.data. Unfortunately, it is STILL crashing. I narrowed it down a little bit, but not much success. I've opened a new world in update 1.07, and it works fine. My only guess is that I recently changed my minecraft name, so maybe the twitch launcher is getting confused? Otherwise, no clue. (Crash report linked below)
https://pastebin.com/FfsvXwFS

**Comment by NillerMedDild** [comment]
Are you sure you deleted all your player data? It's multiple files

**Comment by OpusTheMoose** [comment]
I really don't want to ask, but where are some of the player data files? I've deleted the ones in the world's save folder, but it still crashes. Are there any other player data files?

**Comment by NillerMedDild** [comment]
There are 6 seperate files per player in the playerdata folder in your world, and there are atleast 3 more in the data folder. If you're playing SP, I suggest you delete both the "playerdata" and "data" folder.

If that still doesn't do the trick, you can try removing Spice of Life: Carrot Edition and readd it once you've loaded up your world.

**Comment by OpusTheMoose** [comment]
Welp, after deleting all my data it still crashes.
then i just removed SOL Carrot and it worked. problem resolved. :D
