### ISSUE TITLE
PlusTic Trait "Prosperous"

### ISSUE THREAD

**Issue by WhirlyZaph** [NillerMedDild/Enigmatica2Expert#130]
The Trait Prosperous doesn't work with Crossbows(?).

Expert 1.26C

No Crash Report. I'm not sure if Prosperous doesn't work with Crossbow (not the bolt) or the chance of dropping the shards is around <1%?

![2018-06-25_10 01 27](https://user-images.githubusercontent.com/40259033/41828330-dda0156a-785e-11e8-8358-31e9600c82ef.png)

**Comment by NillerMedDild** [comment]
Prosperous only works when breaking blocks.
