### ISSUE TITLE
nbt mismatch with creative tank

### ISSUE THREAD

**Issue by MasterSloth1** [NillerMedDild/Enigmatica2Expert#1300]
**Modpack version**
Verision 1.66c

**Can the issue be reproduced?**
Yes

**Issue**
went to create the creative tank noticed i couldnt click the Plus button in jei so i placed it all by hand and still couldnt craft the recipe. looking at the nbt data for the recipe
RECIPE ITEMS/NBT DATA
![2019-08-01_20 16 52](https://user-images.githubusercontent.com/34207969/62277408-35acef80-b49a-11e9-9247-5a6f25e959db.png)
![2019-08-01_20 16 55](https://user-images.githubusercontent.com/34207969/62277410-36458600-b49a-11e9-913e-daa703d204ae.png)
![2019-08-01_20 16 59](https://user-images.githubusercontent.com/34207969/62277411-36458600-b49a-11e9-89ff-fb055b19db0c.png)
![2019-08-01_20 17 01](https://user-images.githubusercontent.com/34207969/62277412-36458600-b49a-11e9-8686-b371a68f3931.png)

i noticed that my tanks are different, I tried with tanks that have been placed in the world and ones that havent both with the same result
MY ITEMS/NBT DATA
![2019-08-01_20 24 01](https://user-images.githubusercontent.com/34207969/62277556-7f95d580-b49a-11e9-9947-17da36825049.png)
![2019-08-01_20 24 03](https://user-images.githubusercontent.com/34207969/62277557-7f95d580-b49a-11e9-94bf-9af861761a2d.png)
![2019-08-01_20 24 05](https://user-images.githubusercontent.com/34207969/62277558-7f95d580-b49a-11e9-9680-fa6ec8461eab.png)
![2019-08-01_20 24 07](https://user-images.githubusercontent.com/34207969/62277559-802e6c00-b49a-11e9-874f-6cbd69cb4eec.png)

**Comment by NillerMedDild** [comment]
Thanks for the screenshots, very helpful :)

I don't think the tanks are the issue - NBT tags are inclusive, meaning it only requires that one tag you see in JEI - As long as that tag matches, the rest of the tags don't matter.

Have you double checked all the buckets? I know Milk is pretty easy to get mixed up for one.

**Comment by MasterSloth1** [comment]
yea when i hover over the pus icon in jei it shows like this
![2019-08-01_20 16 33](https://user-images.githubusercontent.com/34207969/62336090-d21ad480-b522-11e9-924d-173f9ce9dace.png)

**Comment by NillerMedDild** [comment]
Hmm.. have the Black Hole Tanks been placed, do they have any nbt? 0 tags would also count.

**Comment by MasterSloth1** [comment]
they where freshly made so nope never been placed before

**Comment by MasterSloth1** [comment]
All 4 are identical to that
![2019-08-02_16 36 51](https://user-images.githubusercontent.com/34207969/62344845-cee41080-b543-11e9-8fa8-7f5f1404e909.png)

**Comment by NillerMedDild** [comment]
Dammit :P I'll look into it. I hope you can cheat it in and void the materials :)

**Comment by MasterSloth1** [comment]
i can ill hold onto all the mats for now until a new version of the pack is released incase u need more info :D

**Comment by NillerMedDild** [comment]
Perfect, thank you.

**Comment by MasterSloth1** [comment]
lol soo i cheated in a creative tank and yea the quest book doesn't recognize it lol
QUESTBOOK ITEM/NBT DATA
![2019-08-02_17 15 07](https://user-images.githubusercontent.com/34207969/62346192-4d8f7c80-b549-11e9-98aa-ef09dff8c4f8.png)

MY ITEM THAT I CHEATED IN/NBT DATA
![2019-08-02_17 15 12](https://user-images.githubusercontent.com/34207969/62346213-65670080-b549-11e9-84ae-063ecf71f570.png)

**Comment by MasterSloth1** [comment]
so the questbook recognizes the tank once u place the tank in your personal crafting table and recraft it, but NOT if u pluck it straight from jei

**Comment by NillerMedDild** [comment]
I know, there's no way around that :)

**Comment by NillerMedDild** [comment]
Although the tanks cannot be shift-clicked into the table with the JEI `+`, the recipe works just fine at the moment. It may have been fixed in the (very long) time it took me to investigate.
