### ISSUE TITLE
Structural Engineer Villager's Final Trade has Wrong Copper Ingot

### ISSUE THREAD

**Issue by AwesomeAim** [NillerMedDild/Enigmatica2Expert#1301]
**Modpack version**
1.65d

**Can the issue be reproduced?**
Yes, tested in my survival world and a fresh creative world.

**Issue**
![image](https://user-images.githubusercontent.com/30537683/62338221-96353000-b48c-11e9-8032-faa7d4bf35a2.png)
![image](https://user-images.githubusercontent.com/30537683/62338231-9df4d480-b48c-11e9-9f1c-edfa1475d49d.png)
The map-like item is a mineral deposit map for a specific ore, but I have no way to get it as the copper ingot it requests is from Immersive Engineering

**Comment by Frikkle** [comment]
You can convert the copper via Forge Lexicon, a simple "book" that can convert oredict stuff

**Comment by NillerMedDild** [comment]
While this really sucks, we can't fix it unfortunately :( I hope Frikkles workaround does the trick.

**Comment by Frikkle** [comment]
I have done exactly this in version 1.63 of the modpack and it worked just fine. I needed it to get some Immersive Engineering items.
