### ISSUE TITLE
Feature Request: Make Astral Sorcery Max Perk Level Higher

### ISSUE THREAD

**Issue by KrakenG7** [NillerMedDild/Enigmatica2Expert#1302]
Hi, If it's not much of an issue, it would be awesome if we could have more perk levels for Astral Sorcery, it's more fun to play with those

thanks

**Comment by NillerMedDild** [comment]
I'll consider it :)

**Comment by MorganSimic** [comment]
I personally haven't played much with the new perk system but from what i have seen Hellfire did a lot of work to make such a vast tree somewhat resembling balance. And the results i have seen are really insane what you can achieve. I think it would not be good balance wise to increase the cap higher than intended in this pack. One of the difficult dicissions arises from that fact that you only have so many skillpoints to spent and a vast number of perks to choose.

**Comment by Frikkle** [comment]
+1 on what Morgan said. It is annoying that you cannot get all cool stuff at once, but then again, that would be ridiculously overpowered. Attuning to a certain constellation means that you choose to align yourself with it and thus with the perks that go with it. Explaining that there's other things you cannot do.

**Comment by NillerMedDild** [comment]
Good points, thanks for the suggestion regardless :)
