### ISSUE TITLE
Supremium Pickaxe Incorrect mining level

### ISSUE THREAD

**Issue by KrakenG7** [NillerMedDild/Enigmatica2Expert#1303]
**Modpack version**
1.66c

**Can the issue be reproduced?**
Yes

**Logs**
N/A

**Issue**
Supremium Pickaxe does not have correct mining level

![2019-08-01_22 49 29](https://user-images.githubusercontent.com/37258603/62343068-ecb36600-b4ae-11e9-9703-df8b0a3f8dd2.png)

**Comment by Frikkle** [comment]
Has you pickaxe been modified with sharpening kits by any chance? If it has a sharpening kit with a lower tool material the item adopts that material for the mining level. Just checking.

**Comment by KrakenG7** [comment]
It's a mystical agriculture Supremium pick, not tinker's

**Comment by NillerMedDild** [comment]
You're meant to use Tinkers exclusively, that's why the harvest level of "ordinary" tools is lower.
