### ISSUE TITLE
Dank/Null

### ISSUE THREAD

**Issue by SgtZocker** [NillerMedDild/Enigmatica2Expert#1304]
Why was Dank/Null in Version 1.67 removed?

**Comment by Frikkle** [comment]
/Dank/Null has had a lot of stability issues over the last year; the mod author decided to remove all versions from CurseForge except 1.5.71 (which is unstable and has client crashes, player file corruption and is incompatible with upgrades from older versions).

The versions that are in use in the Enigmatica 2 packs are not available for download anymore, hence we cannot keep them in the pack. Once there's a stable reliable fix and version out for the general public we can and will reconsider adding it.

**Comment by SgtZocker** [comment]
hmmm ok

**Comment by GrimTheReaper** [comment]
@Frikkle you might not want to add them back in anyway, as I'm on 1.65d and Dank Nulls are still duplicating.

**Comment by ben-mkiv** [comment]
well, it says that its close to be fixed. 
I think its not a good move to remove such item, as many people play on servers where they cant control when the update happens (and they arent even aware of the removed dank/null before the update) so a lot of people will lose their stuff in the dank/null

**Comment by NillerMedDild** [comment]
I had no choice, the update had to happen and it could not get approved if Dank/Null was left in.

**Comment by InjuredWolf** [comment]
Dank null recently updated with all bugs fixed, according to the changelog. Is it likely we'll see it re-added next update?

**Comment by NillerMedDild** [comment]
It is highly unlikely, as it could break worlds updating from 1.64d.
