### ISSUE TITLE
[MineTweaker] Alumite alloying math incorrect

### ISSUE THREAD

**Issue by Landmaster** [NillerMedDild/Enigmatica2Expert#1305]
https://github.com/NillerMedDild/Enigmatica2Expert/blob/92af8c610b66967fff8818af93b0a716cd4bf1d9/scripts/TinkersConstruct.zs#L36-L39
Author of PlusTiC here. This should be 432 and 864mB of Alumite, respectively, not 216 and 432mB. 3 Alumite Ingots should be created per 5 Aluminum, but the script incorrectly specifies 1.5 ingots.

The liquid values for Iron and Obsidian should both also be doubled, as there is 2 iron and 1 block of obsidian (=288 mB) per 5 Aluminum/3 Alumite, not 1 iron and 0.5 block.

Hence, the correct alloying ratio should be

720 Aluminum + 288 Iron + 288 Obsidian = 432 Alumite
1440 " + 576 " + 576 " = 864 Alumite

**Comment by Frikkle** [comment]
Thank you for nothing and reporting this. I suspect that @NillerMedDild did this on purpose when designing the pack. There's more alloys in there that yield less resulting metals when alloyed. Might be for the purposes of the expert pack.

But it could be an oversight as well. I'll leave the issue unlabeled for now and leave it to Niller to respond.

**Comment by Landmaster** [comment]
Fair enough. If this alloy ratio was intentional, then it might be a good idea to add a recipe for the Adv. Metallurgic Fabricator to yield more Alumite. However, I don't think it was intentional because no other alloy in the pack is balanced this way (e.g. 1 Osgloglas = 1 of each main Mekanism metal is the same as default).

**Comment by NillerMedDild** [comment]
This is indeed a mistake, I think at the time I was thinking the recipe would negate the ore doubling bonus, but that doesn't really apply :P

**Comment by Landmaster** [comment]
@NillerMedDild You forgot to double the Iron and Obsidian liquid values in the ratio.
