### ISSUE TITLE
[CoFH World] Parse error

### ISSUE THREAD

**Issue by Landmaster** [NillerMedDild/Enigmatica2Expert#1306]
https://github.com/NillerMedDild/Enigmatica2Expert/blob/master/config/cofh/world/16_advanced_rocketry_planets_ore.json#L228

The brackets around `minecraft:end_stone` should not be there.

**Comment by MorganSimic** [comment]
Confirmed, those brackets are not right. When i read that right, it prevents the generation of endstone clusters on certain planets.  I'm wondering why is that even there? Just for flavour or am i reading this file completely wrong?

**Comment by NillerMedDild** [comment]
Yep just flavour :)
