### ISSUE TITLE
Bibliocraft bookcase can not accept Integrated Dynamics book

### ISSUE THREAD

**Issue by Moleculor** [NillerMedDild/Enigmatica2Expert#1307]
**Modpack version**
E2:E 1.67

**Can the issue be reproduced?**
Yes

**Issue**
The bibliocraft bookcase is designed to accept books. It can accept most books. It won't accept "On the Dynamics of Integration", the Dynamic Integration book/manual.

The change needed to the bibliocraft.cfg file is described here: https://www.bibliocraftmod.com/wiki/bookcase/

It's likely you'd need to add 'dynamics of integration' as a single keyword rather than just 'dynamics' to avoid enabling the whole mod to go in there, but that's just me guessing.

**Comment by NillerMedDild** [comment]
I'll get that fixed, thanks :)

**Comment by MaxNeedsSnacks** [comment]
not sure why but i just forgot to merge my changes into master for a solid 4 weeks, anyway this is gonna be solved in the next release ^^

**Comment by NillerMedDild** [comment]
Nice one :P
