### ISSUE TITLE
Ice and Fire Statue Entities not being destroyed properly

### ISSUE THREAD

**Issue by Mcgrolox** [NillerMedDild/Enigmatica2Expert#1308]
**Modpack version**
1.66c

**Can the issue be reproduced?**
Yes

**Logs**
log.latest too large for pastebin lite.

**Issue**
If you use a quark soul bead to get the curse effect (mobs spawn regardless of biome/light levels) trolls will be among the mobs that spawn, and if its in daylight they turn to stone form as normal. However when you go to mine them (using a pickaxe, I've tried vanilla, tinkers, both with and without silk touch, and a few other mod tools that count as pickaxes for mining such as the Atomic Disassembler from Mekanism) the stone model disappears and the statue is replaced by a model consisting only of the troll's eyes and its weapon, still listed as an entity but no item drops and no way to damage/destroy it. For the sake of this given world, it's SP survival with no cheats, so simply removing the entity via command console isn't necessarily an option where it would be for MP servers or cheats enabled. Ive found one other instance of this (for lack of a better term) bug mentioned online, with no suggestions for a viable fix listed there, so I'm noting it here for reference and as a comment on the Ice and Fire page. Also note, if the map or the given chunks are reloaded, either by reloading the game or unloading and reloading the existing chunks, the troll reappears in statue form. If absolutely necessary a log small enough to comply with pastebin lite's kb limit may be created on request.

**Comment by Frikkle** [comment]
Thank you for reporting this. I'm curious as to whether this issue also occurs on servers. Additionally, could you provide a log to us indeed? GitHub's gists have a higher limit than pastebin.

**Comment by Mcgrolox** [comment]
[latest.log](https://github.com/NillerMedDild/Enigmatica2Expert/files/3478180/latest.log)

**Comment by Mcgrolox** [comment]
Unfortunately i have no way to test whether the issue occurs on servers, my sincerest apologies, but the other report of this issue that I mentioned in my original post was apparently on MP, whether on a server or LAN it didnt specify but I would assume the former.

**Comment by NillerMedDild** [comment]
I'm not seeing anything Ice & Fire related in there unfortunately. However you appear to be using outdated Java. This is often caused by Twitch defaulting to an older version than you have available. Follow these steps to update.

* Make sure you have the latest 64-bit Java installed
    https://www.java.com/en/download/manual.jsp Windows Offline (64-bit) is the one you need
* Go to the Twitch Minecraft settings
* Add `-version:1.8+` to the Additional Arguments

**Comment by Mcgrolox** [comment]
I actually re-updated java and reforced the twitch-minecraft launcher shortly after my reply this morning given that there was a pack update for Enigmatica 2, and have also updated to that version of the pack, since that will change which version of the pack this issue is technically posted to. Unfortunately that didnt change the issue, and more unfortunately is the log I sent you was from after I took all of the actions available to me on the troll statues themselves, so theoretically any block or entity updates that they are going through, if they are going through any, should have been posted there, but I admit I also noticed there wasnt any seemingly relevant information there when I glanced at the logs myself. It is possible that my method of overriding the java version that is being used isnt working for some reason, such as not using the correct setting menu (I have historically used the one inside the minecraft launcher, after clicking the actual button from the twitch launcher, and edited which java the individual pack should be using in there. I will try changing the default in the twitch setting since ive now found that, and see if that makes a difference and update respectively) It is also possible that I am getting the wrong log or getting the log at the wrong time, but given the other information I saw in there it synced up with everything else I was doing so I dont think that is the case.

 Ive also done some experimentation for short term workarounds, and after burying the entity in gravity blocks (gravel in this case, originally the thought was maybe suffocate the entity if possible) and reloading the chunk, it had changed from what I think is the forest troll model, maybe a default or something, to the ice troll appropriate the biome I'm in, and after trying to pick it up with the pickaxe that time it worked, but i have to figure out the exact order i did things in because ive only had it work once. I used a silk touch pickaxe and was interested to see if the statue maintained its proper functionality once placed down again, which it did not, which makes me think it may have something to do with how entities change from 'normal' form to statue form in ice and fire. In order to test that second theory i plan to go to a gorgon lair and see if those statues are also affected, if so i will post that information here since it may help narrowing down where the actual issue is occuring.

**Comment by Mcgrolox** [comment]
So I used the argument you listed, in addition to manually overriding the version of java from bundled to the up to date 64 bit version, with no changes to the issue, and went to the gorgon lair as formerly mentioned, the issue does in fact apply to all Ice and Fire stone statues, including those spawned in the gorgon structure at world gen, and any created afterwards by any means available in the mod. I didnt do much else so the client stream log was very short, and as before there is no mention of anything to do with the entities involved, so I dont know if I'll be able to get a useful log for this issue since it doesnt seem to be recording what's going wrong in the logs. I have yet to figure out what block or entity update caused the one statue to work properly, will continue testing as I can to try to figure that bit out.

**Comment by NillerMedDild** [comment]
I would appreciate the new log anyway, just to verify Java version. Thanks for your extensive testing!

**Comment by Mcgrolox** [comment]
[latest.log](https://github.com/NillerMedDild/Enigmatica2Expert/files/3488285/latest.log)

**Comment by NillerMedDild** [comment]
Yep you configured it correctly, thanks :)

**Comment by Lordroran** [comment]
May i ask why this Issue was closed? The problem persists in my server...

Still a big thank you for this awesome modpack!

**Comment by NillerMedDild** [comment]
It was closed because we can't fix it - We cannot update Ice & Fire without major changes, so even if it is fixed in an update of I&F we're kinda locked in :/

I should've said so when I closed it though, seems I was in a hurry to clean up issues :P

**Comment by Lordroran** [comment]
Thank you for the explanation. I managed to remove them using the kill command:
`/kill @e[type=iceandfire:if_troll]`

**Comment by SomeoneSneaky** [comment]
Apologies for reviving this, but wanted to make a note -- you _can_ destroy the statues manually with a pickaxe. Don't hold down the 'mine' button, but instead tap it repeatedly, like you're swinging a sword. Even though the entity turns invisible after the first hit, you can still see its name and health if you're using a WAILA-type mod. After ten hits, the entity will be destroyed, and drops a few blocks of cobble. It's always ten hits, regardless of original health -- I've tried it on all the statues in a gorgon's dungeon, from bats to trolls, and it all works the same.
