### ISSUE TITLE
mod request: worley's caves

### ISSUE THREAD

**Issue by lag42** [NillerMedDild/Enigmatica2Expert#1309]
[worley's caves](https://www.curseforge.com/minecraft/mc-mods/worleys-caves) generates huge branching caves across the world that are mostly all connected and go down from the surface to about y 11,

it would make searching for ores before you have a scanner much less annoying and it would overall improve the underground

**Comment by Frikkle** [comment]
Not sure about Worley's Caves myself; I've had this mod in the past and the generated caves are indeed nice; but the world gen (masked ores in other stone-types iirc) doesn't play nice with shaders (although that definitely isn't a reason for not wanting this).

Some reasons for thinking this might not be a good plan:
- World-gen would change overall causing issues for existing servers when upgrading (not sure if this can be adjusted/prevented).
- The pack is already really heavy on the world-gen.
- E2 is nearing end-of-life and adding such a "big" change would more likely destabilize the pack than not.

**Comment by NillerMedDild** [comment]
I think it would cause issues on existing worlds I'm afraid, and I'd rather not add more content to E2E. Thank you for the suggestions anyway.
