### ISSUE TITLE
Hwyla doesn't show Ingredients from TE Cache

### ISSUE THREAD

**Issue by BlueKingMuch** [NillerMedDild/Enigmatica2Expert#1310]
**Modpack version**
1.67

**Can the issue be reproduced?**
Yes - create a TE Cache, fill it with items, look at it

**Issue**
Normally, Hwyla shows the ingredients of TE Caches. In this Modpack, it doesn't do that.

I also tried manually temporarely to use The one Probe to find out if it's a Problem from Hwyla, but it has the same Issue.

In your changelog i found a "change in Behaviour for TE Caches for better Crossmod compatibility" --> maybe that's the issue?

![2019-08-10 15_09_14-Enigmatica 2_ Expert](https://user-images.githubusercontent.com/53972523/62822232-f27d0b80-bb80-11e9-96a3-330cda8542ff.png)

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.
