### ISSUE TITLE
EnderIO Conduit Filter Crash

### ISSUE THREAD

**Issue by Sikona** [NillerMedDild/Enigmatica2Expert#1311]
**Modpack version**
Version 1.67
**Can the issue be reproduced?**
Yes

**Logs**
https://pastebin.com/TUukHTri

**Issue**
I have an item conduit and redstone conduit connecting to a chest. When I tried putting a basic item filter into it in any way, the game crashes.

![tim](https://user-images.githubusercontent.com/53983011/62827572-734b0000-bb9f-11e9-84f0-a56b5f3dbeb4.png)
![tim2](https://user-images.githubusercontent.com/53983011/62827573-780fb400-bb9f-11e9-9e8a-f6d8bf388eda.png)
![tim3](https://user-images.githubusercontent.com/53983011/62827574-7a720e00-bb9f-11e9-802e-b7d4ecb1752f.png)

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by Frikkle** [comment]
@Sikona thank you for the report and the provided screenshots; they will assist in debugging. Additionally, it seems that your crash report is incomplete? I am missing some information about the environment, java version, JVM arguments, etc. etc. Could you submit the full report while I'm trying to reproduce this on my end?

**Comment by Frikkle** [comment]
I managed to reproduce the issue _somewhat_..

Here's my [log](https://paste.dimdev.org/uyujefiseg.mccrash). I my case I tried to mouse-scroll the filter in, causing my MouseTweaks to be the "cause" of the crash. I'll do some additional testing.

**Comment by Frikkle** [comment]
Additionally, it also happened when using a Big Item Filter. So it's not just the basic one that causes this.

I'll try and reproduce this on a local setup with just EnderIO.

**Comment by Frikkle** [comment]
Just reproduced this with a minimal setup:
- Forge `14.23.5.2838`
- EnderCore `1.12.2-0.5.65`
- EnderIO `5.0.46`

Here are my [logs](https://paste.dimdev.org/yetiwomilo.mccrash)

**Comment by NillerMedDild** [comment]
Absolutely, great work, I'll relay this evening.

**Comment by NillerMedDild** [comment]
It was already reported it seems, https://github.com/SleepyTrousers/EnderIO/issues/5202

**Comment by MaxNeedsSnacks** [comment]
I'm guessing the mod update is gonna be in the next pack ver. then? :P

**Comment by NillerMedDild** [comment]
Yes :P

**Comment by BMK2** [comment]
This crash is happening again (in nearly the same setup as OP's). Did something change in recent patches?
