### ISSUE TITLE
gemObsidian OreDict woes

### ISSUE THREAD

**Issue by MaxNeedsSnacks** [NillerMedDild/Enigmatica2Expert#1312]
**Modpack version**
1.67

**Can the issue be reproduced?**
Yes

**Logs**
N/A

**Issue**
Every machine except for the IC2 compressor uses the Cyclic "Crystallized Obsidian" to make obsidian plates (which are needed for ID stuff, turbine housing and reinforcement modifiers) since it is oredicted as "gemObsidian". I'm pretty sure this isn't intentional since the IC2 compressor has the standard dust->plate recipe and all the other recipes are needlessly unbalanced and expensive as a consequence of this.

**Comment by NillerMedDild** [comment]
That doesn't sound intentional, I don't even know what Crystallized Obsidian is ^^'

**Comment by MaxNeedsSnacks** [comment]
it's an item from cyclic that's used for like the lategame / op swords and items in cyclic but apparently it's oredicted as a gem for obsidian

**Comment by MaxNeedsSnacks** [comment]
hm, we COULD try just removing "gemObsidian" and then seeing whether *that* changes anything about it, but i sorta fear that Thermal registers its recipes before crafttweaker can remove the oredict

**Comment by NillerMedDild** [comment]
Worth a shot!

**Comment by NillerMedDild** [comment]
Didn't work :(

**Comment by NillerMedDild** [comment]
I think this issue is a bit too inconsequential to spend a lot of time on, given development is mostly on 1.14 now.

**Comment by MaxNeedsSnacks** [comment]
Oh well, yeah it really isn't all that important 😅
