### ISSUE TITLE
[DraconicEvolution] Information Tablet can't download manifest

### ISSUE THREAD

**Issue by EscolarProgramming** [NillerMedDild/Enigmatica2Expert#1314]
**Modpack version**
1.67

**Can the issue be reproduced?**
Yes - Tested with 3 persons from different computers and networks

**Logs**
`[19:39:13] [PI-Update-Manager/ERROR]: [Pi Reported Error]: Failed to download the PI mod manifest from https://pi.brandon3055.com/manifest.json
[19:39:13] [Client thread/ERROR]: [Pi Reported Error]: No documentation pages were found! This most likely means the documentation failed to download for some reason.
[19:39:51] [Client thread/ERROR]: [Pi Reported Error]: Attempted to open documentation for mod Draconic Evolution But there is no documentation avalible for this mod.`

**Issue**
The Information Tablet of Draconic Evolution can't download the manifest. 
![grafik](https://user-images.githubusercontent.com/6965961/62885984-73333780-bd3a-11e9-8a44-b328fdc7ae97.png)

If I open the URL in my browser all works fine but the Tablet won't display it.

**Comment by NillerMedDild** [comment]
Thanks for the report.

We're a few versions behind on Project Intelligence, I have a feeling updating will fix this issue.

**Comment by EscolarProgramming** [comment]
Thanks for your answer. 
I've updated to latest Project Intelligence (1.0.7.24) and latest Brandons Core (2.4.17.208) but there's the same error.

**Comment by NillerMedDild** [comment]
Cool, I hope they get it fixed.

**Comment by Dark-Matter-001** [comment]
Try the adding the vanilla fix mod from this report: https://github.com/brandon3055/Draconic-Evolution/issues/1253

Worked for me.

**Comment by NillerMedDild** [comment]
I highly recommend that you don't add VanillaFix.

**Comment by Frikkle** [comment]
I used to run the pack with VanillaFix but that did not resolve this issue for me.

**Comment by NillerMedDild** [comment]
Hopefully resolved in version 1.68 :)

**Comment by HorribleNerd** [comment]
Still/again happening in version 1.76a, same error

**Comment by Shirkit** [comment]
Yep, I have the same error as well, I guess some config updated and broke it @NillerMedDild ?

**Comment by NillerMedDild** [comment]
I didn't update any configs, I'll let the mod author know it's broken again :)

**Comment by NillerMedDild** [comment]
I do not believe I can fix this, and the majority of modders no longer support 1.12, so I'll close this issue.

Nethertheless, thank you for reporting :)
