### ISSUE TITLE
QOL CT Feature Request: Coke dust to be able to be SAG Mill'd

### ISSUE THREAD

**Issue by jaxx050** [NillerMedDild/Enigmatica2Expert#1315]
Basically, the Immersive Engineering Coke Dust is used for a variety of recipes, mostly for EnderIO capacitors, but you can't put Coal Coke into a SAG Mill to make it unlike a lot of the other "crushing" type machines. So, add that as a crafttweaker recipe. :P

**Comment by NillerMedDild** [comment]
It can only be crushed by an IE multiblock atm, right?

**Comment by jaxx050** [comment]
Negative, it is currently processable by the Extra Utilities Crusher, Actually Additions Crusher, Mekanism Crusher, IE Crusher, TE Pulverizer, and IC2 Macerator. Hence, adding it to the SAG Mill for convenience.

**Comment by NillerMedDild** [comment]
Ah alright, then sure :)
