### ISSUE TITLE
Crash w/ EU2 Ineffable Glass when entering compact machine

### ISSUE THREAD

**Issue by kingatdoc** [NillerMedDild/Enigmatica2Expert#1316]
**Modpack version**
E2E 1.66c

**Can the issue be reproduced?**
Unknown

**Logs**
https://pastebin.com/PwSuGSB0

**Issue**
game crash on entering compact machine dimension

**Comment by NillerMedDild** [comment]
You appear to be using outdated Java. This is often caused by Twitch defaulting to an older version than you have available. Follow these steps to update.

* Make sure you have the latest 64-bit Java installed
    https://www.java.com/en/download/manual.jsp Windows Offline (64-bit) is the one you need
* Go to the Twitch Minecraft settings
* Add `-version:1.8+` to the Additional Arguments

**Comment by kingatdoc** [comment]
Awesome! thanks for the reply :)

--
Patrick Dougherty
(484) 678-1658
