### ISSUE TITLE
[Mod Request] Apotheosis & TorchMaster

### ISSUE THREAD

**Issue by ben-mkiv** [NillerMedDild/Enigmatica2Expert#1317]
Hi,

would be neat to see those two Mods in the pack

Torchmaster to pretend Hostile/Animal spawns
https://www.curseforge.com/minecraft/mc-mods/torchmaster

Aptheosis for fun, specially for Endgame and High Tier Enchants (as it removes the enchant Level limit)
https://www.curseforge.com/minecraft/mc-mods/apotheosis

**Comment by NillerMedDild** [comment]
I will not be adding more mods I'm afraid, but thanks for the suggestion.
