### ISSUE TITLE
E2E Crash on startup - foamfix deduplication error and possible solution

### ISSUE THREAD

**Issue by cmndrOri** [NillerMedDild/Enigmatica2Expert#1318]
**Modpack version**
1.67

**Can the issue be reproduced?**
Yes - consistent crash without fix applied

**Logs**
[Crash log - foamfix deduplication.txt](https://github.com/NillerMedDild/Enigmatica2Expert/files/3512644/Crash.log.-.foamfix.deduplication.txt)

**Issue**
Launched through twitch, fresh install with no backups, added mods, or other changes to modpack. Game reaches stage 3 loading model manager, and when it attempts to run deduplication the game crashes to minecraft launcher and displays the crash screen. I tested it twice, both times crashed at exactly the same point in the loading process.  After a bit of digging around i found that deduplication is from foamfix, and changed one of the config options (see below) to see if it would help. The game launched correctly twice in a row afterwards. I don't know why this is an issue, but if you need a different log/report/what ever to figure it out i can unfix it easily.

I'm running it on a modern gaming computer with 8 gig allocated, so it shouldn't be a hardware/memory issue. 

    # Clears the baked models generated in the first pass *before* entering the second pass, instead of *after*. While this doesn't reduce memory usage in-game, it does reduce it noticeably during loading. [default: true]
    B:clearDuplicateModelRegistry=false
This was changed from true to false /\

Edit - mod file is foamfix-0.10.5-1.12.2 if relevant.

**Comment by NillerMedDild** [comment]
Could you please re-install the modpack and try again, without the fix applied? I've seen this issue before, but it usually stems from adding LagGoggles to the pack.

**Comment by cmndrOri** [comment]
That was the reinstall, but for science I removed it and all of the backups again. Redownloaded, started the game up, crash to launcher at deduplication twice in a row. Apply the config tweak, loaded straight to the main menu, no problems.

As I said, this was (and is) a totally fresh install via twitch with nothing added, removed, changed in the config, etc. except for the tweak to foamfix.

**Comment by NillerMedDild** [comment]
I see, thanks for trying anyway. Could you please provide the crash report? It seems to have been the latest.log you supplied.

**Comment by cmndrOri** [comment]
Lets see.... i think this should be the crashlog?

[hs_err_pid10092.log](https://github.com/NillerMedDild/Enigmatica2Expert/files/3513584/hs_err_pid10092.log)

**Comment by Discomanco** [comment]
`(build 1.8.0_51-b16)` Outdated java is being used.

From our Discord pins:  
You appear to be using outdated Java. This is often caused by Twitch defaulting to an older version than you have available. Follow these steps to update.

* Make sure you have the latest 64-bit Java installed
    https://www.java.com/en/download/manual.jsp Windows Offline (64-bit) is the one you need
* Go to the Twitch Minecraft settings
* Add -version:1.8+ to the Additional Arguments

**Comment by cmndrOri** [comment]
Ah. Updating java was the first thing I tried, didn't occur to me that twitch would be too daft to use the most up to date version. Added that arg and it loaded (with the newer java) just fine, thanks. :)
