### ISSUE TITLE
Game crashed while tesselating block

### ISSUE THREAD

**Issue by OpusTheMoose** [NillerMedDild/Enigmatica2Expert#132]
When trying to enter a server I play on, the game has crashed 5 times, every single time i've entered. The world will start to load before it crashes, and I get a "Game crashed while tessleating block" error message. I've tried updating to Java version 1.8.0 171

The modpack version is version 1.29. As I understand, this isn't the latest version (1.3), but the server hasn't updated yet. 

---- Minecraft Crash Report ----

WARNING: coremods are present:
  LoadingPlugin (Quark-r1.4-124.jar)
  AppleCore (AppleCore-mc1.12.2-3.1.3.jar)
  BedPatch (bedpatch-2.2-1.12.2.jar)
  EnderCorePlugin (EnderCore-1.12.2-0.5.31.jar)
  RandomPatches (randompatches-1.12.2-1.2.0.0.jar)
  CTMCorePlugin (CTM-MC1.12-0.3.0.15.jar)
  LoadingPlugin (RandomThings-MC1.12.2-4.1.7.jar)
  ColytraLoadingPlugin (colytra-1.12.2-1.0.4.3.jar)
  ForgelinPlugin (Forgelin-1.7.2.jar)
  OpenModsCorePlugin (OpenModsLib-1.12.2-0.11.5.jar)
  SHLoadingPlugin (ScalingHealth-1.12-1.3.17-100.jar)
  Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.9.9.1-1.12.2-anarchy.jar)
  Plugin (NotEnoughIDs-1.5.4.2.jar)
  FMLPlugin (elulib-0.1.12.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.64-dev.jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-82.jar)
  LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
  llibrary (llibrary-core-1.0.6-1.12.2.jar)
  TransformerLoader (OpenComputers-MC1.12.2-1.7.2.67.jar)
  IvToolkit (IvToolkit-1.3.3-1.12.jar)
  AstralCore (astralsorcery-1.12.2-1.9.1.jar)
Contact their authors BEFORE contacting forge

// Don't be sad, have a hug! <3

Time: 6/26/18 9:37 AM
Description: Tesselating block model

java.lang.IllegalStateException: vanilla model 'net.minecraft.client.renderer.block.model.ModelBlock@3a6f8a64' can't have non-vanilla parent
	at net.minecraftforge.client.model.ModelLoader$VanillaModelWrapper.getTextures(ModelLoader.java:402)
	at net.minecraftforge.client.model.ModelLoader$WeightedRandomModel.retexture(ModelLoader.java:759)
	at net.minecraftforge.client.model.ModelLoader$WeightedRandomModel.retexture(ModelLoader.java:635)
	at slimeknights.tconstruct.shared.client.BakedTableModel.getActualModel(BakedTableModel.java:101)
	at slimeknights.tconstruct.shared.client.BakedTableModel.func_188616_a(BakedTableModel.java:193)
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.render(ForgeBlockModelRenderer.java:99)
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.func_187498_b(ForgeBlockModelRenderer.java:85)
	at net.minecraft.client.renderer.BlockModelRenderer.func_187493_a(BlockModelRenderer.java:47)
	at net.minecraft.client.renderer.BlockModelRenderer.func_178267_a(BlockModelRenderer.java:38)
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:80)
	at codechicken.lib.render.block.CCBlockRendererDispatcher.func_175018_a(CCBlockRendererDispatcher.java:69)
	at com.elytradev.architecture.client.render.CustomBlockDispatcher.func_175018_a(CustomBlockDispatcher.java:98)
	at net.minecraft.client.renderer.chunk.RenderChunk.func_178581_b(RenderChunk.java:200)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(SourceFile:100)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(SourceFile:43)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraftforge.client.model.ModelLoader$VanillaModelWrapper.getTextures(ModelLoader.java:402)
	at net.minecraftforge.client.model.ModelLoader$WeightedRandomModel.retexture(ModelLoader.java:759)
	at net.minecraftforge.client.model.ModelLoader$WeightedRandomModel.retexture(ModelLoader.java:635)
	at slimeknights.tconstruct.shared.client.BakedTableModel.getActualModel(BakedTableModel.java:101)
	at slimeknights.tconstruct.shared.client.BakedTableModel.func_188616_a(BakedTableModel.java:193)
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.render(ForgeBlockModelRenderer.java:99)
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.func_187498_b(ForgeBlockModelRenderer.java:85)

-- Block model being tesselated --
Details:
	Block: tconstruct:tooltables[type=partbuilder]
	Block location: World: (-52,48,-567), Chunk: (at 12,3,9 in -4,-36; contains blocks -64,0,-576 to -49,255,-561), Region: (-1,-2; contains chunks -32,-64 to -1,-33, blocks -512,0,-1024 to -1,255,-513)
	Using AO: true
Stacktrace:
	at net.minecraft.client.renderer.BlockModelRenderer.func_187493_a(BlockModelRenderer.java:47)
	at net.minecraft.client.renderer.BlockModelRenderer.func_178267_a(BlockModelRenderer.java:38)

-- Block being tesselated --
Details:
	Block type: ID #2750 (tile.tconstruct.tooltables // slimeknights.tconstruct.tools.common.block.BlockToolTable)
	Block data value: 2 / 0x2 / 0b0010
	Block location: World: (-52,48,-567), Chunk: (at 12,3,9 in -4,-36; contains blocks -64,0,-576 to -49,255,-561), Region: (-1,-2; contains chunks -32,-64 to -1,-33, blocks -512,0,-1024 to -1,255,-513)
Stacktrace:
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:80)
	at codechicken.lib.render.block.CCBlockRendererDispatcher.func_175018_a(CCBlockRendererDispatcher.java:69)
	at com.elytradev.architecture.client.render.CustomBlockDispatcher.func_175018_a(CustomBlockDispatcher.java:98)

-- Affected level --
Details:
	Level name: MpServer
	All players: 2 total; [EntityPlayerSP['_Hat_Kid_'/2117187, l='MpServer', x=-47.27, y=49.00, z=-565.99], EntityOtherPlayerMP['themadminer123'/1722131, l='MpServer', x=-74.15, y=67.00, z=-567.79]]
	Chunk stats: MultiplayerChunkCache: 441, 441
	Level seed: 0
	Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-137,64,336), Chunk: (at 7,4,0 in -9,21; contains blocks -144,0,336 to -129,255,351), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 23431046 game time, 21592762 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 71 total; [EntitySkeleton['Skeleton'/2118048, l='MpServer', x=-115.50, y=12.00, z=-548.50], EntityOcelot['Cat'/1, l='MpServer', x=-60.81, y=49.00, z=-565.70], EntityOtherPlayerMP['themadminer123'/1722131, l='MpServer', x=-74.15, y=67.00, z=-567.79], EntityZombie['Zombie'/2106790, l='MpServer', x=-69.74, y=40.00, z=-555.52], EntityZombie['Zombie'/2106791, l='MpServer', x=-68.52, y=40.00, z=-552.75], EntityOtherPlayerMP['themadminer123'/1722131, l='MpServer', x=-74.15, y=67.00, z=-567.79], EntityEnderman['Enderman'/2119342, l='MpServer', x=-77.50, y=68.00, z=-575.50], EntityItem['item.item.carrots'/1981838, l='MpServer', x=-44.31, y=48.94, z=-608.47], EntityBat['Bat'/2117042, l='MpServer', x=15.83, y=14.10, z=-588.25], EntityZombie['Zombie'/1886991, l='MpServer', x=-74.50, y=19.00, z=-643.21], EntityBlightFire['entity.BlightFire.name'/2119348, l='MpServer', x=-77.50, y=70.18, z=-575.50], EntitySkeleton['Skeleton'/2112438, l='MpServer', x=-115.50, y=24.00, z=-588.50], EntityBlightFire['entity.BlightFire.name'/2118071, l='MpServer', x=16.50, y=62.73, z=-580.50], EntityCreeper['Creeper'/2118969, l='MpServer', x=-95.50, y=69.00, z=-589.50], EntityZombie['Zombie'/1886977, l='MpServer', x=-66.19, y=53.00, z=-625.47], EntityCreeper['Creeper'/2118974, l='MpServer', x=-95.50, y=69.00, z=-590.50], EntityCockatrice['Cockatrice'/159, l='MpServer', x=-66.39, y=68.00, z=-579.30], EntityCreeper['Creeper'/2118975, l='MpServer', x=-108.65, y=24.00, z=-592.50], EntitySkeleton['Skeleton'/2113284, l='MpServer', x=-86.50, y=64.00, z=-628.50], EntitySkeleton['Skeleton'/2115590, l='MpServer', x=-62.50, y=67.00, z=-488.50], EntityBlightFire['entity.BlightFire.name'/2117255, l='MpServer', x=-8.50, y=26.28, z=-622.50], EntityCreeper['Creeper'/2099208, l='MpServer', x=-74.33, y=59.00, z=-578.40], EntityCreeper['Creeper'/2117000, l='MpServer', x=10.50, y=66.00, z=-577.50], EntityBlightFire['entity.BlightFire.name'/2117007, l='MpServer', x=10.50, y=67.28, z=-577.50], EntityBat['Bat'/2118033, l='MpServer', x=-25.49, y=33.40, z=-637.61], EntityBat['Bat'/2117019, l='MpServer', x=-69.73, y=24.10, z=-590.70], EntityBat['Bat'/2117021, l='MpServer', x=-80.72, y=21.26, z=-635.13], EntityBlightFire['entity.BlightFire.name'/2099229, l='MpServer', x=-74.33, y=60.28, z=-578.40], EntityBlightFire['entity.BlightFire.name'/2113311, l='MpServer', x=-86.50, y=65.49, z=-628.50], EntityItem['item.item.carrots'/2111647, l='MpServer', x=-44.55, y=48.94, z=-609.51], EntitySpider['Spider'/2116322, l='MpServer', x=14.50, y=69.00, z=-617.50], EntityBlightFire['entity.BlightFire.name'/2119267, l='MpServer', x=-74.18, y=71.11, z=-576.45], EntitySkeleton['Skeleton'/2113895, l='MpServer', x=-2.50, y=59.00, z=-597.50], EntityZombie['Zombie'/2118121, l='MpServer', x=-97.50, y=69.00, z=-623.50], EntityItem['item.item.carrots'/1925079, l='MpServer', x=-44.23, y=48.94, z=-606.98], EntityBlightFire['entity.BlightFire.name'/2092756, l='MpServer', x=-55.52, y=21.28, z=-574.49], EntitySpider['Spider'/2117228, l='MpServer', x=-39.50, y=69.00, z=-626.50], EntitySpider['Spider'/2118508, l='MpServer', x=-84.50, y=68.00, z=-601.50], EntitySkeleton['Skeleton'/2117229, l='MpServer', x=-39.50, y=69.00, z=-619.50], EntityPlayerSP['_Hat_Kid_'/2117187, l='MpServer', x=-47.27, y=49.00, z=-565.99], EntityCreeper['Creeper'/2092751, l='MpServer', x=-55.52, y=20.00, z=-574.49], EntityItem['item.item.carrots'/2101232, l='MpServer', x=-45.57, y=48.94, z=-609.07], EntityZombie['Zombie'/2116336, l='MpServer', x=-43.50, y=26.00, z=-601.50], EntityRamFriesian['Friesian Ram'/1887048, l='MpServer', x=-18.00, y=69.60, z=-618.83], EntitySpider['Spider'/2118132, l='MpServer', x=27.15, y=21.10, z=-524.30], EntityRamMerino['Merino Ram'/1887049, l='MpServer', x=-23.40, y=69.60, z=-620.00], EntitySpider['Spider'/2118517, l='MpServer', x=14.83, y=47.00, z=-594.83], EntityRamMerino['Merino Ram'/1887050, l='MpServer', x=-16.00, y=69.60, z=-616.84], EntityItem['item.item.carrots'/1954506, l='MpServer', x=-43.13, y=48.94, z=-608.29], EntityZombie['Zombie'/2118007, l='MpServer', x=16.50, y=62.00, z=-580.50], EntitySkeleton['Skeleton'/2035527, l='MpServer', x=-39.60, y=45.00, z=-599.20], EntityItem['item.item.carrots'/2100089, l='MpServer', x=-43.19, y=48.75, z=-606.34], EntityBlightFire['entity.BlightFire.name'/2116346, l='MpServer', x=-43.50, y=27.46, z=-601.50], EntityZombieVillager['Zombie Villager'/2117242, l='MpServer', x=15.27, y=70.00, z=-627.70], EntityBlightFire['entity.BlightFire.name'/2118523, l='MpServer', x=14.83, y=47.45, z=-594.83], EntityCreeper['Creeper'/2117247, l='MpServer', x=-8.50, y=25.00, z=-622.50], EntitySpider['Spider'/2118015, l='MpServer', x=-51.50, y=67.00, z=-618.50], EntityEnderman['Enderman'/2119295, l='MpServer', x=-74.11, y=68.86, z=-575.40], EntityCreeper['Creeper'/2118976, l='MpServer', x=-113.50, y=25.00, z=-593.50], EntitySpider['Spider'/2115270, l='MpServer', x=-123.00, y=68.00, z=-487.00], EntityBlightFire['entity.BlightFire.name'/2118984, l='MpServer', x=-95.50, y=70.28, z=-589.50], EntityZombie['Zombie'/1887090, l='MpServer', x=10.41, y=26.00, z=-499.47], EntityBrainyZombie['Angry Zombie'/111, l='MpServer', x=-88.76, y=18.00, z=-566.52], EntityItem['item.item.carrots'/2096624, l='MpServer', x=-42.88, y=50.00, z=-608.19], EntityZombieVillager['Zombie Villager'/2118095, l='MpServer', x=32.50, y=63.00, z=-511.50], EntityItem['item.item.carrots'/1749866, l='MpServer', x=-43.13, y=48.94, z=-607.39], EntityZombie['Zombie'/2104283, l='MpServer', x=-81.69, y=62.00, z=-577.54], EntityEnderman['Enderman'/2119260, l='MpServer', x=-74.18, y=68.94, z=-576.45], EntitySkeleton['Skeleton'/2116317, l='MpServer', x=21.50, y=69.00, z=-613.50], EntityEnderman['Enderman'/2119261, l='MpServer', x=-72.08, y=68.94, z=-579.40], EntitySpider['Spider'/2117982, l='MpServer', x=-92.50, y=69.00, z=-613.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2738)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(

**Comment by NillerMedDild** [comment]
"Fixed" via Discord
