### ISSUE TITLE
Server automatically restarting when "stopping"

### ISSUE THREAD

**Issue by scottmmuc** [NillerMedDild/Enigmatica2Expert#1321]
I'm on 1.66c so I'm not sure if this has been patched out or not yet, but I run the server on my main PC so I shut it down when I shut my PC down, and when I go to stop it it just automatically restarts itself. It used to give me the option to either restart or shut down completely by typing "y/n" to restart or not, but that option only came up a couple times and recently it hasn't been giving me that option at all. I've just been having to close the terminal window manually which I'd rather not do, I'd like to be able to just stop it and it shuts down entirely. Is there an option or setting for this somewhere that I'm just missing?

**Comment by NillerMedDild** [comment]
There's no option for that, either edit the script or make your own :)

**Comment by scottmmuc** [comment]
Ahh yeah you're right, I wasn't sure if I could do that or not. I just found the bit in the .bat file that had the restart code, just took it out and it seems to be working for me just fine. Cheers!
