### ISSUE TITLE
E2E: Screen flickering in the Nether

### ISSUE THREAD

**Issue by SeseMueller** [NillerMedDild/Enigmatica2Expert#1322]
[Enigmatica2Expert 22.08.2019 13_50_49.zip](https://github.com/NillerMedDild/Enigmatica2Expert/files/3530181/Enigmatica2Expert.22.08.2019.13_50_49.zip)

**Modpack version**
Newest via Twitch launcher.

**Can the issue be reproduced?**
Unknown, as I don't have access to another PC running E2E.

**Issue**
While in the nether, sometimes, the screen flickers multiple times per second randomly. This is normal E2E minus BetterFPS plus Optifine, though I remember this glitch happening prior to me replacing BetterFps with Optifine. Notice the white Blocks during the black screen in the Zip file.

**Comment by NillerMedDild** [comment]
I'm sorry but I will not open zip files from people I do not know. Can you reproduce this issue on default E2E, without Optifine?

**Comment by SeseMueller** [comment]
Edit: I am sorry to have bothered you. I have finally concluded to test it out without Optifine, and it works. Apparently, Optifine doesn't like Ice and Fire very much. (Source: Vanillafix spammed me, because the rendering engine threw errors left and right.)
