### ISSUE TITLE
Advanced Inscribers/Crystal Growth Chambers(AE2 Stuff) generates Huge lag when There are more than 2 active oxygen vents(Advanced Rocketry) nearby

### ISSUE THREAD

**Issue by PizzaAddict** [NillerMedDild/Enigmatica2Expert#1323]
**Modpack version**
1.66c

**Can the issue be reproduced?**
Yes

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Issue**
I think A screenshot will explain this issue better.
https://imgur.com/sJ3OcFE

The bug occurs in space. didn't test if other dimensions produce this bug also

If this is a feature request, feel free to delete the template.

**Comment by NillerMedDild** [comment]
Thank you for the report. Could you try removing the Item Conduits and check if it's still laggy?

**Comment by PizzaAddict** [comment]
https://imgur.com/KKTktGh
yeah. it bugged by it's own

**Comment by NillerMedDild** [comment]
And this doesn't happen if there are no Oxygen Vents nearby?

**Comment by PizzaAddict** [comment]
Yes. 2->fine 3->lag.

**Comment by NillerMedDild** [comment]
It doesn't look like the mod is maintained atm.
