### ISSUE TITLE
Storing encoded patterns Into ME networks makes bugged cells

### ISSUE THREAD

**Issue by PizzaAddict** [NillerMedDild/Enigmatica2Expert#1324]
**Modpack version**
1.66c

**Can the issue be reproduced?**
Yes

how to reproduce:
make multiple any encoded patterns->store in ME network(not in Interface)->search "pattern" in ME terminal
 
issue:
1: patterns keep appearing-disappearing. ME terminal displays different encoded patterns every time I open the terminal
2: Icon of some patterns remains in ME terminal after extracted.
3: some patterns are unextractable
4: when I have this issue, if I empty every cells In my network using cell I/o port, there are bugged cells.
bugged cells display more than 0 Item types used, but the cell is empty(noting shows up when inserted in ME drive)

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
Closing because the possibility of getting a fix is very low, as I understand it.
