### ISSUE TITLE
Crashed upon server start

### ISSUE THREAD

**Issue by xuyz1999** [NillerMedDild/Enigmatica2Expert#1326]
**Modpack version**
1.67

**Can the issue be reproduced?**
Yes

**Logs**
https://pastebin.com/8VV1V4iM

**Issue**
It seems that none of the blocks (mob slaughter factory or some twilight forest items) exists in the map but it still causes the server to crash randomly.

**Comment by NillerMedDild** [comment]
Reproduce this without your added mods please.

**Comment by xuyz1999** [comment]
It's just the original 1.67 version of E2E pack. The same problem also happens in other packs which have mods mentioned in the crash report.

**Comment by xuyz1999** [comment]
I'm sorry but I have read another crash report :( the actually cause is out of memory.
Anyway thanks a lot for the help !
