### ISSUE TITLE
cannot Autocraft Item: 3 kinds

### ISSUE THREAD

**Issue by PizzaAddict** [NillerMedDild/Enigmatica2Expert#1327]
**Modpack version**
1.66c

**Can the issue be reproduced?**
Yes

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Issue**
item 1: Flux core from "flux networks"
the recipe which uses itself to be crafted
 the crafting plan GUI's start button is dimmed even if I have enough resources and CPU

item 2: IC2 generator
autocrafting succeeds to Its components(RE battery, Basic Machine casing, and furnace),  but combining these components is the problem. the crafting monitor shows generator as 'scheduled'
Workaround: making two patterns of the generator, and then insert processing pattern to an interface, crafting pattern to adjacent assembler solves this problem

item 3: Backpack from "Backpack"
same is IC2 generator. didn't test if this one has the same workaround

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by Frikkle** [comment]
Again, the woods issue here so I can't check this, but if I recall correctly the IC2 thing might have to do with metadata on (some of) the crafting components.

I always test each crafting pattern to see if it's working. If not I craft all it's components and check if any of them has NBT tags and then substitute those parts in the recipe by the previously auto-crafted components with the right tags.

That solves my auto-crafting issues 9 out of 10 times.

Leaving this open for others check as I can't right now :)

**Comment by NillerMedDild** [comment]
Closing because the possibility of getting a fix is very low, as I understand it.
