### ISSUE TITLE
Fluid Duplication Glitch

### ISSUE THREAD

**Issue by amylizzle** [NillerMedDild/Enigmatica2Expert#1328]
**Modpack version**
1.67

**Can the issue be reproduced?**
Yes

**Logs**
N/A

**Issue**
The follow set up allows for the duplication of fluids:

1. Set up a basic Tinker's smelter. 
2. Attach an AE2 ME Fluid Storage Bus to the Smeltery Drain set to extract only.
3. Melt the desired fluid in the smelter (at least 1 bucket worth) [Update: Fluids can be placed directly into the smeltery in the normal manner, this also works]
4. Attach an AE2 ME Fluid Export Bus to a Mekanism Ingot Former (may work for other blocks, haven't tested.) [Update: Works for anything as far as I can tell]
5. Use the Extra Cells Fluid Auto Filler to craft a bucket of the desired fluid, apply the bucket to the fluid export bus.
6. Enjoy your infinite fluid as the export bus continues to dump it out even though the smeltery is empty. Acceleration cards in the export bus can increase the fluid rate.

This is confirmed with Alumite and Draconium. I can post my save if necessary.

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
I don't have time to fix this issue I'm afraid, if someone goes through the trouble of all those exact steps, they almost deserve it :P
