### ISSUE TITLE
[Mod Suggestion] Fossils and Archaeology 

### ISSUE THREAD

**Issue by yikies** [NillerMedDild/Enigmatica2Expert#1329]
I know this is a long shot, but the mod is pretty stable on 1.12.2 now and it's a lot of fun especially alongside mods like Ice and Fire. Would love to see it integrated into a pack as good as this one!

**Comment by Frikkle** [comment]
I assume this mod includes world gen? If so it would be incompatible with pre-existing servers, which would be an issue. In addition the pack is already quite heavy on the world gen, so I think Niller wouldn't be too inclined on adding more mods that add to it.

I think this mod could be cool, especially when Integrated and intertwined with other mods making it part of the whole experience.

**Comment by NillerMedDild** [comment]
Agreed, Possibly for E4, but no for E2E :)
