### ISSUE TITLE
quests randomly complete themselves and reset when logging back into world

### ISSUE THREAD

**Issue by DragonmasterDJ** [NillerMedDild/Enigmatica2Expert#133]
#### Issue Description
When I go to sleep. I log out of the game, and then put the computer to sleep. though on waking up, waking up the computer, and then starting my world. the game chooses a random quest to complete, then reset completely. like if you just added a new quest and didn't edit it at all! this is a problem though, since it gets rid of its possible rewards and descriptions.

#### Modpack version (Do not use "latest")
1.30

#### Crash Report
none

####Images
![capppture](https://user-images.githubusercontent.com/29170640/42003520-3989716c-7aaf-11e8-8286-94a1a3c0d63a.PNG)

![captture](https://user-images.githubusercontent.com/29170640/42003528-3f493290-7aaf-11e8-9e9d-4f67811c3f14.PNG)

**Comment by NillerMedDild** [comment]
It can occasionally be fixed by using `/bq_admin default load`
I'm aware of the issue, and have reported it to the Better Questing dev.
Thank you for the report.

**Comment by NillerMedDild** [comment]
Yeah it's kinda hit and miss. I'm afraid I can't help you.
