### ISSUE TITLE
Gauge dropper doesn't empty the gas tanks

### ISSUE THREAD

**Issue by meromorf** [NillerMedDild/Enigmatica2Expert#1330]
**Modpack version**
1.67

**Can the issue be reproduced?**
Yes

**Logs**
not applicable

**Issue**
Input short description of the issue here

As gauge dropper doesn't empty the gas tanks, the infinite version of these tanks can't  be reused (I get no issue with infinite liquid tanks).

If this is a feature request, feel free to delete the template.

**Comment by NillerMedDild** [comment]
Change the gas with a gauge dropper filled with the gas you want.
