### ISSUE TITLE
Magma crucible not working

### ISSUE THREAD

**Issue by Smite420** [NillerMedDild/Enigmatica2Expert#1331]
**Modpack version**
Light

**description**
The magma crucible was working, it was how I got lava into my tinkers furnace, but now it’s not using any power. It has cobblestone, hardened fluid ducts with properly programmed servos and plenty of power.
![image](https://user-images.githubusercontent.com/54250325/63667836-37b95400-c7a3-11e9-8787-1508a834ed5e.jpg)

**Comment by NillerMedDild** [comment]
Have you tried breaking and replacing it?

**Comment by Smite420** [comment]
I did yeah. I even saved and quit everything

**Comment by NillerMedDild** [comment]
Did you give it a redstone signal? That can turn it off, depending on it's mode.

**Comment by Smite420** [comment]
Bruh. Damn idk why it changed, I always had it on ignored before I broke it. Lmao sorry bro thanks

**Comment by NillerMedDild** [comment]
No worries :)
