### ISSUE TITLE
Some Items Are Not visible in ME network, even their patterns.

### ISSUE THREAD

**Issue by PizzaAddict** [NillerMedDild/Enigmatica2Expert#1333]
**Modpack version**
1.66c
**Can the issue be reproduced?**
Yes

**Issue**
Some Items Are not visible in ME network.
Here's a detailed example.

![2019-08-28_06 24 25](https://user-images.githubusercontent.com/34593536/63809548-8f9bba80-c95d-11e9-92ec-fd1e9f3f7254.png)

I made 32 basic fluid tank(from mekanism)

![2019-08-28_06 25 00](https://user-images.githubusercontent.com/34593536/63809549-90345100-c95d-11e9-8174-e096de5b154e.png)

as soon as I insert them to ME network, the network shows the tanks. don't mind of the quantity. there are bunch of basic tanks inserted in advance for testing.

![2019-08-28_06 25 04](https://user-images.githubusercontent.com/34593536/63809550-90345100-c95d-11e9-8633-5f007076ee7f.png)

And I close the terminal, and reopen, then, puff. they are gone.

![2019-08-28_06 25 20](https://user-images.githubusercontent.com/34593536/63809551-90345100-c95d-11e9-8c1b-c2dfbb8ddd65.png)

Why I used manual crafting instead of autocrafting? because I have The pattern!

![2019-08-28_06 25 32](https://user-images.githubusercontent.com/34593536/63809552-90345100-c95d-11e9-990c-baa9b2b778a7.png)

Strange. definetely I have a pattern of mekanism tanks from basic to ultimate. AND they used to be worked well. and I don't see them now.

![2019-08-28_06 41 08](https://user-images.githubusercontent.com/34593536/63810151-05545600-c95f-11e9-8eba-71ff29a2a01f.png)

but,  next pattern of the pattern, block of tin, is craftable. so the interface is working well. 

![2019-08-28_06 25 38](https://user-images.githubusercontent.com/34593536/63809553-90cce780-c95d-11e9-9bc3-d8345bfa27df.png)

The area is chunkloaded

![2019-08-28_06 26 16](https://user-images.githubusercontent.com/34593536/63809554-90cce780-c95d-11e9-8e32-35016b4465a6.png)

these are interfaces used for crafting. they are in space dimension, the channels are moved by p2p tunnel. the p2p tunnel is connected to overworld via quantum network bridge. 

![2019-08-28_06 27 57](https://user-images.githubusercontent.com/34593536/63809555-90cce780-c95d-11e9-8a19-7507e0757107.png)

also chunkloaded

This bug happens to 'encoded patterns'(same as #1324), and 'cobblestones named by inscriber name press' also.
I think there should be more.

devs. this bug is serious. please find the cause.

**Comment by NillerMedDild** [comment]
Could you please chunkload your entire AE system with IC2 chunkloaders, and see if the issue persists?

**Comment by PizzaAddict** [comment]
I've downloaded the server save file from the multiplayer admins.(because the IC2 chunkloader was banned item, so I had to experiment it on singleplayer)

I entered the world in singleplayer, and opened the game to LAN to change the gamemode to creative.

![2019-08-30_12 24 28](https://user-images.githubusercontent.com/34593536/63991079-52802580-cb21-11e9-88ae-f8378d281ebe.png)

Placed a chunkloader

![2019-08-30_12 24 32](https://user-images.githubusercontent.com/34593536/63991156-9410d080-cb21-11e9-9c60-0f41aaa7fd25.png)

Chunkloaded the area

![2019-08-30_12 24 40](https://user-images.githubusercontent.com/34593536/63991168-9b37de80-cb21-11e9-8156-a5907a917adc.png)

The problem persists( there should be crafting patterns of basic to ultimate fluid tanks, but only one is showing. insisting all tanks execpt ultimate one is currently invisible)

![2019-08-30_12 29 41](https://user-images.githubusercontent.com/34593536/63991239-e05c1080-cb21-11e9-80ed-db4e03c520be.png)

certainly the network has 113 basic fluid tanks, 15 advanced fluid tanks, but none of them are visible


![2019-08-30_12 34 46](https://user-images.githubusercontent.com/34593536/63991465-fc13e680-cb22-11e9-909d-c3317791c2fa.png)

I changed the setup. Seperated ME drives from main network via subnetwork

![2019-08-30_12 36 16](https://user-images.githubusercontent.com/34593536/63991516-236ab380-cb23-11e9-9396-e86a0382ff38.png)


Subnetwork shows proper content

![2019-08-30_12 36 18](https://user-images.githubusercontent.com/34593536/63991528-2cf41b80-cb23-11e9-948e-0520dd086345.png)

Main network is still on trouble

![2019-08-30_12 36 26](https://user-images.githubusercontent.com/34593536/63991572-49905380-cb23-11e9-8a59-a335be9c6827.png)

this time, the crafting patterns of the main network shows pattern of elite fluid tank also. this shows visible items changing time to time. sometimes, all of recipes(from basic to ultimate) are showed, and sometimes non of they are visible.

![2019-08-30_12 43 10](https://user-images.githubusercontent.com/34593536/63991693-c1f71480-cb23-11e9-996a-477e6870e05f.png)

This time, I've disconnected ME storages from main network. that means, the main ME system now has patterns only, not items.

![2019-08-30_12 44 57](https://user-images.githubusercontent.com/34593536/63991771-fcf94800-cb23-11e9-8d56-1c3c23fbf441.png)

All of patterns are visible now.

In addition to this, I tried:
1: discard ALL of storage cells, replacing them with new ones(used ME I/O port)
2: Same as 1, but This time, the procedure was ME I/O port connected to temporary ME network->A chest connected to storage bus ->Item conduit attatched to ME interface->Main ME network, NOT inserting contents of cells via ME I/O port connected to Main network
3:Moving entire ME controllers. broke down ME structure and built to somewhere else. So technically, I've made A new network, different to previous one.

None of them are worked.

**Comment by PizzaAddict** [comment]
+ I think This Issue is tricky to reproduce. So If you want, I can share the save file(the size if 10gb when compressed, though)

**Comment by NillerMedDild** [comment]
Possibly stupid question, but where do the Quantum Bridges go?
No thanks, I don't have enough room on my laptop for that :P

**Comment by PizzaAddict** [comment]
![2019-08-30_14 16 47](https://user-images.githubusercontent.com/34593536/63994811-e5748c00-cb30-11e9-8556-8ce7d4a2ccf8.png)
The main network connected via p2p network. the bridge you mention is actually A sub network dedicated to carry p2p channel

![2019-08-30_14 17 10](https://user-images.githubusercontent.com/34593536/63994850-0d63ef80-cb31-11e9-86b1-a519856f8879.png)
Sub network.

**Comment by NillerMedDild** [comment]
Ah okay, thank you. I really appreciate all the screenshots btw :)

**Comment by PizzaAddict** [comment]
@NillerMedDild 

the issue is reproducible, for encoded patterns only, Idk how to reproduce for other items(MEkanism fluid tanks, TE fluid tanks, named cobblestones, and 'PackagedAuto' packages..etc)

procedure:
1:make an ME network

![2019-09-01_22 51 55](https://user-images.githubusercontent.com/34593536/64077458-a3ec0880-cd0b-11e9-8529-a041f911033d.png)

2:make bunch of encoded patterns. I've made 18.

![2019-09-01_22 53 10](https://user-images.githubusercontent.com/34593536/64077463-b6fed880-cd0b-11e9-8779-5897025b2f5f.png)

![2019-09-01_22 53 11](https://user-images.githubusercontent.com/34593536/64077472-cc740280-cd0b-11e9-961c-fc49cfc63bbf.png)

3:
insert them into the ME network using shift-click.

![2019-09-01_22 53 29](https://user-images.githubusercontent.com/34593536/64077479-d72e9780-cd0b-11e9-839b-8d8a4db50117.png)

4:try to extract them using shift-click.
BUT SOME OF THEY ARE DIsplayed in the terminal even after EXTRACTED

![2019-09-01_22 53 43](https://user-images.githubusercontent.com/34593536/64077488-ead9fe00-cd0b-11e9-872e-19addb37d5e6.png)

![2019-09-01_22 53 46](https://user-images.githubusercontent.com/34593536/64077498-0218eb80-cd0c-11e9-87d3-d3624f48e100.png)

5:
repeat several times

6: 
Congratulations. Now you have THE BUG. I've certainly inserted 18 patterns, but only 10 of them are showed.
![2019-09-01_22 54 24](https://user-images.githubusercontent.com/34593536/64077502-12c96180-cd0c-11e9-922e-7c323ebe250f.png)

7: Try closing and opening the terminal several times. number of patterns showed are changes time to time. they were 10, now 6

![2019-09-01_22 55 00](https://user-images.githubusercontent.com/34593536/64077523-4b693b00-cd0c-11e9-9518-62b82e548908.png)

**Comment by NillerMedDild** [comment]
Would you mind reposting this issue on the [AE2 GitHub](https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/new?template=bug_report.md)? It has not been reported there.

**Comment by PizzaAddict** [comment]
Yeah. This bug happens in FTB:Revelation 3.01 , Enigmatica2 1.66c, and ATM3R 1.49

**Comment by PizzaAddict** [comment]
LOL. The mod author closed it immediately. 
I think He is not gonna fix this bug.

**Comment by NillerMedDild** [comment]
The issue was closed because you didn't follow the template, I'm guessing.

**Comment by NillerMedDild** [comment]
Closing because the possibility of getting a fix is very low, as I understand it.
