### ISSUE TITLE
Ice and Fire 1.8 adds lots of new content

### ISSUE THREAD

**Issue by Ricket** [NillerMedDild/Enigmatica2Expert#1334]
**Modpack version**
1.68 I hope?

**Can the issue be reproduced?**
n/a

**Issue**
Just wanted to give you a heads-up that Ice and Fire 1.8 adds a lot of new stuff and will probably need a few tweaks to the `IceAndFire.zs` script (new armor etc).

Thank you so much for continuing to keep this modpack up to date after all this time.

**Comment by NillerMedDild** [comment]
I'm not planning to update it tbh, too much new content to adapt.

**Comment by Ricket** [comment]
Ah that's unfortunate, can you give any tips in case someone (perhaps myself) were to do it? For example what's the thinking behind the removals in [IceAndFire.zs#36](https://github.com/NillerMedDild/Enigmatica2Expert/blob/master/scripts/IceAndFire.zs#36) ?

**Comment by NillerMedDild** [comment]
We already have Sapphire and Silver Armor, and non-Tinkers tools without special abilities are generally disabled to enforce the custom harvest levels :)
