### ISSUE TITLE
Black Hole Storage Quest not completeable

### ISSUE THREAD

**Issue by Adatrem** [NillerMedDild/Enigmatica2Expert#1338]
**Modpack version**
1.67

**Can the issue be reproduced?**
Yes

**Issue**
In Order to complete the Quest "Black Hole Storage", you have to craft the "Black Hole Controller (DEPRECATED)". The problem is that you can only craft the Black Hole Controller v2.0 since well, the "original" one is deprecated. Sadly the v2.0 one does not fulfill the retrieval task.

**Comment by NillerMedDild** [comment]
The issue you are experiencing has been fixed, please run the command `/bq_admin default load` to reload your quests.
You need admin rights to run the command. If you're playing singleplayer and don't have cheats enabled, Open to LAN from the Esc menu, with cheats enabled.
