### ISSUE TITLE
Crash caused by allocation of memory greater than 8GB

### ISSUE THREAD

**Issue by NazTDragN** [NillerMedDild/Enigmatica2Expert#1339]
**Modpack version**
1.68

**Can the issue be reproduced?**
Yes: So far

**Logs**
Does not generate Log upon choosing the option to.

**Issue**
Accidentally deleted E2: Expert when trying to delete normal E2. After reinstall, trying to load instance causes crash that doesn't result in a Crash Log. All previous loads before reinstall worked fine.

Edit before initial post: Seems that crash 'may' be caused by allocating more than 8GB. When lowered back down to 8GB, Instance loaded with no issues. Using Twitch App for Mod-pack installation/play.

**Comment by NillerMedDild** [comment]
So... there's no issue? :)
