### ISSUE TITLE
Fluid Transposer getting stuck in crafting

### ISSUE THREAD

**Issue by frostedclaws** [NillerMedDild/Enigmatica2Expert#1341]
**Modpack version**
1.65d

**Can the issue be reproduced?**
occurred 5+ times in troubleshot area. have not tried to reproduce in another build.

**Logs**
https://imgur.com/a/OGtMFY7

**Issue**
autocrafting in fluid transposer gets stuck until i grab and replace input materials.

Have noticed it with Niter, Pulverized obsidian, possibly snowballs.  When trying to make the powders that the blaze(ish) mobs drop the transposer will get stuck until i come and remove then replace the items.  The current setup is in a compact machine and uses ae2 interface to move items into the transposer, ender i/o to grab output and put back into the interface.  'ME Liquid Export Bus'  filling the transposer all the time with 'Liquid Exp' from cyclic.  Have tried blocking mode on and off in the ae2 interface. Also tried auto-pull enabled and disabled in the transposer.  In the pic it stopped again while i was in its fluid transposer config screen.  Crafting queus are created from a fluid level emitter around the magma crucible.

I did not move onto the newest version of the pack because i dont want to lose dank/null mod and changelog never explained why it was removed just that it was.

**Comment by frostedclaws** [comment]
The chunk the compact machine is in is chunk loaded. The rest of the AE2 network should be chunkloaded as well.  One of the times i noticed it bugged out was when just starting the game up today.  The channels in the room showed 8 on the compact machine internat network like it was an adhoc network.  Replacing the ME Capability Adapters (in and out) and the closest wires fixed that problem.

**Comment by NillerMedDild** [comment]
I'm fairly certain this issue is fixed in the latest version. The changelogs has a link to annotate that explains why Dank/Null was removed.
