### ISSUE TITLE
Death by falling block

### ISSUE THREAD

**Issue by UnknownJester** [NillerMedDild/Enigmatica2Expert#1344]
**Can the issue be reproduced?**
Yes

Dying by a falling block, tried twice with a deathworm from fire & ice, deletes your grave marker and all your items.

**Comment by NillerMedDild** [comment]
So you were killed by a Deathworm, and no grave spawned?

FYI, you can restore your inventory with the command `/tmg_restore playername latest`
You can also cycle through deaths with tab, if you omit latest from the command.

**Comment by UnknownJester** [comment]
Not that I could tell, I did get the grave sheet when I respawned but when I went back to where I died there was just a bunch of sand. I dug down and no grave stone.

Thanks, I didn't know that.

**Comment by NillerMedDild** [comment]
Did you check around your death waypoint? Sometimes falling blocks can displace the grave, it'll try to go to the nearest suitable location.

**Comment by UnknownJester** [comment]
I did, I can double check to make sure I didn't miss anything.

**Comment by NillerMedDild** [comment]
Errr that's... odd. Can you check it's contents?

**Comment by UnknownJester** [comment]
I would but it seems I don't have access to any commands. Unless I'm doing something wrong which is very possible.

**Comment by NillerMedDild** [comment]
If you're in single player, open to LAN and enable cheats.

**Comment by UnknownJester** [comment]
Trying to restore the grave doesn't work. I'm trying tmg_restore playername latest playername

**Comment by NillerMedDild** [comment]
You did substitute playername for your playername right? Also, remember backslash and only playername once, like I wrote it.
