### ISSUE TITLE
Feature Request Chickens Mod

### ISSUE THREAD

**Issue by timmyderselts** [NillerMedDild/Enigmatica2Expert#1345]
I've played a lot of the stone block mod pack but love this one better however I fell in love with the chickens, more chickens, and hatchery mods. Whould love to see them in this pack. Links added for your viewing pleasure.

Chickens: https://www.curseforge.com/minecraft/mc-mods/chickens
More Chickens: https://www.curseforge.com/minecraft/mc-mods/more-chickens
Hatchery: https://www.curseforge.com/minecraft/mc-mods/hatchery

**Comment by Discomanco** [comment]
There are already plenty of resource generation options available, so I don't see why more are needed

**Comment by NillerMedDild** [comment]
Agreed, sorry but no :)
