### ISSUE TITLE
[Probable Bug] Extra Cells 2 content unavailable in JEI, ME fluid handling seems impossible.

### ISSUE THREAD

**Issue by sniggyfigbat** [NillerMedDild/Enigmatica2Expert#1346]
**Modpack version**
Enigmatica 2 Expert 1.67

**Can the issue be reproduced?**
Unknown

**Logs**
N/A

**Issue**
I and a few friends use a small server running off a bare-metal box, owned by one of us. I'm currently attempting to make our ME system handle fluid-based crafting. As far as I can tell, this is something that both Extra Cells 2 and modern versions of Applied Energistics are supposed to be able to do, but neither appears to have the appropriate functionality. I spent several hours yesterday attempting to make any of it work to no avail; ME patterns simply can't handle liquids, and nothing relevant came up in JEI for either 'pattern' or '@extracells2'.

However, this morning, while digging through some JEI connections for an entirely different project, I discovered that there *is* an Extra Cells 2 'ME Fluid Pattern' - it just doesn't appear in JEI. I was even able to make the item just fine, once I'd worked out what the recipe was. I can't use it as a pattern in the AE pattern terminal, but I suspect that I'm not supposed to be able to - there's probably other hidden EC2 items that complete the functionality.

What is the intended behaviour? Are the EC2 items supposed to be entirely unavailable? If so, how does one do fluid-based crafting? Or is this just a bug with JEI integration?

*Fig 1: Fluid Patterns can be crafted, but are not available in JEI. What else is unavailable that should be, or is available that shouldn't?*

![Proof.](https://i.imgur.com/Btc7Max.png)

**Comment by NillerMedDild** [comment]
It is intended that Extra Cells items are largely unavailable, they are horribly broken. I've been waiting for the developer of the mod to fix it for about 6 months now, but it looks like removing Extra Cells is the way to go. 
With "vanilla" AE2, I'm fairly certain you can automate fluid crafting by using buckets in the patterns.

**Comment by NillerMedDild** [comment]
Ah right, I can't remove it, we use some of the items from it in recipes ><

**Comment by Discomanco** [comment]
And while vanilla AE2 has fluid storage, it does not support fluid crafting, which Extra Cells does (when it's working that is)

**Comment by sniggyfigbat** [comment]
Right, gotcha'. That's... Painful, frankly. Oh well.
