### ISSUE TITLE
Terrasteel & Elf Portal OCD

### ISSUE THREAD

**Issue by temp1029** [NillerMedDild/Enigmatica2Expert#1349]
When creating the first terrasteel ingot you get 9 nuggets per normal. However it 10 nuggets are required to create the pylons and gateway core for the portal. This means a second terrasteel nugget is needed to open the portal. This wouldn’t be an issue except it leaves 8 left-over nuggets for which there is very little (if any) use.

A simple fix to this, without changing any recipes, would be to give one terrasteel nugget as a reward for the terrasteel ingot quest.

**Comment by NillerMedDild** [comment]
This is entirely intentional :D

**Comment by NillerMedDild** [comment]
... Sorry

**Comment by temp1029** [comment]
Oof, not being kind to my OCD, lol!

Thanks for the response and the amazing mod pack, love playing it!
