### ISSUE TITLE
Rainbow Sprouts and Fairies spawning in Compact Machines

### ISSUE THREAD

**Issue by TheWyrdsmith** [NillerMedDild/Enigmatica2Expert#135]
#### Issue Description
As title, Ember Root passive mobs can spawn inside Compact Machines. They spawn consistently when killed (~5 every few hours) and though the free dye and glowstone is enjoyable it is probably not intended (?). I have never seen these mobs in the Overworld; it may be that as they are the only things allowed to spawn here they do so much more often than usual.

It doesn't appear that there is a dimension blacklist available in the Ember Root configs, and the Compact Machines dimension uses standard biomes (i.e. can't blacklist a compact_machine biome) so this may not be fixable at the moment?

#### Modpack version (Do not use "latest")
1.30

![2018-06-28_20 27 09](https://user-images.githubusercontent.com/661297/42056455-31920628-7b12-11e8-9ce9-1d9b1bdac2e1.png)

**Comment by NillerMedDild** [comment]
Looking into it :)

**Comment by urikkiru** [comment]
This is still occurring as of v1.45 of the pack. Can we have this re-opened?

**Comment by NillerMedDild** [comment]
Issues marked as stale are not resolved, but sure, I'll reopen for clarity.

**Comment by btbenedi** [comment]
bump on this guy? on v1.52 and these little guys are so annoying in my compact machines

**Comment by NillerMedDild** [comment]
Nothing should spawn in Compact Machines, mobs may spawn in RFTools Dimensions.

**Comment by ventolin** [comment]
I'm seeing this in my world, too, in v1.52 of the pack. Super annoying. If it matters, I'm inside a 13x13x13 compact machine and the biome is reported by JourneyMaps as "Extreme Hills."

**Comment by btbenedi** [comment]
@ventolin that was all in the compact machine configs? Shouldn't I ml paxf anything other than being able to build mob spawner in the machines. I'll do that for now at least.

For the record, I have these guys in a lot of machines across a variety of biomed, ocean, forest, plains, to name a few

**Comment by ventolin** [comment]
Yeah, in `config/compactmachines3/settings.cfg` there's `B:allowHostileSpawns` and `B:allowPeacefulSpawns` and I set them both to `false`, and I haven't seen a sprout or fairy since.

**Comment by scribbler957** [comment]
Related: I put grass in a botania cube (didn't want my magnet messing with it) and Animalia critters spawned and ate all my botania flowers! I switched to dirt and put cobblestone along the top to stop it.
