### ISSUE TITLE
Awakened Sharpening Kit uncraftable

### ISSUE THREAD

**Issue by ppoozl** [NillerMedDild/Enigmatica2Expert#1350]
**Modpack version**
1.68

**Can the issue be reproduced?**
unknown

**Logs**
 
[logs.zip](https://github.com/NillerMedDild/Enigmatica2Expert/files/3613001/logs.zip)

**Issue**
Awakened Sharpening Kit uncraftable.

Also, suggest add pickaxe head to complete the mission. So we can choose. I usually just swap my pickaxe head.

If this is a feature request, feel free to delete the template.

**Comment by ppoozl** [comment]
Chaotic also uncraftable.

**Comment by NillerMedDild** [comment]
Are you able to craft any other Tinkers item out of Awakened / Chaotic cores?

**Comment by ppoozl** [comment]
I can't melt Cores.

**Comment by NillerMedDild** [comment]
Use the Part Builder :)
