### ISSUE TITLE
Palm Sapling Leaves not decaying after removing all the wood

### ISSUE THREAD

**Issue by Smfrost** [NillerMedDild/Enigmatica2Expert#1351]
**Modpack version**
1.68

I tested it in a different world as well to see if it was just my world. It seems like the leaves won't decay, the mod that it is from is Biomes O'Plenty

No Logs available 

**Issue**
The leaves on Palm Sapling doesn't decay, the only method of getting saplings is by breaking the leaves. I don't know if this was intentional but most trees leaves are able to decay after breaking the logs except that one. Just a heads-up. Not a big deal for me just want to let you guys know :)

Please close this if it's a mod issue, thanks for reading 👍

**Comment by NillerMedDild** [comment]
I did a bit of reading, and it appears to be intentional, see https://github.com/Glitchfiend/BiomesOPlenty/issues/1165
Thanks for the report anyhow!
