### ISSUE TITLE
Config: Vanillia Tools

### ISSUE THREAD

**Issue by timmyderselts** [NillerMedDild/Enigmatica2Expert#1354]
I have added other mods to my version of E2E and one of them requires vanilla tools, where can I go in the config to re-enable the use of vanilla tools? I tried looking for iguana's but it doesn't seem that it is installed. Any help would be great, thanks.

**Comment by NillerMedDild** [comment]
Remove the script `Tools.zs` found in the `scripts` folder, and remove the mod Tool Progression. That should do the trick :)

**Comment by timmyderselts** [comment]
remove the mod you said and deleted the script, but vanilla tools still have a no durability, idea? I even tried crafting new tools after a restart and still have no durability and have the warning message when i hover over them that they are disabled.

**Comment by NillerMedDild** [comment]
Remove lines 288-326 from `Tooltips.zs` to remove the Tooltip. Which tools did you craft specifically?

**Comment by timmyderselts** [comment]
I was trying to craft a wooden hoe, and it broke after about 3 uses.

**Comment by timmyderselts** [comment]
Nevermind I got it, thanks for the help, realized I had to do the changes on both my client and server not just my server.
