### ISSUE TITLE
Airtight Seal won't apply to Quantum/Nano armor

### ISSUE THREAD

**Issue by Dark-Matter-001** [NillerMedDild/Enigmatica2Expert#1356]
**Modpack version**
1.67

**Can the issue be reproduced?**
Yes

**Issue**
As the title says, you can't put Airtight Seal on Quantum/Nano IC2 armors even tho it says you should be able to.

https://imgur.com/a/YbypG1J

**Comment by NillerMedDild** [comment]
I'm afraid those armors don't accept enchants.
