### ISSUE TITLE
java.lang.NullPointerException: Unexpected error HELP

### ISSUE THREAD

**Issue by Tikayos** [NillerMedDild/Enigmatica2Expert#1357]
**Modpack version**
1.59a

**Can the issue be reproduced?**
unknown

**Logs**
[crash-2019-09-26_14.27.16-client x 2.txt](https://github.com/NillerMedDild/Enigmatica2Expert/files/3660131/crash-2019-09-26_14.27.16-client.x.2.txt)

**Issue**
Basically im trying to play the Enigmatica 2 Expert v. 1.59a on a server with two of my friends. We are all running it off of the Twitch launcher and they can both join and play normally, but i can't. I supposedly join in the game, then 1-2 minutes later leave, all while it still has the loading screen for me. please help

If this is a feature request, feel free to delete the template.

**Comment by NillerMedDild** [comment]
Try re-installing :) 
I'm curious, Why are you using such an old version?

**Comment by Tikayos** [comment]
I’ve tried reinstalling pretty much everything. I’m not sure why we’re using the old version, I think it’s because of how the server was initially set up. Regardless I think the problem is consistent across most, if not all the versions.

**Comment by Frikkle** [comment]
One of the things I noticed in the crash report is that you're running the game with the embedded Java version that comes packaged with Twitch (`1.8.0_51`). This version is quite old and causes quite a lot of the crashes we come across.

You can force Twitch to use your system's Java version instead, by doing the following:
- Make sure you have the latest 64-bit Java installed
- Go to the Twitch Minecraft settings
- Add `-version:1.8+` to the Additional Arguments

Please let me know if doing this resolves the issue for you. If not, please drop us a new crash report and we'll continue from there.

**Comment by Tikayos** [comment]
it wont launch after everything in the launcher(which has been reverted to the old one) is done because of a "unable to locate JRE meeting specification "1.8+"

**Comment by Tikayos** [comment]
also, i had just downloaded java and it showed as 1.8.0_51 as being the highest and only available 64 bit version

**Comment by NillerMedDild** [comment]
You most likely downloaded 32bit Java then, you need 64bit :)

**Comment by Frikkle** [comment]
Also make sure to reboot your computer after installing the 64-bit Java to make sure all under-water settings are properly updated by your operating system.

**Comment by Tikayos** [comment]
I just ended up using java 1.8.0_22 or whatever, works great, thanks for all your help

**Comment by samisnotverygoodatcoding** [comment]
Anyone else looking at this from google, it could also be you're joining a server with a different version than the one you are using.
