### ISSUE TITLE
Recipe bug with making "disk platter" for open computers.

### ISSUE THREAD

**Issue by ChrisVisser** [NillerMedDild/Enigmatica2Expert#1358]
**Modpack version**
1.69

**Can the issue be reproduced?**
yes

**Issue**
When trying to craft the "Disk Platter" via JEI right click the recipe that appears in a table is Ice and Fires "Iron Chain Link"

If this is a feature request, feel free to delete the template.

**Comment by NillerMedDild** [comment]
Thanks for the report, I'll get that fixed :)

**Comment by ChrisVisser** [comment]
Im not sure you hear this enough, you're amazing!.

**Comment by NillerMedDild** [comment]
Thank you! :D

**Comment by PizzaAddict** [comment]
Any workaround please?

**Comment by NillerMedDild** [comment]
Forestry has a special Workbench that allows you to cycle between recipes.

**Comment by PizzaAddict** [comment]
You are genius
