### ISSUE TITLE
Host can't invite lan players to better questing party

### ISSUE THREAD

**Issue by Attakajakka** [NillerMedDild/Enigmatica2Expert#1360]
**Modpack version**
1.69

**Can the issue be reproduced?**
unknown

**Logs**
N/A

**Issue**
When on a lan world the host player is unable to invite players who have joined to a better questing party

If this is a feature request, feel free to delete the template.

**Comment by NillerMedDild** [comment]
Can players who joined invite the host?

**Comment by NillerMedDild** [comment]
@Funwayguy I hope you don't mind the ping - Do you know anything about this issue? :) 

BetterQuesting-3.5.311
StandardExpansion-3.4.167

**Comment by Attakajakka** [comment]
Yes the player who joined could invite the host to a party
