### ISSUE TITLE
Mekanism Induction Matrix shows wrong values.

### ISSUE THREAD

**Issue by YenYenJay** [NillerMedDild/Enigmatica2Expert#1361]
**Modpack version**
Enigmatica 2 1.69

**Can the issue be reproduced?**
Yes/it's related to a mod version

**Issue**
The Mekanism version on the pack doesn't show the correct values in the Induction Matrix (stuck at 2.14GRF). Already been fixed in a newer version.
(https://github.com/mekanism/Mekanism/issues/5609)

**Comment by Frikkle** [comment]
This was reported and discussed in the Discord support chat. I asked Yen to create an issue here for reference reasons and getting it patched. I haven't yet 
confirmed this myself in game.
