### ISSUE TITLE
I'm unable to create a single playerworld. 

### ISSUE THREAD

**Issue by h454** [NillerMedDild/Enigmatica2Expert#1362]
**Modpack version**
1.69

**Can the issue be reproduced?**
Absolutely.

**Logs**
https://paste.dimdev.org/emalokiqah.rb

**Issue**
Everytime I try to create a new world in Singleplayer the game crashes before it gets to finish loading up. This is on a fresh install using the Twitch launcher and default settings with 9 GBs of ram allocated.

**Comment by NillerMedDild** [comment]
You appear to be using outdated Java. This is often caused by Twitch defaulting to an older version than you have available. Follow these steps to update.

* Make sure you have the latest 64-bit Java installed
    https://www.java.com/en/download/manual.jsp Windows Offline (64-bit) is the one you need
* Go to the Twitch Minecraft settings
* Add `-version:1.8+` to the Additional Arguments

Additionally, I recommend that you lower the RAM allocation to 8GB, unless you're using shaders or texture packs.

**Comment by h454** [comment]
I have done the things you have suggested but the error still persists?

- Log 
https://paste.dimdev.org/ezaxedowah.rbsss
- Settings Screenshot 
https://i.imgur.com/26iJdC5.png

I don't seem to have this issue with Enigmatica 2 Non-Expert mode.

**Comment by NillerMedDild** [comment]
Hmm. You've tried to generate multiple new worlds right? Have you tried reinstalling the modpack completely?

**Comment by h454** [comment]
So, I have reinstalled the modpack but the issue is back with what seems to be the exact same error.
I don't think there's any useful information in the log.

- Log
https://paste.dimdev.org/ohugimagan.rb

Could my JVM arguments be incorrect?

`-d64 -server -XX:+AggressiveOpts -XX:ParallelGCThreads=6 -XX:+UseConcMarkSweepGC -XX:+UnlockExperimentalVMOptions -XX:+UseParNewGC -XX:+ExplicitGCInvokesConcurrent -XX:MaxGCPauseMillis=10 -XX:GCPauseIntervalMillis=50 -XX:+UseFastAccessorMethods -XX:+OptimizeStringConcat -XX:NewSize=84m -XX:+UseAdaptiveGCBoundary -XX:NewRatio=3 -Dfml.readTimeout=90 -Ddeployment.trace=true -Ddeployment.log=true -Ddeployment.trace.level=all -Dfml.debugNetworkHandshake=true -Dfml.badPacketCounter=10 -version:1.8+`

**Comment by NillerMedDild** [comment]
Yes, they absolutely could :)

Recommend arguments:

```
-version:1.8+ -XX:+UseG1GC -Dsun.rmi.dgc.server.gcInterval=2147483646 -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
```

**Comment by h454** [comment]
Alright nice, I'll try them out now and I'll see if that fixes it.

**Comment by h454** [comment]
Changing the JVM Arguments to the ones you listed fixed the issue!
Thank you for your help.

**Comment by NillerMedDild** [comment]
Awesome, no problem.
