### ISSUE TITLE
[Crash Report] Repeated crashes on startup.

### ISSUE THREAD

**Issue by sniggyfigbat** [NillerMedDild/Enigmatica2Expert#1363]
**Modpack version**
Enigmatica 2 Expert 1.69

**Can the issue be reproduced?**
Unknown

**Logs**
[Here.](https://pastebin.com/ZGJ3BTmy)

**Issue**
I'm having significant problems getting the game to launch, and even when it does it crashes almost immediately. This produces no crash reports, the logs just seem to end in the middle of normal operation. It's also an entirely new behaviour; the modpack ran fine yesterday, and I didn't change anything overnight. I've tried the 'Repair Profile' on Twitch, and that didn't help either.

I'm a bit stumped, frankly. It seems likely to be an issue on my end rather than the modpack's but there are issues in the logs, and I though it was worth checking whether they're likely to be the culprit.

**Comment by Discomanco** [comment]
You appear to be using outdated Java. This is often caused by Twitch defaulting to an older version than you have available. Follow these steps to update.

* Make sure you have the latest 64-bit Java installed
    https://www.java.com/en/download/manual.jsp Windows Offline (64-bit) is the one you need
* Go to the Twitch Minecraft settings
* Add -version:1.8+ to the Additional Arguments

**Comment by sniggyfigbat** [comment]
I've followed the instructions given by @Discomanco , and unfortunately they haven't really solved the issue. It *was* using the Twitch-bundled version of Java, however, so it's possible that was a factor.

The crashes are still occurring seemingly at random, however, although at a reduced rate - I usually at least get past the loading screen now. I've attached the very end of the latest log [here](https://pastebin.com/cXHLbtLH), as it included some exciting-looking errors.

**Comment by NillerMedDild** [comment]
Those errors aren't meaningful I'm afraid, could you supply the entire latest.log please? The one from your last attempt :)

**Comment by sniggyfigbat** [comment]
[2019-10-02-2.log.gz](https://github.com/NillerMedDild/Enigmatica2Expert/files/3682085/2019-10-02-2.log.gz)

That's the full log. Interestingly, the version in the gz is different to the latest.log version, and has a bunch of extra issues at the end. I had assumed they'd be identical.

I really your taking the time to help!

**Comment by Discomanco** [comment]
Was there generated a crashlog for the server? Because that latest.log doesn't indicate a crash at all.
The client log doesn't say anything meaningful either. The best log to provide is the file `latest.log`, and not any of the compressed ones. This goes for both client and server

**Comment by sniggyfigbat** [comment]
No, unfortunately the server didn't generate a crash log. I now suspect that the issue with the server was entirely separate; this is completely anecdotal, but using brown magic to teleport too and from the further end (the bit through the ender-pearl portal) seemed to cause the server to start lagging uncontrollably. Restarting the server seems to fix the issue, and next time I'm on without anyone else online I'll test it again to see whether that was actually a correlation rather than simply coincidence.

The random crashing seems to have tailed off significantly, but still happens occasionally. Again, there is no obvious error and no crash report, the game simply shuts down. At this point, it's infrequent enough to merely be annoying rather than unplayable. Very odd, given that, again, I don't believe I've changed anything remotely relevant.

I would attach the latest.log for the most recent crash, but it's over the 10MB file size limit. Will add the next applicable log the next time I play.

**Comment by sniggyfigbat** [comment]
Bah, spoke too soon. Crashed during startup. Again, nothing remotely helpful in the log, no crash report.

[latest.log](https://github.com/NillerMedDild/Enigmatica2Expert/files/3683604/latest.log)

**Comment by NillerMedDild** [comment]
Hmm.. how much RAM have you allocated, and how much does your PC have?

**Comment by Halfdeaf** [comment]
I've been having this issue too. Allocating 8gb, system has 16. 
[2019-10-03-1.log.gz](https://github.com/NillerMedDild/Enigmatica2Expert/files/3688381/2019-10-03-1.log.gz)
No crash report generated

**Comment by NillerMedDild** [comment]
Could you please provide latest.log instead Halfdeaf? :)

**Comment by sniggyfigbat** [comment]
Similarly to Halfdeaf, I've got 16GB in the PC, and I'm allocating over 8GB.

**Comment by Halfdeaf** [comment]
[latest.log](https://github.com/NillerMedDild/Enigmatica2Expert/files/3693797/latest.log)
Happened again today. Here is the latest from that

**Comment by NillerMedDild** [comment]
Useless log again I'm afraid :/ you are using old java though.

**Comment by NillerMedDild** [comment]
Sorry guys, but I can't do anything about this issue for now.

**Comment by sniggyfigbat** [comment]
I've found a strong candidate for the culprit: Running MemTest86 reveals that my RAM is essentially swiss cheese. Hardware, not software, is likely the issue.

Sorry for wasting people's time!

**Comment by Frikkle** [comment]
No worries, stuff happens.
