### ISSUE TITLE
Checkbox wont open on server

### ISSUE THREAD

**Issue by lux-skyeward** [NillerMedDild/Enigmatica2Expert#1364]
**Modpack version**
1.68

**Can the issue be reproduced?**
unknown

**Issue**
I'm on a LAN server that I do not own. Checkbox gates (astral sorcery and forestry) aren't opening or registering that I am even trying to select it. The first checkbox did open. The other person on the server isn't having these issues. What do?

If this is a feature request, feel free to delete the template.

**Comment by Frikkle** [comment]
I'm not sure if this is a know issue, but just to gather some additional information: are you guys physically on the same network or using a tool like Hamachi to simulate LAN behaviour across the internet?
