### ISSUE TITLE
Elite teir installer issue

### ISSUE THREAD

**Issue by Echo251** [NillerMedDild/Enigmatica2Expert#1365]
**Modpack version**
the latest version

**Can the issue be reproduced?**
unknown

one of my party members unlocked the quests advanced, elite and ultimate tier installers and since completing these quest i havent been able to collect any rewards from quests i have completed, and i keep getting the quest notification and sound for the tier installers going off. 

i tried deleting my profile from the server. 
i tried reseting my server to a date before the quests were complete. 
i tried enter edit mode in the quest book and reseting the quest and putting them as complete but they just keep bugging out from completed to incompleted. 

can anyone help me XD

If this is a feature request, feel free to delete the template.

**Comment by NillerMedDild** [comment]
Thank you for the report. Which modpack version are you on?

**Comment by Echo251** [comment]
version 1.69 i think

**Comment by NillerMedDild** [comment]
Please make sure.

**Comment by Nabbieshtron** [comment]
1.69 is not there yet or i cant install it

**Comment by NillerMedDild** [comment]
https://www.curseforge.com/minecraft/modpacks/enigmatica2expert/files/2791602
