### ISSUE TITLE
EnderStorage Crash

### ISSUE THREAD

**Issue by Yoyotree12** [NillerMedDild/Enigmatica2Expert#1366]
**Modpack version**
1.68

**Can the issue be reproduced?**
unknown

**Logs**
https://paste.dimdev.org/jahujikudo.mccrash

**Issue**
I loaded up my world and my minecraft crashed and told me EnderStorage is causing the problem.

**Comment by NillerMedDild** [comment]
I'm guessing you read this `EnderStorage was unable to read it's data, please delete the 'EnderStorage' folder Here: C:\Users\kavip\Twitch\Minecraft\Instances\Enigmatica 2 Expert\saves\Enigmatica 2\EnderStorage and start the server again.` from the log? :)
