### ISSUE TITLE
Angel Ring not working properly

### ISSUE THREAD

**Issue by Nabbieshtron** [NillerMedDild/Enigmatica2Expert#1367]
**Modpack version**
1.68

**Can the issue be reproduced?**
unkown

**Logs**
no crash

**Issue**
Angel Ring and Angel ring of squids loosing grid power flying from energy source even when chunks on source are loaded

If this is a feature request, feel free to delete the template.

**Comment by NillerMedDild** [comment]
The issue is almost certainly faulty chunk loading I'm afraid, and we have not been able to get that issue fixed :/

**Comment by Nabbieshtron** [comment]
might be because my ender pouch not working anymore with ender chest

**Comment by NillerMedDild** [comment]
Those shouldn't be affected by chunkloading.

**Comment by Nabbieshtron** [comment]
well then thats another issue their not working

**Comment by Nabbieshtron** [comment]
i sometimes getting crash errors where i can upload them

**Comment by NillerMedDild** [comment]
https://gist.github.com/

**Comment by Nabbieshtron** [comment]
Hey i just wanna tell you that might be same things with chunk loading , I'm not sure but universal cable  randomly stops working.But i can fix it by replacing it.

**Comment by Nabbieshtron** [comment]
I dont know what is happening but my angel ring and ender chest start working again ???
