### ISSUE TITLE
Disk platter from open computer  recipe conflict with Iron chain link from ice and fire 

### ISSUE THREAD

**Issue by waffleviet** [NillerMedDild/Enigmatica2Expert#1368]
**Modpack version**
Egnimiatic 2 expert version 1.69

**Can the issue be reproduced?**
Yes
**Issue**
Input short description of the issue here
So the iron chain link from ice and fire has a recipe conflict with the disk platter from open computers that has a recipe conflict. I don't know how to craft the disk platter from an open computer. This is important because its used to craft stuff like the digital miner from mekanism.

**Comment by PizzaAddict** [comment]
#1358
