### ISSUE TITLE
Indusctial craft uranium rod

### ISSUE THREAD

**Issue by Nabbieshtron** [NillerMedDild/Enigmatica2Expert#1369]
**Modpack version**
1.68

**Issue**
Fuel rod(Uranium), Duel fuel rod(Uranium), Quad fuel rod(Uranium) all 3 has same durability 20000
Fuel rod(Mox), Duel fuel rod(Mox), Quad fuel rod(Mox) all 3 has same durability 10000

I don't know is it actually work as durability says that might be just wrong number or as it says

**Comment by NillerMedDild** [comment]
Extra fuel rods generate more energy, they don't last longer.
