### ISSUE TITLE
Metallurgical Infuser crash

### ISSUE THREAD

**Issue by Catonyx** [NillerMedDild/Enigmatica2Expert#137]
#### Issue Description
Crash when looking at recipe for metallurgical infuser

#### Modpack version
1.30

#### Crash Report
https://paste.ee/p/CX96Y

```
Description: Rendering item

java.lang.ClassCastException: it.unimi.dsi.fastutil.ints.Int2ObjectOpenHashMap cannot be cast to gnu.trove.map.hash.TIntObjectHashMap
	at team.chisel.ctm.client.model.ModelUtil.lambda$getMesh$0(ModelUtil.java:51)
	at java.util.Optional.map(Unknown Source)

```

**Comment by NillerMedDild** [comment]
I believe this has been fixed in a recent update to JEI, do you mind trying to reproduce it on update 1.31, when that goes live?

**Comment by Catonyx** [comment]
As an update, it's not just the metallurgical infuser. It also crashes when I view the recipe of the wood to iron chest upgrade

**Comment by Catonyx** [comment]
It turns out it's because I had the wrong version of forge. I'm sorry for the invalid report

**Comment by NillerMedDild** [comment]
No worries.
