### ISSUE TITLE
[Feature Request] A High-Tier Infinite-Durability Graphite Electrode

### ISSUE THREAD

**Issue by sniggyfigbat** [NillerMedDild/Enigmatica2Expert#1370]
*Immersive Engineering*'s Arc Furnaces are neat. They're a cool multiblock, they do their job well, they feel sensibly priced, and they look awesome while doing it.

Unfortunately, they also run on Graphite Electrodes, which run out. And they can't be restocked automatically, because *IE*'s designer makes questionable game-design decisions.

This means that, if we ever forget to shut down our ore extractors / digital miners / gravel sieving setup / etc, we inevitably return to a server that's running at one tick a minute because the electrodes have run out, the buffer chests are full, and there's ten thousand entities sitting on an *Immersive Engineering* belt.

To be clear, there are ways around this, starting with not using *IE* belts, and including changing the graphite rod durability in the config. But the latter feels cheap, and the former feels a bit sad, because *IE* belts are cool and look neat.

Is there any chance of adding an infinite-durability graphite electrode equivalent to the modpack? Using an Fluid Transposer to infuse an electrode with blutonium would probably do the trick, or some other high-tier process. It'd be a nice way of making *IE* arc furnaces viable in the mid- to late-game, and it'd help our server's tick-rate a hell of a lot!

**Comment by Frikkle** [comment]
I get the idea and I feel your pain; additionally I love seeing people that put the Arc Furnace to good use, awesome. But at the same time I feel I have to mention that if you put in the time to nicely automate IE stuff, you can also create overflow mechanisms that will take stuff from the belts into an overflow buffer, which you can configure in such a way that when the buffer fills up, the machines feeding onto the belt in the first place, also stop.

On another related note, you can actually enchant the Graphite Electrodes to increase their lifespan by a lot.

As for your feature request; I am not too sure about the complexity of such a change, if it would even be possible at all. Niller might have to pitch in on that. But as development focus is on E4 I am not all too sure many changes to E2 will be pushed unless.

Marking is as a feature request/suggestion but leaving it for Niller for further thoughts.

**Comment by NillerMedDild** [comment]
The Arc Furnace is not meant to be 100% automatable, that's the trade-off for it's many uses, so we will not be working on this, sorry.
