### ISSUE TITLE
I keep catching JEI exceptions whenever I launch Enigmatica 2 Expert.

### ISSUE THREAD

**Issue by SamuelBucher** [NillerMedDild/Enigmatica2Expert#1373]
**Modpack version**
1.69

**Can the issue be reproduced?**
Yes

**Logs**
https://pastebin.com/ctHZ62wR

**Issue**
Minecraft crashes immediately after loading with this message: The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Just Enough Items (jei)

**Comment by NillerMedDild** [comment]
You need to allocate already 6GB RAM.
