### ISSUE TITLE
Slow stack crafting in player inventory

### ISSUE THREAD

**Issue by Aelian778** [NillerMedDild/Enigmatica2Expert#1374]
E2E v1.69 (no mods added JRE1.8 x64)
Forge v14.23.5.2838

**Can the issue be reproduced?**
Yes

**Issue**
When crafting a stack (shift click) in the player inventory (like planks from logs for example) there is a very noticeable lag, one plank gets in the inventory then one second later, the rest of the stack. It also seems like the whole world freezes while the rest of the stack is being crafted. This does not happen when using crafting tables.

**Comment by NillerMedDild** [comment]
I'm afraid there's nothing we can do about that.
