### ISSUE TITLE
Quest book completion glitch 

### ISSUE THREAD

**Issue by Echo251** [NillerMedDild/Enigmatica2Expert#1375]
**Modpack version**
1.69

**Can the issue be reproduced?**
unknown

**Issue**
basically i cannot complete any quest whether i complete them or if my party member completes them, the quest book glitches between them being completed and being uncompleted but when i make a quest item it allows my party member to get the reward.. i tried manually completing the quest in edit mode which did not work either, resetting the quest book. and leaving the current party and resetting then.

i do want to try and keep my party part member quest if there is any methods of solving this issue.

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.
Are you in a LAN world or server?

**Comment by Echo251** [comment]
i am in a LAN world

**Comment by Echo251** [comment]
is there any way i can fix it cause it is ruining my game i cant complete
quest easily cause i cant look into descriptions etc

**Comment by NillerMedDild** [comment]
It's fixed in the new version :) you just need to update.
