### ISSUE TITLE
Advanced Rocketry: After 1.69 update rockets drift horizontally and "miss" the ground/space station LZ.

### ISSUE THREAD

**Issue by Melikoth** [NillerMedDild/Enigmatica2Expert#1376]
**Modpack version**
Enigmatica 2 Expert 1.69

**Can the issue be reproduced?**
Issue is reproducible on the multi-player server I am playing on by all players who have used Advanced Rocketry. Unknown if it can be reproduced from scratch.

**Logs**
None available from server at the moment.

**Issue**
I am playing on a small multi-player server hosted by a friend. After the recent update to 1.69 any shuttle launched with players aboard becomes "lost in space". 

If the target of the mission was a space station landing pad the rocket will move westward horizontally while descending causing the rocket to miss the landing pad and get stuck falling. You must suffocate to death to return to earth. 

If Luna was the target of the mission the rocket will move westward horizontally while descending but seemingly never encounter the surface. You can jump off the rocket and land on the ground in this scenario and must suffocate to return to earth.

We were unable to find a way to reset the data for Luna or the space stations, thought it appears possible for all other planets.

**Comment by NillerMedDild** [comment]
Thanks for the report. Does your server use SpongeForge?

**Comment by NillerMedDild** [comment]
Also, deleting the advRocketry folder from the world resets it's worlds.

**Comment by vanpunch** [comment]
I'm playing on the same server as Melikoth and talked to the guy that's hosting it.  We are not using SpongeForge, We're attempting to delete the advRocketry folder to see if that makes a change.

**Comment by NillerMedDild** [comment]
If anyone has encountered this issue on another server, please let me know :)

I need the servers latest.log please @Melikoth

**Comment by Melikoth** [comment]
Here's a log from a little earlier today.

[latest.log](https://github.com/NillerMedDild/Enigmatica2Expert/files/3726847/latest.log)

**Comment by NillerMedDild** [comment]
Could you try switching to JRE or JDK please? OpenJDK has a few issues with Minecraft.

**Comment by vanpunch** [comment]
Switched to JRE

Bug persists

Changes

Now moves positive along x-axis (used to move negatively)
Did not land on moon till i jumped off and "pushed" it down by jumping on it (would never land on moon before)
When coming back to earth, got stuck at 405, like it was sitting on land
Rocket Switched to JRE

Bug persists

Changes

Now moves positive along x-axis (used to move negatively)
Did not land on moon till i jumped off and "pushed" it down by jumping on it (would never land on moon before)
When coming back to earth, got stuck at 405, like it was sitting on land
Rocket disapeared on "disassembling"



Started Creative World on Local PC,
Had same bug

Difference
Moved on negative z-axis
Rocket had to be "pushed" down to moon again,
Could also push it down to earth. on "disassembling"



Started Creative World on Local PC,
Had same bug

Difference
Moved on negative z-axis
Rocket had to be "pushed" down to moon again,
Could also be pushed down to earth.

**Comment by Melikoth** [comment]
Did some testing with a fresh copy of E2E 1.69 launched via MultiMC using Oracle JRE 1.8.0_221, logs attached. The issue is reproducible in single-player creative worlds as well.

Created/loaded a superflat word, the exited and reloaded to make sure everything was working properly. Built the minimal launchpad/fueling setup and minimum viable rocket. Set destination for Luna and took off. Oddly, it landed just fine. Then I jumped back on and hit launch with the destination still set to Luna, went into orbit and this time when coming in for landing it "missed" the ground.

[latest.log](https://github.com/NillerMedDild/Enigmatica2Expert/files/3729925/latest.log)
[debug.zip](https://github.com/NillerMedDild/Enigmatica2Expert/files/3729926/debug.zip)

**Comment by NillerMedDild** [comment]
So while on Luna, you launched towards Luna?

**Comment by Melikoth** [comment]
Yes.

**Comment by NillerMedDild** [comment]
I think the rocket is trying to do a full cycle around the world, to return to the place of launch. Iirc rockets can be used to travel horizontally if you specify coordinates.

**Comment by Melikoth** [comment]
I posted it so you could easily see how the bug worked when reproduced. Had I known it would cause my issue to invalidate I wouldn't have provided that test data. 

Did some additional testing this morning and it doesn't reproduce 100% going Luna to Luna anyhow, it worked about 3 times in a row before finally causing a fail to land scenario. At any rate it looks like if you're playing a multiplayer server and anyone causes this issue once then the whole server is done with space. 

We're gonna try a rollback on our multiplayer server and keep troubleshooting. Thanks for your help!

**Comment by NillerMedDild** [comment]
I just tested this in single player, and there definitely is some kind of bug. I'm getting all kinds of different results though. Sometimes it works perfectly fine, sometimes I land 30 blocks above the ground, sometimes I don't land.

But to be completely honest with you, I don't think we'll be getting a fix, even if we know what the issue is.

**Comment by Melikoth** [comment]
That was also my experience regarding the cause and results. Unfortunately, I haven't learned anything new/useful from the subsequent tests. I've noticed some other odd behavior in Advanced Rocketry however, so it does seem to be isolated.

We've been using the following set of workarounds to the issue to minimize use of Advanced Rocketry and turn the risks into annoyances: 
1) Ensure you have the inventory cake upgrade. Items stored there remain in those slots through death, so handy for retaining your items in the event the bug is encountered
2) Setup an RFTools teleporters on each planet visited so others can easily reach them.

Thanks for taking a look into the issue!
