### ISSUE TITLE
After 1.70 update, now creating Mekanism steel instead of Thermal

### ISSUE THREAD

**Issue by md5i** [NillerMedDild/Enigmatica2Expert#1378]
**Modpack version**
1.70

**Issue**
After the update to 1.70, Mekanism infusers are creating steel dust instead of steel blend, which then turns into Mekanism steel ingots instead of Thermal Foundation steel ingots.  This breaks huge numbers of autocrafting recipes.

**Comment by md5i** [comment]
I will note that the Mekanism steel does not show up in JEI.

**Comment by NillerMedDild** [comment]
I will hotfix within a few hours, thank you for letting me know :) if you're playing single player you can fix it by downgrading the mod UniDict one version.

**Comment by NillerMedDild** [comment]
I found some time, I'm verifying the fix now, will ship a new version in about 10 minutes if the fix works.
