### ISSUE TITLE
Crashing on startup

### ISSUE THREAD

**Issue by CielSensei** [NillerMedDild/Enigmatica2Expert#1379]
**Modpack version**
1.70b

**Issue**
Crashing on startup

**Logs**
https://pastebin.com/sEyexEtc

**Comment by NillerMedDild** [comment]
You appear to be using outdated Java. This is often caused by Twitch defaulting to an older version than you have available. Follow these steps to update.

* Make sure you have the latest 64-bit Java installed
    https://www.java.com/en/download/manual.jsp Windows Offline (64-bit) is the one you need
* Go to the Twitch Minecraft settings
* Add `-version:1.8+` to the Additional Arguments
