### ISSUE TITLE
Game crashes on startup.

### ISSUE THREAD

**Issue by SamuelBucher** [NillerMedDild/Enigmatica2Expert#1382]
**Modpack version**
1.70

**Issue**
I followed the instructions from here: https://github.com/NillerMedDild/Enigmatica2Expert/issues/1381, and now my game crashes on startup. Did I do something wrong?

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by NillerMedDild** [comment]
You can write in closed issues, fyi :)

When does it crash on startup? Do you have a crash report?

**Comment by SamuelBucher** [comment]
https://pastebin.com/ctHZ62wR

**Comment by NillerMedDild** [comment]
Ah, I thought you were on 1.70b. You need to update to 1.70b :)

**Comment by SamuelBucher** [comment]
I am.
![2019-10-20](https://user-images.githubusercontent.com/56469863/67151392-3abd5600-f2b5-11e9-83a6-960976359297.png)

**Comment by NillerMedDild** [comment]
Damn. Reinstall then I guess.

**Comment by SamuelBucher** [comment]
That won't wipe my safe file, right?

**Comment by jamaa** [comment]
Having the same issue after updating to 1.70b

**Comment by SamuelBucher** [comment]
I removed the -version:1.8+ from Additional Arguments and and now the game doesn't crash on launch. However, the previous issue is still there, making my survival world virtually unplayable.

**Comment by jamaa** [comment]
I followed the advice in #1379 and forced the use of latest Java (thought not with the Additional Argument, but by specifying the Java version to use in the Minecraft launcher) and no longer get a crash on startup :-)

**Comment by SamuelBucher** [comment]
I should also note that this started when I was on version 1.69.

**Comment by SamuelBucher** [comment]
> I followed the advice in #1379 and forced the use of latest Java (thought not with the Additional Argument, but by specifying the Java version to use in the Minecraft launcher) and no longer get a crash on startup :-)

I did this for the latest Java and I get a crash on startup.

**Comment by NillerMedDild** [comment]
Sounds like you have 32bit Java installed. Either way, this is a support issue, not a bug. If you need more help please go to the discord.

**Comment by SamuelBucher** [comment]
Have managed to make Minecraft work on latest Java. But looking at JEI still causes an immediate crash, and ONLY on my survival world. That's a bug, right? 

Latest log: https://pastebin.com/ctHZ62wR

**Comment by NillerMedDild** [comment]
Please write that you're using Optifine in your bug reports. Does the crash happen if you remove Optifine?

**Comment by SamuelBucher** [comment]
No.

**Comment by NillerMedDild** [comment]
Alright then.

**Comment by SamuelBucher** [comment]
Oh. Alright then. Guess no Optifine for me. Thanks for help.
