### ISSUE TITLE
Crash on modpack launch

### ISSUE THREAD

**Issue by erplsf** [NillerMedDild/Enigmatica2Expert#1383]
**Modpack version**
1.70b

**Issue**
After upgrade via Twitch launcher, trying to start a modpack I receive a crash
Short part that may help:
```
The game crashed whilst initializing game
Error: java.lang.IllegalArgumentException: Cannot set property PropertyAnyInteger{name=variation, clazz=class java.lang.Integer, values=[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]} to 1 on block unlimitedchiselworks:chisel_planks_oak_forestry_planks_0_14, it is not an allowed value
```

**Logs**
https://pastebin.com/rZmRVpHZ

**Comment by Discomanco** [comment]
You appear to be using outdated Java. This is often caused by Twitch defaulting to an older version than you have available. Follow these steps to update.

* Make sure you have the latest 64-bit Java installed
    https://www.java.com/en/download/manual.jsp Windows Offline (64-bit) is the one you need
* Go to the Twitch Minecraft settings
* Add -version:1.8+ to the Additional Arguments

**Comment by erplsf** [comment]
Sorry. It's very weird, because I don't have auto-updates enabled but after fourth try it launched successfully.
