### ISSUE TITLE
FoamFix Startup Crash

### ISSUE THREAD

**Issue by NillerMedDild** [NillerMedDild/Enigmatica2Expert#1384]
FoamFix and Unlimited Chisel Works causes startup crashes for some people, setting `smallPropertyStorage=false` in the foamfix config fixes this.

**Comment by asiekierka** [comment]
Was this fixed by UCW 0.3.2?

**Comment by NillerMedDild** [comment]
I don't know, I was never able to reproduce the issue, and we've kept `smallPropertyStorage` set to false.

**Comment by asiekierka** [comment]
It seems to have been (but I need proof!) a race condition caused by an omission on my side in UCW. Note that keeping smallPropertyStorage set to false increases E2:E's constant memory usage by I think approximately 300-500MB.

**Comment by NillerMedDild** [comment]
So SmallPropertyStorage isn't just set to false anymore? If it works now, I wouldn't mind making an alpha build to test it.

**Comment by asiekierka** [comment]
smallPropertyStorage was always true by default, it's just that UCW had a bug which prevented it from working right.

It *should* work now. An alpha build would be nice - I have gotten two reports back that the crash no longer occurs from people who could reproduce it more often (it was a race condition, people with high core counts or specific mod setups would get it more often as such).

**Comment by NillerMedDild** [comment]
Ahh, that explains why I never got the crash. I'll try to get a build out this weekend :)

**Comment by asiekierka** [comment]
Please note that you'll need FoamFix 0.10.10 (which I have just released) - it both fixes the issue found once and for all, and no longer disables smallPropertyStorage on JEIDs/NEIDs detection (which turned out to be a red herring).

**Comment by NillerMedDild** [comment]
Errr... I can't find FoamFix on CurseForge anymore...?

**Comment by NillerMedDild** [comment]
And today FoamFix was back, huh. I released version 1.73 alpha with FoamFix 0.10.10 in it, so fingers crossed!

**Comment by asiekierka** [comment]
> Errr... I can't find FoamFix on CurseForge anymore...?

>Your project, FoamFix for Minecraft (https://www.curseforge.com/minecraft/mc-mods/foamfix-for-minecraft), requires changes before it can be approved:
>
>The name of your project contains words or phrases that are not allowed:
>- Game name: Minecraft.
