### ISSUE TITLE
Cannot craft Slimey Generator

### ISSUE THREAD

**Issue by md5i** [NillerMedDild/Enigmatica2Expert#1385]
**Modpack version**
1.70

**Issue**
The Slimey Generator seems to be uncraftable.  The recipe appears in JEI, but it will neither craft nor generate an AE2 pattern.  It is a prerequisite for the Rainbow Generator, which is itself a prerequisite for the Creative Power Cell.

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
Something went wrong with the oredict ingredient in the middle, which is a block of slime - I've re-made the recipe so it should work in the next update :)

**Comment by md5i** [comment]
I can verify that this is fixed in 1.71.

**Comment by NillerMedDild** [comment]
Thanks for the verification :)

**Comment by Traask1970** [comment]
1.72b I am having the same issue

**Comment by NillerMedDild** [comment]
Enigmatica 2: Expert version 1.72b @Traask1970? It works just fine for me.

**Comment by Traask1970** [comment]
Never mind. PEBCAK error - Congealed Slime Block =/= Slime Block . Thank you for checking though.
