### ISSUE TITLE
Duplication bug (Dark Armor)

### ISSUE THREAD

**Issue by OttoMaster** [NillerMedDild/Enigmatica2Expert#1386]
**Modpack version**
1.70b

**Issue**
When you shift-click a Dark steel upgrade out of dark armor, it duplicates the upgrade to fill both your inventory and the storage slots of the dark armor/tool. If you shift-click the upgrades in the storage, the original disappears in the upgrade slot. Because of this I now have 59 Dark Steel Upgrade "Jump."

I am playing single-player and I have added a couple mods, but they should not have caused this.

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by OttoMaster** [comment]
This also occurs in version 1.71.

**Comment by NillerMedDild** [comment]
https://github.com/SleepyTrousers/EnderIO/issues/5262

**Comment by Oray65** [comment]
puting on the black steel armor from the hotbar duplicates evrything from upgrades and inventory

**Comment by Frikkle** [comment]
@NillerMedDild the referenced issue has been closed by the EnderIO dev, not sure if they fixed it though. A bit unclear on that.
