### ISSUE TITLE
Actually Additions Farmer not planting on Fertile Soil. 

### ISSUE THREAD

**Issue by SwivelDiscourse** [NillerMedDild/Enigmatica2Expert#1387]
**Modpack version**
Enigmatica 2: Expert 1.70c

**Issue**
Actually Additions Farmer doesn’t recognize Fertile Soil as plantable soil. Quickest Resolution seems to be a CT Script iBlockStateMatcher to have Fertile Soil and Tilled Fertile Soil’s Blockstate be the same as Vanilla Dirt.

**Comment by PizzaAddict** [comment]
+fertilized dirt from Random things. the farmer sows seed only if the dirt is hoed.

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
If you know how to do this you're very welcome to submit a PR, or explain it :)

I was unable to find anything that could do this in the docs, but I could be wrong.

https://docs.blamejared.com/1.12/en/#Vanilla/Blocks/IBlockStateMatcher/#iblockstatematcher
