### ISSUE TITLE
Wireless crafting terminal search bar clears when typing "b"

### ISSUE THREAD

**Issue by amurphy4** [NillerMedDild/Enigmatica2Expert#1388]
**Modpack version**
1.69

**Issue**
The search bar in the wireless crafting terminal (from Wireless Crafting Terminal 2) clears whenever you type "b". E.g. if you try to search for "marble" the search clears when you press "b"

<img width="2048" alt="Screenshot 2019-10-25 at 12 11 30" src="https://user-images.githubusercontent.com/5718668/67566868-aaea3280-f720-11e9-8985-de86b88f50cd.png">
<img width="2048" alt="Screenshot 2019-10-25 at 12 11 37" src="https://user-images.githubusercontent.com/5718668/67566869-aaea3280-f720-11e9-9a77-7662391a3e28.png">

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.
