### ISSUE TITLE
Random crashes when opening vanilla chests

### ISSUE THREAD

**Issue by omerpamir** [NillerMedDild/Enigmatica2Expert#1389]
**Modpack version**
1.70b

**Issue**
I got a room full of double vanilla chests like 7 8 of them. When I try search some stuff in them with JEI's search function one random chest crashes the game when opening it.Like every 5 hours it crashes 1 or 2 times. And i don't know it doesn't look like a crash log but MultiMC gave me this log.

**Logs**
https://pastebin.com/GrRSSGrr

**Comment by NillerMedDild** [comment]
Looks like a Java crash, I suggest you try to update both Java and your graphics drivers :) it looks like Immersive Engineering is causing it though.
