### ISSUE TITLE
Vanilla recipes in Version 1.31 instead of the modified recipies

### ISSUE THREAD

**Issue by Cnights** [NillerMedDild/Enigmatica2Expert#139]
#### Issue Description

So far what Ive seen is the chest, furnace and coke brick recipe are the vanilla recipes instead of the modified recipes. Both vanilla and modified recipes show up in JEI and only the vanilla recipe works. Intentional?

**Comment by ByteTemplar** [comment]
I dont have this problem at all, no Vanilla recipes show up in JEI on those items and dont work either.
I think you might have something messed up in scripts or something...

**Comment by NillerMedDild** [comment]
I suggest reinstalling the instance :)
