### ISSUE TITLE
Draconic Armour wont craft 

### ISSUE THREAD

**Issue by Aberim** [NillerMedDild/Enigmatica2Expert#1391]
**Modpack version**
Version: 1.70c

Minecraft Version: 1.12.2

(modded) forge-14.23.5.2847

**Issue**Components for Draconic armour sit on pedestals with particle effects but craft does not complete.

**Logs**
no logs as yet

**Comment by NillerMedDild** [comment]
A screenshot would be nice :)

How much RF/t are you feeding it?

**Comment by Aberim** [comment]
Feeding it a million a tick through Flux point - pulling from a thee trillion RF source

![2019-10-26_11 37 06](https://user-images.githubusercontent.com/57019862/67618302-73918980-f7e5-11e9-9bf2-d83e3f84d8fe.png)
![2019-10-26_11 37 35](https://user-images.githubusercontent.com/57019862/67618303-73918980-f7e5-11e9-8fb4-0346bc3f3eb8.png)
![2019-10-26_11 36 44](https://user-images.githubusercontent.com/57019862/67618304-73918980-f7e5-11e9-8149-ea0fedcbef24.png)

Progress arrow seems to stop half way then all progress will vanish.

**Comment by NillerMedDild** [comment]
Could you try supplying power with something other than a Flux Plug please?

**Comment by Aberim** [comment]
Tired with Ender Energy conduit and Ultimate Universal Cable - still wont complete.

**Comment by Aberim** [comment]
Additionally cheated in and direct connected a creative power cell - watched it draw over 10,000,000,000 RF.

![2019-10-26_12 54 03](https://user-images.githubusercontent.com/57019862/67619149-f4ee1980-f7ef-11e9-84e8-6cb875a71335.png)

Also rebooted server several times.

**Comment by NillerMedDild** [comment]
Have you tried any other recipes? :)

**Comment by Aberim** [comment]
Yes - crafter still seems to be making all other recipes - just having issues with the draconic armour set

**Comment by NillerMedDild** [comment]
Alright then, thanks for all the info, I'll see what I can do.

**Comment by NillerMedDild** [comment]
I have a feeling downgrading Extended Crafting will do the trick here, would you mind verifying once I've uploaded the update? :)

**Comment by Aberim** [comment]
Sure thing! :)

**Comment by NillerMedDild** [comment]
1.71 incoming! :D

**Comment by Aberim** [comment]
Fixed! Good Job - love this pack  - me and my wife have been playing it coop for months after Direwolf20's play through - coming to the end now though - Chaos dragon here we come!

**Comment by NillerMedDild** [comment]
Thanks - Good luck you two :D
