### ISSUE TITLE
e2e server startup crash - fluid level emitter maybe

### ISSUE THREAD

**Issue by narken** [NillerMedDild/Enigmatica2Expert#1393]
**Modpack version**
e2e 1.70b

**Issue**
Crash on server start. Might be after I played around a bit with fluid level emitters. 

**Logs**
https://pastebin.com/Uw71fQR3

**Comment by NillerMedDild** [comment]
That is indeed an ExtraCells issue - You will need to remove the Fluid Level Emitter through MCEdit. I'm afraid there's nothing we can do to fix it :/ I thought I had removed the recipe for that block though.

**Comment by narken** [comment]
No worries, will try to remove with MCedit and tell my players not to use them
