### ISSUE TITLE
Extra Cells Drive issue (Downgrade ExtraCells)

### ISSUE THREAD

**Issue by NillerMedDild** [NillerMedDild/Enigmatica2Expert#1394]
Everything is still broken in EC2, more recipes should be removed. Every block, basicly.

**Comment by Ieldra2** [comment]
I can't confirm that. I use EC2 extensively, and I would hate to see it removed. Really.

**Comment by NillerMedDild** [comment]
Oh, that's surprising to say the least :P I've been getting so many reports I just assumed everyone had issues with EC2.

**Comment by Ieldra2** [comment]
I've only had issues with gas terminals, and occasionally, the auto-filler lost its connection and had to be broken and re-placed. Everything else has been working perfectly.

**Comment by KirtKlikas** [comment]
EC2 everything has been working flawlessly for our multiplayer server till we updated from 170c to 172. I have been using nearly everything in that mod.

**Comment by NillerMedDild** [comment]
1.72 broke EC2 for you? What exactly broke?

**Comment by KirtKlikas** [comment]
We just updated to 172b and I am noticing all of the users Gas and Fluid drives are zeroed out for fluid types and data. With multiple systems tied to it that should be auto feeding, none of the drives are filling up with anything.  This just happened today, so it seems all of our fluids are completely missing.  Pretty sure we all were using EC2 storage drives and various other additions.  I know mine should have water in the system feeding with a level emitter set to stop at 400 buckets.  If we cant find a quick fix, we will likely roll back to 170c to pull out important fluids (Primal Mana, liquid DNA, Rocket Fuel/Lubricant) before trying again. I have not investigated other EC2 impacts just yet.

**Comment by NillerMedDild** [comment]
Oh damn, that's one hell of a bug - Did it happen right after you updated to 1.72 or after a while?

**Comment by KirtKlikas** [comment]
immediately after updating, nothing EC2 worked (interfaces, drives).  We are back on 170c and all is working again, unfortunately we were updating because a user is running into the draconic armor unable to craft bug. that was fixed in 172.

**Comment by NillerMedDild** [comment]
I will make sure to downgrade the Extra Cells version for 1.73 - sorry about that, the EC2 changelogs only mentioned small bug fixes, so I thought it would be stable.

**Comment by KirtKlikas** [comment]
Amazing, I look forward to the next revision.

**Comment by ShadoWZYE** [comment]
So... on that cells issue. Seems like the EC2 cells over 64K storage on the fluid <Probably gas as well> are  bugged. The ME doesn't recognize them on 1.72b - ExtraCells-1.12.2-2.6.4. 
![2019-12-18_13 07 14](https://user-images.githubusercontent.com/48412812/71089324-8480ca80-2198-11ea-9d1b-c0af560522b2.png)
![2019-12-18_13 07 00](https://user-images.githubusercontent.com/48412812/71089325-8480ca80-2198-11ea-89b3-88b56248f381.png)
![2019-12-18_13 07 03](https://user-images.githubusercontent.com/48412812/71089326-8480ca80-2198-11ea-8333-f69f73760363.png)
![2019-12-18_13 07 11](https://user-images.githubusercontent.com/48412812/71089327-8480ca80-2198-11ea-80fd-eda86665adb2.png)

**Comment by ShadoWZYE** [comment]
Nothing can store on those. Using 64k Fluid cells works fine.

**Comment by Frikkle** [comment]
Thanks for providing additional feedback @ShadoWZYE

**Comment by ShadoWZYE** [comment]
Also, started using the gas cells last night, couple of issues with them.
They straight up ignore partitioning to begin with, also if say your gases
get fragmented on multiple cells, the gas terminal only shows the gas
available on the first cell encountered. Ex: cell a and b has gas X  2
buckets each, gas terminal looks for gas X finds it on the cell a and shows
2 buckets. Cell b is unavailable/invisible in the terminal.

**Comment by ShadoWZYE** [comment]
EC2 coul use some rewriting here and there, and possibly some quality of
life improvements, such as acceleration cards compatibility for the fluid
auto filler, the thing is great, slow as hell, but useful, and since it's
already an AE2 compatible block, AC would make sens.

**Comment by NillerMedDild** [comment]
@KirtKlikas I'm afraid I was unable to downgrade Extra Cells, as it gave me a startup crash. If you move all your fluids out of 64K+ Fluid drives and into smaller ones, you should be able to upgrade without issues.
