### ISSUE TITLE
Black Quartz Duplication

### ISSUE THREAD

**Issue by Metalit** [NillerMedDild/Enigmatica2Expert#1395]
Version:
1.7.1

Issue:
The black quartz pillar block takes 2 quartz to make but can be converted into 4.

**Comment by NillerMedDild** [comment]
We've fixed this issue before, are you certain it still exists in 1.71?

**Comment by Metalit** [comment]
I just updated, and the recipes are still there.

**Comment by NillerMedDild** [comment]
You didn't change any scripts or configs right?

**Comment by Metalit** [comment]
I had changed some configs before updating, but they were reset (to the modpack settings, not default) and I think the scripts would be too. I also am almost certain I have never edited the scripts anyway.

**Comment by NillerMedDild** [comment]
That's odd, cause I double checked the scripts and they seem correct. Could you get me a screenshot of the pillar recipe, and conversion back to quartz please?

**Comment by Metalit** [comment]
Well, if it's only a problem for me somehow, it's not exactly gamebreaking. But if you would like to look into it further, here are the screenshots:
https://user-images.githubusercontent.com/48568911/67727752-96c06280-f9b8-11e9-8b26-8fd287553cc5.png
https://user-images.githubusercontent.com/48568911/67727755-9b851680-f9b8-11e9-965b-d7d7a6020100.png

**Comment by NillerMedDild** [comment]
Do you get any errors in the chat when logging in? Did you disable AE2 channels?

**Comment by Metalit** [comment]
No, no errors or disabled channels. I've tried to figure out what's different, but I only reported it in the first place because I thought it was a general bug. As it appears to be specific to my game only, I don't think it's really worth the time to investigate, honestly. Thanks.

**Comment by NillerMedDild** [comment]
Alright :)
