### ISSUE TITLE
Destruction Gadget Bug

### ISSUE THREAD

**Issue by Metalit** [NillerMedDild/Enigmatica2Expert#1396]
Version:
1.71

Issue:
The destruction gadget can delete the blocks of compact machines that are supposed to be unbreakable.

**Comment by Metalit** [comment]
Nevermind, forgot to check if it was in the latest version. Must've been fixed outside the changelog.

**Comment by NillerMedDild** [comment]
Most in-mod bugs don't make it into our changelogs, thanks for double checking the bug.
