### ISSUE TITLE
Ae2 bug

### ISSUE THREAD

**Issue by bloodulitmate** [NillerMedDild/Enigmatica2Expert#1397]
1.69 ae2 cables and auto crafting breaks off

**Comment by NillerMedDild** [comment]
Breaks off? What do you mean?

**Comment by bloodulitmate** [comment]
the cables connected to auto crafting co processers break and disapper and i have to keep putting cables back on

**Comment by md5i** [comment]
This bug report is so sparse as to be mostly useless.  Could it be referencing the following?  I have some compact machines that are very close to AE2 wiring.  When I exit the machines, sometimes I get a loud AE2 breaking cable sound, and sometimes cables are visibly missing.  But everything works and they are still there.  Changing dimensions fixes the graphical glitches.  This problem has exited for many versions, but appears to be harmless.

**Comment by bloodulitmate** [comment]
No it has to do with when using the wireless crafting it will break random
cables off and then destroy the co processors and 64k crafting units

**Comment by NillerMedDild** [comment]
Are the blocks actually destroyed, or do they reappear if you log out and reenter? Is the entire AE network chunkloaded?

Please provide your latest.log from one of these incidents.

**Comment by SeseMueller** [comment]
This sounds like something I know from my own worlds. It looks like the cables/p2p tunnels are breaking and the client even plays the sound. This happens, when entering a world or teleporting to the network while the game lags. But, if your setup is not too difficult, or you unload the chunks and reload them slowly, the bug won't happen. Additionally, it's just client-sided and doesn't change how the ME-System works.
Is this want you described, @bloodulitmate ?
If so, no fix would be needed, as it doesn't really effect gameplay.
