### ISSUE TITLE
New world-gen.json (linked)

### ISSUE THREAD

**Issue by bryanbecker** [NillerMedDild/Enigmatica2Expert#14]
The old world-gen.json left out most of the nether ores.

I made a new one combining Dims 0 and -1

https://pastebin.com/waBNXMEp

**Comment by bryanbecker** [comment]
https://pastebin.com/iSGFc2fq

Here's one with overworld, nether, end, deep dark, and twilight profiled at 1000 chunks each

**Comment by NillerMedDild** [comment]
Thanks! I'll replace the current one with yours :)
