### ISSUE TITLE
Latest Chisel and CTM cause glass to be rendered as black when using Sphax(bdcraft) Resource Pack

### ISSUE THREAD

**Issue by urikkiru** [NillerMedDild/Enigmatica2Expert#1400]
Modpack version
1.70c

Issue
When using a resource pack(specifically tested with Sphax 64x textures), Chisel'd glass textures render as black, and do not use connected textures at all.

Enigmatica 2 Expert v1.70c includes "Chisel-MC1.12.2-1.0.0.42.jar" and "CTM-MC1.12.2-1.0.0.29.jar". Apparently these versions included some non-trivial changes that broke compatibility with existing resource packs.

Reverting to "Chisel-MC1.12.2-0.2.1.35.jar" and "CTM-MC1.12.2-0.3.3.22.jar" fixes this issue.

**Comment by NillerMedDild** [comment]
Thank you for the report. I will investigate if I get time to do so, but resource pack compatibility is not a priority for me tbh. Have you reported it to the creators of Sphax?

**Comment by urikkiru** [comment]
Sphax(bdcraft textures) for modding are supported by the community, so it'd be waiting for someone there to figure out exactly how the changes to Chisel broke compat with existing resource packs. Something similar happened with JEI a while back, and it turned out that resource pack textures had to be re-worked to support the latest JEI changes.

This can be a long wait, and we're at the end of the 1.12 mod cycle. It's possible this will never be fixed. I was thinking you could instead revert Chisel/CTM to the previously highly stable versions, and wait out using updated versions until the 1.14+ cycle of mods.

It's just a thought. I've reverted to the previously highly stable versions of Chisel/CTM myself, it's just an annoyance for anyone who picks up the pack and wonders why resource packs aren't working in odd ways.

**Comment by urikkiru** [comment]
Looks like I  spoke too soon, this has been fixed already specifically for Chisel bdcraft(sphax) textures. Never mind.
