### ISSUE TITLE
Halloween Event Crash?

### ISSUE THREAD

**Issue by TheFeuerzeug** [NillerMedDild/Enigmatica2Expert#1402]
**Modpack version**
1.69

**Issue**
Instantly crashes after opening a Wireless crafting terminal, caused by the wither skeleton in the UI with the "Happy Halloween" writing underneath it, the crash log supports this too
Edit: I temporarily solved this by setting my laptops date to 10.30.2019 instead of 10.31.2019
**Logs**
https://pastebin.com/DymKzDZb

**Comment by md5i** [comment]
Confirmed here as well in 1.70:

```
java.lang.ClassCastException: net.minecraft.entity.monster.EntityWitherSkeleton cannot be cast to net.minecraft.entity.player.EntityPlayer
	at p455w0rd.wct.client.gui.GuiWCT.func_146273_a(GuiWCT.java:289)
```

**Comment by NillerMedDild** [comment]
Thanks for the help md5i! Changing your PC date should resolve this issue :)
