### ISSUE TITLE
Airtight Seal still uncraftable

### ISSUE THREAD

**Issue by yazzledore** [NillerMedDild/Enigmatica2Expert#1403]
**Modpack version**
1.71

**Issue**
Same as "Airtight Seal is uncraftable #1353" basically, but now it gives Magnetic instead of Autosmelt.  Don't trust myself to mess with script files so I haven't tried to adjust it like the previous poster.  Sorry if this is in fact the same issue (I assume the 1.71a in the previous post means alpha and it's been changed since then?).  Thank you for the hard work on this pack; it's amazing!

**Logs**
N/A

**Comment by NillerMedDild** [comment]
Dammit, I need a better way to make enchanted book data. Thanks for the report, and you are most welcome :)

**Comment by Keilay** [comment]
Yeah i tried to get this book all night as well. (Not sure how it work with the Chemical reactor)
Note : i installed a setup with enchanting factory which didnt gave me any either.
Agree on the exellent modpack, best one i played so far thanks dude!

**Comment by MaxNeedsSnacks** [comment]
@NillerMedDild there *is* an enchantment bracket handler in CrT

`<enchantment:modid:name>`

maybe that could be of service?

**Comment by MaxNeedsSnacks** [comment]
Okay so in short, yes, this bracket handler will prevent us from ever having an issue like this in the future, but the problem right now is -- from what I can tell, enchantment IDs are actually mapped per world, so for existing worlds, I'm afraid this issue is probably going to remain and you're just going to have to either modify the script again or find some other way to get this enchant on your armour

**Comment by NillerMedDild** [comment]
Was the label on this supposed to be Unresolved? :)

**Comment by MaxNeedsSnacks** [comment]
Yeah, since this particular issue is sort of *Unresolved*

**Comment by NillerMedDild** [comment]
I'm fairly certain the enchantment bracket handler is able to handle per world ids, after all that is the entire point of having an enchantment bracket handler.

**Comment by MaxNeedsSnacks** [comment]
in my testing it wasn't able to unfortunately, it would  instead just craft a "Holding I" book for me

**Comment by NillerMedDild** [comment]
Oh alright :/ this is as good a fix as possible then :P
