### ISSUE TITLE
Tinkers' Construct-made crooks don't gain xp from breaking leaves

### ISSUE THREAD

**Issue by Ieldra2** [NillerMedDild/Enigmatica2Expert#1404]
Pack version: 1.70c

As the title says, the crooks I make with TiC don't gain xp from using them for their main purpose, which is breaking leaves. In case it's materials-dependent, my variant used cobalt as material for the head rod, livingwood, paper and osmium for the other 3 rods, and I put 4 reinforced modifiers on it before starting to use it.

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
Looks like the Crooks were removed from Tinkers' Complement.
