### ISSUE TITLE
Twitch can't update modpack

### ISSUE THREAD

**Issue by Rob251** [NillerMedDild/Enigmatica2Expert#1405]
**Modpack version**
1.70b

**Issue**
I tried to update the game for a while now first to 1.70C now to 1.71 and it fails it said the files are being used by another application please exit etc, now I tried to update this after a full PC restart, after PC has been left off for a day and after i exit trumpetear or eartrumpet or what i saw online people say exited steam, did all the exiting i could when it comes to apps, still can't update, but i can update other modpacks.

**Logs**
N/A
![Capture](https://user-images.githubusercontent.com/57270573/68053562-24b38a80-fce4-11e9-92ed-bdb06c515eef.PNG)

PS: Did alot of troubleshooting and searching on google for the past week if not more.

**Comment by OttoMaster** [comment]
I had the same problem. I ended up having to install a new instance and transfer my save and journeymap folders.

**Comment by NillerMedDild** [comment]
That is indeed the way to fix it.

**Comment by bk-one** [comment]
Not to reopen, but to leave a remark. The modpack is installed with a "read-only" flag on the folder. If you go to the modpack folder, right-click, select properties and uncheck the "Read-only" flag, you can upgrade your modpack again. Not sure if that's Twitch or how the files are being distributed - anyway, with this method you don't need to copy your safes around. But you do need to do it after each update.
The "read-only" flag is responsible for the "files are in use" message that you posted.

**Comment by NillerMedDild** [comment]
Twitch is responsible for that, but very nice to know, thanks.
