### ISSUE TITLE
NuclearCraft Ingot Former has a very limited set of recipes. 

### ISSUE THREAD

**Issue by SwivelDiscourse** [NillerMedDild/Enigmatica2Expert#1408]
**Modpack Version**
1.71

**Issue**
The Ingot Former has a very limited set of alloys and metals that it can make, compared to the Tinker's Smeltery and casting system. 
 I believe Ingot Former and Smelter recipes share a similar recipe format, and they both have CT Support, so exporting a list from one to the other doesn't seem too difficult a fix, though I may be mistaken.

**Comment by NillerMedDild** [comment]
It'd be nice if exporting recipes from one machine to another was a thing, but sadly this has to be done manually, as everything else :P I probably won't get around to do this tbh, if anyone wants to make a pull request I'll happily merge it.

**Comment by MaxNeedsSnacks** [comment]
this *might* be doable using kubejs scripts actually, since you can work with java types directly there and tinkers SHOULD have a registry of casting recipes

at least, that’s what i hope

**Comment by NillerMedDild** [comment]
Adding KubeJS for that one thing would be a bit overkill though xD

**Comment by MaxNeedsSnacks** [comment]
it's quite lightweight actually ^^
i get what you mean though, although it does open up more possibilities for more recipe adapters like this in the future

**Comment by NillerMedDild** [comment]
Maybe for 1.14 :D

**Comment by MaxNeedsSnacks** [comment]
side note: i tried doing this anyway just for fun and it turns out it's not doable after all, anyways, or at least not easily, due to just how late tinkers' actually registers smelting recipes

**Comment by NillerMedDild** [comment]
Ah alright :/

**Comment by pjc21** [comment]
This is what I found missing from the NC Ingot Former that the Tinkers Smeltery has, I only increased the multiplier for the Demon Metal Ingot as it seems to be the only one that needs a lot more heat to melt in tinkers compared to the others.

```
# Add missing ingots/bricks to ingot former
	//Brick
	mods.nuclearcraft.ingot_former.addRecipe([<liquid:clay>*144, <minecraft:brick>, 1.0, 1.0]);
	//Starmetal Ingot
	mods.nuclearcraft.ingot_former.addRecipe([<liquid:astral_starmetal>*144, <astralsorcery:itemcraftingcomponent:1>, 1.0, 1.0]);
	//Demon Metal Ingot
	mods.nuclearcraft.ingot_former.addRecipe([<liquid:xu_demonic_metal>*144, <extrautils2:ingredients:11>, 2.0, 2.0]);
	//Enchanted Ingot
	mods.nuclearcraft.ingot_former.addRecipe([<liquid:xu_enchanted_metal>*144, <extrautils2:ingredients:12>, 1.0, 1.0]);
	//Evil Infushed Iron Ingot
	mods.nuclearcraft.ingot_former.addRecipe([<liquid:xu_evil_metal>*144, <extrautils2:ingredients:17>, 1.0, 1.0]);
	//Fire Dragonsteel Ingot
	mods.nuclearcraft.ingot_former.addRecipe([<liquid:dragonsteel_fire>*144, <iceandfire:dragonsteel_fire_ingot>, 1.0, 1.0]);
	//Ice Dragonsteel Ingot
	mods.nuclearcraft.ingot_former.addRecipe([<liquid:dragonsteel_ice>*144, <iceandfire:dragonsteel_ice_ingot>, 1.0, 1.0]);
	//Pink Slime Ingot
	mods.nuclearcraft.ingot_former.addRecipe([<liquid:molten_reinforced_pink_slime>*144, <industrialforegoing:pink_slime_ingot>, 1.0, 1.0]);
	//Refined Obsidian Ingot
	mods.nuclearcraft.ingot_former.addRecipe([<liquid:refinedobsidian>*144, <mekanism:ingot>, 1.0, 1.0]);
	//Refined Glowstone Ingot
	mods.nuclearcraft.ingot_former.addRecipe([<liquid:refinedglowstone>*144, <mekanism:ingot:3>, 1.0, 1.0]);
	//Base Essence Ingot
	mods.nuclearcraft.ingot_former.addRecipe([<liquid:base_essence>*144, <mysticalagriculture:crafting:32>, 1.0, 1.0]);
	//Psimetal Ingot
	mods.nuclearcraft.ingot_former.addRecipe([<liquid:psimetal>*144, <psi:material:1>, 1.0, 1.0]);
	//Fiery Ingot
	mods.nuclearcraft.ingot_former.addRecipe([<liquid:fierymetal>*144, <twilightforest:fiery_ingot>, 1.0, 1.0]);
	//Seared Brick
	mods.nuclearcraft.ingot_former.addRecipe([<liquid:stone>*144, <tconstruct:materials>, 1.0, 1.0]);
	//Mud Brick
	mods.nuclearcraft.ingot_former.addRecipe([<liquid:dirt>*144, <tconstruct:materials:1>, 1.0, 1.0]);
	//Elementium Ingot
	mods.nuclearcraft.ingot_former.addRecipe([<liquid:elementium>*144, <botania:manaresource:7>, 1.0, 1.0]);
```

**Comment by MaxNeedsSnacks** [comment]
thaat looks good to me ^^

feel free to PR it and i'll test it ingame

**Comment by pjc21** [comment]
Cool, PR done - first time doing a PR, so think I've done it correctly but let me know if not.

**Comment by MaxNeedsSnacks** [comment]
nice, i'm gonna try to check it out when i can ^^
