### ISSUE TITLE
Suggestion: make Enderman heads from Enderman Essence

### ISSUE THREAD

**Issue by Ieldra2** [NillerMedDild/Enigmatica2Expert#1409]
Enderman essence can be used to make Ender Pearls. Which is nice, but there are many other ways to get those. Enderman heads, however, are only available by running a mob farm. It would be nice if there was a way to get them that didn't involve a mob farm. I propose a custom recipe to craft EnderIO's Enderman heads from Mystical Agriculture's Enderman Essence.

**Comment by NillerMedDild** [comment]
The thing is though, I want the player to make a mobfarm. Why would you prefer too avoid that? :)

**Comment by MaxNeedsSnacks** [comment]
TPS issues are definitely a good reason why you'd want players to avoid mob farms, but I guess for that case we could just add soft support for Woot or DML or something like that

**Comment by Ieldra2** [comment]
You need a mob farm anyway, but I'd rather dispense with it eventually. It can be late in the game, but I prefer to get there. It's a matter of style.

**Comment by NillerMedDild** [comment]
Crop farms are laggy too, and I don't really see a matter of style as valid reason to change a large feature.
