### ISSUE TITLE
Enderstorage causing crash

### ISSUE THREAD

**Issue by dopefull1** [NillerMedDild/Enigmatica2Expert#1410]
**Modpack version**
1.71
**Issue**
My world crashes now whenever I try to load it. I don't know if this helps, but at the moment in that world I'm using the Enderpouch to store my tools and a pair of Enderchests to transport gravel, soulsand, dust etc. out of a compact machine into my sieves.
EDIT: I realise in the crashreport that it says to delete the enderstorage folder (which fixes the crash), but I'm still curious if I did something wrong in which case I'd like to know so I can avoid it.

**Logs**
https://pastebin.com/fWwpidSk

**Comment by NillerMedDild** [comment]
Thanks for the report.

excerpt from the crash-report:
```
EnderStorage was unable to read it's data, please delete the 'EnderStorage' folder Here: C:\Users\dope\Documents\MultiMC\instances\Enigmatica2Expert-1.71\minecraft\saves\Enigmatica 2 Expert\EnderStorage and start the server again.
```
