### ISSUE TITLE
Lens in Astral Sorcery crash.

### ISSUE THREAD

**Issue by SANagisa** [NillerMedDild/Enigmatica2Expert#1412]
**Modpack version**
Enigmatica2Expert-1.71

**Issue**
Put Lens(Astral Sorcery) and link it with other block will crash the server.

**Logs** 
Input pastebin link to crash-report or latest log, if applicable
[log.txt](https://github.com/NillerMedDild/Enigmatica2Expert/files/3828363/log.txt)
[crash-2019-11-10_19.14.55-server.txt](https://github.com/NillerMedDild/Enigmatica2Expert/files/3828362/crash-2019-11-10_19.14.55-server.txt)

**Comment by NillerMedDild** [comment]
Thank you for the report.
* Did you craft the Lens normally? 
* Which block did you link it to? 
* Does it happen no matter which block you link it to?

**Comment by SANagisa** [comment]
> * Did you craft the Lens normally?
Yes
> * Which block did you link it to?
An iron block
> * Does it happen no matter which block you link it to?
Yes after crash, I try to connect it to a grass block, but it still crashed

**Comment by NillerMedDild** [comment]
Can you reproduce the issue with a different lens?
