### ISSUE TITLE
AE2 fluid formation planes do not work

### ISSUE THREAD

**Issue by Ieldra2** [NillerMedDild/Enigmatica2Expert#1413]
Modpack version 1.70c

The issue is simply that I could't get the fluid formation plane to output fluid stored in the ME network under any circumstances I tried. It simply sits there and does nothing. Meanwhile, fluid export buses work in all the same circumstances, as do fluid interfaces. In regular circumstances, these combined with other mods' fluid placers serve as a workaround, but those didn't apply when I tried the formation plane, and found it didn't work at all.

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
It works just fine for me in 1.73 :)
