### ISSUE TITLE
Auto-crafting flux core yields 2 cores, not 4

### ISSUE THREAD

**Issue by PizzaAddict** [NillerMedDild/Enigmatica2Expert#1414]
**Modpack version**
1.70c

**Issue**
setup: make a recipe: {crafts "48 flux core" from "64 obsidian" and "64 flux"}
then build a  XNET auto crafting system: the system always holds 64 flux cores, and submit to The ME network cores if it exceeds 64.

by whichever block the flux core crafted, this bug happens: TE sequantial fabricator, AE2 molcular assembler, RFtools Crafter, Mekanism Crafter.... 

behavier:
The Crafter Craftes flux cores normally(makes 4. 1 stays in buffer, 3 go as output.) then send them to a buffer. the Xnet Checks if the buffer's current store exceeds 64. 

The magic happens here. 2 of 4 crafted cores are...just 'disappear.', resulting only 16 core, not  48 cores.
the 
**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by NillerMedDild** [comment]
I probably won't have time to look into this to be honest, but thank you for the report.
