### ISSUE TITLE
Crash on server when using Nature's Compas

### ISSUE THREAD

**Issue by Attakajakka** [NillerMedDild/Enigmatica2Expert#1416]
**Modpack version**
1.72

**Issue**
When using the nature's compas the server crashes and generates a crashreport has happened twice in a row now

**Logs**
https://pastebin.com/WMcEZkQd

**Comment by NillerMedDild** [comment]
It looks related to https://github.com/MattCzyr/NaturesCompass/issues/34

Could you please allocate atleast 6GB of RAM and try again? I'm kinda amazed you even got the pack started with 4GB set.

**Comment by Frikkle** [comment]
We just received another one of this on Discord; uploading the crash report in a bit.

This issue has been reported in the Nature's Compass issue tracker and is said to be solved in 1.8.5 of the mod; see https://github.com/MattCzyr/NaturesCompass/issues/58

**Comment by Frikkle** [comment]
It is a different error though, but worth trying to check.

**Comment by Frikkle** [comment]
Additionally, for Fandrule, the client crashed. I'll check if there is more known on this.

**Comment by NillerMedDild** [comment]
This was fixed a long time ago, Fandrule was on version 1.72b :)

**Comment by Frikkle** [comment]
Ugh, sorry 'bout that :)

**Comment by NillerMedDild** [comment]
Better safe than sorry :D
