### ISSUE TITLE
AS Crystal CT method now working to accept any AS crystal

### ISSUE THREAD

**Issue by pjc21** [NillerMedDild/Enigmatica2Expert#1417]
**Modpack version**
1.71

**Feature Request**
In relation to issue #1267 - have only tested with prosperity block but it now accepts crystalAstralAny

```
# Block of Prosperity
	val myCrystal = Utils.getCrystalORIngredient(false, false);
	recipes.addShapedMirrored("Block of Prosperity", 
	<mysticalagriculture:storage:5> * 2, 
	[[<minecraft:emerald_block>, <botania:grassseeds:*>, <minecraft:quartz_block>],
	[<botania:grassseeds:*>, myCrystal, <botania:grassseeds:*>], 
	[<minecraft:gold_block>, <botania:grassseeds:*>, <minecraft:diamond_block>]]);
```

![2019-11-15_07 30 03](https://user-images.githubusercontent.com/4660190/68904882-33457b80-0793-11ea-8bde-b0adfcccc62a.png)

**Comment by NillerMedDild** [comment]
To be perfectly honest I'd rather not modify this again, as I'm afraid the recipes would break at some point.

**Comment by pjc21** [comment]
Yeah good point, and you can just get rock crystal essence going for a supply of simple rock crystal anyway.

**Comment by NillerMedDild** [comment]
But thanks anyway :)
