### ISSUE TITLE
JEI + Advanced Generators Crash

### ISSUE THREAD

**Issue by eccentricayman** [NillerMedDild/Enigmatica2Expert#1418]
**Modpack version**
1.69

**Issue**
Every time I inventory is opened, it crashes - seems to be something related to JEI and Advanced Generators Turbine Controller.

**Logs**
https://paste.dimdev.org/ecoyisidiz.mccrash

**Comment by NillerMedDild** [comment]
Please remove Optifine, that is most likely the cause. If it isn't the cause, feel free to comment here and we'll look into the issue.
