### ISSUE TITLE
Draconium Armour requires too much RF to craft

### ISSUE THREAD

**Issue by Trasheater** [NillerMedDild/Enigmatica2Expert#1420]
**Modpack version**
1.71

**Issue**
Hi, I posted this issue on the discord but it got no response. When I try to craft the draconic set using the crafting core, it says it requires 10 billion RF, which it does say in the Armor.zs file, but even with more than enough power, the progress bar will reset and stop crafting midway through

Videos online show it as requiring around 1.4 billion RF due to some integer overflow? Not sure

**Logs**
none

**Comment by NillerMedDild** [comment]
This issue was fixed very recently, please try updating.

**Comment by Trasheater** [comment]
I have reinstalled both 1.71 and 1.72, they both have armour with RF of 1.4 billion, is this intentional?

**Comment by NillerMedDild** [comment]
No that is not intentionally, but probably just a visual bug. Does it craft?

**Comment by pjc21** [comment]
Hey, not sure but may have spotted the issue. Just installed a fresh copy of 1.72 which installs ExtendedCrafting-1.12.2-1.5.5.jar

The [Changes max RF cost and RF/t from int to long](https://github.com/BlakeBr0/ExtendedCrafting/pull/74) was done in latest version [ExtendedCrafting-1.12.2-1.5.6.jar](https://www.curseforge.com/minecraft/mc-mods/extended-crafting/files/2777071)

**Comment by NillerMedDild** [comment]
Dammit, that's bad news. The new version causes issues with recipes as well, that's why I downgraded. Have you found other recipes that you can't craft?

**Comment by Trasheater** [comment]
That one works fine for me, i would think that any recipe that needs more than 2^31-1 RF would either not craft or craft with an incorrect RF value, but on 1.72 I was able to craft the armour (using 1.4 billion RF)

**Comment by NillerMedDild** [comment]
Thanks for the help! :D
