### ISSUE TITLE
Wrong Block of Steel when building Advanced Thermionic Fabricator

### ISSUE THREAD

**Issue by bk-one** [NillerMedDild/Enigmatica2Expert#1422]
**Modpack version**
1.72

**Issue**
When building the "Advanced Thermionic Fabricator", the blueprint requires 8 Steel Block. It needs #8991/8 Steel (Immersive Engineering), but default Block of Steel is #4672/0 (Thermal Foundation). 

**Workaround**
You can chisel from 4672/0 to 8991/8, so technically it's just an annoyance, but the recipe should use #4672/0.

**Comment by NillerMedDild** [comment]
That is on purpose, for the sake of aesthetics :)

**Comment by bk-one** [comment]
fair enough, I assume anyone that reaches the "Advanced Thermionic Fabricator" also knows how to chisel from one to another.. :)

**Comment by NillerMedDild** [comment]
I sure hope so :D
