### ISSUE TITLE
Changed behaviour for Manufactory/Silicon Ingot

### ISSUE THREAD

**Issue by bk-one** [NillerMedDild/Enigmatica2Expert#1423]
**Modpack version**
1.72

**Issue**
Previous to 1.72, the Manufactory (NuclearCraft) produced Silicon (#7503/5) from Silicon Ingots (#6829/3). Now it produces Silicon Dust (#6828/3). Oddly enough, there are two recipes in the Manufactory for Silicon Ingot (#6828/3) as seen on the screenshot. One is producing Silicon Dust, one is producing Silicon. Maybe the two recipes where in it prior to 1.72, but the default behavior changed (at least for me), breaking my automation - but I ended up with a lot of Silicon Dust, so won't complain.. free dust, yay!

**Workaround**
Change automation to use e.g., Nether Quartz Dust to produce Silicon. 

**Remark**
I assume the current behavior does also make sense, not sure if this should be fixed - but I thought at least I create a remark if someone stumble upon it. The recipe for Silicon Ingot to Silicon should be removed at least.

![2019-11-19_15 17 21](https://user-images.githubusercontent.com/37401/69125171-2c46a200-0ae0-11ea-81c9-3425a6763a46.png)

**Comment by NillerMedDild** [comment]
Thanks for the report! Would you mind checking if the other ways to obtain silicon appear normal/functional?

**Comment by bk-one** [comment]
So some more details:

- all other recipes to create Silicon via standard smelting are fine
- but there is a recipe to create Silicon from Crushed Quartz (actuallyadditions), but you removed the recipes for that, so you can't obtain them ([source](https://github.com/NillerMedDild/Enigmatica2Expert/blob/master/scripts/ActuallyAdditions.zs#L116)) - so it would make sense to remove the Crushed Quartz -> Silicon recipes as well
- Silicon Ingot also appears to behave the way it's intended.. 

hope that helps.

-

**Comment by NillerMedDild** [comment]
That helps a great deal, thank you.
I'm fine with silicon being obtainable in multiple ways, I'll leave it up to the player to choose :)

**Comment by bk-one** [comment]
Not so fast :) It still does break current automation and the displayed recipe to create Silicon from Silicon Ingot to Silicon is displayed, but not viable as the Manufactory will produce the Dust. So it's still a bug imho.

**Comment by NillerMedDild** [comment]
Dammit, you're right xD
