### ISSUE TITLE
Blue Slime not accessible

### ISSUE THREAD

**Issue by bk-one** [NillerMedDild/Enigmatica2Expert#1424]
**Modpack version**
1.72

**Issue**
There's currently no way to get Blue Slime (#8362/1). Besides the fact that #1407 exits, it's also odd that Blue Slime Saplings in the Sapling Infuser generate Green Slime Blocks, not blue ones. The other workaround via Compact Drawers (see https://www.reddit.com/r/feedthebeast/comments/bowu1o/enigmatica2expert_how_to_get_blue_slimes/enmixeo/?context=8&depth=9) also doesn't work anymore, so there's mo way to get Blue Slime in the game imho.

**Comment by NillerMedDild** [comment]
What about Blue Slime Trees?

**Comment by pjc21** [comment]
There's also the option of automating blue slime blocks via a mob duplicator setup and auto-crafting the blue slime balls into blocks. You just need to find a blue slime first and have a supply of mob essence for the duplicator.

**Comment by NillerMedDild** [comment]
Seeing as this issue is a side effect of no blue slimes spawning, that's not possible.

**Comment by urikkiru** [comment]
I have found a blue sapling in the world(broke slimey leaves), but when planted it produces green slime blocks. Blue slime balls can be found in the world as well, but I have not seen an automated way of producing them.

**Comment by NillerMedDild** [comment]
Blue slime drops from blue slime leaves.

**Comment by bk-one** [comment]
I never found any blue slimy leaves - and JEI doesn't show any.

**Comment by pjc21** [comment]
Yes can confirm, blue slime balls have a random chance to drop form blue slime leaves. They do seem to have a very low chance but definitely do drop.

From 5 blue slime trees vein-mined leaves using a supremium crook, I got 90 blue slime saplings, 4 green slime balls & 2 blue slime balls.

**Comment by NillerMedDild** [comment]
Thanks for confirming :)
