### ISSUE TITLE
ConcurrentModificationException in p455w0rds-Library

### ISSUE THREAD

**Issue by freundlich** [NillerMedDild/Enigmatica2Expert#1425]
**Modpack version**
1.72

The first time I logged into the game after updating to 1.72, I ran into the following issue:
https://github.com/p455w0rd/p455w0rds-Library/issues/52

This might have been a case of bad luck because logging in a second time was fine, so this probably has nothing to do with version 1.72 in particular. It might be an idea tough to disable the setting B:EnableShaders in p455w0rdsLib.cfg as mentioned in the issue.

**Comment by NillerMedDild** [comment]
Thanks, I've updated the config :)
