### ISSUE TITLE
IE village buildings have steel tools as loot

### ISSUE THREAD

**Issue by MorganSimic** [NillerMedDild/Enigmatica2Expert#1428]
**Modpack version**
1.72

**Issue**
The IE buildings in villages can contain IE steel tools of all kinds as loot in the crates. I glimpsed over the last IE changelogs but couldn't find anything when it was added but maybe i just missed it.
A quick look also didn't reveal a config option for that anywhere, so probably loot tweaker must be used to get rid of those tools.

**Comment by NillerMedDild** [comment]
Thanks for the report :D
