### ISSUE TITLE
Crash on viewing Recipe via p445sw0rds Library

### ISSUE THREAD

**Issue by SeseMueller** [NillerMedDild/Enigmatica2Expert#1429]
**Modpack version**
Newest stable via Twitch launcher: 1.72 

**Issue**
Crash on viewing a recipe while holding a Wireless Crafting Table. I have the default modpack, but added Vanillafix, so I can see crashes, etc. might be because I didn't wait the 10 minutes to let my World load. Other Information should be in the pastebin. Vanillafix says, p445sw0rds Library does it.

**Logs**
https://paste.dimdev.org/lidaficaqe.mccrash (via Vanillafix)

**Comment by NillerMedDild** [comment]
Update to 1.72a :)

**Comment by SeseMueller** [comment]
Wow, work! Good Job!
