### ISSUE TITLE
Tinkers Compliment dupe bug

### ISSUE THREAD

**Issue by Halfdeaf** [NillerMedDild/Enigmatica2Expert#1430]
https://github.com/KnightMiner/TinkersComplement/issues/56

**Comment by NillerMedDild** [comment]
Yikes, that's a bad one.

**Comment by Frikkle** [comment]
There's been a possible cause being discussed on the linked issue; I bumped the conversation.

**Comment by NillerMedDild** [comment]
I do not believe I can fix this, and the majority of modders no longer support 1.12, so I'll close this issue.

Nethertheless, thank you for reporting :)
