### ISSUE TITLE
Disconnect after updating from 1.71 to 1.72a

### ISSUE THREAD

**Issue by rbrantley7** [NillerMedDild/Enigmatica2Expert#1431]
**Modpack version**
1.72a

**Issue**
After upgrading to 1.72a I can launch a  single player game without issue, however when connecting to the server I see loading terrain and a brief flash of the pause screen with the world in the background, then it goes blank. See server side logs below. 

**Logs**
Server log:
23.11 10:36:55 [Connect] User [Username], IP [IPADDR]
23.11 10:36:55 [Server] Server thread/INFO [mcjtylib_ng]: SMP: Sync dimensions to client
23.11 10:36:55 [Server] Server thread/INFO [Username] joined the game
23.11 10:36:55 [Multicraft] [Username] ran command Message of the Day
23.11 10:36:55 [Server] Server thread/INFO [buildinggadgets]: Sending SyncedConfig to freshly logged in player [Username].
23.11 10:36:55 [Server] Server thread/INFO [Waila]: Player EntityPlayerMP['[Username]'/62531, l='_altearth_world', x=-1923.08, y=66.00, z=754.65] connected. Sending ping
23.11 10:36:55 [Server] Server thread/INFO [EnderCore]: Sending server configs to client for com.enderio.core.common.config.ConfigHandler
23.11 10:36:55 [Server] Server thread/INFO [mcjtylib_ng]: SMP: Player logged in: Sync diminfo to clients
23.11 10:36:55 [Server] Server thread/INFO [mcjtylib_ng]: Send dimlet rules to the client
23.11 10:36:55 [Server] Server thread/INFO [mcjtylib_ng]: Rules packet size: 5638 of 8192
23.11 10:36:55 [Server] Server thread/INFO [Actually Additions]: Sending Player Data to player [Username] with UUID 8283a102-8d38-4448-84cd-3d2014dc696c.
23.11 10:36:55 [Server] Server thread/INFO [Mekanism]: Sent config to '[Username].'
23.11 10:36:55 [Server] Server thread/INFO [Astral Sorcery]: [Astral Sorcery] Waiting for server synchronization on login for [Username]...
23.11 10:36:55 [Server] Server thread/INFO [Astral Sorcery]: [Astral Sorcery] Synchronizing baseline information to [Username]
23.11 10:36:55 [Disconnect] User [Username] has disconnected, reason: You have been idle for too long!
23.11 10:36:55 [Server] Server thread/INFO [Username] left the game

**Comment by NillerMedDild** [comment]
Please provide your full client and server latest.logs.

**Comment by rbrantley7** [comment]
1) Other players can log in without issue on 172a.
2) I can login with my daughter's account on my client without issue.
3) Tried backing up and deleting my playerdata information in case it was something odd with my inventory or location. The behavior still occurs.
4) I can stop the server, rename the world folder and start it up(thus allowing a new world to be generated) and it works fine.

[server-latest.log](https://github.com/NillerMedDild/Enigmatica2Expert/files/3882903/server-latest.log)
[client-latest.log](https://github.com/NillerMedDild/Enigmatica2Expert/files/3882919/client-latest.log)

**Comment by NillerMedDild** [comment]
Good work!

I'm afraid due to the nature of this bug, we most likely won't be able to find the cause. The logs don't indicate what is actually causing this behaviour, and it could be give or take all the mods.

**Comment by rbrantley7** [comment]
I agree it is very odd. What doesn’t make any sense is that my daughters account works fine with my client, however my account doesn’t work with the very same client on the very same machine. This lead me to believe that the issue was with the playerdata, however deleting the playerdata does not seem to change the behavior. Occasionally it will let me log in and move around for a moment before closing, which is how I knew the playerdata was reset(when I deleted it for my UUID) as I was at the world-spawn.

**Comment by pjc21** [comment]
Not sure if this could cause an issue like this but I believe journeymap is also player specific outside of playerdata. As you said that you can connect ok when logged in with your daughter's account on same client (I assume with the same instance in MultiMC) maybe it got corrupted somehow.
Make a backup of the journeymap folder first then delete it and give it go, worth a shot.

**Comment by NillerMedDild** [comment]
Deleting your player.data could also do the trick.

**Comment by rbrantley7** [comment]
Attempted deleting playerdata from server side from the following locations:

/_altearth_world/advancements/8283a102-8d38-4448-84cd-3d2014dc696c.json
/_altearth_world/data/ftb_lib/players/zynthviur.dat
/_altearth_world/data/ftb_lib/teams/zynthviur.dat
/_altearth_world/data/ftb_lib/teams/claimedchunks/zynthviur.dat
/_altearth_world/data/ApiaristTracker.8283a102-8d38-4448-84cd-3d2014dc696c.dat
/_altearth_world/data/ArboristTracker.8283a102-8d38-4448-84cd-3d2014dc696c.dat
/_altearth_world/data/LepidopteristTracker.8283a102-8d38-4448-84cd-3d2014dc696c.dat
/_altearth_world/data/POBox_player-zynthviur-8283a102-8d38-4448-84cd-3d2014dc696c.dat
/_altearth_world/playerdata/8283a102-8d38-4448-84cd-3d2014dc696c.astral
/_altearth_world/playerdata/8283a102-8d38-4448-84cd-3d2014dc696c.astralback
/_altearth_world/playerdata/8283a102-8d38-4448-84cd-3d2014dc696c.cosarmor
/_altearth_world/playerdata/8283a102-8d38-4448-84cd-3d2014dc696c.cyclicinvo
/_altearth_world/playerdata/8283a102-8d38-4448-84cd-3d2014dc696c.dat
/_altearth_world/stats/8283a102-8d38-4448-84cd-3d2014dc696c.json


Additionally attempted a fresh install of client with the same outcomes:

1) Daughter's account is still able to log in using the fresh install.
2) My account is able to log in and immediately gets the disconnected message from the server.

**Comment by pjc21** [comment]
If you have server/client backups and the time you could try this to see if it's due to specific mod/'s added/updated between version 1.71 - 1.72

1. Restore server and client backups.
2. Disable all mods added/updated between 1.71 & 1.72 on both server/client
   -- rename mods to disable - modname.jar.disabled
3. Start server and client
4. After staring the server, in the server console you will need to run command /fml confirm in order for the server to complete startup with previously enabled mods now disabled.
5. On the client when joining server you should get the yes/no to continue with missing entries screen, click yes. 

<details>
<summary>If ?? your able to connect OK with those mods disabled</summary>

> Then you can repeat the process but slowly reduce the list of disabled mods until you find the culprit mod/'s. 
> Maybe break the list up into groups to speed the process up.
> Some mods like libraries/dependents (ie. ValkyrieLib/Environmental Tech) will need to be done together or even just leave all mod..lib mods enabled on second repeat. 
> I would also do a fresh backup restore each time.

</details> 

<details>
<summary>Mods added/updated between 1.71 & 1.72</summary>

```
- FTB Backups
- /Dank/Null
- Actually Additions
- AE2WTLib
- Animania
- Animus
- Applied Energistics
- ArchitectureCraft
- Better Questing
- Biomes O' Plenty
- Blood Magic
- Botania
- BrokenWings
- BuildingGadgets
- Capability Adapter
- CarryOn
- Chunk Pregenerator
- Cyclic
- CyclopsCore
- DarkUtils
- EnderCore
- Environmental Materials
- Environmental Tech
- ExnihiloCreatio
- Extra Cells
- Forestry
- FTBLib
- FTBUtilities
- Immersive Engineering
- Industrial Foregoing
- JEI
- Just Enough Harvestcraft (JEHC)
- MysticalLib
- Nature's Compass
- NuclearCraft
- P455w0rdslib
- Pam's Harvestcraft
- RandomThings
- RebornCore
- Tinkers' Construct
- Twilight Forest
- ValkyrieLib
- WirelessCraftingTerminal
```

</details>

**Comment by rbrantley7** [comment]
Welp, I'm not sure I have an answer. Tried quite a few things, however this morning I backed up the server, upgraded to 1.72b, downloaded 1.72b client and all is working again it appears. No problems logging in now :)
