### ISSUE TITLE
Crashes with dank/null

### ISSUE THREAD

**Issue by PlazmaCaster** [NillerMedDild/Enigmatica2Expert#1432]
**Modpack version**
1.72a

**Issue**
When on a server (both updated and fresh install) having a dank/null with cobblestone crashes the client. I assume that the crash will occur with other items/blocks in the dank/null but have not tested it yet. Single player does not cause this crash however.

**Replication**
- Start a new world or a pre-existing one on a server
- Spawn/create dank/null
- Add cobblestone to the dank/null inventory by opening GUI

**Logs**
(updated from 1.72 to 1.72a)
https://pastebin.com/JfzCfGrY
https://pastebin.com/7d7FFgUb

(fresh install)
https://pastebin.com/fxSbLHz3
https://pastebin.com/MiwyrAEd

Edit: adding latest server log
[2019-11-24-2.log](https://github.com/NillerMedDild/Enigmatica2Expert/files/3883819/2019-11-24-2.log)

**Comment by NillerMedDild** [comment]
Thanks for the detailed report! :) I'm uploading a hotfix as we speak, would you mind testing that out?

**Comment by PlazmaCaster** [comment]
Yeah I'd be willing to. what do I have to do?

**Comment by PlazmaCaster** [comment]
Seems the hotfix worked, no issues. Thanks for the patch. :)

**Comment by NillerMedDild** [comment]
Sure, thanks for the help :D
