### ISSUE TITLE
I&F ash block to coal coke recipe conflict 

### ISSUE THREAD

**Issue by MorganSimic** [NillerMedDild/Enigmatica2Expert#1434]
**Modpack version**
1.72

Ash blocks from I&F have a custom made recipe into coal coke blocks that is now conflicting with the newly added dust to charcoal recipe from I&F
**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by NillerMedDild** [comment]
I'll get that fixed, ty :)
