### ISSUE TITLE
Unbreakable TC Sword broken by Cyclic Automated User

### ISSUE THREAD

**Issue by dnulho** [NillerMedDild/Enigmatica2Expert#1436]
**Modpack version**
1.71

**Issue**
This is a compound issue:
1) Unbreakable TC Sword broken by Cyclic Automated User.
     I was setting up a mob farm, and used a Cyclic AU to hit the mobs. When I put an unbreakable sword in to test the system, it immediately broke, and became unusable.
2) Broken unbreakable tools unable to be repaired/restored.
     I took the broken sword to a workstation to try to repair it. I am unable to make the sword usable again. I tried all of the materials to no avail. Did some googling, and found this: https://github.com/SlimeKnights/TinkersConstruct/issues/3173

Not sure why Cyclic's AU broke it though.

**Comment by NillerMedDild** [comment]
Which materials are the sword made from?

**Comment by dnulho** [comment]
It is a Wooden Tool Rod, Evil Blade, Stone Cross Guard.

**Comment by NillerMedDild** [comment]
Can you repair it with Evil Nuggets?

**Comment by dnulho** [comment]
There are no evil nuggets, only ingots and blocks.

**Comment by NillerMedDild** [comment]
Alright then, we'll look into it, thanks for the report :)

**Comment by Metalit** [comment]
I had the same issue. It's the evil infused parts - if you replace them, the sword will be fine. (At least for me.) You will have to make a new sword, though.

**Comment by dnulho** [comment]
I actually tried upgrading my wither skeleton cleaver with an evil infused plate, and as soon as I put it back in, it broke as well... I would second your analysis in saying that the issue is with automating evil infused tools. Would that be a bug to report to Tinkers Construct, or Extra Utilities?

**Comment by Metalit** [comment]
Tinkers since it also breaks with cyclic’s user.

**Comment by NillerMedDild** [comment]
It's not a bug, it's intended behaviour.
