### ISSUE TITLE
Game Crashes on World Load After Update

### ISSUE THREAD

**Issue by AzzBlock** [NillerMedDild/Enigmatica2Expert#1437]
**Modpack version**
Latest version

**Issue**
The game crashed whilst exception ticking world.

**Logs**
https://pastebin.com/yTebpSeA

I recently updated the pack and was a few versions behind as I haven't been playing for a while. After updating when I tried to load the world after a while the game would crash and give me message saying "the game crashed whilst exception ticking world".

Any idea how to fix this?

**Comment by NillerMedDild** [comment]
Was that on version 1.72b?

**Comment by AzzBlock** [comment]
> Was that on version 1.72b?

Yes.

**Comment by NillerMedDild** [comment]
There's usually no easy fix for that type of crash, but seeing as your java is outdated, I would start with getting that set up properly, please follow these instructions:
```
You appear to be using outdated Java. This is often caused by Twitch defaulting to an older version than you have available. Follow these steps to update.

* Make sure you have the latest 64-bit Java installed
    https://www.java.com/en/download/manual.jsp Windows Offline (64-bit) is the one you need
* Go to the Twitch Minecraft settings
* Add `-version:1.8+` to the Additional Arguments
```

**Comment by AzzBlock** [comment]
Hi. Tried your suggestion and unfortunately still have the same problem.

**Comment by NillerMedDild** [comment]
Alright, damn. Please post the new crash report :)

**Comment by AzzBlock** [comment]
> Alright, damn. Please post the new crash report :)

Sorry for the late reply, I was busy looking for work and starting and a new job. Here is the new report: https://pastebin.com/Pgs1B3vw

Thanks for taking the time to look into it.

**Comment by NillerMedDild** [comment]
Alright that's a new crash, caused by Optifine.
