### ISSUE TITLE
Moving an Iron dropper with a piston crashes games / servers

### ISSUE THREAD

**Issue by WhyCantPigsFly** [NillerMedDild/Enigmatica2Expert#1438]
**Modpack version**
1.71

**Issue**
If you use a sticky piston to move an iron dropper (maybe others, but this is the only one I've tried), your game / server will freeze and eventually crash.

**Logs**
https://pastebin.com/PKKkxTzc

**Comment by NillerMedDild** [comment]
Thanks for the report, I blacklisted all Random Things blocks from being moved by pistons.
