### ISSUE TITLE
DankNull stuck in AE System

### ISSUE THREAD

**Issue by smmailik** [NillerMedDild/Enigmatica2Expert#1439]
**Modpack version**
**1.72a**

**Issue**

I've accidentally put my DankNull in the AE System and now I can't get it out of there (I've tried many things to get it out no success , I've tried even to exportBus it into a chest as well no success )

**Logs**
No Logs have been created

**Comment by NillerMedDild** [comment]
Try putting a Fuzzy Card in the Export Bus :)

**Comment by smmailik** [comment]
It's not a big deal, I just wanted somehow to warn other people that play to be careful with that . :3
