### ISSUE TITLE
Can't find fire lilies

### ISSUE THREAD

**Issue by codeka** [NillerMedDild/Enigmatica2Expert#144]
#### Issue Description

I wanted to try my hand at breeding Ice & Fire dragons, but you need Fire Lilies to make their food. According to JEI, Fire Lilies grow in the nether, but I flew around there for like half and hour and couldn't find any.

![2018-07-03_22 59 50](https://user-images.githubusercontent.com/1569910/42259320-d523868a-7f14-11e8-9e56-cc65373dc284.png)

I don't know if I just didn't look hard enough, or they're actually not spawning there, but if they're really that hard to find there's basically no point breeding dragons.

#### Modpack version

1.31 (manually downgraded AE2, haven't gotten around to updating to 1.32 yet)

**Comment by NillerMedDild** [comment]
This will be fixed in the next version of Ice&Fire, thank you for the report.
