### ISSUE TITLE
Question: Official Docker server

### ISSUE THREAD

**Issue by StiviiK** [NillerMedDild/Enigmatica2Expert#1440]
Is there any offical Docker image of you for a server with this modpack available?

**Comment by NillerMedDild** [comment]
@Frikkle did you ever publicize yours?

**Comment by Frikkle** [comment]
I haven't yet so far. It wasn't just E2E though, it was embedded in a Multicraft manager. I might throw it online during the Christmas holiday when I have some spare time :)

**Comment by Frikkle** [comment]
@NillerMedDild I've just looked into the container and whether or not its implementation is stable. Here some findings:

- It is stable, but undocumented
- It installs a base Multicraft instance with added built-in SSL certificate issuing for the control panel.
- It is highly configurable in terms of ports and other setup parameters, all through the Docker compose file, so no fiddling with under-water Linux config.
- The installation process is a one-command process followed by a "next, next next" wizard with all settings preconfigured.

The stuff that needs to be done:
- Document "how to install/use".
- Create the possibility to add a `servers.json` (or similar) file in which you can configure server information for servers you want to install (i.e. install Enigmatica 2: Expert version 1.68 on port 31415).
- Make the scripts parse this file and install the defined servers (Forge + modpack download and extraction)
- Create a Server upgrade process; i.e. backup current server, download the new (Forge and) modpack files, create new instance and copy over the world.

When this has been done I think it could be used for the greater public. I am thinking of shipping it with built-in support for:
- Enigmatica 2
- Enigmatica 2: Light
- Enigmatica 2: Expert
- Enigmatica 2: Expert Skyblock
- Enigmatica 4
- Enigmatica 5

The only thing that would be useful for this is some kind of API that helps me resolve a server type and version "Enigmatica 2: Expert v1.68" to a CurseForge file location and Forge version. Is this available somewhere or can we create this?

**Comment by NillerMedDild** [comment]
> Create a Server upgrade process; i.e. backup current server, download the new (Forge and) modpack files, create new instance and copy over the world.

I have a script for that, it requires the server to have a connection to the modpack git repo though.
https://github.com/NillerMedDild/Enigmatica4/blob/master/development/include-in-server-files/update-server.ps1

**Comment by Frikkle** [comment]
Cool, I'd have to convert it to Unix but that's easy enough. Thanks! :)

**Comment by andrefmarques** [comment]
Any progress? :)
