### ISSUE TITLE
Mekanism Cables connection visual

### ISSUE THREAD

**Issue by Atadele** [NillerMedDild/Enigmatica2Expert#1442]
**Modpack version**
1.74b

**Issue**
Not a big deal but, having this problem with mekanism pipes in 2 chunks in my base. They connect but, visually they show no connection. This only fixes if I update the chunk by placing a block nearby. I removed machines in the chunk that could be a problem and no fix. It is also some machine when i remove with a wrench, the render stays. Also it is not is all of the chunk because the problem is not there underground.

**Logs**
https://imgur.com/NQP2SV4 

https://imgur.com/VvEGJxk

https://imgur.com/UYGYoVr

https://imgur.com/8A8ktsq

**Comment by NillerMedDild** [comment]
I understand that this issue is annoying, but I think it would take too long to get fixed, compared to the pay-off. I hope that's alright with you - I would rather spend my time on Enigmatica 4 :)

**Comment by Atadele** [comment]
Oh its fine I just didn't know if it was my save or a problem already known. Thanks for letting me know its a known thing.
