### ISSUE TITLE
Master Crystal from Mystical Agriculture deleted when used on a Basic crafting table

### ISSUE THREAD

**Issue by BodiwNz** [NillerMedDild/Enigmatica2Expert#1444]
**Modpack version**
1.72

**Issue**
Master crystal from Mystical agriculture consumed while making prudentium,I believe it will consume it on other tiers as well.
(As im playing in a small community server I bug-duped the crystals for the sake of science)

**Logs**
YT video https://youtu.be/0n0grEvM3IU

**Comment by NillerMedDild** [comment]
First of all thanks for the video, 10/10 bug showcase :D

I believe updating Extended Crafting will fix this issue, but it will however also break 3 of our existing recipes, so I would prefer not to.

**Comment by BodiwNz** [comment]
Also one more thing,is sticky resin UU mater value 33buckets intentional?
And id like to thank you for such an awesome pack,so far I never found a reason to go into astral or botania and I actually like both after trying them,still got much blood magic and others to discover deeply

**Comment by NillerMedDild** [comment]
Somewhat intentional - The vast majority of UU matter values are generated by IC2, we have no control over those.

You're very welcome! :D
