### ISSUE TITLE
Client crash when using Crescent Hammer on EnderIO Painting Machine

### ISSUE THREAD

**Issue by Unarelith** [NillerMedDild/Enigmatica2Expert#1446]
**Modpack version**
1.72b (latest on Twitch launcher)

**Issue**
Game crashes when using Crescent Hammer on EnderIO Painting Machine (and probably other EnderIO machines too, but I didn't try)

**Logs**
Crash report: https://pastebin.com/LS0qz7BD

**Comment by NillerMedDild** [comment]
Known issue, will be fixed in the next version, thank you for the report :)
