### ISSUE TITLE
Please tweak EnderIO Painting Machine recipe

### ISSUE THREAD

**Issue by Unarelith** [NillerMedDild/Enigmatica2Expert#1447]
**Modpack version**
1.72b

**Issue**
EnderIO Painting Machine requires a NuclearCraft Machine Chassis, which means you need to be quite far in the game to get access to it... However, the Painting Machine is the only way to get access to Conduit Facade blocks, which are more than useful to hide conduits (OC conduits for example, since the OpenComputers cables can't be hidden).

Would it be possible to make this recipe less expansive and complicated?

**Comment by NillerMedDild** [comment]
Did you check the Nuclearcraft machine chassis recipe?

**Comment by Unarelith** [comment]
Oh I though Lithium and Ferroboron weren't early game ores but actually they are.
I was wrong then, but I still think this recipe is way too expensive for what it is (cosmetic upgrade)

**Comment by NillerMedDild** [comment]
I don't, it's incentive to progress :)
