### ISSUE TITLE
OpenBlocks Tank not showing in JEI

### ISSUE THREAD

**Issue by Unarelith** [NillerMedDild/Enigmatica2Expert#1448]
**Modpack version**
1.72b

**Issue**
The OpenBlocks Tank is not showing in JEI when searching for it with either "tank" or "@openblocks", but it's still possible to find it by looking at the usage of obsidian... Is it intended to hide it?

**Comment by NillerMedDild** [comment]
Yep it is intended, showing it tends to cause quite a bit of lag.

**Comment by Unarelith** [comment]
Hmmm ok I see, but this is a cheap tank and it's really useful imo, could it be possible to replace its 3D model in JEI by a 2D image within the modpack? Or is that something that only OpenBlocks developers can do?

**Comment by NillerMedDild** [comment]
No, that would require you to turn it into an item, and that kinda destroys it's purpose. It's craftable even though it's not in JEI - glass panes in a plus sign with obsidian around it.
