### ISSUE TITLE
IC2 not respecting wrench config

### ISSUE THREAD

**Issue by MorganSimic** [NillerMedDild/Enigmatica2Expert#1449]
**Modpack version**
1.72

**Issue**
The IC2 config is set to not require a wrench but you can't mine machines. This is a repeat of #1131. And it was fixed before by IC2 but it seems the bug is back again. Couldn't find anything in the IC2 changelog that would indicate that it is fixed.

Things to probably do:
Check if it remains the same on recent modpack version (1.72b) and recent IC2 version.
Maybe report to IC2 that this bug is happening again.

**Comment by NillerMedDild** [comment]
dammit :P
We're about 20 versions behind, I'm a bit scared to update tbh.

**Comment by MorganSimic** [comment]
I can understand that. IC2 added a bunch of new stuff in more recent versions. Like the Coke Oven, pipes, some kind of heat transfer system and bunch of other stuff. So updating might not be trivial.

**Comment by NillerMedDild** [comment]
Yep.. I updated 1 version too far and ended up with a mean dupe issue, so imagine the damage 20 versions could do :D

**Comment by NillerMedDild** [comment]
I can mine machines just fine in 1.73 :)
