### ISSUE TITLE
Dupe Bug with Player Chest from Ex Util 2.

### ISSUE THREAD

**Issue by SweetestPumpkin** [NillerMedDild/Enigmatica2Expert#1450]
I sent it to Frikkle on the discord and he said he'll send it to Niller and other mods !
This is so that it doesnt get out easily

**Comment by Frikkle** [comment]
And I forwarded the information to Niller.

**Comment by NillerMedDild** [comment]
Thanks for letting us know. I've known about this issue for quite some time, but have decided not to do anything, as it would require disabling items that are fairly frequently used. If people really want to dupe things, I think they'll always find a way.

**Comment by Frikkle** [comment]
Closing this issue as "won't fix because of reasons".
