### ISSUE TITLE
Re-enabled SmallPropertyStorage in FoamFix, potentially reducing RAM usage by 300-500MB

### ISSUE THREAD

**Issue by NillerMedDild** [NillerMedDild/Enigmatica2Expert#1451]

**Comment by Dimentive** [comment]
Why was this disabled in the first place?

**Comment by Dimentive** [comment]
Why was this disabled in the first place? Can it cause issues?

**Comment by NillerMedDild** [comment]
It used to cause a startup crash, when paired with NEID and UnlimitedChiselWorks.
