### ISSUE TITLE
Game crashes 

### ISSUE THREAD

**Issue by Smok3boy** [NillerMedDild/Enigmatica2Expert#1452]
**Modpack version**
1.72

**Issue**
I crash every time i load my unloaded base 

**Logs**
https://pastebin.com/b2n5Fz3M

**Comment by Discomanco** [comment]
A lighting update from Passwords Lib.
Do you have a dank/null in a docking station in your base? If so, remove it.
A dank/null fix has also been applied to 1.73, so you could try updating to that.

And with all that, I can see you're running with an outdated java.
```
You appear to be using outdated Java. This is often caused by Twitch defaulting to an older version than you have available. Follow these steps to update.

* Make sure you have the latest 64-bit Java installed
    https://www.java.com/en/download/manual.jsp Windows Offline (64-bit) is the one you need
* Go to the Twitch Minecraft settings
* Add -version:1.8+ to the Additional Arguments
```

**Comment by NillerMedDild** [comment]
1.72b and 1.73 should both resolve this issue.

**Comment by Smok3boy** [comment]
i upgrade my java to the lastest 
we dont use dank/null 
i try to log -in and https://pastebin.com/d23ZWFJh

**Comment by NillerMedDild** [comment]
Please verify whether 1.72b or 1.73 resolves your issue, or not.

**Comment by Smok3boy** [comment]
i cannot for now since the server i play is on 1.72

**Comment by Frikkle** [comment]
Please let us know when you have been able to confirm updating fixes the issue. You can link this issue to your server admin for reference.

**Comment by Smok3boy** [comment]
The server got updated to 1.73 and i got not crash since then
