### ISSUE TITLE
Ultimate Stew Recipe - Grapes not oredict'd

### ISSUE THREAD

**Issue by valarnin** [NillerMedDild/Enigmatica2Expert#1454]
**Modpack version**
1.72b

**Issue**
In the `Ultimate Stew` recipe, the grapes are not ordict'd, and must be Rustic grapes (Pams Harvestcraft grapes don't work). Should probably be oredict'd, and some of the others might need to be as well?

**Comment by NillerMedDild** [comment]
Thanks for the report, I'll get that fixed :)

**Comment by Frikkle** [comment]
And here I was thinking this was intentionally being a pain 😅
