### ISSUE TITLE
Rock Crystal ore not ore dictionary with $ore or ore*

### ISSUE THREAD

**Issue by SweetestPumpkin** [NillerMedDild/Enigmatica2Expert#1455]
**Modpack version**
1.72

**Issue**
Title explains everything , just noticed that rock crystal ore is not ore dict'd with 'ore' and found no reason for it to not be. 

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by NillerMedDild** [comment]
The reason it's not oredicted with ore is so Digital Miners and the like don't find it - It's intentional from the mod author's side I believe.
