### ISSUE TITLE
Power buffer on Decay Hastener too small

### ISSUE THREAD

**Issue by valarnin** [NillerMedDild/Enigmatica2Expert#1456]
**Modpack version**
1.72b

**Issue**
The power buffer of the Decay Hastener is too small, causing it to stutter when fully upgraded no matter how much RF/t you can input

Not sure if this is a pack config issue or an underlying NC issue, so reporting here first. If it's an underlying NC issue let me know and I'll report it there as well.

![image](https://user-images.githubusercontent.com/6119598/71431881-448f7b00-26a3-11ea-8b2d-5bc1f08bd048.png)

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
It works just fine for me, the buffer goes to 0 but it doesn't stutter or slow down.
