### ISSUE TITLE
Extra Cells 2 Gas cells not working correctly - wrong capacity

### ISSUE THREAD

**Issue by HerrHebel** [NillerMedDild/Enigmatica2Expert#1457]
**Modpack version**
1.74 (same issue present on 1.72b)

**Issue**
ExtraCells 2 Gas storage cells not having proper capacity - for example 4K Storage Cell has a capacity of 32 buckets of gas (afaik they should have the same properties as fluid cells, that is 4k cell ~1k buckets of capacity) - https://imgur.com/a/L1HHQG6. 
I cant make any adjustments in config with this matter and im not competent enough to figure out anything more then that

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.
