### ISSUE TITLE
Journeymap waypoint labels no longer visible

### ISSUE THREAD

**Issue by Nila24** [NillerMedDild/Enigmatica2Expert#1458]
Modpack version V1.73, V1.74 with journeymap-1.12.2-5.5.6 

**Issue**
Journeymap waypoint labels no longer visible neither on in game or full screen map. Full map setting with the corresponding name does nothing
Downgrading to journeymap-1.12.2-5.5.5 fixes the issue in V1.74

**Comment by NillerMedDild** [comment]
Thanks for the report, I have relayed the issue :)

**Comment by NillerMedDild** [comment]
It has been fixed in JourneyMap, it'll be in next update of it :)

**Comment by Nila24** [comment]
Thanks!
