### ISSUE TITLE
Vulpes Library Elite Motor Uncraftable

### ISSUE THREAD

**Issue by ladecaz** [NillerMedDild/Enigmatica2Expert#1459]
**Modpack version**
Version 1.74 Release

**Issue**
The Elite motor from Vulpes Library is no longer craft-able. The Dilithium crystals have disappeared from the recipe. In the version 1.72b the recipe worked and required the Dilithium Crystals. Issue was able to be temporarily resoled by downgrading both AdvancedRocketry and LibVulpes from:
 - AdvancedRocketry-1.12.2-1.6.0-190-universal
 - LibVulpes-1.12.2-0.4.2-69-universal
to version:
 - LibVulpes-1.12.2-0.4.0-56-universal
 - AdvancedRocketry-1.12.2-1.5.0-139-universal

**Logs**
No logs or crash, however screenshots attached.
v1 72b working recipe
![v1 72b working recipe](https://user-images.githubusercontent.com/19367737/71500099-9c063480-28b7-11ea-8b3b-fb165b90a7b1.png)
v1 74 recipe issue
![v1 74 recipe issue](https://user-images.githubusercontent.com/19367737/71500101-9c9ecb00-28b7-11ea-9448-1e668319f529.png)
v1 74 listed recipe
![v1 74 listed recipe](https://user-images.githubusercontent.com/19367737/71500102-9c9ecb00-28b7-11ea-8c74-c5a5e86a8f36.png)

**Comment by NillerMedDild** [comment]
I'll get that fixed, thanks for the report :)
