### ISSUE TITLE
Server always crash

### ISSUE THREAD

**Issue by SamLam140330** [NillerMedDild/Enigmatica2Expert#1460]
**Modpack version**
1.74

**Issue**
When I update the modpack to the latest version which is 1.74 from 1.69, the server will alway crash suddenly.

**Logs**
https://drive.google.com/drive/folders/13paqSrmYdpdEZo6MRCo85u-RQ5TjRiFm?usp=sharing

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
Which rituals do you currently have running? The crash is caused by a Master Ritual Stone.

**Comment by NillerMedDild** [comment]
Also, I greatly appreciate that you supplied so many log files :)

**Comment by SamLam140330** [comment]
> Which rituals do you currently have running? The crash is caused by a Master Ritual Stone.

As I know, Serenade of the Nether and Well of suffering. But I am not sure my friends

**Comment by NillerMedDild** [comment]
Could you ask if any of them are using a Ritual from Animus, please?

**Comment by SamLam140330** [comment]
> Could you ask if any of them are using a Ritual from Animus please?

They said they didn't use Ritual from Animus

**Comment by NillerMedDild** [comment]
Thank you :)

**Comment by NillerMedDild** [comment]
Have you tried updating again, after turning Rituals off?
