### ISSUE TITLE
Repeatedly crashing during startup.

### ISSUE THREAD

**Issue by QazCetelic** [NillerMedDild/Enigmatica2Expert#1463]
**Modpack version**
1.74

**Issue**
Can't start modpack
It crashes while loading while at:
`Loading - Initializing Minecraft Engine
Loading Resource - Modelmanager
Modelloader- baking`
It has happend 4 times now.

**Logs**
https://paste.ee/p/iR9Gu

**Comment by Discomanco** [comment]
You only have 2GB RAM allocated. You must allocate at least 6GB, 8GB recommended

**Comment by QazCetelic** [comment]
That's weird because I selected 6GB

**Comment by Frikkle** [comment]
@QazCetelic if you're using the Twitch launcher, make sure to change the allocated ram settings in the global Minecraft settings through the Twitch menu. Changing the ram in the Minecraft instance profile tends to keep resetting it every launch.
