### ISSUE TITLE
Forestry Circuit Board Autocrafting pattern issue

### ISSUE THREAD

**Issue by HerrHebel** [NillerMedDild/Enigmatica2Expert#1465]
**Modpack version**
1.74 

**Issue**
When making an autocrafting pattern for AE system that contains circuit boards, the pattern terminal always puts Forestry circuits as "Fits 1 electron tube", whereas tooltip on boards themselves says 4 (or 3 or 2, depending on circuit tier). It doesn't dictionary in any way, setting pattern to use substitutions doesn't work. Tried it with multiple items and I always had to manually switch the circuit put by terminal to the one I have in my storage

https://imgur.com/a/lNrbmLc

**Comment by NillerMedDild** [comment]
I'm afraid there's nothing we can do about that.

**Comment by NillerMedDild** [comment]
I was wrong about this, it is looking like a bug on my end, sorry for closing the issue prematurely.
It is being tracked here: #1471
