### ISSUE TITLE
Nuclearcraft Ores via Void Ore Miner Tier 6

### ISSUE THREAD

**Issue by UnbreakableHoe** [NillerMedDild/Enigmatica2Expert#1467]
**Modpack version**
1.74

**Issue**
More of a suggestion, but I feel that the nuclearcraft ores (magnesium, lithium, thorium, boron) should be one of the outputs of the void ore miner tier 6 - it would further incentivize creating a void ore miner tier 6 as the only unique output it has over a tier 5 is draconium, which can be farmed via seeds. There are no seeds for these ingots, so I feel that, to make it more useful to get to a tier 6, these ores should be added to the loot table. Thanks in advance, and love the work you guys do - amazing pack!

**Comment by NillerMedDild** [comment]
Thanks! :D

This isn't the first time this has been suggested, but I would prefer that people use Sieves to get NuclearCraft Ores.

**Comment by UnbreakableHoe** [comment]
Okay, thank you!
