### ISSUE TITLE
Gendustry causing crash before pack finishes launching

### ISSUE THREAD

**Issue by ArrZeroZero** [NillerMedDild/Enigmatica2Expert#1468]
**Modpack version**
1.74
**Issue**
before all the mods can load gendustry causes the pack to crash i think ive tried updating java and giving the pack more ram

**Logs**
https://pastebin.com/TGkLLp71
[crash-2019-12-30_14.32.09-client.txt](https://github.com/NillerMedDild/Enigmatica2Expert/files/4010831/crash-2019-12-30_14.32.09-client.txt)

**Comment by NillerMedDild** [comment]
Twitch is using old Java, in order to fix it:
* Go to the Twitch Minecraft settings
* Add `-version:1.8+` to the Additional Arguments

Additionally, I recommend redownloading the pack to fix this issue.

**Comment by ArrZeroZero** [comment]
i have redownloaded the pack and the twitch launcher let me try the additional argument and let you know

**Comment by ArrZeroZero** [comment]
Error: Unable to locate JRE meeting specification "1.8+"

thats what i get when i add that to the additional arguments

**Comment by NillerMedDild** [comment]
You've downloaded 32-bit java, you need 64-bit.

**Comment by ArrZeroZero** [comment]
just downloaded the 64-bit java idk why the auto installer of java put 32-bit but im still getting the same issue about the additional argument i typed it in exactly how you did

**Comment by NillerMedDild** [comment]
Did you delete the 32-bit version?

**Comment by ArrZeroZero** [comment]
yes
