### ISSUE TITLE
Cockatrice Scepter is Uncraftable

### ISSUE THREAD

**Issue by Aglacor434** [NillerMedDild/Enigmatica2Expert#1469]
**Modpack version**
1.72b

**Issue**
no recipe for witherbone shards as the recipe changes witherbone to the tinkers equivalent and vice versa

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by NillerMedDild** [comment]
What do you need Witherbone Shards for?

**Comment by Aglacor434** [comment]
to make a cockatrice scepter from ice and fire. it isn't needed for the pack just someone on my server wanted to make one but can't was going to change the recipe myself but wasn't sure what i needed to tweak

**Comment by NillerMedDild** [comment]
Ah I see, I guess that was added in a recent(ish) update. I'll look into getting the recipe changed.

**Comment by Aglacor434** [comment]
thank you appreciate it :)
