### ISSUE TITLE
Trouble getting latest version to run on ubuntu server

### ISSUE THREAD

**Issue by XB33RGOGGL3SX** [NillerMedDild/Enigmatica2Expert#1470]
**Modpack version**
1.74
**Issue**
*update* of course I can install java on my win 10 machine and I am currently running the server on there and pregen-ing. Going to try and copy it onto my server then run it and see what happens. I can't find a way to get java 8 for my server and I am kinda bummed.* 

I am trying to install and run this on a ubuntu server. I have google fu-ed all I can and none of the resolutions I have found worked. I am sure it is something simple that I messed up and there is one promising git reply I found but the person never gives a complete answer to the resolution.

Installing java 8, unfortunately oracal has locked down everything so I can't get java8jre to install.

I have edited the errors out of the serverstartscript, but now I keep getting an error that won't let the server start. I did run the 1.12.2 server in the directory and it did start up. So I know the 12.2 server file that was installed when I ran the script the first time will run on my server. 

the error is
A problem occurred running the Server launcher.java.lang.reflect.InvocationTargetException
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at cpw.mods.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:43)
at cpw.mods.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:12)
Caused by: java.lang.NoClassDefFoundError: org/apache/logging/log4j/Level
at net.minecraft.launchwrapper.Launch.launch(Launch.java:94)
at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by NillerMedDild** [comment]
You need Java 8, so I guess OpenJDK is your best bet for Ubuntu. The error you pasted (please include actual logs next time) indicates that Forge was not installed, or not installed correctly.
You could be missing the library/libraries folders.

**Comment by XB33RGOGGL3SX** [comment]
Ok. I just wanted to confirm the java 8 part. Just blows they pulled it out of apt get.

**Comment by NillerMedDild** [comment]
Yeah, it really does :(
