### ISSUE TITLE
Forestry CircuitBoard Bug

### ISSUE THREAD

**Issue by S1lentN1ght** [NillerMedDild/Enigmatica2Expert#1471]
Version 1.74

There is a bug with the 2 crafting recipes involving Intricate Circuit Boards having a text script of "Fits 1 Electron Tube" in recipe examples, rather than what it should be on the crafted item as "Fits 4 Electron Tubes."
While this doesn't seem like a big deal, it does disable the use of Intricate Circuit Boards in AE2 Automation. 
![IntricateCB_Normal](https://user-images.githubusercontent.com/59313874/71610925-2de59a00-2b63-11ea-9531-672e68c87189.png)
How it should be.
![IntricateCB_Broken](https://user-images.githubusercontent.com/59313874/71610932-34741180-2b63-11ea-9d42-084f8a5002ac.png)
How it becomes in recipes and automation. 
![MCAutomation](https://user-images.githubusercontent.com/59313874/71610938-45248780-2b63-11ea-9958-d5d41997ebc0.png)

**Comment by S1lentN1ght** [comment]
After more exploring It doesn't happen with just this Forestry Circuit Board, but all boards. (Except Tin since it can only have 1 Electron tube to start with.)

**Comment by NillerMedDild** [comment]
Input the correct Circuit Board in the AE recipe, I'm guessing this issue comes from shift-clicking the recipe into a Crafting Pattern from JEI.

**Comment by NillerMedDild** [comment]
Could you please take the correct Circuit Board in your hand, use the command `/ct hand` and then paste the result here?

**Comment by S1lentN1ght** [comment]
![Board](https://user-images.githubusercontent.com/59313874/71624776-4b8e2000-2bb2-11ea-809c-8412282c2ca1.png)
