### ISSUE TITLE
Creative Powercell uncraftable

### ISSUE THREAD

**Issue by SaanMcC** [NillerMedDild/Enigmatica2Expert#1473]
**Modpack version**
1.74

**Issue**
Can't craft the creative powercell.  If NBT tags are important then issue appears to be with the 8 "Energy Cell (Resonant)"
NBT Tag on the recipe is {Level:4b}
NBT Tag on a freshly created one is {Recv:125000,RSControl:0b,Facing:3b,Creative:0b,Energy:0,Level:4b,SideCache:[B;2B,1B,1B,1B,1B,1B],Send:125000}

A freshly created TE Energy Cell (before upgrading it) while it is still in the crafting grid and untouched has these NBT tags as well.

Holding shift over the actual item has one extra line (than the recipe): "Signal: Disabled"

Metadata is identical.

No recipe for the energy cell (resonant), when clicking it in the recipe.

**Logs**
n/a

**Comment by SaanMcC** [comment]
FYI When checking some Let's Plays, I noticed that their recipies had AdvRocketry Dilithium crystals in the recipe, these are missing in 1.74.

**Comment by NillerMedDild** [comment]
The oredict for Dilithium changed in Advanced Rocketry, for some reason, which broke this recipe - Thanks for the report, I'll make a hotfix soon :)
