### ISSUE TITLE
Bug with new modified crafts

### ISSUE THREAD

**Issue by geixen** [NillerMedDild/Enigmatica2Expert#1474]
**Modpack version**

Enigmatica expert 2 1.72b

**Issue**

no puedo avanzar en los crafteos , no aparecen los crafteos modificados y en youtube las personas que juegan enigmatica 2 expert si les aparece los nuevos crafteos como el marco de maquina básica y ami nome aparece ninguno de los nuevos.

I can not advance in the crafteos, the modified crafteos do not appear and in youtube the people who play enigmatica 2 expert if the new crafteos appear as the basic machine frame and in addition none of the new ones appears.

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by NillerMedDild** [comment]
If you're sure that you downloaded Enigmatica 2: Expert and not just Enigmatica 2, try re-installing the modpack.

**Comment by geixen** [comment]
> Si está seguro de que descargó Enigmatica 2: Expert y no solo Enigmatica 2, intente volver a instalar el modpack.

obviously , Enigmatica EXPERT 2 1.72b , not only does it happen to me, but also those who enter the private server

**Comment by NillerMedDild** [comment]
In that case you have set up the server incorrectly, you're most likely missing the scripts folder.
