### ISSUE TITLE
Cheap Pizza

### ISSUE THREAD

**Issue by nhilerion** [NillerMedDild/Enigmatica2Expert#1475]
**Modpack version**
1.74

**Issue**
Basically free pizza.

**Recipe**
![javaw_ItvyckB0O7](https://user-images.githubusercontent.com/51247841/71785572-7ee10c80-3001-11ea-93d6-d2aa5cf0c6ba.png)

**Comment by NillerMedDild** [comment]
Yikes, I'll get that fixed, thanks :)

**Comment by MaxNeedsSnacks** [comment]
this is actually a bug in harvestcraft, not within enigmatica iirc

**Comment by Frikkle** [comment]
This has been reported to Harvestcraft; see https://github.com/MatrexsVigil/harvestcraft/issues/382
