### ISSUE TITLE
Can't craft Creative Powercell

### ISSUE THREAD

**Issue by internetyh** [NillerMedDild/Enigmatica2Expert#1476]
Enigmatica 2 Expert
1.74

Can't craft the Creative Powercell with all items in the table, tried clicking the output slot many times didn't work, went back the old recipe I've seen on youtube with 4 Dilthium Crystals inbetween the Anglesite and the Benitoite, that didn't work either. Also tried upgrading them with a resonant kit and also upgrading by going through all the tiers. The energy cells are not charged with 0 send receive like the recipe specifies 

**Logs**
https://i.imgur.com/i2tP6JB.png
https://i.imgur.com/uglpQCB.png
https://i.imgur.com/l4x20fH.png

**Comment by Discomanco** [comment]
This was fixed in 1.75, so please update your client and try again :)
