### ISSUE TITLE
Iron Nuggets from Arc Furnace no Craft recipe

### ISSUE THREAD

**Issue by TheSim14** [NillerMedDild/Enigmatica2Expert#1477]
**Modpack version**
1.75

**Issue**
Iron Nuggets in Arc Furnace (after smelting some Armor and so) are from Immersive not from Minecraft (after Update from 1.74 to 1.75)

And sorry for my bad english :/

**Comment by NillerMedDild** [comment]
Thanks for the report, and your english was perfectly fine! :)

**Comment by TheSim14** [comment]
Np^^

Using meanwhile the Oredictionficator from Mekanism^^

**Comment by NillerMedDild** [comment]
I am unable to fix this it seems, and the mod author is reluctant: https://github.com/BluSunrize/ImmersiveEngineering/issues/3234
