### ISSUE TITLE
duplication of Black Quartz.

### ISSUE THREAD

**Issue by rsauber** [NillerMedDild/Enigmatica2Expert#1478]
**Modpack version**
1.74 

**Issue**
Duplication of Black Quartz. 2 create a block, a block creates into 4. This is an install straight from twitch with no modifications or changes.  I did not upgrade the pack from anything as I just started recently from a fresh install. 

**Logs**
No logs.   I know this was reported previously, but it appears to still be an issue on a fresh install.  If you need any more information, please ask!

**Comment by NillerMedDild** [comment]
I'll have another look, thanks for the report :)

**Comment by rsauber** [comment]
the black quartz block back to 4 black quartz says it is a recipe from crafttweeker2, if that is any help.

**Comment by NillerMedDild** [comment]
I made it, sadly :P

**Comment by thornss** [comment]
not sure if it's intended
4 black quartz makes a block
![2020-01-11_21 34 28](https://user-images.githubusercontent.com/55922862/72209408-d0384280-34be-11ea-9211-9d9f76563f16.jpg)

block can be crushed into 9 dusts
![2020-01-11_21 58 54](https://user-images.githubusercontent.com/55922862/72209411-ddedc800-34be-11ea-9921-18408ccf5395.jpg)

dust can be smelted into black quartz
![2020-01-11_21 59 07](https://user-images.githubusercontent.com/55922862/72209414-eb0ab700-34be-11ea-8f4c-fbcea4a592de.jpg)

i.e. 4 black quartz makes 9

**Comment by NillerMedDild** [comment]
Thanks for the added info, that's not on purpose either ^^'

**Comment by Frikkle** [comment]
If there's more issues here, should the ready for testing label be removed? :)

**Comment by NillerMedDild** [comment]
I can't for the life of me find the Block of Black Quartz Sag Mill recipe, so I can't remove it ><

**Comment by NillerMedDild** [comment]
Alright, I gave it a shot, atleast 50% of this issue is fixed ^^'

**Comment by NillerMedDild** [comment]
I was unable to fix the Block Sag Mill recipe.
