### ISSUE TITLE
[Crash] Calling some Plethora-added peripherals methods from OpenComputers

### ISSUE THREAD

**Issue by Lgmrszd** [NillerMedDild/Enigmatica2Expert#1479]
**Modpack version**
1.74

**Issue**
When connecting OpenComputers computer (using it's adapter) to ActuallyAdditions Item Interface (with Item Laser attached, but I haven't tested without it, should probably crash too) and calling any method except `getDocs`, the game will crash. After loading world again computer displays error "Unsupported method". This is similar to https://github.com/MightyPirates/OpenComputers/issues/2996 but this time causes game to crash. My suggestion is to disable CC-oriented peripherals support in OC to prevent them appearing as available components but looks like there is no config option for it.

**Logs**
Two of them, second one created with VanillaFix installed
[log1](https://pastebin.com/5LXmEZXi)
[log2](https://pastebin.com/QHkbUD4i)

**Comment by NillerMedDild** [comment]
Thanks for the report, I'll have a look at what we can do.

**Comment by Lgmrszd** [comment]
Tested it again, this happens basically with every tile-entity with inventory attached to OC adapter. It is possible to disable some of Plethora functionality (as described [here](https://squiddev-cc.github.io/plethora/configuring.html#blacklisting-providers)), but this is not a good solution since this will disable such functionality for ComputerCraft as well.

**Comment by NillerMedDild** [comment]
Dammit. I suppose the best solution would be to keep this bug open for people coming across the issue.

**Comment by Lgmrszd** [comment]
Fixed in Plethora 1.2.3!
