### ISSUE TITLE
First Backpack Recipe

### ISSUE THREAD

**Issue by Protius7331** [NillerMedDild/Enigmatica2Expert#148]
#### Issue Description

At the beginning of the pack, the very first quest reward for the backpack frame and tanned leather suggests making a backpack. When I looked in JEI to find the recipe, it only showed the Iron Frame in the recipe. After trying with the wooden frame the backpack crafted but it was confusing to have JEI tell me otherwise. I am unsure if the issue is the mod's JEI integration or something in the pack hiding that recipe.

#### Modpack version (Do not use "latest")

1.32

#### Crash Report

N/A

**Comment by Protius7331** [comment]
I've never encountered the mod before, so any frame works in the recipe and that determines the stats of the bag? It works so it's not a huge problem, just was slightly confusing to me. Is is possible to have the current recipe cycle through the different options (like it does with oredict or multiple possible items in the same place), or would that require changing the recipe itself?

**Comment by NillerMedDild** [comment]
Yeah, any frame works, and any leather works - The quality determines the size of the Backpack. It's not possible to have it cycle through ingredients, because each distinct set of ingredients makes a different backpack.
