### ISSUE TITLE
/dank/null duplication

### ISSUE THREAD

**Issue by questman595** [NillerMedDild/Enigmatica2Expert#1480]
**Modpack version**
1.75

**Issue**
While exploring the /dank/null Docking Station, Holding shift (Crouching) and right clicking with the /dank/null MKVI and the Docking Station while simultaneously moving mouse down to a block without an inventory (e.g. Wood). doesnt work 100% but I now have 50 /dank/nulls :) 

Thankyou

**Comment by NillerMedDild** [comment]
Ouch, does the inventory of the Dank/Null get replicated as well?

**Comment by NillerMedDild** [comment]
Possibly linked to https://github.com/p455w0rd/DankNull/issues/241 - Would you mind checking if you can do it with other tiers of Dank/Null?

**Comment by questman595** [comment]
Ok, This bug only works with freshly spawned /dank/null, and when you put an item in it, it will stop any glitches from occuring reguardless of if you have any items in it. This works with any /dank/null Version. when you spawn it in, it won't place it on the docking station, it would only open the inventory. so to answer your question yes it works for multiple tiers, and putting items in removes the duplication glitch from that /dank/null.

**Comment by NillerMedDild** [comment]
Alright, thanks for testing - In that case I will let this remain unsolved, since the dev is very busy/stressed out :)
