### ISSUE TITLE
Astral Sorcery Mineralis Ritual doesn't generate normal Certus

### ISSUE THREAD

**Issue by PinieP** [NillerMedDild/Enigmatica2Expert#1481]
**Modpack version**
1.75

**Issue**
Astral Sorcery Mineralis Ritual only generates Charged Certus Ore no normal Certus.

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by NillerMedDild** [comment]
I sadly cannot change that, it's Charged Certus Ore or no Certus.
