### ISSUE TITLE
Crashes while loading

### ISSUE THREAD

**Issue by indomonkeyy** [NillerMedDild/Enigmatica2Expert#1482]
**Modpack version**
1.74

**Issue**
Crashes while loading, already updated java and reinstalled twitch app and minecraft launcher. 

**Logs**
https://pastebin.com/CUPWbX3P

**Comment by Discomanco** [comment]
Not every step to use update Java has been done, as it's still using the integrated one.  
```You appear to be using outdated Java. This is often caused by Twitch defaulting to an older version than you have available. Follow these steps to update.

* Make sure you have the latest 64-bit Java installed
    https://www.java.com/en/download/manual.jsp Windows Offline (64-bit) is the one you need
* Go to the Twitch Minecraft settings
* Add -version:1.8+ to the Additional Arguments
```

You also only have 3GB RAM allocated, which is not enough. You need to allocate at least 6GB, 8GB recommended
