### ISSUE TITLE
Better Questing Party Not "Working"

### ISSUE THREAD

**Issue by MS21GH** [NillerMedDild/Enigmatica2Expert#1483]
**Modpack version**
1.75

**Issue**
Just like #1336 , the mod doesn't seem to realize that we're in a party and my friend's quests don't result as completed on my end

**Comment by NillerMedDild** [comment]
Are you online at the same time?

**Comment by MS21GH** [comment]
Yes, we're both online at the same time

**Comment by NillerMedDild** [comment]
Is the on a dedicated server or LAN? Are you in different time zones?

**Comment by intoxicatedpenguin** [comment]
I am also having issues with party progression. Same timezone for 2/3 players on a dedicated server that I'm hosting.

**Comment by NillerMedDild** [comment]
And none of you are getting quest updates, while simultanously online?

**Comment by MS21GH** [comment]
We're in the same timezone, over Internet, and the other person seems to be
getting the quests they're completing, whereas I'm not getting the ones
they're completing

**Comment by NillerMedDild** [comment]
Kinda weird question, but could you try syncing your PC times? It might be linked to this: https://github.com/NillerMedDild/Enigmatica2/issues/596

**Comment by MS21GH** [comment]
I'll try next time I'm able to play, busy atm

**Comment by MS21GH** [comment]
Our system clocks seem to be ever-so-slightly out of sync (like 3 to 5 seconds)

**Comment by MS21GH** [comment]
My friend has now completed a quest that wasn't complete on my end, but that I had access too, and it seems like it completed it on my end too; the rest of the quests, however, are still locked for me

**Comment by NillerMedDild** [comment]
Thanks, that helps a great deal, I'll report the issue this evening.

**Comment by NillerMedDild** [comment]
I added this issue to an existing issue that is related - https://github.com/Funwayguy/BetterQuesting/issues/679
