### ISSUE TITLE
High velocity when using Tinker's Construct slime boots and under "bouncy" effect"

### ISSUE THREAD

**Issue by Lgmrszd** [NillerMedDild/Enigmatica2Expert#1484]
**Modpack version**
1.74

**Issue**
Cyclic adds bouncy effect which can be acquired from both Potion of Bouncing or one of the Slime Plates. This effect allows player to accumulate velocity when jumping. Slime Boots do similar thing. Combining those, it is possible in some conditions (jumping from > 3 blocks height or using the Slime Plate, no trees/building/mountains/etc on the way) to travel over a very long distance (near 8000 blocks in Biomes O' Plenty world, over 12000000 in superflat) in a very short time (5-10 seconds), causing worldgen lag.

**Logs**
There aren't any.

**Comment by NillerMedDild** [comment]
Jesus christ, cool :P

**Comment by NillerMedDild** [comment]
Reported the issue here: https://github.com/Lothrazar/Cyclic/issues/1275
Thanks for the report!

**Comment by Lgmrszd** [comment]
Just remembered [this reddit post](https://www.reddit.com/r/feedthebeast/comments/e4qz4n/i_thought_slimeboots_with_slimesling_is_seriously/) featuring same issue when using Player Launcher. Looks like it have been reported already (with using slimesling instead of boots though): https://github.com/Lothrazar/Cyclic/issues/1191

**Comment by NillerMedDild** [comment]
That it has, and I guess it's working as intended ^^'
