### ISSUE TITLE
Mekanism Cardboard Boxes stuck in AE2 Computer Storage

### ISSUE THREAD

**Issue by BluRael** [NillerMedDild/Enigmatica2Expert#1485]
**Modpack version**
1.75

**Issue**
Cardborad boxes with blocks inside cannot be taken out of the AE2 computer storage.
Clicking on the box in the terminal does nothing.

**Logs**
![image](https://user-images.githubusercontent.com/26899728/72209696-e935f900-34a8-11ea-8ac8-bda186823599.png)

**Comment by NillerMedDild** [comment]
#1337
