### ISSUE TITLE
Forestry Carpenter didn't accept liquids until I quit and reopened the game

### ISSUE THREAD

**Issue by RolaRoul** [NillerMedDild/Enigmatica2Expert#1486]
**Modpack version**
1.75

**Issue**
When I created the carpenter from Forestry, I was not able to insert fluids. Neither placing a bucket of liquid into the liquid input slot on the GUI nor pumping them in in-world using IO fluid conduits or TE fluiducts worked. Exiting the world and re-entering it did not fix the issue. Closing the game and re-opening it did fix the issue.

**Comment by NillerMedDild** [comment]
Can you reproduce the issue? :)
