### ISSUE TITLE
Infinite power - Wireless Crafting Terminal

### ISSUE THREAD

**Issue by Defman** [NillerMedDild/Enigmatica2Expert#1487]
**Modpack version**
Enigmatica2Expert-1.73

**Issue**
Charging the "Wireless Crafting Terminal" in a "Induction Matrix" from "Mekanism" results in negative -2^31 AE on the "Wireless Crafting Terminal" and a constant max input rate of RF into the "Induction Matrix". If the "Induction Matrix" contains a single "Advanced Induction Cell" and "Advanced Induction Provider" it will charge with 204.8kRF/t until its full at 3.2GRF.

![image](https://user-images.githubusercontent.com/1496019/72265998-c11bd680-361d-11ea-9d0a-382b99acf4e0.png)

**Comment by NillerMedDild** [comment]
Thanks for the report! Please update to 1.75 and check if it still occurs :)

**Comment by Defman** [comment]
Confirmed EnigmaticaExpert1.75.

It might be a bug due to the fact that the "Wireless Crafting Terminal" internally uses a singed 32bit integer to store its power and the "Induction Matrix" can store more than a signed 32bit int can hold and it overflows into negative and the "induction Matrix" have no idea have to handle a negative power source and treats its as infinite which is some what the normal i.e. -1 to represent infinite.

**Comment by NillerMedDild** [comment]
That's probably what's happening, yeah. I didn't think signed integers could overflow, but I guess they can :P I'll report this to the Wireless Crafting Terminal & Mekanism issue trackers tomorrow evening (in roughly 20 hours)

**Comment by NillerMedDild** [comment]
I do not believe I can fix this, and the majority of modders no longer support 1.12, so I'll close this issue.

Nethertheless, thank you for reporting :)
