### ISSUE TITLE
Delayed Lag Spiking?

### ISSUE THREAD

**Issue by S1lentN1ght** [NillerMedDild/Enigmatica2Expert#1488]
Version 1.75

So last night was playing on my Single Player world, everything has been going fine so far, computer is easily enough for the game, ram usage has been fine, no new updates for Minecraft, or any expected things that would effect it. But suddenly now no matter what I do when I'm on, I'll get this period delay. The best way I can see it is through things such as turning on my Extreme Reactor, as the power increases over time, it only increases in big chunks about 3 seconds apart. Same thing happens with AE2 molecular assemblers, or any machines. It will be at the same chunked time, and its really bothering. 
I've messed with BetterFps, and on a duplicated save tried using optifine, and messed with different settings, but nothing's been working.

*It won't be a Twitch ram usage, I allow the game up to 8448 Mb, and I've never seen it spike past 6000.

**Comment by NillerMedDild** [comment]
I'll have to guess at the issue since you didn't provide logs, but old Java is the cause of this about 90% of the time.
```
You appear to be using outdated Java. This is often caused by Twitch defaulting to an older version than you have available. Follow these steps to update.

* Make sure you have the latest 64-bit Java installed
    https://www.java.com/en/download/manual.jsp Windows Offline (64-bit) is the one you need
* Go to the Twitch Minecraft settings
* Add `-version:1.8+` to the Additional Arguments```
