### ISSUE TITLE
Tinkers construct - Star metal

### ISSUE THREAD

**Issue by Bolsward1** [NillerMedDild/Enigmatica2Expert#1489]
**Modpack version**
1.75

**Issue**
It is not possible to make to make Tinker Construct tools from star metal (Astral sorcery). The smelter converts the Astral sorcery star metal into 'Astral star metal' from JAOPCA which can not be used to cast tools with. 

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by NillerMedDild** [comment]
I didn't even know Star Metal tools existed O_O
