### ISSUE TITLE
Modular machine to mix fluids

### ISSUE THREAD

**Issue by DragonmasterDJ** [NillerMedDild/Enigmatica2Expert#149]
Maybe could there be a added machine which can be used to make fluids like Primal mana for a slightly cheaper price. though the blueprint and/or added blocks would be more expensive, since primal mana is mid/late game. so to automate its process would help more late- players

**Comment by NillerMedDild** [comment]
I'll think about it, it's a pretty good idea :)

**Comment by NillerMedDild** [comment]
To be honest, I don't want to make Primal Mana cheaper.
