### ISSUE TITLE
Quests just do not work because the claim button just never works and the dialogue for completing a quest keeps looping

### ISSUE THREAD

**Issue by Papasalt** [NillerMedDild/Enigmatica2Expert#1490]
**Modpack version**
1.75

**Issue**
When I finish a quest and I go to claim it it does say "1/1 quests completed" but the claim button doesn't work. What else happens is that the dialogue saying that I finished a quest keeps looping on my screen. My suspicion is that for some reasons, the mod keeps checking for the item since when I drop the item needed for the quest, the dialogue stops. But I still can't claim the reward(s)

**Comment by NillerMedDild** [comment]
Sorry for the late response, I didn't see the notification.

Are you in a Better Questing party, and is it on a server or singleplayer?

**Comment by Papasalt** [comment]
I am in a party and I am playing on a LAN server.
Using the /bq_admin complete command sometimes lets me claim the rewards.

**Comment by NillerMedDild** [comment]
This should be fixed in 1.76, could you please verify that? :)
