### ISSUE TITLE
Different behaviors when crushing/pulverising Charged Certus Quartz

### ISSUE THREAD

**Issue by fabrossmann** [NillerMedDild/Enigmatica2Expert#1492]
**Modpack version**
1.75

**Issue**
There are different outputs when crushing/pulverising Charged Certus Quartz. Either it's the JAPOCA Dust or plain Certus Dust. 

![enigmatica2_bug](https://user-images.githubusercontent.com/6189957/72909259-03889600-3d37-11ea-8a7d-8302510d1ce9.png)
![image](https://user-images.githubusercontent.com/6189957/72909307-18652980-3d37-11ea-97d9-78d4439550e5.png)
![image](https://user-images.githubusercontent.com/6189957/72909324-2024ce00-3d37-11ea-9f8e-4be189216d04.png)
![image](https://user-images.githubusercontent.com/6189957/72909373-32067100-3d37-11ea-881a-88adaad14729.png)
![image](https://user-images.githubusercontent.com/6189957/72909617-96c1cb80-3d37-11ea-8c1b-e333653e8e1c.png)

**Comment by Frikkle** [comment]
Personally, I don't know if this was intentional or not, but I wouldn't be surprised if different ways of processing things result in different kinds of resulting product. But this is one for Niller to shine his light on.

**Comment by NillerMedDild** [comment]
Thanks for the report, this is a bug :)
