### ISSUE TITLE
IE Cyclic Duplication Glitch

### ISSUE THREAD

**Issue by RockRoller01** [NillerMedDild/Enigmatica2Expert#1493]
**Modpack version**
1.75

**Issue**
Moving immersive engineering multiblock structures with the cyclic piston scepter makes the clicked block of the structure move, it however is a transparent block without texture and the mutliblock stays functional. When the block gets moved, the block itself gets dropped once, meaning you can move the block around as much as you want and for every time you move it you get a dupe of it.
Only tried this with Alloy Kiln, Coke Oven and Blast Furnace.

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
To be honest this issue is so specific that I don't really wanna attempt to fix it. The Piston Scepter has a lot of issues, and moving multiblocks like that is generally a bad idea.
