### ISSUE TITLE
PlusTiC's Brown Magic tool trait desyncs player state when going between dimensions.

### ISSUE THREAD

**Issue by Zarklord** [NillerMedDild/Enigmatica2Expert#1494]
**Modpack version**
1.7.5
(also using the preview build of optifine, but it happened even before I was using that)

**Issue**
Using any tool with the Brown Magic trait to travel between dimensions desyncs the player state,
this means any hearts you have earned from Spice of Life: Carrot Edition are (visually) removed(this always happens), attempting to sleep in a bed will force you to use /kickme in order to leave the bed(regardless of the sleep charm)(this only happens sometimes), and Actually Additions medium(and I would assume large, but I haven't been able to craft those to test yet) storage crates, the arrow buttons to go to the different pages of storage fail to work(this only happens sometimes), and probably a bunch of other stuff I don't know about.
Swapping dimensions normally removes the desync if it exists.

To reproduce, simply travel to any dimension, and use brown magic to warp to a different dimension, upon warping to the other dimension, all the above things will stop working properly.

**Logs**
here is the logfile, but I have no idea if anything helpful is in there: [latest.log](https://privatebin.net/?8e1a7fdc7ca0c3ba#FYqNH95p1cjQPJBpWpuHnhopqW6iTARfkJ4ngNvgiYbq) (this uses privatebin, since the size is too large for non pro users of pastebin.)

**Comment by NillerMedDild** [comment]
Thanks for the report, I've relayed it :)

**Comment by Zarklord** [comment]
This also seems to happen with draconic evolution's dislocator.

**Comment by NillerMedDild** [comment]
I believe that has been fixed: https://github.com/brandon3055/Draconic-Evolution/issues/1368
