### ISSUE TITLE
JAOPCA cobalt and ardite ore dusts don't properly compact in compacting drawers

### ISSUE THREAD

**Issue by Zarklord** [NillerMedDild/Enigmatica2Expert#1497]
**Modpack version**
1.7.5, with optifine

**Issue**
putting in tiny piles of cobalt/ardite dust should result in them compacting into cobalt/ardite ore dust, all other tiny piles of ore dust(from jaopca, the ic2 ones behave completely differently) properly compact in storage drawers.
this is a twofold problem, the reason why cobalt/ardite dust don't compact properly is that a recipe for small piles(4 for a dust) and tiny piles(9 for a dust) are both craftable depending on where you place the dust in the crafting recipe, all other jaopca dusts, while having both crafting recipes, the tiny piles take precedence over small piles recipe, and the small dust is uncraftable.
you can fix this by setting custom rules for compacting drawers for the jaopca dusts(as far as I can tell, nothing uses the small piles of ore dust) to correctly convert them, and allow crafting of the small piles of ore dust, OR, you can just straight up remove the small piles of ore dust crafting recipes which would also fix it.

EDIT: if you chose to add the compacting rules, they would be these:
```
exnihilocreatio:item_ore_cobalt:2, jaopca:item_dusttinycobalt, 9
exnihilocreatio:item_ore_ardite:2, jaopca:item_dusttinyardite, 9
```

**Comment by NillerMedDild** [comment]
Thanks for the report, and the solution :D

**Comment by Zarklord** [comment]
also applies to thorium and boron, here are the compacting rules for those:
```
nuclearcraft:dust:3, jaopca:item_dusttinythorium, 9
nuclearcraft:dust:5, jaopca:item_dusttinyboron, 9
```

**Comment by NillerMedDild** [comment]
It doesn't seem to work for any Small or Tiny pile, at all. I've tried about 20 different ones now, none of them can be compacted in Compacting Drawers.

**Comment by Zarklord** [comment]
Osmium, Nickel, Platinum, Aluminum all properly compact, 
sidepoint: just to be clear, small piles and tiny piles working at the same time is an impossibility for 1.12 storage drawers, but since nothing uses small piles, they don't need to be the ones that work with compacting drawers.
The ones that properly compact, you can see both the tiny(9x) and small(4x) crafting recipes are identical, with the tiny recipe showing up first.

**Comment by NillerMedDild** [comment]
This should be fixed by the next update :)

**Comment by NillerMedDild** [comment]
Would you mind checking if the issue still exists in 1.77? :)
Uploading it now.

**Comment by Zarklord** [comment]
> Would you mind checking if the issue still exists in 1.77? :)
> Uploading it now.

I'll test it as soon as I can.
