### ISSUE TITLE
Tinker's tool with diamond upgrade doesn't change mining level after using sharpening kit.

### ISSUE THREAD

**Issue by Snowgleb** [NillerMedDild/Enigmatica2Expert#1498]
**Modpack version**
1.7.5

**Issue**
Tinker's tool with diamond upgrade  does  not change mining level  after using sharpening kit.

(I had wooden + stone pickaxe and I  upgraded to copper pickaxe head, applied diamond (that I  found  while exploring) then used quartz  sharpening kit, and the mining level was still copper.

**Comment by Snowgleb** [comment]
Edit: Seems like  the level is 1 step down. as using iron sharpening kit will make it certus mining level

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
This is a side-effect of me overhauling mining levels, and it doesn't look like it can be fixed without a rewrite of the Tinkers API, so I'm afraid you'll have to live with it :)
