### ISSUE TITLE
Tinkers Complement Chisel deletes blocks if its max durability is lower than the stack size

### ISSUE THREAD

**Issue by Zarklord** [NillerMedDild/Enigmatica2Expert#1499]
**Modpack version**
1.7.5, with optifine

**Issue**
Make a paper chisel, try to chisel a stack of blocks, watch as you end up with only 13 blocks after the fact.

**Comment by NillerMedDild** [comment]
Thanks for the report, we know, it's a duplicate of #1430

**Comment by Zarklord** [comment]
Just so its clear, this isn't duplicating blocks, its straight up deleting them, even with reinforced 4(80% chance to not lose durability), it still capped at 13 blocks(which is what a paper chisels durability is), even though the chisel didn't break...
