### ISSUE TITLE
Fake Player recipe hardcore-ified

### ISSUE THREAD

**Issue by DragonmasterDJ** [NillerMedDild/Enigmatica2Expert#150]
The mechanical player is a extremely useful tool. it can be used to automate the making of astral sorcery resonating gems, and automating the refinement of ores via the starlight infuser. and it can be used early game to automate the making of liquid starlight. so it makes the process of astral scorcery really easy

**Comment by NillerMedDild** [comment]
Good point, I'll make the recipes harder.

**Comment by DragonmasterDJ** [comment]
@NillerMedDild 
Oh yes! and Im pretty sure as well as extra util 2's mechanical player. Cyclic has its own fake player If I am remembering correctly. so maybe a recipe could be made to turn 1 mechanical player into cyclics version if players prefer it. and vice versa.

**Comment by NillerMedDild** [comment]
Hopefully I'll find all of them ^^
