### ISSUE TITLE
RFTools Teleporters won't keep the Dial

### ISSUE THREAD

**Issue by MS21GH** [NillerMedDild/Enigmatica2Expert#1501]
**Modpack version**
1.75

**Issue**
Dialing a Teleporter, going through the other side, then dialing the original one and going back to it *will* remove the Dial and everytime someone wants to go through, the Teleporter will have to be re-dialed each single time; both teleporters are Chunkloaded through FTBUtil

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
I'm afraid I can't reproduce this, so I can't do much.
