### ISSUE TITLE
World not showing up in world list in game

### ISSUE THREAD

**Issue by pjr2005** [NillerMedDild/Enigmatica2Expert#1502]
**Modpack version**
1.73
**Issue**
my computer shutdown wrong and couldn't startup and then it did and the level was open when it shut off and now it wont show up in in 
game world list and it shows up in the games files
[logs.zip](https://github.com/NillerMedDild/Enigmatica2Expert/files/4112597/logs.zip)

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by Lgmrszd** [comment]
1.12.2 is version of Minecraft, not modpack. Current version is 1.75, yours should be lesser since you have logs from December. Although I don't think modpack version matters in this case..
