### ISSUE TITLE
Pink Slime is craftable using normal slime

### ISSUE THREAD

**Issue by fabrossmann** [NillerMedDild/Enigmatica2Expert#1503]
**Modpack version**
1,75

**Issue**
Hey I just found out, you can create pink slime using vanilla slime blocks in a compacting drawer.
![image](https://user-images.githubusercontent.com/6189957/73188807-b71ccc00-4123-11ea-93f9-9c046092509c.png)

**Comment by NillerMedDild** [comment]
Working as intended :)
