### ISSUE TITLE
Sharpening Kit Fortified Text not being applied when Head has higher harvest level

### ISSUE THREAD

**Issue by CornOnTheJayCob** [NillerMedDild/Enigmatica2Expert#1507]
**Modpack version**
1.76a

**Issue**
A block of black of black iron is labeled as being able to be harvested by a Supremium level pickaxe. However, I am holding a Tinkers' Construct pickaxe with a Supremium head on it, but it says it is not harvestable. I did not fully attempt to mine it, however I did mine it a bit, and the time it would take to fully mine the block seems to reflect the fact that it is not harvestable with my pickaxe.
![Screenshot (16)](https://user-images.githubusercontent.com/60523214/73569747-0707d580-4439-11ea-81d7-71fd2cf66472.png)

**Comment by NillerMedDild** [comment]
Do you happen to have a sharpening kit or diamond on your pickaxe?

**Comment by CornOnTheJayCob** [comment]
Yes for the sharpening kit. The pickaxe I have is from the very beginning of the game, I just kept replacing the parts or using sharpening kits. No for the diamond though.

**Comment by NillerMedDild** [comment]
Which sharpening kit is it? :)

**Comment by CornOnTheJayCob** [comment]
It was multiple. It was obsidian, manyullyn, osgloglas, and enderium.

**Comment by NillerMedDild** [comment]
The mining level is equal to that of your sharpening kit.

**Comment by CornOnTheJayCob** [comment]
What? My pickaxe says that it's mining level is Supremium. The block of black iron says that you need a Supremium level pickaxe to harvest it. However, I am not able to harvest this block. This is clearly not supposed to happen. How does a sharpening kit even matter in this situation, when they were applied previously, and have now been overwritten by the Supremium head? I cannot take a screenshot while I am holding shift to show you, but when I do, it shows that the the pickaxe is not able to mine the material. This is counter to the fact it should be able to based off of what it says the required material is and based off of the material my pickaxe is made out of.

**Comment by NillerMedDild** [comment]
The purpose of a Sharpening Kit is to override the harvest level of a tool.

**Comment by CornOnTheJayCob** [comment]
Yes, but when you apply a new head after you have applied a sharpening kit, if the new head is above the level of the sharpening kit, the sharpening kit gets overridden itself.

**Comment by NillerMedDild** [comment]
No, it does not and should not. The purpose of a Sharpening Kit is to override the harvest level of a tool. Not override unless the head has a higher material.

**Comment by CornOnTheJayCob** [comment]
Then why would a pickaxe with a wooden head that has been upgrade with a copper kit say "Fortified (Copper)" when my Supremium pickaxe has no Fortified modifier

**Comment by CornOnTheJayCob** [comment]
Also,I just went into a creative world and tried it with a Supremium pickaxe directly from Mystical Agriculture, while in gamemode 0. The speed of mining was what you would expect if you were able to mine the block, however the block of iron was not dropped, and instead was voided.

**Comment by NillerMedDild** [comment]
Any tool that has been modified with a Sharpening Kit should say Fortified.

**Comment by NillerMedDild** [comment]
That is also intended, to further discourage you from using "vanilla" style tools.

**Comment by Discomanco** [comment]
You can definitely see the Sharpening Kit in the picture. It has an Enderium Sharpening Kit applied, as implied by the dark green tips of the Pickaxe.  
I also can't replicate this the issue of "Fortified" not being shown. Gave myself an Osgloglas Pickaxe (full Osgloglas), Mining Level 9. Applied Enderium Sharpening Kit, Mining Level 10. Changed Pickaxe Head for Supremium Head (lvl 12), still Mining Level 10, as intended. Fortified text is still being shown
![image](https://user-images.githubusercontent.com/4707702/73579885-0fd1c900-4484-11ea-854a-d5b7825bee27.png)
