### ISSUE TITLE
Sheetmetal Chute from IE broken

### ISSUE THREAD

**Issue by Lgmrszd** [NillerMedDild/Enigmatica2Expert#1509]
**Modpack version**
1.76a

**Issue**
Seems to happen on server only
When placing Sheetmetal Chute from Immersive Engineering, it visually appears as placed, however, it places conveyor belt with broken NBT data (after re-logging it shows broken block), and chute stays in your inventory (also causing inventory desync until relogin). Broken conveyor belt can be mined back.
This issue is known and listed in IE repository (https://github.com/BluSunrize/ImmersiveEngineering/issues/3611), posting it here in case if someone also encounters this.

**Logs**
In the linked issue

**Comment by NillerMedDild** [comment]
Thanks a lot for rejaying :)

**Comment by Lgmrszd** [comment]
Well, this got fixed month ago, I guess.
