### ISSUE TITLE
Performance issues?

### ISSUE THREAD

**Issue by HerrHebel** [NillerMedDild/Enigmatica2Expert#1513]
**Modpack version**
1.76a

**Issue**
Dunno if its just me but after not playing in January, I updated the pack from 1.74 to 1.76a and instead of like 70ish fps in my base I have ~50 with drops, and my CPU sweats like crazy at 90-100%. I know that it would finally happen cuz I'm stupid and I like building bases vertically instead of horizontally, but it happened for no reason. And also a lot of latency in block updates (not sure if thats the proper term) occur now, after placing a block the texture shows up only after another block in its proximity is broken. Even when putting disks in ME storage drives does not show the proper texture that they're inserted, they show up only after breaking a block. And I haven't done anything in the place of occurrence after I updated the pack, it just started happening.

My specs are as follows:
8600K at stock 
GTX 1080
16GB@3200mhz RAM, 9GB allocated to MC, when inspecting debug it uses at most 7GB in most demanding places (those are just spikes tho, apart from them it sit at quite steady 5-6GB usage)

Anyone reported this? Or is something just wrong with my save? Any additional info I can provide?

**Comment by NillerMedDild** [comment]
Thanks for the report - We've not heard of performance issues with 1.76a, could you please provide your latest.log file? :)

**Comment by HerrHebel** [comment]
Here ya go. 
[latest.log](https://github.com/NillerMedDild/Enigmatica2Expert/files/4161689/latest.log)

As I've mentioned - part of the lag is on my part cuz of the base layout. And I've also used astral cave illuminators, so there's probably around a billion pointless lightsources in every hole under me, and as i've read they can cause some serious performance issues.

**Comment by NillerMedDild** [comment]
You appear to be using outdated Java. This is often caused by Twitch defaulting to an older version than you have available. Follow these steps to update.

* Make sure you have the latest 64-bit Java installed
    https://www.java.com/en/download/manual.jsp Windows Offline (64-bit) is the one you need
* Go to the Twitch Minecraft settings
* Add `-version:1.8+` to the Additional Arguments

This is a very common cause of lag, so I bet that'll do wonders - Please let me know whether it helps or not.

**Comment by HerrHebel** [comment]
Yep, it made it better, got like a 10+ fps more on averag in the laggy space, and the not updating textures dont happen so frequently. Thanks for the help man ;)

And I dont know where else to express this but I gotta say it. Your support and how fast you answer to issues is insane, I have never experienced something like this. This pack is the best I have ever played in modded MC (I've been using mods since 1.2.5 as far as I can remember, maybe even few versions earlier but thats the oldest one stuck in my head) both in terms of performance and how well the quest progression is built and how smartly gates to mods are set. I'm at 170h of playtime and I'm having a blast every minute of it. You may be sure, that when E4:E comes out, I'll be on board both playing it and reporting all the problems I encounter to help you make it at least as good as E2:E is :D Great work man, keep it up!

**Comment by NillerMedDild** [comment]
Thank you :D I really appreciate it.
