### ISSUE TITLE
Mechanical user problem

### ISSUE THREAD

**Issue by HerrHebel** [NillerMedDild/Enigmatica2Expert#1514]
**Modpack version**
1.76a

**Issue**
I've set up a farm for flowers from botania using mechanical users. 16 of them plant petals, 16 fertilize them and gatherer from IF with leaf shearing upgrade collects them. The problem is that the user forgets its redstone behavior every time I load the save. As shown on pictures the emitters are set to emit redstone when below 500, there is 500 in system so they don't turn on, but the user depite being set to "redstone on" still plants stuff. After clicking to "redstone off" and back to "redstone on" it behaves itself as intened. Dunno if its a pack or mod issue or I'm just doing something wrong.

https://imgur.com/a/HSYY1Si

**Comment by NillerMedDild** [comment]
Looks like your Mechanical Users are being powered by adjacent Emitters - That might be the issue :)

**Comment by HerrHebel** [comment]
I'll try to break every other user and emitter and see if it fixes it, I'll come back with info on Friday/Saturday probably.
