### ISSUE TITLE
Spam about removal without registration and massive tps drop

### ISSUE THREAD

**Issue by jinkhya** [NillerMedDild/Enigmatica2Expert#1518]
**Modpack version**
1.74

**Issue**
Hello, We're having an issue with somebody's base built in space. Everytime he logs off the base doesn't seem to unload properly and tps tanks to the ground. If I go to his base with nobody else on the server tps is at 20. Then when I log off, or go to server's spawn, tps drops to 1-3, spams in console and eventually crashes.

**Logs**
Here is what is spamming in console :
 https://paste.gg/p/anonymous/5c33374424874ca9ada204b6d89790b9
log : 
https://paste.gg/p/anonymous/8b655a5dd3334d1e9228fa732bbe4ec0
crash log : 
https://paste.gg/p/anonymous/5a14bea4c67a44209a6e0f6895016fc9

**Comment by NillerMedDild** [comment]
Thanks for the report - Could you please remove SpongeForge and see if that fixes the issue?

**Comment by jinkhya** [comment]
I can try it without, I need to make a copy of the server first. I'll get back to you

**Comment by jinkhya** [comment]
So erm... this is awkward. I'd love to check if it still does it without sponge however if I remove sponge, DIM-2 seems to have reset. The base is gone ...

With sponge, I found another player's base in space and it unloaded fine (couple spam messages looking the same but it didn't drop TPS and the base unloaded properly.) I suppose they have something breaking it somewhere and the search must begin :woman_shrugging:

**Comment by NillerMedDild** [comment]
I'm guessing the mix of SpongeForge, IC2, Mekanism and machines acting as chunkloaders are the combined cause of this issue.
If you can reproduce it without SpongeForge (once you find the base again :P) I'll gladly investigate further.

**Comment by jinkhya** [comment]
Haha yeah I'm not quite sure why the dim is resetting to be honest. Removing sponge shouldn't cause that.
Anyway thanks Niller! I'll close the issue for now if I can reproduce a similar issue without sponge I'll come back to you.
