### ISSUE TITLE
Cleaning up AS resplendant prism config

### ISSUE THREAD

**Issue by MorganSimic** [NillerMedDild/Enigmatica2Expert#1519]
**Modpack version**
1.76a

**Issue**
The enchantment config for the Resplendant Prism from AS should be cleaned up. It's the thing that can boost enchants on a player. But there is a lot of questionable stuff in the config.
Imo, stuff like sieve enchants should be removed entirely since they do nothing at all on the prism. The XU boomerang enchants need to be toned way down, if not removed. I feel it's nice to have some bad enchants to make it harder to get the really good stuff but the way it is now it is pure sadness.
I think i will make a PR for that change in case this is a desirable change.

**Comment by NillerMedDild** [comment]
I'm pretty sure that's a desirable change!
I have no idea what the Resplendant Prism is though ^^'

**Comment by MorganSimic** [comment]
It's a bauble that boost existing enchants or does give new enchants. The traits on the prism are random and can be rerolled for a price. But you get way to much utter garbage as it is, so it's really frustrating if you actually want to use it.
Now i only need to figure out again how to do a PR. It's been a while and i forget everything :D

**Comment by MorganSimic** [comment]
PR is up, but i didn't merge it yet because i'm not sure if everything is in order. I still don't know my way around Git.

**Comment by NillerMedDild** [comment]
Good work, thanks :D
