### ISSUE TITLE
Recipes in Slice'N'Splice make it hard to automate

### ISSUE THREAD

**Issue by codeka** [NillerMedDild/Enigmatica2Expert#152]
#### Issue Description
The Slice'N'Splice is usually pretty smart in that if you try to pipe items in, it'll only place items in slots that are valid for the recipes it has. But there's two recipes in the pack which put silicon in different places:

![2018-07-10_12 09 29](https://user-images.githubusercontent.com/1569910/42487207-e7fb8746-843a-11e8-8c84-e62b8be24560.png)

![2018-07-10_12 09 35](https://user-images.githubusercontent.com/1569910/42487217-f32c1478-843a-11e8-8bf3-6c20f7c96cbf.png)

If I try to pipe items in to make a Skeletal Contractor, it'll put the silicon in the bottom-left, because that's the place it goes for the Z-Logic controller.

![2018-07-10_12 17 53](https://user-images.githubusercontent.com/1569910/42487301-5b042b58-843b-11e8-967b-3c1a6ed55141.png)

I have to manually move the silicon to the bottom-middle for the item to craft.

Looks like this was reported in EnderIO a while ago (https://github.com/SleepyTrousers/EnderIO/issues/3852) but I think a simple fix would be to just change the recipe for the Skeletal Contractor and Guardian Diode to take something other than a silicon piece in the bottom-middle (maybe a capacitor?).

#### Modpack version (Do not use "latest")
1.32

**Comment by NillerMedDild** [comment]
Sounds like a good fix, thank you for the report and thorough investigation :)

**Comment by NillerMedDild** [comment]
I ended up moving the Silicon to the sides.
