### ISSUE TITLE
Macerator should be able to process all the same ores that other mods can

### ISSUE THREAD

**Issue by aaronhowser1** [NillerMedDild/Enigmatica2Expert#1521]
**Modpack version**
1.76a

**Issue**
Some ores, like Black Quartz, can be processed by the Grinder, SAG Mill, Crusher, etc, but *not* the Macerator. I feel like this just makes players not go the IC2 path, which isn't great.

**Comment by NillerMedDild** [comment]
Agreed! Do you know of any other ores that cannot be processed by the Macerator?

**Comment by aaronhowser1** [comment]
Coal
Lapis Lazuli
Diamond
Redstone
Emerald
Nether Quartz
Aquamarine
Certus Quartz
Charged Certus Quartz
all of BoP's ores
Oil Sand
Oil Shale
Destabalized Redstone OreResonant End Stone, and Dilithium

**Comment by NillerMedDild** [comment]
Oh boy, I got work to do. Thanks for the list, much appreciated!
