### ISSUE TITLE
The Squeezer has multiple recipes for the same items, giving different amounts

### ISSUE THREAD

**Issue by aaronhowser1** [NillerMedDild/Enigmatica2Expert#1522]
**Modpack version**
1.76a

**Issue**
![image](https://user-images.githubusercontent.com/15698722/74105112-9ccdef80-4b20-11ea-988a-b4f029f72612.png)
![image](https://user-images.githubusercontent.com/15698722/74105114-a0617680-4b20-11ea-87b4-3bf0c58d1cd6.png)
This happens with some other items too, like Chili Peppers

**Comment by NillerMedDild** [comment]
I'll get that fixed, thanks!
