### ISSUE TITLE
Two types of Amber Ore generate

### ISSUE THREAD

**Issue by aaronhowser1** [NillerMedDild/Enigmatica2Expert#1523]
**Modpack version**
1.76a

**Issue**
Amber from both BoP and Thaumcraft generate in the world. I suggest disabling BoP's, because it doesn't drop Preserved Curiosities, and then maybe increasing Thaumcraft's to compensate for the difference.

**Comment by aaronhowser1** [comment]
Also, apparently BoP's Amber is hidden in JEI? It's a bit weird that BoP's spawn more (at least in my experience. According to JER, Amber Bearing Stone is more common, which isn't what I've observed).

**Comment by NillerMedDild** [comment]
I'd love to, but I don't know how to disable BoP ores to be honest. 

They only spawn in specific biomes, that's most likely why the Thaumcraft Amber has higher generation in JER.

**Comment by aaronhowser1** [comment]
lol I looked it up and found this
![image](https://user-images.githubusercontent.com/15698722/74107263-a3199700-4b33-11ea-8163-d4995bb8e790.png)
Guess there's no way, which is very odd

**Comment by Omegapsychosis** [comment]
I believe disabling them is for all BOP gem spawns. 

Could you disable them by default and then add custom ore spawn JSON files using COFH World and then just omit re-adding the BOP Amber Ore to worldgen?

Could work but it may be more convoluted a solution than needs to be.

**Comment by NillerMedDild** [comment]
There is one way of doing it by default, but that will override all other generator-settings used, which I think is worse than having duplicate ores :/
https://biomesoplenty.fandom.com/wiki/Configuration
