### ISSUE TITLE
Forestry Farm quest should link to the Gamepedia wiki, not ftbwiki

### ISSUE THREAD

**Issue by aaronhowser1** [NillerMedDild/Enigmatica2Expert#1524]
**Modpack version**
1.76a

**Issue**
![](https://cdn.discordapp.com/attachments/166630061217153024/676113328874979340/unknown.png)
ftbwiki.org is extremely old and outdated. That specific page hasn't been edited since freaking 2017.
The Gamepedia wiki is up to date: https://ftb.gamepedia.com/Multifarm

**Comment by aaronhowser1** [comment]
Sorry for making so many issues by the way. I'm loving the pack so far :D

**Comment by NillerMedDild** [comment]
Haha, no worries, I appreciate it :D
