### ISSUE TITLE
Basic Fluiducts have a normal recipe

### ISSUE THREAD

**Issue by aaronhowser1** [NillerMedDild/Enigmatica2Expert#1525]
**Modpack version**
1.76a

**Issue**
Regular non-opaque, non-hardened Fluiducts only need 2 Copper Ingots and 1 regular Glass. Seeing as how the Opaque ones need Plates and a Network Cable, that's probably not intended.

**Comment by NillerMedDild** [comment]
It is actually intended, it's to incentivise using lag-free cabling :P
When I made the recipe I thought non-opaque ducts had an impact on server TPS, but seeing as that's... not true, I'll change the recipe.
Thanks again!
