### ISSUE TITLE
Advanced Carpenter consumes 5000mb of water [Bug(?)/Question]

### ISSUE THREAD

**Issue by KleinGrrmpf** [NillerMedDild/Enigmatica2Expert#1527]
**Modpack version**
1.76a

**Issue**
I don't know if this intended or not, but:
When using the advanced carpenter, normally the fluid needed for one crafting process is half of the fluid needed for the same item in a normal carpenter. But for all the circuit boards the amount of water needed in the advanced carpenter is 5000mb. This may be intended, but as all circuit boards take 1000mb of water in the normal carpenter, it doesn't appear logical to me, hence this issue. This may also just be a typo, where you just accidentally added on  "0" too much. Anyways, great pack :)

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by NillerMedDild** [comment]
Iirc my reasoning behind the added water is that the "large-scale" fabrication of circuits would need more cooling.

Thanks for reporting anyway! :D

**Comment by KleinGrrmpf** [comment]
Ok ^^
