### ISSUE TITLE
SoL: New foods don't always register

### ISSUE THREAD

**Issue by Carionis** [NillerMedDild/Enigmatica2Expert#1528]
**Modpack version**
1.76a - Singleplayer

**Issue**
After some time (sometimes even after 10 minutes) playing, eating new foods does't give the particle effect and hearts don't progress. However, in the inventory view, the foods count as "already eaten". After closing and restarting, the foods show as "not yet eaten" again.

**Comment by Lgmrszd** [comment]
What usually happens in-game before this situation occurs? Have you teleported or traveled between dimensions? There are some cases when user state got de-synced, like using PlusTiC's Brown Magic (https://github.com/NillerMedDild/Enigmatica2Expert/issues/1494). This is just guess but maybe this is the source of the issue.

**Comment by Carionis** [comment]
Death, Dragon Roar (Weakness) or travel to the nether...

**Comment by NillerMedDild** [comment]
No you shouldn't have to, it sounds like a side effect of the issue @Lgmrszd mentioned. I don't think we'll be able to resolve this I'm afraid.

**Comment by Carionis** [comment]
Suboptimal, but since it's hard to pin down, I get where you're coming from. So basically hoping that fixing #1494 fixes this. Thanks anyways for looking into it.

**Comment by NillerMedDild** [comment]
It's not so much hard to pin down, it's just extremely wide spread. A ton of different mechanics can cause the desync, including vanilla dimension changes. 

But yeah it does suck, and I've attempted to fix it several times with nothing to show for it :(

**Comment by Carionis** [comment]
I've read somewhere else (SoL bugs or something, I can't quite remember) that player state desyncing when travelling between dimensions might be a 1.12.2 issue of vanilla. So that's not really something you will fix easily, I guess. Kudos to you for trying, though!

**Comment by purxiz** [comment]
I don't mean to necro this, but this happened to me without ever travelling between dimensions, is there any fix for that?

**Comment by NillerMedDild** [comment]
I'm afraid not.
