### ISSUE TITLE
EnderIO decoration blocks far too expensive

### ISSUE THREAD

**Issue by theboo** [NillerMedDild/Enigmatica2Expert#1531]
**Modpack version**
1.74

**Issue**
Just want to point out that the enderio "decoration blocks" are EXTREMELY expensive for what they do, requiring industrial machine chassis to make. Might think about making them a bit cheaper similar to how the paint machine is much cheaper. Seems to be a bit much for decoration. One suggestion would be to change the recipe for "machine parts" as they are only used for decoration blocks and block detectors. 

I noticed this when attempting to make the invisible decoration block.

**Comment by NillerMedDild** [comment]
Could you supply screenshots of some/any of the recipes you would like changed please? :)

**Comment by theboo** [comment]
![2020-02-13_13 46 48](https://user-images.githubusercontent.com/3585761/74481317-5b627a80-4e67-11ea-91a3-806f4d728f48.png)

i think if u made this take like a mekanism steel casing instead it would be much more reasonable. They are only used for EIO block detectors and EIO decoration blocks

**Comment by NillerMedDild** [comment]
Thanks, I'll look into it :)
