### ISSUE TITLE
16384k Storage Cell recipe uses diamonds instead of diamond chests

### ISSUE THREAD

**Issue by KleinGrrmpf** [NillerMedDild/Enigmatica2Expert#1532]
**Modpack version**
1.76a

**Issue**
Again, I don't know if this is intended, but the recipe for the 16384k Storage Cell uses diamonds whereas all the other Components with Advanced Storage Housings and the recipe for the Advanced Storage Housing itself use diamond chests.

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by NillerMedDild** [comment]
Sounds like a bug to me, thanks for the report :)
