### ISSUE TITLE
Missing loot in Ice&Fire chests after pack update

### ISSUE THREAD

**Issue by XarenHypr** [NillerMedDild/Enigmatica2Expert#1533]
**Modpack version**
1.76a

**Issue**
After updating the pack from 1.58 to 1.76a (long hiatus, RL reasons), and exploring in my existing world, I have been finding that all unlooted dragon hoard chests (both surface and lair) no longer have any loot, every chest is empty.  This is true for those in chunks I had already generated, as well as those that I generated afterwards for a test.  The mobs and gold/silver piles are being created properly.  Is there a fix for this, aside from restarting my world (which I'd rather not do, as I had just started preparations for space)?

**Comment by NillerMedDild** [comment]
I'm afraid there's nothing we can do about that. You can cheat the chests in :)

**Comment by XarenHypr** [comment]
Understood, how would I go about doing that?  Please forgive the question, but I am not sure how to cheat in an I&F chest with random contents :(

**Comment by NillerMedDild** [comment]
Understandably, I'll get you the command this evening, I can't remember :P

**Comment by NillerMedDild** [comment]
`/setblock ~ ~ ~ minecraft:chest 1 0 {LootTable:"iceandfire:fire_dragon_female_cave"}`

**Comment by XarenHypr** [comment]
Thank you very much!  :)
