### ISSUE TITLE
IE's metal rod recipes are very weird

### ISSUE THREAD

**Issue by aaronhowser1** [NillerMedDild/Enigmatica2Expert#1534]
**Modpack version**
1.76a

**Issue**
I just crafted my first rod for the Manufactory, and the Aluminum Rod recipe through me completely off.
![image](https://user-images.githubusercontent.com/15698722/74617563-6fbaa780-50f3-11ea-92ce-a06989897d91.png)
I assumed it wouldn't use up the Redstone or Piston, kinda like recipes that use Water Buckets. But when I crafted it in a Crafting Station, I lost them! That means that *one* Aluminum Rod costs 10 Redstone, 36 Cobblestone, 3 Treated Wood, and an Iron Plate. That's insane.
I understand that there are alternate recipes for it, like IE and AR (which honestly is a bit overpowered; a piston plus three iron ingots for all the things that it does, WITH NO RF COST). I would suggest either making that recipe not use up those parts, or simply removing that recipe entirely. Also maybe adding a recipe for it using IC2, probably with the Metal Former.

**Comment by Zarklord** [comment]
This isn't an issue, this is making the recipe more expensive in the beginning, and after you have more infrastructure, the costs goes down.

**Comment by NillerMedDild** [comment]
Indeed, this is a an attempt to make the player use the AR press. I suppose removing the recipe and adding a tooltip would be better though.

**Comment by aaronhowser1** [comment]
In that case, I suggest making the AR press more expensive. A piston plus three iron ingots is arguably cheaper than a piston plus a block of redstone, and it works without RF which means you would never really need to use the IE one.

**Comment by NillerMedDild** [comment]
I know, and yet it remains largely unused - I want people to make it over the IE press, to try to automate new things.

**Comment by Discomanco** [comment]
The AR press even gives more rods per ingot than IE. But IE is just so much more convenient, and you already need multiple for wires, gears and plates
