### ISSUE TITLE
Some Quark Mobs Cannot Despawn (Changed their spawns, made their spawn eggs available through the Market)

### ISSUE THREAD

**Issue by NillerMedDild** [NillerMedDild/Enigmatica2Expert#1535]
Frogs & Hell woofs.
Add their spawn eggs to the market.
Make a global mob cap for those 2 entities with In Control

**Comment by Lgmrszd** [comment]
While changes to config already have been made (https://github.com/NillerMedDild/Enigmatica2Expert/pull/1540) in new release, changelog of [new release of Quark](https://www.curseforge.com/minecraft/mc-mods/quark/files/2889332) (1 day ago) says that foxhound and frogs spawn rate got fixed. If this is true then maybe those changes will be unnecessary in next modpack versions.

**Comment by NillerMedDild** [comment]
The issue isn't the spawnrate, the issue is that they don't despawn naturally. We've "fixed" it by setting a mob cap, meaning there can never be more than 20 frogs or fox hounds at a time. This at least makes the performance impact manageable.
