### ISSUE TITLE
Me-System eating items

### ISSUE THREAD

**Issue by peckozz** [NillerMedDild/Enigmatica2Expert#1536]
**Modpack version**
1.76a

**Issue**
Me-system doesn't show correct item/ items dissapear in the system.

I've had a few problems (mostly with machine frames but other items as well)
Happens on a server(multiplayer)

**Logs**
not applicable

**Comment by Lgmrszd** [comment]
Can confirm, happened with ME attached to storage drawers controller using storage bus, some items won't show up, had to reconnect

**Comment by NillerMedDild** [comment]
I need a lot more details in order to do anything about this. Latest.log from the server to begin with, and preferably screenshots of the entire setup, and what went missing.

But to be honest, I doubt I can do anything about this, as it sounds very general.

**Comment by peckozz** [comment]
Its mostly machine cases that dissapear i made 20 and from the 20 i could use 5 an hour later the other 15 were gone.

![setup](https://user-images.githubusercontent.com/22295471/75025756-0b556a80-549c-11ea-94f1-0d3cd5bdf9d4.PNG)

[2020-02-18-1.log](https://github.com/NillerMedDild/Enigmatica2Expert/files/4235504/2020-02-18-1.log)

**Comment by NillerMedDild** [comment]
thanks for the additional info, but I'm afraid everything looks normal in there.

**Comment by NillerMedDild** [comment]
I'm going to close this issue, as I don't see anything we can do with the available information. Feel free to add to the issue if you find more information.
