### ISSUE TITLE
Nutritional values for Canned Fruit Juice

### ISSUE THREAD

**Issue by Lystraeus** [NillerMedDild/Enigmatica2Expert#1538]
**Modpack version**
1.76a

**Issue**
No JEI for Forestry Can or Bottler recipes.

Also, canned Fruit Juice should be on the Spice of Life whitelist.

**Comment by NillerMedDild** [comment]
Bottler recipes are hidden on purpose, so is the Can and all of the filled variants. Filled fluid containers often cause lag when displayed in JEI.

I'll look into adding Nutritional values for Canned Fruit Juice.

**Comment by NillerMedDild** [comment]
I'm afraid I can't add Nutritional values to Canned Fruit Juice, as the item is made in a funky way.
