### ISSUE TITLE
IC2 Plutonium in Dragon Loot table

### ISSUE THREAD

**Issue by Lystraeus** [NillerMedDild/Enigmatica2Expert#1539]
**Modpack version**
1.76a

**Issue**
IC2 Plutonium in Dragon Loot table.

Nasty surprise for non-veteran IC2 players. Worse since NuclearCraft isotopes are holdable. E2E isn't a hardcore survival pack.

Breaks gravestone retrieval.

**Comment by NillerMedDild** [comment]
This is intended behaviour :)

To retrieve your grave, you can make a rubber suit, click the grave so it no longer force-inputs into original slots, and shift on the grave like normal.
