### ISSUE TITLE
I cant upgrade thermal expansion pulveriser.

### ISSUE THREAD

**Issue by zadiend12** [NillerMedDild/Enigmatica2Expert#154]
#### Issue Description
is it normal to not be able to upgrade pulveriser?
#### Modpack version (Do not use "latest")
1.1
#### Crash Report

[pastebin/gist/etc link here]

**Comment by Discomanco** [comment]
Sounds like this is meant for Skyblock ( https://github.com/Discomanco/Enigmatica2ExpertSkyblock/issues ).

But which item are you trying to use, and what tier is the pulverizer?
