### ISSUE TITLE
Game won't launch

### ISSUE THREAD

**Issue by Mushwoom** [NillerMedDild/Enigmatica2Expert#1542]
**Modpack version**
1.76a

**Issue**
Game crashes at startup after some time of loading. If I don't use the bundled java, then the game will crash immediately and won't show a crash report

**Logs**
https://pastebin.com/UHsiAcWG

**Comment by Discomanco** [comment]
You are indeed crashing due to the outdated Java.
If you crash while using your system Java, then it's either 32-bit or newer than Java 8.

You can find Java 8, 64-bit here: https://www.java.com/en/download/manual.jsp, by choosing the Offline Installer
