### ISSUE TITLE
This modpack requires a dependency that is missing or no longer available. Missing Addon ID: 235328

### ISSUE THREAD

**Issue by NauticalJoker82** [NillerMedDild/Enigmatica2Expert#1543]
**Modpack version**
1.76a
**Issue**
This modpack requires a dependency that is missing or no longer available. Missing Addon ID: 235328
![Annotation 2020-02-24 191727](https://user-images.githubusercontent.com/61431389/75183394-5e4c4d80-573a-11ea-99e5-c9d02b9116d5.png)

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by NillerMedDild** [comment]
Please try again in 30 minutes :P This is almost always a Twitch issue.
