### ISSUE TITLE
Additional health resets on dimension change

### ISSUE THREAD

**Issue by SevenChords** [NillerMedDild/Enigmatica2Expert#1546]
**Modpack version**
latest

**Issue**
whenever i change dimensions all my orange and yellow hearts get lost and i have to regen them, which costs me a lot of saturation after each travel, need to eat about 2 ploughman's lunch after every dimension change to get them all back up

**Comment by NillerMedDild** [comment]
Known and unresolved issue I'm afraid, we've reported it to the affected mods.
