### ISSUE TITLE
Dark armor.

### ISSUE THREAD

**Issue by zyeborg** [NillerMedDild/Enigmatica2Expert#1547]
**Modpack version**
1.76a

**Issue**
Dark steel armor set cant upgrades . fx from Empowerement 1 to Empowerement 2 .
or put jump on them :S

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
Yes it can, you need to use a Dark Steel Anvil and insert upgrades through that :)
