### ISSUE TITLE
Alabaster missing

### ISSUE THREAD

**Issue by PlazmaCaster** [NillerMedDild/Enigmatica2Expert#1548]
**Modpack version**
1.76a

Less of an issue and more just curious. I was looking at some materials for building and noticed that alabaster from "Environmental Materials" was there but couldn't be crafted nor could it be obtained from any of the void miners. Noticed it was also not in any of the configs for the void miners either. Was this intentional?

**Comment by Erebos3D** [comment]
White alabaster is craftable, but the light gray version is still unobtainable, as it was in normal E2: https://github.com/NillerMedDild/Enigmatica2/issues/222

Please also add the fix here.

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.
