### ISSUE TITLE
astral sorcery luminous crafting table not working

### ISSUE THREAD

**Issue by meow121325** [NillerMedDild/Enigmatica2Expert#1549]
**Modpack version**
1.76a
**Issue**
whenever i try to use the luminous crafting table even when its full of starlight it doesnt craft items in it i made sure i had all the right stuff i made sure i used the wand but it just doesnt craft
**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by NillerMedDild** [comment]
You must have crafted already one Luminous Crafting Table yourself to be able to use one, could that be your issue?

**Comment by meow121325** [comment]
oh didnt know that ok imma try that
