### ISSUE TITLE
Dark Steel Boots consume power from any RF containing item in inventory

### ISSUE THREAD

**Issue by MorganSimic** [NillerMedDild/Enigmatica2Expert#155]
#### Issue Description
EnderIOs Dark Steel Boots (possibly any Dark Steel Armor) with Empowered Upgrade draw power from any item in the inventory that contains RF. Not only capacitors but the Staff of Travel or even the PlusTiC Laser Gun. This is possibly an EnderIO issue but the EnderIO github said i should report to the modpack author first.

#### Modpack version (Do not use "latest")
Enigmatica 2 Expert 1.32
slightly modified with Constructs Armory added

**Comment by NillerMedDild** [comment]
I misinterpreted a config, fixed :)
