### ISSUE TITLE
Inventory bug

### ISSUE THREAD

**Issue by OperatorMater** [NillerMedDild/Enigmatica2Expert#1550]
**Modpack version**
1.76a

**Issue**
Items in inventory become bugged at seemingly random times where items like trying to plant seeds but they dont plant and disappear as if they had. Other issues found with the animal mod the feeding trough has had the same issue.

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by NillerMedDild** [comment]
We cannot do anything about this, it's simply too vague and general. It sounds like a client desync, relogging ought to fix it.

**Comment by OperatorMater** [comment]
Ok, thanks for getting back to me
