### ISSUE TITLE
Arcane Workbench apparently doesn't work in claimed chunks

### ISSUE THREAD

**Issue by aaronhowser1** [NillerMedDild/Enigmatica2Expert#1552]
**Modpack version**
1.76a

**Issue**
![image](https://user-images.githubusercontent.com/15698722/75615134-b9e55500-5b05-11ea-9d0b-595ae5f9a9e6.png)
This showed as having 0 available originally, but I found [this Reddit post](https://www.reddit.com/r/feedthebeast/comments/aq8x1e/enigmatica_2_expert_arcane_workbench_issue/) which said to unclaim the chunk and reload it. I have absolutely no idea what would cause this, but I don't see any existing issue about this

**Comment by NillerMedDild** [comment]
Huh, I knew about the issue but not the cause or fix :P 
Thanks for the report, I'll look into it.

**Comment by NillerMedDild** [comment]
I cannot reproduce this.
