### ISSUE TITLE
Compact Machines has regular recipes?

### ISSUE THREAD

**Issue by aaronhowser1** [NillerMedDild/Enigmatica2Expert#1554]
**Modpack version**
1.76a

**Issue**
Not sure if this is necessarily an issue, but I was very surprised to see Compact Machines uses regular recipes. I feel like something so powerful would be made a bit harder to craft in an expert mode modpack.

**Comment by NillerMedDild** [comment]
I kinda see them as an automation tool combined with a way of keeping your base tidy, which is why they're not gated.

.... but also because I didn't know the recipes could be removed/added with CrT.
