### ISSUE TITLE
""JavaVersionOrPathError"" on ServerStart

### ISSUE THREAD

**Issue by sasquatchdesires** [NillerMedDild/Enigmatica2Expert#1555]
**Modpack version**
Enigmatica 2 Expert Server 1.77

**Issue**
Just downloaded the server file from https://www.curseforge.com/minecraft/modpacks/enigmatica2expert/files and briefly after running ServerStart.bat I get 
_ERROR: Could not find valid java version installed.
64-bit Java ver 1.8+ is highly recomended. Check here for latest downloads:
https://java.com/en/download/manual.jsp

**** ERROR ****
There was an Error, Code: ""JavaVersionOrPathError""_
I have java version 1.8 installed on the same drive that the server file is on. I downloaded the java uninstaller and reinstalled java version 1.8 to no avail. I decided to download a new server file after I could not manage to fix this error on my previous server that was on version 1.65d. I previously thought the error with my old server was because I moved the server file from one SSD to my new one, because the error happened immediately after I moved it. If this is the case, I'm not sure why it's happening now, as I've installed java 1.8 and the server file entirely on my new SSD. I'm not very savvy with Java and have had horrible experiences fixing errors with it in the past, but I'm very eager to learn and play with my friends. I'm almost certain it is a path error, but I don't know how to begin fixing this.
**Logs**
I don't think there is anything applicable here, but please let me know anything you need that would help :)

**Comment by Carionis** [comment]
1.77 Singleplayer crashes on startup for me. Maybe a similar issue.
1.76a starts without trouble.

**Comment by NillerMedDild** [comment]
Do you have any other Java versions installed? The server files require that only Java 8 is present :)

**Comment by NillerMedDild** [comment]
@Carionis that is not related, please go to the support channel on my discord.

**Comment by sasquatchdesires** [comment]
So I've deleted all other versions of java that I've installed, but in my earlier attempts to fix the issue I seem to have created a new problem. When I run the ServerStart bat file, it instantly closes. I know this is an issue with environment variables with java but I can't seem to find exactly what I'm looking for in any documentation. I've tried messing around with PATH variables but I'm not sure I understand what I need to do to fix this. Sorry if this is not relevant to the ticket, if you know of any resources I can use to fix this I would greatly appreciate it! Thanks for your time!

**Comment by NillerMedDild** [comment]
Let's continue this on my discord, in the support channel where others can pitch in :)

**Comment by Tyler-Am** [comment]
Help im having the same issue and cant seem to find a solution

**Comment by Carionis** [comment]
Which Launcher are you using?
