### ISSUE TITLE
Additional Recipes for making IC2 Casings

### ISSUE THREAD

**Issue by NillerMedDild** [NillerMedDild/Enigmatica2Expert#1556]
Relayed from Discord: Update 1.77 of E2:Expert, somehow removed all Manufactory Recipes for IC2 Item Casings

**Comment by theboo** [comment]
Uhh you sure it wasn't some other machine? Item casings should never have been made by manufactory as the manufactory is like a pulveriser... Im playing on 1.74 and the only item casing recipes are IC2 metal former and the crafting grid recipe with hammer...

**Comment by NillerMedDild** [comment]
Indeed, I'll change the issue to be about adding additional support/recipes for ic2 casing
