### ISSUE TITLE
minor issue with Charcoal Blocks - don't get dropped by droppers nor dispensed by dispensers

### ISSUE THREAD

**Issue by Carionis** [NillerMedDild/Enigmatica2Expert#1557]
**Modpack version**
1.77 - was present in 1.76a as well

**Issue** - very minor
I'm trying to automate Botania Endoflames and I'm using charcoal to do it. Regular charcoal pieces, coal pieces and Coal Blocks work fine, get dropped out of the dropper and dispensed out of dispensers (I tried it with both). Charcoal Blocks however just stay in the inventory of both dropper and dispenser. I haven't tried it with other modded versions of both dispenser or dropper, but since they are vanilla, I'm assuming the charcoal block, which isn't vanilla, is the problem here. Since it is a very minor issue and easily worked around, I would understand completely if it doesn't get fixed.

**Comment by NillerMedDild** [comment]
Thanks for the report, I'll have a look :)
I believe the Open Crate from Botania can drop it, just fyi.

**Comment by Carionis** [comment]
Thanks for looking into it and the tip. I was toying with the idea of hoppers and ImmEngi conveyors but open crate is probably even easier. I just love the pressure plate automation... sorry. There might even be other modded options, like the AA dispenser or dropper, but I assumed that the vanilla stuff should be working, since it's likely the first option, especially early game.

**Comment by NillerMedDild** [comment]
I cannot reproduce this.

**Comment by Carionis** [comment]
Okay, new update, tried it today. Droppers now work (probably did before, might have been oversight on my part) with charcoal blocks. Dispensers place blocks into the world instead of throwing them, which, with my configuration didn't work since there was a pressure plate in the way.

Thanks so much for checking it out.
