### ISSUE TITLE
Integrated Dynamics Mechanical Squeezer recipe does not work

### ISSUE THREAD

**Issue by cdepuydt** [NillerMedDild/Enigmatica2Expert#1558]
**Modpack version**
1.77

**Issue**
The recipe for the integrated dynamics mechanical squeezer does not work.  The recipe loads in JEI, but when added to a crafting table it is not actually craftable.  I loaded into creative to verify all the battery combinations, and none of them worked (100k, 400k, 1.6m, with or without rf).

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by theboo** [comment]
mechanical drying basin and generator also cannot be crafted in 1.77... im thinking the tag .anyDamage() no longer works with these, i am currently attempting a fix with .withTag({energy: }).. I got it to work with energy: 0 only for empty batteries ofc, i am unsure if there is a way to have energy: any integer... got damn i miss /ct reload

**Comment by cdepuydt** [comment]
Another thing to look out for that I noticed while trying to set this up is that a Squeezer that's been used gets fingerprinted somehow with meta data and becomes unstackable.  It seems like it's unrelated to the core issue, but might cause issues with getting it working.

**Comment by theboo** [comment]
Might have something to do with this commit on the ID github, was added in 1.1.2

https://github.com/CyclopsMC/IntegratedDynamics/commit/c3c4b8b6f5116105810a746e1b9c9fd1e2f31488

**Comment by theboo** [comment]
should be fixed with PR #1561
