### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by 20Koen02** [NillerMedDild/Enigmatica2Expert#1559]
**Modpack version**
1.77

**Issue**
Crashes near the end of startup
Tried to reinstall

**Logs**
https://bin.koen02.nl/ekojuqulis

**Comment by 20Koen02** [comment]
Doesn't crash on 1.76a

**Comment by NillerMedDild** [comment]
You appear to be using outdated Java. This is often caused by Twitch defaulting to an older version than you have available. Follow these steps to update.

* Make sure you have the latest 64-bit Java installed
    https://www.java.com/en/download/manual.jsp Windows Offline (64-bit) is the one you need
* Go to the Twitch Minecraft settings
* Add `-version:1.8+` to the Additional Arguments
