### ISSUE TITLE
need help removing some twilight forest trophies I placed on a wall

### ISSUE THREAD

**Issue by croftyraider** [NillerMedDild/Enigmatica2Expert#156]
They claim to require Osgloglas level of mining, but even with a Supremium level tool they are unbreakable. I tried a block breaker to remove one but that generated a skeleton skull not the original Naga head.

**Comment by NillerMedDild** [comment]
Which update are you on?

**Comment by croftyraider** [comment]
Probably ancient - 1.22 if I can believe the Twitch launcher - if an update is required will it keep changes I've made to configs? I made a few minor changes to configs

**Comment by NillerMedDild** [comment]
This issue was fixed in 1.29 I believe. You will need to reapply your config changes after the update.
