### ISSUE TITLE
Blood Altar Tier 3 and 4 quests request incorrect items

### ISSUE THREAD

**Issue by Umgak** [NillerMedDild/Enigmatica2Expert#1562]
**Modpack version**
1.77

**Issue**
Blood Altar Tier 3 requires the player to own 4 Sea Lantern, and Blood Altar Tier 4 requires the player to own 4 Large Bloodstone Brick. However, the actual altar tiers require Glowstone and Large Bloodstone Tile, respectively.

**Comment by Discomanco** [comment]
The quests has multiple complete conditions, just like the altars has multiple setup conditions, as will accept both Glowstone and Bloodstone Tiles respectively as well
