### ISSUE TITLE
immersive engineering excavator

### ISSUE THREAD

**Issue by noa12390** [NillerMedDild/Enigmatica2Expert#1563]
1.77 version of pack
is there a reason the bucket for it is running backwards

**Comment by NillerMedDild** [comment]
Could you please make a video of it happening? :)
Are you using Optifine?

**Comment by noa12390** [comment]
no way to do video but if you build one on any deposit it will run backwards for the bucket and even then only at half speed have 4 of them running

**Comment by noa12390** [comment]
does the bucket turn clock wise or counter clock wise since these are all going counter clock wise

**Comment by NillerMedDild** [comment]
Again, are you using Optifine?

**Comment by noa12390** [comment]
no don't need to use it system can run minecraft at Ultra settings at unlimited frames so ya

**Comment by NicholasRC7** [comment]
I've experienced this too, it only happens when something is blocking some space around the excavator, it seems. Probably just an animation bug. I am using Optifine.
