### ISSUE TITLE
ME Interface confusing refined / compressed obsidian

### ISSUE THREAD

**Issue by Hypermobile** [NillerMedDild/Enigmatica2Expert#1565]
**Modpack version**
1.77

**Issue**
When using a crafting card to have an ME interface auto supply compressed obsidian to its internal inventory, it only supplies refined obsidian dust

Sorry if any more info is needed, I can provide whatever more is necessary

**Comment by NillerMedDild** [comment]
Thanks for the report - I would like screenshots of the Interfaces GUI, as well as of the patterns that hold all recipes that are related to this :)

**Comment by Hypermobile** [comment]
Not too used to using imgur, but believe this should work. https://imgur.com/gallery/NCkeTPW

**Comment by NillerMedDild** [comment]
Thanks! What is the disconnected item conduit on top of the far right interface doing? Does your ME system have room for refined obsidian dust?

**Comment by Hypermobile** [comment]
The disconnected conduit was only used for testing. Regardless of if it's there or not the issue still occurs (I was looking to see what happened if I autofed the dust back into the system). The ME system has several empty disks and several with free types.

**Comment by NillerMedDild** [comment]
Alright, I'll have a look :)

**Comment by NillerMedDild** [comment]
Works just fine for me with this beautiful setup :P
![Uploading billede.png…]()
