### ISSUE TITLE
RFTools Teleport Broken

### ISSUE THREAD

**Issue by Merlo17** [NillerMedDild/Enigmatica2Expert#1566]
**Modpack version**
1.76

**Issue**
I'm playing on a server and seemingly out of nowhere, for no reason at all, every Matter Transmitter/Receiver stopped working. When I try teleporting, either with the Transmitter/Dialing Device or the Charged Porter the text in chat "Starting" appears, but then nothing happens. The same thing, in the same exact setup, worked on the server two days ago. I'm 100% sure the blocks in question are chunkloaded, and the issue appears everywhere, no matter if between dimensions or same dimension, and for all players.

**Logs**
Nothing in the server console indicates anything weird is going on, when I initiate the teleport absolutely nothing appears in it.

**Comment by NillerMedDild** [comment]
Have you tried restarting the server? :)

**Comment by Merlo17** [comment]
Yeah, tried that too, probably should've mentioned that to be fair lol. At least a couple times probably, one intentionally to try and fix the issue. Also tried breaking and replacing the blocks and making new ones.

**Comment by NillerMedDild** [comment]
Cool, I'll try to replicate it :)

**Comment by Merlo17** [comment]
[crash-2020-03-24_15.05.01-client.txt](https://github.com/NillerMedDild/Enigmatica2Expert/files/4375689/crash-2020-03-24_15.05.01-client.txt)
Might be related to this, but I installed VanillaFix on the server and I'm getting a bunch of these

**Comment by NillerMedDild** [comment]
Please remove VanillaFix and see if it persists.

**Comment by Merlo17** [comment]
Teleporters were broken before I installed it btw, just wanted to point that out. I'm gonna try that later and tell you what happens

**Comment by NillerMedDild** [comment]
I can't reproduce this issue I'm afraid, not much I can do. Your logs might help, but I doubt they'll reveal the cause.
