### ISSUE TITLE
Advanced Rocketry gas charge pad quest describtion

### ISSUE THREAD

**Issue by viveleroi** [NillerMedDild/Enigmatica2Expert#1567]
**Modpack version**
1.77

**Issue**
Advanced Rocketry gas charge pad isn't working.

I followed the quest book: built an AR electrolyser, input water, built a space suit, built an AR gas charge pad, piped the oxygen into the gas charge pad, stood on it with the space suit on, but nothing happens.

The O2 meter doesn't change, the oxygen in the charge pad doesn't drain. Is there some aspect I'm missing that wasn't explained in the quest book?

I asked on discord and no one knew what the issue was.

https://i.imgur.com/mehQvF2.png

**Logs**
N/A

**Comment by NillerMedDild** [comment]
Did you remember to put tanks in your Space Suit? :)

**Comment by NillerMedDild** [comment]
If I remember correctly the Gas Charge Pad requires power.

**Comment by viveleroi** [comment]
I did not put tanks in yet, because the suit should have a 30 minute o2 supply built-in, I checked the ar configs to ensure that wasn't disabled and it appears to be enabled.

I'm going to try with air-seal armor next, and will try with actual tanks, but I have not made the infrastructure needed to make lubricant yet.

The gas charge pad normally requires power, and I have powered it just to try, but the quest book says "The gas charge pad is a simple machine that can fill items with oxygen or hydrogen without RF" so power shouldn't be needed.

**Comment by viveleroi** [comment]
Ok, it does require a tank to be added to the chestplate.

I would suggest that the quest book, in the gas charge pad section, explains that you need to add a tank first, because currently it only mentions the suit. Additionally, the suit work station quest appears more like an optional addon, but it should be a required step in the process.

**Comment by NillerMedDild** [comment]
Sure thing :)
