### ISSUE TITLE
Several end-game ores available from the IF laser drill

### ISSUE THREAD

**Issue by viveleroi** [NillerMedDild/Enigmatica2Expert#1568]
**Modpack version**
1.77

**Issue**
Several ores require "exploring the galaxy" to find them, and/or are locked behind high tier Environmental Tech ore miners.

Yet, several are available from the IF laser drill which is far easier to obtain and I don't think it should be a source of these ores. It should only return ores available in the overworld (and maybe Starmetal, since it can be made on the overworld)

- Prosperity Ore
- Inferium Ore
- Dimensional Shard Ore
- Iridium Ore
- Mana Infused Ore

**Comment by NillerMedDild** [comment]
Thank you for the report, but that is intended behaviour - mod knowledge let's you bypass some grindy elements.
