### ISSUE TITLE
Astral Sorcery: Transformation not working

### ISSUE THREAD

**Issue by Dotoren** [NillerMedDild/Enigmatica2Expert#1569]
**Modpack version**
1.76a

**Issue**
Iron ores (and other ores) not transforming in nighttime when linked to crystal.

**Logs**

Screenshot of setup:
https://i.imgur.com/sByteGj.png

**Comment by NillerMedDild** [comment]
Does the crystal have clear line of sight to the sky?

**Comment by Dotoren** [comment]
Yes ass seen in the picture. Apparently other crystals do work. Does this mean this crystal is just bugged? It's close to my base so I would really like it to work.

**Comment by NillerMedDild** [comment]
Oh Woops, I didn't notice the screenshot. Yep, that happens occasionally I'm afraid.
