### ISSUE TITLE
EU to RF conversion is inconsistent between mods

### ISSUE THREAD

**Issue by UltimateEnforcer** [NillerMedDild/Enigmatica2Expert#157]
Mekanism converts 1 eu to 4 rf, wheras nuclearcraft converts 1 eu to 16 rf. You can test this by letting a full batbox(40k eu) feed into a basic voltaic pile (results in 640k FE), and into a basic energy cube (results in160k FE).

Version: 1.32

**Comment by NillerMedDild** [comment]
That is intended, due to the shear amount NuclearCraft reactors can output, the EU production needed a slight nerf. You can ofcourse just convert it with Mekanism to avoid the 1:16 ratio.

I appreciate the report regardless :)
