### ISSUE TITLE
Thuamcraft Golems don't drop logs when breaking Greatwood

### ISSUE THREAD

**Issue by jayyyin** [NillerMedDild/Enigmatica2Expert#1570]
**Modpack version**
1.77

**Issue**
Thuamcraft Golems don't drop logs when breaking Greatwood (from Thaumcraft as well)

**Comment by NillerMedDild** [comment]
Do other logs drop when they break them? Is the area claimed?

**Comment by jayyyin** [comment]
we aren't using chunk claiming and yes the same spot I tested oak, it worked fine, pretty sure this is due to Greatwood having Iron tier harvest requirement and the golems probably not having a harvest level, any way to work around this?

**Comment by NillerMedDild** [comment]
Yes, that would indeed cause the issue :/

**Comment by NillerMedDild** [comment]
Can you upgrade the Golem's mining level?

**Comment by jayyyin** [comment]
Not that I can tell, it's already got the block breaker upgrade (it uses diamonds in it's recipe so I'd imagine it's probably intended to able to break things at diamond level) but it doesn't have a mining level I don't think.

**Comment by jayyyin** [comment]
unless there's some way to change that in the config or something.

**Comment by NillerMedDild** [comment]
I'm afraid not. I'm kinda torn between reducing the harvest level required, or letting the issue be.

**Comment by jayyyin** [comment]
well I don't know if there's another way to automate thaumcraft's trees...

**Comment by NillerMedDild** [comment]
There are many :) Cyclic's Forester for example
