### ISSUE TITLE
Backpack mod causes game window to turn white（machine translation）

### ISSUE THREAD

**Issue by EternisField** [NillerMedDild/Enigmatica2Expert#1571]
**Modpack version**
Enigmatica2Expert-1.77

**Issue**
Glowing buffs in LAN multiplayer games will cause other players' game windows to turn white. It's just that the screen becomes white, and those players can still move normally. I found out that the problem is caused by the backpack mod.
 (machine translation)

**Comment by NillerMedDild** [comment]
Could it be the same as #1244 ?
Please provide your latest.log

**Comment by EternisField** [comment]
Yes, this problem is very similar to #1244 , because the wearer of the night vision helmet will have a glowing buff.All items that give an entity a glow buff can cause this problem.
I cannot provide you with latest.log because it has been lost
(machine translation)

**Comment by NillerMedDild** [comment]
I'm afraid we've done what we can to fix this issue, you will simply have to steer clear of the glowing effect, or backpacks.

**Comment by EternisField** [comment]
Why not remove the backpack mod in Enigmatica2Expert
Many players report that the backpack mod has a lot of bugs, such as using the backpack bug in the server to generate double items
（machine translation）

**Comment by NillerMedDild** [comment]
All backpack mods have that bug, as far as I know. I can't remove it, because it would result in a ton of players losing things.

**Comment by EternisField** [comment]
I have a suggestion, why not get a separate fix version? Although this will increase your workload
Or can I modify your modpack and share it with my friends to play with?
（machine translation）

**Comment by NillerMedDild** [comment]
Why not just stop using it?

**Comment by EternisField** [comment]
Oh, well, sorry, I wasted so much of your time. I do n’t express my ideas very well, I know you are bored with this matter, please forgive me for making trouble

**Comment by NillerMedDild** [comment]
No trouble :) I messaged the mod author in the hope that it'll be fixed, but I doubt he answers.
