### ISSUE TITLE
Quest URL for Thermal Evaporation Plant is outdated

### ISSUE THREAD

**Issue by viveleroi** [NillerMedDild/Enigmatica2Expert#1572]
**Modpack version**
1.77

**Issue**
On the quest page for Mekanism's Thermal Evaporation Plant, the address printed is `https://wiki.aidancbrady.com/wiki/Thermal_Evaporation_Plant` but no longer goes to a useful page.

Maybe you can use https://ftb.gamepedia.com/Thermal_Evaporation_Plant instead.

**Comment by NillerMedDild** [comment]
Thanks, fixed in next update :)
