### ISSUE TITLE
Having a bizarre kick from with my client to a server

### ISSUE THREAD

**Issue by Xplodin** [NillerMedDild/Enigmatica2Expert#1573]
**Modpack version**
latest 1.77

**Issue**
Rustic chairs on server kicking me out of the game to connection terminated screen

**Logs**
[2020-03-15-1.log](https://github.com/NillerMedDild/Enigmatica2Expert/files/4333838/2020-03-15-1.log)

it started when i accidentally sat in a chair during backup and it kicked me out of the game. everytime i join im stuck in the chair and once LShift is pressed it kicks me

**Comment by NillerMedDild** [comment]
Thanks for the report, I relayed it to the mod author. In the meantime, I recommend that you either delete your player data, or edit the chair away with MCEdit.

**Comment by Xplodin** [comment]
Managed to fix my playerdata without reset or deleting it entirely.
Open playerdata in nbt and delete a section relating to vehicle with rustic. (the chair i sat in for example)

**Comment by NillerMedDild** [comment]
I do not believe I can fix this, and the majority of modders no longer support 1.12, so I'll close this issue.

Nethertheless, thank you for reporting :)
