### ISSUE TITLE
Blood Magic Teleportation Arrays trigger don't work and trigger "moved wrongly" if you do anything but stand in them

### ISSUE THREAD

**Issue by Scorch-Mechanic** [NillerMedDild/Enigmatica2Expert#1575]
**Modpack version**
1.77

**Issue**
Blood Magic's teleportation arrays trigger minecraft's inherent "moved wrongly" anticheat frequently. They work if you stand still in them, but walking at any speed into them makes me shiver and judder and it's generally annoying to use.

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
I'm not sure what the Teleportation Array is, could you please outline steps to reproduce this?

**Comment by Scorch-Mechanic** [comment]
A Teleportation Array is a short-range, low cost teleportation method. They have an entry in the Sanguine Scientium's "The Alchemist" chapter. Facing the direction you want to teleport in, use arcane ashes to place an alchemy array, then right click it with an ender pearl and a redstone dust, in that order. You'll see it rise off the ground and start to rotate if you've done it right. Once the teleportation array is created, stepping into it will teleport you to the nearest array marking (within 20 blocks) in a straight line respecting the orthagonal direction you placed the teleportation array to begin with. You can tell which direction the array will teleport you in by observing the direction the arrow shape in the array circle is facing. It's sort of like an openblocks elevator in that sense. Teleportation is one way, but there's nothing to stop you from making the receiving array into a teleportation array facing the opposite direction.

I suspect the issue is with blood magic and not necessarily with this modpack, but the blood magic bug report page has strict instructions regarding modpacks.

**Comment by NillerMedDild** [comment]
Excellent instructions, thanks. I'll reproduce it this evening and report to the Blood Magic issue tracker :)

**Comment by NillerMedDild** [comment]
Hmm, I haven't been able to reproduce this at all - Did it happen on a server?

**Comment by Scorch-Mechanic** [comment]
No, this is only singleplayer. If you can't replicate it on a server I suspect it is a raw computing power problem, and my own. Oh well.
