### ISSUE TITLE
Aluminum Brass production with only 2 Gold Ingots

### ISSUE THREAD

**Issue by saovenn** [NillerMedDild/Enigmatica2Expert#1578]
**Modpack version**
1.77

**Issue**
If you do a blank cast in the smeltery you get aluminum brass out. (Blank Cast can be made with 2 gold in the smeltery, which actually costs 1 copper and 3 tin in the Induction Smelter or Arc Furnace).

**Comment by NillerMedDild** [comment]
I know, that is intentional, converting gold to aluminum brass isn't particularly strong :)

**Comment by NillerMedDild** [comment]
- but thanks for the report!
