### ISSUE TITLE
""JavaVersionOrPathError"" on ServerStart

### ISSUE THREAD

**Issue by RS16x** [NillerMedDild/Enigmatica2Expert#1579]
**Modpack version**
Enigmatica 2

**Issue**
after running ServerStart.bat I get
_ERROR: Could not find valid java version installed.
64-bit Java ver 1.8+ is highly recomended. Check here for latest downloads:
https://java.com/en/download/manual.jsp

**ERROR**
There was an Error, Code: ""JavaVersionOrPathError""_
I have java version 1.8 installed on the same drive that the server file is on. I downloaded the java uninstaller and reinstalled java version 1.8

**Comment by NillerMedDild** [comment]
If you have any other java versions installed, uninstall them - Having Java 9, 10, 11 etc will cause the script to malfunction.

If you don't have other java versions, I suggest a restart. If none of that works, go to the support seciton on my Discord linked below :)

**Comment by Acidgrayn** [comment]
@NielsPilgaard You fucking suck. Stop making people leave this forum and "solving" their issue in a fucking discord server of all places.

**Comment by MommyHeather** [comment]
...what sort of comment is that, holy hell

**Comment by MommyHeather** [comment]
lol 8 minute old account too

**Comment by NielsPilgaard** [comment]
Java errors can be infuriating 😄 
Acidgrayn is now blocked from our issue trackers.
