### ISSUE TITLE
performance issues with 1.32 version of the pack

### ISSUE THREAD

**Issue by croftyraider** [NillerMedDild/Enigmatica2Expert#158]
I updated my setup to 1.32 recently to solve an issue with twilight forest trophies being unbreakable from the wall I had placed them on. All has gone well except for some kind of memory leak or something that leads to things being (eventually) unplayable.

I've been noticing some stuttering lag recently as I've been steadily adding more machinery as I near the end game, but recently it's gotten much worse - the game gets to the point (I've given it 6G of memory) where it goes from 70% used to 97% used in a matter of seconds and then stalls while a massive GC occurs.

I'm hoping you have some tools to diagnose this sort of thing to point a finger at a particular mod as some mod is generating vast quantities of garbage.

I have made many recent changes to my world so I'm not sure what it could be on my end, but I'll keep poking at it until I find something (I hope...).

**Comment by NillerMedDild** [comment]
I know what's causing the memory leak - It has been fixed, I just haven't updated yet, as the updates were unstable.
Please let me know if this is fixed in 1.33 :)

**Comment by croftyraider** [comment]
Could you share which mod is doing it? Maybe I can reduce that from my world until you're able to update. Currently I can play for about an hour before I have to shutdown minecrat and restart :(

**Comment by NillerMedDild** [comment]
It's ConnectedTexturesMod.

**Comment by NillerMedDild** [comment]
Any update?

**Comment by croftyraider** [comment]
Seems to be much much better. The update was annoying though as it created a whole new folder and so I had to copy over my config changes (maybe I should give some of them to you LOL) and my world folder and my journeymap data etc.

A few of the config changes I made that you could decide to take are:

IC2.ini:
enableIc2Audio = false
enableEnetExplosions = false

mekanism.cfg:
B:EnableMachineSounds=false

neat.cfg:
B:"Only show the health bar for the entity looked at"=true

The main change I've made is to turn off the menglin biome from integrated dynamics - I found in prior 1.12.2 testing that having it present eliminates many (!) biomes from BOP. Something about how it generates doesn't play nice. Sadly, I doubt you can do that because it will break the world most likely (I did that in SevTech ages after playing a world for awhile and ended up with a dead world).

I also disabled random blazes (quark.cfg) and firebats and wisps (thaumcraft_world.cfg) because frankly they are just annoying in the early game and in later game irrelevant.

**Comment by NillerMedDild** [comment]
Cool :)
