### ISSUE TITLE
wireless crystal can't connect to thermal expansion machines

### ISSUE THREAD

**Issue by TheSim14** [NillerMedDild/Enigmatica2Expert#1580]
**Modpack version**
1.77

**Issue**
Can't link from Draconic Wireless Energy Crystal to Thermal Expansion Machines alltime said "That tile can not supply energy on that side!" is that a bug or changed anything?

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by TheSim14** [comment]
Ok nvm, sry D: was my bad i didnt realize crystal goes in input mode, thats why i cant connect X.x

**Comment by NillerMedDild** [comment]
Heh alright.
