### ISSUE TITLE
There are a lot of items that don't have a recipe

### ISSUE THREAD

**Issue by 2696703792** [NillerMedDild/Enigmatica2Expert#1581]
**Modpack version**
1.77

**Issue**
There are a lot of items that don't have a recipe  and cycled in the Gates ultimate mission because I can't make a cutting machine
![image](https://user-images.githubusercontent.com/42534870/77274157-373b5a00-6cad-11ea-82d6-202870b8c90c.png)
![image](https://user-images.githubusercontent.com/42534870/77274172-40c4c200-6cad-11ea-94a4-a75dcf237025.png)

**Comment by NillerMedDild** [comment]
I'm not sure what the issue is to be honest, could you please rephrase?

**Comment by 2696703792** [comment]
I can't make the machine I need

**Comment by 2696703792** [comment]
such as cutting machine、rftoolscontrol:cpu_core_500、computercraft:turtle_expanded

**Comment by NillerMedDild** [comment]
Did you modify the modpack in any way? Do you see errors in the chat when you log in?

**Comment by 2696703792** [comment]
I added "i18nupdatemod-1.12.2-1.0.8"、"OptiFine_1.12.2_HD_U_F5""JustEnoughCharacters-1.12.0-3.4.3", on the client

**Comment by NillerMedDild** [comment]
Please re-install the modpack and see if the issues persist.

**Comment by 2696703792** [comment]
I am trying and will give you a reply later，thanks

**Comment by 2696703792** [comment]
Sorry for the trouble. The problem has been solved.Thank you for your answer

**Comment by 2696703792** [comment]
Is OptiFine  problem, you can add a list of incompatibilities to tell the following players

**Comment by NillerMedDild** [comment]
Optifine does not cause recipe issues afaik.

I don't support Optifine because it can (and often does) produce tons and tons of issues with mods. Keeping a list of incompatibilities would take a very large amount of maintenance, for a mod I'm already trying to avoid supporting.

If people want to use Optifine that's just fine, but they're on their own, just like if they add other mods to the pack.

**Comment by 2696703792** [comment]
Thanks for reminding, but the problem of the recipe this time is really Optifine's problem
