### ISSUE TITLE
Tinkers' Compliment's High Oven gives 2.5x ore easily early game

### ISSUE THREAD

**Issue by SSyl** [NillerMedDild/Enigmatica2Expert#1582]
**Modpack version**
1.77

**Issues**

1. Tinkers' Compliment's High Oven gives 2.5x ore and is easily made very early in the game. All you need to make it is Scorched Bricks, which is just Seared Stone poured over a minecraft brick using the Smeltery. Essentially, as soon as you get a Tinker's Construct Smeltery you're just minutes away from having the capability to get 2.5x the ingot yield per ore.

2. In addition, the High Oven lets you put in 1x Iron Ore, 1x Gunpowder, 1x Redstone, 1x Sand to get 2.5 ingots of Steel. This essentially allows you to bypass using the Coke Oven and Blast Furnace as well as letting you get 2.5x ingots of Steel per single Iron Ore.

3. It also allows you to melt Redstone into Destabilized Redstone giving you early access to Signalum. However, that's fairly minor since you can't do much with Signalum until you get to Thermal Expansion anyway.

**Suggested Solutions**

1. You can tweak the ore to ingot ratio in the tcomplement.cfg file. I think that setting it to 1.0 would put it in balance with the rest of the early game ore processing.

2. You'd have to use CraftTweaker to disable the creation of steel in the high oven. Although, if you did set the ore to ingot ratio to 1.0 it should deter anyone from bothering with the high oven to make steel since the material cost would outweigh using the Coke Oven + Blast Furnace. 
Removing it using CraftTweaker seems as simple as this:

```
import mods.tcomplement.highoven.HighOven;

// HighOven.removeMixRecipe(ILiquidStack output, @Optional ILiquidStack input);
HighOven.removeMixRecipe(<liquid:steel>); // disable any steel-producing mix recipe
```

3. You can probably leave the Destabilized Redstone melting as is unless I'm missing some hidden use for signalum.

**Comment by NillerMedDild** [comment]
Excellent report, thank you, I'll get this fixed.

**Comment by Krutoy242** [comment]
IMHO High Oven is awkward for Ore doubling, because it have several disadvantages:

- It have very small inside buffer - Oven capped in size (can be only 3x3) so 1 slot for 8 scorched bricks block
- 2.5 doubling causing excess liquid left inside often
- Small Plate Presser relatively cheap too (need 6 more iron to make), but doubling ore way too faster (about 3 ticks / ore)

**Comment by NillerMedDild** [comment]
Duely noted, but it is unintentional that it can 2.5x ores - Maybe 1.5x would be fine.

**Comment by NillerMedDild** [comment]
I decided to remove the High Oven completely.
