### ISSUE TITLE
Dragon breeding not working

### ISSUE THREAD

**Issue by Albino150** [NillerMedDild/Enigmatica2Expert#1585]
**Modpack version**
1.77

**Issue**
When trying to breed dragons from Ice and Fire the heart animations show up but they dont breed.

**Logs**
n/a

**Comment by NillerMedDild** [comment]
Thanks for the report, I found it reported here: https://github.com/Alex-the-666/Ice_and_Fire/issues/2231

**Comment by Albino150** [comment]
Thank you for the quick response :)
