### ISSUE TITLE
Cannot craft Flux

### ISSUE THREAD

**Issue by hnnter** [NillerMedDild/Enigmatica2Expert#1586]
**Modpack version**
1.77
**Issue**
I cannot craft flux, nor can I throw red stone in fire or lava like it says in the JEI without it burning and disappearing. Any fixes/ideas?

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by NillerMedDild** [comment]
I'll look into it :)

**Comment by NillerMedDild** [comment]
Works just fine for me with Redstone + Black Quartz - How are you trying to craft it?

**Comment by hnnter** [comment]
There is no recipe when I try to craft it, and the redstone and quartz recipe doesn’t work either.
![image](https://user-images.githubusercontent.com/62776597/77821767-229efd80-70c3-11ea-8fbc-181ec40fd1a5.jpg)

**Comment by NillerMedDild** [comment]
Something is up with your scripts, did you modify anything? Are you playing Single player?

**Comment by hnnter** [comment]
No changes, downloaded the mod pack straight from the website, and yes I am playing single player

**Comment by NillerMedDild** [comment]
Huh, that's odd, may I have your latest.log please?

**Comment by hnnter** [comment]
https://paste.ee/p/tf2nn

**Comment by NillerMedDild** [comment]
Hmm, may I also see your crafttweaker.log please? It's in the main folder.

**Comment by hnnter** [comment]
[crafttweaker.log](https://github.com/NillerMedDild/Enigmatica2Expert/files/4411977/crafttweaker.log)

**Comment by hnnter** [comment]
Black iron and a few other items I found dont have crafting recipes either.

**Comment by NillerMedDild** [comment]
Looks like you don't have any scripts. Is your scripts folder empty? Where did you download it, and how did you proceed from there?

**Comment by hnnter** [comment]
Yes my scripts folder is empty. I believe i downloaded the pack from either twitch or curseforge, and then I just added the pack to multimc which I use to run the mod.

**Comment by NillerMedDild** [comment]
Alright, well re-install the modpack to fix it :)

**Comment by hnnter** [comment]
That worked, I think I just forgot to select scripts when downloading the pack from twitch, but it is working now. Thanks for all the help.

**Comment by NillerMedDild** [comment]
Sure thing :)
