### ISSUE TITLE
Harder Emerald Dank Null Recipe

### ISSUE THREAD

**Issue by Knightener** [NillerMedDild/Enigmatica2Expert#1587]
**Modpack version**
Version 1.77
**Issue**
Due to the crafting of the black hole unit requiring you to defeat the final boss of Botania, and requiring the construction of many Mekanism machines, i'd consider it a late mid-game item. However, with the use of a /dank/null/MKV (Commonly referred to as "emerald /dank/null") which is not gated whatsoever, you can store up to 2^(31) − 1 items, not to mention that it has 60 slots, nothing compared to the mere one the  black hole unit provides. And with the use of a /dank/null docking station, it is possible to pump items in/out of said device.

**Possible solutions**
1. Make it so that it is only possible to extract from a /dank/null docking station.
2. Heavily gate the /dank/null/MKV (Or vice-versa).
3. Nerf the /dank/null/MKV.

**Comment by NillerMedDild** [comment]
The Docking Station is already extract-only :) I agree that it needs to be nerfed though.

**Comment by Knightener** [comment]
Actually i tested it, i managed to insert some cobblestone into a /dank/null/ using some simple item conduits, so maybe that's an issue too?

**Comment by NillerMedDild** [comment]
Oh boy, that's bad news.

**Comment by NovaBomber** [comment]
I'm actually using it as part of my storage in my AE2 System, they respond perfectly to AE2 storage buses.

**Comment by NillerMedDild** [comment]
Oh dear god. In that case, the Docking Station will be removed.

**Comment by MorganSimic** [comment]
Harder recipes for dank/null is always a pain because of the upgrade recipes. But i remebered that IterationFunk did some work on those upgrade recipes, wich i think worked out. I'm not sure how exactly he has done it but i looked up the scripts in his never released cryosim pack. 
[https://github.com/xt9/cryogenic-simulation/blob/master/scripts/mods/danknull.zs](url)
This might be similar stuff to #1553

**Comment by MuteTiefling** [comment]
Would it be possible to request a change of the DankNull dev to give you the extract only option you were expecting from the docking station? Having no dock to easily dump items from the dank null makes it far less useful as a tool, and very annoying to work with to extract all of the things it has collected. 

If it had a config option to be extract only, then it could be re-instated.

**Comment by NillerMedDild** [comment]
It does have that config, the issue is that it can be bypassed. Furthermore, the Docking Station can potentially be very damaging to servers, because of the amount of data it can contain - It almost killed one of the official server's worlds.
