### ISSUE TITLE
Creative Fluid Tank not craftable. Issue with nbt-data of portable tanks

### ISSUE THREAD

**Issue by PinieP** [NillerMedDild/Enigmatica2Expert#1589]
**Modpack version**
1.77

**Issue**
The recipe of the Creative Fluid Tank doesn't recognize portable tanks with any other nbt data than exactly the same as specified in the crafttweaker file.

A tank with only this data works:
{Fluid: {FluidName: "ic2uu_matter", Amount: 32000}}

The standart tank with all normal nbt data  doesn't work:
{RSControl:0b, Creative:0b,Fluid: {FluidName: "ic2uu_matter", Amount: 32000}, Level:0b, Lock:0b}

Edit: It's just shift clicking the recipe, sorry for the wrong issue

**Comment by NillerMedDild** [comment]
No worries :)
