### ISSUE TITLE
Issue crafting block 

### ISSUE THREAD

**Issue by Shinikibiligi** [NillerMedDild/Enigmatica2Expert#1590]
**Modpack version**
1.77
**Issue**
When crafting Quark - basalt bricks it just gives back the four polished for some reason. There is a way around this by using chisel but that makes the crafting requirements for making the Chiseled and Pavement options not possible through automation. 
**Logs**

**Comment by NillerMedDild** [comment]
The Chisel can be automated with the Auto Chisel, but I'll look into the issue :)
