### ISSUE TITLE
Creating Hydrated Coal dust (IC2 component) with a Thermal Expansion Reservoir succeeds but deletes the reservoir

### ISSUE THREAD

**Issue by Scorch-Mechanic** [NillerMedDild/Enigmatica2Expert#1591]
**Modpack version**
1.77

**Issue**
As title. Hydrated coal dust is a component of IC2 single-use batteries, which are exactly what they say on the tin. The recipe for hydrated coal dust is a bucket of water surrounded by piles of coal dust. I assume the problem is related to replacing the full bucket with an empty bucket, which goes screwy when there's no bucket in the first place. 

This issue exists with both the full 8 piece recipe and the single 1 piece recipe. I've been using a "hardened" reservoir but I don't think that's the issue.

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
I didn't fix this correctly, removing the new recipe in 1.82
