### ISSUE TITLE
Sink Harder Recipe

### ISSUE THREAD

**Issue by NillerMedDild** [NillerMedDild/Enigmatica2Expert#1594]
Aqueous Accumulator + Speed Upgrades + Metal of some kind for example?

**Comment by Scorch-Mechanic** [comment]
Gonna be sad to see the ol' splashy boi get nerfed but he's had it comin'. Maybe include a theoretical infinite water source in the recipe to gate it a little bit more? Depends on which speed upgrades you decide to require, I suppose.

**Comment by MorganSimic** [comment]
Well, you could be really devious and disable the infinte water config. :P That would be a bit harsh for sure but that would remove all issues with it at once. It also removes the ability to supply 2.1B/t to whatever you want like evap plants and other fusion setups. Not sure if fusion configs are sustainable in this pack without the sink. But the MA water source totally is reasonable for the powerlevel you are getting.

**Comment by NillerMedDild** [comment]
That would break a ton of existing setups, I won't do that :P

**Comment by AndyScherrenberg** [comment]
I had a suggestion for this recipe to make it more difficult to craft could be a little bit to hard:

- Replace the bucket in the recipe with the Dense Infinite Watersource from NuclearCraft
- One Iron with the Aqueous Accumulator
- 2 Iron with the Ultimate Fluid Tank from Mekanism

**Comment by KleinGrrmpf** [comment]
I actually like the idea of the theoretical infinite water source :)
