### ISSUE TITLE
Harder Building Gadgets Recipes

### ISSUE THREAD

**Issue by NillerMedDild** [NillerMedDild/Enigmatica2Expert#1595]
They're default at the moment, tsk tsk.

**Comment by MorganSimic** [comment]
As someone who was already opposed to the changes to the builder wand recipes, i personally wouldn't change the recipe of the building gadgets. I feel even for this pack they are in the right place. They make the creative aspect of the game so much easier and a lot of people already struggle with that. So a harder recipe would put an additional stone on that path. And i don't like that. I can see barely any circumstance where having any of the gadgets would make the progression any easier. But that is just my opinion on the matter and i thought i share it.
Although on a related matter, it came to mind that it could probably be reasonable to disable the stone and iron wands completely. But depending on what you have in mind for the gadgets it may not be necessary.

**Comment by MuteTiefling** [comment]
I'd actually go the other way and make them easier. Perhaps replacing emeralds with some Immersive Engineering components. You're already required to get into IE for some power production before you can realistically use the building gadgets, so it makes sort of sense that you'd maybe need to push into those recipes to get it built.

**Comment by NillerMedDild** [comment]
Hm, alright ._. won't fix.
