### ISSUE TITLE
Cobalt Ore in Macerator from IC2 outputs Crushed Ardite Ore.

### ISSUE THREAD

**Issue by AK9Official** [NillerMedDild/Enigmatica2Expert#1599]
**Modpack version**
1.78

**Issue**
Input of Cobalt Ore into Macerator outputs Crushed Ardite Ore for some odd reason. Seems like Cobalt Ore is put into the oreArdite OreDict?

**Comment by AK9Official** [comment]
https://i.imgur.com/dzhqW4D.png Seems to be causing issues with other machines also. It outputs both Ardite & Cobalt Ingot but it chooses Ardite over Cobalt.

**Comment by NillerMedDild** [comment]
Thanks for the report, I'll have a look :)
