### ISSUE TITLE
Tinkers modifier "reinforcement" + veinminer trivialises mining

### ISSUE THREAD

**Issue by elementalistic** [NillerMedDild/Enigmatica2Expert#16]
#### Issue Description
Using a tinkers tool with 5x reinforcement modifier makes it unbreakable.  Along with veinminer, it's made it easy to not only infinitely level those tools(mining stone), it's made it extremely cheap to start fast mining the world.

We had one player rush to botania and get living wood, made the pickaxe head and handle out of living wood, this gave them 6 modifiers, 5 used on reinforcement to make it unbreakable.  From there they just power leveled the tool.  This could also be done with paper tools or just leveling a cheap tool.

#### Modpack version
Enigmatica 2 Expert: 1.10

#### Suggestions
- Restrict reinforcement to only be able to applied 4x or less to stop unbreakable.
- Decrease how much reinforcement each level actually gives
- Make the reinforcement modifier more expensive then just 8 obsidian and 2 gold each.

**Comment by NillerMedDild** [comment]
Done as of update 1.13, requires some IC2 infrastructure
