### ISSUE TITLE
AE2 Storage cells

### ISSUE THREAD

**Issue by RedstoneGamer123** [NillerMedDild/Enigmatica2Expert#1600]
**Modpack version**
Input version here
1.78
**Issue**
Input short description of the issue here

Unless you take out a second full quantity 
of an item from the same storage cell the AE2 doesnt update the storage cell to allow a new item in when you take out only 1 full quantity of an item.

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by NillerMedDild** [comment]
Thanks for the report.
So what you're saying is that the 0 out of 63 item types text doesn't get updated properly, am I understanding that correctly? :)

**Comment by RedstoneGamer123** [comment]
No, It updates just fine, but once it's at 63 out of 63, though it updates to 62 out of 63 it doesnt make it green on the ME Drive block and I cant put the item back into the terminal till I take another item out of only that same storage cell then it updates or I take out and put back in the storage cell from the ME Drive block.

**Comment by NillerMedDild** [comment]
Ahh I see, I'll look into it.

**Comment by RedstoneGamer123** [comment]
Any updates on this?

**Comment by NillerMedDild** [comment]
Nope.

**Comment by NillerMedDild** [comment]
I've decided not to take this issue any further, as most modders no longer work on Minecraft 1.12, and development of Enigmatica is focused on Minecraft 1.15+ - I hope that's understandable :)
Thank you for helping to make E2E polished by reporting, I hope to see you in E5+!
