### ISSUE TITLE
Journey Map reset completely after 1.78 modpack update

### ISSUE THREAD

**Issue by SubtleSloth** [NillerMedDild/Enigmatica2Expert#1601]
**Modpack version**
1.78

**Issue**

After update from 1.77 to 1.78, all Journeymap progress and waypoints are gone. I grabbed the “mp” folder from the 1.77 profile “journeymap” folder and it brought back the waypoints, but the fog-of-war effect on the map is still completely reset meaning anything I’ve discovered that doesn’t have a waypoint is now undiscovered again.

**Comment by NillerMedDild** [comment]
Thanks for the report - Did you update to a new profile?

**Comment by SubtleSloth** [comment]
> Thanks for the report - Did you update to a new profile?

Yep, granted, this is my first time doing this and I am still super new to the game both vanilla and modded, so I could have messed something up. Though, the other guys on the server also lost their maps and such. I actually spoke to one of them about it and he said he didn’t do a new profile.

**Comment by NillerMedDild** [comment]
Seems to be a known issue actually :/ https://github.com/TeamJM/journeymap/issues/150
You'll have to not use a new profile when you update, and if that fails, copy the journeymap folder over as you did.

I'm afraid I can't really help further :(

**Comment by SubtleSloth** [comment]
Ahh, rgr that! Will try and get the entire JM folder instead of just the mp folder when I get back on tonight. Thanks for the help bud!

**Comment by Pacosaurus21** [comment]
Thanks you so much, I had the same problem and I found this, and it worked
