### ISSUE TITLE
Thaumcraft Smelting Bonus fix is not applied

### ISSUE THREAD

**Issue by MorganSimic** [NillerMedDild/Enigmatica2Expert#1604]
I noticed that using the infernal furnace from thaumcraft you still obtain thaumcraft nuggets, despite recalling seeing the fix in the scripts. Looking at the scripts i think all that is missing is `mods.thaumcraft.SmeltingBonus.removeSmeltingBonus` instead of only `removeSmeltingBonus`. So that should be an easy fix.

**Comment by MorganSimic** [comment]
I just noticed, that was on 1.76a. But i checked the files on github that should be recent and they still have the same error, so it should be the same in recent versions.

**Comment by NillerMedDild** [comment]
Actually the scripts import `mods.thaumcraft.SmeltingBonus.removeSmeltingBonus`, so using `removeSmeltingBonus` by itself is fine.

**Comment by MorganSimic** [comment]
Fact is, it doesn't work either way. Infernal furnace does spit out TC nuggets when processing native clusters. Didn't try with normal ores.

**Comment by NillerMedDild** [comment]
Worth a shot then, fingers crossed!

**Comment by NillerMedDild** [comment]
Pretty sure I found the issue, apparently the clusters have their own oredict, which is probably what the recipe is using.
