### ISSUE TITLE
Issue with the advanced metallurgic fabricator and Plustic centrifuge

### ISSUE THREAD

**Issue by Knightener** [NillerMedDild/Enigmatica2Expert#1605]
**Modpack version**
1.78

**Issue**
Huge issue regarding the advanced metallurgic fabricator and plustic centrifuge
First, you input your desired alloy to produce
![l](https://user-images.githubusercontent.com/62793679/78357220-b5ef9b80-75b9-11ea-8083-14fdd6f48cae.jpg)
Second,you melt that alloy using any kind of melting machine(I'm using a nuclearcraft melter here) you can convert the alloy to its liquefied form
![a](https://user-images.githubusercontent.com/62793679/78357451-2c8c9900-75ba-11ea-8a15-be10e0a74f23.jpg)
Third, you can convert liquefied alloy to its components. However the issue here is that the centrifuge uses smeltery alloying rates, not the advanced metallurgic fabricator rates. And since I used osmiridium alloy, that has a 1 to 2 ratio in the smeltery, yet a 1 to 4 ratio in the advanced metallurgic fabricator, it can effectively double the osmium and iridium.
![f jpg](https://user-images.githubusercontent.com/62793679/78357749-a3299680-75ba-11ea-9768-320450db85d8.png)
It can be reformed by a nuclearcraft ingot former or casting, the result is two osmium and iridium, double the original input.
![o jpg](https://user-images.githubusercontent.com/62793679/78357940-05829700-75bb-11ea-9b0e-789604529483.png)
This process can be repeated as many times as you would like, at the cost of a little energy. This issue is game-breaking and can be used to duplicate a plethora of metals. The same can be done for osgloglas, and mirion. Mirion while a little more complex (since the original rates are 1 ingot for 4 mirion) can have cobalt as a byproduct.

**Possible fix**
1. Remove the centrifuge
2. Remove the recipes for 3 said alloys in the advanced metallurgic infuser

**Comment by MorganSimic** [comment]
Voting for removing the centrifuge. It's not really needed and reverse crafting in any way is always a pain to balance. Also it's something 90% of people don't even know exists, so good riddance i would say.
Thank you for reporting. I suspected that there was something when i noticed the centrifuge but didn't bother testing.

**Comment by MorganSimic** [comment]
Looked into it shortly, it seems it's a simple config thing with setting in the plustic.cfg
```
    # Enable the machines from this mod (Centrifuge, etc.) [default: true]
    B:"Enable Machines addon"=true
```
Not sure if that entails anything else than the centrifuge though, can't look that up right now.

**Comment by Knightener** [comment]
True, I've never seen anyone talk about or even mention the plus tic centrifuge, and when i first saw it, i thought it was some placeholder item (because the texture isn't the best tbh)
