### ISSUE TITLE
Materials and You not alphabetized

### ISSUE THREAD

**Issue by SubtleSloth** [NillerMedDild/Enigmatica2Expert#1606]
**Modpack version**
1.78

**Issue**
Not sure if this is really an ISSUE, but something I’m sure a lot of us would love to see, especially people new to E2:E, and I didn’t know where else to recommend it. 

I personally would love to see the Materials and You book be alphabetized instead of whatever it is organized by right now. And I don’t know if it has a search bar at all, which would be amazing if possible. 

If I’m out of line putting this in issues, please let me know where to put it! Thanks!

**Comment by Discomanco** [comment]
Is it even possible to sort them? I'm not sure it is

**Comment by MorganSimic** [comment]
That would need to occure on the TiCon side of things. As pack dev you have no influence over that book other than removing materials and changing them.

**Comment by SubtleSloth** [comment]
> That would need to occure on the TiCon side of things. As pack dev you have no influence over that book other than removing materials and changing them.

This kind of makes sense to me, but at the same time, it doesn’t. How can the dev change recipes of blocks then? Also, if the pack dev can remove materials from the book, how can they not Swap the order? Or can they just remove the item from the modpack itself but the material still show up in the book?  I’m super new to Minecraft in general so sorry for the nub questions.

**Comment by Discomanco** [comment]
As pack devs, there is a limit of what we have access to.
We have access to Recipes through CraftTweaker, and that includes removing recipes from Tinkers Construct. When we remove a metal recipe from TiC, the Book will then update on that and not show that material as valid. So we can only indirectly influence the book, by adding or removing stuff. The rest of the book is outside of our reach.

**Comment by NillerMedDild** [comment]
I was a bit too hasty in closing this, we can try :)

**Comment by SubtleSloth** [comment]
@NillerMedDild Thanks bud, I appreciate the help/effort. Not many devs are this dedicated to their pack or even their fully released games lol. If you would like, I can contact the Tinker’s guys, but you probably have worked with them before on stuff, so coming from you, it might be better.

**Comment by SubtleSloth** [comment]
> As pack devs, there is a limit of what we have access to.
> We have access to Recipes through CraftTweaker, and that includes removing recipes from Tinkers Construct. When we remove a metal recipe from TiC, the Book will then update on that and not show that material as valid. So we can only indirectly influence the book, by adding or removing stuff. The rest of the book is outside of our reach.

Thanks for the explanation man. Completely understand now 😁

**Comment by NillerMedDild** [comment]
> If you would like, I can contact the Tinker’s guys

That'd be really nice :D

**Comment by SubtleSloth** [comment]
https://github.com/SlimeKnights/TinkersConstruct/issues/4071

@NillerMedDild sent them my idea, sending you the link so you can watch it if you would like 😁

**Comment by NillerMedDild** [comment]
Perfect, thank you!
