### ISSUE TITLE
Despite PR, Integrated Dynamics recipes are still broken, seemingly.

### ISSUE THREAD

**Issue by vini2003** [NillerMedDild/Enigmatica2Expert#1607]
**Version:** Enigmatica 2: Expert 1.78 (client and server)

**Issue:** Integrated Dynamics Mechanical Squeezer not working, despite #1558 and consequently #1561.

![](https://i.imgur.com/kdQ1mWZ.png)

I am unaware of the server's exact version, however I expect it to be 1.78, as I required 1.78 to be able to join.

**Comment by NillerMedDild** [comment]
I failed to merge the PR prior to publishing 1.78 ^^'
