### ISSUE TITLE
NuclearCraft Graphite Can't be made in some Crushers

### ISSUE THREAD

**Issue by noa12390** [NillerMedDild/Enigmatica2Expert#1608]
**Modpack version**
1.78

**Issue**
dust shows can be made in crusher but when ingots are input nothing happens 
even if the dust it's self lists the mek crusher as one of the machines that can make the dust by crushing the graphite ingots
**Logs**

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.
