### ISSUE TITLE
Astral Sorcery Celestial Gateways

### ISSUE THREAD

**Issue by enbian** [NillerMedDild/Enigmatica2Expert#161]
#### Issue Description
This is an issue with the version of Astral Sorcery that is present in the pack (1.9.2). Celestial Gateways do not link to each other, making them useless. This is fixed in later versions of the mod.

#### Modpack version (Do not use "latest")
1.32

**Comment by NillerMedDild** [comment]
Reporting a fixed issue seems a bit pointless, but thanks anyway :)
