### ISSUE TITLE
Immersive Engineering causing game to randomly crash

### ISSUE THREAD

**Issue by Igbathscaller** [NillerMedDild/Enigmatica2Expert#1610]
**Modpack version**
1.76a

**Issue**
Game randomly crashes when I am near immersive engineering blocks. It is pretty uncommon, but both times it happened I was near an improved blast furnace, waterwheel, lv capacitor and a Engineer's Workbench

**Logs**
https://pastebin.com/Vzk4MS9R

**Comment by NillerMedDild** [comment]
You appear to be using outdated Java. This is often caused by Twitch defaulting to an older version than you have available. Follow these steps to update.

* Make sure you have the latest 64-bit Java installed
    https://www.java.com/en/download/manual.jsp Windows Offline (64-bit) is the one you need
* Go to the Twitch Minecraft settings
* Add `-version:1.8+` to the Additional Arguments
