### ISSUE TITLE
Block cutting machine from IC2 gives wrong block.

### ISSUE THREAD

**Issue by BlitzieTheFolf** [NillerMedDild/Enigmatica2Expert#1611]
**Modpack version**
latest: 1.78

**Issue**
When you put a greatwood log into block cutting machine from industrial craft, you get oak wood planks instead of greatwood planks.

**Logs**
N/A

**Comment by NillerMedDild** [comment]
That's just how to IC2 Block Cutting Machine operates I'm afraid, all non-vanilla logs are turned into Oak. If I get a lot of time I'll fix it :)

**Comment by NillerMedDild** [comment]
@Krutoy242 If you're feeling adventurous, this looks right up your alley :P

**Comment by Krutoy242** [comment]
I can do this.
Through, can we install IC2 Tweaker addon for IC2 in CraftTweaker?

**Comment by NillerMedDild** [comment]
Absolutely :)
