### ISSUE TITLE
Thaumcraft

### ISSUE THREAD

**Issue by RedstoneGamer123** [NillerMedDild/Enigmatica2Expert#1613]
**Modpack version**
Input version here
1.78
**Issue**
Input short description of the issue here

At least on a server, the arcane workbench will not let me get a thaumometer. I've tried several times, even had jei put the items in. I can see it, but cant grab it from the output slot.
**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by NillerMedDild** [comment]
Have you tried relogging, restarting etc? If yes, please supply both client and server latest.log

**Comment by MorganSimic** [comment]
Also a few things to note, i assume you unlocked the recipe in the Thaumonomicon and supplied at least one of every vis crystal required to the workbench? If it still doesn't work, check the aura, the workbench might show 0 vis in the aura, that mean aura is broken at the moment. It's an annoying issue but it fixes itself as random as it breaks. Also switching chunks can help. Those are the common issues.

**Comment by RedstoneGamer123** [comment]
Restarting the server fixed it, sorry.
