### ISSUE TITLE
Thaumcraft disappearing seals (re-post)

### ISSUE THREAD

**Issue by pauldwrona** [NillerMedDild/Enigmatica2Expert#1614]
**Modpack version**
1.78

**Can this issue be reproduced?**
Yes

**Issue**
I noted the same [issue](https://github.com/NillerMedDild/Enigmatica2Expert/issues/924#issue-416331457) as noted in a previous thread, but the seals only seemed to disappear when placed on a tile entity (plant, farmland, etc) but not when placed on a static block. So far this has been stable, so I'm not sure how to resolve storing items with golems without placing the seal on a tile entity. I will have to do some testing myself.

_Originally posted by @pauldwrona in https://github.com/NillerMedDild/Enigmatica2Expert/issues/924#issuecomment-609460966_

**Comment by NillerMedDild** [comment]
Thanks for reposting with more details - I highly doubt this will be fixed though to be honest, Thaumcraft seems for the most part abandoned.

**Comment by NillerMedDild** [comment]
I've decided not to take this issue any further, as most modders no longer work on Minecraft 1.12, and development of Enigmatica is focused on Minecraft 1.15+ - I hope that's understandable :)
Thank you for helping to make E2E polished by reporting, I hope to see you in E5+!
