### ISSUE TITLE
BoP ores should have a tooltip saying they don't generate

### ISSUE THREAD

**Issue by aaronhowser1** [NillerMedDild/Enigmatica2Expert#1616]
**Modpack version**
1.79

**Issue**
They only spawn in certain biomes, but JER doesn't say which ones. This should be added to the tooltips for them.

**Comment by NillerMedDild** [comment]
Sure thing, thanks QA :P
I recommend you use the Sieve to get them though.

**Comment by aaronhowser1** [comment]
Oh man I completely forgot that Ex Nihilo was even *in* E2E! Definitely will go that route instead lol.
