### ISSUE TITLE
Rustic cabinets and IndustrialCraft 2 storage boxes are too easy to craft

### ISSUE THREAD

**Issue by FreeFull** [NillerMedDild/Enigmatica2Expert#1617]
**Modpack version**
1.78

**Issue**
The pack uses default recipes for the cabinets from Rustic and storage boxes from IndustrialCraft 2. These are both easier than the modified chest recipe. The storage boxes in particular function very similarly to shulker boxes, so should probably have a tougher recipe.

**Comment by NillerMedDild** [comment]
That is intended, to reward players who have "Expert" level knowledge of Minecraft :P 
Thanks for the report though, appreciate it!
