### ISSUE TITLE
PSI bar over screen

### ISSUE THREAD

**Issue by EternisField** [NillerMedDild/Enigmatica2Expert#1618]
**Modpack version**
Enigmatica2Expert-1.78

**Issue**
The PSI bar cannot be displayed on the screen. If you change the GUI scale or change the value of "Maximum Psi Bar Scale" in the PSI configuration, it will be displayed. I changed it to 4 and the PSI bar was displayed. I think this should be the oversight of the psi owner. 
This is not a issue, but I suggest that you modify the PSI config in the mudpack.
(machine translation)

**Logs**
None

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
Why did you close this issue?

**Comment by EternisField** [comment]
Oh, sorry, I accidentally clicked
