### ISSUE TITLE
Issue with /Dank/Null version 1.7.91

### ISSUE THREAD

**Issue by SSyl** [NillerMedDild/Enigmatica2Expert#1619]
**Modpack version**
1.79

**Issue**
The latest version of /Dank/Null (1.12.2-1.7.91) causes items to disappear visually in the /Dank/Null GUI.

It looks like the items disappear entirely, but if you try to click on a block in the dank null itself or even on some empty squares, it'll pick up one of the items that had disappeared. So, you're not actually losing the items. They just don't appear and the ones that do appear are often not the ones that you're actually picking up (if that makes sense).

It's already a reported issue to the /dank/null dev here: https://github.com/p455w0rd/DankNull/issues/270

Reverting to 1.7.90 fixes the issue.

**Comment by NillerMedDild** [comment]
Thanks for relaying :D

**Comment by NillerMedDild** [comment]
We fixed this by downgrading in 1.82 iirc
