### ISSUE TITLE
Actually Additions Oil Generator vs Thermal Expansion Compression Dynamo Inconsistencies 

### ISSUE THREAD

**Issue by killslash** [NillerMedDild/Enigmatica2Expert#162]
Hello,

Feel free to close this if it's intended, but I have noticed a bit of inconsistency regarding actually additions oil energy values in the Oil Generator compared to the TE Compression Dynamo.

With the current config here are the total energy values for a bucket of the 4 tiers of AA Oil in the AA Oil Generator:

              Canola:      40/t * 20t * 50s  =    40,000 total RF          
        Refined Canola:    80/t * 20t * 100s =   160,000 total RF
       Crystallized Oil:   240/t * 20t * 500s= 2,400,000 total RF
           Empowered Oil:  480/t * 20t * 750s= 7,200,000 total RF

Now Compared to the TE Compression Dynamo I noticed the values differed wildly. Also these are the only values displayed in JEI, not the Oil generator values.  It outputs a constant 60rf/tick values below:

                 Canola:  80,000 total RF (Double the Oil Generator)    
         Refined Canola: 200,000 total RF (25% better than oil generator) 
      Crystallized Oil:  400,000 total RF (1/6th as good as oil generator)
          Empowered Oil: 700,000 total RF (less than 1/10th the oil generator)

So for the first two tiers of oil, the Oil generator is worse than dynamo, but second two tiers it is A LOT better. This isn't even taking in to consideration the speed of generation, where first tier is worse in AA Oil generator, and everything else is better.

It seems inconsistent for two similar power generator to flip flop in efficiency when they are roughly the same tier, and one isn't displayed in JEI at all.

**Comment by NillerMedDild** [comment]
Damn, the difference is a lot higher than I ever thought. I'm going to nerf the AA Generator quite a bit, and as soon as the Modtweaker documentation for it is made, I will change the Dynamo values to fit. 

Thank you for your thorough investigation :)
