### ISSUE TITLE
Use iron to make aluminum

### ISSUE THREAD

**Issue by EternisField** [NillerMedDild/Enigmatica2Expert#1621]
**Modpack version**
Enigmatica2Expert-1.78

**Issue**
The Smeltery melting funnel using Tinkers' Construct will become molten aluminum. The funnel can be made of iron plate or aluminum plate.
(Machine Translation)
**Logs**
None

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
Ah right, that is actually intended :D enjoy!
