### ISSUE TITLE
Ae2 controller unable to be bookedmarked in jei

### ISSUE THREAD

**Issue by DabMaster408** [NillerMedDild/Enigmatica2Expert#1622]
**Modpack version**
1.77
**Issue**
When trying to bookmark an ae2 controller in jei nothing happens. Not really much of a problem as i cant see myself ever making these in bulk, yet I thought i might atleast bring it to your attention.

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
Works just fine for me :)
