### ISSUE TITLE
Recipes missing OreDictionary options

### ISSUE THREAD

**Issue by Aquintus** [NillerMedDild/Enigmatica2Expert#1623]
**Modpack version**
1.77

**Issue**
Recipes missing OreDictionary options

Hey Niller, 

not sure if I should bring it to your attention or to the attention of the Mod developers, but here are some recipes I found, that are limited due to missing ore dictionary options:
Fruit Basket of the mod Cooking for Blockheads requires an oak pressure plate and only works with oak.

The Presser of Pam's HarvestCraft only accepts vanilla wood logs to be turned into paper

The Actually Additions Empowerer does not work with Basalt from Quark to make empowered void crystal blocks

Kind regards and thanks for the awesome pack, playing through it a second time after playing it pretty much 2 years ago :D

**Comment by NillerMedDild** [comment]
Thanks for the report, and you're very welcome! I'll get that fixed :)

**Comment by NillerMedDild** [comment]
The Presser I can't fix I'm afraid, the others I could.
