### ISSUE TITLE
Starlight crafting enginge schematic (schematica) is broken

### ISSUE THREAD

**Issue by MorganSimic** [NillerMedDild/Enigmatica2Expert#1624]
**Modpack version**
1.77 and 1.78
**Issue**
I just had reports on Discord that Astral Sorcery schematics are broken. It seems at least the custom starlight crafting engine is the others may aswell. Couldn't test that out personnally. Also could have something to do with #1511 since it appears on 1.77 the version where the new schematics got merged.
Can not confirm this myself yet, but it seems this needs at least investigation.

**Comment by NillerMedDild** [comment]
Agreed, thanks for making the issue.

**Comment by NillerMedDild** [comment]
It is indeed broken, very very broken.
![billede](https://user-images.githubusercontent.com/21295394/79117078-66b02480-7d8a-11ea-985b-191cf9889fb3.png)
