### ISSUE TITLE
The issue of MEK digital miner in the server

### ISSUE THREAD

**Issue by EternisField** [NillerMedDild/Enigmatica2Expert#1626]
**Modpack version**
Enigmatica2Expert-1.78

**Issue**
It is not possible to use the MEK digital miner to mine ores like diamond ore and emerald ore on the server, but iron ore and gold ore can be mined. There is no issue in single player games. 
(machine translation)

**Logs**
None

**Comment by EternisField** [comment]
I found that mining other ores will also produce this kind of issue, such as lead ore. The mining is over in one second. Two of the more than 200 ores in the range are dug, and the value becomes 0
machine translation

**Comment by NillerMedDild** [comment]
If some ores work but others don't, they're probably just not in range.

**Comment by EternisField** [comment]
Sorry, I claimed the block. It was my negligence that caused this issue
