### ISSUE TITLE
Tinkers "Prosperous"-trait bugging out 

### ISSUE THREAD

**Issue by Aquintus** [NillerMedDild/Enigmatica2Expert#1627]
**Modpack version**
1.77

**Issue**
The prosperous trait you get from, for example, parts made out of prudentium (early quest reward you can resmelt to turn into rods/bindings) does bug out after a while and starts to drop full stacks of prosperity shards instead of just one.

How to reproduce:
Cyclic block placer, Extra Utilities 2 mechanical user and a Tinkers Pickaxe/Hatchet/Shovel with prosperous and global traveler traits with sending items set to the placer and then just letting it automine for a certain time.
[Example](https://streamable.com/xfpxww)
(the bug will not appear as quickly as that but rather after letting such a system run for a while is when we first experienced that bug)
 Once it did happen, even other tools while manually using them with the prosperous trait will start to drop full stacks rather than just a single shard. Really strange bug and kinda defeats the purpose of the rather expensive crafting recipe of the prosperity blocks.

Kind regards

**Comment by NillerMedDild** [comment]
Man that is weird, thanks for reporting it.

**Comment by MorganSimic** [comment]
This bug did happen also a long time ago, like a ton of versions ago, so it's really been there all the time. Not sure if there is something to fix it. From the conversations i remember and personal experience it's also super hard to replicate this as it works for some and not for others. I had an automatic farm going just fine while for others it would instantly break.

**Comment by NillerMedDild** [comment]
I will leave this unresolved in that case - Thanks for the report anyway, enjoy the extra Prosperity :P

**Comment by Porcy** [comment]
I stumble upon the exact opposite of this: I got some shards for a while (64 - 70 or so) and it stopped dropping them after some time.

**Comment by Hapseleg** [comment]
> 

Yeah I experience the same thing, I had em coming for some time (using a mechanical user + cursed earth mob farm) but suddenly I am getting pretty much 0, maybe it's once the weapon gets too high level or something?? I will create a new one and test it.
Also thanks for a great modpack Niller :)
