### ISSUE TITLE
Nuclearcraft active fluid coolers don't work with all liquids.

### ISSUE THREAD

**Issue by OfficialGHepic** [NillerMedDild/Enigmatica2Expert#1628]
**Modpack version**
1.78

**Issue**
The active fluid coolers from nuclearcraft only seem to cool while filled with water and doesn't work with other liquids. Active coolers can be filled succesfully with other liquids but in the fission controller UI it states that there isn't any heat dissapated per tick. It doesn't look like a visual glitch since the heat will stay in the reactor forever. 

Excuse me if this error isn't related to this modpack but instead for the mod itself.

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by OfficialGHepic** [comment]
Great to hear, actually just found this: https://github.com/turbodiesel4598/NuclearCraft/issues/214. Maybe this has some relation with the problem?

**Comment by NillerMedDild** [comment]
Sounds like the same issue, it's 2 years old though.

**Comment by NillerMedDild** [comment]
May I have a screenshot of your setup please?

**Comment by OfficialGHepic** [comment]
Here are some images:
![2020-04-13_15 51 15](https://user-images.githubusercontent.com/23342585/79125997-60787300-7d9f-11ea-9dcb-ca5c390c186a.png)
This is the pattern the reactor repeats until the last layer.
![2020-04-13_15 54 04](https://user-images.githubusercontent.com/23342585/79126028-71c17f80-7d9f-11ea-84eb-37269490d9e1.png)
A picture of the last layer.
![2020-04-13_15 55 28](https://user-images.githubusercontent.com/23342585/79126056-7be37e00-7d9f-11ea-9d9b-07d1c3f170ba.png)
For this purpose I used a creative tank.
![2020-04-13_15 54 54](https://user-images.githubusercontent.com/23342585/79126089-8ef64e00-7d9f-11ea-97a5-fbbdddd0817f.png)
As seen in this picture the coolers are filled with a liquid. But there isn't any heat dissapated.
![2020-04-13_15 55 14](https://user-images.githubusercontent.com/23342585/79126117-9ae21000-7d9f-11ea-9d97-5b1fad03772d.png)
I also filled the coolers with water.
![2020-04-13_16 01 26](https://user-images.githubusercontent.com/23342585/79126392-2196ed00-7da0-11ea-8435-5058a43de80c.png)
The controllers shows that with water there is heat dissapated.
![2020-04-13_16 01 39](https://user-images.githubusercontent.com/23342585/79126430-31163600-7da0-11ea-8003-606777069f5d.png)

Quick note that these pictures are taken in the newer 1.79a version of the modpack.

**Comment by NillerMedDild** [comment]
@TurboDiesel4598 would you mind having a look? The NuclearCraft version here is `NuclearCraft-2.18r-1.12.2`

**Comment by turbodiesel4598** [comment]
Hey there @OfficialGHepic - active coolers still need to respect their passive counterpart's placement rules. For example, active cryotheum coolers must be adjacent to two cells :)

**Comment by NillerMedDild** [comment]
Oh, now I understand the tooltip :P
