### ISSUE TITLE
Enderman chunks are enabled without any use/need an information tab

### ISSUE THREAD

**Issue by Aquintus** [NillerMedDild/Enigmatica2Expert#1629]
**Modpack version**
1.77

**Issue**
You can still get Mystical Agriculture enderman chunks via the "chunly" trait of tinkers, but they don't seem to have any use. If it's not possible to disable them dropping it might be worth it to add an information tab to them. ^^

Kind regards

**Comment by NillerMedDild** [comment]
Good idea, thanks for the report :)

**Comment by Aquintus** [comment]
The Tier 1-6 Mob Chunks of Mystical Agriculture also aren't used for anything right now, so could also be entirely be removed from JEI or at least get their crafting recipe removed ^^
