### ISSUE TITLE
Pam's harvest Fresh water duping

### ISSUE THREAD

**Issue by Igbathscaller** [NillerMedDild/Enigmatica2Expert#1631]
**Modpack version**
Version 1.78

**Issue**
1 Fresh water crafts into 8 fresh water. Not overpowered since Blockheads Sink exists.

**Logs**
https://imgur.com/a/2i2leKQ

**Comment by NillerMedDild** [comment]
Thanks for letting me know, I'm perfectly happy with that recipe :)
