### ISSUE TITLE
Replace PlusTiC with Plus TiC

### ISSUE THREAD

**Issue by NillerMedDild** [NillerMedDild/Enigmatica2Expert#1632]
The original mod was removed and reuploaded under the name Plus TiC, it seems.

**Comment by kaikue** [comment]
Plus TiC was removed too, FYI: https://www.reddit.com/r/feedthebeast/comments/g3fekk/looks_like_plus_tic_and_all_of_landmasters_mods/

**Comment by NillerMedDild** [comment]
I know, but thanks for the heads up :)

**Comment by aaronhowser1** [comment]
The Botania parts could be replaced with [Botania Materials](https://www.curseforge.com/minecraft/customization/botania-materials), maybe the rest can be done custom too?

**Comment by NillerMedDild** [comment]
That looks cool, very possible.
