### ISSUE TITLE
Issue with Blood Magic in Better Questing

### ISSUE THREAD

**Issue by EternisField** [NillerMedDild/Enigmatica2Expert#1633]
**Modpack version**
Enigmatica2Expert-1.78

**Issue**
I found that Blood Altar Tier 3 wrote in Better Questing's book that it needs Sea Lantern * 4, but in fact it needs glowstone * 4 to build blood altar tier 3. (machine translation)

**Logs**
None

**Comment by NillerMedDild** [comment]
Both work.
