### ISSUE TITLE
Issue about Quark  and MEK

### ISSUE THREAD

**Issue by EternisField** [NillerMedDild/Enigmatica2Expert#1635]
**Modpack version**
Enigmatica2Expert-1.78

**Issue**
Using the lock orientation function of the quark mod will cause MEK's liquid tanks and gas tanks to return to the basic level. I don't know if mek's machine also has this issue

**Logs**
None

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
It seems someone already opened an issue about this, I made a comment https://github.com/Vazkii/Quark/issues/1847

**Comment by EternisField** [comment]
Thanks!

**Comment by NillerMedDild** [comment]
I do not believe I can fix this, and the majority of modders no longer support 1.12, so I'll close this issue.

Nethertheless, thank you for reporting :)
