### ISSUE TITLE
Misprinted quest name for quest ID # 21

### ISSUE THREAD

**Issue by musicsoul0142** [NillerMedDild/Enigmatica2Expert#1636]
**Modpack version**
Egnimatica2Expert V1.78

**Issue**
(Use Google Translate)
The item name of Psi that is the quest name of quest ID #21 is different from the actual one.
The correct name is "Creative CAD Assembly"
Probably because you did not change the quest name when Magical Psi was removed from the Pack.
This is a very small typo, but thank you.

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.
