### ISSUE TITLE
Disconnecting from server

### ISSUE THREAD

**Issue by chicklick** [NillerMedDild/Enigmatica2Expert#1637]
**Modpack version**
1.78

**Issue**
Disconnecting randomly, says nothing in the console only on his side.

**Logs**
[Gyazo](https://gyazo.com/876b406f6d008a12e4f50fba09a6132e)

**Comment by NillerMedDild** [comment]
Please supply his latest.log :)

**Comment by chicklick** [comment]
[latest.log](https://github.com/NillerMedDild/Enigmatica2Expert/files/4465017/latest.log)

**Comment by NillerMedDild** [comment]
Not really sure what's wrong, but his Java is definitely outdated.
Please send him this guide for setting up the modpack correctly:
https://gist.github.com/NillerMedDild/40b4992b7a3e5e653a353fe1d45f2185

**Comment by chicklick** [comment]
He did all that and the error is still there, this however came up recently [Gyazo](https://gyazo.com/98d521ce3d58b0d881d5b40b71d248e7)

**Comment by NillerMedDild** [comment]
Please go to the support section on our discord :)
