### ISSUE TITLE
Game crashes before even starting

### ISSUE THREAD

**Issue by KleinGrrmpf** [NillerMedDild/Enigmatica2Expert#1638]
**Modpack version**
1.79a

**Issue**
Whenever I start the modpack in the minecraft launcher the game doesn't even appear. It crashes before any window opens and without a crash report, This never happened to me before, only after I updated to 1.79a from 1.78
I tried repairing the pack in the twitch app, but the same error occured.
[latest.log](https://github.com/NillerMedDild/Enigmatica2Expert/files/4466101/latest.log)

EDIT: After completely deleting and reinstalling the pack it worked fine. But it is still weird that after updating the pack it was so weird.

**Logs**
Latest log is attached to the issue

**Comment by NillerMedDild** [comment]
You appear to be using outdated Java. This is often caused by Twitch defaulting to an older version than you have available. Follow these steps to update.

* Make sure you have the latest 64-bit Java installed
    https://www.java.com/en/download/manual.jsp Windows Offline (64-bit) is the one you need
* Go to the Twitch Minecraft settings
* Add `-version:1.8+` to the Additional Arguments

**Comment by KleinGrrmpf** [comment]
Ok, that is weird... I had the newest Java Version and before the update it worked fine. Whatever, reinstalling fixed it, but thanks anyways :)

**Comment by NillerMedDild** [comment]
Sure thing :)

**Comment by musicsoul0142** [comment]
The real cause of this problem is probably due to a later added version of Vanilla Fix.
Older versions of Vanilla Fix appear to have conflicts with Mods modified after 1.78.
I had a similar issue, which was resolved by updating the Vanilla Fix.
