### ISSUE TITLE
[Request] Add Twilight Forest Blocks to Chisel

### ISSUE THREAD

**Issue by Protius7331** [NillerMedDild/Enigmatica2Expert#164]
I've noticed that the Twilight Forest Castle blocks are in a Chisel group but neither the Rune blocks nor the Door blocks are Chisel-able. Also the doors only drop the yellow colour when broken and I would personally like to be able to use other coloured doors, so the ability to Chisel them would also be appreciated. If interested, I have written (and tested) the following to add them:

```addVariation("castlebrickrune", <twilightforest:castle_rune_brick:0>);
addVariation("castlebrickrune", <twilightforest:castle_rune_brick:1>);
addVariation("castlebrickrune", <twilightforest:castle_rune_brick:2>);
addVariation("castlebrickrune", <twilightforest:castle_rune_brick:3>);

addVariation("castlebrickdoor", <twilightforest:castle_door:0>);
addVariation("castlebrickdoor", <twilightforest:castle_door:1>);
addVariation("castlebrickdoor", <twilightforest:castle_door:2>);
addVariation("castlebrickdoor", <twilightforest:castle_door:3>);
```

To be added to the "Chisel.zs" script. Hope it can be added!

**Comment by NillerMedDild** [comment]
I've added it to the script, thank you!
