### ISSUE TITLE
Energized Smelter produces IC2 ingots

### ISSUE THREAD

**Issue by viveleroi** [NillerMedDild/Enigmatica2Expert#1640]
**Modpack version**
1.78

**Issue**
Smelting ic2 crushed ores in a Mekanism smelter gives me the IC2 ingots, yet smelting the crushed ore in a normal furnace gives me the thermal foundation ingots.

I can't use these ingots the same, can't make blocks with them, they don't appear to be useful in JEI for processing the same way thermal ingots are.

**Comment by NillerMedDild** [comment]
Thanks for the report, I'll get that fixed :)
