### ISSUE TITLE
Bucket duping/infinite iron with poison bucket recipe.

### ISSUE THREAD

**Issue by Igbathscaller** [NillerMedDild/Enigmatica2Expert#1641]
**Modpack version**
Version: 1.78

**Issue**
You can easily duplicate buckets with the poison bucket recipe. Can potentially be abused to create infinite iron.
Could probably just fix with a recipe change.

**Logs**
https://imgur.com/a/Wzqx826

**Comment by NillerMedDild** [comment]
I'll get that fixed, thanks :)
