### ISSUE TITLE
Dank Nulls Dupe Items

### ISSUE THREAD

**Issue by SubtleSloth** [NillerMedDild/Enigmatica2Expert#1643]
**Modpack version**
1.79a

**Issue**
Dank Nulls duplicate items under the following conditions:

Step 1: Empty Dank Null (I believe the last selected item in the dank will show up as the currently selected item to place with the dank, even though it will not be in the dank anymore, but it COULD just be the first slot that is dumping items, still not sure on this)

Step 2: Drop dank on ground 
Step 3: Pick up dank
Step 4: Look inside Dank, item that was shown in the dank but not actually in the dank should now exist in the dank (again, not sure if it’s a first slot thing, or last selected item, or both)

https://github.com/p455w0rd/DankNull/issues/275

Sent the mod dev a link to this issue to give them a heads up.

**Comment by NillerMedDild** [comment]
Thanks for the steps to reproduce, and reporting the issue :)

**Comment by NillerMedDild** [comment]
The version of DankNull we're currently using is the most stable I've found, so I will not risk updating to potentially fix this issue.
