### ISSUE TITLE
Black Hole Tank Duplication Glitch with Cyclic Piston Scepter

### ISSUE THREAD

**Issue by Notme2222** [NillerMedDild/Enigmatica2Expert#1644]
**Modpack version**
1.79a

**Issue**
Hitting a Black Hole Tank that has a label on it with a Piston Scepter will move the black hole tank and drop one on the ground

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by Notme2222** [comment]
Also works with black hole unit

**Comment by NillerMedDild** [comment]
Thanks for the report. I'll just disable the Piston Scepter, it has a ton of these issues.
