### ISSUE TITLE
Mass Fabricator quest corrections

### ISSUE THREAD

**Issue by viveleroi** [NillerMedDild/Enigmatica2Expert#1648]
**Modpack version**
1.78

**Issue**
Under the IndustrialCraft section, the "Mass Fabricator" quest could use a few tweaks:

- Replace "Mass" with "Matter" in title and description, since we're meant to use the Matter Fab over Mass Fab
- Fix typo on "scrab" to "scrap"

**Comment by NillerMedDild** [comment]
Thanks for letting me know, I'll get that fixed.

**Comment by Frikkle** [comment]
Just as an fyi, these have also been fixed in the quest rework fork.

**Comment by NillerMedDild** [comment]
Good to know, thanks!
