### ISSUE TITLE
Universal Fluid Cell

### ISSUE THREAD

**Issue by Zenthae** [NillerMedDild/Enigmatica2Expert#1649]
**Modpack version**
1.79a

**Issue**
Universal Fluid Cell <Empty> hidden by default in JEI

**Comment by NillerMedDild** [comment]
I can't even remember what that is, I'll have a look :P

**Comment by Discomanco** [comment]
IC2 stackable "bucket" :P
Its a bit of a weird one, because it seems to be a 50/50 if it shows up in peoples JEI

**Comment by NillerMedDild** [comment]
Ahh right, my mind went straight to AE2/Extra Cells
It's hidden on purpose because liquid containers cause lag when viewed in JEI.
