### ISSUE TITLE
Release 1.80 immediate crash

### ISSUE THREAD

**Issue by Dobby2719** [NillerMedDild/Enigmatica2Expert#1650]
**Modpack version**
1.80 (current)

**Issue**
Just updated to the newest release and modpack no longer opens. No settings changed or anything. Click launch from the Twitch launcher, it opens the Minecraft launcher from which I press "Play", the launcher closes like it's about to start launching the game, but it immediately reopens to the launcher window with the message "an unexpected issue has occurred and the game has crashed"

**Logs**
https://pastebin.com/Hgkean2Q

**Comment by NillerMedDild** [comment]
You appear to be using outdated Java. This is often caused by Twitch defaulting to an older version than you have available. Follow these steps to update.

* Make sure you have the latest 64-bit Java installed
    https://www.java.com/en/download/manual.jsp Windows Offline (64-bit) is the one you need
* Go to the Twitch Minecraft settings
* Add `-version:1.8+` to the Additional Arguments
