### ISSUE TITLE
EnderIO Soul Vial does not respect default config blacklist

### ISSUE THREAD

**Issue by Skynet0** [NillerMedDild/Enigmatica2Expert#1651]
**Modpack version**
1.80

**Issue**
EnderIO Soul Vial can be used on the Wither, even though this is blocked in the default config (then used in a powered spawner). Explicitly adding the wither line to config/enderio/recipes/user/spawner.xml fixes this, though that's probably not the fix you're looking for... This may extend to other default blacklisted bosses, but I did not check those.

**Logs**
N/A

**Comment by NillerMedDild** [comment]
Hmm, I haven't been able to reproduce this. Are you doing something special to capture it?

**Comment by Skynet0** [comment]
Nope. I downloaded 1.80 through Twitch launcher, and made a creative world. I set up the wither using JEI to make sure I wouldn't die, then changed to survival to finish the spawn.

I used JEI to get Soul Sand, Wither Skeleton Skulls, Creative Mill, Angel Ring, Soul Vial, and armor. I let it spawn, flew away to avoid the initial explosion, then flew back to capture it.

**Comment by NillerMedDild** [comment]
Hmm that's odd, I did the same :s

**Comment by Skynet0** [comment]
Also of note - all the supposedly banned soul vials show up in JEI, including bosses (Twilight Forest), Elder Guardian, etc., suggesting that something is wrong with how it's loading the config. Anything else I should check?

**Comment by NillerMedDild** [comment]
Nah, but thanks for asking :)

**Comment by theboo** [comment]
it has been this way for awhiiiiile... my server is on 1.74 and i have had a powered wither spawner for about a month now i think?

**Comment by NillerMedDild** [comment]
I actually like that it works in a Powered Spawner, what I don't like is being able to capture it easily :P

**Comment by Skynet0** [comment]
Correction - Twilight forest bosses, at the least, are not able to be captured in soul vials.

**Comment by KleinGrrmpf** [comment]
Ok, I can confirm, this still works. I made a creative world, took infinity armor, soul sand, wither skulls and soul vials out of the creative inventory, switched to survival mode, spawned the wither in survival and could capture it with a soul vial...

**Comment by NillerMedDild** [comment]
I managed to recreate it in a new world, still can't in my original test world for some reason. I'll try to disable it better :P

**Comment by NillerMedDild** [comment]
I have been unable to fix this issue I'm afraid.

**Comment by Discomanco** [comment]
Just tried to regenerate the entire EnderIO config folder. And the Soul Vial blacklist is not to be found in there

**Comment by bibo38** [comment]
@NillerMedDild Can you elaborate why you were unable to fix this issue?

I've overridden my `spawner.xml` file with the contents of the `spawner.xml` file on the develop branch (https://github.com/NillerMedDild/Enigmatica2Expert/blob/6da785fec132576f6ff37a6feb68334ae5d8c883/config/enderio/recipes/user/spawner.xml) in my (fairly new) Enigmatica2Expert 1.80 folder and after a restart of Minecraft it worked as intended for me:
![Wither cannot be picked up by Soul vials, instead an error message is displayed](https://user-images.githubusercontent.com/1812304/83188018-58964780-a12f-11ea-88ee-5de921bd0079.png)
Your fix works :smirk:

**Comment by NillerMedDild** [comment]
Huh, that's... something. I was still able to capture it in my testing world. I'm glad it works :P

**Comment by bibo38** [comment]
Just cloned the current develp branch (deca811), ran `java -jar InstanceSync.jar` (and manually downloaded Pams Harvestcraft). Then added the folder to MultiMC and added the recommended Forge version (14.23.5.2854). After starting Minecraft and setting up a world, the Soul vials were not able to capture the wither :smile: .
