### ISSUE TITLE
Consider replacing Immersive Tech with Immersive Technology

### ISSUE THREAD

**Issue by stevenkxu** [NillerMedDild/Enigmatica2Expert#1652]
**Modpack version**
Input version here
1.80
**Issue**
Input short description of the issue here
Immersive Tech has not been updated in roughly 2 years. This [reddit post](https://www.reddit.com/r/feedthebeast/comments/g2bf2s/mc_eternal_seems_like_immersive_tech_is_broken/) suggests there are possibly unanticipated bugs within the mod. 

Immersive Technology (https://www.curseforge.com/minecraft/mc-mods/mct-immersive-technology) is "unofficially an update to Immersive Tech" and "will swap seamlessly with Immersive Tech". 

It is still being updated and balanced. It has some minor feature bloat, but it's still being improved on. If possible, replacing Immersive Tech with Immersive Technology may be better for game stability/bugs. If it actually is a seamless swap, the downsides of the change seem minimal.

**Comment by NillerMedDild** [comment]
No thank you, Immersive Tech works fine in E2E :)

**Comment by stevenkxu** [comment]
Fair enough, but if a major bug does pop up, at least there's an alternative.

**Comment by NillerMedDild** [comment]
True, thanks for the heads up!
