### ISSUE TITLE
ChunkLoader

### ISSUE THREAD

**Issue by MishuBufnita** [NillerMedDild/Enigmatica2Expert#1654]
**Modpack version**
Enigmatica 2 Expert 1.80(Release)

**Issue**
I put a chunk loader(IC2) with a geo thermal generator(IC2) beside 2 mob spawners(Minecraft) for xp and it dosen't work. I still have to stay there to get the experience. Can you modify the mod files or add the mod "ChichenChunks"? From old versions of modded miecraft that had this mode, this problem didn't exist. Thanks =))) And keep up the good work !

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by NillerMedDild** [comment]
Vanilla Spawners are only active when a player is within 24 blocks of them. You can fix it by using a different kind of spawner, or if I remember correctly, by putting Cursed Earth under it.
