### ISSUE TITLE
Screen turns red whenever a skeleton is hit

### ISSUE THREAD

**Issue by KleinGrrmpf** [NillerMedDild/Enigmatica2Expert#1656]
**Modpack version**
1.79a

**Issue**
Whenever a skeleton is hit in my presence, whether I hit it, another player hits it, a mob grinder kills it or it burns in the sunlight, my screen gets a red tint. This never happened to me in my first 445h playthrough, but suddenly it started happening after ~60h on a friend's server. By that point we have already played with version 1.79a for a few days, so I don't think it is related to the version. I didn't change anything regarding the resource pack (first playthrough with the same pack). On the server I emptied out my whole inventory and it still appeared. Then I created a completely new singleplayer world and it still occured. The issue occurs in survival and creative mode. I also opened a reddit thread about my issue if you can find any additional information in there:

https://www.reddit.com/r/feedthebeast/comments/g2jsew/e2e_screen_sometimes_randomly_gets_a_red_tint/

If you need any logs, let me know. 
I haven't yet tried to reinstall the pack.

The texture pack I'm using is the official sphax purebdcraft patch for this modpack. There are no additional mods involved.

![2020-04-16_19 22 56](https://user-images.githubusercontent.com/50833808/79606630-2c2fea00-80f2-11ea-8ebe-fd48ab02902c.png)

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by NillerMedDild** [comment]
Hm, that's odd. May I have your latest.log please?

**Comment by KleinGrrmpf** [comment]
Ok, I checked the log...
Why did I not think of this earlier???
The log contains 1.45 million lines and 99.9% are the same, so I will delete a lot of it to be able to upload it (The file is 66MB)
The line that is spammed in the log is
`[21:14:49] [Client thread/ERROR]: Couldn't render entity
java.lang.ClassCastException: null`

**Comment by NillerMedDild** [comment]
I need a bit more information than that I'm afraid :/

**Comment by KleinGrrmpf** [comment]
Working on it...

**Comment by NillerMedDild** [comment]
Tbh odds are your java is outdated:
This is often caused by Twitch defaulting to an older version than you have available. Follow these steps to update.

* Make sure you have the latest 64-bit Java installed
    https://www.java.com/en/download/manual.jsp Windows Offline (64-bit) is the one you need
* Go to the Twitch Minecraft settings
* Add `-version:1.8+` to the Additional Arguments

**Comment by KleinGrrmpf** [comment]
I have the additional argument. I would really like to use the Java Version that I have installed, but the "Check for Java Version" button is grayed out in Twitch.

**Comment by NillerMedDild** [comment]
If you restart the game and provide me the new latest.log that'll tell me which version it's using.

**Comment by KleinGrrmpf** [comment]
[latest.log](https://github.com/NillerMedDild/Enigmatica2Expert/files/4495397/latest.log)

This is the log of my current game. This game has already been started with the additional Java argument. I deleted a lot of the code line I mentioned before, but I guess you still get the idea.

And also, when I go into the Java settings in Twitch, it says I am using the Java Version 11.0.1.0 (64 Bit) which is the development kit, but it won't let me change to the current runtime environment version. The weird thing is however, that in the minecraft launcher it says that it is using the bundled Java runtime. I can change that to my own Java installation but when I close the launcher and reopen it via Twitch, the setting is reset.

**Comment by NillerMedDild** [comment]
That log doesn't indicate the used java version, that would be right at the start, somewhere in the first 100 lines iirc.

Please make sure you have Java 8 64-bit, Java 11 won't work with Minecraft. I recommend that you remove Java 11 if you don't need it.

**Comment by KleinGrrmpf** [comment]
Currently ingame the java version that is displayed in the F3 screen is 1.8.0_241 64bit

**Comment by NillerMedDild** [comment]
Oh right, I forgot all about that ^^'

**Comment by NillerMedDild** [comment]
Are you wearing a Backpack?

**Comment by KleinGrrmpf** [comment]
A backpack from the Iron Backpack mod, yes. The golden one

**Comment by NillerMedDild** [comment]
Could you remove all your armor, baubles and backpack(s) and see if the issue persists?
I'mma go to bed, will troubleshoot more tomorrow :P

**Comment by KleinGrrmpf** [comment]
I removed my whole inventory, baubles, extra inventory from cyclic and it still persisted. The issue also persisted when I created a completely new world. In creative and survival.

**Comment by KleinGrrmpf** [comment]
Ok, I found out how to use the newest Java version with the twitch launcher. Let's see with the next start if the problem still appears, although the Java version I was using the time the issue came up first was quite new...

**Comment by NillerMedDild** [comment]
I doubt it'll fix it, I'll see if I can reproduce it :)

**Comment by KleinGrrmpf** [comment]
Ok, I started the game with the newest Java version (The top right corner of the F3 menu shows 1.8.0_251) and at least in singleplayer the issue surprisingly didn't persist. I tried creative and survival. When I checked the logs, no line of code was spamming the document, so maybe the issue is gone? I have to test in on the server yet, but for now that is a good sign...

**Comment by KleinGrrmpf** [comment]
Ok, so I tested it on the server, too and the issue did not persist anymore. I still have no idea why it came up in the first place. I did not do anything to the Java version when the tinting started, but apparently updating Java fixed it for some reason. I guess we can close this issue now and hope this does not show up ever again. Thanks for your help, though ;)

**Comment by NillerMedDild** [comment]
Huh, that's odd, but nice! :D
