### ISSUE TITLE
Quest book got reset, graves stopped being marked, loot boxes stopped dropping loot, spice of life occasionally not saving consumed food

### ISSUE THREAD

**Issue by LordBoxe** [NillerMedDild/Enigmatica2Expert#1657]
**Modpack version**
1.79a updated to 1.80 3 days ago

**Issue**
About 3 hours ago the first 3 of the above issues surfaced one after the other. I went AFK for a bit and died afterwards, after which the grave waypoint didn't appear(I checked if I haven't changed the minimap's settings accidentally,didn't seem to be the case, to make sure I killed my character,which didn't create a waypoint. Luckily the graves were there). The quest book just got completley reset and after I completed the ones I had already finished with a little help from creative mode I noticed that the loot boxes weren't generating loot( IIRC the message they were giving was something along the lines of "loot tables not set"). I feel like the spice of life problem is pretty self explanatory. I tried loading a backup from 2 hours before it started,sadly the problems were still there. 

**Logs**
I'm not sure which logs could help with this, but if one is required I'll try to provide them ASAP. Thanks in advance.

**Comment by NillerMedDild** [comment]
The Spice of Life issue is known, cannot be fixed as far as I know :(

In regards to quest issues:

`/bqs_loot default load` to restore loot chests
A backup of your questdata exists within your world folder, you'll need to retrieve and restore that

In general it sounds like your instance got messed up, I recommend that you reinstall. I'm going to attach a link to my Discord in case you need further assistance - That doesn't mean you're not allowed to continue to post here, feel free to do so :)
