### ISSUE TITLE
PlusTiC Removed from Curseforge, update required!

### ISSUE THREAD

**Issue by NLBlacky** [NillerMedDild/Enigmatica2Expert#1658]
https://www.reddit.com/r/feedthebeast/comments/g3fekk/looks_like_plus_tic_and_all_of_landmasters_mods/

The mod plustic is no longer available on Curseforge due to breaking Curseforge's ToS. Since Enigmatica 2 Expert is using this mod, Enigmatica 2 Expert will no longer be downloadable till this mod has been removed from the modpack. I believe a few other mods below this developer were removed as well but I have no names.

**Comment by NillerMedDild** [comment]
The modpack can still be downloaded :)

**Comment by 2ndkirbyever** [comment]
The modpack can still be downloaded, but new downloads will not contain PlusTiC, breaking the mining levels and recipes.

**Comment by NillerMedDild** [comment]
@2ndkirbyever Are you certain, have you tested?

**Comment by NLBlacky** [comment]
I downloaded a pack earlier today with this mod in it as well, which worked suprisingly. Usually when a mod becomes unavailable, the modpacks will no longer be downloadable. Perhaps there is a small buffer time before it takes effect, but for that I'm not sure. I wouldn't recommend to wait too long with a small update to fix this.

**Comment by NillerMedDild** [comment]
Thanks for the heads up either way :)

**Comment by aaronhowser1** [comment]
https://www.curseforge.com/minecraft/mc-mods/plusticminusbad

**Comment by xJon** [comment]
@NillerMedDild Do you have any idea what's the current alternative in the CurseForge platform, whenever one updates a modpack containing PlusTiC?

**Comment by Discomanco** [comment]
> 
> 
> @NillerMedDild Do you have any idea what's the current alternative in the CurseForge platform, whenever one updates a modpack containing PlusTiC?

That would be the `plusticminusbad` link that's above

**Comment by xJon** [comment]
> > @NillerMedDild Do you have any idea what's the current alternative in the CurseForge platform, whenever one updates a modpack containing PlusTiC?
> 
> That would be the `plusticminusbad` link that's above

Do you mean `xXx_MoreToolMats_xXx` with the picture of smelly, smiling cheese?

**Comment by Discomanco** [comment]
> 
> 
> > > @NillerMedDild Do you have any idea what's the current alternative in the CurseForge platform, whenever one updates a modpack containing PlusTiC?
> > 
> > 
> > That would be the `plusticminusbad` link that's above
> 
> Do you mean `xXx_MoreToolMats_xXx` with the picture of smelly, smiling cheese?

That is exactly the one I mean
