### ISSUE TITLE
E2E keeps crashing

### ISSUE THREAD

**Issue by skyboy1963** [NillerMedDild/Enigmatica2Expert#1659]
**Modpack version**
1.80

**Issue**
Game crashes every time I try to start it, only happens for E2E. I previously had an issue with updating to 1.80, so maybe it is connected?

**Logs**

**Comment by PiggyWhiskey** [comment]
Have you tried on a new World? It might be an issue with your Save

**Comment by skyboy1963** [comment]
It's when I launch the instance, not the world

**Comment by NillerMedDild** [comment]
I need the crash report, or latest.log if there is no crash report.

**Comment by skyboy1963** [comment]
https://pastebin.com/rmeSiYP5 Here is the latest.log

**Comment by NillerMedDild** [comment]
You appear to be using outdated Java. This is often caused by Twitch defaulting to an older version than you have available. Follow these steps to update.

* Make sure you have the latest 64-bit Java installed
    https://www.java.com/en/download/manual.jsp Windows Offline (64-bit) is the one you need
* Go to the Twitch Minecraft settings
* Add `-version:1.8+` to the Additional Arguments

**Comment by skyboy1963** [comment]
I updated my java and added the additional argument, but I am still getting the same error. https://pastebin.com/VhjVqVQm

**Comment by NillerMedDild** [comment]
Please reinstall the modpack and let me know if that works :)

**Comment by skyboy1963** [comment]
That seemed to do the trick thanks!
