### ISSUE TITLE
Game crash

### ISSUE THREAD

**Issue by ginkoopl** [NillerMedDild/Enigmatica2Expert#166]
Game crashes whenever I try to see the recipes that glowstone block can be used in. (hotkey U, also tried right clicking it through NEI)

LATEST modpack version, 1.33

https://pastebin.com/nQ4daiyu

**Comment by NillerMedDild** [comment]
The issue has been reported to the mod author of Tinker I/O, thank you for the report.
https://github.com/gkbm2013/tinker-IO/issues/80

**Comment by Crusaderkvw** [comment]
I would ,like to add to this conversation with my own report. I noticed that when trying to see what an Item is used for with JEI (U button) the game crashes.  

Modpack version: 1.34.
Forge version: 14.23.4.2739.

I have 2 crash reports, thought it was just an oddity at first but the second crash confirmed it was a crash with the U button use.

[crash-2018-08-04_17.23.11-client.txt](https://github.com/NillerMedDild/Enigmatica2Expert/files/2259581/crash-2018-08-04_17.23.11-client.txt)
[crash-2018-08-04_17.11.07-client.txt](https://github.com/NillerMedDild/Enigmatica2Expert/files/2259582/crash-2018-08-04_17.11.07-client.txt)

**Comment by NillerMedDild** [comment]
That's a completely seperate issue @Crusaderkvw, do not piggyback issues.

**Comment by bigyihsuan** [comment]
I'm having a similar issue to OP. This was triggered by showing the uses of a Thermal Expansion Portable Tank (Basic), although the crash also triggered from showing the uses of a vanilla Spider Eye.

The crash was on 1.34, but I've gotten a crash in 1.33, possibly 1.32, also. However, I don't have the crash log for the Spider Eye case.

https://paste.ee/p/ff775

**Comment by Lantorer** [comment]
I just had the same problem that my game crashed, I've had it before with glowstone & basic portable tank but this time when I pressed U for uses on cobblestone it crashed my game. 

The game crashed whilst updating screen events
The game crashed whilst updating screen events
Error: java.lang.RuntimeException: Block Block{randomthings:plate_extraction} (class lumien.randomthings.block.plates.BlockExtractionPlate) belonging to item 1xtile.plate_extraction@0 failed to convert its item damage into a blockstate. This is
[crash.txt](https://github.com/NillerMedDild/Enigmatica2Expert/files/2261731/crash.txt)
 a bug in the mod 'Random Things'.

**Comment by NillerMedDild** [comment]
There's really no reason to add to this issue, it will be resolved when the mod dev in question has time to fix it.
