### ISSUE TITLE
Arcane Crafting Engine: Order crystal clusters disappear, with very little flux in chunk.

### ISSUE THREAD

**Issue by eyekantspel** [NillerMedDild/Enigmatica2Expert#1661]
**Modpack version**
1.77

**Issue**
Order crystal clusters required for the arcane crafting engine disappear after placement.

Flux in the chunk is at 14, which seems to be the ambient level (ranges from 12 to 17 in various places where no Thaumcraft has been done). Tested creating the arcane crafting engine in a chunk with 14.2 flux as well.

Also of note, the vis batteries in the arcane crafting engine do not seem to be charging.

**Comment by NillerMedDild** [comment]
How much Vis is in the chunk? If I remember correctly, crystals blocks can be consumed by the chunk to regenerate vis.

**Comment by eyekantspel** [comment]
Looks to be near max, shows 168.8 currently and the amount is on/past the marker that can be seen with the thaumometer.

[https://i.imgur.com/0a6KVO8.png](url)

**Comment by eyekantspel** [comment]
Ok, did some further testing. Although the meter shows a vis and flux amount, it's from wherever chunk I last checked. A second player on the server claimed he saw 0 essentia at the same time I saw the 168.8.

After leaving the compact machine we were in, checking a different chunk, and going back to the compact machine with the arcane crafting engine, we now saw the same number, but it was 135 vis in the chunk according to the meter. Checking the work table without the charger on top shows the chunk as having 0 Vis.

I'll move the arcane crafting engine into another compact machine, and re-test this.

**Comment by MorganSimic** [comment]
The aura tends to break at random wich causes it to have 0 vis in it. There is nothing that can be done about it, other than to wait for it to fix itself. It's broken in thaumcraft. So that's where the 0 vis weirdness comes from. So if you check a workbench and see 0 vis or check with the scanner thingy and the vis number doesn't fluctuate from chunk to chunk that means aura is gone.
I could see that breaking the crystals.

**Comment by eyekantspel** [comment]
After moving the arcane crafting engine into a third compact machine, it seems I *lucked* out on finding two freak chunks that actually had 0 vis in them, further confused by the thaumometer repeating the last measurements it saw from chunks that had it still.

As Morgan commented (thanks for the help in discord btw!), moving seems to have fixed the issue.

**Comment by MorganSimic** [comment]
Well, there is no guarantee of the aura not breaking again sadly.
