### ISSUE TITLE
Capability adapter & Quantum Ring do not have alternative recipes if channels are disabled.

### ISSUE THREAD

**Issue by LordHellscream** [NillerMedDild/Enigmatica2Expert#1662]
Based on what I've gathered from discord, having channels disabled should be a supported scenario since recipes such as Neutron collector and modular controller both default to use energy acceptor when channels are disabled.

(if not then I'm ok with that..)

However, capability adapter and quantum ring (which requires dense covered cable or dense smart cable, also disabled when channels are) do not have alternative recipes.

Thanks.

**Comment by NillerMedDild** [comment]
We'll get that fixed, thanks :)

**Comment by LordHellscream** [comment]
Quantum ring may also be the same case (I am not in the game to confirm just wanna put it here in case i forget)
Thanks!

**Comment by NillerMedDild** [comment]
And you disabled channels when you checked these recipes, right?

**Comment by LordHellscream** [comment]
Yep. Just started the game now here are screenshot:
Capability Adapter:
https://imgur.com/MUJoQqP
Quantum Ring:
https://imgur.com/0InkOT2

If you can kindly let me know what you will be using for replacement that will be awesome, consider the whole Landmaster situation we may not get an update soon :)

Thanks for the awesome mod pack.

**Comment by LordHellscream** [comment]
@NillerMedDild can you share your plan of what to  use to replace the recipes? So i can  mitigate this temporarily from creative mode. Thanks !

**Comment by NillerMedDild** [comment]
I haven't decided yet I'm afraid.

**Comment by LordHellscream** [comment]
what about ender io ME dense conduit? those are not disabled by the config. and cost  about the same with the ME dense cables.

**Comment by NillerMedDild** [comment]
Brilliant idea!
