### ISSUE TITLE
Thermal Expansion Compactor/Sequential Fabricator Quest Icons are Switched

### ISSUE THREAD

**Issue by mpg0907** [NillerMedDild/Enigmatica2Expert#1663]
Modpack version
1.79a

Issue
blood magic tier 3 altar quest ddont work with glowstone and`teh picture in the thermal expension quest line from teh sequental fabricator and the compacter are switched.

dont know if these has been fixed on newer versions.

**Comment by NillerMedDild** [comment]
Thanks for the report, I'll investigate. Are you sure the Blood Magic Altar Tier 3 doesn't trigger when you have the required items? Please keep in mind there can be multiple pages of tasks.

**Comment by mpg0907** [comment]
with the glowstone thign i emant teh quest. teh quest only accept sea lanters

**Comment by NillerMedDild** [comment]
Are you sure about that? Please check for additional quest pages.

**Comment by mpg0907** [comment]
i just checke dand i nwo it did work. maby it was somethign on my server
