### ISSUE TITLE
Can't insert Clock nor Compass into Induction Smelter

### ISSUE THREAD

**Issue by fuhrriel** [NillerMedDild/Enigmatica2Expert#1664]
**Modpack version**
1.80

**Issue**
![image](https://user-images.githubusercontent.com/49496299/79899654-60b2e700-840d-11ea-95ac-a3f670584202.png)
This recipe doesn't work, there is no way to insert clock nor compass into Induction Smelter, tried by hand, with hopper, conduits and itemducts. Recipe is pretty needed as it's the only way to reasonably automate rich slag production.

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by Smfrost** [comment]
I am having the same issue and I am on verison 1.80 as well! Was about to make an issue till i saw this!

**Comment by NillerMedDild** [comment]
You didn't lock the Induction Smelter or anything like that right? :)

**Comment by fuhrriel** [comment]
Tried with both flux slot locked and unlocked, on 2 smelters in survi and 2 in creative. Checked some ore recipes and all were working correctly on same smelters with exact same config.

**Comment by Smfrost** [comment]
![2020-04-24_13 12 01](https://user-images.githubusercontent.com/55335809/80243714-51aa7f80-862d-11ea-842a-bb042aff7d6e.png)
![2020-04-24_13 12 12](https://user-images.githubusercontent.com/55335809/80243721-53744300-862d-11ea-8917-453871dfce31.png)
![2020-04-24_13 12 18](https://user-images.githubusercontent.com/55335809/80243726-566f3380-862d-11ea-8e41-88383549fbfe.png)
![2020-04-24_13 12 23](https://user-images.githubusercontent.com/55335809/80243730-5838f700-862d-11ea-87da-200070f037b9.png)


Images with unlocked and locked, with compass and clock not working. I did double check to confirm. It appears to not be working.

**Comment by NillerMedDild** [comment]
Perfect, thanks a lot!

**Comment by NillerMedDild** [comment]
I reported the issue on the CoFH Discord, but they sadly only fix critical issues for 1.12, which is understandable. I will try to fix this with CraftTweaker, but I doubt it'll work to be honest.

**Comment by Smfrost** [comment]
Thanks for trying. I'm no programmer but you have my respect +.

**Comment by TafiKoi** [comment]
I play in the same server as Smfrost and i think i found the issue. When you craft a clock it has no ntb tags. However when u add it to your inventory the quark mod automatically adds an ntb tab. I assume the induction smelter looks for a clock without any tags and rejects it due to the tag existing.

**Comment by TafiKoi** [comment]
After some testing i found a work around. If u use some kind of auto-crafter and pipe the clock/compass into the induction furnace it will accept and process it.

@fuhrriel 

 
![2020-05-07_17 21 42](https://user-images.githubusercontent.com/64995033/81356995-723ff400-9087-11ea-9f6a-f83e5cb3b788.png)
![2020-05-07_17 21 46](https://user-images.githubusercontent.com/64995033/81356998-72d88a80-9087-11ea-8966-c94353314745.png)

**Comment by NillerMedDild** [comment]
Good work!

**Comment by TheUnolyGamer** [comment]
If you need a quick work around or if your playing in the outdated version crafting the clock then droping it directly from the crafting menu and never letting it get put in your inventory and have a vacuumulater pick it up then put it in the induction smelter the NBT tag isnt added. (tested and working)

**Comment by OshidaBCF** [comment]
Did this bug was fixed for 1.12.2 ? or it is only for later versions ?
