### ISSUE TITLE
Item Placeholder in Epic tier reward: Resonant Exchanger

### ISSUE THREAD

**Issue by AnAngryBrit** [NillerMedDild/Enigmatica2Expert#1665]
**Modpack version**
1.80

**Issue**
Item Placeholder in Epic tier reward, 
exchangers:resonant_exchanger/0

looks like the resonant exchange is still in the rewards table despite the mod having been removed in favour of the building gadget.
 
Relevant change log.
1.80
Using Forge-1.12.2-14.23.5.2847
Exchangers Outclassed by Building Gadgets, sorry :(

**Logs**
N/A

**Comment by NillerMedDild** [comment]
Thanks for the report :D
