### ISSUE TITLE
Issue of FTB and Cyclic

### ISSUE THREAD

**Issue by EternisField** [NillerMedDild/Enigmatica2Expert#1666]
**Modpack version**
Enigmatica2Expert-1.80

**Issue**
The server OP uses the My Server settings in the FTB client settings to modify the nickname resulting in the Cyclic Extended Inventory being cleared.
The specific operation is as follows:
Press E to open the backpack, click Client Settings at the top left of FTB, then enter My Server Settings, then modify Nickname, and then Cyclic's Extended Inventory is cleared.
(machine translation)

**Logs**
None

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by EternisField** [comment]
I don 't know what happened. I asked my friend to try. He changed his nickname and then changed it back. The disappeared items reappeared, but I couldn' t.

**Comment by NillerMedDild** [comment]
I'm sorry but it's a bit too circumstantial to try and fix.
