### ISSUE TITLE
Arcane Workbench can't be craft

### ISSUE THREAD

**Issue by PC121295** [NillerMedDild/Enigmatica2Expert#1667]
**Modpack version**
1.80

**Issue**
Can't craft Arcane Workbench from Thaumcraft.
To craft it we need to right click with Salis Mundus on a vanilla crafting table.
But the vanilla crafting table is replace by the crafting Table from the mod FastWorkBench.

**Comment by NillerMedDild** [comment]
This may be a stupid question, but have you tried? :)

**Comment by PC121295** [comment]
yes it's like that a found the prob. i only can open the table. And it's not a stupide question XD

**Comment by NillerMedDild** [comment]
I don't quite understand, did you get it to work?

**Comment by DanielLowry** [comment]
Same issue for me, but got it to work by applying Salis Mundus to crafting station from Tinker's instead.  Would be helpful to have the quest updated with the correct item?

**Comment by NillerMedDild** [comment]
Did you do the steps leading up to crafting the workbench? Getting Crystals and then sleeping?
