### ISSUE TITLE
Please add TheBOMPlugin

### ISSUE THREAD

**Issue by brch-cndy** [NillerMedDild/Enigmatica2Expert#1668]
I'm sorry if this is the wrong place, but I find this mod increasingly helpful and useful. I think it would make a great addition to the pack.

https://www.curseforge.com/minecraft/mc-mods/thebomplugin

**Comment by NillerMedDild** [comment]
It's the right place :)

That mod has previously been in the pack, but it just made JEI less user friendly imo.
