### ISSUE TITLE
Cannot transmute iron ore to Astral Sorcery's starmetal ore

### ISSUE THREAD

**Issue by rolovis** [NillerMedDild/Enigmatica2Expert#167]
#### Issue Description
Iron ore is never transmuted to starmetal ore when linked to an altar's collector crystal. Using a world-generated altar and the linking tool, and the crystal has a clear view of the sky. Particles appear above the ore like it is undergoing transmutation, but the transmutation never completes. Everything is in the same chunk, which is chunkloaded. I've also tried idling right next to the ore for a few nights, but nothing happens. Lenses don't seem to help the process either.
#### Modpack version (Do not use "latest")
1.33

**Comment by rolovis** [comment]
It never occurred to me to try a different altar, which of course worked almost immediately for some reason. Derp.

**Comment by NillerMedDild** [comment]
I believe this issue is caused by errors in the Starlight field, some world gen crystals simply don't work.
