### ISSUE TITLE
RFTools Storage Scanner Crash

### ISSUE THREAD

**Issue by osmanosman88** [NillerMedDild/Enigmatica2Expert#1671]
**Modpack version**
1.80 

**Issue**
Rendering screen crash when opening rftools storage scanner on a server where this crash has happened for anyone who tries to open it. I assume it's a thaumcraft RecipeMagicDust causing it.

**Logs**
https://pastebin.com/a2vijVAC

**Comment by NillerMedDild** [comment]
Thanks for the report - Looks like this was reported to the Thaumcraft tracker back in April last year.
https://github.com/Azanor/thaumcraft-beta/issues/1670

**Comment by osmanosman88** [comment]
Thanks for the quick response! Was wondering any way I can get rid of this recipe? I broke the storage scanner and placed it down again but I still crashed.

**Comment by NillerMedDild** [comment]
You would most likely have to edit it's NBT data, somehow. I recommend either loading a backup or removing the block completely.

**Comment by osmanosman88** [comment]
Removed it and spawned in a new one. Thanks for the help :)

**Comment by NillerMedDild** [comment]
You're welcome, thanks for the report.

**Comment by NillerMedDild** [comment]
I do not believe I can fix this, and the majority of modders no longer support 1.12, so I'll close this issue.

Nethertheless, thank you for reporting :)
