### ISSUE TITLE
Forestry Logs cannot be cut in Mekanism sawmill or Nuclearcraft Manufactory

### ISSUE THREAD

**Issue by stevenkxu** [NillerMedDild/Enigmatica2Expert#1674]
**Modpack version**
1.80

**Issue**
Tried with Maple, Desert Acacia, Willow, and Teak. The only 3x planks recipe for these logs are the TE sawmill and the IC2 Block Cutting Machine. Thought I'd bring this up to see if it's intended behavior.

**Comment by NillerMedDild** [comment]
It's laziness to be honest :P We haven't added the recipes for them.

**Comment by Krutoy242** [comment]
> It's laziness to be honest 

I can make PR with this fix if you want (in ~10 days i guess)

**Comment by NillerMedDild** [comment]
That would be much appreciated :D

**Comment by Krutoy242** [comment]
Ok, gotcha.
