### ISSUE TITLE
Strange Reaction after Firing a crossbow while riding a horse.

### ISSUE THREAD

**Issue by Igbathscaller** [NillerMedDild/Enigmatica2Expert#1676]
**Modpack version**
1.78

**Issue**
I rode an animania horse (i believe it was a draft or smth, untamed), then I use a tinkers construct crossbow with blizzard and endspeed bolt. I fell into the void and my coordinates are undecipherable and claim i fell into the void.
It said something along the lines of invalid player move packet
There are no crash logs, since it seems the server is just kicking me
https://imgur.com/a/g7XZXv0

**Comment by NillerMedDild** [comment]
What the hell :P
Can you reproduce this on 1.80?
If you can, please supply a latest.log and the server's latest.log from a time where it happened.

**Comment by Igbathscaller** [comment]
I'll try. I hope it was just dumb luck though.

**Comment by Igbathscaller** [comment]
I've managed to recreate it in 1.78 on a flat world server

**Comment by Igbathscaller** [comment]
https://drive.google.com/file/d/1rKZTzMr1VpDLlg4Ydoza04qOqqgzE7lr/view?usp=sharing

**Comment by NillerMedDild** [comment]
Alright thanks. I'll try to reproduce it on 1.80 :)

**Comment by NillerMedDild** [comment]
It still happens on 1.80 in the world you sent. Yikes, what a strange issue.

**Comment by Igbathscaller** [comment]
I believe it is primarily due to the Blizzard from plustic. It freezes invulnerable mobs as well as other things that shouldn't be affected (e.g. you can hit dead frozen mobs multiple times before they disappear, you can freeze the wither before it is done charging up, and you can freeze mobs you are riding on as well as armor stands.)

**Comment by NillerMedDild** [comment]
Perhaps, but it doesn't happen with a pure Ice Dragonsteel Crossbow + Endspeed Bolts.

**Comment by Igbathscaller** [comment]
I think bows from tinkers construct cannot use damage boosts or effects, only the bolts and arrows can. Does it freeze mobs when you used your weapon?

**Comment by NillerMedDild** [comment]
I didn't notice, it one-shotted everything ^^' 
Anywho, if the Blizzard trait is the issue, this isn't going to be fixed, PlusTiC is dead :/

**Comment by Igbathscaller** [comment]
I'm just going to be more careful with the trait from here on, but it seems to be very buggy.

**Comment by bibo38** [comment]
> PlusTiC is dead :/

Just weird... The repository had it's last commits in April, not that far away. But since then it seems to have shut down it's issue tracker and deleted the Curseforge mod page. It's just interesting, that Enigmatica can still get the required mod files, but looking at the Curseforge Dependency list, it isn't listed there anymore.

**Comment by NillerMedDild** [comment]
I've decided not to take this issue any further, as most modders no longer work on Minecraft 1.12, and development of Enigmatica is focused on Minecraft 1.15+ - I hope that's understandable :)
Thank you for helping to make E2E polished by reporting, I hope to see you in E5+!
