### ISSUE TITLE
'RedstoneFlux-1.12-2.1.1.1-universal.jar' caused the error 'Exception in server tick loop'

### ISSUE THREAD

**Issue by FreeGamer5201** [NillerMedDild/Enigmatica2Expert#1677]
**Modpack version**
1.80

**Issue**
I am trying to host a server using this modpack, but every time I start the server, I get an error stating redstoneflux caused an exception in server tick loop error. This is after it can't find a certain signature.

**Logs**
[crash-2020-04-28_15.30.09-server.txt](https://github.com/NillerMedDild/Enigmatica2Expert/files/4546878/crash-2020-04-28_15.30.09-server.txt)

**Comment by NillerMedDild** [comment]
You added the mod [ServerInfoProvider-1.12.1-3.0.36](https://www.curseforge.com/minecraft/mc-mods/serverinfoprovider), that's the issue. According to the changelog of ServerInfoProvider, this issue is fixed in version `3.0.38`
