### ISSUE TITLE
Can we include a ComputerCraft peripheral library, e.g. plethora?

### ISSUE THREAD

**Issue by codeka** [NillerMedDild/Enigmatica2Expert#168]
Two related requests here.

1. Can we replace vanilla ComputerCraft with [CC: Tweaked](https://minecraft.curseforge.com/projects/cc-tweaked)? CC: Tweaked is a fork of CC that has some better properties. In particular, it has full-block wired modems which allow you to connect modems to chests -- vanilla CC can't even interface with vanilla chests!

2. Can we include a peripheral library, such as [plethora](https://squiddev-cc.github.io/plethora/)? This library includes things like interfacing with the in-game chat (which you can disable on servers), interfacing with AE system, and so on.

About the only issue I had, was I had to compile plethora manually because the latest release is fairly old and has some AE integration bugs (I filed https://github.com/SquidDev-CC/plethora/issues/134 to see if they'll do a new release with all the bug fixes).

**Comment by NillerMedDild** [comment]
Both mods seem to be too unstable to add, and I don't think either would benefit the average player, sorry.

**Comment by codeka** [comment]
I'm playing SP, so I'm just going to keep using my own installation of the mods ;)

**Comment by SquidDev** [comment]
> Since CC:T is a fork of CC, will swapping the mods keep items and blocks from CC on saves?

Yep! You can switch from CC to CC:T without any issues. You can go the other way too with minimal problems, though you'll obviously lose any full block modems. This is something I test quite a lot, as I end up loading the same world in multiple workspaces.
