### ISSUE TITLE
replace nuclearcraft 1.0 with 2.0

### ISSUE THREAD

**Issue by noa12390** [NillerMedDild/Enigmatica2Expert#1680]
https://www.curseforge.com/minecraft/mc-mods/nuclearcraft-overhauled/files/2944669

just a sugestion nothing more and it is warned in their discord that 1.0 and 2.0 to put it mildly hate each other so if this was to be added any already made worlds likely will have to be wiped

**Comment by NillerMedDild** [comment]
I don't think breaking worlds is worth it for one mod :)
