### ISSUE TITLE
Every time I enter the archive, press e to open the backpack, the contents of the backpack will jump around

### ISSUE THREAD

**Issue by nethcx** [NillerMedDild/Enigmatica2Expert#1682]
**Modpack version**1.80
Input version here

**Issue**
Input short description of the issue here

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by NillerMedDild** [comment]
What is "the archive"? Which Backpack are you using?

Sounds like you've bound inventory sorting to some key you often use.
