### ISSUE TITLE
Game crash on boot

### ISSUE THREAD

**Issue by helhel1** [NillerMedDild/Enigmatica2Expert#1683]
**Modpack version**
1.80

**Issue**
When loading a client, a crash occurs

**Logs**
[1.txt](https://github.com/NillerMedDild/Enigmatica2Expert/files/4570389/1.txt)

**Comment by Discomanco** [comment]
You appear to be using outdated Java. This is often caused by Twitch defaulting to an older version than you have available. Follow these steps to update.

* Make sure you have the latest 64-bit Java installed
    https://www.java.com/en/download/manual.jsp Windows Offline (64-bit) is the one you need
* Go to the Twitch Minecraft settings
* Add -version:1.8+ to the Additional Arguments
