### ISSUE TITLE
Strange behavior with ae2 wireless terminal in space.

### ISSUE THREAD

**Issue by LahiruVIP** [NillerMedDild/Enigmatica2Expert#1684]
**Modpack version**
1.80

**Issue**
While in space you can access the ea2 wireless terminal. you can acces the items stored in the me system and start autocrafting. However you cannot craft inside the crafting with the JEI move items button. You can craft in the crafting terminal by manually putting items into it. All this without having an wireless access point in space. There is a chat message saying "Wireless out of range" but it doesn't kick you out of the wireless terminal.

Edit: happens in all advanced rocketry dimension/planets.

**Comment by NillerMedDild** [comment]
Thanks for the report. It has been reported on the mod's issue tracker here: https://github.com/p455w0rd/WirelessCraftingTerminal/issues/348

**Comment by NillerMedDild** [comment]
I do not believe I can fix this, and the majority of modders no longer support 1.12, so I'll close this issue.

Nethertheless, thank you for reporting :)
