### ISSUE TITLE
Help understanding crash

### ISSUE THREAD

**Issue by ValaheilX** [NillerMedDild/Enigmatica2Expert#1685]
**Modpack version**
1.80

**Issue**
Server starts for a few moments and crashes, I understand the ridiculous tick time but not what is causing it.

**Logs**
https://pastebin.com/xzrz3H8H

**Comment by ValaheilX** [comment]
![unknown](https://user-images.githubusercontent.com/39144942/80921776-3b877800-8d2d-11ea-9091-b9babea33351.png)
It looks like its ae from lag goggles

**Comment by NillerMedDild** [comment]
That it does. I recommend that you sex `max-tick-time` to -1 in the server.properties, maybe the lag will blow over once the initial lag spike is "processed".
