### ISSUE TITLE
Pattern storage says 0EU, but replicator consumes power

### ISSUE THREAD

**Issue by NatMath** [NillerMedDild/Enigmatica2Expert#1687]
**Modpack version**
1.77

**Issue**
On the pattern storage, every item show 0EU energy consumption, but obviously replicator still consumes power when replicating

**Logs**
N/A
![2020-05-03_16 09 47](https://user-images.githubusercontent.com/64751772/80924732-a00bfc80-8d58-11ea-8a5b-86b988b16c31.png)

**Comment by NillerMedDild** [comment]
I know, I think it's just bad design from IC2's side :P The Machine determines energy usage, not the pattern.
