### ISSUE TITLE
Unregisted minecraft item

### ISSUE THREAD

**Issue by 3qw** [NillerMedDild/Enigmatica2Expert#1688]
**Modpack version**
version 1.80
**Issue**
Internal Exception: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalStateException: Recipe minecraft:furnace
(net.minecraft.item.crafting.ShapedRecipes@58c80967) produces unregistered item minecraft:furnace
(net.minecraft.item.ItemBlock@780dbed7
[Dg5JTqpq.txt](https://github.com/NillerMedDild/Enigmatica2Expert/files/4572497/Dg5JTqpq.txt)
[Dg5JTqpq.txt](https://github.com/NillerMedDild/Enigmatica2Expert/files/4572498/Dg5JTqpq.txt)

**Comment by NillerMedDild** [comment]
Please provide a lot more information. What happened? What did you expect to happen? And a full latest.log please.
