### ISSUE TITLE
Items not appearning on TiC Casting Table

### ISSUE THREAD

**Issue by mathranger101** [NillerMedDild/Enigmatica2Expert#169]
#### Modpack version: 1.33

This does not happen in 1.32, and the only thing I see in the change-log is "Tinker's Construct: Disabled the in-world render of most blocks, to avoid a tessellating block crash." Is this a by-product of this change or is it an unrelated bug?

[screenshots](https://imgur.com/a/ZUDfyO6)

**Comment by NillerMedDild** [comment]
It's not a by-product of that change it *is* that change.
I am reverting the change in 1.34
