### ISSUE TITLE
Molten Salt Reactor Configs are weird/not really useable

### ISSUE THREAD

**Issue by Thalzamar** [NillerMedDild/Enigmatica2Expert#1690]
Enigmatica 2 Expert v1.8

Heaters for MSR are boosted by a Factor of 15-23 but Fuel has default Heatsettings
which makes the most viable Fuel HE-Cf-251(base Heat of 1200)
 since you can even cool a 20 cell 600% effiency design 237600Hu/t
also you have reduced the CoolentHeatMultiplier to 30 which is reasonable but further enhances the issue since less steam is made in Heat Exchangers from hotCoolent, the conductivity nerf does not help it either
i recommend using default settings for Heaters and Heat gen
boosting the conductivity of thermoconductive alloy to either to standard 1.25 or even 1.3 to reward upgrading to the best tubes
also people need the higher conductivity is larger Heat Exchanger to use up all the hotCoolent and not to clogg up the Heaters with hotCoolent so they don't cool the reactor anymore
my last recommendation is boosting the rf/mb from turbines for High Pressure Steam(HPS) and Low Pressure Steam(LPS) to 80rf/mb(HPS) and 20 mb/rf (LPS)
Turbines can even be boosted more since it's fairly complex setting up a functioning Steam Cycle to get the most RF out of MSR's
 watch the Tutorial made by the Nuclearcraft dev to understand what goes into building the complete cycle
https://www.youtube.com/watch?v=hg69-3e-gdE&t=177s

i hope this helps making the modpack better

**Comment by NillerMedDild** [comment]
Thanks for the report, looks like you put a lot of thought into this! I will look into implementing the changes you suggested :)

**Comment by Thalzamar** [comment]
Someone in the Nuclearcraft Discord asked for a Molten Salt Reactor, so i opened up the Modpack to see what you guys had changed, it showed a flawed understanding of the Molten Salt Reactor and since not many build them because of their complexity/scale i came here to give you guys a heads-up 
 i propose those changes so that the reward for MSR are worth it in default they are 32x as effective as a solid fission of the same size and Fueltype
once the whole thing is running it's far more maintenance easy than a fusion reactor but the setup and the mechanics are quite the challange

**Comment by Thalzamar** [comment]
[Tutorial MSR Spreadsheet.xlsx](https://github.com/NillerMedDild/Enigmatica2Expert/files/4588900/Tutorial.MSR.Spreadsheet.xlsx)
![MSR Tutorial 32kTbu](https://user-images.githubusercontent.com/48890032/81216962-1ff5c900-8fdc-11ea-9a05-d4e83495c1c0.png)
[only Salt.txt](https://github.com/NillerMedDild/Enigmatica2Expert/files/4588907/only.Salt.txt)
to give you an understanding how complex MSR i have attached a .txt where the default salt crafting is in it (i don't know how much Crafttweaking you guys have done)
a picture of a little MSR and the spreadsheet with default settings
how much it would produce with Pre-heated Water and  copper pipes and the size of the Heat-exchanger (water contacts)
it should give you a better idea how everything relates to each other and how complex it is all in all
it also shows why the heater boost was bad since the more you overcool a MSR the worse it works

**Comment by NillerMedDild** [comment]
I regenned the salt_fission and turbine parts of the config, I think that'll be the safest approach :)

**Comment by NillerMedDild** [comment]
I regenned the salt_fission and turbine parts of the config, I think that'll be the safest approach :)
