### ISSUE TITLE
find replacement for better questing

### ISSUE THREAD

**Issue by loordgek** [NillerMedDild/Enigmatica2Expert#1691]
https://twitter.com/quat1024/status/1258094747241140225
if better questing gets banned from curseforge you are screwed
i just let you know

**Comment by loordgek** [comment]
https://github.com/Funwayguy/BetterQuesting/blob/1.12/src/main/java/betterquesting/network/PacketAssembly.java#L180-L211

**Comment by loordgek** [comment]
https://twitter.com/quat1024/status/1258117461716676608

**Comment by NillerMedDild** [comment]
Thanks for letting me know.

**Comment by loordgek** [comment]
ask curseforge if they are going to do something about it before you are going to redo the quests

**Comment by Discomanco** [comment]
Lets not jump the fence on this one yet, and wait and see what actually happens
https://www.reddit.com/r/feedthebeast/comments/geqo1q/in_the_better_questing_update_new_code_was_added/fppri6w/

**Comment by KleinGrrmpf** [comment]
I wish there was HQM for 1.12... It was so much better than BQ

**Comment by Discomanco** [comment]
Not if you're making quests.
HQMs quest builder is horrible. At least if it hasn't changed since 1.10
