### ISSUE TITLE
Advanced Rocketry Warp controller

### ISSUE THREAD

**Issue by Thornodin** [NillerMedDild/Enigmatica2Expert#1692]
**Modpack version**
1.80

**Issue**
Warp controller doesn't recognize the deposited dilithium crystals in the warp core multiblock. Preventing you from warping to any new planets. status of warp controller is NOT READY and 0 fuel even after I deposited 2 stacks of 64 dilithium crystals into the Warp core input hatch.

**Comment by NillerMedDild** [comment]
Thanks for the report. Have you tried breaking and replacing the Warp Controller and/or Warp Core? The Warp Controller may need to be placed after the Core.
Could you please provide screenshots of your setup?

**Comment by Thornodin** [comment]
I reconstructed it and now it works. 
![2020-05-07_08 20 28](https://user-images.githubusercontent.com/51204119/81294361-c83b7a00-903c-11ea-8963-2da6ca029e44.png)
![2020-05-07_08 20 41](https://user-images.githubusercontent.com/51204119/81294370-cbcf0100-903c-11ea-9c10-eef6fd472518.png) (this picture is before I rebuild the core)
![2020-05-07_08 24 10](https://user-images.githubusercontent.com/51204119/81294444-e86b3900-903c-11ea-87cd-a88cafbbb783.png)
![2020-05-07_08 24 53](https://user-images.githubusercontent.com/51204119/81294450-eacd9300-903c-11ea-8f75-52ac65b124da.png)
![2020-05-07_08 25 16](https://user-images.githubusercontent.com/51204119/81294460-eef9b080-903c-11ea-9840-b7e688298815.png)
![2020-05-07_08 25 21](https://user-images.githubusercontent.com/51204119/81294472-f325ce00-903c-11ea-9008-828b20c2ea1b.png)
![2020-05-07_08 25 46](https://user-images.githubusercontent.com/51204119/81294494-f9b44580-903c-11ea-8ac6-59031fbe53a0.png)
last one is when rebuild completed now the fuel lvl show 1000 and the warp controller "ready"

I do have to note when reconstructing the core I've noticed an X showing up on the second layer after I placed the structure frame down then after a couple of seconds it was gone.

**Comment by NillerMedDild** [comment]
Hmm, odd, but I'm glad it works now :)
