### ISSUE TITLE
Keeps crashing on loading screen. I love this modpack but can't play ;-;

### ISSUE THREAD

**Issue by itzdarkfael** [NillerMedDild/Enigmatica2Expert#1694]
**Modpack version**
1.80

**Issue**
When I load it keeps crashing all time, I tried a lot to solve but couldn't 

**Logs**

[hs_errpid2324.txt](https://github.com/NillerMedDild/Enigmatica2Expert/files/4603487/hs_errpid2324.txt)

**Comment by NillerMedDild** [comment]
You appear to be using outdated Java. This is often caused by Twitch defaulting to an older version than you have available. Follow these steps to update.

* Make sure you have the latest 64-bit Java installed
    https://www.java.com/en/download/manual.jsp Windows Offline (64-bit) is the one you need
* Go to the Twitch Minecraft settings
* Add `-version:1.8+` to the Additional Arguments

**Comment by itzdarkfael** [comment]
I know it's not here to talk about it but I really like the work you did on this modpack, I think it's the best about the way I play. Tks a lot for this great work you did!

**Comment by NillerMedDild** [comment]
Thank you, I appreciate that :)
