### ISSUE TITLE
Can't craft Draconic Evolution Basic Relay Crystal into 2 I/O Crystals as shown in JEI 

### ISSUE THREAD

**Issue by hinchy34** [NillerMedDild/Enigmatica2Expert#1695]
**Modpack version**
v1.80

**Issue**
The JEI shows I should be able to craft two I/O crystal from the relay crystal, as a shapeless recipe (shown in the middle crafting grid slot. The reverse works, 2 i/o crystals will make a relay. These came from loot rewards.

**Logs**
n/a

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
Works just fine for me, would you mind holding the crystal in your hand in use the command `/ct hand`, and then paste the result here? Maybe it has bugged data or something :)

**Comment by hinchy34** [comment]
Maybe the client or server needs a reboot... Still having the issue. Here is the output:

<draconicevolution:energy_crystal:6>.withTag({BCTileData: {BCManagedData: {transportState: 1 as byte, inputMode: 0 as byte}}})

**Comment by NillerMedDild** [comment]
Cool thanks, that explains it :)

**Comment by NillerMedDild** [comment]
The item you were holding is a Basic Wireless Energy Crystal, which cannot be converted to the others.
