### ISSUE TITLE
White screen-flickering when looking at blocks in the Nether 

### ISSUE THREAD

**Issue by TheOnlyPhoenix** [NillerMedDild/Enigmatica2Expert#1696]
**Modpack version**
1.80

**Issue**
White screen-flickering in the Nether

**Logs**
No log, as this wasn't a crash.

So, this only occurs when looking at blocks. The screen starts flickering like crazy, even faster than in [this example](https://gyazo.com/7b385100bb4a1b3705794d6f9d87936c) (The link is a Gyazo link, as I read in issue #1322 that you won't open .zip files.) I have tried both with and without the Faithful 32x (vanilla and modded) texture pack. This issue is very similar, if not identical, to issue #1322. Please help.

**Comment by NillerMedDild** [comment]
Please supply your latest.log :)
Are you using Optifine and/or VanillaFix?

**Comment by TheOnlyPhoenix** [comment]
Yes, I am using both OptiFine and VanillaFix. Although, when I logged in today, the issue was fixed. I have no idea what caused it.
[latest.log](https://github.com/NillerMedDild/Enigmatica2Expert/files/4605429/latest.log)

**Comment by NillerMedDild** [comment]
Issue #1322 you linked to was caused by Optifine, so that's probably the cause...
