### ISSUE TITLE
Spellbound Cloth not reusable

### ISSUE THREAD

**Issue by LazyDope** [NillerMedDild/Enigmatica2Expert#1697]
**Modpack version**
1.80

**Issue**
Spellbound Cloth with durability used cannot be used to make more Fancy Amulets for TC6 due to CraftTweaker 2 script missing wildcards on lines 76 & 77 of thaumcraft.zs

**Comment by NillerMedDild** [comment]
I believe that is intended, but I'll double check.

**Comment by NillerMedDild** [comment]
Yup it's intended :)

**Comment by LazyDope** [comment]
So the bug would instead be that the cloth is not consumed then?

**Comment by NillerMedDild** [comment]
Yep I didn't think about that, woops :) will get it fixed.
