### ISSUE TITLE
/dank/null problem to the point where it is unusable

### ISSUE THREAD

**Issue by TheOnlyPhoenix** [NillerMedDild/Enigmatica2Expert#1698]
**Modpack version**
1.80

**Issue**
/dank/null problem where it is unusable

**Logs**
[Crash report](https://pastebin.com/HPsJ0PFb)

![2020-05-10_11 44 39](https://user-images.githubusercontent.com/54004241/81495857-ad266f80-92b3-11ea-940e-1c2c09eff529.png)
This happened yesterday as well, causing my game to completely crash, instantly, twice. It just shut off. Almost unable to play, since all my materials are in my /dank/null. I know I submitted another issue yesterday, but I need help. Now I just can't open it, I  instantly get this message.

**Comment by NillerMedDild** [comment]
Please remove all mods you've added and see if the issue still occurs. If it does, please supply the crash report.

**Comment by TheOnlyPhoenix** [comment]
Removed all mods, works. Note that this is on a server, and it did work with the mods in a singleplayer world. The mods we had are: LagGoggles, Tickcentral, Enchanting Plus, and I had (client) VanillaFix, OptiFine (.disabled BetterFPS).

**Comment by TheOnlyPhoenix** [comment]
So, the /dank/null works in a singelplayer world, with all of the added mods. But when I try do use it on my server from BH, it doesn't. I have switched instances, still doesn't work.

**Comment by NillerMedDild** [comment]
This is most likely caused by Optifine or VanillaFix, not much I can do.
