### ISSUE TITLE
Unlimited Fresh Water from Pam's: intended behaviour?

### ISSUE THREAD

**Issue by gonsanbo** [NillerMedDild/Enigmatica2Expert#1699]
**Modpack version**
v1.80

**Issue**
The recipie for fresh water from pam's is a bucket of water, which gives you 8, but there is another recipie, one accepting all listWater, and the fresh water from Pam's being listWater, one bucket essentially gives you an unlimited amount. I can't really tell if this is intended behavior.

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by NillerMedDild** [comment]
That is intended :)
