### ISSUE TITLE
Hard Crash when placing Cyclic Dropper

### ISSUE THREAD

**Issue by mattburchett** [NillerMedDild/Enigmatica2Expert#17]
#### Issue Description
I think I found a hard crash - It's in a reboot loop and had to restore from backup. 

#### What you expected to happen
Cyclic Dropper to be placed without crash.

#### Modpack version (Do not use "latest")
v1.12

#### Your most recent log file where the issue was present
https://pastebin.com/i1uveSAX

Crash occurred after placing a Cyclic Dropper.

**Comment by NillerMedDild** [comment]
Fixed in https://github.com/PrinceOfAmber/Cyclic/issues/752#event-1534805764
