### ISSUE TITLE
Silicon Unification

### ISSUE THREAD

**Issue by MorganSimic** [NillerMedDild/Enigmatica2Expert#1700]
The issue in short:
We currently have 4 types of Silicon, wich 99% overlap in usage.

Possible solution in short:
Merge all aquiring methods into one `itemSilicon`. Recommended would be NC silicon.

Possible issue arising from this change:
Can break existing setups, if output type of silicon from machines is changed.

The long explanation:
The four types of silicon are AE2 silicon, wich is aquired by smelting quartz dust, the EIO silicon, wich only can be obtained via conversion recipe, the NC silicon, wich has multiple methods, inlcuding a custom one in the compactor and the stonework factory, and then there is also the AR silicon ingot.
The thing is 99% of stuff uses `ore:itemSilicon` anyways, apart from silicon dust and silicon plates, wich can only be obtained fromAR silicon, but those have no use anyways.
So you could get rid of the 3 other types, keep conversion recipes in place from all other types to the main one and change all output to one type of silicon. I would recommend NC silicon, just because the stonework factory produces it and that is probably the prevelant way people are doing it.

**Comment by NillerMedDild** [comment]
That sounds reasonable, I'll consider it. UniDict has caused Silicon to be a massive pain to work with in the past, but maybe I can get it right this time :P

**Comment by MorganSimic** [comment]
One thing i noticed yesterday is, that the AR silicon ingot is an ingredient of the ultimate ingot, i totally missed that. So that needs to be considered.

**Comment by NillerMedDild** [comment]
I don't want to risk destroying existing setups, I believe Disco will cover this however.

**Comment by Anthonity** [comment]
AE2 silicon looks the best tbh
