### ISSUE TITLE
AA Empowerer JEI Recipe has 35 pages for various Chisel Basalt block.

### ISSUE THREAD

**Issue by hinchy34** [NillerMedDild/Enigmatica2Expert#1703]
**Modpack version**
v1.80

**Issue**
Not really an issue, but there is an extra 35 pages in the JEI for making empowered void crystals because of the Basalt block, an entry for every Chisel variation. I'm mostly curious if this is a quick script fix or a limitation of the various mods and craft tweaker?

**Logs**
n/a

**Comment by NillerMedDild** [comment]
It's a limitation of the recipe type, it doesn't accept oredict values, so I had to specify all of the different basalt blocks.

**Comment by Discomanco** [comment]
Wouldn't it be better for it to not accept chisel variants then? :P
Because if I recall, it started with only accepting Cracked Basalt

**Comment by NillerMedDild** [comment]
Yup I changed it recently. I think it's fine as is, rather accept everything than only 1 kind.
