### ISSUE TITLE
Random Game Crashes on launch

### ISSUE THREAD

**Issue by Osprey4444** [NillerMedDild/Enigmatica2Expert#1704]
**Modpack version**
1.80

**Issue**
Reporting this on behalf of many players of my Servers.

Around 8-10 people who play on my E2E Server have experienced random crashes on loading up but then it will randomly work. There seems to be no rhyme or reason to it. Doesn't happen to them on bigger packs/other packs.

**Logs**
https://hastebin.com/uxexedixil.makefile (Crash Report)

**Comment by NillerMedDild** [comment]
You appear to be using outdated Java. This is often caused by Twitch defaulting to an older version than you have available. Follow these steps to update.

* Make sure you have the latest 64-bit Java installed
    https://www.java.com/en/download/manual.jsp Windows Offline (64-bit) is the one you need
* Go to the Twitch Minecraft settings
* Add `-version:1.8+` to the Additional Arguments

**Comment by NillerMedDild** [comment]
If you send me more crash reports, I will happily have a look, and re-open the issue if needed.
