### ISSUE TITLE
Crash on rendering information of item conduit from EnderIO

### ISSUE THREAD

**Issue by ItsmeCurly** [NillerMedDild/Enigmatica2Expert#1706]
**Modpack version**
1.80

**Issue**
When placing a mekanism machine and hooking it up with an enderio item conduit with a enderio power conduit/other conduit that forms a connection, the machine will render the two connecting but will throw an error if the item conduit's information button is hovered over. This is probably due to the item conduit not forming the connection, as the mekanism machine doesn't connect to the conduit unless there's another one forming the connection.

Steps to reproduce:
1) Place mekanism machine
2) Set mekanism machine connection to None
3) Place item conduit, it should not connect to the side as its connection is None
4) Set mekanism machine side with the item conduit to Input or Output
5) Place another conduit (not item conduit) on same side that forms connection to machine
6) Hover over the (i) button that displays the number of effective items the conduit is pulling from the machine.

**Logs**
https://pastebin.com/5Y5NTGUH

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
I cannot reproduce this, but I did update EnderCore so I'm guessing it's fixed.
