### ISSUE TITLE
Problem with PackagedAuto

### ISSUE THREAD

**Issue by john13210** [NillerMedDild/Enigmatica2Expert#1708]
**Modpack version**
Input version here
1.80

**Issue**
When im gonna add the recipe to the package holder (i have problem with ultimate ingot) and request one of the packages a lot of them i can request  disapears from the ae2 system so i cant request them and eventualy set complete recipe (for example ultimate ingot)

I am playing on the server so i dont know if it happens on singleplayer

**Comment by NillerMedDild** [comment]
A lot of what disappears from your AE system? To be honest this doesn't sound like a bug.

**Comment by john13210** [comment]
like the icons when you want to request something

**Comment by john13210** [comment]
https://imgur.com/iJ86Yxs

**Comment by NillerMedDild** [comment]
Ah okay, that does sound like a bug, I'll investigate :)

**Comment by NillerMedDild** [comment]
I've decided not to take this issue any further, as most modders no longer work on Minecraft 1.12, and development of Enigmatica is focused on Minecraft 1.15+ - I hope that's understandable :)
Thank you for helping to make E2E polished by reporting, I hope to see you in E5+!
