### ISSUE TITLE
Pam's Harvestcraft tools not working properly with Botania corporea after being used in crafty crate

### ISSUE THREAD

**Issue by Branjoman** [NillerMedDild/Enigmatica2Expert#1709]
**Modpack version**
latest: 1.80

**Issue**
After a successful craft using a pam's harvestcraft tool has been performed in a crafty crate, a corporea funnel used to request the pam's harvestcraft tool will no longer request the tool, even though it is identical to the tool it has been set to. This only triggers if the crafty crate crafts successfully (so ejecting the tool before a craft is performed does not trigger this issue).

**Steps to Recreate**
 - Create a botania crafty crate setup like the one in this image: https://imgur.com/a/EgmjIJC. 
 - Place a mortar and pestle and some wheat into the bottom output chest. 
  - Trigger the corporea funnel for the mortar and pestle (which requests the mortar and pestle), then the funnel for the wheat.
 - Wait for the results of the craft to return to the output chest.
 - Trigger the mortar funnel again, requesting the mortar and pestle again from the chest.
 - Observe as the funnel fails to retrieve the mortar and pestle that it successfully retrived 10 seconds earlier.

**Logs**
[latest.log](https://github.com/NillerMedDild/Enigmatica2Expert/files/4639151/latest.log)

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by Branjoman** [comment]
Sorry for posting on such an old bug report, but I have an update that narrows down what's causing this issue. Another thing I've found is that this bug does not only affect pam's harvescraft tools, it also affects vanilla milk buckets too i.e. when setting a corporea funnel to request a milk bucket, the network will only request _that specific bucket_ and no others. This behaviour is referenced in these two reddit posts: [https://www.reddit.com/r/botania/comments/dcvuhz/hopperhockcorporea_not_recognizing_milk_buckets/](url)
and
[https://www.reddit.com/r/botania/comments/c36ynr/hopperhock_not_picking_up_milked_buckets_ftb/](url)
which both say that a bug in astral sorcery is causing this issue by giving a unique identifier to each item (which heavily affects non-stackable items).

**Comment by NillerMedDild** [comment]
I've decided not to take this issue any further, as most modders no longer work on Minecraft 1.12, and development of Enigmatica is focused on Minecraft 1.15+ - I hope that's understandable :)
Thank you for helping to make E2E polished by reporting, I hope to see you in E5+!
