### ISSUE TITLE
Immersive Engineering Crusher

### ISSUE THREAD

**Issue by burt666** [NillerMedDild/Enigmatica2Expert#171]
#### Issue Description
The crusher from Immersive Engineering does not function. It can be constructed and turned into a multiblock, but does not function as described in the engineering manual.

#### Modpack version (Do not use "latest")
1.33

**Comment by NillerMedDild** [comment]
It's missing the vast majority of it's recipes, I've been trying to find out what's causing the issue for a while now. Thank you for the report :)
