### ISSUE TITLE
Use for TiCon's Slimy Dirt

### ISSUE THREAD

**Issue by MeiTianyou** [NillerMedDild/Enigmatica2Expert#1710]
Suggestion: Currently, the varieties of slimy dirt added by tinker's construct have pretty low utility. They just are used for soil when planting slime trees.  It would be cool if we could centrifuge them (forestry/thermal expansion) for the respective color slimeballs and regular dirt.

**Comment by NillerMedDild** [comment]
Good idea :)

**Comment by MorganSimic** [comment]
Is slimey dirt craftable? Not sure on that but better check that, so no infinite loop is created.

**Comment by NillerMedDild** [comment]
It is craftable with grass + 4 slime balls of the type you want, so the processing will need to output 4 slime balls at most.
