### ISSUE TITLE
Missing IE Crusher Recipies

### ISSUE THREAD

**Issue by PlazmaCaster** [NillerMedDild/Enigmatica2Expert#1711]
**Modpack version**
1.80

**Issue**
The crusher from Immersive Engineering seems to except all of the nether ores except nether tin ore and nether iron ore. First noticed it when I tossed some tin in and it wouldn't accept it but other would and all but those two have their recipes in JEI.

**Comment by NillerMedDild** [comment]
Woops, I'll get that added, thanks.

**Comment by NillerMedDild** [comment]
Hmm, not sure what's going on here, we have the recipes for those ores and they are correct.
