### ISSUE TITLE
Fractionating still doesn't accept fluid.

### ISSUE THREAD

**Issue by OmerMel** [NillerMedDild/Enigmatica2Expert#1712]
**Modpack version**
1.80

**Issue**
Fractionating still doesn't accept fluid ( resin ),
I dont know if this is problem in the modpack or the mod itself.
I tried with mekanism pipe and thermal fluiduct. They both didn't work. :(
https://imgur.com/a/uNL6DVB

**Comment by NillerMedDild** [comment]
Possibly silly questions: 
* Is the tank empty?
* Is the Servo set to redstone disabled or low?

**Comment by OmerMel** [comment]
> Possibly silly questions:
> 
> * Is the tank empty?
> * Is the Servo set to redstone disabled or low?

- The tank in the picture in not empty ( can easly filled it with the sawmil that under it ).
- The servo is set to ingnored.
- The fluiduct is full with the fluid.

**Comment by OmerMel** [comment]
okay... I just didn't pay attention and I made sap and not rosin. My bad.
