### ISSUE TITLE
Advanced Thermionic Fabricator not recognized

### ISSUE THREAD

**Issue by gonsanbo** [NillerMedDild/Enigmatica2Expert#1714]
**Modpack version**
v1.80

**Issue**
The Advanced Thermionic Fabricator from modular machinery is not recognized. This is the 3rd time I build it and I have double double checked all the blocks. Any ideas why the structure isn't found?

**Logs**
https://imgur.com/a/8PoLtva

**Comment by NillerMedDild** [comment]
I can't remember how to build the structure off the top of my head, but I'm pretty sure it works in 1.80.

Do you have the 7 buckets of fluid on the inside?

**Comment by gonsanbo** [comment]
Uh 7 buckets? Maybe you're confusing it with the advanced carpenter, on the blueprint it says 9 buckets of blazing pyrotheum.

**Comment by NillerMedDild** [comment]
Yup you're probably right :P been a while. I'll check in game when I get time, but I recommend asking for help in our discords support channel.
