### ISSUE TITLE
Cinnamon Sapling is shown twice when searching in the Market(Farming for Blockheads)

### ISSUE THREAD

**Issue by damnedsky** [NillerMedDild/Enigmatica2Expert#1716]
**Modpack version**
1.80

**Issue**
I was searching for a Cinnamon Sapling in the Farming for Blockheads Market, and it shows the Cinnamon Sapling twice.

**Logs**
N/A

![image](https://user-images.githubusercontent.com/2750205/82687977-bffc5500-9c60-11ea-9a66-a61fee1e9a7d.png)

**Comment by NillerMedDild** [comment]
Thanks for the bug report, it looks like this is an issue with the mod, I'll relay it :)

**Comment by NillerMedDild** [comment]
This will not be fixed, as the mod dev no longer works on 1.12 :(
