### ISSUE TITLE
Pig Iron not alloying on dedicated server

### ISSUE THREAD

**Issue by magicthize** [NillerMedDild/Enigmatica2Expert#1717]
**Modpack version**
1.8

**Issue**
While playing on my dedicated server I was unable to create Pig Iron: melting down the blood, iron and clay just results in liquid versions of each, they don't create an alloy. Testing on a single player world I found it works without issue. I created a new server on my PC and tried to recreate the issue - exactly the same result. I managed to fix it by taking all the appropriate folders from my client instance and overwriting the files in the server folder (quickest way to do it because I couldn't figure out where the recipes are located!).

![Capture](https://user-images.githubusercontent.com/6639972/82732995-ac0c2e00-9d08-11ea-86b2-fdfc047a519d.PNG)

**Logs**
n/a

**Comment by NillerMedDild** [comment]
Did you test this out in the server's spawn chunks? :)

**Comment by magicthize** [comment]
Assuming I understand you correctly here's the steps I took to test it:

Started up a brand new dedicated server from download.
Created a smeltery at spawn. No alloying.
Travelled ~1000 blocks from spawn.
Created a smeltery.. No alloying.

Shut down the server and overwrote the server files with those from my client.
Started up the server.
Checked the smeltery ~1000 blocks from spawn. Successful alloying.
Checked the smeltery @spawn. Successful alloying.

**Comment by NillerMedDild** [comment]
Hmm weird. Did you use these server files? https://www.curseforge.com/minecraft/modpacks/enigmatica2expert/files/2929251

**Comment by magicthize** [comment]
Yep. Freshly downloaded the server files before a made the new server.

**Comment by NillerMedDild** [comment]
Cool, thanks for the prompt answers, should make troubleshooting this a lot easier :)

**Comment by NillerMedDild** [comment]
I do not believe I can fix this, and the majority of modders no longer support 1.12, so I'll close this issue.

Nethertheless, thank you for reporting :)
