### ISSUE TITLE
CoFH Potions in Fluid Form Incompatible with Transposer or IE Bottler

### ISSUE THREAD

**Issue by Fysalk** [NillerMedDild/Enigmatica2Expert#1718]
**Modpack version**
1.77

**Issue**
TE/CoFH potions in fluid form (made through the Alchemical Imbuer) aren't compatible with vanilla bottles in the Fluid Transposer ([pic](https://i.imgur.com/Ej0mpzn.png)). Tested with IE Bottling Machine and bottles enter then exit the conveyor still empty ([pic](https://i.imgur.com/AtnDvue.png)). 

The recipe for the vanilla "Instant Health II" potion seems to have a conflict in the Fluid Transposer JEI entry. Following the recipe for the bottled potion looks okay, but following the "uses" for the fluid form in the same entry is replaced with potions of strength ([pic](https://i.imgur.com/2GPrNd1.png))

Problem seems to be related to the CoFH potions specifically. Instant Health II gets bottled but III does not. Not sure if they were removed for balance reasons or if this is a bug.

**Comment by Fysalk** [comment]
Seems I needed to remove the bottle in the middle slot of the first pic to get the process going. IE Bottler is still incompatible with CoFH potions, however I've closed this since Fluid Transposer was the intended method and it works.

**Comment by NillerMedDild** [comment]
Glad you got it working, albeit partially :)
