### ISSUE TITLE
Carpenter isn`t recieving water

### ISSUE THREAD

**Issue by DigaoFreire** [NillerMedDild/Enigmatica2Expert#1719]
**Modpack version**
1.8

**Issue**
Carpenter isn`t accepting any water source (pipes or bucket in GUI)

**Comment by NillerMedDild** [comment]
Thanks for the bug report :)
Have you tried:
* Breaking and replacing it?
* Relogging and/or restarting the server?

**Comment by DigaoFreire** [comment]
Yes, I tried a both:
  
- Replace the block doesn't work
- Relogging in the map or in another one doesn't work too
- Reopen the game works. But, in some point at the gameplay (that I couldn't identify) the block bug again and I need to reopen the game.

**Comment by NillerMedDild** [comment]
Hm alright, I'm guessing I won't be able to reproduce this then. Do you only use it for 1 fluid?
