### ISSUE TITLE
Tinkers' Construct Casts and molds dont render correctly

### ISSUE THREAD

**Issue by robzombie91** [NillerMedDild/Enigmatica2Expert#172]
#### Issue Description
Tinkers construct molds/casts do not render correctly, "are just invisible in the casting table". I have no other rendering mods "optifine" other than the ones included in the modpack, "Betterfps and foamfix"

#### Modpack version (Do not use "latest")
Expert 1.33

#### Crash Report
Game does not crash, just a rendering issue

[pastebin/gist/etc link here]
https://gist.github.com/robzombie91/54770150af0b2f1727b4be297502dfb4

**Comment by Discomanco** [comment]
Intended change, and noted in the changelog. It's up for changing back in next version though
#170 #169
