### ISSUE TITLE
JEI bugs introduced since 1.77

### ISSUE THREAD

**Issue by sylviapossenau** [NillerMedDild/Enigmatica2Expert#1720]
**Modpack version**
1.80

**Issue**
I upgraded from 1.77 to 1.80 and now there are at least 2 JEI related bugs:
* the back button on an item and its uses goes in the forward direction (hit U on e.g. oak planks to see uses and try to go through list in backwards order)
* I can no longer use the plus button (move items) for crafting a single recipe (also now goes to next uses), shift click still does multiple recipes.

**Comment by NillerMedDild** [comment]
Thanks for the report. I think you should try to reinstall before we take this further :)

**Comment by sylviapossenau** [comment]
That did fix it. Weird.
