### ISSUE TITLE
Crash on destroying HV wire with rainbow cannon from Cyclic

### ISSUE THREAD

**Issue by ItsmeCurly** [NillerMedDild/Enigmatica2Expert#1721]
**Modpack version**
1.80

**Issue**
Game crash on shooting HV wire with Rainbow cannon from Cyclic
I would suggest removing the Rainbow cannon as it has no direct assistance to the modpack and forced us to revert to a backup as the world was irretrievable and crashed on startup.

**Logs**
https://pastebin.com/q4snW7fn

**Comment by NillerMedDild** [comment]
Thanks for letting me know :) I've never actually used or seen the Rainbow Cannon, what does it do?

**Comment by ItsmeCurly** [comment]
I didn't get to test the item before we server-wide disabled the usage, but a person I play with said it just shoots out a rainbow projectile that does damage. I'm not sure of the logistics of how it works but I would assume its somewhat similar to a mining laser. The ability to destroy blocks though is quite troublesome, and seems to lead to unintentional griefing.
