### ISSUE TITLE
Strange power loss with LV Connectors, Mek Cables, and Cyclic Battery

### ISSUE THREAD

**Issue by Celebnasse** [NillerMedDild/Enigmatica2Expert#1723]
**Modpack version**
1.76a (Also reported by someone in 1.80)

**Issue**
When hooked up to Mek Universal Cables with LV Connectors, a Cylic Battery has a constant RF drain on it, even if the Cables aren't connected to anything.  It's not just LV and Cyclic Battery, as in the picture [here](https://prnt.sc/sppax9), there is no drain currently on the battery, but if I connect an LV Wire between the 2 connectors on the right, the battery will drain at approx 30 RF / second.  As you can see, there is nothing even connected to the Mek Cable on the far right.

This happens even without the Mek cable between the battery and LV connector.  If the LV Connector is directly on the battery, the same thing happens.

There is no loss to the machine on the left (LV -> Wire -> LV -> Machine).  If I put a Mek Cable between the LV on the far left and the machine, there is again a loss of power even if the Thermal machine is full.

**Logs**
N/A

**Comment by MorganSimic** [comment]
That is indeed very weird. I would guess it has something to do with mekanism being mekanism. Try setting the mekanism connecting on the LV connector to only be push or pull respectively. I could imagine power being circulated and some power being lost in conversion as mekanism still uses Joule internally. If i remember i will check it out tomorrow myself.
For now, please try the suggested configuration, then report back.

**Comment by Celebnasse** [comment]
If I change it to Pull, it indeed doesn't drain the battery, but it also doesn't power anything connected to it.  See [here](https://prnt.sc/sprkkg).  The compactor isn't getting power.

**Comment by MorganSimic** [comment]
I tested it and found that power is also draining if you only connect 2 filled mek pipes by IE connectors, no in or ouput. So that supports my theory that some conversion error or something does come in affect when power is looped.

**Comment by NillerMedDild** [comment]
The conversion config is sound, so this would be an internal issue with Mekanism or Immersive Engineering, or the LV loss percentage is acting up. But LV Wire is not lossless, and not meant to be.

**Comment by MorganSimic** [comment]
I think there is some internal bug invovled, as in theory no power should be moved. If both input and output cable are full, no power should be flowing, yet it does. From my testing it seems mek doesn't like IE connectors really.

**Comment by Nabbieshtron** [comment]
i think i have issue with same bug on quantum entangloporter i using transfer power ender io conduit and on quantum entangloporter all output is set to none and still transfers power after some time it randomly disconects and if i select in quantum entangloporter output side it didnt output any energy unless i press auto-eject and choose any side.

**Comment by NillerMedDild** [comment]
melter, hydrator, dehydrator

**Comment by NillerMedDild** [comment]
I've decided not to take this issue any further, as most modders no longer work on Minecraft 1.12, and development of Enigmatica is focused on Minecraft 1.15+ - I hope that's understandable :)
Thank you for helping to make E2E polished by reporting, I hope to see you in E5+!
