### ISSUE TITLE
InstanceSync Pams Harvestcraft issue

### ISSUE THREAD

**Issue by bibo38** [NillerMedDild/Enigmatica2Expert#1725]
**Modpack version**
Current `develop` branch (deca811)

**Issue**
After cloning the repository running `java -jar InstanceSync.jar` causes the following error:

```
Downloading Pam's HarvestCraft 1.12.2zg.jar
Failed to download Pam's HarvestCraft 1.12.2zg.jar
java.io.IOException: Server returned HTTP response code: 400 for URL: https://edge.forgecdn.net/files/2904/825/Pam's HarvestCraft 1.12.2zg.jar
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
        at vazkii.instancesync.DownloadManager.lambda$0(DownloadManager.java:83)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
```

Furthermore this creates an empty (0 KB) jar-File in the mods folder and never tries to retrieve it again due the existing file.

The issue is already reported under https://github.com/Vazkii/InstanceSync/issues/5

Otherwise it is also possible to replace the whitespace in the `downloadUrl` (https://github.com/NillerMedDild/Enigmatica2Expert/blob/develop/minecraftinstance.json#L12166) with `%20` which fixes this issue. But I don't know how well this works with the Twitch Launcher.

**Comment by NillerMedDild** [comment]
Thanks for letting me know! I assume that this is mostly just a PSA?

**Comment by bibo38** [comment]
PSA meaning "Public Service Announcement" :thinking: ? This issue is not that important (as probably very few will create Pull Requests or work with the repository directly), but would be nice to have it fixed (if Vazkii patches InstanceSync or with the "hacky" json change). Feel free to mark it/close it, if it clutters the issue list.

**Comment by NillerMedDild** [comment]
I think it's good to have visible while the issue exists :)

**Comment by forresthopkinsa** [comment]
Here's an easy patch server owners can apply after cloning the repo or extracting the release:

```patch
diff --git a/minecraftinstance.json b/minecraftinstance.json
index a87cbc5..07e357f 100644
--- a/minecraftinstance.json
+++ b/minecraftinstance.json
@@ -12389,7 +12389,7 @@
         "fileLength": 4912890,
         "releaseType": 1,
         "fileStatus": 4,
-        "downloadUrl": "https://edge.forgecdn.net/files/2904/825/Pam's HarvestCraft 1.12.2zg.jar",
+        "downloadUrl": "https://edge.forgecdn.net/files/2904/825/Pam's%20HarvestCraft%201.12.2zg.jar",
         "isAlternate": false,
         "alternateFileId": 0,
         "dependencies": [],
```

Copy the above into a file `whatever.patch` and then `git apply whatever.patch`
