### ISSUE TITLE
Modular Machine block "Machine Gearbox" doesn't craft

### ISSUE THREAD

**Issue by vegon** [NillerMedDild/Enigmatica2Expert#1728]
**Modpack version**
1.81

**Issue**
Modular Machine block "Machine Gearbox" doesn't craft, seems like the recipe is missing an item. From discord:

"it's the iridium rod from AR that is missing. Probably something during oredict cleanup has gone wrong"

**Comment by Discomanco** [comment]
The fix in the commit of https://github.com/NillerMedDild/Enigmatica2Expert/commit/3f5dd1f1555172aca40448eda1d2c0b318a19040 made this error happen. The Machine Gearbox requires an Iridium Rod. The recipe is of course oreDicted, but there's only 1 stickIridium currently, and that's from AR. L107 should be removed from the AR script
