### ISSUE TITLE
Enigmatica 2 Expert Server 1.81 - Forge Universal missing

### ISSUE THREAD

**Issue by threebigfeet** [NillerMedDild/Enigmatica2Expert#1729]
**Modpack version**
Enigmatica 2 Expert Server 1.81

**Issue**
The forge installer doesn't install the "universal" file or the word "universal" is missing from the file name and the server start bat gets stuck in a loop of installing forge, finding that universal is missing and trying again.

Manually downloading the universal file and installing forge appears to fix the issue.

Otherwise works great.

Thanks

**Comment by NillerMedDild** [comment]
Fixed in 1.81a, thanks for the report :)

**Comment by NillerMedDild** [comment]
You can fix it yourself by changing the Forge version in `settings.cfg` to 2847
