### ISSUE TITLE
Unable to craft Copper Solenoid E2:E Version 1.81

### ISSUE THREAD

**Issue by kellphi** [NillerMedDild/Enigmatica2Expert#1730]
**Modpack version**
1.81

**Issue**
Unable to craft the copper solenoid from NuclearCraft in the crafting station or regular crafting table. This issue is preventing me from completing the Manufactory to move into the NuclearCraft chapter.

**Logs**
N/A

**Comment by NillerMedDild** [comment]
Thanks for the report! Fixed as a side-effect of fixing #1728
