### ISSUE TITLE
Crash, pressing U in JEI over Wooden Barrel.

### ISSUE THREAD

**Issue by Pigbull320** [NillerMedDild/Enigmatica2Expert#1731]
**Modpack version**
1.81

**Issue**
Crashing, FPS issues, I quickly ender pearled 5 chunks away, placed a wooden barrel down, tried placing lava in it and failed, went into jei, press U over the wooden barrel and crashed.
Could have been the new chunks, my java arguments, jei, the wooden barrel.

I disabled BetterFPS at the recommendation of a forge dev.

I'm using these arguments in multiMC 5:
Java Arguments:
[-Dfml.readTimeout=240, -XX:+UseG1GC, -Dsun.rmi.dgc.server.gcInterval=214783646, -XX:+UnlockExperimentalVMOptions, -XX:G1NewSizePercent=20, -XX:G1ReservePercent=20, -XX:MaxGCPauseMillis=50, -XX:+PrintCommandLineFlags, -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms1024m, -Xmx7936m, -Duser.language=en] as you can see in the logs due to me having the printcommandlineflags argument.

In the multiMC launcher I wrote in: -Dfml.readTimeout=240 -XX:+UseG1GC -Dsun.rmi.dgc.server.gcInterval=214783646 -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M

I was crashing doing other things before adding these, playing other packs like skyfactory I've posted several crash reports all contained 'server can't keep up! running xxxMS behind!

**Logs**
https://paste.ee/p/5zupr
[crash-2020-06-02_11.11.04-client.txt](https://github.com/NillerMedDild/Enigmatica2Expert/files/4718780/crash-2020-06-02_11.11.04-client.txt)

I could remove the arguments but my fps was 15 without them... now i get 70 standing still, 40 while moving, 8 while loading new chunks, even tho i used the 'preview' feature before making the world and did a 100 chunk radius, when i first started the world i didn't have frame issues, got 40 easy, then after restarting the new day it dropped to 15, so i added those arguments.
![20200602_120826](https://user-images.githubusercontent.com/16366090/83551675-a8319600-a4d6-11ea-822c-b36e97348ea0.jpg)
Screenshot when first loaded world. Played for 3 hours before crash.

**Comment by Pigbull320** [comment]
Recreating crash does nothing, jei working. Barrel not bugged in any way. Loading same chunks, while reducing fps doesnt crash

**Comment by NillerMedDild** [comment]
This is more a support request than a bug report, as you're not experiencing any particular buggy behaviour.

The culprit behind your crash appears to be your java version, so I suggest updating if possible, downgrading if not.

Please try to keep future issues more concise :)
