### ISSUE TITLE
Flux Networks Inventory Wireless Charging Disabled

### ISSUE THREAD

**Issue by ImVaskel** [NillerMedDild/Enigmatica2Expert#1732]
**Modpack version**
1.8

**Issue**

Flux Networks inventory wireless charging is disabled, tried with controller and storage.

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by NillerMedDild** [comment]
I'm pretty sure that's something the owner of the network controls :)

**Comment by ImVaskel** [comment]
No, like when you look at inventory it says “Inventory (Disabled)

**Comment by ImVaskel** [comment]
https://i.imgur.com/gcPNBxV.png here is an image of the issue

**Comment by KleinGrrmpf** [comment]
Did you configure it in the controller or the flux plug/point? I tried it in the point/plug and it didn't work, but configuring it in the controller worked for me.

**Comment by NillerMedDild** [comment]
https://github.com/NillerMedDild/Enigmatica2Expert/issues?q=is%3Aissue+is%3Aopen+-label%3A%22status%3A+reported%22+-label%3A%22Status%3A+Fixed+In+Next+Release%22+-label%3A%22Status%3A+Blocked%22
