### ISSUE TITLE
Item Placeholders as random quest rewards

### ISSUE THREAD

**Issue by DrewSin-4** [NillerMedDild/Enigmatica2Expert#1733]
**Modpack version**
1.80
**Issue**
Item Placeholders as random quest rewards
**Logs**
No logs

**Comment by Discomanco** [comment]
Would need to know what items they're being placeholder for. If you enable advanced tooltips (F3+H), you should be able to see what it's replacing

**Comment by DrewSin-4** [comment]
> Would need to know what items they're being placeholder for. If you enable advanced tooltips (F3+H), you should be able to see what it's replacing

exchangers:resonant_ender/0

**Comment by NillerMedDild** [comment]
Update and use the command '/bqs_loot default load' :)
