### ISSUE TITLE
The unmanned rocket always spawns at the bottom of the space

### ISSUE THREAD

**Issue by heygeon** [NillerMedDild/Enigmatica2Expert#1735]
**Modpack version**
1.7.0.-208 (Enigmatica 2 Light)

**Issue**
When I launch the unmanned rocket to my space station, it always spawns at the bottom of the space like around y = 0. I have already put the docking pad on my space station. However, when I go to the space station with my rocket (manned rocket), it becomes fine and the rocket can be landed on the docking pad.

**Comment by NillerMedDild** [comment]
This is not the issue tracker for Enigmatica 2: Light, and `1.7.0-208` is not a modpack version. Please try again :) Also include whether you're on a server or singleplayer.
