### ISSUE TITLE
Unmanned rocket unable to land on the docking pad of space station

### ISSUE THREAD

**Issue by heygeon** [NillerMedDild/Enigmatica2Expert#1736]
**Modpack version**
Enigmatica 2: Light 1.4.5

**Issue**
I am running the game in singleplayer and sometimes open to lan to play with my mates.
When I launch the unmanned rocket to my space station, it always spawns at the bottom of the space like around y = 0. I have already put the docking pad on my space station. However, when I go to the space station with my rocket (manned rocket), it becomes fine and the rocket can be landed on the docking pad.

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by NillerMedDild** [comment]
Thank you for remaking the issue :)

Do you remember whether the world was open to LAN during the unmanned rocket launch? Cause LAN worlds tend to have all sorts of odd issues.

**Comment by heygeon** [comment]
Yes, i normally open to LAN all the time

**Comment by NillerMedDild** [comment]
Then that is most likely the cause :/ the chances of getting this fixed is close to 0 I'm afraid, issues I report to the Advanced Rocketry issue tracker are mostly ignored.

**Comment by NillerMedDild** [comment]
https://github.com/NillerMedDild/Enigmatica2Expert/issues?q=is%3Aissue+is%3Aopen+-label%3A%22status%3A+reported%22+-label%3A%22Status%3A+Fixed+In+Next+Release%22+-label%3A%22Status%3A+Blocked%22

**Comment by NillerMedDild** [comment]
I've decided not to take this issue any further, as most modders no longer work on Minecraft 1.12, and development of Enigmatica is focused on Minecraft 1.15+ - I hope that's understandable :)
Thank you for helping to make E2E polished by reporting, I hope to see you in E5+!
