### ISSUE TITLE
Able to duplicate TC essence with ID player simulator

### ISSUE THREAD

**Issue by Opaque02** [NillerMedDild/Enigmatica2Expert#1737]
**Modpack version**
1.77 (couldn't see anything on change logs to say it's been fixed)

**Issue**
I attached a player simulator over a TC cauldron that had water in it. I then attached that player simulator to an item interface attached to a chest. On the player simulator, I put a "True" boolean card in the "Click" section, changed "Right Hand" option to false, along with continuous click to false too. I then put a single crystal into the chest, and the player simulator clicked the cauldron with the crystal to add it to the cauldron (I could see the essence being added using the TC Goggles), and once it was done adding the crystal, it kept repeating. I looked in the chest, and the crystal hadn't been taken out, but the player simulator kept adding essence to the cauldron as if there were multiple crystals. I was then able to use quartz slivers to get more essence crystals out.

I made a gif of the process here: https://gfycat.com/directdimwittedbaboon

**Logs**
No logs

**Comment by Opaque02** [comment]
I should have mentioned this earlier, but this also works with anything that can be put into the cauldron to create essence - for example, putting invar shears in the chest produces 16 instrumentum essence per click, but putting quartz slivers produces nothing

**Comment by NillerMedDild** [comment]
Thanks for the report, I'll relay to the Integrated Dynamics developer when I get some time :)

**Comment by NillerMedDild** [comment]
I've decided not to take this issue any further, as most modders no longer work on Minecraft 1.12, and development of Enigmatica is focused on Minecraft 1.15+ - I hope that's understandable :)
Thank you for helping to make E2E polished by reporting, I hope to see you in E5+!
