### ISSUE TITLE
Ticking Entity Crash when flying around world

### ISSUE THREAD

**Issue by shosh2202** [NillerMedDild/Enigmatica2Expert#1738]
**Modpack version**
Playing E2E-1.80, forge version 14.23.5.2847

**Issue**
Every time I leave the loaded areas in my world (ie. leave my base to gather resources) minecraft crashes. The areas I am flying around have previously been loaded, but most likely were not rendered while I worked in my base. The error seems to be a ticking entity error, but the mob involved changes between crashes (skeleton in the example, angus cow in another instance). The most recent crash log is below.

**Logs**
Two sample crash logs: https://pastebin.com/EEvicf00 and https://pastebin.com/9hPraw7m

**Comment by NillerMedDild** [comment]
Thanks for the report.
Please update to 1.81a and see if the issue persists.
