### ISSUE TITLE
Adv Rocketry Arc Furnace consumes without return

### ISSUE THREAD

**Issue by lywood** [NillerMedDild/Enigmatica2Expert#174]
#### Issue Description
The Advanced Rocketry mod Electric Arc Furnace when making for example Titanium Aluminide, will consume any multiple of the recipes input from its input port all at once (e.g. 63 aluminum and 27 titanium), but upon smelting only return one recipes worth of output (e.g. 3 titanium aluminide). Same thing happens with all arc furnace recipes. Tested in singe player and on a third party server running this pack.

#### Modpack version
1.33. From the Twitch launcher

#### Crash Report
Does not cause a crash

**Comment by lywood** [comment]
Looking into this further a similar issue was reported on the mods github [https://github.com/zmaster587/AdvancedRocketry/issues/1359](url) and the next version of libVulpes ot the one in this pack fixed the issue, LibVulpes-1.12.2-0.2.8-35.

**Comment by NillerMedDild** [comment]
Awesome, I'll get an update pushed out asap.
