### ISSUE TITLE
ExtraCells2 1024k and 4096k Fluid Storage Cells not working properly (Removed recipes)

### ISSUE THREAD

**Issue by ItsmeCurly** [NillerMedDild/Enigmatica2Expert#1740]
**Modpack version**
1.80

**Issue**
ExtraCells2 1024k and 4096k Fluid Storage Cells not working properly.

**Related Issues**
Relevant Issue: ExtraCells/ExtraCells2#684

Yueh of the AE2 team confirms a change will not be occurring: AppliedEnergistics/Applied-Energistics-2#4352

I recommend to remove the 1024k and 4096k Fluid Storage recipes so that people don't craft them mistakenly.

**Comment by NillerMedDild** [comment]
Thanks for the report, I'll look into it :)
