### ISSUE TITLE
1.81a is generating all versions of specific ore ID

### ISSUE THREAD

**Issue by MalikMidas** [NillerMedDild/Enigmatica2Expert#1741]
**Modpack version**
Enigmatica 2 expert 1.81a

**Issue**
All iterations of ores are generating. Ex. Copper ore from Forestry, thermal, and ic2 are all generated in the world. Previous versions only had thermal copper ore. How do I change this?

**Comment by NillerMedDild** [comment]
Sounds like your config folder got reset somehow, reinstalling should fix it :)
