### ISSUE TITLE
Can't change the gas in a creative gas tank

### ISSUE THREAD

**Issue by bclougherty** [NillerMedDild/Enigmatica2Expert#1742]
**Modpack version**
1.81a (also tried on 1.74 and 1.80, with the same results)

**Issue**
The quest book states that you can clear the gas in a creative gas tank with an empty gauge dropper. In practice, I can't find any way to clear or change the gas - I've tried left- and right-clicking on every part of the UI and the block with an empty gauge dropper, with and without shift. I've tried loading a gauge dropper with a different gas into the UI after seeing an older issue suggesting that solution. I've played with the idle/dumping controls in all combinations with the above. Nothing seems to work, so my creative tank is locked to the first gas I put in.

Shift-left-clicking the tank contents with an empty gauge dropper works fine on the creative fluid tank.

**Logs**
N/A

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by KleinGrrmpf** [comment]
Can't you empty it by right-clicking it with another tank or was that just the fluid tank?

**Comment by KleinGrrmpf** [comment]
Ok, after trying a lot, I can confirm this

**Comment by NillerMedDild** [comment]
I agree with your findings. There's a recipe to clear it's contents though :D
