### ISSUE TITLE
Remove Cyclic Hydrator & Dehydrator - Remove Lava recipe from Melter

### ISSUE THREAD

**Issue by peterhaneve** [NillerMedDild/Enigmatica2Expert#1743]
**Modpack version**
1.80

**Issue**
The Advanced Generators Heat Exchanger allows cooling down Lava to heat up Water into Steam. It produces blocks of Obsidian as a result. However, these blocks can be melted back into Lava for free in the Cyclic melter, giving relatively early game power from nothing.

With the standard 2 RF/mb ratio from Steam Turbine Controller (Advanced Generators), Steam Dynamo (Thermal Expansion) or Steam Turbine (NuclearCraft), one bucket of Lava produces 300 000 RF. A max size Heat Exchanger (50 exchanger blocks, pretty iron heavy but only gated by basic coils) produces up to 4000 mb/t, so this makes a consistent and easy 8000 RF/t with no inputs. The Heat Exchanger can be built with as few as 2 exchanger blocks, so it can be built early game and upgraded on the fly while still online!

Scaling up to a Mekanism turbine at 16 RF/mb and building several heat exchangers can push this build to 64000 RF/t or much higher. A 16x16x16 power plant with this build in creative was pushing nearly 500k RF/t.

It feels like this build is too easy and too powerful given the other options at its tier in pack progression.

**Logs**
Not applicable.

**Possible solution**

Remove the obsidian to lava recipe in the Cyclic melter. There is still a power loop with the Lava Factory Controller (Actually Additions) but it requires 150k RF and quite a bit of infrastructure, so less rewarding. The melter has other early game uses so I would not like to see it fully disabled unless it cannot be tweaked.

**Comment by MorganSimic** [comment]
A note on that, it might be a worth thinking about disabling most of the weird cylic machines alltogether. Stuff like the melter, hydrator, dehydrator. They do nothing that can't be done otherwise and also those machines often turn up high on the tps list, no matter if running or not.

**Comment by NillerMedDild** [comment]
Thanks for the report, we'll get that fixed one way or the other - Note noted Morgan :D

**Comment by peterhaneve** [comment]
I found the Solidifier useful for getting ice early for the tinker IO smart output, but the Hydrator and Dehydrator are probably useless as the Mechanical Squeezer and Mechanical Drying Basin generally outclass them for very low RF usage.
