### ISSUE TITLE
just finished testing the new java versions 1.14 and 1.15 300% better server performance.

### ISSUE THREAD

**Issue by Kuktar** [NillerMedDild/Enigmatica2Expert#1744]
in case you didnt try out the newer versions servers can now use more than 1 cpu core. i did extensive testing and wow it is amazing

**Comment by Kuktar** [comment]
sorry i was not specific. is there any expert pack planned for the newer versions or bringing enigmatica2expert update. thank you for all the hard work you do. i still dont have bragging rights quest done lol

**Comment by Kuktar** [comment]
noticed that enigmatica 5 has expert in mind :P

**Comment by NillerMedDild** [comment]
I have no idea what this issue is about :P

**Comment by Kuktar** [comment]
sorry it wasnt an issue. i just was making sure you knew that newer versions of minecraft use more than 1 cpu core/thread much more effectively. i did some tests and on 1.12 i could not travel more then 1200 blocks per a second because of map load / generation.

with 1.14 update i wasnt really able to determine the upper limit but i got to 5000 blocks per a second and the server didnt lag. i used the diagnol piston method for the test.

**Comment by Discomanco** [comment]
We usually use Discord for discussion :P We already know of the improvements that 1.14 and 1.15 (mainly 1.15) brings to the game, the only thing missing is the mods. E2E can not move to 1.14+, since the mods are not built for that
