### ISSUE TITLE
Thermal Expansion Steam Dynamo - Steam input limited to 2000mb/s

### ISSUE THREAD

**Issue by magicthize** [NillerMedDild/Enigmatica2Expert#1745]
**Modpack version**
Enigmatica 2 Expert 1.81a

**Issue**
Can't seem to input more than 2000mb/s of steam into the Thermal Expansion Steam Dynamo. The Dynamo itself also doesn't seem to always generate/output power despite having/consuming the steam available and unlike other machines the RF generation doesn't increase smoothly but rather "ticks" up every 1.5 seconds or so (hoping that makes sense - can make a video if it helps).

I was testing the following which would be an upgrade to my existing Compression-only power generation.

**Signalum Compression Dynamo**
Fuel:
Crystallized Oil

Augments:
Boiler Conversion
Auxiliary Transmission Coil
Fuel Catalyzer

(The machine reports a maximum steam generation of 3600mb/s)

Outputting the steam to:

**Steam Dynamo**
Augments:
Auxiliary Transmission Coil
Fuel Catalyzer
Turbine Conversion

(Maximum steam 3000mb/s).

I initially tested with the super-laminar fluiduct which should provide unlimited steam throughput but the Steam Dynamo only reports 2000mb/s available. Followed up by testing with EnderIO conduits and Mekanism pipes with the same or worse results.

Switching over to my single player test world I replicated the setup but have not been able to provide more than 2000mb/s to the Steam Dynamo even if I run 2 Compression Dynamos worth of steam into it. I can increase the power output with a different augment configuration but I don't seem to be capable of maxing out the machine's capability.

My Google-Fu failed me and I wasn't sure where else to look so I figured I'd ask here as I'm a little puzzled and I'm not sure if it it's a bug or intentional.

**Logs**
n/a

**Comment by NillerMedDild** [comment]
Thanks for the report, I believe this is a side-effect of the massive rf/t increase the Steam Dynamo received in a recent update, I'll see what we can do.

**Comment by MorganSimic** [comment]
Also on a related note, i heard a report on Discord, that with the new numbers the Steam Dynamo with boiler conversion does produce more steam pert tick than the internal buffer can hold. 
Also i took a brief look at the configs and it seems steam is hard to configure since it scales off the RF config.
