### ISSUE TITLE
Alchemy array caused a crash on dedicated server

### ISSUE THREAD

**Issue by Tyde5969** [NillerMedDild/Enigmatica2Expert#1746]
**Modpack version**
1.81a

**Issue**
No one was using the Alchemy array when we crashed

**Logs**
https://pastebin.com/gvEC9Yqj

**Comment by NillerMedDild** [comment]
Thanks for the report, I found the issue on the Blood Magic issue tracker (linked above). I recommend removing the Alchemy Array with something like MCEdit.

**Comment by NillerMedDild** [comment]
I do not believe I can fix this, and the majority of modders no longer support 1.12, so I'll close this issue.

Nethertheless, thank you for reporting :)
