### ISSUE TITLE
Buff Thermal Dynamics Fluxducts

### ISSUE THREAD

**Issue by jwoods7097** [NillerMedDild/Enigmatica2Expert#1747]
**Modpack version**
1.81a

**Issue**
Redstone Energy Fluxducts and above require the Fluid Transposer to craft, which gates them behind Thermal Expansion. However, the top tier Mekanism and EnderIO energy cables can be crafted before unlocking Thermal, and have more than double the transfer rate of the Resonant Fluxduct.

**Logs**
None applicable

**Comment by Krutoy242** [comment]
This also can be resolved with adding more variants of "Fill fluid" crafts with another machines, like NC fluid infuser. @NillerMedDild  I can make this

**Comment by NillerMedDild** [comment]
Thanks for the report, and sounds good @Krutoy242!

**Comment by MorganSimic** [comment]
Oh, yeah the numbers of thermal ducts definitely need to be brought in line with the rest of the power transfer. Apart from being gated behind thermal, they suck in terms of power transfer. Not counting cryo stabilized fluxducts. And the lower tiers are so involved in crafting with all the parts it feels highly unrewarding to use those.
Also filling recipes in the fluid infuser, yes please!
