### ISSUE TITLE
Suggestion: Add 'Not Enough RTGs' mod

### ISSUE THREAD

**Issue by therodet** [NillerMedDild/Enigmatica2Expert#1750]
**Modpack version**
1.81a

**Issue**
With the availability of the Californium 250 fuel from dragon lairs, the avid explorer can easily have an abundance of RTGs for early-mid game power. Adding 'Not Enough RTGs' would help clean things up, and potentially reduce TPS lag (I don't have any evidence on this, but 1 block vs many is usually a good thing).

**Comment by NillerMedDild** [comment]
I think they make high amounts of passive power a little too convinient, I'd rather not add it to be honest. Thanks for the suggestion.
