### ISSUE TITLE
Destroying Advanced Generator with Mekanism's Laser crashes game

### ISSUE THREAD

**Issue by Rakanamatata** [NillerMedDild/Enigmatica2Expert#1754]
**Modpack version**
1.81a

**Issue**
Destroying an Advanced Generator block with Mekanism's Laser crashes the game as long as the entity exists. Tested with Advanced Alloy Turbine on multiblock and a lone Gas Turbine Generator, both crashed. (removing the block drops an world editor stops the crashing)

**Logs**
https://pastebin.com/dcfgvFfa

**Comment by NillerMedDild** [comment]
I'm afraid this will never get fixed, as Mekanism no longer supports 1.12 unless the issue is extremely critical, and Advanced Generators hasn't been worked on in over 2 years :(
