### ISSUE TITLE
Logistic Pipes not craftable

### ISSUE THREAD

**Issue by Discomanco** [NillerMedDild/Enigmatica2Expert#1756]
**Modpack version**
1.81a

**Issue**
Logistic Pipes not craftable, issue taken from Discord
https://gyazo.com/7fb3365e536f3a498b5dcf0b3b34f107
Likely another byproduct from the OreDict cleanup, have not double checked if it's correct.

**Comment by NillerMedDild** [comment]
Thanks for relaying!

**Comment by davidcosta325** [comment]
strange, for me it's normal

**Comment by KleinGrrmpf** [comment]
I can craft them, too
