### ISSUE TITLE
NC Alloy Furnace Steel Recipe not working

### ISSUE THREAD

**Issue by natebc** [NillerMedDild/Enigmatica2Expert#1757]
**Modpack version**
1.81a

**Issue**
Nuclearcraft Alloy Furnace 1 iron + 2 coal =  1 steel recipe doesn't work (SS has 10 + 20 but i've also tried just 1+2)

**Screenshots**
![Annotation 2020-06-27 122912](https://user-images.githubusercontent.com/53818/85927537-bc1dad00-b874-11ea-91d8-a95d88a6e153.png)
![Annotation 2020-06-27 123356](https://user-images.githubusercontent.com/53818/85927541-bf189d80-b874-11ea-8f41-d743e27c07ed.png)

**Comment by NillerMedDild** [comment]
Could you try without upgrades please? :)

**Comment by natebc** [comment]
same :(
![image](https://user-images.githubusercontent.com/53818/85929092-06585b80-b880-11ea-9860-ceb6505c2062.png)

**Comment by NillerMedDild** [comment]
Hmm.. can your Alloy Furnace make other things?

**Comment by natebc** [comment]
Yep. Right after I found this out I swapped in the Graphite + Iron Steel recipe and it works just fine.

**Comment by NillerMedDild** [comment]
Cool, thanks, I'll investigate :)

**Comment by Nabbieshtron** [comment]
Sorry but i didnt see that recipe at all with coal at all.

**Comment by natebc** [comment]
@NillerMedDild, Note that shortly after this I restarted my server because i was encountering the "0 vis available" thing in Thaumcraft and it occurred to me to re-test this recipe ... and it works fine after the restart.

FWIW: my server is essentially private, just me, built-in install on Bisect and reboots nigthly. It had been up about 10-12 hours when i encountered this and i'd played probably 4-5 of those.

**Comment by NillerMedDild** [comment]
Alright, thanks for the follow-up, not much I can do about that sadly :/
