### ISSUE TITLE
Please add Extra Bit Manipulation to the pack

### ISSUE THREAD

**Issue by Zuthal** [NillerMedDild/Enigmatica2Expert#1758]
[Extra Bit Manipulation](https://www.curseforge.com/minecraft/mc-mods/extra-bit-manipulation) adds significant utility for Chisels and Bits, such as the ability to make certain shapes and to shift chiseled blocks by single bit increments. It does not seem to have any functionality that would be useful in breaking modpack progression either, and it is a quite small mod, so I do not see much reason to not include it.

**Comment by NillerMedDild** [comment]
I'll think about it, thanks for the suggestion :)

**Comment by Zuthal** [comment]
Thanks!
