### ISSUE TITLE
Casting Table Rendering Bug

### ISSUE THREAD

**Issue by Cardinalstars** [NillerMedDild/Enigmatica2Expert#176]
I seem to be encountering a rendering bug with TiC with only this pack.  Take a look.  I've made no changes to the pack.

![2018-08-03_13 10 47](https://user-images.githubusercontent.com/42074409/43658610-068c9294-971f-11e8-8c8c-e8dff29b7f18.png)

I have my cast in my hand ready to place into the casting table.  You can clearly see it is an ingot cast.

![2018-08-03_13 10 50](https://user-images.githubusercontent.com/42074409/43658614-0cfff3fa-971f-11e8-9293-845823c0e77c.png)

The cast has been place in but there is no update for WAWLA and no update for the casting table either.  It's essentially invisible and makes casting very annoying.

![2018-08-03_13 10 53](https://user-images.githubusercontent.com/42074409/43658617-0f1d86f2-971f-11e8-8118-c328b6d8de3f.png)

Everything still casts fine, but it doesn't want to render.  How do I fix this?

**Comment by Discomanco** [comment]
#169 #170 #173
Please search before making new issues :)
