### ISSUE TITLE
Infinity energy

### ISSUE THREAD

**Issue by NeutralPlasma** [NillerMedDild/Enigmatica2Expert#1761]
**Modpack version**
1.81a

**Issue**
Basically put wireless crafting terminal into mekanism multiblock energy storage and its just gonna make energy instead of charging up the terminal.
**Picture**
http://images.virtusdevelops.eu/shareX/hh4z5ws9.png

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by thecodingchicken** [comment]
This sounded familar, it looks like someone made an issue with it here at #1487, and p4445w0rd wasn't able to replicate it, as mentioned at https://github.com/p455w0rd/WirelessCraftingTerminal/issues/316.   I had the same bug, but if p445w0rd's not able to reproduce it, it can't be fixed.  Not to mention, it's very unlikely the WCT or matrix will be disabled, as both are very useful.  At most, we have to trust the players to not abuse this bug once they know about it.

**Comment by Stamparas** [comment]
actually this consumes the power from the matrix and also consumes the energy you already got on the wireless terminal

**Comment by NeutralPlasma** [comment]
I mean I have left it there since I made this post and it's still making me infinity power hasn't gone up or down I just get free energy.

**Comment by Stamparas** [comment]
I tried ut, ut didnt work at all for me,

**Comment by NillerMedDild** [comment]
I've decided not to take this issue any further, as most modders no longer work on Minecraft 1.12, and development of Enigmatica is focused on Minecraft 1.15+ - I hope that's understandable :)
Thank you for helping to make E2E polished by reporting, I hope to see you in E5+!
