### ISSUE TITLE
Only void and fortresses in Nether

### ISSUE THREAD

**Issue by Yavenn** [NillerMedDild/Enigmatica2Expert#1762]
**Modpack version**
1.35

**Issue**
 Hello,
I have a problem with progression in Enigmatica 2 Expert as only thing that i have in Nether is void and fortresses, there are no blocks. i have to find cobalt and so on. I tried to make new portal from overworld 1500 block away from first one and was teleported to new place in nether, but again i can see only void and fortress.
Any idea how to solve this?
Version 1.35

**Logs**

**Comment by NillerMedDild** [comment]
It sounds like you're playing the skyblock version of the modpack. The nether is meant to be like that. Use JEI to find out how to obtain nether materials. :)

**Comment by Yavenn** [comment]
Hi,
That's sound resonable, however i have changed world generation when creating new world from skyblock to realistic. overworld looks normal. is there any way that i could turn on nether or have to find different version of modpack? Used the one from Twitch.

Anyway sorry for bothering you.
Many thanks.

**Comment by NillerMedDild** [comment]
If you don't want to play a skyblock modpack, I highly recommend that you use normal Enigmatica 2: Expert instead :) 
https://www.curseforge.com/minecraft/modpacks/enigmatica2expert

If you'd prefer to change the skyblock pack, the void Nether (and end) is controlled by the mod Void Island Control. You can change it's config (line 28) to generate normal nether terrain.
