### ISSUE TITLE
Energetic Infuser (Flux Reconstruction)

### ISSUE THREAD

**Issue by davidcosta325** [NillerMedDild/Enigmatica2Expert#1763]
modpack 1.81a

![image](https://user-images.githubusercontent.com/66092486/86502529-9c0d5280-bd7a-11ea-928e-7b0704262853.png)

the machine, with the modifier to repair, is not working

**Comment by davidcosta325** [comment]
the machine uses energy, however, does not repair

**Comment by stevenkxu** [comment]
You need to give the machine liquid Essence of Knowledge for it to repair things.

**Comment by davidcosta325** [comment]
strange, because I'm trying to put xp and it's not going

**Comment by davidcosta325** [comment]
ok, manage to insert the xp in the machine, it only accepts the thermal itself
