### ISSUE TITLE
Tinkers bolts turn Terra steel into normal Steel

### ISSUE THREAD

**Issue by Mizque** [NillerMedDild/Enigmatica2Expert#1764]
**Modpack version**
1.81a

**Issue**
When making a Terra Steel bolt core for the mana draw to repair, it kept the living wood core I'd used but turned the Terra Steel coating into a normal Steel coating

**Logs**
N/A

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by KleinGrrmpf** [comment]
I could make a Livingwood-Terrasteel Bolt Core, or did I not do what was described?
![2020-08-05_16 50 30](https://user-images.githubusercontent.com/50833808/89427688-d7b18880-d73b-11ea-8ed1-15ae24128dfb.png)
