### ISSUE TITLE
Pressed wax not usable for capsules

### ISSUE THREAD

**Issue by Mizque** [NillerMedDild/Enigmatica2Expert#1765]
**Modpack version**
1.81a

**Issue**
JEI look up shows Pressed Wax from Pam's Harvest craft as an option for making the wax capsules from forestry, however, it will not allow them to craft for some reason

**Logs**
N/A

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by KleinGrrmpf** [comment]
Can confirm

**Comment by NillerMedDild** [comment]
I've decided not to take this issue any further, as most modders no longer work on Minecraft 1.12, and development of Enigmatica is focused on Minecraft 1.15+ - I hope that's understandable :)
Thank you for helping to make E2E polished by reporting, I hope to see you in E5+!
