### ISSUE TITLE
Quests reset for one of us In LAN

### ISSUE THREAD

**Issue by Flamebom** [NillerMedDild/Enigmatica2Expert#1766]
**Modpack version**
1.81a

**Issue**
Quests for me reset, but for the world owner it stays the same. I had 90% of the quests complete, and now they are all gone

**Comment by NillerMedDild** [comment]
There are quest progress backup files in the world folder, and additional quest progress backup files in the backups folder :)

A lot of things do not work very well in LAN worlds, I highly recommend that you switch to a dedicated server if possible.
