### ISSUE TITLE
[SUGGESTION] Add Clumps mod

### ISSUE THREAD

**Issue by DrewSin-4** [NillerMedDild/Enigmatica2Expert#1767]
Hello,

I'm not too sure where to submit this suggestion so I decided to do it on the Git.

Addition of the clumps mod could be super useful for entity lag on Servers and possible FPS lag on clients.

If a player ever accidentally creates a setup where XP isn't properly handled and its just placed as ground item it can turn into a huge issue due to how many entities there are.

Clumps pretty much solves this issue.

Mod link - https://www.curseforge.com/minecraft/mc-mods/clumps

**Comment by NillerMedDild** [comment]
Clumps is already in the modpack :P
