### ISSUE TITLE
Applied Energistics and Storage Drawers

### ISSUE THREAD

**Issue by huihui-15643358** [NillerMedDild/Enigmatica2Expert#1768]
**Modpack version**
Enigmatica2Expert 1.81a
Input version here

**Issue**
Applied Energistics and Storage Drawers. Connect the drawer to the AE network via the ME Storage Bus.The contents in the drawer will be doubled and Cause automatic synthesis to fail.
![affix](https://user-images.githubusercontent.com/53024564/87237627-329cdc00-c42b-11ea-8cb8-90d9e7e915c8.png)

**Comment by huihui-15643358** [comment]
By the way, this is just a display bug

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
I've decided not to take this issue any further, as most modders no longer work on Minecraft 1.12, and development of Enigmatica is focused on Minecraft 1.15+ - I hope that's understandable :)
Thank you for helping to make E2E polished by reporting, I hope to see you in E5+!
