### ISSUE TITLE
Mekanism and Ender Io power conduit problems

### ISSUE THREAD

**Issue by Nabbieshtron** [NillerMedDild/Enigmatica2Expert#1769]
Version 1.18a
Here is a link https://youtu.be/mractrTfFec
I dont what is happening here it should have the connection but it hasn't.
If this issue reported delete it!

**Comment by Nabbieshtron** [comment]
I tested few things and it seems to output power it needs to be on auto-eject

**Comment by NillerMedDild** [comment]
EnderIO power conduits are a bit picky :P
