### ISSUE TITLE
it would be good to have an alternate recipe for the titanium aluminide

### ISSUE THREAD

**Issue by croftyraider** [NillerMedDild/Enigmatica2Expert#177]
Using the 1.33 pack, I put in 48 titanium and a bunch of aluminum and it ate up all the titanium and gave me 3 titanium aluminide ingots. Nothing else.

Needless to say I was a bit unhappy. Maybe add a recipe to some other alloy smelter or arc furnace for in the meantime?

**Comment by NillerMedDild** [comment]
Update to 1.34, the issue is fixed :)
