### ISSUE TITLE
Day and Night Time 

### ISSUE THREAD

**Issue by Nabbieshtron** [NillerMedDild/Enigmatica2Expert#1770]
A suggestion to make day and night longer. At first i didn't think that was an issue but later it became annoying to sleep so often.  ;P

**Comment by NillerMedDild** [comment]
That would have too many unforseen side effects down the line, so I'm afraid not :(

**Comment by Nabbieshtron** [comment]
Oh i get it it would interfere with other mods okey okey i just have to deal with it
