### ISSUE TITLE
Copper, titanium and iridium duplication

### ISSUE THREAD

**Issue by darktiti** [NillerMedDild/Enigmatica2Expert#1774]
**Modpack version**
1.81a

**Issue**
duplication when transforming 1 ingot of copper in 2 copper rod, if I melt the copper rod that give me 6 nugets ( 1 ingot = 12 nugets ) and that also do it to the titanium and the iridium

**Comment by NillerMedDild** [comment]
Thanks for the report, we'll look into it :)

**Comment by Krutoy242** [comment]
This happens because you probably accidentally removed [few excess lines](https://github.com/NillerMedDild/Enigmatica2Expert/pull/1773/files#diff-fbbc4ee79c8293624b10943722b3673bR113-R116).
Fixed in #1773
