### ISSUE TITLE
Minecraft crash when i use a piston to push a Razor Wire

### ISSUE THREAD

**Issue by Minemobs** [NillerMedDild/Enigmatica2Expert#1775]
**Modpack version**
1.81a

**Issue**
Minecraft crash when i use a piston to push a Razor Wire

**Logs**
https://hastebin.com/anorebusaf.coffeescript

**Comment by Discomanco** [comment]
Seems like bad interaction between IE and Quark. AKA, this will likely never get fixed. Solution? Don't push Razor Wires with Pistons.

If it prevents you from loading up your world, open up the Forge.cfg file in the Configs folder, find "Remove Erroring Tile Entities?" and set that to "true"

**Comment by NillerMedDild** [comment]
To be honest we should disable this entirely.
