### ISSUE TITLE
Stuck In Bed

### ISSUE THREAD

**Issue by Jvdv434** [NillerMedDild/Enigmatica2Expert#1776]
**Modpack version**

1.81a

**Issue**

Sometimes when sleeping in a bed. When it turns day I am stuck in the bed and am unable to leave. The only way to get out is to kick myself from the server. The same issue also happened to my friend on the same server.

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
We have a mod in place that's supposed to fix this, if it doesn't there's not much we can do I'm afraid :/
