### ISSUE TITLE
Time in a bottle + External Heater makes ores disappear

### ISSUE THREAD

**Issue by TiuTalk** [NillerMedDild/Enigmatica2Expert#1777]
**Modpack version**
1.81a

**Issue**
Using the **Time in a bottle** on **External Heater** powered furnaces made the furnace stop working, and the ores being smelted disappeared.

**How to reproduce**
1. Connect one or more furnaces to **External Heater** 
2. Provide them with ores
3. Speed the furnaces with **Time in a bottle**
4. Furnace stopped, ores disappeared

**Logs**
Nothing appeared on the logs :(

What I believe is happening is the following: the time in a bottle makes the furnace tick faster, which consumes more "fuel" faster, but the heater can't keep up providing fuel to them, so the burning operation stops midway through.

Since the furnace "consumes" the item when the smelting operation begins, it just looses the progress and the item with it.

If that's the case, I don't think this is a bug in the pack or even in IE.

-----

![2020-07-25_13 26 02](https://user-images.githubusercontent.com/145339/88461513-8e7b5200-ce7a-11ea-9027-f8b44e013456.png)

**Comment by NillerMedDild** [comment]
I believe that is what's happening, this issue has been reported before iirc, and seeing as it has to do with tick acceleration it's a won't fix for most mod developers. Sorry!
