### ISSUE TITLE
Mekanism Digital Miner having trouble mining tin ore in Deep Dark

### ISSUE THREAD

**Issue by pl1173** [NillerMedDild/Enigmatica2Expert#1778]
**Modpack version**
1.81a

**Issue**
The Digital Miner has some trouble mining tin ore in the Deep Dark, depending on the radius setting. At radius of 32, the digital miner fails to detect any tin ore, even if it is right next to the miner. When the radius was reduced to 12, it was able to detect the ore. The maximum radius at which it can detect ore can change when the miner is placed at a different location.

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by NillerMedDild** [comment]
Thank you for the report. We're aware that the Digital Miner has some issues when it comes to specific ores in specific locations, but sadly Mekanism will not be updated further in 1.12, so there's not much we can do :(
