### ISSUE TITLE
Multiple food items don't have a recipe

### ISSUE THREAD

**Issue by KleinGrrmpf** [NillerMedDild/Enigmatica2Expert#1779]
**Modpack version**
1.81a

**Issue**
Berry Vinaigrette Salad from Pam's Harvestcraft is not craftable although it is shown in JEI. According to the wiki it does have a recipe. Don't know if this is a bug in the modpack or the mod itself.

https://ftb.gamepedia.com/Berry_Vinaigrette_Salad

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by KleinGrrmpf** [comment]
Found another one that has no recipe:
Garlic Steak, also from Harvestcraft should also have a recipe.

https://ftb.gamepedia.com/Garlic_Steak

**Comment by KleinGrrmpf** [comment]
Found another one without recipe:
BBQ Jackfruit, also from Harvestcraft, should also have a recipe.

https://harvestcraftmod.fandom.com/wiki/BBQ_Jackfruit

**Comment by KleinGrrmpf** [comment]
Maybe this helps fixing the issue: 

https://github.com/MatrexsVigil/harvestcraft/issues/372

**Comment by KleinGrrmpf** [comment]
[swedishmeatballsitem.txt](https://github.com/NillerMedDild/Enigmatica2Expert/files/5023678/swedishmeatballsitem.txt)

As I couldn't find an online recipe for swedish meatballs, I extracted this on out of the harvestcraft mod. The issue is the one stated in the harvestcraft issue.

**Comment by NillerMedDild** [comment]
(Note to self or the person who fixes this) Found the following fixes after digging through the above issue.

```zenscript
oreDict.cropLychee.add(<harvestcraft:lycheeitem>);
oreDict.cropJackfruit.add(<harvestcraft:jackfruititem>);

recipes.addShapeless(<harvestcraft:imitationcrabsticksitem>, [<ore:toolCuttingboard>, <ore:foodFlour>, <ore:listAllfishcooked>, <ore:listAllegg>, <minecraft:dye:1>]);
recipes.addShapeless(<harvestcraft:saucedlambkebabitem>, [<ore:toolMixingbowl>, <ore:foodLambkebab>, <ore:foodPlainyogurt>, <ore:listAllheavycream>, <ore:cropGarlic>, <ore:cropSpiceleaf>, <ore:cropLime>]);
recipes.addShapeless(<harvestcraft:swedishmeatballsitem>, [<ore:toolSaucepan>, <ore:foodGroundbeef>, <ore:foodFlour>, <ore:cropSpiceleaf>, <ore:foodGroundnutmeg>, <ore:listAllheavycream>, <ore:foodBlackpepper>, <ore:listAllheavycream>, <ore:listAllegg>]);
recipes.addShapeless(<harvestcraft:garlicsteakitem>, [<ore:toolSkillet>, <ore:listAllbeefraw>, <ore:cropGarlic>, <ore:foodButter>, <ore:cropSpiceleaf>]);

recipes.removeShapeless(<harvestcraft:quesadillaitem>);
recipes.addShapeless(<harvestcraft:quesadillaitem>, [<ore:toolSkillet>, <ore:foodTortilla>, <ore:foodCheese>]);
recipes.addShapeless(<harvestcraft:schnitzelitem>, [<ore:toolSkillet>, <ore:listAllmuttonraw>, <ore:foodFlour>, <ore:cropLemon>, <ore:foodOliveoil>, <ore:foodBlackpepper>]);
recipes.addShapeless(<harvestcraft:schnitzelitem>, [<ore:toolSkillet>, <ore:listAllporkraw>, <ore:foodFlour>, <ore:cropLemon>, <ore:foodOliveoil>, <ore:foodBlackpepper>]);
recipes.addShapeless(<harvestcraft:bratwurstitem>, [<ore:toolCuttingboard>, <ore:foodPorksausage>, <ore:foodPickles>, <ore:cropOnion>, <minecraft:bread>]);
```

**Comment by KleinGrrmpf** [comment]
Found two more without recipes:
Pork Rinds and Cracklins (both from harvestcraft)
https://ftb.gamepedia.com/Pork_Rinds
https://ftb.gamepedia.com/Cracklins
