### ISSUE TITLE
Ultimate Tier Installer JEI description

### ISSUE THREAD

**Issue by Ricket** [NillerMedDild/Enigmatica2Expert#1780]
**Modpack version**
1.81a

**Issue**
Ultimate Tier Installer is [apparently not implemented](https://github.com/mekanism/Mekanism/issues/3712) in 1.12 Mekanism. I crafted a handful of them and then was confused why I couldn't right-click them onto my machines. IMO they should be removed via crafttweaker so that others don't have this same confusion. (unless of course they have some purpose, in which case I would love to know!)

**Comment by Ricket** [comment]
Sorry I just saw the quest page about the tier installer. "only works on Bins, Energy Cubes, Gas Tanks and Tanks"

Could you add that as an info tab on the ultimate tier installer usages?

**Comment by NillerMedDild** [comment]
Sure thing :)
