### ISSUE TITLE
[1.81a] Unconfigured Cyclic Pattern Replicator crash and world corrupt

### ISSUE THREAD

**Issue by Frikkle** [NillerMedDild/Enigmatica2Expert#1783]
**Modpack version**
1.81a

**Issue**
Investigating this after a report on Discord by 𝕾𝖔𝖒𝖊 𝕯𝖚𝖉𝖊.

When placing down a Cyclic Pattern Replicator in the world (unpowered), opening its GUI and clicking the unmarked gray button. The game would instantly crash and loading back into the world would result in the same.

![2020-08-01_09 41 30](https://user-images.githubusercontent.com/9324165/89097142-9b4cf800-d3dc-11ea-8cc3-4240d460ff3d.png)

I also traced the most likely cause of this to a missing null-check in the cyclic code. I'll report this crash over there as well.

**Logs**
https://pastebin.com/7cq6mBVy

**Comment by SERGIOHERB** [comment]
Como resolver esse problema?
