### ISSUE TITLE
Digital miner requires non NBT affected advanced computer

### ISSUE THREAD

**Issue by Kimochii-x3** [NillerMedDild/Enigmatica2Expert#1784]
**Modpack version**
1.81a

**Issue**
Mekanism digital miner requiring non NBT affected Advanced Computer

I had previously placed the advanced computer to check it out, which gave it NBT tag "Computer ID: 0"
The recipe requires freshly made advanced computer.

Could have a custom recipe where a computer with NBT tag would be freshened out or recipe adjusted to allow NBT affected craft computers to be used

Non NBT affected advanced computer
![image](https://user-images.githubusercontent.com/38957871/89128270-8eb7c500-d4ec-11ea-8e37-707758d384e6.png)

NBT affected advanced computer
![image](https://user-images.githubusercontent.com/38957871/89128296-b3ac3800-d4ec-11ea-8930-92e30f3e4fe9.png)

**Logs**
N/A

**Comment by NillerMedDild** [comment]
I've changed it so the computer may have data on it :) Thanks for the report.

**Comment by NillerMedDild** [comment]
It'll accept either normal or advanced computers in the future, and any tags.
