### ISSUE TITLE
ME Interface blocking mode not working with Modular Machinery

### ISSUE THREAD

**Issue by KleinGrrmpf** [NillerMedDild/Enigmatica2Expert#1785]
**Modpack version**
1.81a

**Issue**
Having an interface set to blocking mode facing the item input of a modular machinery doesn't obey the blocking mode when autocrafting. This is especially a problem when you have more inventory space than items that are used for crafting. Example:

You are autocrafting multiple wyvern cores. You don't have enough ludicrite, so the system also requests ludicrite blocks. The wyvern cores only need five different items, so even although the interface is set to blocking mode, it puts the five items for the wyvern core into the input BUT ALSO one item of the recipe for ludicrite blocks.
This is nerveracking because if you use XNET to determine what is in the input to put the matching fluid into the fluid input, it can happen that both relevant items are in the input and XNET puts the wrong fluid into the fluid input which messes up the system.

I guess this is a mod-related bug and I would guess that it is AE2 not correctly working, but I thought I'd share it here and maybe somebody here has an idea on how to manually fix it.

**Logs**
-

**Comment by NillerMedDild** [comment]
Thanks for the report. This is a very common issue, it happens with most blocks really. I suggest you place the Interface next to a chest, and then pipe to the intended input. 

I don't think this will ever be fixed, I think it's more or less just how it works :(
