### ISSUE TITLE
Electric Arc Furnace steel recipe produces wrong type of steel ingot

### ISSUE THREAD

**Issue by Branjoman** [NillerMedDild/Enigmatica2Expert#1786]
Modpack version: 1.81a

Issue: The steel recipe in the advanced rocketry electric arc furnace produces Vulpes library steel ingots instead of Thermal Foundation steel ingots. I'm assuming that all steel recipes should be producing the latter, as the former type of steel doesn't appear in JEI.

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by KleinGrrmpf** [comment]
Can confirm this. The recipe even shows up in JEI

**Comment by NillerMedDild** [comment]
Huh, alright, that sucks :P I'll get it fixed then.
