### ISSUE TITLE
Thaumium Fortress Helm JEI recipe not working.  Have to use Thaumonomicon.

### ISSUE THREAD

**Issue by JJSax** [NillerMedDild/Enigmatica2Expert#1787]
**Modpack version**
1.81a

**Issue**
The JEI recipe for the Thaumium Fortress Helm is probably the intended recipe, but in the Thaumonomicon, it shows a different recipe.  The JEI recipe does not work, the Thauminomicon owe does.

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by KleinGrrmpf** [comment]
Can confirm the different recipes in JEI

**Comment by NillerMedDild** [comment]
Doesn't really sound like an issue then, to be honest.
