### ISSUE TITLE
Crash on Worldload 1.76a

### ISSUE THREAD

**Issue by xsimx1990** [NillerMedDild/Enigmatica2Expert#1788]
**Modpack version**
1.76

**Issue**
Crash on Worldload, vanillafix give Compac Machines 3, Capability Adapter & Mekanism as reason
These three mods are used alot in my base, but i didnt change any special thing recently..

**Logs**
crash log:
https://pastebin.com/VVkzwVT3

**Comment by NillerMedDild** [comment]
Please remove VanillaFix and update to the newest version and see if the issue persists.

**Comment by xsimx1990** [comment]
i do as you said and now i get this crash report (almost the same i guess :( ):

https://pastebin.com/u9at7GEL

that said, i already had issues before with updating the modpack to a newer version, thats the reason i stayed at 1.76a

**Comment by NillerMedDild** [comment]
Please remove all the mods you have added. Especially Optifine ^^

**Comment by xsimx1990** [comment]
so i removed every mod i added, except simple void dimensions and thats the crash report:
https://pastebin.com/qusbpeC7

after that i also removed simple void dimension (thats where all my machines, and compactmachines are at, and i get also a crash :(  (simple dimensions, and i guess also vanillafix, because i got like 20 fps with sutter in the overworld.. with a 'okeyish' hardware setup but amd processor...)

https://pastebin.com/NB0wddsV

**Comment by NillerMedDild** [comment]
Hmm.. The thing that's going wrong is the AE Capability Adapter from the mod `capabilityadapter-1.1.0`, I believe. Would you mind also removing that?

My apologies for having you remove so much without a result, those mods are just usually causes of issues.

**Comment by xsimx1990** [comment]
no problem, thanks for the fast responses :) 

so after i remove capabilityadapter, the world loaded, so thats a good sign

ofcourse i couldnt get to the void dimension, and after i try to teleport to a compact machine, the game just freezed and then crashed

https://pastebin.com/mGjNPg2M

maybe i try tomorrow to just remove the capabilityadapter mod, and if this works i try to adapt my system

**Comment by NillerMedDild** [comment]
I think that would do the trick, I hope you have plenty of backups :D

**Comment by xsimx1990** [comment]
and luckily i have made the 'remove mod session' on an new profile :D should be fine

thanks for the help, guess i can close the issue :)

**Comment by NillerMedDild** [comment]
I'll keep it open, I'd like to investigate what went wrong with the Capability Adapter.
