### ISSUE TITLE
Ender IO: Can craft Antenna Extension for Block, that you can't craft - 1.81a

### ISSUE THREAD

**Issue by ImDovah** [NillerMedDild/Enigmatica2Expert#1789]
**Modpack version**
1.81a

**Issue**
You can craft the "Wireless Charging Antenna Extension", but not the "Enhanced Wireless Charging Antenna".
The "Wireless Charging Antenna Extension" ONLY works with the "Enhanced Wireless Charging Antenna".
The extension is NOT for the "Wireless Charging Antenna", it is written there if you expand the description with SHIFT on the extension.

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.
