### ISSUE TITLE
Petrified mobs are invisible after the first hit with a pickaxe

### ISSUE THREAD

**Issue by vrnRaptor** [NillerMedDild/Enigmatica2Expert#1790]
Mod version:
iceandfire-1.9.1-1.12.2
LLibrary 1.7.19

Issue:
The petrified mob becomes invisible after the first hit with a pickaxe.
![ice_and_fire](https://user-images.githubusercontent.com/13599993/89641867-51bc4b80-d8bb-11ea-879c-244939f6ac69.gif)

**Comment by NillerMedDild** [comment]
Hmm, why did you update Ice & Fire yourself?

**Comment by vrnRaptor** [comment]
Sorry, I wrote in the wrong place, I wanted to write to the mod developers.
