### ISSUE TITLE
Add Essentia Resonator to Morph-o-tool

### ISSUE THREAD

**Issue by Ricket** [NillerMedDild/Enigmatica2Expert#1792]
**Modpack version**
1.81a

**Issue**
The Essentia Resonator (Thaumcraft) seems like a good candidate to whitelist for the morph-o-tool. It seems to fit in with the other wrenches and I'm not aware of another wrench-like item in Thaumcraft (though still pretty early in my thaumcraft knowledge so I might've missed something).

edit: It occurs to me that the glove is more of a wrench than the resonator. But doesn't seem like a good idea to put the glove into the morph-o-tool, seems like it might mess with the glove mechanics.

**Comment by NillerMedDild** [comment]
Hmm, I'll look into it. Agreed, definitely no on the glove :P

**Comment by NillerMedDild** [comment]
Neither would make much sense to be honest.
