### ISSUE TITLE
Bug: Items in furnace with external heater disappears on using time in a bottle

### ISSUE THREAD

**Issue by AchalS-iglushrek** [NillerMedDild/Enigmatica2Expert#1793]
**Modpack version**
latest - 1.81a iirc

**Issue**
On using a standard furnace(FastFurnace) with external heater from IE, if we use time in a bottle thrice on it, everything inside the furnace disappears and it resets like a new block. This happened on the server and not once but everytime I tried, also confirmed by another person on the server (Official E2EA) with the same setup. IGN:iglushrek, and of the other person IGN:krazygeek32

RIP Bronze.

**Comment by Discomanco** [comment]
#1777 
Wont be fixed due to weird mod interactions and devs having moved in
