### ISSUE TITLE
Charged certus quartz ore gives regular certus quartz

### ISSUE THREAD

**Issue by Porcy** [NillerMedDild/Enigmatica2Expert#1795]
**Modpack version**
1.81a
Input version here

**Issue**
When charged certus quartz is inserted into Thermal Expansion's pulverizer or Actually Additions' crusher, it outputs regular certus quartz. In JEI, the AA crusher's page lists both certus quartz as the output (It can't be...) 
Input short description of the issue here

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by NillerMedDild** [comment]
Do you mean that Charged Certus Quartz yields Certus Quartz Dust?

**Comment by Porcy** [comment]
Nope. Charged certus quartz ore yields normal (non-charged) certus quartz. It's confusing because JEI reports both outputs (I.E. Inserting charged ore gives charged quartz and non-charged quartz.)

**Comment by NillerMedDild** [comment]
Ah okay! We'll get that corrected :)
