### ISSUE TITLE
Botania Bug Flower

### ISSUE THREAD

**Issue by Stamparas** [NillerMedDild/Enigmatica2Expert#1796]
**Modpack version**
1.81a

**Issue**
you get the "botania flower" wich you can only get through bugs, description of flower as follows "If you have this, it means something went wrong, you should report it", you get it by using the unbreakable wand from better builders wands on a generating flower (i got it from the Endoflame)

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by musicsoul0142** [comment]
Endoflame has NBTs, but there is a bug in the unbreakable wand that erases the NBTs of the TileEntity blocks to be installed. Thus, this is a bug in BetterBuildersWands.

https://github.com/portablejim/BetterBuildersWands/issues/59

**Comment by NillerMedDild** [comment]
I do not believe I can fix this, and the majority of modders no longer support 1.12, so I'll close this issue.

Nethertheless, thank you for reporting :)
