### ISSUE TITLE
can't find rock crystal when mining 150 stack of block(coblestone) on bedrock level

### ISSUE THREAD

**Issue by hacker104** [NillerMedDild/Enigmatica2Expert#1797]
**Modpack version**
1.81

**Issue**
can't find rock crystal when mining 150 stack of block(coblestone) on bedrock level

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by NillerMedDild** [comment]
Have you tried using a Resonating Wand to find them? Have you progressed far enough in Astral Sorcery to be able to see them?

**Comment by hacker104** [comment]
i haven't tried the resoneting wand but i can see then (cofh config change in server 16_andvanced rocetry
)

**Comment by NillerMedDild** [comment]
The intended way to find them is by using the Resonating Wand at night, it helps a lot :)
