### ISSUE TITLE
Incorrect Unbreakable Wand got from loot chests

### ISSUE THREAD

**Issue by unlimitedsola** [NillerMedDild/Enigmatica2Expert#1798]
**Modpack version**
1.81a

**Issue**
There are two different versions of the Unbreakable Wand in the loot pool of quest rewards.
Defined at:
- https://github.com/NillerMedDild/Enigmatica2Expert/blob/master/config/betterquesting/DefaultLoot.json#L2873
- https://github.com/NillerMedDild/Enigmatica2Expert/blob/master/config/betterquesting/DefaultLoot.json#L3642
The one with metadata 12 is craftable but the other with metadata 0 is not craftable and not upgradeable.
Not sure if this is intended, but I think both should have metadata 12 on them.

**Logs**
N/A

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.
