### ISSUE TITLE
Crafting Hydrated Tin Dust from IC2 eats up the water container

### ISSUE THREAD

**Issue by Porcy** [NillerMedDild/Enigmatica2Expert#1799]
**Modpack version**
1.81a

**Issue**
Tried to craft a batch of hydrated tin dust. Put any water container next to tin dust and it will consume the container. I lost 2 thermal expansion portable tanks full of water and one full reinforced ender bucket.

Edit: seems to work fine with vanilla water bucket
**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
The issue is with IC2, I can't fix it I'm afraid. Thanks for the report anyway.
