### ISSUE TITLE
Automation interface creating items out of thin air

### ISSUE THREAD

**Issue by UltimateEnforcer** [NillerMedDild/Enigmatica2Expert#180]
I've got an automation interface on top of an elite crafting table, with a crystaltine ingot recipy stored. Only auto insert from the top is on. The extracted items go into my AE2 system.

 A few days ago, I found 15k crystaltine ingots in my AE2 system, and counting. When I looked inside the crafting table, nothing was being crafted (it also shouldnt, I did not request any). But in the output slot of the automation interface, there was a stack of crystaltine ingots. This stack disappeared slowly (extracted by  a transfernode into my AE2 system). Consequently, me looking at the GUI of the automation interface stopped the creation of crystaltine ingots out of thin air. I subsequently trashed the 15k ingots.

Today, I again found 2k crystaltine ingots in my AE2 system, and counting, yet not having requested any. Again, there was a stack of ingots in the output slot of the automation interface, slowly being extracted. Spooky. And no, there is nothing in my system that would request this amount of crystaltine ingots. I also would not have the resources to make this many even.

P.S. Smart input of the automation interface does not function. Putting it ON, will prevent ALL items from being inserted, also the ones part of the listed recipy.

Version: 1.33 & 1.34

**Comment by NillerMedDild** [comment]
Could you please supply the latest.log file?
Is this on a server or SP?
Is the area chunkloaded?

**Comment by UltimateEnforcer** [comment]
Its on a server, hosted by a friend, though Im usually online by myself. Today nobody else has been online. The area is chunkloaded. See the latest.log file in the attachment, I found out about the crystaltine issue just before 17:17:00.
[latest.log](https://github.com/NillerMedDild/Enigmatica2Expert/files/2260566/latest.log)

**Comment by UltimateEnforcer** [comment]
Regarding the smart insert of the automation interface, in my creative world, it seems to auto insert all items but one, lapis lazuli, to craft the crystaltine ingot. 
![image](https://user-images.githubusercontent.com/41302254/43688727-b7e0a5b4-98ee-11e8-8821-1230b9164a9b.png)
![image](https://user-images.githubusercontent.com/41302254/43688729-bd9a57ca-98ee-11e8-8cba-2f1d5d5f1703.png)
![image](https://user-images.githubusercontent.com/41302254/43688731-c127361a-98ee-11e8-9de4-25998fbd3062.png)
