### ISSUE TITLE
JEI item show

### ISSUE THREAD

**Issue by Stamparas** [NillerMedDild/Enigmatica2Expert#1802]
**Modpack version**
1.81a

**Issue**
pulsating propolis does not show up in JEI, but is very useful as it is needed for resonant cell frame (full), this also goes for mysterious comb wich is used to get the pulsating propolis

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by unlimitedsola** [comment]
I think Uranium Plate is also not searchable from JEI

**Comment by Stamparas** [comment]
yes uranium plate from immersive engineering is neither showing up in JEI

**Comment by InsufferableStudent** [comment]
Vanilla rockets also don't show up

**Comment by NillerMedDild** [comment]
I only managed to fix Uranium Plate, I have no control over the rest as far as I can tell :/
