### ISSUE TITLE
Morphing Tool Additions

### ISSUE THREAD

**Issue by Stamparas** [NillerMedDild/Enigmatica2Expert#1803]
**Modpack version**
1.81a

**Suggestion**
add tools: Immersive Engineering (Hammer and Wire cutter), Storage Drawers (Keys), Astral Sorcery (Resonating Wand), Chisels (Chisel), AE2 Stuff (Wireless Setup Kit), Forestry (Scoop) (or the one from Gendustry)

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by NillerMedDild** [comment]
Sure to some of these :)
