### ISSUE TITLE
Can't craft creative fluid tank

### ISSUE THREAD

**Issue by KleinGrrmpf** [NillerMedDild/Enigmatica2Expert#1806]
**Modpack version**
1.81a
**Issue**
I can't craft the creative fluid tank. All the items are in the right place, but JEI tells me that the tanks are missing/incorrect.
I have all the right fluids in the tanks, but it won't let me craft it. I suspect that the NBT of the tanks is not matching with the NBT of the tanks in the recipe. The tanks in the recipe only have the following NBT:
`{Fluid:{FluidName:"ic2uu_matter",Amount:32000}}`
The tank that I want to craft the creative tank with has the following NBT:
`{RSControl:0b,Creative:0b,Fluid:{FluidName:"ic2uu_matter",Amount:32000},Level:0b,Lock:0b}`

The `{Fluid:{}}` part is the same, it just has extra NBT, and that is probably the problem. You can't even get the tank withouth the RSControl or Level tag, because it already has it when you craft it. 

I guess the recipe checks if the tank has EXACTLY that NBT and not if it has the required NBT plus some extra NBT.

**Logs**
-
![2020-08-29_21 21 09](https://user-images.githubusercontent.com/50833808/91644572-9613b500-ea3d-11ea-89fc-e32b6ae5117e.png)
![2020-08-29_21 12 02](https://user-images.githubusercontent.com/50833808/91644573-9744e200-ea3d-11ea-8191-640754f649d2.png)
![2020-08-29_21 12 07](https://user-images.githubusercontent.com/50833808/91644574-98760f00-ea3d-11ea-94c9-523a0df1e9ee.png)
![2020-08-29_21 21 02](https://user-images.githubusercontent.com/50833808/91644576-990ea580-ea3d-11ea-929f-4897f19fb9e4.png)

**Comment by NillerMedDild** [comment]
Seems awfully similar to #1589 
The recipe disregards the extra tags on the tanks.

Please double check that all buckets/tanks are placed correctly, and I'll of course investigate if that doesn't fix it :)

**Comment by KleinGrrmpf** [comment]
Ok, sorry to bother you...
I thought that JEI would tell me if the buckets were in the incorrect locations, too... I switched Ender and Essence in the bottom left corner. So the recipe totally works, JEI just doesn't accept the tanks, but the recipe itself does.
Sorry again...

**Comment by NillerMedDild** [comment]
No problem at all :)
