### ISSUE TITLE
RFTools Spawner Blue Slime Config Incorrect

### ISSUE THREAD

**Issue by KarateMan** [NillerMedDild/Enigmatica2Expert#1808]
**Modpack version**
1.81a

**Issue**
It is currently impossible to spawn a Blue Slime with the RFTools Spawner because the Blue Slimeball value in the config is incorrect.

Due to the value being incorrect the Spawner requires two sets of living matter, and it is impossible to fill the second one.
I did try to put Blue Slimeballs in anyways just to be sure and it did not take them.

Screenshot of Spawner: https://gyazo.com/23f8aace5b332a47ac350c53b370934d
Screenshot of Applicable Config Lines: https://gyazo.com/7908b1f1a0bbe20affe9b206ab1f8645

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
Changed to vanilla slime balls, not sure how to specify nbt in that config ^^'
