### ISSUE TITLE
Blacklist Unobtainable Foods from Spice of Life: Carrot Edition

### ISSUE THREAD

**Issue by KleinGrrmpf** [NillerMedDild/Enigmatica2Expert#1811]
Modpack version
1.81a

Issue
In order to get all the hearts, you also need to eat the Doughnut from Actually Additions. This item is unobtainable in survival minecraft, as it says in the wiki page. So I would suggest removing it.

https://ftb.gamepedia.com/Doughnut

**Comment by NillerMedDild** [comment]
You suggest removing the doughtnut? As in hide it from JEI? :)

**Comment by KleinGrrmpf** [comment]
Yes. If that fixes the issue that it is required to eat to get all the hearts. If it doesn't, then that's just bad luck. But I guess there is sth like a food blacklist to add foods that don't have to be eaten in order to get more hearts

**Comment by NillerMedDild** [comment]
There is no list of required foods, it's just a number to reach. I cannot remove the doughnut item, I would need a specific config to do that.

**Comment by NillerMedDild** [comment]
Wait, are you saying there are 1699 obtainable food items in E2E? :P

**Comment by KleinGrrmpf** [comment]
Just looked through the spice of life config and there is a section called "Food Blacklist"

**Comment by KleinGrrmpf** [comment]
> 
> 
> Wait, are you saying there are 1699 obtainable food items in E2E? :P

Why?

**Comment by KleinGrrmpf** [comment]
No, actually, I think it is way less... Like sth around 1500 or sth

**Comment by NillerMedDild** [comment]
Thought so :P Err sure I could do that.

**Comment by KleinGrrmpf** [comment]
It's actually 1246 foods in total according to the book. 2 of them are not nourishing enough to count towards adding hearts.

The pink slimeballs from Tinkers' construct are unobtainable as well. You can't change other slimeballs to these in the forge lexicon and for the Ore Dictionary Converter by Industrial Foregoing, you need one of them first to be able to convert others.

The pink slimeball has the id:
tconstruct:edible
and the metadata 5

**Comment by NillerMedDild** [comment]
Reminder for self: Foods are:
- AA Doughnut
- Tinkers Pink Slimeball

**Comment by KleinGrrmpf** [comment]
The Blood Apple from Animus also has no recipe and despite looking through Google I did not find any way to get it. I think it is just not yet implemented...
