### ISSUE TITLE
Can't make Tinkers' Complement Milk Chocolate Ingot

### ISSUE THREAD

**Issue by KleinGrrmpf** [NillerMedDild/Enigmatica2Expert#1812]
**Modpack version**
1.81a

**Issue**
When you want to make the milk chocolate ingot from Tinkers' Complement (which you can only make in the smeltery) you always get the Milk Chocolate item from Nuclearcraft. They both use the same recipe (Molten Milk Chocolate and Ingot Cast).
I suggest removing the Nuclearcraft Milk Chocolate recipe since you can still get that item in the Ingot Former.
![2020-09-04_18 56 57](https://user-images.githubusercontent.com/50833808/92266975-6c94d680-eee0-11ea-8d27-fcaf8f4627bd.png)
![2020-09-04_18 56 44](https://user-images.githubusercontent.com/50833808/92266976-6e5e9a00-eee0-11ea-9e57-34ae60ab43dd.png)

 

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
I've decided not to take this issue any further, as most modders no longer work on Minecraft 1.12, and development of Enigmatica is focused on Minecraft 1.15+ - I hope that's understandable :)
Thank you for helping to make E2E polished by reporting, I hope to see you in E5+!
