### ISSUE TITLE
Cyclic Exchanger Bug

### ISSUE THREAD

**Issue by EasilyItalian** [NillerMedDild/Enigmatica2Expert#1813]
**Modpack version**
1.72b
**Issue**
Cyclic exchanger messed up my whole inventory and can't place blocks
**Logs**
These were all the files that I could put in here. I have a video of what happened after I used the exchanger and another log which is too big for GitHub
[options.txt](https://github.com/NillerMedDild/Enigmatica2Expert/files/5185299/options.txt)
[latest.log](https://github.com/NillerMedDild/Enigmatica2Expert/files/5185300/latest.log)
[launcher_log.txt](https://github.com/NillerMedDild/Enigmatica2Expert/files/5185294/launcher_log.txt)

**Comment by NillerMedDild** [comment]
You're many versions behind, please update and see you if that fixes the issue.

**Comment by EasilyItalian** [comment]
I currently can't/don't know how to update because I forgot to enable cheats on the world before I started. I reported the bug because I didn't really see much in the patch notes about cyclic (unless I missed something).

**Comment by NillerMedDild** [comment]
You don't need cheats enabled to update :) Cyclic has had many mod updates in the updates you've missed, I'm pretty sure this particular bug has been fixed.
