### ISSUE TITLE
Astral Sorcery rituals stop working after server restarts

### ISSUE THREAD

**Issue by KrAzYGEEK32** [NillerMedDild/Enigmatica2Expert#1815]
**Modpack version**
1.81a

**Issue**
im on the official E2E-a server, and whenever server does a restart, all my astral rituals stop working till i break and replace the pedestal, dont know if this is a bug or intentional, reporting this just to confirm

**Logs**
N/A

**Comment by NillerMedDild** [comment]
Thanks for the report. Do your structures have anything other than the structure blocks in them?

**Comment by KrAzYGEEK32** [comment]
not afaik, i have 3 rituals running and 2 of them are boosted with lenses, other than that there are no other blocks

**Comment by NillerMedDild** [comment]
Could be related to this old issue: https://github.com/HellFirePvP/AstralSorcery/issues/1070
Would you mind reading through it, and see if there's an explaination that fits your issue? :)

**Comment by KrAzYGEEK32** [comment]
Hmm, I've gone through the thread and seem like the person above your mention seems to have a similar issue, guess we have to wait for a dev reply

**Comment by NillerMedDild** [comment]
I do not believe I can fix this, and the majority of modders no longer support 1.12, so I'll close this issue.

Nethertheless, thank you for reporting :)
