### ISSUE TITLE
Iron sharpening kit not working

### ISSUE THREAD

**Issue by Fedelisk** [NillerMedDild/Enigmatica2Expert#1816]
**Modpack version**
E2E 1.81a

**Issue**
Using iron sharpening kit does not increase mining level on quartz head pickaxe.

**Logs**
(https://cdn.discordapp.com/attachments/396040299165777921/753976441602834473/unknown.png)
(https://cdn.discordapp.com/attachments/396040299165777921/753975670765387786/unknown.png)
(https://cdn.discordapp.com/attachments/396040299165777921/753976992206159936/20200911_155501.jpg)

**Comment by NillerMedDild** [comment]
Sorry for the long wait, I missed the issue :/ Does the pickaxe have a diamond applied?

**Comment by Fedelisk** [comment]
Yes it does have diamond applied.

**Comment by NillerMedDild** [comment]
That is the cause I'm afraid, can't remember how the diamond modifier messes it up exactly though ^^'
