### ISSUE TITLE
Unable to locate JRE matching 1.8+

### ISSUE THREAD

**Issue by TK-4217** [NillerMedDild/Enigmatica2Expert#1817]
**Modpack version**
I don't know

**Issue**
I can't solve this, I've tried everything. when my friend tries to launch enigmatica 2 expert, it gives this error. it is also stuck on the jar launcher.

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by NillerMedDild** [comment]
He most likely has Java 32-bit installed, he needs 64-bit :)

Follow these steps to update.

https://www.java.com/en/download/manual.jsp Windows Offline (64-bit) is the one you need
