### ISSUE TITLE
Mekanism Dynamic Tank not holding fluid between log-ins

### ISSUE THREAD

**Issue by EasilyItalian** [NillerMedDild/Enigmatica2Expert#1818]
**Modpack version**
1.81a

**Issue**
Mekanism Dynamic Tank not keeping the amount of NuclearCraft Tritium between saving world and going back into the world. I tried to see if this would happen on a creative test world but the tank seems to work fine. My current setup in my main world is Ender IO fluid conduits taking fluid from an ender tank that takes the fluid from my NuclearCraft fusion reactor. Every time I log back in though my ender tank is empty and so is my Mekanism dynamic tank which is in a 3x3 formation. 

**Logs**
N/A

**Comment by NillerMedDild** [comment]
Thanks for the report. Could you please remove all in and outputs from the Dynamic Tank, relog and see if the issue persists?

**Comment by EasilyItalian** [comment]
When I removed the Ender IO Ender fluid conduit all the fluid in the tank disappears. It even happens with Deuterium which I have in another fluid tank next to the one that is deleting the fluids.

**Comment by NillerMedDild** [comment]
O_O well that's alarming. I'll see if I can reproduce it.

**Comment by EasilyItalian** [comment]
I can send you a video of it happening as in the begging I thought it was only Tritium but my Deuterium tank next to it is working fine and exported some to the buggy tank when I connected it back. When I disconnected it, it deleted all the fluid inside.  Could there also be someplace where it could dump an error that could be in the background as I want to see if rebuilding the tank will fix it, and don't want to break it if a code is popping up somewhere.

**Comment by NillerMedDild** [comment]
If it logs the error, it would be in the `latest.log` found in your logs folder :)

**Comment by EasilyItalian** [comment]
I just checked the logs and only server saving stuff. I can send you a screenshot of my setup so you can try to reproduce it as you said you didn't need a video.

**Comment by NillerMedDild** [comment]
Sure that'd be nice :)

**Comment by EasilyItalian** [comment]
![2020-09-16_21 52 32](https://user-images.githubusercontent.com/70922508/93385824-0c4e4f00-f867-11ea-87c3-ef9daed8d7c0.png)
I can give more detailed screenshots but thought this was fine.

**Comment by EasilyItalian** [comment]
So the more that I've been playing with the bug, I've found out that if you log out it shows all the fluid is gone but you can reset it by breaking 1 block in the multi block and it'll bring it back to the original value and liquid that was there before you logged out. This can only be done by manually doing it. If you log out and didn't reset the multi block it will default to the new value if you reset the multi block again. 

I don't know if this info will directly help you but it's had been what I've been finding out while I've been playing.

**Comment by EasilyItalian** [comment]
Could this be some odd incompatibility between the 4 mods that I have in my setup? (NuclearCraft, Mekanism, Ender IO, and EnderStorage) Because another bug that I have now come upon is that my Ender IO conduits that are connected to my fusion reactor for some reason need to be updated to transport fluid again between logins. To update it I click the settings of the side that is extracting and click the redstone mode button which is already on always active, then click it to another setting and put it back to always active. 
![2020-09-17_16 19 12](https://user-images.githubusercontent.com/70922508/93483873-964af600-f901-11ea-8a15-c89176191070.png)

**Comment by NillerMedDild** [comment]
Yes absolutely.

**Comment by EasilyItalian** [comment]
Should I try to recreate this in a new creative world, or are you doing that?

**Comment by NillerMedDild** [comment]
To be honest, even if we do pinpoint the cause of this issue, I doubt it will be fixed. The vast majority of developers have moved on from 1.12.2

**Comment by EasilyItalian** [comment]
Should we close this then, or leave it open to allow other people to see this just in case they have the same problem?

**Comment by NillerMedDild** [comment]
I think we should close it, if that's alright with you, it's my hope that people looking here also check closed issues :)

**Comment by EasilyItalian** [comment]
Ok then, thanks for the help
