### ISSUE TITLE
Kinetic dynamo does not produce power

### ISSUE THREAD

**Issue by KTheRD** [NillerMedDild/Enigmatica2Expert#1819]
**Modpack version**
1.81a

**Issue**
Kinetic dynamo does not produce energy, though wheels are spinning. I tried to place connector on every side, I tried to use fluxducts, still nothing happens.

![2020-09-20_14 14 13](https://user-images.githubusercontent.com/41128086/93708808-b1607480-fb52-11ea-96f5-a20039fc2507.png)

**Comment by Discomanco** [comment]
IIRC, the wheels also have to turn the correct way. Try break the wheels and place them against the Dynamo (and then replace the water

**Comment by KTheRD** [comment]
Thanks, now it works. Didn't know that wheel orientation matters.
