### ISSUE TITLE
"Item Placeholder" is a loot chest reward

### ISSUE THREAD

**Issue by BlueTRaven** [NillerMedDild/Enigmatica2Expert#182]
#### Issue Description
As title states, an "Item Placeholder" with the item id "scalinghealth:heartcontainer/0" (which I think is an item from a mod that was removed in a recent version) can be found in Loot chests.
[Tooltip screenshot](https://imgur.com/MpdjChh)

#### Modpack version (Do not use "latest")
1.33

**Comment by NillerMedDild** [comment]
Update to 1.34 and use the command `/bqs_loot default load`
