### ISSUE TITLE
Creative Powercell uncraftable again?

### ISSUE THREAD

**Issue by adamsonich** [NillerMedDild/Enigmatica2Expert#1820]
Fresh installation of 1.81a in separated instance

part 1:
Crafting energy cell basic. place in world. upgrade with "resonant convertion kit". dig it.
use "/mt nbt" to recive this:
{Recv: 250000, RSControl: 0 as byte, Facing: 3 as byte, Creative: 0 as byte, Energy: 0, **Level: 4 as byte**, SideCache: [2, 1, 1, 1, 1, 1] as byte[] as byte[], Send: 250000}

part 2: 
Open "Creative.zs" ver 1.72, find string "var resonantCube = <thermalexpansion:cell>.withTag({Level: 4 as byte});"
Open "Creative.zs" ver 1.81a (from separated inst), find string "var resonantCube = <thermalexpansion:cell>.withTag({Level: 4 as byte});"

Wtf?

**Comment by adamsonich** [comment]
> Note the difference between withTag and onlyWithTag. withTag is for an output and is the exact tag that will be output. onlyWithTag is for input and sets a condition. Applying withTag on an input has no effect on the recipe.
http://minetweaker3.powerofbytes.com/wiki/Tutorial:Advanced_Recipes

**Comment by NillerMedDild** [comment]
WithTag specifies which tag the item must have, it disregards all others. Are you certain you cannot craft the item? JEI plus might not work, but the recipe should.

**Comment by adamsonich** [comment]
https://prnt.sc/upfmmv
https://prnt.sc/upfmz6

**Comment by NillerMedDild** [comment]
Works just fine for me, something is wrong in your inputs, I can't spot the issue though :)
