### ISSUE TITLE
ModularMachinery Power Bug / Can't complete production recipe

### ISSUE THREAD

**Issue by Ghost942** [NillerMedDild/Enigmatica2Expert#1821]
**Modpack version**
1.81a

**Issue**
Built Modular Machinery - Adv. Metallurgical Fabricator
Have MM run on base power (E.Tech solar)
Find Machine runs once or twice before draining power without completing recipe
Build NC reactor for sole power gen
Use Thermal Cryo-Flux for power transfer with Mekanism Ultimate Power Cube as buffer
Find Machine replicates issue
Search web, result: break and replace energy input hatch
Do break/replace, but with building new energy hatch
Problem persists
Have not rebuilt MM in new chunk (yet) due to chlorine production setup

**Logs**
No log, but video: https://rb.gy/bg2nwg (Dropbox link)

**Comment by NillerMedDild** [comment]
Thanks for the report. Are you supplying the amount of rf/t that the recipe requires? Which recipe is it? :)

**Comment by Ghost942** [comment]
Recipe is for production of Titanium, requiring 100K RF/t. Running the NC reactor with HECF-239 should produce the best amount of RF/t.

I'll try running it without the buffer when I get the chance, but to me, it looks like a bug with the energy hatch

**Comment by NillerMedDild** [comment]
That it does, but it seems to work for others. Which hatch are you using? May I have a screenshot of the controller while it's running?

**Comment by Ghost942** [comment]
Hatch is the Normal Energy Input Hatch

If viewing the Dropbox link to the video, one can see the process in action, including the power drain. Please let me know if the link is invalid.

**Comment by NillerMedDild** [comment]
Oh I'm sorry, forgot about the video, my bad.

**Comment by NillerMedDild** [comment]
So I watched the video, *(as I should have a long time ago)*, and you are not feeding it enough RF/t. It requires 100.000 rf/t - Let the reactor build up an energy buffer and feed it that :)

**Comment by Ghost942** [comment]
I hate being a necro, but I tried this again with a different recipe: https://rb.gy/uz4hgv (Another dropbox video link)
Hope this shows more than I did before

**Comment by NillerMedDild** [comment]
Hm. What about putting a fully charged Mekanism Ultimate Energy Cube next to the energy input? Did you craft the energy input?

**Comment by Ghost942** [comment]
Energy cube next to Input Hatch has been tested off-screen, same results of drain without filling hatch. Energy Hatch was crafted once, trashed to hope solve problem, then crafted second hatch which is the current one

**Comment by NillerMedDild** [comment]
Alright, thank you, I'll try to reproduce it again :)

**Comment by NillerMedDild** [comment]
The issue is that the Ultimate Energy Cube doesn't output 100krf/t, not even close :) use another buffer.
