### ISSUE TITLE
[Mod Suggestion] Integrated NBT

### ISSUE THREAD

**Issue by KrAzYGEEK32** [NillerMedDild/Enigmatica2Expert#1822]
**Issue**
I know mod suggestion are taken with grain of salt for feature complete packs, but this one is a complete QOL add-on for integrated dynamics. Which, ID nerds ( like me) would appreciate a lot. Hope you consider it :)
https://www.curseforge.com/minecraft/mc-mods/integrated-nbt

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by NillerMedDild** [comment]
Thanks for the suggestion, I will add it given how useful and small the mod is :)
