### ISSUE TITLE
Quest idea for all/any of the modpacks

### ISSUE THREAD

**Issue by Kuktar** [NillerMedDild/Enigmatica2Expert#1823]
**Modpack version**
1.84a

**Issue**
enhancement 

Not sure were to suggest this but since i am playing enigmatica 2 expert i chose here.

When doing the IC2 or Nuclearcraft questline please add a quest for the hazmat suites. You could put it right before the plutonium quest or even before the reactor quest. Just an idea because i after years of playing around with nuke reactors just realized there is a way to prevent radiation lol

**Comment by NillerMedDild** [comment]
Thanks for the suggestion, we'll think about it :)
@Frikkle would you consider adding this in the refactor?

**Comment by NillerMedDild** [comment]
I don't have time to implement this I'm afraid, sorry.
