### ISSUE TITLE
An idea

### ISSUE THREAD

**Issue by Nabbieshtron** [NillerMedDild/Enigmatica2Expert#1824]
I just have a question we have so many powerfull swords in game why dont modify enemys healt and damage and dont add maybe few new monsters? I want to be like when i see monster AH SHIT ITS HIM AGAIN. ;D

**Comment by NillerMedDild** [comment]
E2E did modify health and damage of mobs in the past, but it was wildly unpopular. We have added a ton of new monsters, case and point Ice & Fire :P
