### ISSUE TITLE
ERROR: Could not find valid java version installed.

### ISSUE THREAD

**Issue by ZygZagGaming** [NillerMedDild/Enigmatica2Expert#1825]
**Modpack version**
1.81a

**Issue**
When I run the ServerStart.bat file, it shows this error:

ERROR: Could not find valid java version installed.
64-bit Java ver 1.8+ is highly recomended. Check here for latest downloads:
https://java.com/en/download/manual.jsp

**** ERROR ****
There was an Error, Code: ""JavaVersionOrPathError""

**Logs**
[serverstart.log](https://github.com/NillerMedDild/Enigmatica2Expert/files/5324302/serverstart.log)

**Comment by NillerMedDild** [comment]
What is the issue, are the instructions unclear? :)

**Comment by ZygZagGaming** [comment]
I can't run the ServerStart.bat file, it instead shows the error above,

**Comment by NillerMedDild** [comment]
It's saying you need to install Java.
https://www.java.com/en/download/manual.jsp Windows Offline (64-bit) is the one you need
