### ISSUE TITLE
Thermal duct covers crash

### ISSUE THREAD

**Issue by twapenaar** [NillerMedDild/Enigmatica2Expert#1826]
**Modpack version**
1.81a

**Issue**
I created some Thermal duct covers to hide my cables. But when I try to place them or get near my cables I crash.
If I want to go back to my world I need to spam `ctrl + q` in order to drop the covers before it can crash again.

I already places my crash report in #support on the discord server in the name of Wuppy

I wanted to place a grass block cover here (if this helps)
https://imgur.com/a/151SSRL

**Logs**
https://pastebin.com/QC2rcyyS

**Comment by NillerMedDild** [comment]
Thanks for the report - I'm pretty sure this issue is caused by Optifine, could you try removing it and see if it persists please? :)

**Comment by twapenaar** [comment]
It was indeed Optifine, unfortunately. So I'll be keeping that out from now on. Thanks for the help and keep up the good work

**Comment by NillerMedDild** [comment]
My pleasure :)
