### ISSUE TITLE
Items in inventory shift upwards upon key press and release.

### ISSUE THREAD

**Issue by DonaldDuckITH** [NillerMedDild/Enigmatica2Expert#1827]
**Modpack version**
1.81a

**Issue**
Whenever I press any key in the inventory, everything shifts upwards by one row. The same happens upon release of the key.

**Comment by EternisField** [comment]
You need to bind some None buttons (machine translation

**Comment by NillerMedDild** [comment]
Either delete the `options.txt` file in your instance, or bind the Cyclic move inventory up/down buttons to some keys that are not media keys, both should fix it. Please let us know if it doesn't :)
