### ISSUE TITLE
actually additions empower empowers items without power

### ISSUE THREAD

**Issue by lp2257** [NillerMedDild/Enigmatica2Expert#183]
enigmatica 2 expert: Bug actually additions empower empowers items without power

**Comment by NillerMedDild** [comment]
Don't delete the issue template.
Which modpack version?

**Comment by lp2257** [comment]
The latest version

**Comment by NillerMedDild** [comment]
The issue template (that you deleted) specifically says that you should not say "latest" version.

Which modpack version?

**Comment by lp2257** [comment]
enigmatica 2 expert 1.34

**Comment by NillerMedDild** [comment]
Thank you <3

**Comment by NillerMedDild** [comment]
I cannot reproduce this. Which item are you making?

**Comment by lp2257** [comment]
For all item no power required

**Comment by NillerMedDild** [comment]
Are you aware that the Display Stands use the power?
