### ISSUE TITLE
Illegal minecraft recipe

### ISSUE THREAD

**Issue by Derpatron111** [NillerMedDild/Enigmatica2Expert#1830]
Sky factory for servers (4.2.2)

[Client thread/FATAL]: Error executing task java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Recipe minecraft:wooden_door (net.minecraft.item.crafting.ShapedRecipes@2552181d) produces unregistered item minecraft:wooden_door (net.minecraft.item.ItemBlock@50d05167)

does not let me join into the server but I can still run it.

[Logs]    https://pastebin.com/kjHWyQ7q
(Ps: all my other servers have this issue)

**Comment by NillerMedDild** [comment]
This is the issue tracker for Enigmatica 2: Expert, not SkyFactory. However, that issue is almost always caused by files on client and server not matching. Make sure you have the correct version of the modpack on server and client, and that the scripts and resources folders match.

**Comment by Derpatron111** [comment]
i have extra mods in my .minecraft mods folder that are not in the server's mod folder. Is that what you mean?

**Comment by NillerMedDild** [comment]
That could also be an issue, yep.

**Comment by Derpatron111** [comment]
I have trying to find the problem for the issue which is continuing. I have not been sucsessful in fixing the problem.

**Comment by NillerMedDild** [comment]
Please go here for support: https://github.com/DarkPacks/SkyFactory-4
I am in no way affiliated with SkyFactory :)

**Comment by Derpatron111** [comment]
Thanks!
