### ISSUE TITLE
Observers not working as normal

### ISSUE THREAD

**Issue by kyngs** [NillerMedDild/Enigmatica2Expert#1831]
**Modpack version**
Enigmatica 2: Expert

**Issue**
When you push observer by piston, the observer does not send the redstone signal.

**Logs**
https://pastebin.com/QbdqFyDt

**Comment by NillerMedDild** [comment]
Enigmatica 2: Expert is not the version of the modpack :)
I'll have a look though.

**Comment by kyngs** [comment]
Sorry, how do I get what version I use?

**Comment by NillerMedDild** [comment]
I can't reproduce this issue, could you send a screenshot of the setup, or describe your environment in further details please?

**Comment by kyngs** [comment]
https://imgur.com/a/pHKzmUd
Here is the issue I meant, observer should activate when moved. As you may see in footage it does not.

**Comment by NillerMedDild** [comment]
Looks like it could be a visual glitch, please try placing some redstone dust in front of it to see if that lights up. The same thing worked for me, albeit with a non-sticky Piston and the Observer facing away from the Piston.
