### ISSUE TITLE
Fluid Duplication with AE Fluid Terminal

### ISSUE THREAD

**Issue by Gabbleducky** [NillerMedDild/Enigmatica2Expert#1832]
**Modpack version**
1.81a

**Issue**
When extracting fluids from an Applied Energistics Fluid Terminal using a Thermal Expansion Resonant Tank, fluids stored in a 64k fluid storage cell duplicate themselves. I used a Portable Tank (Resonant) to remove 208 buckets of Thermal Foundation Sap from my system. I then hovered over the tank and the tooltip said the tank contained 376 buckets. I repeated the experiment with Lava, going from 13 buckets to 109.8 buckets and (off camera) Liquefacted Coal, going from 34.6 buckets to 202.6 buckets.

This bug also effects fluids stored in external containers with storage buckets such as Mekanism Tanks and Extra Utilities Drums, turning 56 buckets of milk into 232 buckets

The video link is here: https://youtu.be/mTuJw8wV0cU

If you want me to provide any logs or a more detailed view of my setup please let me know

**Comment by NillerMedDild** [comment]
Thank you for an excellent bug report. 
In order to report this issue to AE's issue tracker I will need a forced crash report (you make one by pressing F3+c for 10 seconds)
would you mind supplying that? :)

**Comment by Gabbleducky** [comment]
Happy to help!

The crash report is here https://pastebin.com/V2DKLuBt

It's on my singleplayer world

**Comment by NillerMedDild** [comment]
Awesome, thanks, I relayed it to the AE team.

Side note: I can see in your log that your game is using outdated Java, you could boost performance (and fix quite a few bugs) by updating. Here's a small guide on how you update: https://gist.github.com/NillerMedDild/40b4992b7a3e5e653a353fe1d45f2185#set-twitch-to-use-most-recent-java-8

**Comment by NillerMedDild** [comment]
And this was the AE team's response:
> 
> 
> We no longer support any minecraft version older than 1.15 at this point.
> 
> Should you be able to confirm that this issue still applies to the most recent version, please update the issue and we will reopen it.

Sorry, nothing more we can do :(

**Comment by Gabbleducky** [comment]
Okay, thanks for looking into it and letting me know. If they're not fixing it I'll just have to behave myself!

I'm updating my java now, I'll see if that fixes the issue
