### ISSUE TITLE
Smokey Quartz Block and Black Quartz Block Recipe Conflict

### ISSUE THREAD

**Issue by fabrossmann** [NillerMedDild/Enigmatica2Expert#1834]
**Modpack version**
1.81a

**Issue**
Smokey Quartz Block (Botania) and  Black Quartz Block (Thaumic Tinkerer) have a recipe conflict. The Problem with this is, that if you want to make an Osmotic Enchanter Multiblock, you need the block by Thaumic Tinkerer or else it will fail. If you just craft it in the crafting table, it will be the Botania one.
![image](https://user-images.githubusercontent.com/6189957/95984671-d67b9680-0e23-11eb-9068-ba9aed7a8652.png)

**Comment by NillerMedDild** [comment]
Thanks for letting me know, I'll get that fixed :) In the meantime, you can use a crafting station from Forestry to choose between the output blocks, can't remember the exact name of it though.
