### ISSUE TITLE
Advanced Rocketry Electrolyser

### ISSUE THREAD

**Issue by coetyler** [NillerMedDild/Enigmatica2Expert#1836]
**Modpack version**
Version 1.82

**Issue**
In the newest update the advanced rocketry electrolyser no longer makes oxygen from water not sure if this was intended or not since the previous version of the modpack it did

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by NillerMedDild** [comment]
Hmm, are you sure? Cause the power requirement has gone waaay up on that recipe :)

**Comment by coetyler** [comment]
yeah i was just testing out the new version before updating my server and when i loaded my server world in single player it makes hydrogen and deuterium but not oxygen

**Comment by NillerMedDild** [comment]
ahh I see the culprit, yup that's a bug, thanks for the report :)

**Comment by coetyler** [comment]
also is the electric arc furnace from advanced rocketry supposed to still be make the vulpes steel ingot, i know i opened this bug about the electrolyser but i wanted to double check

**Comment by NillerMedDild** [comment]
Temporary workaround: Make sure it always has under 1000mb of water and it'll produce oxygen + hydrogen

**Comment by NillerMedDild** [comment]
> 
> 
> also is the electric arc furnace from advanced rocketry supposed to still be make the vulpes steel ingot, i know i opened this bug about the electrolyser but i wanted to double check

No it is supposed to make Thermal Foundation Steel, does it not?

**Comment by coetyler** [comment]
never mind it is working, i just had to double check, so its one ingot now instead of the two that the vulpes recipe was correct?

**Comment by NillerMedDild** [comment]
Yup :)

**Comment by Krutoy242** [comment]
My bad 😬

**Comment by john13210** [comment]
What do you mean its fixed in next release im playing 1.82a and its still outputing 50 deuterium and machine needs1000mb of water to work

**Comment by theboo** [comment]
Fixed in next release means the fix is not in a release yet... If it was in a release this issue would be closed :)

**Comment by john13210** [comment]
Real Temporary workaround: you can put liquid oxygen in gas charge pad

**Comment by john13210** [comment]
theboo he said that in 1.82 next release is 1.82a and im playing on it

**Comment by theboo** [comment]
Fixed in next release tag was added on march 7 of this year, 1.82a was released October 14th of last year 😃

**Comment by john13210** [comment]
sorry didnt think this version was this old
