### ISSUE TITLE
All textures disappeared?

### ISSUE THREAD

**Issue by CornOnTheJayCob** [NillerMedDild/Enigmatica2Expert#1837]
1.82a

I don't know what caused this, so I don't think this will be all that useful, but I'll submit this report anyway. Almost all the textures in the game just disappeared, both in the world and in the inventory. This persisted between logging out and back into a world, and continued to happen when I joined a different world. The only way I got it to stop was completely closing E2E and starting it up again. It's kind of hard to explain what happened, so [here's a clip of it](https://streamable.com/2ylkik).

Also, I'm not sure where would be a good place to ask so I'll just ask here, do you plan on adding deep mob learning to the pack?

**Comment by NillerMedDild** [comment]
Hmm, I think you should investigate if your GPU is alright :P I doubt it's pack related tbh.

Nope that's not planned.
