### ISSUE TITLE
Cannot remove enchantments from Wyvern Armor

### ISSUE THREAD

**Issue by Gabbleducky** [NillerMedDild/Enigmatica2Expert#1839]
**Modpack version**
1.8.2

**Issue**
Cannot use IF Enchantment Extractor to remove enchantments from Wyvern or Draconic Armor

I am about to craft the Draconic Armor and wanted to remove the enchantments from my Wyvern Armor before crafting. I have an Industrial Foregoing Enchantment Extractor with power and a stack of books but it won't let me even put the Wyvern gear into the machine. I tried using a hopper but that didn't work either.

**Logs**

https://pastebin.com/1TpNAz1g

**Comment by MorganSimic** [comment]
The Enchantment extractor just doesn't accept some items for some reason. I'm 99% sure we can do nothing about that. You might try the unenchanting pylon from cylic, wich is way more involved but i had great succes with MA tools, wich share the same issue.

**Comment by NillerMedDild** [comment]
In any case, I don't think IF is getting any more non-critical updates on 1.12 :/
