### ISSUE TITLE
Trying to craft diamond nuggets from Thermal gives only extra bit manipulation nugget

### ISSUE THREAD

**Issue by memyselfandcj** [NillerMedDild/Enigmatica2Expert#1842]
**Modpack version**
1.82a

**Issue**
Trying to craft Microchip tier 3..recipe uses diamond nuggets from thermal when trying to craft recipe only gives diamond nuggets from extra bit man...
![2020-10-30_20 57 38](https://user-images.githubusercontent.com/40968814/97767534-0351ce00-1af3-11eb-843a-24dd1d2f9ce4.png)

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by kpopoh** [comment]
if another mod has the same recipe, try using the NoMoreRecipeConflict mod by stimmedcow. It allows you to cycle through items that use the same recipe

**Comment by NillerMedDild** [comment]
Have you checked if there are other ways of obtaining the Diamond Nuggets you need? Or does the recipe perhaps accept either?

**Comment by memyselfandcj** [comment]
I was able to tinkers smeltery to craft the nuggets so there is another way to get them.

**Comment by NillerMedDild** [comment]
They can be used interchangably, they've in the same ordicts :)
