### ISSUE TITLE
MC crashing when launching singleplayer world

### ISSUE THREAD

**Issue by kpopoh** [NillerMedDild/Enigmatica2Expert#1843]
**Modpack version**
using 1.12.2 a custom modpack

**Issue**
Im testing a modpack I put together to make sure everything works well together. But i cant even launch a single player world to test it. I managed to get past the forge loading screen with allowing more Ram, and currently using about 5GBs. I am using the twitch launcher to put together this modpack for me and my friends

Also this is my first time using this forum so hope I can get some help and if I'm in the wrong place I would kindly like to be pointed to the right directed for my problem
[crash-2020-10-31_02.52.58-client.txt](https://github.com/NillerMedDild/Enigmatica2Expert/files/5468626/crash-2020-10-31_02.52.58-client.txt)

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by NillerMedDild** [comment]
Hi there!

This isn't a forum, it is an issue tracker for the modpack Enigmatica 2: Expert. I suggest you ask for help in the Modded MC discord: https://discord.gg/moddedmc
