### ISSUE TITLE
Unable to gather dragon items

### ISSUE THREAD

**Issue by SilentSpectr514** [NillerMedDild/Enigmatica2Expert#1845]
**Modpack version**
1.82a

**Issue**
After killing a dragon, you can not gather the bones. The dragon just remains there showing hp 0. I have tried to log out and log back in to see if that would fix the issue but no. This prevents me, and possibly other users, from using some of the Ice and Fire mod. 

I've noticed this issue when I first started this playing this mod pack. I came across a dragon skeleton and could not mine for the bones. I have a attached a screenshot showing what I am talking about. 

![Runtime Screenshot 2020 11 04 - 10 09 04 32](https://user-images.githubusercontent.com/73952244/98128466-f8e25c00-1e85-11eb-8035-4d7bc3c30977.png)

**Comment by NillerMedDild** [comment]
Have you tried shift-right clicking it with an empty hand? :)

**Comment by SilentSpectr514** [comment]
That did it lol. Feel like an idiot now. Thank you for helping me with that

**Comment by NillerMedDild** [comment]
Sure thing :)
