### ISSUE TITLE
Nuclearcraft Infinite Water Source Recipe Bug

### ISSUE THREAD

**Issue by Luminosites** [NillerMedDild/Enigmatica2Expert#1847]
**Modpack version**
1.82a

**Issue**
Recipe bugs out randomly, either for no apparent reason or after crafting it once or twice, it doesn't recognize the water bucket, exiting to menu or /reload does nothing, restarting game fixes it sometimes, but the bug will happen again.

**Logs**
https://paste.ee/p/tsgBl 
Used this as pastebin has a limit

**Comment by NillerMedDild** [comment]
Thanks for the report, I'll see what I can do :)

**Comment by minecrafterseppe** [comment]
are u manualy crafting it or with an ae2 system
if with an ae2 system  the pattern u made the recipy could be set with 
"allow substition" wich would cause issues if u have multiple types of liqueds

**Comment by Meryl** [comment]
The recipe seems to hang on the water bucket crafting. It does this whether I craft the water bucket through Mystical Agriculture's water essence, or through a Fluid Transposer. The easiest way to temporarily fix this is to manual craft a few water buckets and then it seems to work as it's supposed to.

I think it might not actually be related to NuclearCraft's infinite water source, I think it's something to do with crafting water buckets that makes it stall and NC's infinite water sources just happen to be one of the most common crafting recipes with buckets of water in them.

**Comment by NillerMedDild** [comment]
I do not believe I can fix this, and the majority of modders no longer support 1.12, so I'll close this issue.

Nethertheless, thank you for reporting :)
