### ISSUE TITLE
Dank null for picking up items

### ISSUE THREAD

**Issue by Luminosites** [NillerMedDild/Enigmatica2Expert#1848]
**Modpack version**
1.82a

**Issue**
Dank null randomly ignores certain item after awhile, emptying it and putting stuff back in again works for some items, some of the items are cobblestone, flint and menril stone torch. Sorry if posting 2 issues separately is a spam, new to github.

**Logs**
https://paste.ee/p/tsgBl 
Used this as pastebin has a limit

**Comment by NillerMedDild** [comment]
Welcome to GitHub! Posting 2 seperate issues is considered good practice here :D

To be honest I doubt we can fix this, We're stuck on an older version of the mod because I'm scared newer versions will have more serious bugs.

**Comment by Luminosites** [comment]
Is an alpha/testing branch of E2:E with newer version of Dank null being considered? Since emptying an emerald dank null takes forever, not to mention the docking stationed being disabled due to bug(s).

**Comment by NillerMedDild** [comment]
Not really no, I've spent far too long troubleshooting that mod already.

**Comment by NillerMedDild** [comment]
The version of DankNull we're currently using is the most stable I have found, I will not risk updating :)
