### ISSUE TITLE
Sharpening kits do not increase pickaxe mining level.

### ISSUE THREAD

**Issue by staviq** [NillerMedDild/Enigmatica2Expert#1849]
**Modpack version**
1.82a

**Issue**

I thought its a weird glitch or something, but i managed to actually reproduce the problem:

Steps to reproduce ( does not matter if you craft required items or cheat them in with jei ):

1. craft tinkers paper pickaxe head, paper handle, paper binding, and make a pickaxe with it.
2. craft stone head.
3. replace the pickaxe head form paper to stone.
4. apply diamond modifier to the pickaxe.
5. craft copper sharpening kit.
6. apply the copper sharpening kit

7. you are stuck with copper reinforced tool that still has a flint mining level, and you cannot re-apply the sharpening kit.

If you replace the pick head with a flint one and then again with a stone one, suddenly mining level corrects itself, but it still breaks when you try to apply another mining level.

Here you can see certus sharpening kit, but the tool is stuck with copper mining level.

This is not a visual glitch, the tool actually refuses to mine level aproporiate ores.

https://i.imgur.com/7oWRBVy.png

**Comment by NillerMedDild** [comment]
I'm afraid that's a byproduct of how the diamond modifier "increases" the harvest level, it sets the value instead of just adding one. Not much we can do about it :(
