### ISSUE TITLE
RfTools Powercell + Crescent Hammer bug

### ISSUE THREAD

**Issue by atz513** [NillerMedDild/Enigmatica2Expert#185]
#### Issue Description
Whenever a player shift right clicks a powercell with the crescent hammer it deletes the cell every time.
#### Modpack version (Do not use "latest")
1.3.4
#### Crash Report

[pastebin/gist/etc link here]

**Comment by NillerMedDild** [comment]
Are you absolutely sure you're on 1.34?

**Comment by atz513** [comment]
100%. I recreated the bug as well.

**Comment by NillerMedDild** [comment]
Damnit :P

This isn't the first time that has happened, it was fixed though. May I have your latest.log please?

**Comment by NillerMedDild** [comment]
Sigh, confirmed...

**Comment by NillerMedDild** [comment]
It's a side effect of the mod that handles harvest levels, I'm afraid I don't see a way around it.
