### ISSUE TITLE
Intricate Circuit Board has replicator cost of 12.01 B UU

### ISSUE THREAD

**Issue by telemenar** [NillerMedDild/Enigmatica2Expert#1851]
**Modpack version**
1.82a

**Issue**
If you scan an Intricate Circuit Board into the Replicator it has a cost of 12.01 B UU Matter. 

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by NillerMedDild** [comment]
There are a ton of costs like that, the vast majority of Replicator recipes are automatically generated, and frankly silly :)
