### ISSUE TITLE
eating already eaten food resets one eaten food back to uneaten

### ISSUE THREAD

**Issue by minecrafterseppe** [NillerMedDild/Enigmatica2Expert#1852]
**Modpack version**
1.82a

**Issue**
not sure if this intended behaviour  or not.

but when u have eaten for example 10 different foods and u eat one of the types u already ate
it resets the status of one of the foods back to uneaten while NOT decrease eaten foods in the foodbook
this can be used to gain infinite hearts using only 2 different food types

**Comment by minecrafterseppe** [comment]
another note after some further testing is that it doesent happen all the time 
my guess it also resets un-eaten food back to un-eaten
thus then doing notning

**Comment by NillerMedDild** [comment]
Thanks for the report, I'll look into it.

**Comment by Signupsforeverything** [comment]
I can confirm. It happened on some foods.

**Comment by NillerMedDild** [comment]
I do not believe I can fix this, and the majority of modders no longer support 1.12, so I'll close this issue.

Nethertheless, thank you for reporting :)
