### ISSUE TITLE
Actually Additions Drill should have a higher mining level.

### ISSUE THREAD

**Issue by johnll56** [NillerMedDild/Enigmatica2Expert#1853]
**Modpack version**
Expert 1.82a

**Issue**
Currently, the drill from Actually Additions has a mining level of Lead(4) , yet it drops any block that it breaks, even those that are above its mining level, without being able to veinmine them and also imposing a mining speed penalty. Given that the drill is a midgame item, requiring empowererer automation for the upgrades and a constant supply of RF, I think that it would be beneficial to increase its mining level, making it useful in the lategame where you only use it to break specific blocks, not to go mining as that is already automated. To give a concrete example, I'm progressing through Enviro Tech tiers right now, and the structure blocks are of higher mining level than the drill, meaning that I can't veinmine them but can still break them one by one with the drill. I think increasing its mining level would therefore be a good QoL update and also reduce the need for a Tinkers pick. Unless that's the intended way to play, of course.

I've never posted an issue to Github before so I'm very sorry if this is not the right place or suggestions like this aren't welcome. Thanks for developing this great pack! Also I don't know how to add tags.

**Comment by NillerMedDild** [comment]
Welcome to GitHub, thanks for the report! :D

> I've never posted an issue to Github before so I'm very sorry if this is not the right place or suggestions like this aren't welcome. Thanks for developing this great pack! Also I don't know how to add tags.
- This is the right place
- Suggestions like this are welcome
- You're welcome :D
- You can't add tags yourself

The intended way to play is with a Tinkers pick tbh, but increasing the Drill tier a bit would make good sense, but I'll only set it to 7. It's intended that some of the later blocks require a pretty good Tinkers pick to mine.

That being said, I recommend using the Environmental Tech Assembler for breaking ET blocks, it's *very* efficient at it.

**Comment by johnll56** [comment]
Right. I was using the assembler to break the controller but hadn't thought of using it on the other blocks. Thanks!
Have a good day :)

**Comment by NillerMedDild** [comment]
No problem, you too :D

**Comment by NillerMedDild** [comment]
I was unable to implement this I'm afraid :(
