### ISSUE TITLE
AS marble bricks has conflicting chisel recipes

### ISSUE THREAD

**Issue by studkid** [NillerMedDild/Enigmatica2Expert#1854]
**Modpack version**
1.82a

**Issue**
Trying to chisel Astral Sorcery marble bricks only allows you to chisel it into Unlimited Chisel Works' marble variants.  Trying to use an iChisel (works with a normal chisel though) on any other marble block does not allow you to chisel into Astral Sorcery's marble bricks.  

It seems like UCW is adding an extra set of chisel recipes for marble and tying the original block to AS marble bricks only.  Checking the chisel recipes in JEI also shows these 2 different sets.

For reference, here's the chisel recipes for AS marble bricks:
<img width="445" alt="Screen Shot 2020-11-22 at 7 59 51 PM" src="https://user-images.githubusercontent.com/9309016/99923862-4b809c80-2cfd-11eb-9b53-cde5d5f5bc1b.png">

And here's the normal AS marble block chisel recipes:
<img width="455" alt="Screen Shot 2020-11-22 at 7 52 40 PM" src="https://user-images.githubusercontent.com/9309016/99923645-4a02a480-2cfc-11eb-80d5-341bf39096a3.png">

And here's some images using the normal chisel (since both show the same set of items):
<img width="502" alt="Screen Shot 2020-11-22 at 7 55 27 PM" src="https://user-images.githubusercontent.com/9309016/99923732-b8dffd80-2cfc-11eb-8a81-bc1e4c8734e1.png">
<img width="502" alt="Screen Shot 2020-11-22 at 7 56 06 PM" src="https://user-images.githubusercontent.com/9309016/99923746-c6958300-2cfc-11eb-9f5f-3a0813d1af52.png">

Also I didn't notice this until just now, but it looks like sooty marble bricks also has this same issue: 
<img width="445" alt="Screen Shot 2020-11-22 at 7 58 06 PM" src="https://user-images.githubusercontent.com/9309016/99923816-0eb4a580-2cfd-11eb-8046-9b46db5d2b87.png">

**Comment by ReiDaTecnologia** [comment]
The most annoying bug ever imo.

**Comment by NillerMedDild** [comment]
Thanks for the report, we'll see what we can do :)

**Comment by NillerMedDild** [comment]
I get that this is annoying, but tbh it's a fine way of getting around the issue of having too many chisel variants in the same group. I'll leave this bug in, as the alternative would be similar if not the same.

**Comment by ReiDaTecnologia** [comment]
Yep, it's a really sad and annoying bug. Alternatively you can disable the UCW's blocks or just cheat them and dump the base block like i do personally.
