### ISSUE TITLE
tinkers construct upgrade probelm

### ISSUE THREAD

**Issue by Muser9185** [NillerMedDild/Enigmatica2Expert#1855]
**Modpack version**
enigmatica 2 expertmode version1.82

**Issue**
i got a osgloglas pickaxe with tinkers construct
 and its telling me it isnt letting me mine things like obsidian and even uranium and certus quarts even wen it says i cant it does let me mine it but its very slow cause of it saying it isnt aloud this also happened with the manyullyn pick aswell

![Screen Shot 2020-11-23 at 12 12 08](https://user-images.githubusercontent.com/74909711/99960736-27689e00-2d85-11eb-9147-9db8c8c93b58.png)

**Comment by Discomanco** [comment]
What is the level of Sharpening Kit you have on?
Also, are you on 1.82 or 1.82a? There's a bug with mining levels in 1.82, hence the hotfix

**Comment by freundlich** [comment]
There is currently a bug that makes the mining level not increase if you replace the pickaxe head on a tool that already has a sharpening kit applied. In my case I had a pickaxe with an obsidian sharpening kit. I then swapped the pickaxe head out for a cobalt pickaxe head, but the mining level stayed on obsidian. Only after applying a cobalt sharpening kit as well, did the mining level actually increase.

**Comment by NillerMedDild** [comment]
That's not a bug, the Sharpening Kit overrides the harvest level, as is intended :)

**Comment by freundlich** [comment]
Sorry, for some reason I thought that this worked differently in the past.

**Comment by Muser9185** [comment]
I got to iron level with another pick and that’s were the problem starts it says I can’t mine lead ore with iron pick that’s even with iron pick head and then sharpening kit and Verizon is 1.82a

**Comment by NillerMedDild** [comment]
Could you please provide a screenshot of the Pickaxe's tooltip?

**Comment by Muser9185** [comment]
![2020-11-28_13 31 54](https://user-images.githubusercontent.com/74909711/100516901-f8846a80-317e-11eb-9325-3b71b5661836.png)

**Comment by Muser9185** [comment]
![2020-11-28_13 45 21](https://user-images.githubusercontent.com/74909711/100517065-0c7c9c00-3180-11eb-9616-3ad1796038a3.png)

**Comment by NillerMedDild** [comment]
That really does look like the 1.82 bug to me, could you try to downgrade version and then update to 1.82a again please?
