### ISSUE TITLE
Nether ores explode with new Netherending Ores config

### ISSUE THREAD

**Issue by MorganSimic** [NillerMedDild/Enigmatica2Expert#1856]
**Modpack version**
1.82a

**Issue**
With the new version of Netherending Ores, ores do now explode by default. There is a whole new config section, that wasn't there before, since i think that was not intentional.

Proposed fix:
Change true to false in the this segment of the netherending ores config.
`"ore explosions" {
        # Enables the ability for ores to explode. [default: true]
        B:"Ore explosion"=true
`
Haven't checked yet, but there may be some other nasty suprises in the new config.

**Comment by MorganSimic** [comment]
Yeah i checked, the new (1.4) version, also does now add mobs by default (the netherfish) and stuff, also changes the drop behaviour of ores by default now. Some ores now drop items instead of the ore block. Not sure if that is good change or not. 
Also it has it's own config for angering pigmen, so that may conflict with AngerManagment.
This all isn't mentioned in the changelog of the mod, only on the curseforge feature page, it's mentioned what 1.4+ does.
So the config probably needs some serious clean up in general.

**Comment by NillerMedDild** [comment]
I'm actually the one who requested these changes, like 2 years ago :P but I'll revert to the old version, thanks Morgan!

**Comment by MorganSimic** [comment]
Haha, okay. That i couldn't have anticipated. But i feel now, after two years players are so used to how it works, such a drastic change doesn't seem nice.

**Comment by NillerMedDild** [comment]
Agreed :P

**Comment by joycourier** [comment]
Damn, that's a recent update that flew under the radar? I'll be honest, this update has been responsible for many a shitted pant.
