### ISSUE TITLE
Ok lets talk about E3E Expert. the new version of expert im not even sure you're working on.

### ISSUE THREAD

**Issue by Kuktar** [NillerMedDild/Enigmatica2Expert#1857]
I will try and keep this short, it will be hard though.

So i completed the bragging rights quests and i feel like it took an eternity even with a nice fast server world. I feel very acomplished.

The only way other than updating and changing the tech and magic mods and maybe changing quests or just adding some quests.

I started playing RLcraft last night and i kept having epiphanis about how cool it would be to overhaul the adventuring of an expert pack. So not only is progression expert but the mobs and world you live in becomes expert as well.

I am in no way saying making the rpg and adventuring elements just like or copying rlcraft but getting inspiration from RLcraft could really spice up the life of an expert pack.

I meen minecraft modded has evolved alot so it covers mining, progression, cool things to build, base building, fighting mobs, etc...

For some reason an pack with such tough progression and survival becomes expert makes me weep but i think its a cool direction to go in.

I hope you are having happy holidays even though i dont think you live in america do you lol

**Comment by NillerMedDild** [comment]
Congrats on completing the pack!

> I hope you are having happy holidays even though i dont think you live in america do you lol
No holidays here in Denmark at the moment, but thanks, you too :P

The next Expert pack will hopefully be Enigmatica 6: Expert, here's the issue tracker for it: https://github.com/NillerMedDild/Enigmatica6/issues

Do you have any examples of things you'd like to see in a future Enigmatica Expert?
