### ISSUE TITLE
Crash during modpack load

### ISSUE THREAD

**Issue by brobotato** [NillerMedDild/Enigmatica2Expert#186]
#### Crash Report: [link](https://pastebin.com/ET712p2b)

Solved by updated CodeChickenLib from CodeChicken Lib 1.12.2-3.2.1.349-universal -> CodeChicken Lib 1.12.2-3.2.1.350-universal. Sort of weird this wasn't documented, maybe it was just me?

**Comment by NillerMedDild** [comment]
I don't release versions that crash on loadup. 
How are you downloading the pack? :)

**Comment by brobotato** [comment]
MultiMC 0.6.0 downloader using a local zip file downloaded from the CurseForge page. Inside the manifest.json of the zip I downloaded, I found these lines, which correspond to CodeChicken Lib 1.12.2-3.2.1.349-universal.

    {
      "projectID": 242818,
      "fileID": 2594239,
      "required": true
    }

I also had this problem with other modpacks, so maybe this is just an issue with my computer.

**Comment by NillerMedDild** [comment]
Myeah probably :)
