### ISSUE TITLE
Global Traveler (Alumite trait) does not work with Kama

### ISSUE THREAD

**Issue by joycourier** [NillerMedDild/Enigmatica2Expert#1861]
**Modpack version**
1.82a

**Issue**
I made a Mattock out of Alumite and the item teleportation works as expected.
I made a Kama out of Alumite and it doesn't work. 
Specifically, the head is Alumite.
Could this have something to do with Global Traveller requiring the correct tool, but the Kama just isn't listed as a Shears?

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
I do not believe I can fix this, and the majority of modders no longer support 1.12, so I'll close this issue.

Nethertheless, thank you for reporting :)
