### ISSUE TITLE
Evil Infused Iron arrows always destroy grass, even when not held

### ISSUE THREAD

**Issue by joycourier** [NillerMedDild/Enigmatica2Expert#1862]
**Modpack version**
1.82a

**Issue**
When you have an arrow made of Evil Infused Iron in your inventory, the effect of the Evil Aura trait is always active.

This is true even if you take another arrow and place it 'in front' of the Evil Iron arrow (like a Minecraft arrow).

I would guess that this is because the arrow is 'equipped' somewhere in the code, but I'm surprised that Evil Aura is active even without a bow in your inventory.

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by NillerMedDild** [comment]
Hi there, sorry for the slow response!

I don't really see this as a bug to be honest, albeit annoying :P I don't think there's a good way of knowing if a tool is being used, not without checking very very often, potentially causing lag.
