### ISSUE TITLE
Dispensers not placing seeds as Animania expects (possible Botania conflict?)

### ISSUE THREAD

**Issue by joycourier** [NillerMedDild/Enigmatica2Expert#1863]
**Modpack version**
1.82a

**Issue**
https://github.com/capnkirok/animaniamod/issues/131

This issue is present in E2E as well, regardless of whether B:allowSeedDispenserPlacement is set to true in animania.cfg

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by NillerMedDild** [comment]
I believe this is caused by Quark, it allows using Dispensers for planting.
