### ISSUE TITLE
AE2 crafting terminal closes when trying to start an autocraft from inside a compact machine.

### ISSUE THREAD

**Issue by toastonrye** [NillerMedDild/Enigmatica2Expert#1864]
1.82a

Edit: I realize this should probably be submitted to the AE2 issue tracker, but I'm curious if anyone else has this issue or know why it does it, seemingly irregularly.

I have an AE2 crafting terminal inside of a compact machine, brought in through ME capability adapters and P2P tunnels. I also have the wireless terminal in my inventory, which I am not trying to use because the wireless connection is in the overworld and not in the cube.

Everything is chunkloaded, when I try to start an autocraft by middle-clicking with the mouse inside the crafting terminal (the wired one) the GUI closes instead of asking me how many I want to autocraft. When I removed the wireless terminal from my player inventory, everything worked as normal. And when I brought the wireless terminal back into my inventory, I was still able to autocraft surprisingly...

The wireless terminal is from AE2, it's not a crafting terminal either.

**Comment by NillerMedDild** [comment]
Hi there! Thanks for the bug report. I'm afraid AE2 no longer support 1.12, so there's not much we can do here. Sorry!
