### ISSUE TITLE
Can't craft OpenComputers Diamond Nuggets normally

### ISSUE THREAD

**Issue by pPkMnh4to8994h** [NillerMedDild/Enigmatica2Expert#1865]
**Modpack version**
1.82a

**Issue**
If you go and try to craft Diamond Nuggets, it crafts Extra Bit Manipulation variant of it instead, which are completely unusable in OC recipes, probably because they lack "chipDiamond" entry in OreDict.  I believe you **can** still create usable ones though, by casting them from Smeltery, which is kinda annoying to do.

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by Cyprex** [comment]
We've also ran into this issue, should be as simple as adding an oredict entry or removing one of the recipes

**Comment by airbreather** [comment]
>  I believe you **can** still create usable ones though, by casting them from Smeltery, which is kinda annoying to do.

The correct Diamond Nugget comes out of the Compacting Drawer, so our workaround was to set up an ME processing pattern that "creates" 9 Diamond Nuggets by putting one diamond into such a drawer, and then we always just extract any Diamond Nuggets from that into the ME system.
