### ISSUE TITLE
Dank null MK VI doesnt require MK V in the recipe

### ISSUE THREAD

**Issue by SaleemTheKing** [NillerMedDild/Enigmatica2Expert#1866]
**Modpack version**
1.82a

**Issue**
Dank null mk VI doesnt require mk V in the recipe while upgrading from MK 1 to MK V does

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
I do not believe I can fix this, and the majority of modders no longer support 1.12, so I'll close this issue.

Nethertheless, thank you for reporting :)
