### ISSUE TITLE
Ring of Odin and Personal Nanobeacon Health Boost Modifiers causes loss of hearts

### ISSUE THREAD

**Issue by CutieLuna** [NillerMedDild/Enigmatica2Expert#1867]
**Modpack version**
1.82a

**Issue**
Ring of odin + Nanobeacon 6 health boost modifiers made me lose hearts.
Without nanobeacon, I had 3 purple hearts, with nanobeacon 6 health boost modifiers, it added 3 hearts. I took of ring of odin, and I'm left with 10 less hearts. I got rid of nanobeacon buffs and put on Ring of Odin, and instead of 3 purple hearts, I have 3 blue hearts. I have lost 10 hearts from nothing. Dying might have something to do with that. I believe I died a few times, not sure if the ring stays even if you die.

**Logs**
Not applicable

**Comment by CutieLuna** [comment]
Fix found, somewhat; I decided to remove all armor, baubles, items (threw them on ground) and did /kill. I did it until Nutrition was all at 30%. I put everything back on and got nutrition to full. I am now back at 3 purple hearts with only ring of odin, no Nanobeacon buffs.

**Comment by NillerMedDild** [comment]
could this have something to do with #1546 ? :)

**Comment by CutieLuna** [comment]
> could this have something to do with #1546 ? :)

Seems not. I don't lose hearts when going between dimensions, this only happened with nanobeacon and odin, I've since fixed it as said above, but I'm not quite sure about the cause...

**Comment by NillerMedDild** [comment]
To be honest this issue is so edge-cased that I'd prefer not to look for a permanent solution for it. Most mods don't fix non-critical issues in 1.12 either, so that makes it even harder. Is that alright, or is it important for you that the issue is resolved?

**Comment by CutieLuna** [comment]
The loss of hearts is always disheartening (yes it's a pun), but I don't really care if it gets fixed or not, would be a nice thing, since what if you keep dying and you have to die again without items to fix it
