### ISSUE TITLE
Infinite mob drops: Killing a mob in the same tick you capture it with a golden lasso gives you the drops, and captures the mob

### ISSUE THREAD

**Issue by MyNameIsCalvinDavis** [NillerMedDild/Enigmatica2Expert#1868]
**Modpack version**
1.82a

**Issue**
If you have a ticon laser equipped in offhand and try to capture a mob with a golden lasso, you kill the mob and capture it in the same tick, giving you its drops but also capturing the creature

**Logs**
N/A Does not crash the game

**Comment by NillerMedDild** [comment]
Nice find :P

The items that cause this dupe are both from mods that are no longer maintained, so I'm afraid there's not much we can do.
