### ISSUE TITLE
Dragons can't break blocks

### ISSUE THREAD

**Issue by Vintschente** [NillerMedDild/Enigmatica2Expert#1869]
**Modpack version**
1.82a

**Issue**
Wild and tamed dragons can't break blocks. Tested in claimed and unclaimed chunks. (I am not sure if this is a mod or modpack issue.) Config options are correctly set by default so they are allowed to break blocks.

This causes obvious flaws in the pack (I am running a private server) as one player cheesed a dragon with a iron sword through a wall (not taking damage and just killing the dragon), doing this with several dragons and taming one, then built the dragonsteel armor with gives him stupid amounts of armor. The dragons aren't gated in any way neither is the dragonsteel armor (which should be).

**Comment by NillerMedDild** [comment]
That is intended, so dragons don't wreak havoc on terrain, gravestones and builds :)

**Comment by Vintschente** [comment]
Thanks for the quick answer!

Is there a config option to turn this on somewhere?

**Comment by NillerMedDild** [comment]
Sure thing!

There is:

`ice_and_fire.cfg` line 140

**Comment by Vintschente** [comment]
Thank you so much! By the way you are doing great work with these modpacks and I love them! Is there a donation link available?

**Comment by NillerMedDild** [comment]
You're welcome, and thank you :D
There is, either through GitHub Sponsors, which is like Patreon: https://github.com/sponsors/NillerMedDild
or the [CurseForge paypal link](https://www.paypal.com/donate/?return=https://www.curseforge.com/projects/282744&cn=Add+special+instructions+to+the+addon+author()&business=niels.pilgaard%40hotmail.com&bn=PP-DonationsBF:btn_donateCC_LG.gif:NonHosted&cancel_return=https://www.curseforge.com/projects/282744&lc=US&item_name=Enigmatica+2%3a+Expert+-+E2E+(from+curseforge.com)&cmd=_donations&rm=1&no_shipping=1&currency_code=USD) :)
