### ISSUE TITLE
ender io fluid filter does not work under certain conditions

### ISSUE THREAD

**Issue by kuyana** [NillerMedDild/Enigmatica2Expert#187]
#### Issue Description
In the case of only fluid conduit and fluid filter, it is not possible to set the fluid filter.
In situations where conduit tabs other than fluid conduit are displayed, you can set them.
#### Modpack version (Do not use "latest")
1.34
[pastebin/gist/etc link here]
https://i.imgur.com/twy7M6w.png
https://i.imgur.com/FtDQBY6.png

**Comment by NillerMedDild** [comment]
Huh, that is super weird.

**Comment by buizerd** [comment]
Workaround: sneak right-click with the filter in your hand to open the fluid filter settings
