### ISSUE TITLE
Ender io not working

### ISSUE THREAD

**Issue by Malaci81** [NillerMedDild/Enigmatica2Expert#1874]
**Modpack version**
Enigmatica 2: Expert - E2E -1.82a

**Issue**
Ender io not working. Machines are craftable and accept power but don't function, cables are invisable when placed. Have tested it on a server and in single player. I have tried upgrading to the latest version of ender io (5.2.66) but this version is incompatable with ender tweaker. I have downgraded to Ender IO - 5.2.61 and this works.

**Comment by TemperedFool** [comment]
Do you have Optifine installed? It can cause some crazy issues.

**Comment by Malaci81** [comment]
Its a default Enigmatica 2: Expert - E2E -1.82a pack except for LagGoggles-1.12.2-5.8-132 and TickCentral-3.2 i added to spot lag.

**Comment by NillerMedDild** [comment]
Please remove those two mods and see if the issue persists :)

**Comment by Malaci81** [comment]
Sorry my mistake, completely forgot I installed LagGoggles-1.12.2-5.8-132 and TickCentral-3.2. I just tried it back in its default install states and it indeed works fine. I tried it with just TickCentral-3.2 and it fails looks like that’s the problem. Can I ask for some sort of lag detector be included in the the pack in the future?

**Comment by NillerMedDild** [comment]
I'd rather not add debugging mods to be honest, but TickProfiler and Spark are nice ones, and should be safe to add.
