### ISSUE TITLE
Tinker's Tools/Harvest Levels not applying properly to tools

### ISSUE THREAD

**Issue by Shogun1332** [NillerMedDild/Enigmatica2Expert#1875]
**Modpack version**
1.82a

**Issue**
Tinker's Tools/Harvest Levels incorrect on Pickaxe, potentially other tools. Crafted a certus quartz pickaxe, obtained Iron, crafted a new iron pickaxe and the harvest level is Certus. Had to use OP to grant myself Lead Ore as I was unable to mine it with my iron pick, crafted a new Lead Pick and it's harvest level is Copper, so I am still unable to progress. Attempted using an Iron sharpening kit with the Iron pick, says in the Tinker's Tool Forge GUI that the harvest level is going to be upgraded to Iron, but after applying, the level is still Certus. Also attempted applying a Diamond, again it says that the harvest level will be Iron, but after the application it is still just Certus.

**Logs**
Not sure what, if any, logs would be appropriate, uploaded some screenshots of the iron and lead pickaxe

![Iron Pick](https://user-images.githubusercontent.com/60228512/104109108-bc691d00-5287-11eb-8bdf-ce51679bf927.JPG)
![IMG_4138](https://user-images.githubusercontent.com/60228512/104109106-b83cff80-5287-11eb-9a76-92d33c143e94.JPG)
![unnamed](https://user-images.githubusercontent.com/60228512/104109111-becb7700-5287-11eb-92e7-c27fcda483f2.jpg)
![unnamed (1)](https://user-images.githubusercontent.com/60228512/104109109-bd01b380-5287-11eb-9f4f-6de8c36a9f9c.jpg)

**Comment by NillerMedDild** [comment]
Please reinstall, this was fixed in 1.82a :)

**Comment by Shogun1332** [comment]
Thanks for the quick response!

**Comment by NillerMedDild** [comment]
Sure thing! Please let me know if reinstalling doesn't help :)

**Comment by Shogun1332** [comment]
Looks much better, clients were on 1.82a but my server was running 1.82. Appreciate the help!
