### ISSUE TITLE
Can't join hamachi server with a friend

### ISSUE THREAD

**Issue by Trovinha** [NillerMedDild/Enigmatica2Expert#1877]
**Modpack version**
1.82a

**Issue**
Everytime I try to login our hamachi server this error appears, we were playing just fine for a while, now I can't connect to the server.  This is the erro that appears,  does not have a crash log or anything

**
![image](https://user-images.githubusercontent.com/77309521/104259029-6058f100-545f-11eb-809c-c20793d5660b.png)
**

**Comment by NillerMedDild** [comment]
Both of you should reinstall :)
