### ISSUE TITLE
Builder Quarry in the Nether can crash a server

### ISSUE THREAD

**Issue by Vintschente** [NillerMedDild/Enigmatica2Expert#1879]
**Modpack version**
1.82a

**Issue**
The builder counts as a fake player thus the Netherending Ores explode when the builder mines them. This causes thousands of items to lay on the ground and almost killed my server by lagging about 40 seconds all the time. For now I disabled the explosions in the Netherending Ores config. Is there some kind of exception in a config that can be made for fake player blocks?

**Comment by NillerMedDild** [comment]
Not that I'm aware of, but ores aren't even meant to explode, see #1856 :)
