### ISSUE TITLE
thaumcraft

### ISSUE THREAD

**Issue by anaslaktati** [NillerMedDild/Enigmatica2Expert#188]
can't get any thaumcraft items (right clicking a bookshelf or cauldron with the violet dust)

Modpack enigmatica2 expert

**Comment by NillerMedDild** [comment]
The issue template is there for a reason, don't just delete it.

Please read the quests you're given. You need to pick up Vis Crystals (they are often found in caves), and sleep afterwards. Then you'll be able to make the Thaumonomicon.
