### ISSUE TITLE
uu-matter recipe for connectors is unbalanced 

### ISSUE THREAD

**Issue by NexusNull** [NillerMedDild/Enigmatica2Expert#1880]
Enigmatica 2 Expert 1.82a

I just want to bring attention to a very unbalanced replicator recipe, the replicator is able to produce connectors from environmental tech for about 1.7 mB of UU-matter the alternative crafting recipe takes 4 blocks of tin.

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by toastonrye** [comment]
Is there another config that allows the envirotech connector to be replicated with uu-matter? I don't see it in the IC2 config, just curious what other items can be replicated?

**Comment by NillerMedDild** [comment]
It is indeed in the ic2.ini file :)
Connectors being very cheap is on purpose btw.
