### ISSUE TITLE
Immersive Engineering Crusher not crushing ores

### ISSUE THREAD

**Issue by CptTrilby** [NillerMedDild/Enigmatica2Expert#1881]
**Modpack version**
1.82a

**Issue**
The Immersive engineering crusher multiblock will not crush ores, it will just get "stuck" and continue to crush endlessly without outputting anything. It crushes cobblestone fine.

EDIT:
found a similar problem in another modpack. https://github.com/FTBTeam/FTB-Continuum/issues/314

**Comment by NillerMedDild** [comment]
duplicate of #1841
