### ISSUE TITLE
[Ice and Fire] Dragons can't decline their flight with "sneak"

### ISSUE THREAD

**Issue by Signupsforeverything** [NillerMedDild/Enigmatica2Expert#1882]
**Modpack version**
Enigmatica 2 Expert 1.82a

**Issue**
Dragons can't decline flight.
Ingame Mod-Manuel says "sneak" to make the dragon go down.
But sneak is dismount dragon.
So me and dragon drop out of the sky like dead birds.

----------------------------------------------------------------------------

**Sidenotes, like other (unrelated) issues/nagging about stuff I encountered:**
- (Ice and Fire) Dragons can't breed, but I saw that already in progress. Just mentioning.
- Is it intended that Underground Ice Dragons (Ice and Fire) stay quite? Makes them harder to find.
Or is it unintended that Underground Fire Dragons can't keep quite?
I think in Expert 1.73 they didn't make any noise, so I never found them to get eggs when we played 2 years ago.
- I captured some pixies (Ice and Fire). I jared them up and wanted to place them elsewhere and instead of using the bag of holding like a smart person I pickaxed the jars. Pixie stole my pants... Server: It would be realy inconvinient when this pixie would phase shift right now, right? Maybe it was lag. Either way the pixie just stoped to exist in some way on my end, together with my pants. Two days later I return to the sceen of the crime and I see the pixie flying in the same corner before it dimention hopped.
Have no jar on me, so I go for one, because I want the pixie dust. Got some cake too as a last resort to tame it.
I return, pixie gone. Crap. I try to capture the air in vain. I trow my cake. Get "Ha-Ha"-ed. Something happened. I port back and forth with brown magic from tinkers. Find pixie on the ground where the cake was with my pants in their clutch.
Named it "Panty" in revenge. Got pants back at some point. Don't know, it just let it fall. Had replaced my pants already with a better pants...
- The chest plate of the infinity armor (Avaritia), the arms are not correctly orientated. Looks weird.
- Armor/held items on me or other players are sometimes not displayed in inventory/world. Not sure what triggers it.
Naked player skins. Naked player skins everywhere.
Logging back in temporarily fixes it.
- (In local game, creative) If tainted (Thaumcraft) Ice-and-Fire-Mobs take damage my game "crashes" (freeze-locks).
- Ice and Fire sapphires are placed in the chests in ice dragon layers. They seem pointless, because bioms o'plenty sapphiers.
- The thaumcraft enchantment altar has issues. It crashed the server, when an unexpected item was placed and didn't enchant the mantle of stars from Astral Sorcery.
- The (cyclic) unchant pylon seems to not remove the XP-cost-increase, because I removed all enchantments from my Mantle of Stars to change the Alignment, because I didn't know if this would void the enchantments, but afterwards the anvil tells me everything is too expensive (40+?). And so I stood there with 120 Levels...
- Fire dragon hatchlings have a "small" gap in their wings. Looks weird.
- Bloodmagic could need a better seperation between lore and crafting instructions/explainations. Also it needs some info boxes in TooManyItems (TMI) too. Couldn't find how to make blood shards in the book and no descrition in TMI about it. Took me three days to find it in the manuel between the lines of lore.  *sad violin starts playing*
- (Tinkers Construkt) "Endspeed" on the arrow shaft made my arrows not instant hit things.
- (In local game, creative) The medusa head (Ice and Fire) seems to have some problems. Like: mobs being caught in a "dead-alive"-state.
- (Thaumcraft) (In local game, creative) The Focus inscription table has problems with inscribing foci that were drawn from TMI.
They either get voided when taken into the inventory on the side of the UI, or the inscription process doesn't even finish.

**Comment by NillerMedDild** [comment]
I believe the dragon descend keybinding is actually X, not sure I can make shift not dismount you, but I'll try.

> Is it intended that Underground Ice Dragons (Ice and Fire) stay quite? Makes them harder to find.
Or is it unintended that Underground Fire Dragons can't keep quite?
I think in Expert 1.73 they didn't make any noise, so I never found them to get eggs when we played 2 years ago.

Not directly intended by me, probably by the mod.

> The thaumcraft enchantment altar has issues. It crashed the server, when an unexpected item was placed and didn't enchant the mantle of stars from Astral Sorcery.

Crash report please


To be honest this is way too much for one bug report, please split the issues you deem important into other issues.
