### ISSUE TITLE
Rock Crystal Ore Incorrectly given into

### ISSUE THREAD

**Issue by Danxv33** [NillerMedDild/Enigmatica2Expert#1883]
Latest Version

**Issue**
Rock Crystal ore from astral has info on JEI that says "generates in large quantities on other planets", but JER says it only generates in the overworld, so either the info is incorrect or JER is incorrect. Haven't been to space so cannot comment on the spawn rate.

**Comment by NillerMedDild** [comment]
JEI is incorrect :)

**Comment by Thiana** [comment]
Other planets? Does that mean dimensions like Undergarden/etc or did I miss a space mod being added?

**Comment by Danxv33** [comment]
In either case, this is a bug no?

**Comment by Danxv33** [comment]
> Other planets? Does that mean dimensions like Undergarden/etc or did I miss a space mod being added?

Advanced Rocketry?

**Comment by Thiana** [comment]
Oops. Ignore me, didnt notice the discord github feed was for all Enigmatica repos not just E6.

**Comment by NillerMedDild** [comment]
It just has a JEI description instead of JER, because JER fails to register it.
