### ISSUE TITLE
Visual glitch after death until I get my Grave....

### ISSUE THREAD

**Issue by JmB819** [NillerMedDild/Enigmatica2Expert#1884]
**Modpack version**
1.82a
**Issue**
Visual glitch after death until I get my Grave....

tried dyng with no items on me for a pic but the glitch didnt happen

![2021-01-28_20 11 16_2](https://user-images.githubusercontent.com/78180188/106218977-7f1cee80-61a6-11eb-98ea-c67d2f6e10ca.png)
![2021-01-28_20 11 16_2](https://user-images.githubusercontent.com/78180188/106219005-8d6b0a80-61a6-11eb-932a-6648bc6f1eef.png)

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by JmB819** [comment]
note that everything return to normal; once grave is picked up...

**Comment by NillerMedDild** [comment]
Damn that is strange, thanks for the report. Are you using Optifine and/or VanillaFix?

**Comment by JmB819** [comment]
no I did not modify the pack beside adding ram so it would run....

________________________________
De : Niels Pilgaard Grøndahl <notifications@github.com>
Envoyé : 29 janvier 2021 01:26
À : NillerMedDild/Enigmatica2Expert <Enigmatica2Expert@noreply.github.com>
Cc : JmB819 <jmboyer819@hotmail.com>; Author <author@noreply.github.com>
Objet : Re: [NillerMedDild/Enigmatica2Expert] Visual glitch after death until I get my Grave.... (#1884)


Damn that is strange, thanks for the report. Are you using Optifine and/or VanillaFix?

**Comment by NillerMedDild** [comment]
Alright, I'll investigate :)

**Comment by NillerMedDild** [comment]
Cannot reproduce, might've been fixed.
