### ISSUE TITLE
still alive

### ISSUE THREAD

**Issue by gabbyzhat** [NillerMedDild/Enigmatica2Expert#1885]
**Modpack version**
Input modpack version here

**Issue**
Input short description of the issue here

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by Merlo17** [comment]
I think something went wrong there :P

**Comment by theboo** [comment]
I'm glad you're still alive... I hope you continue staying in that state!

**Comment by Ridanisaurus** [comment]
I'm confused

**Comment by Merlo17** [comment]
https://www.youtube.com/watch?v=Y6ljFaKRTrI

**Comment by gabbyzhat** [comment]
> 
> 
> I'm confused

dont do drugs kids
