### ISSUE TITLE
Arc Furnace Recipes forgotten

### ISSUE THREAD

**Issue by Danxv33** [NillerMedDild/Enigmatica2Expert#1888]
**Modpack version**
Latest

**Issue**
Just wanna say at the start that this might not be an e2e problem, might be an IE problem, but oh well I'll continue. The arc furnace seems to forget, for lack of a better term what items can be recycled. For example, right now, it forgot that you can recycle terrasteel armour. Previously, it forgot how to recycle anything made of manasteel and elementium. Restarting fixes this, but I want to know if this is caused by my bad computer or an actual glitch.

**Comment by NillerMedDild** [comment]
I'm guessing this is an actual glitch, as the Arc Furnace recycling recipes are also troublesome in newer Minecraft versions, albeit in a different way. Sadly, there's nothing we can do as Immersive Engineering no longer supports Minecraft 1.12.
