### ISSUE TITLE
crash while finishing the Metallurgic fabricator

### ISSUE THREAD

**Issue by Alex-S98** [NillerMedDild/Enigmatica2Expert#1889]
**Modpack version**
Enigmatica2Expert-1.82a.zip From CurseForge

**Issue**
When I finish the structure of the Metallurgic Fabricator, any of the "recipe" make the game crash, and I can't get back into the world anymore ( infinite world loading).
I've removed Ice and Fire from the modpack and added ultimate "skyblock resource generator" 

**Logs**
Crash Report
https://pastebin.com/aeiLpTkH

The "main line" that MC launcher shows: 
java.lang.IllegalArgumentException: Unknown ItemStack: Cannot find an item in oredict 'ingotModularium'!

**Comment by NillerMedDild** [comment]
Interesting O_o did you update any mods?

**Comment by Alex-S98** [comment]
I just deleted Ice and fire to not get bothered by the dragons, added the "syblock things" (https://www.curseforge.com/minecraft/mc-mods/ultimate-skyblock-generator)

and this time ( cuz I already had this bug earlier this year and stopped playing after it blocked my main world), I tried to desactivad the channel things on AE2. Upon that, the modpack is just downloaded from the Curseforge software and I've allocated 8256 MB of ram out of 16G ( maybe I should set the ram in the JVM argument and not with the slider on the curseforge soft? ) 

This bug happens on a new superflat map with nothing other build than this structure
I'll try to reinstall the modpack with a clean install and retry to make the structure in a superflat world...

**Comment by Alex-S98** [comment]
IT seems like it's working on a brand new installation. 
I'll try to just tweaks the options to avoid the Ice and Fire things in my world and try to see without the "generators" mod too....

**Comment by NillerMedDild** [comment]
Deleting Ice and Fire was probably the culprit :)
