### ISSUE TITLE
Mod Request - Comforts

### ISSUE THREAD

**Issue by SirNahka** [NillerMedDild/Enigmatica2Expert#189]
https://minecraft.curseforge.com/projects/comforts

Comforts adds two main things - sleeping bags in all 16 colours instead of just the one that we have now, and a Hammock which does the opposite of a bed. It can be used to change day to night. This would help significantly with getting through Astral Sorcery content and Thaumcraft's moon scanning mechanics.

**Comment by NillerMedDild** [comment]
It doesn't add anything the pack doesn't already have. You can use Blood Magic's Imperfect Ritual Stone with a Lapis Block on top to make it night.

**Comment by SirNahka** [comment]
I was not aware of that! Thank you.

**Comment by NillerMedDild** [comment]
Sure thing :)
