### ISSUE TITLE
Game REALLY likes crashing during load-up

### ISSUE THREAD

**Issue by Roflpwnage** [NillerMedDild/Enigmatica2Expert#1890]
**Modpack version**
1.82a (This has been an issue for me for many a version though)

**Issue**
The game crashes while trying to load the modpack. It's random when exactly it crashes during the load up; but it usually crashes every time. Might get lucky after about 5-10 attempts. This is the ONLY modpack that does this to me, and I've played a few.

**Logs**
[hs_err_pid14484.log](https://github.com/NillerMedDild/Enigmatica2Expert/files/5969259/hs_err_pid14484.log) The first error log that the client launcher gave me. 

[hs_err_pid552.log](https://github.com/NillerMedDild/Enigmatica2Expert/files/5969267/hs_err_pid552.log) Second Attempt.

Apologies if this is not the correct 'crash log' you are looking for, I am completely lost with this stuff. I'm just grabbing the crash report that the minecraft client is giving me, and giving whatever information I can figure out.

I have made attempts to uninstall/reinstall the modpack several times, usually with full clears. I am using the CurseForge application to launch the modpack. I have the memory allocation set to the max the application will allow (12228mb), I have 24gb, more than enough to run it. The load up screen shows I am using 10923mb of ram.

**Comment by Discomanco** [comment]
You appear to be using outdated Java.
This is often caused by the CurseForge Client defaulting to an old, integrated Java version, rather than what you have available on your PC.
Follow these steps to update.

Step 1. Make sure you have the latest Java 8, 64-bit installed
   - Windows:
       https://www.java.com/en/download/windows-64bit.jsp
   - All downloads (Mac/Linux):
       https://www.java.com/en/download/manual.jsp
Step 2. Go to the CurseForge Minecraft settings
Step 3. Add `-version:1.8+` to the Additional Arguments

**Comment by Roflpwnage** [comment]
Cool, that seems to have fixed it: unless I just got lucky twice. Thanks.

Kind of begs the question of why this is the only modpack I had this issue with though,, I've played at least 7 or more other modpacks, both new and old.

**Comment by Discomanco** [comment]
It's honestly very random. Immersive Engineering has been a "culprit" of not working with 5 year old Java for some time, but it has extended to more mods now too, if it doesn't get loaded correctly
