### ISSUE TITLE
Redstone Furnace pyrolytic conversion Rf amounts are off

### ISSUE THREAD

**Issue by Danxv33** [NillerMedDild/Enigmatica2Expert#1892]
Newest

The pyrolytic conversion augment takes 4500 rf to turn 1 coal into 1 coal coke but taked 3600 rf to turn 1 block of coal into 1 coal coke block (this could just be a thermal foundation problem)

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
I don't have time to fix this I'm afraid, I hope you don't mind too much. ^^'
