### ISSUE TITLE
Two outcomes for the same recipe

### ISSUE THREAD

**Issue by RobertTurkot** [NillerMedDild/Enigmatica2Expert#1893]
Blue slime balls are able to be crafted into both a normal green slime block and a blue slime block, creating a conflict.

![image](https://user-images.githubusercontent.com/45073229/107963111-6be48e00-6fb0-11eb-9c3e-0d73071dec9a.png)

![image](https://user-images.githubusercontent.com/45073229/107963168-7c950400-6fb0-11eb-9824-ae4de39450e5.png)

**Comment by NillerMedDild** [comment]
Thanks for the report. Do you know which block is "picked"?

**Comment by RobertTurkot** [comment]
The block crafted is the blue slime block

![image](https://user-images.githubusercontent.com/45073229/107980901-bc1c1a00-6fc9-11eb-82ff-974c565b9e3f.png)

**Comment by NillerMedDild** [comment]
Awesome! In that case I'll not spend time on fixing this, as I have plenty of other issues to attend to tbh :P Thanks.
