### ISSUE TITLE
Astral sorcery is not working (Enigmatica 2 Expert Skyblock)

### ISSUE THREAD

**Issue by PUMA-09** [NillerMedDild/Enigmatica2Expert#1894]
**Modpack Version**
1.35

**Issue**
I can't use the Astral sorcery mod  table.  I think it's broken because if I insert a crafting recipe from the JEI nothing happens. It wouldn't show the result of the crafting. When I click on it with an resonating wand nothing happens. It wouldn't change when the table is higher or lower. I hope you can fix it because I can't play any further without it.

**Logs**
[latest.log](https://github.com/NillerMedDild/Enigmatica2Expert/files/5995384/latest.log)

**Comment by PUMA-09** [comment]
I used the support channel and they informed me it is a bug and redirected me to this page

**Comment by NillerMedDild** [comment]
Really? Huh. Alright. In that case please supply screenshots of your setup. Did you craft your Luminous Crafting Table yourself?

**Comment by PUMA-09** [comment]
I crafted it myself. I put it nearly everywhere (highest lowest point). The problem is when I insert a recipe (JEI) it doesn't show the output.
![no result right from the recipe](https://user-images.githubusercontent.com/66727155/108254209-0385e000-715b-11eb-88f3-dded85614a46.png)
![no result right from the recipe](https://user-images.githubusercontent.com/66727155/108253901-9d00c200-715a-11eb-8c9b-99a67b0e87d3.png)

I cheated a better astral sorcery table. This one doesn't register the surrounding blocks. It's like there are the Items but the input code of it isn't completely loaded Idk.
![cheated better astral sorcery table in the same world](https://user-images.githubusercontent.com/66727155/108254224-08e32a80-715b-11eb-80b8-98863bdca593.png)

If you have any clue or you need more screenshots of specific constellations let me know. Because I can't really play the magic tree or the hard chapters.

**Comment by PUMA-09** [comment]
Oh there is twice the same picture Sry.
![crafted astral sorcery table](https://user-images.githubusercontent.com/66727155/108254467-565f9780-715b-11eb-8a7e-aa29971b58a7.png)

**Comment by Merlo17** [comment]
You might simply not have enough starlight. Have you tried at night when the bar is full?

**Comment by KrAzYGEEK32** [comment]
It is a really old version of the pack, try updating? I can confirm the recipe works in latest (1.82a) version.

**Comment by NillerMedDild** [comment]
He's using the latest Skyblock version, it's just the wrong repo :P

**Comment by Discomanco** [comment]
It is definitely a lack of starlight. Apothecary needs a near full bar, even if the output doesn't show (just a case for custom recipes).  
Cheating in higher tables also wont yield you any results, as your progression wont trigger from that.  
Also also, your first picture seems to be during daylight, where starlight is least.

**Comment by PUMA-09** [comment]
Yeah but it won't change in the night.
I can't open the akashic tome the game freezes everytime and I can restart the pack
[Akashik tome.docx](https://github.com/NillerMedDild/Enigmatica2Expert/files/5998233/Akashik.tome.docx)

**Comment by Merlo17** [comment]
(you should really come to discord in our support channel to get this kind of help)
