### ISSUE TITLE
Jungles don't generate

### ISSUE THREAD

**Issue by toastonrye** [NillerMedDild/Enigmatica2Expert#1895]
**Modpack version**
1.82a

**Issue**
I can't find any Jungles which I need to find Tropical Hives. I need the Tropical Bees to complete the Forestry chapter. I'll list what I have tried:

1. I have tried using Nature's Compass to look for Jungles, in a 10k radius around my base. I even traveled the nether to quickly check 20k blocks from my base in the South and East directions.
2. I also looked for the biomes o plenty biomes Tropical Island, Tropical Rainforest, and Bayou because I read on Reddit they may have tropical hives... However I didn't find those either.

It seems I am suffering from bad luck with RNG and I will likely cheat in the tropical hives, which I have managed to avoid doing so far in this pack. (I'm mid way through the Draconic Ev chapter).

**Suggestion**
If I am missing something obvious, let me know but I don't see any tip in the Apiarst's Armour quest chapter. I think there should be another route to obtain the Apiarist's armour. It's the only item I can think of that suffers from bad luck with RNG. Thanks,

**Comment by toastonrye** [comment]
So I found the solution, something I've never done before so I didn't think of it but I am definitely going to try because I'm end game and can afford it. Making an RFTools dimension, the only thing I'm not sure of is how to get a Jungle biome, I don't have one to use a Biome absorber on!

And it's horrendously gated as the pack dev admits here lol! https://www.reddit.com/r/feedthebeast/comments/bm5p7y/enigmatica_2_expert_after_9000_thousand_blocks_of/emuawxw/

But if I'm able to get a Jungle biome from RFTools dimensions, I still feel like that tip should be in the forestry quest book.

**Comment by NillerMedDild** [comment]
Jungles (and a ton of other biomes) don't generate because of an issue with Integrated Dynamics Meneglin biome, we'll get that fixed eventually, thanks for the report :)
