### ISSUE TITLE
[Bug] (COFH) Flat Bedrock having 2 layers of bedrock bug AS Rituals in the nether and possibility other dimensions (and mods)

### ISSUE THREAD

**Issue by ReiDaTecnologia** [NillerMedDild/Enigmatica2Expert#1899]
**Modpack version**
1.82a
**Issue**
COFH's World config of Flat Bedrock have a config of how many layers of bedrock exist, by default it is 2 but i found out that by the nether roof having two layers of bedrock, it make the AS rituals doesn't work as it need to detect (a layer of) bedrock or the sky to activate the ritual, easily fixed by changing to 1. This bug can possibility affect other dimensions and mods. Of course this is a world gen alteration and therefore you would need to regen the chunk to see the change but exist several methods of breaking the bedrock in survival (both vanilla and modded) and obvious it will not affect new or returning players.

**Logs**
N/A

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.
