### ISSUE TITLE
1.13 Immersive Engineering Issues

### ISSUE THREAD

**Issue by deathpenalty52** [NillerMedDild/Enigmatica2Expert#19]
#### Issue Description
There are multiple issues with Immersive Engineering, such as the inability to remove creosote oil from the coke oven using a bucket, along with while breaking the crude blast furnace, it drops a physical item that represents the multiblock along with extra blast brick than was used to create it.

#### Modpack version (Do not use "latest")
Version 1.13 of the Enigmatica 2 Expert pack

**Comment by NillerMedDild** [comment]
IE just released an update, I'll update the pack asap.

**Comment by NillerMedDild** [comment]
And thank you for reporting!
