### ISSUE TITLE
Cobweb breaking - Consider expanding the selection of swords?

### ISSUE THREAD

**Issue by SirNahka** [NillerMedDild/Enigmatica2Expert#190]
#### Issue Description
Many "sword" type items are incapable of breaking cobwebs. TE's Flux-Infused Sword, BM's Sentient Sword, and EIO's The Ender all fail on webs. All of these are quite mid-to-lategame swords, its not like I'm trying to use a vanilla wooden sword or something.

#### Modpack version (Do not use "latest")
1.32

(Apologies if this has already been fixed a later version, I'm playing on a server and have no personal control over when they update)

**Comment by NillerMedDild** [comment]
This has not been fixed, thanks for the report :)
