### ISSUE TITLE
[net.minecraft.client.Minecraft]: Error executing task java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Recipe minecraft:wooden_door (net.minecraft.item.crafting.ShapedRecipes@2a73a64f) produces unregistered item minecraft:wooden_door (net.minecraft.item.ItemDoor@67a38)

### ISSUE THREAD

**Issue by ygabrielxd** [NillerMedDild/Enigmatica2Expert#1900]
**Modpack version**
Minecraft 1.12.2 MODPACK

**Issue**
[16:25:08] [Client thread/FATAL] [net.minecraft.client.Minecraft]: Error executing task
java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Recipe minecraft:wooden_door (net.minecraft.item.crafting.ShapedRecipes@2a73a64f) produces unregistered item minecraft:wooden_door (net.minecraft.item.ItemDoor@67a38)

my friend is having this error when trying to enter my lan world.

**Logs**
CLIENT LOG :   [2021-03-16-1.log](https://github.com/NillerMedDild/Enigmatica2Expert/files/6152082/2021-03-16-1.log)
SERVER LOG :   [2021-03-16-7.log](https://github.com/NillerMedDild/Enigmatica2Expert/files/6152083/2021-03-16-7.log)

**Comment by Danxv33** [comment]
I just checked the log, why are Bonsai Tree's and steve's carts mentioned? It's either you downloading more mods for E2E, or a different modpack.
