### ISSUE TITLE
Precision sawmill creates sawdust from different mods depending on recipe

### ISSUE THREAD

**Issue by complover116** [NillerMedDild/Enigmatica2Expert#1901]
**Modpack version**
1.82a

**Issue**
Cutting logs in a Mekanism Precision Sawmill gives Sawdust from Thermal Foundation. 
  Cutting planks into sticks, however, gives Sawdust from Mekanism.

Thank you for the pack!

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by Krutoy242** [comment]
> Cutting planks into sticks, however, gives Sawdust from Mekanism.

This could would be fixed in my next PR (probably in next month).
Or Niller can [pull this lines](https://github.com/Krutoy242/Enigmatica2Expert-Extended/blob/1c6525c1d3070e7f2ba00107069cd708fce8ac03/scripts/category/wood.zs#L129-L135).

**Comment by Krutoy242** [comment]
@NillerMedDild You commited straight with `scripts.wrap.[..]`
`scripts.wrap` is wrapper file im using for wrapping machine methods to output additional information.
You should use plain `mods.`, so lines would be
```zs
mods.mekanism.sawmill.removeRecipe(<ore:plankWood>);
mods.mekanism.sawmill.removeRecipe(<ore:slabWood>);
mods.mekanism.sawmill.addRecipe(<ore:stickWood>, <thermalfoundation:material:800>);
mods.mekanism.sawmill.addRecipe(<ore:plankWood>, <minecraft:stick> * 6, <thermalfoundation:material:800>, 0.25d);
mods.mekanism.sawmill.addRecipe(<ore:slabWood> , <minecraft:stick> * 3, <thermalfoundation:material:800>, 0.25d / 2.0d);
```
I forgot to mention that.

**Comment by NillerMedDild** [comment]
Thanks for clearing that up 👍
