### ISSUE TITLE
Official Docker images please!

### ISSUE THREAD

**Issue by rafaeltab** [NillerMedDild/Enigmatica2Expert#1902]
I'd like to get some official docker images of the Enigmatica modpacks especially this one . This makes it really easy to deploy any of your servers. There are already some unofficial ones but I don't really want to risk downloading something malicious when using those. 

If you don't know what docker is i'll give a brief summary here:
It is a program that allows for easy installation of virtual machines with code in them. All that is needed to create a minecraft server (without installing java or anything other then docker) is to run the command: `docker run -d -p 25565:25565 --name mc itzg/minecraft-server` and bam! after a few seconds you've got a simple minecraft server.

P.S. I'll only post this request here and not on the other Enigmatica repositories as I don't want to be annoying

**Comment by NillerMedDild** [comment]
Here you go good sir: https://github.com/NillerMedDild/Enigmatica6/blob/master/docker/docker-compose.yml :)

**Comment by rafaeltab** [comment]
Perfect that's what I'm looking for but only then for enigmatica2expert ;). Though I assume I can just use the same docker compose and change the zip to be the one from enigmatica2expert.

I would still suggest putting it on docker hub though!

**Comment by NillerMedDild** [comment]
Putting it on DockerHub would mean another place to maintain server files, I'd rather steer clear of that :)

**Comment by rafaeltab** [comment]
[https://docs.github.com/en/actions/guides/publishing-docker-images ](https://docs.github.com/en/actions/guides/publishing-docker-images )it can be easily handled through github actions meaning you could automatically publish it on every release or on every commit.

 If you don't want to go through the effort I'll wish you good luck with the rest making and maintaining these fantastic modpacks!

**Comment by TheRealGorrik** [comment]
I have been using docker to deploy all of my servers for a little bit, and for the most part, its all pretty much the same setup. 

I use this [dockerfile](https://pastebin.com/xc6q7QLU) to start.

All you have to do is extract the server zip files on your host system, and recompress to a .tar.gz format. You can do this using 7zip by first 'adding to archive', then choose tar as the format, then do the same for that output except with .gzip.

Next get a copy of the [eula.txt file](https://pastebin.com/eFscu4iD) and update the text to say `eula=true`

Place the dockerfile, the server .tar.gz file, and the eula all in the same directory and run the `docker build` and `docker run` commands found at the top of the dockerfile.

As a note, this particular dockerfile uses the 1.82 version and the 1.82 patch, you can update the dockerfile to make any other versions you want. 

I have used this dockerfile format for a couple other servers too. You just have to update the directory and file names and it should work
