### ISSUE TITLE
Attuning Mantle of Stars Isn’t Working

### ISSUE THREAD

**Issue by javagog** [NillerMedDild/Enigmatica2Expert#1903]
**Modpack version**
Valhesia 3

**Issue**
Attempting to attune the mantle of stars to vicio just won’t work for some reason. Even tried equipping, no change.

**Logs**
I have no idea where to find these

**Comment by NillerMedDild** [comment]
This is the issue tracker for Enigmatica 2: Expert, not Valhelsia 3 :)
