### ISSUE TITLE
Uanble to craft Yellow colored blocks in Flat Colored Blocks mod

### ISSUE THREAD

**Issue by Erytropus** [NillerMedDild/Enigmatica2Expert#1906]
**Modpack version**
1.82a

**Issue**
Yellow colored blocks are not craftable in Colored Block Crafter, every other dye seems to be working fine though.

**Comment by NillerMedDild** [comment]
Thanks for the report. I'm aware of the issue, but fixing it would result in id shifts for all the other colors, potentially ruining a lot of worlds, so there's not much I can do :(

**Comment by ReiDaTecnologia** [comment]
But you can fix it manually (at your own risk) by changing "HUE_SHADES" in the mod's config but as Niller said, it can generate issues so create a backup!
Change the "HUE_SHADES", "HUE_SHADES_GLOWING", and "HUE_SHADES_TRANSPARENT" value to the default one: 32
I did that in my world, checked if issues appeared and didn't find any, but if i find any, it will be easily fixed as i have a backup.
