### ISSUE TITLE
Unable to copy Omni-Directional Connector group to another connector.

### ISSUE THREAD

**Issue by EDSenne** [NillerMedDild/Enigmatica2Expert#1908]
**Modpack version**
Version 1.82a

**Issue**
The recipe to link 2 omni-directional connectors together to the same group is missing. If you accidentally reset one, it is currently impossible to ever have it be linked with any other connector again, short of crafting 3 new ones out of it with the shaped recipe.

![IDRecipes](https://user-images.githubusercontent.com/16165970/115397556-86bcc400-a1e6-11eb-98e1-69bc287d7c6f.png)

![IngameIDRecipes](https://user-images.githubusercontent.com/16165970/115397563-87edf100-a1e6-11eb-8a89-1d739fde4288.png)

![UnableToCopy](https://user-images.githubusercontent.com/16165970/115397567-88868780-a1e6-11eb-9cff-2830d5630221.png)

I have a hunch this was caused by replacing the recipes to add the Ender Chest and an additional Logic Director to them:

```
# Omni directional
var connector = <integrateddynamics:part_connector_omni_directional_item>;
var part = <integrateddynamics:logic_director>;
var mono = <integrateddynamics:part_connector_mono_directional_item>;
recipes.remove(connector);

recipes.addShaped("part_connector_omni_directional_item_11", connector * 3, [
	[part, <enderstorage:ender_storage>, part], 
	[mono, connector, mono],
	[null, part, null]]);

recipes.addShaped("part_connector_omni_directional_item", connector * 2, [
	[part, <enderstorage:ender_storage>, part], 
	[mono, <integrateddynamics:cable>, mono], 
	[null, part, null]]);
```

**Comment by NillerMedDild** [comment]
Thanks for the report, should be a fairly straight forward fix :)

**Comment by chadwood1999** [comment]
Adding this line to the bottom of scripts/IntegratedDynamics.zs adds the recipe back in.
`recipes.addShapeless("part_connector_omni_directional_item_12", connector * 2, [connector, connector]);
`

**Comment by NillerMedDild** [comment]
Have you verified whether that recipe copies data? :)

**Comment by chadwood1999** [comment]
Yep, I used it earlier today and the group converted as intended

**Comment by NillerMedDild** [comment]
Awesome, thanks!
