### ISSUE TITLE
Issue with current server files (New ones are sorta out)

### ISSUE THREAD

**Issue by knoxfighter** [NillerMedDild/Enigmatica2Expert#1909]
**Modpack version**
1.82a

**Issue**
I had to reinstall my server today and i wanted to run this modpack again. Unfortunatly it is not able to install forge. The installer gets downloaded without any problem, but when executing it, it just prints out the generic error message `A problem installing the server was detected, server install cannot continue`.
What exactly causes this error message and how do i fix it?

What i tried:
- Running the script `ServerStartLinux.sh` inside and outside docker on Debian 10.
- Running `java -jar installer.jar --installServer` inside and outside docker on Debian 10 and on a Windows 7 machine.
- Redownloading everything to make sure the downloads where correct

**Logs**
serverstart.log: https://pastebin.com/FeD8ASMS

installer.jar.log:
```
java.net.preferIPv4Stack=true
Installing server to current directory
A problem installing the server was detected, server install cannot continue
```

**Comment by NillerMedDild** [comment]
I was able to reproduce the issue and am working to fix it.

**Comment by NillerMedDild** [comment]
Fix done! When CurseForge approves, the patched server files will be available here: https://www.curseforge.com/minecraft/modpacks/enigmatica2expert/files/3285831

**Comment by NillerMedDild** [comment]
The updated server files were rejected because some mod versions we're using have been removed.
Use these server files: https://media.forgecdn.net/files/3080/974/Enigmatica2ExpertServer-1.82a.zip
Unzip them and add (overwrite) these 3 files into the folder: [Enigmatica2ExpertServer-1.82a-fix_forge.zip](https://github.com/NillerMedDild/Enigmatica2Expert/files/6369037/Enigmatica2ExpertServer-1.82a-fix_forge.zip)

**Comment by DejonckheereWard** [comment]
> The updated server files were rejected because some mod versions we're using have been removed.
> Use these server files: https://media.forgecdn.net/files/3080/974/Enigmatica2ExpertServer-1.82a.zip
> Unzip them and add (overwrite) these 3 files into the folder: [Enigmatica2ExpertServer-1.82a-fix_forge.zip](https://github.com/NillerMedDild/Enigmatica2Expert/files/6369037/Enigmatica2ExpertServer-1.82a-fix_forge.zip)

Since this issue is still open, i'm not sure about the current state of this, and how much this is related to the existing issue.
I'm currently having issues with the latest server files, when starting the server it tries installing forge, but fails to ping mincraftforge.net, resulting in an error and stopping the script.
When I edited the script to skip the pinging to minecraftforge.net, the installing continued perfectly without issue.
Below is the output of the script when running it.

<details>
  <summary>Server Output</summary>
  
  Spoiler text. Note that it's important to have a space after the summary tag. You should be able to write any markdown you want inside the `<details>` tag... just make sure you close `<details>` afterward.
  
```cmd

*** Loading Enigmatica 2: Expert Server ***
Running Forge 2854 for Minecraft 1.12.2

::::::::::::::::::::::::::::::::::::::::::::::::::::
   Minecraft-Forge Server install/launcher script
   (Created by the "All The Mods" modpack team)
::::::::::::::::::::::::::::::::::::::::::::::::::::

This script will launch a Minecraft Forge Modded server

FOR HELP (or more details);
   Github:   https://github.com/AllTheMods/Server-Scripts
   Discord:  https://discord.gg/FdFDVWb


INFO: Checking java installation...
java version "1.8.0_271"
Java(TM) SE Runtime Environment (build 1.8.0_271-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.271-b09, mixed mode)
Checking if current folder is valid...
Checking for basic internet connectivity...
Checking for forge/minecraft binaries...
FORGE 14.23.5.2854 binary not found, re-installing...
Clearing old files before installing forge/minecraft...
ERROR: Could not reach minecraftforge.net! Possible firewall or internet issue?

**** ERROR ****
There was an Error, Code: "NoInternetConnectivityMinecraftForgeNet"
```
  
</details>

**Comment by NillerMedDild** [comment]
That doesn't sound related tbh, I'm guessing that'll fix itself after a while.

**Comment by S-Explorer** [comment]
> > The updated server files were rejected because some mod versions we're using have been removed.
> > Use these server files: https://media.forgecdn.net/files/3080/974/Enigmatica2ExpertServer-1.82a.zip
> > Unzip them and add (overwrite) these 3 files into the folder: [Enigmatica2ExpertServer-1.82a-fix_forge.zip](https://github.com/NillerMedDild/Enigmatica2Expert/files/6369037/Enigmatica2ExpertServer-1.82a-fix_forge.zip)
> 
> Since this issue is still open, i'm not sure about the current state of this, and how much this is related to the existing issue. I'm currently having issues with the latest server files, when starting the server it tries installing forge, but fails to ping mincraftforge.net, resulting in an error and stopping the script. When I edited the script to skip the pinging to minecraftforge.net, the installing continued perfectly without issue. Below is the output of the script when running it.
> Server Output

i find the same issue, because the  `%ERRORLEVEL% ` not EQU 0 ,whatever ping minecraftforge.net fail or success, so i change the line in 605
```batchfile
IF 0 EQU 0 (
	ECHO INFO: Ping of "minecraftforge.net" Successfull 1>>  "%~dp0logs\serverstart.log" 2>&1
) 
```
than i can start the server !

**Comment by liamferrante** [comment]
> > > The updated server files were rejected because some mod versions we're using have been removed.
> > > Use these server files: https://media.forgecdn.net/files/3080/974/Enigmatica2ExpertServer-1.82a.zip
> > > Unzip them and add (overwrite) these 3 files into the folder: [Enigmatica2ExpertServer-1.82a-fix_forge.zip](https://github.com/NillerMedDild/Enigmatica2Expert/files/6369037/Enigmatica2ExpertServer-1.82a-fix_forge.zip)
> > 
> > 
> > Since this issue is still open, i'm not sure about the current state of this, and how much this is related to the existing issue. I'm currently having issues with the latest server files, when starting the server it tries installing forge, but fails to ping mincraftforge.net, resulting in an error and stopping the script. When I edited the script to skip the pinging to minecraftforge.net, the installing continued perfectly without issue. Below is the output of the script when running it.
> > Server Output
> 
> i find the same issue, because the `%ERRORLEVEL% ` not EQU 0 ,whatever ping minecraftforge.net fail or success, so i change the line in 605
> 
> ```batchfile
> IF 0 EQU 0 (
> 	ECHO INFO: Ping of "minecraftforge.net" Successfull 1>>  "%~dp0logs\serverstart.log" 2>&1
> ) 
> ```
> 
> than i can start the server !

Thank you!
