### ISSUE TITLE
Ultimate control circuit for FREEEE.

### ISSUE THREAD

**Issue by ArmageddonX430** [NillerMedDild/Enigmatica2Expert#191]
#### Issue Description

Plopped my elite control circuit and four atomic alloys on the Actually Additions empowerer.  Suddenly it starts up even though I haven't connected the ultimate energy cube yet!  I'm about to connect it, and the thing finishes.  Zero RF consumed.  I don't think that's supposed to happen.

https://i.imgur.com/ehIswTs.png

#### Modpack version (Use "latest" but only if you WISH TO DIE.)

 1.34

**Comment by NillerMedDild** [comment]
Reported, thank you :)
https://github.com/Ellpeck/ActuallyAdditions/issues/1159

**Comment by ArmageddonX430** [comment]
Really?  That was an AA issue?  I figured the recipe was simply missing an RF amount in E2E.  Man it's hard to determine the culprit sometimes.

**Comment by NillerMedDild** [comment]
It used to work, that helps with troubleshooting quite a bit.
