### ISSUE TITLE
Tinker's Pickaxes completely broken

### ISSUE THREAD

**Issue by Swagbasket** [NillerMedDild/Enigmatica2Expert#1911]
1.82a

I don't really know how to describe this issue because it seems to have no rhyme or reason. An iron pickaxe head can mine anything in the game at a low speed. Replacing the head changes what it can mine, but it does not match up to the WAILA mining level. Pickaxe heads also do not match the mining level that the final pickaxe has. This is gamebreaking

**Comment by NillerMedDild** [comment]
Sounds similar to #1855 #1498 #1849 :)
Additional, if you're accidentally on 1.82 mining levels are broken entirely.
