### ISSUE TITLE
Enigmatica Shader Issue

### ISSUE THREAD

**Issue by JustLiam040** [NillerMedDild/Enigmatica2Expert#1916]
**Modpack version**
1.82a

**Issue**
When using shaders all gui's become blue and transparent. This doesn't seem to be a shader issue as it occurs with whatever shader i use. I have also tried using different versions of optifine and the issue still persists. I have disabled Astrals sky rendering etc as i have heard this can cause issues; and although it did fix a couple issues with the sky the GUI issues still occur.

I've attached a screenshot so you can see what im on about.

![2021-06-04_10 07 36](https://user-images.githubusercontent.com/33065753/120777676-730eb800-c51d-11eb-971c-8f28559fb5b0.png)

**Comment by toastonrye** [comment]
For anyone in the future trying to get shaders to work with this mod pack, this is what worked for me after many hours of Google and testing. I had 2 issues with Optifine shaders, the sky issues and JEI doing weird rendering from certain searches.

The sky:
Astral Sorcery
S:weakSkyRenders <
0

Advanced Rocketry
B:PlanetSkyOverride=false
B:StationSkyOverride=false
B:overworldSkyOverride=false

JEI Search
Animania
B:fancyEggs=false


Video https://www.youtube.com/watch?v=w6l2oYhYLTQ
