### ISSUE TITLE
World Reset

### ISSUE THREAD

**Issue by bevakashaezrot** [NillerMedDild/Enigmatica2Expert#1917]
**Modpack version**
1.82a

**Issue**
Terrain reset to the start of the world, deleting everything that I built instead of blocks such as grass. also should mention this deleted everything i have other a few random structures.

**Logs**
[2021-06-06-3.log.gz](https://github.com/NillerMedDild/Enigmatica2Expert/files/6604370/2021-06-06-3.log.gz)

**Comment by NillerMedDild** [comment]
Damn that sucks, I hope you have a recent backup :(
