### ISSUE TITLE
The mods (except nutrition) aren't there, everything else is

### ISSUE THREAD

**Issue by ZoomGC** [NillerMedDild/Enigmatica2Expert#1918]
**Modpack version**
1.82a

**Issue**
When I try to download the modpack manually from the CureForge website, I look into the mods folder in "overrides" and find only one mod, the nutrition mod, no other mods being installed, the config still there and everything in the config folder, just the mods are missing, and if I try to download it through the CurseForge app then I get an error anywhere between mod 10 and 21, that option being ruled out too, I'm really at a loss and would build the source code but I'm not sure what I'd use, Maven? (I've never used Maven or any source code builders before.

Here is an image of the issue - 
![image](https://user-images.githubusercontent.com/69386185/122092346-b6acd000-ce01-11eb-9bea-6a632d935aad.png)

**Logs**
None

**Comment by ZoomGC** [comment]
![image](https://user-images.githubusercontent.com/69386185/122092281-a563c380-ce01-11eb-82f1-21291d2ffb7a.png)

**Comment by NillerMedDild** [comment]
We recommend that you use the CurseForge App, MultiMC or the GDLauncher :)
The file you downloaded from CurseForge is a manifest that you can give to launchers, the launchers will then install everything required.
