### ISSUE TITLE
Storage Drawers + Vein Miner + Global Trabeller bug

### ISSUE THREAD

**Issue by muniategui** [NillerMedDild/Enigmatica2Expert#1919]
1.82a

In order to reproduce the bug is needed:

Some basic drawers (used like 20 of the 2*2) (they had capacity upgrade 5).
Connect to a drawer controller the 20 storage drawers.
Insert some materials in the drawers.
Then set as the destination of the tool the drawer controller (Global Trabeller).
Use the vein miner on the basic drawers.

Result:

No drawers are dropped nor its content (well got 2 silver out of probably 40k resources)

**Comment by NillerMedDild** [comment]
Hi there, thanks for the report.

To be honest, I don't think this is a bug, and it should be fairly easy to avoid.
