### ISSUE TITLE
Quests that can not be cleared & quests in reverse order

### ISSUE THREAD

**Issue by kuyana** [NillerMedDild/Enigmatica2Expert#192]
#### Issue Description
Quest can not be cleared because enchanced combustion generator (ender io) has been deleted.
In the quest of blood magic there is sacrificial dagger quest next to inspectoris scandalum (blood altar tier 1), but blood is necessary to create inspectoris scandalum, so we need to make sacrificial dagger first.

#### Modpack version (Do not use "latest")
1.34

**Comment by NillerMedDild** [comment]
Woops, I'll get that fixed, thank you!
