### ISSUE TITLE
Extra Utilities 2 "Upgrade Speed" item duplication

### ISSUE THREAD

**Issue by Raifa21** [NillerMedDild/Enigmatica2Expert#1920]
**1.82a**

**I shift clicked 4 upgrade speed items into a magmatic generator(also extra utilities 2) and I shift clicked the item out, and i got the 4 back in my inventory, but 4 was still in the generator. Not visual bug, I relaunched the game several times, and both of them is still in my inv. Also i cant stack them**
<img width="1024" alt="Screen Shot 2021-06-19 at 12 31 13" src="https://user-images.githubusercontent.com/79643312/122632037-3dabc200-d0fa-11eb-8ea9-8a5796c88ff6.png">

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
I cannot reproduce this issue.
