### ISSUE TITLE
Duplication Bug

### ISSUE THREAD

**Issue by JoshieGemFinder** [NillerMedDild/Enigmatica2Expert#1923]
**Modpack version**
1.82a

**Issue**
The command "`/undo_excavation_forced`" doesn't require operator (OP) privileges, meaning duplication of blocks
it also keeps blockdata, meaning duplication from chests

**Comment by JoshieGemFinder** [comment]
it even works with chests

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by JoshieGemFinder** [comment]
Apologies for not seeing (and clarifying) this earlier,  
The issue is it will still restore the blocks even if you drop them out of your inventory before running the command.

Should've listed steps:
1. Excavate blocks
2. Drop items onto floor (or put them into a chest)
3. Run `/undo_excavation_forced`
4. Duplicate blocks (Profit)

**Comment by NielsPilgaard** [comment]
Ahh I see. Not much we can do at this point :P
