### ISSUE TITLE
[Bug] Big Reactors' Reactor don't accept Block of Uranium (IE)

### ISSUE THREAD

**Issue by ReiDaTecnologia** [NillerMedDild/Enigmatica2Expert#1924]
**Modpack version**
1.82a

**Issue**
Sadly, the Immersive Engineering's Block of Uranium can't be used as fuel input for the Big Reactors' reactor because (For some reason) it need to have the "blockYellorium" oredict for it to actually accept.
I don't know if u still accept this type of issue (low priority issue or non-game breaking issue) as i'm not sure what "support status" this modpack is right now. Sorry for the issue if you don't accept this type of issue anymore.

**Logs**
N/A

**Comment by NillerMedDild** [comment]
Thanks for the report, we'll get that fixed :)
