### ISSUE TITLE
Advanced Rocketry links broken in quest book (404)

### ISSUE THREAD

**Issue by BestMod** [NillerMedDild/Enigmatica2Expert#1925]
**Modpack version**
1.82a(latest)

**Issue**
Advanced Rocketry links broken in quest book (404)

**Logs**
N/A

**Comment by NillerMedDild** [comment]
All of them?

**Comment by BestMod** [comment]
[
![image](https://user-images.githubusercontent.com/71246119/124345306-05da5b00-db8d-11eb-94f8-8dfae29eee62.png)
](url)

this is where the ip itself goes to lol
