### ISSUE TITLE
[Suggestion] Disable Cyclic's Sprinkler Animation to increase performance

### ISSUE THREAD

**Issue by ReiDaTecnologia** [NillerMedDild/Enigmatica2Expert#1929]
**Modpack version**
N/A

**"Issue"**
As you probably know, the Cyclic's Sprinkler is incredibly op and helps a lot with MA's crops farming, but to do this you need to use a lot of Sprinklers and it get heavy in performance pretty quickly so as experienced by myself, disabling Cyclic's sprinkler animation increases the overall performance when looking at the direction of the sprinklers.
Config name: SprinklerAnimationsAllowed
Default: true
Suggestion: false

**Logs**
N/A

**Comment by NillerMedDild** [comment]
Will think this over, thanks for the suggestion.
