### ISSUE TITLE
My immortal dog is still alive even after being to turned to stone

### ISSUE THREAD

**Issue by cloviswolf359** [NillerMedDild/Enigmatica2Expert#1930]
**Modpack version**
Curseforge 1.45

**Issue**
I was fighting a gorgon and my dog came to assist me but looked at the gorgon and was turned to stone, like normal. However, my config files have my dog still set as immortal and the dog was spawned using a dog charm from the doggy talents mod. So I dog is now stuck in a basement, made of stone and still wagging its tail. My radar also shows that the dog is still alive as well.

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by NillerMedDild** [comment]
We're aware that mobs sometimes move after being Petrified, nothing we can do about it I'm afraid :(
