### ISSUE TITLE
"Could not find java version installed" 

### ISSUE THREAD

**Issue by DirtyDan21** [NillerMedDild/Enigmatica2Expert#1931]
**Modpack version**
1.82a

**Issue**
When i start the server it comes up with this error 
ERROR: Could not find valid java version installed.
64-bit Java ver 1.8+ is highly recomended. Check here for latest downloads:
https://java.com/en/download/manual.jsp

**** ERROR ****
There was an Error, Code: ""JavaVersionOrPathError""
I have uninstalled all other versions of java except for java 8 and when it still did not work i uninstalled and reinstalled java 8 and it still does not work 

**Logs**
https://pastebin.com/15hnWA6P

**Comment by NillerMedDild** [comment]
Restarting your server/PC ought to fix it, you're most likely missing the environment variable update that comes with Java 8.
