### ISSUE TITLE
[Bug] Beheading does not apply to laser gun if the held in off-hand position

### ISSUE THREAD

**Issue by Linuis12** [NillerMedDild/Enigmatica2Expert#1933]
**Modpack version**
1.82a
**Issue**
Noticed my beheading III laser gun was not giving any wither skulls (1 in 40 kills) when I used it in offhand with food in main hand. After moving it to main hand, I immediately started receiving a skull every other kill. Not sure if other tinkers modifiers such as looting are similarly affected.

**Comment by NillerMedDild** [comment]
I'm afraid there's not much we can do about that, 1.12.2 mod support isn't really a thing anymore 😄 thanks for reporting anyhow.
