### ISSUE TITLE
Duplication Bug Using CarryOn + Unpackagers

### ISSUE THREAD

**Issue by Alec-KB** [NillerMedDild/Enigmatica2Expert#1934]
Modpack version: 1.82a

If you're holding an unpackager using CarryOn, placing it down will place it down but tell you that it experienced an error in placing, so you end up still carrying one, and can repeat this to gain infinite of any recipe pack that's in there

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.
