### ISSUE TITLE
not able to download server "NoInternetConnectivityMinecraftForgeNet"

### ISSUE THREAD

**Issue by LucienOliveira** [NillerMedDild/Enigmatica2Expert#1935]
**Modpack version**
1.82a

**Issue**
I have installed the fresh serverfiles with the 3 fix files but it keeps telling me:

****ERROR****
There was an Error, Code: "NoInternetConnectivityMinecraftForgeNet"

At first i was downloading the server without the fix files and it had the same Error message

**Logs**
(https://github.com/NillerMedDild/Enigmatica2Expert/files/6964948/serverstart.log)

**Comment by NillerMedDild** [comment]
Thanks for the report - Are you still experiencing the issue? This error sometimes happens intermittently.

**Comment by LucienOliveira** [comment]
Sadly yes

**Comment by NillerMedDild** [comment]
Damn :/ could you try with 1.83?

**Comment by LucienOliveira** [comment]
still wont work with or without the fix files gives me the exact same error

**Comment by LucienOliveira** [comment]
```
REM Ping minecraftforge before attempting download
%MC_SYS32%\PING.EXE -n 2 -w 1000 minecraftforge.net | %MC_SYS32%\FIND.EXE "TTL="  1>> "%~dp0logs\serverstart.log" 2>&1
IF %ERRORLEVEL% EQU 0 (
	ECHO INFO: Ping of "minecraftforge.net" Successfull 1>>  "%~dp0logs\serverstart.log" 2>&1
) ELSE (
	ECHO ERROR: Could not reach minecraftforge.net! Possible firewall or internet issue?
	ECHO ERROR: Could not reach minecraftforge.net 1>>  "%~dp0logs\serverstart.log" 2>&1
	SET MC_SERVER_ERROR_REASON=NoInternetConnectivityMinecraftForgeNet
	GOTO ERROR
)
```
Changing "TTL="1 to "time="1 fixes this issue. Windows ping (at least on my machine returns time= instead of TTL. Maybe this is different on other versions of windows?

**Comment by NillerMedDild** [comment]
Which version of Windows do you have?

**Comment by LucienOliveira** [comment]
windows 10 21H1

**Comment by NillerMedDild** [comment]
So am I, it's working flawlessly ^^' You may have firewall issues?

**Comment by Nothing3000** [comment]
Disclaimer: I was previously using Lucien's account to comment on this issue.
I did some further testing and the issue seems to appear when using ping.exe with an IPv6 enabled adapter. When using IPv6 ping does not print a TTL. (No idea why not). Ping can be forced to use IPv4 by passing the -4 flag.
