### ISSUE TITLE
Cannot Use Single Player World on my Server

### ISSUE THREAD

**Issue by YungSchmuel** [NillerMedDild/Enigmatica2Expert#1936]
**Modpack version**
0.5.9

**Issue**
Tried to use Solo World as the world for my Server, Causes Client to say Encrypting over and over and if I click Cancel, it causes the client to freeze and crash

**Logs**
**Multiplayer Log:** 
[latest.log](https://github.com/NillerMedDild/Enigmatica2Expert/files/6965213/latest.log)

**Client Log:** 
[latest.log](https://github.com/NillerMedDild/Enigmatica2Expert/files/6965215/latest.log)

**Comment by NillerMedDild** [comment]
Thanks for the report. Could you please try to delete the icon from the world folder and try again?
