### ISSUE TITLE
Creeper Seeds don't grow in space

### ISSUE THREAD

**Issue by Alec-KB** [NillerMedDild/Enigmatica2Expert#1937]
**Modpack version**
1.82a

**Issue**
Creeper seeds refuse to grow in space. I've tried it on fertilized and non-fertilized farmland, in different areas, etc. Even the Mystical Agriculture watering can can't get them to grow. They grow perfectly fine in the Twilight (other area I've tested). Afaik, it's only creeper seeds, and only in space, as the other MA seeds in my station are growing.

**Comment by NillerMedDild** [comment]
Thanks for the report, would you mind updating to 1.83 and see if that resolves the issue?

**Comment by NillerMedDild** [comment]
Awesome!
