### ISSUE TITLE
Particle effect CTD.

### ISSUE THREAD

**Issue by ArmageddonX430** [NillerMedDild/Enigmatica2Expert#194]
#### Issue Description

Since I have to rebuild my XNet network everytime I log in, I was removing the regular connectors and facades.  Crashed to desktop.  Restarted game.  Tried again, worked.  Tried removing the one advanced connector.  Crashed when attempting to break connector.  Restarted.  Crashed when attempting to break connector.  Restarted and turned off particle effects.  Crashed when attempting to break connector.  Came on here to post the crash report.

#### Modpack version (Do not use "latest")

1.34

#### Crash Report

https://pastebin.com/LGFJeCw7

P.S.: I'm going to see if Mekanism cardboard boxes or creative mode work now.  If they don't I either have to rebuild my base somewhere else, or wait for a fix.

Update: I can move the offending block with a box.  Tried uncovering it and breaking.  CTD.  Will just creative mode destroy the box, and give myself a new advanced connector, box, and facade.

Update 2: This bug seems to not be happening anymore for whatever reason.  I can break facades and connectors freely.

**Comment by NillerMedDild** [comment]
That's.. super weird. The rebuild error happens if a connector on the Controller network is connected to a Mekanism block, I believe.

**Comment by NillerMedDild** [comment]
It has been reported to XNet, btw.
