### ISSUE TITLE
E2E Crashes on startup...

### ISSUE THREAD

**Issue by isakurs** [NillerMedDild/Enigmatica2Expert#1941]
**Modpack version**
1.82a

**Issue**
I installed E2E and played for ~1 hour. I then went to go eat irl and in the time it took me to eat the game had crashed and won't reopen.
*Edit... the only thing I changed about it was adding optifine... could that be it?

**Logs**
[latest.log](https://github.com/NillerMedDild/Enigmatica2Expert/files/7024283/latest.log)

**Comment by Discomanco** [comment]
Well, first step should be to remove Optifine and try again.

**Comment by isakurs** [comment]
That would make sense... I'm gonna try that

**Comment by 1arts** [comment]
same thing is happening to me, removed optifine as well... no luck
