### ISSUE TITLE
Advanced Rocketry machines are invisible

### ISSUE THREAD

**Issue by chadlupkes** [NillerMedDild/Enigmatica2Expert#1943]
**Modpack version**
1.83

**Issue**
The Advanced Rocketry machines have gone invisible in the latest version.  They still work, but something made the blocks disappear.  I tried this with both default and Sphax.

![Screenshot 2021-08-22 170405](https://user-images.githubusercontent.com/2680342/130374446-ddc80a5a-fbe9-4931-b26b-01f2c98cce97.png)
![Screenshot 2021-08-22 170247](https://user-images.githubusercontent.com/2680342/130374447-301bb67e-e3ce-497c-aa1f-ebf2857666f8.png)
![Screenshot 2021-08-22 170442](https://user-images.githubusercontent.com/2680342/130374449-3a8b6725-8d28-4ee4-b0c8-9f006d8869f1.png)

**Comment by NillerMedDild** [comment]
Thanks for the report. Are you using Optifine?

**Comment by chadlupkes** [comment]
No, I don't have that installed.

**Comment by NillerMedDild** [comment]
Damn, that would've made this a lot easier :P I'll try to find out what's going on.
Have you added or removed any mods?

**Comment by chadlupkes** [comment]
No, just did the update to 1.83 to see how well it works.

**Comment by NillerMedDild** [comment]
I can't reproduce this issue - Have you tried breaking and replacing it?

**Comment by chadlupkes** [comment]
Broke and replaced the Lathe, and it looks like I had it turned around.  Now it looks right.
Broke and replaced the Rolling Machine, and the configuration has completely changed for some reason.  Now it looks right.
The Precision Assembler seems to work fine, so I don't think those machine structure blocks are actually invisible, I just don't remember them changing like that.
So, I think we're good.
