### ISSUE TITLE
/dank/null item dupe when placed

### ISSUE THREAD

**Issue by Th1med** [NillerMedDild/Enigmatica2Expert#1945]
**Modpack version**
1.82a

**Issue**
Put an item in the first slot close the dank open it again,pull the item using the GUI place the dank using the feature from DE (default P?)pick it up by right clicking and there you go you can  pull the item again (tested with MK2 dank )

**Comment by NillerMedDild** [comment]
Thanks for the report. I'm afraid there's not much we can do about this, updating the DankNull mod usually doesn't turn it well :P
