### ISSUE TITLE
Advanced Rocketry machines not playing with AE2

### ISSUE THREAD

**Issue by chadlupkes** [NillerMedDild/Enigmatica2Expert#1949]
**Modpack version**
1.83

**Issue**
I've tried an ME Interface on multiple input ports and I've tried an import bus on all different sides of the output port.  No dice.  It's like AE2 can't reach into the inventory of Advanced Rocketry machines.

**Comment by chadlupkes** [comment]
https://youtu.be/HbXHe6T2zJU

**Comment by Deyril** [comment]
I had the exact same issues as chadlupkes when I updated from 1.82a to 1.83. The multiblock structues apparently changed between the version. After rebuilding them they started to interact with AE2 again, well except for the electric arc furnace.

Some multiblock structures dont use the electric motor anymore which made them slower in 1.83.

**Comment by NillerMedDild** [comment]
Ah I see :/ not much we can do about that I'm afraid, sorry for the trouble.
