### ISSUE TITLE
Load into world with previous inventory appearing Post workload Lost

### ISSUE THREAD

**Issue by BaconWorld** [NillerMedDild/Enigmatica2Expert#195]
#### Issue Description
The best way I can explain my issue currently is from the start:
Finishing with collecting my haul from the Nether I returned back to the overworld to add my manyullyn sharpening to my just finished Hammer from tinkers.  I exit the game back to the Menu where hopefully saving progress???. I finish with whatever task I had and returned to game this maybe about 10-15 minutes of Menu screen being on (not exiting minecraft). I returned to the game and find myself several chunks away from my base... ~assuming my previous game load starting area.. with the inventory I had at the time.. all inventory I had before logging out LOST!.

Some of the game progress however had saved since my Mapping progress was still intact and I am assuming my Nether world travel mapping and progress also still saved....

I do not know what more I can do to provide a description for what happened because I am unfamiliar with these sorts of things. It just felt like this problem should not have happened after just logging out of my game????
#### Modpack version (Do not use "latest")
Enigmatica2 expert 1.34
#### Crash Report

[https://pastebin.com/nYWN6UdF]

**Comment by BaconWorld** [comment]
I am unsure if something is wrong with my world entirely now... certain Items I retain and some I end up losing... I believe I need to debug my game entirely now..

https://pastebin.com/RYKZ4TbM 

Enigmatica2 expert 1.34 Twitch App Version 7.5.6786.12 Live
minecraft version: 1.12.2 (modded) forge- 14.23.4.2739

**Comment by NillerMedDild** [comment]
There's nothing in the supplied log that looks off, weird.
You have plenty of space on your PC right?
