### ISSUE TITLE
Weird bug with NaN Hp (immortality + unable to do few things)

### ISSUE THREAD

**Issue by Tosiek99** [NillerMedDild/Enigmatica2Expert#1952]
**Modpack version**
1.83

**Issue**
After getting ANY damage my hp bar is empty, i can't get killed and i can't pickup any items.

**Logs**
Don't have it! But i have record.
https://www.youtube.com/watch?v=mocHZNp73sg

**Comment by Tosiek99** [comment]
Also i can't kill myself with command (/kill).

**Comment by NillerMedDild** [comment]
Please update and see if the issue persists :)

**Comment by Tosiek99** [comment]
Sorry. i'm using 1.83. It's the newest version.

**Comment by NillerMedDild** [comment]
Can you reproduce this issue without items, baubles, backpack etc?

**Comment by Tosiek99** [comment]
I suspect why this is happening. If somebody with healing on laser gun will hit player which is currently doing something in crafting or etc. this bug will occur. I'm not 100% sure, but this happened again.

**Comment by NillerMedDild** [comment]
I'm afraid I can't do anything about that, then :< thanks for the report anyhow.
