### ISSUE TITLE
Advanced Rocketry Satellite Builder Crashes on Build

### ISSUE THREAD

**Issue by SamAugust69** [NillerMedDild/Enigmatica2Expert#1953]
**Modpack version**
1.83

**Issue**
upon pressing the "build" button inside of the satellite builder, game crashes.  The crash doesn't happen unless all the required items shown the screenshot below are present 
![image](https://user-images.githubusercontent.com/43421731/132056153-421b8b96-2666-4ccd-b5b4-9a815d908c8c.png)

**Logs**
[crash-2021-09-01_16.00.44-client(1).txt](https://github.com/NillerMedDild/Enigmatica2Expert/files/7108084/crash-2021-09-01_16.00.44-client.1.txt)
plicable

**Comment by NillerMedDild** [comment]
Thanks for the report! Would you mind updating Advanced Rocketry and Lib Vulpes, and see if that resolves the issue? It should be fixed in the second latest release because of this: https://github.com/Advanced-Rocketry/AdvancedRocketry/pull/2108
