### ISSUE TITLE
[Bug] Advanced Carpenter don't accept Thermal Expansion's Seed oil only Forestry's Seed oil

### ISSUE THREAD

**Issue by ReiDaTecnologia** [NillerMedDild/Enigmatica2Expert#1954]
**Modpack version**
1.83

**Issue**
In the script file of Advanced Carpenter, the input liquid for Impregnated Casing and Sticks is "seed.oil" which is the Forestry's Seed oil. TE's seed oil is "seed_oil", making TE's seed oil incompatible. This become an issue as TE's seed oil recipe is better than Forestry's cuz it gives 50mb per item instead of just 10mb as Forestry's does. You can give it support for both or unify, your choice man.

**Logs**
N/A

**Comment by ReiDaTecnologia** [comment]
hm, i'm trying to add support for both in my custom modpack (Which have ur modpack as the base) on my own and with my level of knowledge i just couldn't do it so i had to replace the Forestry's seed oil with the TE one sadly. Sorry if you didn't do it before because it is impossible or just not worth it.

**Comment by NillerMedDild** [comment]
Iirc I didn't want them to be interchangeable :P
