### ISSUE TITLE
Is there a way to repair Climbing Gloves?

### ISSUE THREAD

**Issue by chadlupkes** [NillerMedDild/Enigmatica2Expert#1955]
**Modpack version**
1.83

**Issue**
Climbing Gloves don't seem to repair with Mending.  And I'm not able to find the material that I should use to repair them manually.  What am I missing?

**Comment by theboo** [comment]
XP anvil or magma anvil from cyclic(I think?) can repair most anything with durability... Tho this is probably a better question for the discord server

**Comment by chadlupkes** [comment]
The Powered Diamond Anvil works, thanks!

**Comment by theboo** [comment]
ah yes, that's what it's called... been a minute haha

**Comment by chadlupkes** [comment]
Also needed it to repair the Automatic Torch.
