### ISSUE TITLE
grave was not created

### ISSUE THREAD

**Issue by Riesenpilz** [NillerMedDild/Enigmatica2Expert#1958]
Modpack version: 1.83

I died in the deeper dark of the dark, but the Gravestone wasnt created. In the deathlog stands, that the grave is at 0; 0; 0, but that wasnt the case.

**Comment by NillerMedDild** [comment]
That sucks :/ Did you look both up and down from those coordinates as well, or the place your death waypoint was set?
Also, you can restore it with commands iirc - `/tmg_restore [player] <timestamp>`
