### ISSUE TITLE
Mystical Agradditions Tier 6 Inferium Seeds Do Not Work With Garden Cloche

### ISSUE THREAD

**Issue by BlueTRaven** [NillerMedDild/Enigmatica2Expert#196]
#### Issue Description
As the title says, the tier 6 Inferium seeds (which are from the addon mystical agradditions, not mystical agriculture) do not work in the garden cloche, as well as the phytogenic insolator. They can only be grown manually on soil.
Unless I'm missing some sort of crux like the nether star/awakened draconium/dragon egg ones, this probably isn't intended behavior, as every other seed I've tried works.

#### Modpack version (Do not use "latest")
1.34

**Comment by NillerMedDild** [comment]
I've looked into it - The compatibility has been requested, but people seem reluctant to add it.

**Comment by winauer** [comment]
Tier 6 Inferium seeds need an Insanium Block instead of dirt in the cloche.

**Comment by NillerMedDild** [comment]
Sigh, I should've guessed that. Thanks winauer :)
