### ISSUE TITLE
Using using max power time in a bottle on furnace powered by external heater deletes the items

### ISSUE THREAD

**Issue by Scruffular** [NillerMedDild/Enigmatica2Expert#1962]
### Modpack Version

1.82a

### Describe your issue.

Clicking 6 times with a time in a bottle on a furnace powered by external heater deletes the item. Not even a visual bug. Straight up deletes them. (Didn't test if it deleted them with furnace with regular fuel. Assume something like that wouldn't slip through the cracks though)

### Have you modified the modpack?

Yes

### User Modifications

Optifine

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NillerMedDild** [comment]
I'm afraid there's nothing we can do about that, mod devs generally don't accept bugs caused by tick acceleration (like the time in a bottle)

**Comment by Scruffular** [comment]
Understandable. Still a bummer I can't speed up the furnaces though lol.
