### ISSUE TITLE
using the rftools hand held teleporter leads to the world acting oddly

### ISSUE THREAD

**Issue by croftyraider** [NillerMedDild/Enigmatica2Expert#197]
Using 1.34

If I use rftools to teleport around in the same dimension, all is well. If I go between dimensions (this time from the End to the Overworld) then I arrive fine, but machines act oddly. Redstone doesn't fire properly (e.g. pressure plate next to a gate), trying to go through a nether portal does nothing, etc.

I think the world stops "ticking" or something.

**Comment by NillerMedDild** [comment]
I believe you, the player, is actually considered logged off for some reason. Could you supply your latest.log please?

**Comment by croftyraider** [comment]
Here you go - I tried repeating it from the nether back to the overworld but in a single test it didn't fail. However, from the end back to the overworld did fail.


[latest.zip](https://github.com/NillerMedDild/Enigmatica2Expert/files/2285178/latest.zip)

**Comment by NillerMedDild** [comment]
I think I've found the offending line:
`[18:12:48] [Server thread/WARN] [net.minecraft.world.WorldServer]: Force-added player with duplicate UUID a862b98a-b2d5-4d87-af6e-9632dd7e094b`

**Comment by croftyraider** [comment]
Question I just now thought of - is having that UUID in there a good thing? If not can you delete it and the file I uploaded? Thanks

**Comment by NillerMedDild** [comment]
I personally wouldn't worry about it, but I removed it :)

**Comment by croftyraider** [comment]
Thanks :) I didn't do any research on the topic but hopefully it's not an issue in the first place.

**Comment by croftyraider** [comment]
Any fix for this? Stale bot closed it for some reason

**Comment by NillerMedDild** [comment]
Nothing yet, other than relogging :/

**Comment by NillerMedDild** [comment]
I don't think this issue will ever get fixed to be honest. It appears some mod is interpreting moving from The End to another dimension without going through the portal equals death, and is thus desyncing the player, I think. It could be several mods with the same logic aswell.

**Comment by NillerMedDild** [comment]
It is not limited to RFTools, Just Enough Dimensions teleporting does it too, and Astral Sorcery and Ender Utilities have the issue too.  I'm aware that is the issue, as I clearly state in comment 4.

**Comment by NillerMedDild** [comment]
In addition, it seems that this issue is actually fixed in a pull request:
https://github.com/McJtyMods/McJtyLib/pull/86

**Comment by douglasg14b** [comment]
@NillerMedDild  I'm not trying to argue, just applying extra critical thinking to the problem, and not dismissing it early.

Saw your reply, leaving the text below as it's still relevant.

________________

*Something* is happening that is fairly unique to RFTools (or the libraries it uses), and a select few mods, but doesn't seem to be a problem for most. This makes it a solvable problem, as others have been here before. Either other mods have either solved this already, go about moving the player in a different way, have avoided a common pitfall that caused the issue, or use a different library for player movement that doesn't have the issue.

________________

It's great that there is a pull request to resolve the problem, I just wanted to address the hand-waving "someone elses problem" that seemed to have been occurring with these issues by presenting some reasoning. As a software dev myself, it doesn't seem like good stewardship to dismiss what appears to be an ongoing problem practically unique to RFTools.

**Comment by NillerMedDild** [comment]
The reason I practically abandoned it, is because it has been reported appropriately, and there is no further action I can take to rectify the issue.
