### ISSUE TITLE
Forestry Carpenter Does not make Impregnated Casing 

### ISSUE THREAD

**Issue by DefaultUSERNAME9** [NillerMedDild/Enigmatica2Expert#1974]
### Modpack Version

 Enigmatica 2 Expert 1.83

### Describe your issue.

I was playing Enigmatica 2 expert and suddenly forestry carpenter does not craft impregnated chest even if i put more than enough seed oil.

Some Pictures
![2021-11-28_11 57 08](https://user-images.githubusercontent.com/92053557/143729078-1525e9ee-699d-4819-88c8-53e04d268967.png)
![2021-11-28_12 02 35](https://user-images.githubusercontent.com/92053557/143729089-2faf8d78-1f9d-4934-8516-60a0e7faac1e.png)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NillerMedDild** [comment]
Restarting your game fixes this :)
