### ISSUE TITLE
Lighting Glitch in some Blocks

### ISSUE THREAD

**Issue by DefaultUSERNAME9** [NillerMedDild/Enigmatica2Expert#1975]
### Modpack Version

 Enigmatica 2 Expert 1.83

### Describe your issue.

Some Blocks have black colored textures  I think it is because of Optifine or something I don't know
![2021-12-01_22 23 01](https://user-images.githubusercontent.com/92053557/144252379-a6b53676-2660-4fdc-8efc-7ebdd39a3877.png)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NillerMedDild** [comment]
Yeah if you have optifine then that is very plausible :P we can't do anything about that I'm afraid
