### ISSUE TITLE
Liquid Dictionary Converter and Rocket Fuel

### ISSUE THREAD

**Issue by chadlupkes** [NillerMedDild/Enigmatica2Expert#1978]
### Describe your suggestion

I made WAY too much Ender IO Rocket Fuel, and I would like to convert it to Advanced Rocketry Rocket Fuel.  I wish the Liquid Dictionary Converter could do that.  Maybe set it so that you have to put a bucket of each into the machine before it works, just so we can be sure that we've gone through the steps to create each version on our own first?

### Why would you like this added/changed?

I understand needing to build the machines to qualify, but once we do that, we should be able to create the fuel via the easiest method.  Just an idea.

**Comment by NillerMedDild** [comment]
Thanks for the suggestion, but I think those two liquids are too different to varrant conversion between them.
