### ISSUE TITLE
Void ore miner tier 6 doesn't generate most resources that previous tiers produce

### ISSUE THREAD

**Issue by winauer** [NillerMedDild/Enigmatica2Expert#198]
#### Issue Description

The void ore miner tier 6 doesn't generate:
* Aquamarine Shale
* Coal Ore
* Iron Ore
* Redstone Ore
* Lapis Ore
* Copper Ore
* Tin Ore
* Silver Ore
* Lead Ore
* Uranium Ore
* Certus Quartz Ore
* Cinnabar Ore
* Nickel Ore
* Apatite Ore
* Black Quartz Ore
* Osmium Ore
* Prosperity Ore

All of those are generated by previous tiers of void miners.

#### Modpack version (Do not use "latest")

1.34

#### Crash Report

None

**Comment by jmarler** [comment]
A tooltip indicating the change would be very helpful here. Essentially, we need to keep a Tier 5 up and running next to a Tier 6 to continue to harvest basic ores.

**Comment by NillerMedDild** [comment]
Good idea :)
