### ISSUE TITLE
Geiger Counter Doesnt show up on JEI

### ISSUE THREAD

**Issue by Us3rNqmed** [NillerMedDild/Enigmatica2Expert#1980]
### Modpack Version

1.83

### Describe your issue.

despite the geiger counter item not showing up on JEI, it is craftable and it exists

Mod: NuclearCraft

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NillerMedDild** [comment]
Thanks for the report. This is intended, because radiation is turned off :)
