### ISSUE TITLE
Game crashing

### ISSUE THREAD

**Issue by iOkamii** [NillerMedDild/Enigmatica2Expert#1981]
### Modpack Version

1.8.3

### Describe your issue.

the game is crashing on launch, i've tried reinstalling java and some other stuff but it didn't work.

I have 8 ram and java 8 is at version 311

### Crash Report

https://gist.github.com/iOkamii/2ea7f7f2ba0c6ead5e1c2e1b7fbf21c1

### Latest Log

https://gist.github.com/iOkamii/2740efb2b6ed2b54224193b859eff1ce

### Have you modified the modpack?

No

### User Modifications

none

### Did the issue happen in singleplayer or on a server?

Both

**Comment by NillerMedDild** [comment]
Your java seems to be correct, but installed in the wrong folder. I recommend you try reinstalling again, make sure it's 64bit java

**Comment by iOkamii** [comment]
as well? I already installed java several times

**Comment by NillerMedDild** [comment]
Java is installed in the wrong folder, so the install probably went wrong 🤔
