### ISSUE TITLE
1.34 Akashic Tome not accepting all in game books

### ISSUE THREAD

**Issue by ZephyrWindSpirit** [NillerMedDild/Enigmatica2Expert#199]
#### v.1.34

Steps to reproduce:
1. Acquire Astral Sorcery book.
2. Acquire Akashic tome.
3. Try to craft together.
4. FAIL.

Please consider fixing this, and thank you for your time. 
~ZephyrWindSpirit

**Comment by NillerMedDild** [comment]
Thanks for the report, I finally got it fixed :)
