### ISSUE TITLE
Stuck at downloading

### ISSUE THREAD

**Issue by L3Chuuck** [NillerMedDild/Enigmatica2Expert#20]
#### Issue Description
Starting the server with the bat file nothing changed in the settings, stuck at downloading.
#### Modpack version (Do not use "latest")
Enigmatica 2: Expert 1.15
#### Your most recent log file where the issue was present

https://pastebin.com/5mv2kRCn

**Comment by L3Chuuck** [comment]
You can close this thread.

**Comment by NillerMedDild** [comment]
Did you get it to work?
