### ISSUE TITLE
[Skyblock] [Thaumcraft] Make Crimson Cult armor craftable / Crimson Knights spawnable

### ISSUE THREAD

**Issue by hron84** [NillerMedDild/Enigmatica2Expert#201]
For Thaumcraft progression at some point you will need the Crimson book (I don't recall the real name) that is dropped by Crimson Knights / Cultists. As Crimsons rarely spawns and especially rarely spawns on Skyblock, it would be good if it could be craftable.

Also Crimson Cult / Knight armors are very nice and it would be a good change it could be crafted somehow. Basically, they're same as iron-level armor pieces with no special trait/effect so maybe they could be crafted independently of Thaumcraft Gate. 

Alternatively, make Crimson Armor wearable by other mobs, like how RSA helmet/armor works.

**Comment by NillerMedDild** [comment]
You're on the wrong issue tracker, please open this issue here: https://github.com/Discomanco/Enigmatica2ExpertSkyblock/issues
