### ISSUE TITLE
[Suggestion] A few small mods

### ISSUE THREAD

**Issue by zOwenn** [NillerMedDild/Enigmatica2Expert#202]
Any chances that the Tinkers training dummy mod (MmmMmmMmmMmm) could be thrown in, its only a light thing for the sake of finding the numbers behind TCon weapon damage with the wide range of traits available to mess with. Also, Dirt2Path would be a welcome addition to make it so you can... make paths from dirt.

I understand the mod list is already quite long, but these could be nice additions.

**Comment by NillerMedDild** [comment]
Sure, I'll add Dirt2Path in the next update.

I believe Cyclic is working on a Training Dummy, so I'll hold off on adding MmmMmmMmmMmm :)
