### ISSUE TITLE
Enigmatica 2 Expert Skyblock v.1.3a

### ISSUE THREAD

**Issue by Wol3eb** [NillerMedDild/Enigmatica2Expert#203]
#### Issue Description
In game quests are randomly completing (by themselves). 
#### Modpack version (Do not use "latest")
Enigmatica 2 Expert Skyblock     v.1.3a

**Comment by NillerMedDild** [comment]
This isn't the Skyblock issuetracker.

However, that bug is known, and it's not looking like we're gonna get a fix I'm afraid.

You can use the command `/bq_admin default load` to refresh quests, and `/bq_admin edit` to reset their progress.
