### ISSUE TITLE
can't put saplings into the gendustry dna extractor

### ISSUE THREAD

**Issue by croftyraider** [NillerMedDild/Enigmatica2Expert#205]
1.24 of your pack

According to the various wiki's I looked at, I should be able to put in saplings into the dna extractor but it doesn't work. One of the premises early in the forestry chapter is that I would NOT have to mess around with bee's and I would really rather not.

Suggestions?

**Comment by croftyraider** [comment]
Typo - 1.34 of your pack, sorry!

**Comment by NillerMedDild** [comment]
You need to convert them to Forestry saplings, by analyzing them with the Forestry analyzer. You need some sort of honey drop to power it. 

You can't avoid bees entirely, but you don't have to breed them.

**Comment by croftyraider** [comment]
Tou can close this issue - turns out finding a forestry maple tree did the trick - my forestry farm is growing them and I'm getting plenty of saplings now... maybe that could go into your quest line or tips list at some point? just a thought :)

**Comment by NillerMedDild** [comment]
I may get around to it :)
