### ISSUE TITLE
I need help

### ISSUE THREAD

**Issue by Drak0necal** [NillerMedDild/Enigmatica2Expert#206]
plz I need your help
after I updated the pack my world was lost
I have all of my items when I logged off 
but I respawned on the original tree
and do do not have a single back-up

**Comment by NillerMedDild** [comment]
You can find backups in the backup folder of your instance.

**Comment by croftyraider** [comment]
Lately when the pack updates it makes a new folder (some change in the Curse launcher?) - so I've had to copy over my world save and my journeymap data.

**Comment by Drak0necal** [comment]
1. There are no back up folders in my save and after logging in the first
time after the thing happened I had all of my stuff it is just the world
and the map

2.every thing happened randomly that I could not of make a backup
When I finished playing I quited the world then the game then my PC
And when I logged on the second day my world was reset but I had my items

**Comment by NillerMedDild** [comment]
Not in your save, in the root folder of your instance.

**Comment by NillerMedDild** [comment]
Here by default: `C:\Users\[Username]\Documents\Curse\Minecraft\Instances\Enigmatica 2 Expert\backups`

**Comment by Drak0necal** [comment]
I do not have this folder ... I had the same problems with other packs but
I had backups but here I do not

**Comment by NillerMedDild** [comment]
Oh you're in the wrong issue tracker. I'm afraid versions below 1.3 don't make backups. If you have a backup, it will be in the Saves folder.
