### ISSUE TITLE
Mechanical User + Watering can = I broke it

### ISSUE THREAD

**Issue by JakeOTwitch** [NillerMedDild/Enigmatica2Expert#21]
#### Issue Description
Using a watering can in a mechanical user in a claimed chunk causes the game to crash and will crash on startup.
#### What you expected to happen
The mechanical user to water the crops.
#### Modpack version (Do not use "latest")
Version 1.18
#### Your most recent log file where the issue was present
Server side, ask Jester
[pastebin/gist/etc link here]

**Comment by NillerMedDild** [comment]
A recent change in FTBUtilities changed how Fake Players worked in claimed chunks. You will need to either trust the fake player block, called something like "Fake Player ExU", or unclaim the chunk.

Sorry for the inconvinience.
