### ISSUE TITLE
Question: Integrated Dynamics World Block Importer

### ISSUE THREAD

**Issue by scotty9090** [NillerMedDild/Enigmatica2Expert#210]
Pack Version:  1.34

Is there anything in this pack that may be preventing an Integrated Tunnels World Block Importer from breaking blocks that require a pick?  Here's what I'm encountering:

Works with Sand, Livingwood, Dirt, Clay - i.e. things that require something other than a pick.
Does not work with Cobble, Livingrock, or any other stone like block regardless of harvest level.

I've used these with no problems in other packs which is why I'm asking.  If this is something I need to report on the mod's page, please let me know.

EDIT: An Actually Additions Auto Breaker won't break Livingrock either, so I don't think it's Int Tunnels that is the problem.

**Comment by NillerMedDild** [comment]
The harvestlevels are custom, I imagine the Auto Breaker and World Block Importer have a harvestlevel of 0. That can't be changed I'm afraid.

**Comment by NillerMedDild** [comment]
Several block breakers work, but a Mechanical User with a Pickaxe with the appropriate level is the most reliable.
