### ISSUE TITLE
Tinker I/O and Extra Utilities crash (TIO dev already working on it.)

### ISSUE THREAD

**Issue by ArmageddonX430** [NillerMedDild/Enigmatica2Expert#212]
When you connect an ExU2 transfer pipe to a Tinker I/O smart output the game crashes.  The Tinker I/O dev is aware of this and is remaking Tinker I/O from scratch in hopes to resolve this and other issues.  I am merely adding this issue here to notify you of the current situation, and possibly nudge you to update the pack once the new version becomes available.

#### Modpack version (Do not use "latest")
1.34

**Comment by NillerMedDild** [comment]
I am aware, it was reported months ago iirc, but thank you :)
