### ISSUE TITLE
Crash on pressing U

### ISSUE THREAD

**Issue by DanielSchuerhoff** [NillerMedDild/Enigmatica2Expert#215]
#### Issue Description
When pressing U (in JEI) on gold pressure plate, I experience crash to desktop. This can be replicated without Optifine. This is similar to #166 but different. It was recorded with the TinkerIO mod removed (which causes #166).

When removing RandomThings as well, this bug does not occur and the game seems to run fine.

#### Modpack version (Do not use "latest")
Modpack: 1.45
Forge: 14.23.4.2739

#### Crash Report
https://pastebin.com/Sji9C57h

**Comment by NillerMedDild** [comment]
This is a known issue, but thank you for reporting it anyway :)
