### ISSUE TITLE
Two mod Request and a config suggestion.

### ISSUE THREAD

**Issue by Trinsdar** [NillerMedDild/Enigmatica2Expert#216]
[Wolf armor and storage](https://minecraft.curseforge.com/projects/wolf-armor-and-storage) and [Demagnetized](https://minecraft.curseforge.com/projects/demagnetize) are the two mods. Demagnitzed adds a block that prevents magnets from working in it's range like the solognolia but unlike the solognolia also has a filter. Wolf armor ads armor for wolves and would be really useful since the mobs in this pack are really tough.

The config suggestion was to add animania random eggs to the market for cows, sheep, pigs, chickens, and rabbits or add a crafting recipe for them using vanilla spawn eggs, such as cow to random cow.

**Comment by NillerMedDild** [comment]
The Animania Random Spawn Egg already has a recipe, you'll have to try your luck with that :)

I see no need for the wolf mod. I may add Demagnetise :)

**Comment by Trinsdar** [comment]
woops did not see the recipe for random animal spawn eggs.
