### ISSUE TITLE
Player Simulator > Autonomous User recipe conflicts with Player Simulator clearing recipe

### ISSUE THREAD

**Issue by triacontakai** [NillerMedDild/Enigmatica2Expert#217]
#### Issue Description
As the title says, attempting to craft an autonomous user by putting a player simulator into the crafting table does not work as expected:
JEI:
![image](https://user-images.githubusercontent.com/31161627/44494557-3f976300-a63a-11e8-90bb-f82272c3124b.png)
Reality:
![image](https://user-images.githubusercontent.com/31161627/44494609-6b1a4d80-a63a-11e8-94a4-b676536e4156.png)
#### Modpack version (Do not use "latest")
1.34

**Comment by NillerMedDild** [comment]
Woops, I'll get that fixed, thank you for the report :)
