### ISSUE TITLE
Unable to break cobwebs with shears

### ISSUE THREAD

**Issue by Trinsdar** [NillerMedDild/Enigmatica2Expert#218]
#### Issue Description
When I try to break cobwebs with shears it acts like trying to break bedrock, meaning I can not get cobwebs unless I have a sword with silk touch.
#### Modpack version (Do not use "latest")
1.34
I know there was a recent update to the pack; however I haven't gotten around to updating and I don't think much has changed that would affect this.

**Comment by NillerMedDild** [comment]
I'll try to fix this, but I'm a bit doubtful I can to be honest.

**Comment by NillerMedDild** [comment]
It turned out to be easy, Shears now silk-touch break Cobweb.
