### ISSUE TITLE
Some progression broken by mob drops

### ISSUE THREAD

**Issue by LumberWizard** [NillerMedDild/Enigmatica2Expert#219]
#### Issue Description
It is possible to obtain the NanoSuit, Flux Infused Armor, and QuantumSuit very early on from mob drops. Using the Arc Furnace, it is also possible to get superium and elementium (and I assume supremium and terrasteel as well, though I haven't ran into those yet) quite early on. The MFSU or the Charge Pads from Mekanism also aren't that hard to make in order to charge the armor.

I think it is also possible to get Tinkers' weapons with the prosperous modifier early on and get prosperity shards much earlier than intended, but I don't recall if I did get any.

#### Modpack version (Do not use "latest")
1.35

**Comment by NillerMedDild** [comment]
All of this is intended behaviour.
