### ISSUE TITLE
Quantum Compressor break after crafting one singularity

### ISSUE THREAD

**Issue by codeka** [NillerMedDild/Enigmatica2Expert#220]
#### Issue Description
After a quantum compressor crafts one singularity, they break, They'll continue to show "x/10,000" items in their GUI, and once they hit the 10,000 mark again, they'll show progress as if they're crafting something, but then they just end up eating the items and nothing comes out. The hovering singularity that *should* be visible above them dissappears, too.

![2018-08-24_07 05 29](https://user-images.githubusercontent.com/1569910/44589121-85544880-a76c-11e8-9487-4aae54a5e761.png)

![2018-08-24_07 05 27](https://user-images.githubusercontent.com/1569910/44589127-88e7cf80-a76c-11e8-9ef9-3552406f396d.png)

I imagine this is a bug in the extended crafting mod...

#### Modpack version (Do not use "latest")
1.35

**Comment by codeka** [comment]
BTW, broke some time between 1.33 and 1.35, I skipped 1.34 so not sure if it was there. I see the last update to Extended Crafting was [Aug 12](https://minecraft.curseforge.com/projects/extended-crafting/files). I'll try reverting to the previous version when I get home to see if that was the culprit.

**Comment by NillerMedDild** [comment]
Thanks for the report :)
