### ISSUE TITLE
Cant create item (Carpenter, Forestry)

### ISSUE THREAD

**Issue by mal0znaal** [NillerMedDild/Enigmatica2Expert#2203]
### Modpack Version

1.90h

### Describe your issue.

Im running own E2E server on Ubuntu Server. Playing with my friend
In early game we couldn craft Carpenter block from Forestry (while playing on server)
But in singleplayer game i can craft Carpenter, even without completing quests, just giving out the necessary items.

![2024-10-19_16-24-41](https://github.com/user-attachments/assets/d7a311b4-fa51-4090-9a89-61db4074a5e2)

As you can see, the recipe is laid out correctly, but I cannot pick up the item

### Crash Report

no

### Latest Log

https://gist.github.com/DoggerHou/aabf0764c09a62fe97970e51ca0a5f19

### Have you modified the modpack?

No

### User Modifications

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by mal0znaal** [comment]
UPD:
Reinstalled E2E server (clean installation from git) and launched a new world, same issue

Also, when I transferred the world from the server to a single player game, I managed to create a carpenter

**Comment by HeatherComputer** [comment]
This implies a botched e2e installation on the server. You're missing scripts that you should have.

How did you install it exactly?

**Comment by mal0znaal** [comment]
> How did you install it exactly?

git pull from this repository
setup.sh to download mods
ServerStartLinux.sh to start server


UPD 1
just started the server from CurseForge server files, it seems to work properly
Any tips how to correctly transfer the old world to a new server?

**Comment by HeatherComputer** [comment]
That's an unconventional method - and not the intended one.

There's a server pack attached to each release on curseforge. Download it, extract it and run the Linux startup script.

**Comment by HeatherComputer** [comment]
> Any tips how to correctly transfer the old world to a new server?
> 
You can just copy the world over, but I'd advise against it - there's no telling what else was broken.

**Comment by mal0znaal** [comment]
I really don't want to start over......
I take it that setup.sh loads files for the old version?

If yes, can you tell me - for which one, if suddenly the world breaks down...

**Comment by HeatherComputer** [comment]
I sadly can't tell you exactly what was broken, all we know is that forestry was.

If you want to keep the same world, do - I wouldn't expect it to suddenly break down or anything like that.
