### ISSUE TITLE
Infinity booster card/ dimensional card wont work

### ISSUE THREAD

**Issue by mushulaymi** [NillerMedDild/Enigmatica2Expert#2204]
### Modpack Version

2.4

### Describe your issue.

I can put one of the cards in the access point but whenever i go beyond 150 blocks it says "wireless network cannot be found" i made another world in creative and tried it,it worked perfectly fine 

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by HeatherComputer** [comment]
Not a bug. You just forgot to chunkload your network.
Using ftbchunks (the map in the top left of your inventory) is the best way to do it. Click to claim, then shift+click to chunkload.
