### ISSUE TITLE
1.35 Bonemeal/Fertilizers no longer work on crops/pams fruit

### ISSUE THREAD

**Issue by ZephyrWindSpirit** [NillerMedDild/Enigmatica2Expert#221]
Modpack version 1.35
I'm reaching my wit's end on searching for why this is happening. 
In the latest (1.35) version of Enigmatica2Expert, bonemeal and forestry fertilizer no longer work to grow crops and pam's harvestcraft fruit/crops. 
Just grass. I'm opening up my 1.34 client on multimc to see if that is still a thing. But from my novice config digging, I'm not finding any reasons on why the crops no longer grow properly. 

I'll return with my findings of 1.34.

Repeatable in both single player and multiplayer. 
1. plant crop on farmland/fertilized dirt/fertile soil/any farmland block.
2. right click with bonemeal.
3. Try again when it fails and does nothing.
4. An attempt on pam's fruit, fail.

**Comment by ZephyrWindSpirit** [comment]
1.34 fertilizing and bonemealing crops works as normal.

**Comment by NillerMedDild** [comment]
Fixed in dev: https://minecraft.curseforge.com/projects/pams-harvestcraft/files/2607341
