### ISSUE TITLE
Extreme Reactor controller recipe broken

### ISSUE THREAD

**Issue by LumberWizard** [NillerMedDild/Enigmatica2Expert#222]
#### Issue Description
The extended crafting recipe in the basic crafting table calls for a Fission Controller with registry name "nuclearcraft:fission_controller_new_idle", while the craftable block is "nuclearcraft:fission_controller_new_fixed". I am unsure if there is a way to obtain the former as of right now.

#### Modpack version (Do not use "latest")
1.35

**Comment by NillerMedDild** [comment]
Huh, I wonder when that changed. Thanks for the report!
