### ISSUE TITLE
Erreur del modpack

### ISSUE THREAD

**Issue by Nicocraft05** [NillerMedDild/Enigmatica2Expert#223]
#### Modpack version (Do not use "latest")
![11111](https://user-images.githubusercontent.com/42539799/44642129-14f73280-a9cb-11e8-9180-ae5ab5b902c4.png)

#### Crash Report

[pastebin/gist/etc link here]

**Comment by TheLostInPlace** [comment]
IIRC Forge version 2750 specifically has been targeted by some anti-viruses as a virus for some odd reason. If you're using an antivirus and it's active while you are downloading, I'd suggest try turning it off and repeat the download.

**Comment by Nicocraft05** [comment]
no antivirus lol

**Comment by NillerMedDild** [comment]
Not even Windows Defender? It's default on Windows 10.

**Comment by Nicocraft05** [comment]
no 2 people same problem

**Comment by NillerMedDild** [comment]
You can download the server files, and manually update with those. You will need forge 2751

**Comment by Nicocraft05** [comment]
it's goog thanks
