### ISSUE TITLE
Strange crash bug

### ISSUE THREAD

**Issue by LumberWizard** [NillerMedDild/Enigmatica2Expert#224]
#### Issue Description
My server crashes randomly, happened twice already. Both times only 1 player was connected.
The player was using an Extra Cells 2 wireless terminal thingy, and there were a bunch of machines running; a lot from Mekanism and IC2, and a few from Industrial Foregoing, Thermal Expansion, RFTools, and Actually Additions, as well as an active AE2 network and a few active XNet setups.

The player was using his Wireless Terminal thingy from Extra Cells 2, and it disappeared from his inventory after the crash.

#### Modpack version (Do not use "latest")
1.35

#### Crash Report
Two days ago - https://pastebin.com/WUwXibqR
Today - https://pastebin.com/1bPAtgxs

**Comment by NillerMedDild** [comment]
It seems your player has something in his AE system that has waaay too much data. May I see a screenshot of his terminal?

**Comment by LumberWizard** [comment]
There's a lot of stuff in the ME system, do you want everything, or just anything we suspect has a lot of NBT tags?

**Comment by NillerMedDild** [comment]
Just take in out of the system all together preferably :b 
Seems linked to this: https://github.com/p455w0rd/WirelessCraftingTerminal/issues/280

**Comment by LumberWizard** [comment]
That must explain why he caused 2 crashes with the same ME system and I never did - because I don't have auto search enabled! I'll upload some screenshots tomorrow (UTC).

**Comment by NillerMedDild** [comment]
Cool :)

**Comment by LumberWizard** [comment]
Ah - but the terminal we're using is the wireless universal terminal from Extra Cells 2, not the Wireless Crafting Terminal.

**Comment by NillerMedDild** [comment]
D'oh, my bad.

**Comment by NillerMedDild** [comment]
I believe ExtraCells 2 is being written into AE2, so I suggest either avoiding the ExtraCells terminals for now, or simply toggle auto search off, and cross your fingers that fixes it :D

**Comment by p455w0rd** [comment]
yeah..EC2 is in a weird state with AE2 RV6 not being released yet..once AE2 RV6 releases, I'll be able to overhaul EC2..for now..I'd say just remove the mod tbh..would be a lot less headache on us mod/pack devs #BlameAE2 lol

**Comment by LumberWizard** [comment]
We were finally able to successfully and reliably replicate it! @p455w0rd just making sure you can read this comment - the crash happens when you open the wireless crafting terminal, and press the number key that corresponds to its hotbar position while mousing over one of the crafting grid slots.

**Comment by p455w0rd** [comment]
thank you @LumberWizard - I will work on this tomorrow for both RV5 and RV6 WCT =D - I'll do it on stream if you wanna come watch..I don't have a schedule yet, so you'd just have to watch my twitter for when I go live
