### ISSUE TITLE
Liquid Cross-mod Compatibility

### ISSUE THREAD

**Issue by LumberWizard** [NillerMedDild/Enigmatica2Expert#225]
Those are, liquid hydrogen, liquid oxygen, liquid sulfur dioxide, liquid sulfur trioxide, sulfuric acid, sodium/molten sodium (I think it should be oredicted but I'm not sure), liquid deuterium, liquid tritium, and lithium/molten lithium. There also isn't a crafting recipe for heavy water from any mod in JEI (IC2 or Mekanism) but I'm not sure one is needed.

**Comment by LumberWizard** [comment]
After further testing, it appears that the problem is only with tritium, deuterium, and sulfur products.

**Comment by NillerMedDild** [comment]
There is no such thing as oredict for Gases or Fluids I'm afraid, although that would be very convinient. It's also worth mentioning that liquids and gases are not the same, so they are not interchangable.

**Comment by LumberWizard** [comment]
Most mekanism gasses have a liquid version. For recipes that take for example oxygen in nuclearcraft, liquid oxygen from Mekanism can be used. The same is not true for liquid sulfuric acid from Mekanism. I figure there must be some way through configs/crafttweaker to enable support for that, since the liquids are made from exactly the same materials, in exactly the same process - just in different machines.

**Comment by NillerMedDild** [comment]
I'm well aware of that.

As far as I know, the recipes that do work are created from NuclearCraft's side.

It may be possible, and I may do it at some point, but no promises.

**Comment by NillerMedDild** [comment]
Bad stale bot, bad!
