### ISSUE TITLE
Extreme Reactors controller uncraftable 

### ISSUE THREAD

**Issue by Trethope** [NillerMedDild/Enigmatica2Expert#226]
#### Issue Description
When attempting to craft the extreme reactors reactor controller the pattern does not recognize the nuclear craft Fission Controller. 
![image](https://user-images.githubusercontent.com/42754232/44688659-8c07e780-aa1a-11e8-8097-ea5a2a28d2ef.png)
![image](https://user-images.githubusercontent.com/42754232/44688693-a0e47b00-aa1a-11e8-8527-db151c7829ed.png)
![image](https://user-images.githubusercontent.com/42754232/44688715-b2c61e00-aa1a-11e8-97b0-34ffd495ead5.png)

Tried on two different basic crafting tables and two fission controllers 

#### Modpack version (Do not use "latest")
1.35
#### Crash Report

[pastebin/gist/etc link here]

**Comment by Trethope** [comment]
I have found the issue for you to fix and am fixing it in my game. The name for the Nuclear craft reactor has reference has changed from nuclearcraft:fission_controller_new_idle to nuclearcraft:fission_controller_new_fixed.

![image](https://user-images.githubusercontent.com/42754232/44689062-d9d11f80-aa1b-11e8-9d8e-1209e48160f3.png)
![image](https://user-images.githubusercontent.com/42754232/44689073-e2295a80-aa1b-11e8-8903-30a4947a9557.png)

**Comment by NillerMedDild** [comment]
Just update to 1.36, this is fixed already.
