### ISSUE TITLE
HarvestCraft tomato/grape seeds produce Rustic tomatoes/grapes

### ISSUE THREAD

**Issue by codeka** [NillerMedDild/Enigmatica2Expert#227]
This is fairly minor, but makes ultimate stew pretty tough (because there's no other way to get HarvestCraft tomatos, except by breaking lots of gardens):

![2018-08-27_22 41 31](https://user-images.githubusercontent.com/1569910/44702950-9641da00-aa4a-11e8-9a39-97701e75b288.png)

Rustic has it's own seeds which you can use to make Rustic tomatoes

**Comment by codeka** [comment]
(you could also remove the harvestcraft tomatoes from the ultimate stew recipe... it already has rustic tomatoes as well :) )

**Comment by NillerMedDild** [comment]
It's supposed to be oredict tomato, I'll get it fixed. Thanks for the report!

**Comment by codeka** [comment]
By the way, not sure if you fixed this one as well, but I found that harvestcraft:beetseeditem make minecraft:beetroot, not harvestcraft:beetitem

**Comment by NillerMedDild** [comment]
That's fine imo :)

**Comment by codeka** [comment]
I guess it's not a huge problem, I ended up just growing them in the ground the old fashioned way :)
