### ISSUE TITLE
Repeatable BetterQuesting Reload Quest

### ISSUE THREAD

**Issue by EchoingZen** [NillerMedDild/Enigmatica2Expert#228]
As I play Hardcore mode, I am not able to enter commands to reload the quests/loot without opening the game to LAN with cheats. Doing this, however, crashes my game.

Please consider adding a repeatable quest that runs those commands for us, regardless of whether cheats are enabled or not. This would help Hardcore players or players who have cheats disabled.

Thank you for the awesome pack. :)

**Comment by NillerMedDild** [comment]
Huh, I thought I made one already, guess that was only on the skyblock ^^'

**Comment by NillerMedDild** [comment]
And my pleasure :)

**Comment by EchoingZen** [comment]
Thank you!
