### ISSUE TITLE
Can't sneak-rclick immersive engineering fluid pump with engineering hammer

### ISSUE THREAD

**Issue by Xetaxheb** [NillerMedDild/Enigmatica2Expert#23]
#### Issue Description

Can't sneak-rclick immersive engineering fluid pump with engineering hammer. It just does nothing.

#### What you expected to happen

Opposite side to change config (none->input->output->none)

#### Modpack version (Do not use "latest")

1.18

**Comment by NillerMedDild** [comment]
Has that ever been a thing?

**Comment by Xetaxheb** [comment]
Yes. Just tested current IE release standalone, works fine. Gonna test further with Enig2E mods and see if I can find the culprit.

**Comment by Xetaxheb** [comment]
Hmm.. fresh installed Enig2E and it works now.
I'm not sure what's different in my main profile that would be causing an issue but it must have been something I did then.

**Comment by Xetaxheb** [comment]
Turns out it's an issue with IE; can't do it with literally anything in offhand.

**Comment by NillerMedDild** [comment]
I see, thanks for fixing it :b
