### ISSUE TITLE
Extreme Reactors controller uncraftable

### ISSUE THREAD

**Issue by schliip** [NillerMedDild/Enigmatica2Expert#230]
#### Issue Description
The Extreme Reactors legacy Reactor Controller requires a "nuclearcraft:fission_controller_new_idle" to craft, but the only craftable NuclearCraft fission controller is the "nuclearcraft:fission_controller_new_fixed"
#### Modpack version (Do not use "latest")
Enigmatica 2: Expert Skyblock 1.4
#### Crash Report
N/A

**Comment by NillerMedDild** [comment]
This is not the issue tracker for the skyblock version, please report this there :)
