### ISSUE TITLE
Enchanter recipe issue

### ISSUE THREAD

**Issue by LumberWizard** [NillerMedDild/Enigmatica2Expert#231]
#### Issue Description
The Magical Wood recipe in the Enchanter from ExU2 appears to work with all types of bookshelves in JEI (the ones from quark made of different wood types), however, any bookshelf other than the vanilla one can't be put in the Enchanter.
#### Modpack version (Do not use "latest")
1.36

**Comment by NillerMedDild** [comment]
I'm aware of this issue, but since Extra Utilities 2 doesn't have an issue tracker, I'm afraid this issue is probably permanent. Thanks for the report anyway.

**Comment by LumberWizard** [comment]
Extra Utils 2 does in fact have an issue tracker. https://github.com/rwtema/Extra-Utilities-2-Source/issues.

**Comment by NillerMedDild** [comment]
That may be, but it's not maintained.

**Comment by LumberWizard** [comment]
Last commit was 4 days ago, seems to be maintained to me.

**Comment by LumberWizard** [comment]
Tema rarely actually responds, but he does close issues.

**Comment by NillerMedDild** [comment]
I see, I guess I'll report it then.

**Comment by NillerMedDild** [comment]
I finally reported it!
