### ISSUE TITLE
Server Connection Issues

### ISSUE THREAD

**Issue by Alexis-Grimm** [NillerMedDild/Enigmatica2Expert#234]
#### Issue Description: I decided to set down 13 manyullyn condensers with manyullyn casings, they each have a drawer underneath them and they each have a basic automation of 2 fluid droppers a crucible with a magma block and a crucible inserter being fed by a hopper. The purpose for this was that my condensers produced a large quantity of metal from one dust, however this took anywhere from half an hour to multiple hours to finish, i didn't have time to simply wait for each dust to finish the first time over before continuing the pack, i thought being able to run all the metals at once was naturally the solution. However since then my connection to the server has tanked, from somewhere around 80ms to 2000ms, this however only occurs while i'm in the game, at my base, and have the condensers set down. We've run server diagnostics, network diagnostics, and tried various hardware and software solutions to no change. The only solution for the moment seems to be building an island hundreds of blocks away for the purpose of condensers only.

edit: only one other person has tested coming to my island, however they do not seem to have the issue.

#### Crash Report: No crash

[pastebin/gist/etc link here]

**Comment by NillerMedDild** [comment]
You're in the wrong issue tracker, this is not skyblock.
