### ISSUE TITLE
ExtraCells 2 unstable and buggy.

### ISSUE THREAD

**Issue by LumberWizard** [NillerMedDild/Enigmatica2Expert#235]
I think it should be removed from the pack (with warning of course!).

### Issues I've found with it so far:
* Bugs:
Gas level emitters doesn't work (it acts as a fluid level emitter when you place it down, including what it's called in the GUI. I haven't tested if it actually operates as a fluid level emitter, but its interface accepts fluids instead of gases)
The gas terminal doesn't display correct gas amounts (further testing is needed to determine what it actually displays. assumption: the level of a certain gas in the first cell it finds in the ME system).
The wireless universal terminal seems to be causing a crash (see #224)

* Gameplay/balance issues:
It's much easier to use up fluid or gas bytes than items. a 64k item storage cell can store millions of items, a 64k gas or fluid storage cell can't even store 20,000 buckets of the fluid.
Its gas/fluid transport system isn't any better - 625mb/t just isn't enough for most fluids and use cases (and that's the maximum for an import/export bus with 4 acceleration cards), especially for fluids. Gases are mostly fine since most Mekanism machines can't use more than 256mb/t.
It has no in game documentation, and its online documentation is sorely lacking.

* Redundancy:
Most of its functionality can be replaced with normal fluid transport systems and fluid P2P tunnels, and it seems AE2 will be adding fluid storage some time in the future as well, making ExtraCells 2 even less needed.

Really, so far it's caused me more grief than good in my game, and not in a fun challenging way.

**Comment by NillerMedDild** [comment]
As you mention, AE2 will be adding Fluid Storage. When that is fully implemented and released, ExtraCells2 will be removed. Thank you for the report and suggestions :)

**Comment by redgoblin88** [comment]
i have done some testing and have found the following results:
if the entire gas storage network is just storage busses then the amount that is read in storage is not updated every tick, instead it seems to be a random value of length thats gets bigger and bigger until the system does nt appear to update at all.
There IS a work-around for this problem though, if you use a gas import bus then that bus provides the constant ticking updates so all the gasses that are accessed with storage busses will be updated constantly and at the correct value.

The gas level emiter is indeed just a retextured fluid emiter

the export bus with max speed upgrades, well i cant tell the rate of it but its about 2000mb/second which seems plenty considering how fast machines generally create and use gases

moans:
after 14000mb of gas then the terminal just shows it as whole buckets (15b,16b,17b) so you cant tell the precise amount
gas storage bus displays "fluid storage bus" as the name within the GUI and the gas terminal renders as the fluid in the world
oh and this texture being tiny bit bigger than the hitbox...
![2018-09-08_09 33 05](https://user-images.githubusercontent.com/13396472/45252175-5207e100-b34a-11e8-9ae8-8f7f39182050.png)

**Comment by LumberWizard** [comment]
Ah, it's 2b/t? HWYLA says 625mb/t.

**Comment by NillerMedDild** [comment]
Well he said 2000mb/sec, so 100mb/t.

**Comment by LumberWizard** [comment]
Ah. I misread it as 2000mb/t. My bad. the speed of the gas terminal isn't a problem, it's fluids that I need a higher bandwidth for.
