### ISSUE TITLE
Can't craft Benitoite without relogging

### ISSUE THREAD

**Issue by codeka** [NillerMedDild/Enigmatica2Expert#236]
This is kind of a weird one. I noticed Jestyr had the same issue in one of his recent videos too. Basically, if you put all of the ingredients on the pedestals to craft Benitoite, nothing happens. But if you leave the items on there, shutdown the client and relog, it'll start crafting them as soon as log back in.

Basically,

 1. Put all the ingredients to make Benitoite on the pedestals
 2. Notice nothing happens
 3. Exit the game
 4. Restart the game
 5. Notice that the crafting is happening now that you've relogged.

**Comment by NillerMedDild** [comment]
... What the hell

**Comment by NillerMedDild** [comment]
Is this only the case for Benitoite?

**Comment by codeka** [comment]
I think so. I've got a few other recipes that work fine (Resonant Cell Frame (Full) for example is one that I can do no problems).

**Comment by NillerMedDild** [comment]
[ExtremeReactors.zip](https://github.com/NillerMedDild/Enigmatica2Expert/files/2349592/ExtremeReactors.zip)
Would you mind trying that file out? Just extract and overwrite into your scripts folder.

**Comment by codeka** [comment]
That seems to have worked!

**Comment by NillerMedDild** [comment]
Oh, that's a surprise. But awesome!
