### ISSUE TITLE
Extra Utilities 2... Is it a Tier 1 or a Tier 2 Tech Mod?

### ISSUE THREAD

**Issue by SephirothWS** [NillerMedDild/Enigmatica2Expert#24]
![Image](https://i.imgur.com/KLeYVRJ.png)
![Image](https://i.imgur.com/ze95goU.png)

#### Modpack version (Do not use "latest")
1.18

**Comment by Lukas45** [comment]
Yes.

**Comment by NillerMedDild** [comment]
It's 1.5 :P
