### ISSUE TITLE
Tinker Smeltery / Emerald Arrow Head bug

### ISSUE THREAD

**Issue by MadCat64** [NillerMedDild/Enigmatica2Expert#241]
#### Issue Description
I tried to use Tinkers Smeltery to pour an Emerald Arrow Head.  (Who else but me would try that?)  The liquid Emerald pours in short bursts then everything disappears from the tank and reappears after a few seconds.  
Ok - so I poured it in short bursts.  Then all of the liquid showed up in the smeltery again.
When I tried to remove the Emerald Arrowhead from the cast I can remove and replace the cast but the Emerald Arrow Head (as well as liquid emerald) remain in the table. *See the images to understand that last sentence.  Liquid and arrowhead in table.
Now there is the appearance of the full amount of liquid emerald inside the tank and on the table.

Breaking the casting table and tinker controller takes care of the problem and deletes the emeralds.
I did not test pouring out the liquid emerald from the tank because I did not have another emerald to make a cast.  

#### Modpack version (Do not use "latest")
Enigmatica 2:Expert version 1.36
Forge 1.12.2-14.23.4.2705

#### Crash Report
No crash, nothing in logs.

Images can be seen at https://imgur.com/a/baTaTsJ

**Comment by NillerMedDild** [comment]
This sounds somewhat like a desync. Can you reproduce the issue?
Also, I don't think your forge version is 2705, are you sure?

**Comment by Nicdel87** [comment]
I've had that issue before and restarting the server/game fixed it in case you haven't tried that yet. No issues on my server running version 1.35.

**Comment by MadCat64** [comment]
You may be right.  The server and game have both been restarted and I just tried again and it works.  The only differences being the restarts and having a clock on the smeltery.  The forge version was taken from the files on the server.  I'm sorry I forgot problem solving 101 - restart everything.  Consider this taken care of.  Sorry to waste your time.

**Comment by NillerMedDild** [comment]
No worries :)
