### ISSUE TITLE
Cyclic hearts take away food-earned (Spice of Life) hearts

### ISSUE THREAD

**Issue by darchitectlp** [NillerMedDild/Enigmatica2Expert#242]
Looks like your Cyclic config has a max of 20 hearts allowed. I have 23 from SOL: Carrot Edition. I ate a Cyclic heart, and had my hearts reduced to 20. Not a big deal, but thought you should know.

**Comment by NillerMedDild** [comment]
Damnit, the Cyclic config is meant to only affect Cyclic hearts, not ones gained from SoL:CE.

**Comment by LumberWizard** [comment]
Note that Nutrition (temporary) hearts are unaffected - with 10 extra hearts from full nutrition and 10 from Spice of Life, a Cyclic heart still gave me my 31st heart.

**Comment by NillerMedDild** [comment]
Nutrition hearts are from the Resistance buff, so they're unaffected.

**Comment by LumberWizard** [comment]
Resistance is damage reduction, the Nutrition hearts don't come from a status effect. I don't know how Cyclic 'knows' they're temporary. It could be a problem with SOL. More testing with other mods that add extra heart containers might be needed.

**Comment by NillerMedDild** [comment]
Woops not resistance, toughness. It is a status effect.

**Comment by LumberWizard** [comment]
I thought toughness was armor toughness?

**Comment by NillerMedDild** [comment]
Both things exist.

**Comment by LumberWizard** [comment]
I'm certain the toughness potion effect gives armor toughness, I'm not sure whether or not that's what gives the extra heart. I'll test it with /effect some time.

**Comment by NillerMedDild** [comment]
https://github.com/PrinceOfAmber/Cyclic/issues/918
