### ISSUE TITLE
Quests completed without prerequisite item acquired

### ISSUE THREAD

**Issue by tivec** [NillerMedDild/Enigmatica2Expert#243]
#### Issue Description
On leaving the world and coming back in, multiple quests started completing themselves. I am at a very early stage, haven't even gotten any metals yet, and suddenly seeing that the bragging rights chapter is opened because a quest unlocked is a bit saddening. 

What to do?

#### Modpack version (Do not use "latest")
1.4

**Comment by NillerMedDild** [comment]
The Bragging Rights chapter is always opened :) 
There's nothing to do but reset the quests I'm afraid, either through the command `/bq_admin reset playername questid` or the editor with `/bq_admin edit`

**Comment by pfmoore** [comment]
I've hit this, too. Resetting the quests (using "all") did no good - my progression was reset but I still had the "New Quest" broken quests. I would try resetting by quest ID, but how do I find out what the quest ID is for a quest in the book?

I didn't see a "reset" option when I tried `/bq_admin edit`.

I also tried restoring the "betterquesting" folder from backup. That worked for a few days, but then the quests started resetting again. It's really odd - there's no obvious sign of what triggers things to suddenly break.

Accepting that this is a mod issue, it's a *really* frustrating one. Can anyone provide a simple, step by step guide to patching up the mess if it happens? (I assume I need to go into cheat mode for this, so step one is presumably to use "Open to LAN" to allow cheats. But after that?)

**Comment by NillerMedDild** [comment]
* Open to LAN
* Run the command `/bq_admin default load`
* Activate Advanced Tooltips with F3+H
* Find the IDs of all quests that have converted to "New Quest", hover over the quest to see the ID.
* Use the command `/bq_admin reset playername questid` on all the IDs you've found.

**Comment by NillerMedDild** [comment]
Reopening for visibility

**Comment by pfmoore** [comment]
Thanks - that seemed to work. One minor point, it's `/bq_admin reset questid playername`. The game froze when I did "Save and Exit", which was worrying. Going back in, though, all looks OK.

So yes, this looks good :smile:

I'll report back if the problem happens again. But hopefully this is the last you'll hear from me! (In case I don't have cause to comment again, thanks for an amazing pack, by the way 😄 )

**Comment by NillerMedDild** [comment]
Woops, edited :)

I hope the issue will cut you some slack :P

You're very welcome!

**Comment by Raiveru** [comment]
This is happening to me all the time. In fact, it's happened to me so bad right now in SP that resetting a quest that's visible breaks it and forces it green instead of blue. Furthermore, it causes more quests to 'break' as new quest and complete themselves so I get no where. To get the quests to appear back I have to do /bq_admin default load which just puts be back to square one with a bunch of ill completed quests...
