### ISSUE TITLE
Thaumcraft wrong quest names + lacking descriptions

### ISSUE THREAD

**Issue by LumberWizard** [NillerMedDild/Enigmatica2Expert#244]
#### Issue Description
A lot of the names for quests in the Thaumcraft tree are identical to the names of the previous quests (for example the wireless Essentia transfer thingies are both called arcane bellows, which is the previous quest).

Also, some quests have hidden Thaumonomicon entries for their items (void seeds in particular I had to google to figure out), so the description of 'see Thaumonomicon for details' isn't great. You should either add your own description of how to obtain the item/research, or just put something about it being hidden.
#### Modpack version (Do not use "latest")
1.36

**Comment by NillerMedDild** [comment]
The Void Seeds in particular have a tooltip explaining how to obtain them.
Fixed the names, thanks.
