### ISSUE TITLE
Problem with recipes after disabling AE2 Channels 

### ISSUE THREAD

**Issue by Zazukih** [NillerMedDild/Enigmatica2Expert#247]
**Disabling AE2 channels breaks all the custom recipes.**

![sharex_2018-09-10_15-59-07](https://user-images.githubusercontent.com/43141744/45302251-0d7b7180-b513-11e8-86bd-7218e50bc5a3.png)

![javaw_2018-09-10_16-03-04](https://user-images.githubusercontent.com/43141744/45302250-0d7b7180-b513-11e8-841d-e09e5d1a4605.png)

![javaw_2018-09-10_16-02-46](https://user-images.githubusercontent.com/43141744/45302252-0e140800-b513-11e8-84ff-05f123388dd0.png)
![javaw_2018-09-10_16-02-58](https://user-images.githubusercontent.com/43141744/45302253-0e140800-b513-11e8-8c34-33fa50d579f9.png)

**Comment by NillerMedDild** [comment]
I'm not sure why you reported this? Yes, removing several core items from the game causes issues.

**Comment by Zazukih** [comment]
There's no way to disable AE2 channels without having any problem with recipes?

**Comment by NillerMedDild** [comment]
You'd have to make changes to some of the scripts, but it's doable :)

**Comment by Zazukih** [comment]
What are the items that I need to replace?

**Comment by NillerMedDild** [comment]
I'll do it, hold on a few minutes.

**Comment by NillerMedDild** [comment]
[scripts.zip](https://github.com/NillerMedDild/Enigmatica2Expert/files/2367407/scripts.zip)
Just unzip that into your scripts folder and overwrite, that should fix it.

**Comment by NillerMedDild** [comment]
Will you please let me know whether it works or not?

**Comment by Zazukih** [comment]
This seems to fix it, thank you a lot!

**Comment by NillerMedDild** [comment]
Nice! You're welcome :)
