### ISSUE TITLE
Using TE Portable Tank with IC2 Coolant Cell recipe consumes whole tank

### ISSUE THREAD

**Issue by erplsf** [NillerMedDild/Enigmatica2Expert#25]
#### Issue Description
Using TE Portable Tank with IC2 Coolant Cell recipe consumes whole tank
#### What you expected to happen
It will use appropriate amount of liquid in tank and return the tank
#### Modpack version (Do not use "latest")
1.18
#### Your most recent log file where the issue was present
Do I need to attach it? It doesn't crahs the game. IF it's still needed I'll do it.

**Comment by NillerMedDild** [comment]
Thanks for reporting. It's an issue with how Coolant is seen as an ingredient I believe. I suggest you use the Carpenter recipe instead. I'm not able to fix it.
