### ISSUE TITLE
Request Soulbound compatibility in TMG2

### ISSUE THREAD

**Issue by kuyana** [NillerMedDild/Enigmatica2Expert#251]
#### For feature/mod requests, feel free to delete this template
Invalidation seems to be specification but there is no indication that it will be corrected. Request to remove mod.
#### Issue Description
Enchant of soulbound added by ender io is invalidated by tomb generated with tomb many graves 2.
If tombs added by open blocks, soulbound 's Enchant is not invalidated.
I think tomb many graves 2 is unnecessary.
#### Modpack version (Do not use "latest")
1.37

**Comment by NillerMedDild** [comment]
I'm aware of the issue, but I like TMG2 a lot better than the OpenBlocks graves, as it places your items correctly everytime.

**Comment by NillerMedDild** [comment]
Situations where you have most armor/bauble slots occupied, and your inventory, resulting in your armor/bauble items spilling out into the world.

I think you should enable OpenBlocks graves in your own instance, and remove TMG2 if possible.

I recognize it as a big issue, but I'm hopefully someone will make a pull request with the Soulbound fix.
