### ISSUE TITLE
Molten Botania Metals Machine Compatibility

### ISSUE THREAD

**Issue by LumberWizard** [NillerMedDild/Enigmatica2Expert#253]
The smeltery is very slow, and elementium pipe pieces are needed for elven mana spreaders. It would be much nicer if we could melt the elementium in a NuclearCraft melter and use a Tinkers' IO smart output* to craft the pipe pieces.

*which, by the way, isn't working with itemducts or EnderIO item conduits, and I'd assume most other item transportation mods - hoppers it did work with, though, and I'd like to think Integrated Dynamics works as well, anyhow, the recent TIO update that was supposed to address this and other issues is incompatible with old worlds, so do what you will with that mod.

**Comment by NillerMedDild** [comment]
That sounds reasonable, sure. 
Manasteel, Elementium and Terrasteel will be smeltable in the NuclearCraft Melter & Thermal Expansion Magma Crucible.

**Comment by LumberWizard** [comment]
Osgloglas and Mirion as well, please, as I have just noticed they're needed for primal mana.

**Comment by LumberWizard** [comment]
[NuclearCraft](https://pastebin.com/bZ4AqFRe) and [Thermal Expansion](https://pastebin.com/bgqzewJz).

**Comment by NillerMedDild** [comment]
Excellent work, thank you.
