### ISSUE TITLE
/bq_admin default load issue

### ISSUE THREAD

**Issue by phlaxyr** [NillerMedDild/Enigmatica2Expert#254]
#### After I run /bq_admin default load, a few of the quests turn into "New Quests". These "New Quest" quests have a nether star icon, do not have any dependencies, and are automatically completed. After I run /bq_admin default load again, those quests revert back to what they were before, however they are still completed.
Here is a screenshot https://i.imgur.com/wVYbZZT.png
I had completed Blood Magic, but it reverted anyways.
The quests I have problems with is in the gate chapter, Ender IO, Advanced Rocketry, and Blood Magic. In addition, in the forestry chapter, I had problems with the peat-fired engine.
I had also experienced this issue the last time that I ran /bq_admin default load, and also had an issue in the Mekanism, but I that did not happen this time. I can elaborate more on this.

**Comment by NillerMedDild** [comment]
Duplicate of #243 
This is a mod issue, that doesn't seem will get a fix, sorry for the inconvinience.

**Comment by alpal01** [comment]
I wonder when the mod dev of betterquesting will fix this serious issue?

**Comment by NillerMedDild** [comment]
The issue is already reported, do not open additional issues about it, especially on behalf of my modpack.

**Comment by alpal01** [comment]
I closed that issue, sorry

**Comment by NillerMedDild** [comment]
No worries, your frustration is understandable :)

The mod dev is working on rewriting the mod, so my hope is that it will eventually be robust enough to prevent this kind of corruption. It's a slow process though.

**Comment by Funwayguy** [comment]
Can confirm it's a slow process. I wish I could rush everything faster but the mod is fairly complex mixed with a mess if legacy code and backwards compatibility. If that wasn't bad enough, some packs are exceeding 1000 quests making testing scalability extremely hard and stressing systems beyond breaking point.

As for this particular issue, I'd prefer players not use the commands if at all possible, their primarily for pack devs. Pack devs can also set version tags now to prompt players to update their quests with the click of a button. I've tried several times to fix this but have just decided to leave it for now until that portion of code is ready to be rewritten.

Fun Fact: BQ 3.x.x has been an ongoing rewrite for over a year now but has come a long way in stability compared to BQ1 and BQ2

**Comment by NillerMedDild** [comment]
Oh boy, I forgot all about the new versioning system. Does that use a different method to update compared to `/bq_admin default load`?

**Comment by Funwayguy** [comment]
Besides the GUI prompt and button to install it from the home screen, the underlying code is fairly similar but so far nobody has reported any issues from it yet. Can never seem to repeat the original issue in dev anyway.

You can set the version info in the same place you set the splash screen. If the current pack name matches the one in the default quests but has an older version number, you'll see the prompt on the home screen.

**Comment by NillerMedDild** [comment]
Nice, I'll switch over to that in the next round of updates, thanks.

How does it check the currrent pack name? I'm wondering what the syntax to put in `pack_name` is.

**Comment by Funwayguy** [comment]
Yes as "admin" in the command name implies. The update prompt does not.

**Comment by Raiveru** [comment]
A temporary solution for you that I just discovered for myself is, if you go to your save folder for the world, there's a BQ folder. Open that and there should be a backups folder in there. Open that, open the most recent backup available, copy "QuestProgress.json" over to the root BQ folder, save the corrupted one just in case, but you can just 'cheat' your lost progress back and get rid of the loot crates/rewards that you had before. At least you won't have broken quests and randomly completed endgame quests :D 

Also, I noticed I only encountered issues when using the commands so you probably shouldn't. Funway did say that too e.e
