### ISSUE TITLE
Can't create Nickel Plates in IC2 Metal Former

### ISSUE THREAD

**Issue by erplsf** [NillerMedDild/Enigmatica2Expert#26]
#### Issue Description
Can't create Nickel Plates in IC2 Metal Former
#### What you expected to happen
I'm able to use Metal Former for creating all plates
#### Modpack version (Do not use "latest")
1.18
#### Your most recent log file where the issue was present
No log.

**Comment by gaminggirl** [comment]
I'd like to add Aluminium plates to that list

**Comment by erplsf** [comment]
Great thanks!
