### ISSUE TITLE
 Suggest limiting the mod Ore Excavation

### ISSUE THREAD

**Issue by Bob558-51** [NillerMedDild/Enigmatica2Expert#260]
I want to suggest limiting the mod Ore Excavation. To forbid him to obtain wood and stone.
There are big axes for cutting trees Tinkers Construct.

Otherwise, it turns out that the pick digs out a lot of stone instantly, which makes it better Quarry

https://youtu.be/szjBYbeF8hY    -- wood
https://www.youtube.com/watch?v=szjBYbeF8hY -- stone

**Comment by NillerMedDild** [comment]
This is working as intended. I don't want the pack to be grindy or tedious, so gathering materials is quick.

Thanks for the suggestion though.
