### ISSUE TITLE
cant run server keeps crashing

### ISSUE THREAD

**Issue by sirblockwood101** [NillerMedDild/Enigmatica2Expert#263]
Trying to run a server with 6gb ram on a HDD 
I can run sevtech fine on this but this modpack is just like nope! 

I cant find the crash logs..I am running this on a second desktop so plz help!

**Comment by NillerMedDild** [comment]
Don't just delete the issue template, fill it out.

**Comment by NillerMedDild** [comment]
I need your latest.log to be of any help, you're not giving me any information.

**Comment by sirblockwood101** [comment]
okay will try and get the log files for ya
