### ISSUE TITLE
Sword of the Cosmos quest not detecting I have the sword

### ISSUE THREAD

**Issue by codeka** [NillerMedDild/Enigmatica2Expert#264]
Yeah, so I have a Sword of the Cosmos, but it's not registering in the quest book :'(

![2018-09-23_23 07 49](https://user-images.githubusercontent.com/1569910/45939224-bb603480-bf85-11e8-8e51-3e721a5c84e3.png)

**Comment by NillerMedDild** [comment]
I fixed this in 1.36 or 1.37, did you remember to run the update command?

**Comment by codeka** [comment]
I did, I just ran it again and it's still no detecting it. I'm running 1.37 BTW.

**Comment by NillerMedDild** [comment]
Huh, alright I'll have another look :)
