### ISSUE TITLE
Mystical Agriculture seed recipes not appearing in JEI

### ISSUE THREAD

**Issue by Viimes** [NillerMedDild/Enigmatica2Expert#266]
The recipes for seeds for all metals, gems and other assorted seeds don't show up in JEI when pressing "u" on the crafting seed. This started happening after I went to the end in version 1.34 so I updated but the issue still persists on 1.37. They were showing in JEI before going to the end.

**Comment by NillerMedDild** [comment]
Which crafting seed are you pressing U on?

**Comment by NillerMedDild** [comment]
I can't reproduce this issue.

**Comment by GreenForzeGaming** [comment]
i am having this issue right now

**Comment by GreenForzeGaming** [comment]
did some digging and can confirm that i have Mystical Adaptations installed, this gives you the new item called a Seed exctractor, and in the mods config it has removed all seed recepies by default.
