### ISSUE TITLE
Tin ore duplication

### ISSUE THREAD

**Issue by Salnex** [NillerMedDild/Enigmatica2Expert#27]
#### Issue Description
Ore Multiplication when using a bronze head, wood binding, wood rod with 1 durability attempting to vein mine resulted in the block dropping about 100 tin ores from a single tin ore block

#### What you expected to happen
A single tin ore drop
#### Modpack version (Do not use "latest")
1.18
#### Your most recent log file where the issue was present
https://gist.github.com/Salnex/6d47dca1b5c926cc6d49ea67e0ca34b6
[pastebin/gist/etc link here]

**Comment by Salnex** [comment]
https://clips.twitch.tv/SpeedyMoralSardineYouWHY don't think so, but got it recorded so? I can't spot an diagonal connections, but potentially behind to the left I guess?

**Comment by NillerMedDild** [comment]
It's not possible to determine from that clip. The thing is, I can't reproduce it.

**Comment by Salnex** [comment]
Got time, will find the area and mine around looking for air space around it

**Comment by Salnex** [comment]
https://i.imgur.com/DERFgEc.jpg well shit, I guess it was a series of diagonally connected veins. Massive vein though, just over 100 ores. My bad

**Comment by NillerMedDild** [comment]
Cool - I appreciate the report anyway :)
