### ISSUE TITLE
EnderIO Conduit Config in 1.38

### ISSUE THREAD

**Issue by sarcastic6** [NillerMedDild/Enigmatica2Expert#275]
**Issue Description**
EnderIO conduits are using their default values instead of the those from previous versions of the pack.  For example, tier 1 energy conduit is the default 640 rf/tick versus 5000 rf/tick in previous versions of the pack.

If you look at config/enderio/enderioconduits.cfg you'll see that everything appears to be defined there twice; your customized values are at the top but then all the default stuff is beneath it, ultimately replacing your custom values. 

I believe that enderio is regenerating the configuration because you misspelled "conduit" as "condit" on line 3.

**Modpack version (Do not use "latest")**
1.38

**Logs**
N/A

**Screenshots**
N/A

**Additional context**
N/A

**Comment by NillerMedDild** [comment]
Woops, looks like it reset, thanks for the report :)
