### ISSUE TITLE
AE2 WiFi disables AE2 server

### ISSUE THREAD

**Issue by MarcinSzuba** [NillerMedDild/Enigmatica2Expert#279]
**Issue Description**
I have an AE2 Server. After upgrade server mod pack to 1.38 my AE2 Server works fine... if I disconnect all WiFi connections. If I have at least one server is not working but on 1.37 it was working.

**Modpack version (Do not use "latest")**
1.38

**Logs**
Not a crash, don't even know where to get any logs that you can want to see

**Screenshots**
![2018-10-04_13 10 36](https://user-images.githubusercontent.com/24719433/46470490-16d8c080-c7d7-11e8-9872-e18c09dfceb2.png)
![2018-10-04_13 10 53](https://user-images.githubusercontent.com/24719433/46470491-17715700-c7d7-11e8-9b49-3d9dce55ece4.png)

**Additional context**

**Comment by NillerMedDild** [comment]
Are you supplying enough power? It looks like it needs a ton.

**Comment by NillerMedDild** [comment]
I'm guessing you mean AE2 Network when you say AE2 Server, right?

**Comment by MarcinSzuba** [comment]
Ok I've resolved it. It was a problem with not enough power in AE2 server. I had to add Energy Cells. It was due to changes in Ender Energy Conduits you've made in  1.38 and restored in 1.38a.
