### ISSUE TITLE
Bibliocraft Armor Stands spam log with 'Couldn't render entity' errors

### ISSUE THREAD

**Issue by SeooY** [NillerMedDild/Enigmatica2Expert#282]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
Having any Bibliocraft Armor Stand in the world starts spamming several 'Couldn't render entity' errors each second to the Minecraft log.

**Modpack version (Do not use "latest")**
1.38

**Logs**
https://hastebin.com/goyexegufa.makefile

**Screenshots**

**Additional context**
According to the error, it also seems to be related to the Backpacks mod, I'm not sure if it's specific to an interaction with those two, but it was working fine before updating the pack.

**Comment by NillerMedDild** [comment]
Neither mod updated from 1.37 to 1.38, so this is a bit weird.

The hastebin link is empty, remember to save :)

**Comment by SeooY** [comment]
That's weird, I did save it, but hastebin seems like it's having issues as it won't let me create another one and it's just showing an error. Here's a pastebin instead
https://pastebin.com/hdQRw1x0

**Comment by NillerMedDild** [comment]
Ah that issue :P it has been reported to the mod dev multiple times. For what it's worth, it's completely harmless.
