### ISSUE TITLE
New game crash

### ISSUE THREAD

**Issue by MarcinSzuba** [NillerMedDild/Enigmatica2Expert#285]
## Thank you for helping us improve. #####

**Issue Description**
Due to a problem with my server I've wanted to check if the same one occures on single player. Just after creating new world I can't load it. Every time MC crashes.  I'm using JAVA 1.8.0_171

**Modpack version (Do not use "latest")**
1.38a

**Logs**
[latest.log](https://github.com/NillerMedDild/Enigmatica2Expert/files/2447733/latest.log)
Sorry that it's not on hastebin but I somehow it doesn't work for me. That's the crash log with just the name "latest.log"

**Screenshots**

**Additional context**

**Comment by NillerMedDild** [comment]
Thank you for the report. I will release a hotfix 1.38b soon that remedies this.

**Comment by stormshard** [comment]
I also had this error creating singleplayer world. Log here if needed:

https://pastebin.com/DjVm5XDg

**Comment by sarcastic6** [comment]
Is it possible it's this issue?  https://github.com/fewizz/NotEnoughIDs/issues/78

**Comment by Raiveru** [comment]
Our server's been working great until updating to 1.38a. Upon exploring our world just a tiny bit, we encountered a similar crash and here's our log to compare. 

https://pastebin.com/gXqiNzGJ

**Comment by NillerMedDild** [comment]
Yes that is indeed the issue, thank you @sarcastic6 :)
