### ISSUE TITLE
Void miner blocks other than controller disappearing

### ISSUE THREAD

**Issue by TaterHog** [NillerMedDild/Enigmatica2Expert#287]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
Void ore miner blocks disappear when mined or right clicked with building wand

**Modpack version (Do not use "latest")**
1.38

**Logs**

If applicable, please upload your crash report, or latest.log to [hastebin](https://hastebin.com/).

**Screenshots**

**Additional context**

**Comment by NillerMedDild** [comment]
Fixed by mod dev :)
https://minecraft.curseforge.com/projects/valkyrielib/files/2624358
