### ISSUE TITLE
MV-transformer stops sending EU

### ISSUE THREAD

**Issue by gaminggirl** [NillerMedDild/Enigmatica2Expert#29]
#### Issue Description

At random the IC2 MV-transformer stops sending EU on the down transformed sides. Transformer is set to "fixed step-down" and has no redstone signal. it outputs on two sides with insulated copper cables and inputs 2x insulated gold cables. 

#### What you expected to happen
The transformer doesn't stop sending power at random. 

#### Modpack version (Do not use "latest")

version 1.18

#### Your most recent log file where the issue was present

[pastebin/gist/etc link here]

**Comment by NillerMedDild** [comment]
Could I have a screenshot or two of the setup?

**Comment by gaminggirl** [comment]
![ic2 first](https://user-images.githubusercontent.com/19671059/39237551-275f8cc0-487c-11e8-8255-24b1821fed97.png)
![ic2 second](https://user-images.githubusercontent.com/19671059/39237553-277d29d8-487c-11e8-99b3-6102ce8b390c.png)
![MV-transformer settings](https://user-images.githubusercontent.com/19671059/39237611-4c2f84c4-487c-11e8-9033-c7d91f98a7d9.png)


Tell if you want some other angle or something...

**Comment by NillerMedDild** [comment]
Could it be redstone powered through blocks?

**Comment by gaminggirl** [comment]
I havn't placed any redstone in the world so no on that.

**Comment by NillerMedDild** [comment]
Alright then. I suggest you use Mekanism Cubes/Cables instead :/
Since we have Mekanism using the IC2 power grid in this pack, I don't think I'd be able to throw a bug report at IC2.
