### ISSUE TITLE
Crashes on startup

### ISSUE THREAD

**Issue by Nickiel12** [NillerMedDild/Enigmatica2Expert#295]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
I load the game, join my single-player world, three seconds in, it crashes.

**Modpack version (Do not use "latest")**
1.39

**Logs**

 [pastebin](https://pastebin.com/vTJ1m3rk).

**Screenshots**

**Additional context**

**Comment by NillerMedDild** [comment]
I believe the issue is, that an item is being pulled out of an Iron Chest via Ender IO Item Conduit, but that item has a bad null check, or is null. Do you happen to know which chest I could be talking about?

I'm fairly certain you will have to fix this issue with MCEdit I'm afraid.

**Comment by NillerMedDild** [comment]
Fair enough :)
