### ISSUE TITLE
AE2 Cutting Knife unusable after one use.

### ISSUE THREAD

**Issue by RyanP1991** [NillerMedDild/Enigmatica2Expert#301]
**Issue Description**

When trying to make AE2 cable anchors with the cutting knife the moment you use it once, it is then unable to be used again to make further anchors so requiring constant making of new cutting knifes. 

What should happen is being able to use the cutting knife for it's full durability to make cable anchors.

**Modpack version (Do not use "latest")**

Version - 1.39a

**Logs**

**Screenshots**

Link below shows what I see

https://imgur.com/a/h4uSp3j

**Comment by lomira** [comment]
I can reproduce this issue.
Tested with certus and nether quartz cutting knife on vanilla crafting table and AE2 crafting grid.

**Comment by NillerMedDild** [comment]
Oh I see it's already reported, woops.
https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/3746

Thanks for the report.
Thank you for the additional testing @lomira :)
