### ISSUE TITLE
BQ issues with "New Quest" and random progress completion

### ISSUE THREAD

**Issue by Raiveru** [NillerMedDild/Enigmatica2Expert#302]
This is happening to me all the time. In fact, it's happened to me so bad right now in SP that resetting a quest that's visible breaks it as "New Quest" and forces it green instead of blue. Furthermore, it causes more quests to 'break' as new quest and complete themselves so I get no where. To get the quests to appear back I have to do /bq_admin default load which just puts be back to square one with a bunch of ill completed quests...

I don't know what to do. Now "Gate: Bragging Rights" is complete, at this rate I won't have any quests left to do for myself. Should I just throw the world away?

**Comment by Raiveru** [comment]
Sorry, didn't see the issue already open that's stale, but I saw one that was closed

**Comment by NillerMedDild** [comment]
No worries :)
