### ISSUE TITLE
Extra Utilities 2 Generetors disappears when broken

### ISSUE THREAD

**Issue by Steel723** [NillerMedDild/Enigmatica2Expert#306]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
Extra Utilities 2 Generetors disappears when broken with pickaxe. Tried with survival, furnace, culinary, ender and overclocked. Rainbow generator gives you back the item.

**Modpack version (Do not use "latest")**
1.38

**Logs**

If applicable, please upload your crash report, or latest.log to [hastebin](https://hastebin.com/).

**Screenshots**

**Additional context**

**Comment by NillerMedDild** [comment]
What did you use to break in, and can you reproduce this in 1.39a?

**Comment by Steel723** [comment]
Tinker's construct pickaxe.

Reproducted in 1.39a, the problem is solved. I'll update the server.
