### ISSUE TITLE
Thermal expansion missing recipe's

### ISSUE THREAD

**Issue by KingRizla** [NillerMedDild/Enigmatica2Expert#308]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
currently ive only test one thing and that is the resonant energy cell, you can make the empty version and then fill it, but there is no recipe to make the actual resonant energy cell (the functional one)

**Modpack version (Do not use "latest")**

v1.39a

**Logs**

If applicable, please upload your crash report, or latest.log to [hastebin](https://hastebin.com/).

**Screenshots**

**Additional context**

**Comment by NillerMedDild** [comment]
That item no longer exists, you have to upgrade a normal energy cell with a kit.
