### ISSUE TITLE
JEI Resources - Blacklisted Enchant List Correction

### ISSUE THREAD

**Issue by Guswut** [NillerMedDild/Enigmatica2Expert#311]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**

The "Curse of Vanishing" is listed on the "jeresources.cfg" under ".minecraft\config\jeresources" as "curseofvanishing", but it should be listed as "vanishing_curse" to disable the curse of vanishing from being listed in the enchantment tab.

This can be tested by doing a JEI usage for "Uranium RTG".

**Modpack version (Do not use "latest")**

1.39a

**Logs**

N/a

**Screenshots**

N/a

**Additional context**

N/a

**Comment by NillerMedDild** [comment]
Excellent, thank you very much :)
