### ISSUE TITLE
NC Infinite Water Supply inside Thermal Evaporation Controller Causes Crash

### ISSUE THREAD

**Issue by Rob110178** [NillerMedDild/Enigmatica2Expert#316]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
I set up the Thermal Evaporation Tower. I constructed the Tier 1 Nuclear Craft Infinite Water Supply and placed it into the water supply slot (Top left block). Nothing adverse happened until I noticed that initially it would supply water but than stopped supplying water. I tried to remove it by clicking and Shift Clicking on the water supply and it caused the game to lag than crash. Breaking the Block did not yield a return of the Infinite Water Supply. 

**Modpack version (Do not use "latest")**
1.39A

**Logs**
https://hastebin.com/zefazihawi.rb
https://hastebin.com/esiyojayup.rb
Apparently these didn't work, please try the two below:
https://pastebin.com/pB0W2PCC
https://pastebin.com/regnB5qf

**Screenshots**

No Screenshots available See Description

**Additional context**
None

**Comment by tyler489** [comment]
Seems those logs links are invalid.. if i had to guess i would say nuclearcraft doesnt like carryon

**Comment by Rob110178** [comment]
Fixed, Updated the issue accordingly. 

https://pastebin.com/pB0W2PCC
https://pastebin.com/regnB5qf

**Comment by tyler489** [comment]
Seems to be a mekanism bug from the report

**Comment by NillerMedDild** [comment]
Thanks for the report, and thank you very much for handling it Tyler! :)

**Comment by NillerMedDild** [comment]
Fixed in Mekanism' dev.

**Comment by NillerMedDild** [comment]
Woops, forgot about my new changelog system, reopening this so it doesn't show as solved yet.
