### ISSUE TITLE
Recipe for beryllium and rhodochrosite changed

### ISSUE THREAD

**Issue by KingFishQiu** [NillerMedDild/Enigmatica2Expert#320]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**

Dear NillerMedDild

I used to have automation systems for beryllium and rhodochrosite. But today, when I tried to use the autocraft again, it didn't work. And I checked the JEI recipe, and the only recipe left is using rock crusher to create the dust of them, which is highly unstable (percentage possibility to get what i need). I rechecked the upgrade changelog and I don't think it's intentionally changed.

Sincerely,
KingFish-v-

**Modpack version (Do not use "latest")**
1.39a

**Logs**

If applicable, please upload your crash report, or latest.log to [hastebin](https://hastebin.com/).

**Screenshots**

**Additional context**

**Comment by tyler489** [comment]
#299
It was intentionaly changed but plans to change it back
