### ISSUE TITLE
Furnaces deleting items

### ISSUE THREAD

**Issue by Reddhero12** [NillerMedDild/Enigmatica2Expert#321]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

very frequently the first objects I put into a furnace get deleted
like if I put in 8 coal and then put in a stack of iron ore or whatever, it deletes the 8 coal and iron, but then the furnace can be used without the bug happening from that point forward
and the furnace still lights up as if its cooking, and the modded "Item -> Item" thing pops up when hovering over it, though all you see is an arrow since both sides are blank. so it's like ____ -> _____
despite nothing being inside

Modpack is 1.39a

It has only happened with vanilla furnaces.

**Comment by NillerMedDild** [comment]
The items don't reappear if you relog, right?

**Comment by Reddhero12** [comment]
No, they are gone for good. It happens in single player and multiplayer. Breaking the furnace also does not give the items.

**Comment by NillerMedDild** [comment]
I can't seem to reproduce this, but I did update FastFurnace, so I'm hoping it's fixed.

**Comment by Reddhero12** [comment]
![](https://cdn.discordapp.com/attachments/501450262628794368/501450399518294016/unknown.png)


Still happening

**Comment by NillerMedDild** [comment]
.....I haven't released an update yet

**Comment by tyler489** [comment]
Yeah.. that would do it...
