### ISSUE TITLE
IE Redstone wire connector broken after reload

### ISSUE THREAD

**Issue by DaniJazza** [NillerMedDild/Enigmatica2Expert#323]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Question or Issue**

I have an issue where the Redstone wire connector can't have more wires connected to it after reloading the game. You receive the "You cannot attach this wire here" message. You need to break it and replace it.

**Modpack Version**

1.39a

**Additional Context**

- Same issue as this person
https://github.com/BluSunrize/ImmersiveEngineering/issues/3204

**Comment by NillerMedDild** [comment]
Thank you for the report :)
https://github.com/FerroO2000/Immersive-Tech/issues/74#issuecomment-419811811
