### ISSUE TITLE
Advanced Rocketry - Small Client Config Change

### ISSUE THREAD

**Issue by Watschman** [NillerMedDild/Enigmatica2Expert#328]
Greetings everyone, I am not sure if a Feature is the correct description for it, more like a pull request

**Is your feature request related to a problem? Please describe.**
Yes, it is related to a Problem:
Since this Modpack is very heavy and therefore requires immense Power, a friend and I decided to setup a Cluster to run this Pack, so that only 2 or 3 people play on one Cluster.  We managed to make a successful Test Setup via Bungeecord and SpongeForge Servers. The only Problem is, that we needed a Vanilla Hub Server due to the fact that we plan on connecting our remaining servers to the Cluster setup which run different Modpacks.

The setup was actually very simple after a bit of Research, there is only one Problem which occurred with one Mod of this Pack, named Advanced Rocketry. If you connect to the Proxy Hubserver, which is a Vanilla 1.8.8 PaperSpigot Server, the Client crashes.

From what I gathered from the Crashlog (see Link Number 1 - Additional Context) the issue was caused due to Advanced Rocketry trying to render some Stars.
I investigated further and boiled it down by connecting with almost only Advanced Rocketry installed. The same crash happened. (see Link Number Two)

Now I got curious and looked into the config and saw a section named Client. 
In there is a Config Option named "overworldSkyOverride" which was set to true.
Setting this Option to false. The Client connects successfully to the Server without a Crash.
I don't know what this Setting is actually doing, but if it isn't game breaking by setting it to false, I would really appreciate that small, but crucial Change.

**Describe the solution you'd like**
I would like the Modpack to set Advanced Rocketry's Client "overworldSkyOverride" Config to false by default,(see Link Number 3) in order to make it able to run on Big Clusters without additionally End User Configuration Changes.

**Additional context**

Link Number 1 - https://pastebin.com/JeUep20t
Link Number 2 - https://pastebin.com/VCs4gB5S
Link Number 3 - https://i.imgur.com/q0G88qB.png

TLTR: Change Advanced Rocktry Config overworldSkyOverride Value to false instead of true.

Greetings, Watschman.

**Comment by NillerMedDild** [comment]
Damn, that is one well written issue. I'll change it :)
