### ISSUE TITLE
Crash After Updating ti 1.19a

### ISSUE THREAD

**Issue by Angelos33** [NillerMedDild/Enigmatica2Expert#33]
#### Issue Description
Game Crashing after entering world! The pack loads just fine but when i enter my save it loads the world, i see everything and the almost immediately crashes and kicks me out to the Minecraft launcher with the crash message. This started after the update to 1.19a from 1.18 version of the pack.
#### What you expected to happen
Enter the world normally with no crashes
#### Modpack version (Do not use "latest")
Modpack Version 1.19a
#### Your most recent log file where the issue was present
[crash-2018-04-25_21.07.16-server.txt](https://github.com/NillerMedDild/Enigmatica2Expert/files/1948313/crash-2018-04-25_21.07.16-server.txt)

**Comment by NillerMedDild** [comment]
Navigate to the `configs` folder, and open the `forge.cfg` file. 
Open it (with Notepad for example) and replace all the text with the contents of [this link](https://pastebin.com/gDTr7sAN)

**Comment by Angelos33** [comment]
It works now! Thank you very much! i will keep playing the pack and report any bugs i find.
