### ISSUE TITLE
[Suggestion] Use RandomPatches' window title feature

### ISSUE THREAD

**Issue by TheRandomLabs** [NillerMedDild/Enigmatica2Expert#330]
You can set the window title in `randompatches.cfg`. The property is `client.window.title`.

**Comment by NillerMedDild** [comment]
I had no idea that was a feature, thanks for the suggestion :D I just implemented it in all the Enigmaticas.

**Comment by NillerMedDild** [comment]
I noticed, I will be using that feature for an upcoming modpack :D
