### ISSUE TITLE
Me annihilation plane break mekanism items without any possible output 

### ISSUE THREAD

**Issue by anthonyL05** [NillerMedDild/Enigmatica2Expert#339]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**

I try to automate the different tier of mechanisme machine (in this case the osmium compressor). i try to use the annihilation plane to break only the basic one by putting as only possible output it. As i do with the livingrock. But when i place the annihilation plane with nothing else in the network than a controller and an energy acceptator he instantly break the osmium compressor. The osmium compressor just desappears. I make some test and find its hapend with all the mekanism item ( including the mekanismgenerators ). I try some other block from different mode but i have never detected the same issu. 

**Modpack version (Do not use "latest")**

1.41

**Logs**

If applicable, please upload your crash report, or latest.log to [hastebin](https://hastebin.com/).

**Screenshots**

**Additional context**

**Comment by anthonyL05** [comment]
I just think about a new test. I try to put an output in the system and do the same things, but the mekanism item doesn't go to the inventory (he just disappear). I dont know if it can help

**Comment by anthonyL05** [comment]
I was trying to find a solution to automate it. I will keep looking for a find another way. Its work very well with thermal expension machine its why i try it.  Thank you anyway.

**Comment by NillerMedDild** [comment]
Oh, and that's with Annihilation Planes aswell?

**Comment by anthonyL05** [comment]
yes i make its with annihilation plate. 
with the pulveriser it give: 
 - the system put the pulveriser and the upgrade to the first network 
- the first system put each upgrade on an automated user who face the formation plate who accept only the before upgrade pulveriser. 
 - the first network put the pulveriser to the first me formation plate who accept only normal one
- the seconde system take back the hardened one ( he had no place to output normal one so wait until item upgrade) with an annihiliation plane 
-  the seconde system put the hardened on the next formation plate
- the first system take back the reinforced one
.....
and the last one put on an enderchest with and export bus who accept only the resonant one. Its put the item to my system.

its work very well. Even if it's not realy usefull but i try to make automation for most of the item i can.

**Comment by anthonyL05** [comment]
i find a solution for automate elite compressing factory. I use only the formation plate then i broke the elite one with mechanical user  in good timing by  pushing him with piston after the upgrade is done.. Its require to take time to make the redstone setup. But it work fine.
https://ibb.co/dftoO0
https://ibb.co/mQMa30

I can now fully autocraft the quantum compressor!

**Comment by NillerMedDild** [comment]
Impressive!
