### ISSUE TITLE
Mekanism advanced solar generator recipe crash

### ISSUE THREAD

**Issue by Sasikaa** [NillerMedDild/Enigmatica2Expert#345]
**Issue Description**

Crafting the advanced solar panel mekanism with tinker construct crafting table. The Applied energetics grinder is conneted this crafting table, and the grindstone inventory show inside the crafting table.

!!!!!The grindstone delete, and the recipe working and not crashing!!!!!

**Modpack version (Do not use "latest")**
1.41

**Logs**

https://hastebin.com/raw/awuteziped

**Comment by NillerMedDild** [comment]
It's a known issue, you can just use a regular crafting table.

**Comment by Sasikaa** [comment]
Thanks the answere. The grinding stone (Applied) removed the side of this tinker table, and working perfectly...

**Comment by NillerMedDild** [comment]
Oh I see. Nice!
