### ISSUE TITLE
Ae2 seeds in enrichment chamber automation

### ISSUE THREAD

**Issue by lesyriad** [NillerMedDild/Enigmatica2Expert#348]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Question or Issue**
Growing of pure ae2 crystals in mekanism enrichment chamber

**Modpack Version**
1.41

**Additional Context**
Any pure ae2 crystal seeds can be grown if manually placed into the mekanism enrichment chamber.  However the enrichment chamber will not accept the seeds if you try to pipe them in via any mod.  Mods tried ae2 export bus/interface, thermal dynamics itemduct from a chest, mekanism basic logistical transporter from chest.  

I can pipe in other items such as ore just none of the pure crystal seeds.  I can even pipe in the fluix dust.

**Comment by Hachuurui** [comment]
This exists in several modpacks, so you know. It is most likely a mod specific issue.

**Comment by NillerMedDild** [comment]
It works just fine for me. 

![billede](https://user-images.githubusercontent.com/21295394/48368021-d7916f80-e6b2-11e8-848a-5372c6235f51.png)
![billede](https://user-images.githubusercontent.com/21295394/48368027-db24f680-e6b2-11e8-9283-2dc7c4c15a3b.png)
![billede](https://user-images.githubusercontent.com/21295394/48368030-deb87d80-e6b2-11e8-9a54-cd1314134d6a.png)
