### ISSUE TITLE
Arcane Workbench backpack bug

### ISSUE THREAD

**Issue by Angelos33** [NillerMedDild/Enigmatica2Expert#35]
#### Issue Description
Every time i open the Arcane Workbench i get a free backpack at the crafted item slot of the table without putting the items to craft it, i don't think that's intended. If i have an item recipe in the table this doesn't happen though.
#### What you expected to happen
To not get a free backpack from the table.
#### Modpack version (Do not use "latest")
Modpack Version 1.20
#### Your most recent crash report or log file where the issue was present

[pastebin/gist/etc link here]

**Comment by NillerMedDild** [comment]
The issue has been reported to the issue trackers of both mods, thank you for the report.
