### ISSUE TITLE
Personal Charger uncraftable

### ISSUE THREAD

**Issue by medtryx** [NillerMedDild/Enigmatica2Expert#351]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
I am unable to craft the Personal Charger. This was noted to be due to conflicting NBT data with what is crafted in game and what was in the WirelessCharger.zs scipt. 

Advanced Tooltips showed the one listed in the JEI recipe did not have all of the NBT data. It would fill in the recipe from JEI, but did not have a result on the table.

I used /ct hand to get the data: <mekanism:energycube>.withTag({tier: 3, mekData: {security: 0, energyStored: 0.0}}) and updated the script. This corrected the issue and allowed me to craft it.

**Modpack version (Do not use "latest")**

1.41

**Logs**

If applicable, please upload your crash report, or latest.log to [hastebin](https://hastebin.com/).

**Screenshots**

**Additional context**

**Comment by Ricket** [comment]
This is the case for a lot of recipes with Mekanism items, it's tracked as #333 , see also the convo in discord ending in this message: https://discordapp.com/channels/195234321836146688/396041096179744768/503884363726061570

**Comment by NillerMedDild** [comment]
Thank you for the report.

**Comment by medtryx** [comment]
> This is the case for a lot of recipes with Mekanism items, it's tracked as #333 , see also the convo in discord ending in this message: https://discordapp.com/channels/195234321836146688/396041096179744768/503884363726061570

Thanks! I searched for Wireless and Personal when I added the issue, not sure why I didn't search with mekanism as well.
