### ISSUE TITLE
Astral Sorcery items craftable in regular crafting station

### ISSUE THREAD

**Issue by Ricket** [NillerMedDild/Enigmatica2Expert#352]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**

You can craft the resonating wand and the luminous crafting table in a tinker crafting station. My understanding is they are supposed to only be craftable in a crafting table inside an astral altar (near the crystal).

**Modpack version (Do not use "latest")**

1.41

**Logs**

N/A

**Screenshots**

N/A

**Additional context**

N/A

**Comment by NillerMedDild** [comment]
The recipes are modified, and can be crafted in the normal crafting table, because a vast amount of players didn't understand the normal way of obtaining them.
