### ISSUE TITLE
Ultimate Furnace recipe broken

### ISSUE THREAD

**Issue by Confluxes** [NillerMedDild/Enigmatica2Expert#353]
## Thank you for helping us improve. #####

**Question or Issue**
The recipe for the Ultimate Furnace seems to be broken. 

**Modpack Version**
1.41

**Additional Context**
Just to be clear, it is the elite smelting factory in the crafting table since you can't really tell the difference between any of them.

![2018-10-27_04 20 03](https://user-images.githubusercontent.com/36505490/47603368-049a0e80-d9a0-11e8-8861-4c9cd56563f5.png)

**Comment by NillerMedDild** [comment]
Fixed by #333 - Thank you for the report :)
