### ISSUE TITLE
Immersive Engineering Steel Scaffold Staircase recipe conflict

### ISSUE THREAD

**Issue by Jomeaga** [NillerMedDild/Enigmatica2Expert#355]
**Issue Description**
When you try to craft Steel Scaffolding Stairs, the output is a new Steel Structural Arm block that has no texture when placed down. Trying to craft the other kinds of steel scaffold stairs ends with the same result, so you cannot just craft another and convert to regular.

**Modpack version (Do not use "latest")**
1.41

**Comment by mgwerner** [comment]
Reopen for 0.12-86, same issue.  Stairs cannot be crafted, no texture (invisible) structural arm when placed.

**Comment by NillerMedDild** [comment]
Fixed by the new version of IE.
