### ISSUE TITLE
Machine-dropped or Split Astral Sorcery Rock/Celestial Crystals despawn on Server

### ISSUE THREAD

**Issue by Targren** [NillerMedDild/Enigmatica2Expert#358]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**

Rock/Celestial Crystals (hereafter "crystals") dropped into liquid starlight aren't supposed to despawn. When dropped by a player with the drop key (default "Q"), they work as expected. 

When they're dropped into the starlight by a non-player (Tested with World Item Exporter (Integrated Tunnels), Item Dropper (Openblocks), Dropper and Dispenser(vanilla), ) OR when a correctly-dropped crystal splits, as per normal Astral Sorcery mechanics,  the items despawn after the usual 5 minutes. 

Confirmed that it was a despawn by enabling the "flash before expiring" option in quark. 

**Modpack version (Do not use "latest")**
1.4.1

**Logs**

N/A

**Screenshots**

An example setup that can I used for demonstration. Removed the liquid starlight from above the dispenser for clarity. 

[Screenshot on Imgur](https://imgur.com/a/T8oynsP)

**Additional context**

The problem is constant on the server, but only intermittently reproducable in SSP. Server is running sponge in addition to server files. Confirmed with server admin that none of the plugins "clean up" or despawn item entities from the world. 

Edit: The explicit list of Sponge plugins 

* "luck perms nucleus, magibridge, nuvotifier, aurionvote listener, lag googles. and chunkgen"

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
I'm afraid I can't reproduce this, it's most likely a Sponge issue. Astral Sorcery does not offer any support to Sponge-specific issues, so I'm not sure what we can do tbh.

**Comment by Targren** [comment]
No problem. Thanks for checking into it.

**Comment by Infogive** [comment]
Using the 12.2 version. Figured out that if you craft them over to "Poor Rock Crystal" then you can drop them in world with a droper(vanila) Have not done any further testing on other droping methods, but seems like this one works. Using a combination modpack that has allowed me to make fully automated "Celestial crystal" creating (with customised crafting recipies). 

So works to use "Poor Rock Crystal". 
(know its late but playing a modpack and had problems with this, so adding it for any other unfortunate soul to meet this problem)

**Comment by Targren** [comment]
Yeah, it turned out to be a problem with sponge. I worked around it by using Integrated Dynamics to pick up and re drop the crystal every 3 minutes.
