### ISSUE TITLE
Forestry Charcoal Pit (ash) does not drop anything

### ISSUE THREAD

**Issue by KindarConrath** [NillerMedDild/Enigmatica2Expert#359]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
Building a forestry charcoal pit, and letting it run to completion, produces Ash blocks, this should (when broken) drop equal amounts of ash & charcoal. However, it drops NOTHING.

**Modpack version (Do not use "latest")**
1.41

**Logs**

If applicable, please upload your crash report, or latest.log to [hastebin](https://hastebin.com/).

**Screenshots**
https://imgur.com/gallery/ObxDQzF

**Additional context**
This shows how it SHOULD work
https://imgur.com/r/feedthebeast/oG0L4

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
Sounds like it's fixed in the latest Forestry: 
https://minecraft.curseforge.com/projects/forestry/files/2634848

**Comment by NillerMedDild** [comment]
Fixed, most likely by ^ that update.
