### ISSUE TITLE
mekanism crash

### ISSUE THREAD

**Issue by jayjones87** [NillerMedDild/Enigmatica2Expert#36]
#### Issue Description
crashing when adding the tier 1 mekanism solar panel into a tinkers crafting table to make the tier 2 solar which requires 4 of them 

#### What you expected to happen
not to crash?

#### Modpack version (Do not use "latest")
1.20
#### Your most recent crash report or log file where the issue was present

https://pastebin.com/QJEApfKw

**Comment by NillerMedDild** [comment]
Your version of the modpack is very very outdated, can you reproduce this in version 1.20?

**Comment by NillerMedDild** [comment]
I cannot reproduce it, could you supply a screenshot of the crafting station and its' whereabouts?

**Comment by NillerMedDild** [comment]
That video is for subscribers only -.-

Try disabling your texture pack and see if it still happens.

**Comment by jayjones87** [comment]
will do, looks like its a individual problem not server wide so im sure we can deal with
