### ISSUE TITLE
rocket invisible after use ender book near

### ISSUE THREAD

**Issue by anthonyL05** [NillerMedDild/Enigmatica2Expert#360]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**

When you use an ender book to teleport you near a rocket, the rocket just became invisible. When its invisible the rocket block you but you cant access to her. The only way to see her again is to log in again.

thx for this anwsome mod pack

**Modpack version (Do not use "latest")**

1.41

**Logs**

If applicable, please upload your crash report, or latest.log to [hastebin](https://hastebin.com/).

**Screenshots**

**Additional context**

**Comment by NillerMedDild** [comment]
I'm glad you like the pack :D
Are you using Optifine or VanillaFix?

**Comment by anthonyL05** [comment]
Its happend only when you already use the rocket or the elevator. if i use the ender book before ( without use them in the same session of game) it work perfectly. But after go in space and come back the ender book make them desapear.
I dont know if it can help

**Comment by NillerMedDild** [comment]
That does help, thanks.
I don't recommend that you install Optifine or VanillaFix, I asked because they can cause rendering issues.
Can you check if you are able to teleport with Journeyman when the bug occurs? I have an idea of what this issue could be.

**Comment by anthonyL05** [comment]
i will have a look when i play again. maybe tonight or tomorow

**Comment by anthonyL05** [comment]
sorry for late anserws. Cant anserws for a week. Now the game crash since i make the update will open a ticket with all information. I will make the test when i can open the game.
