### ISSUE TITLE
Boats crashing the client

### ISSUE THREAD

**Issue by jonasmh10** [NillerMedDild/Enigmatica2Expert#362]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
when we load boats on my server we crash

**Modpack version (Do not use "latest")**
1.41 

**Logs**

If applicable, please upload your crash report, or latest.log to [hastebin](https://hastebin.com/).
[crash-2018-11-02_18.00.42-client.txt](https://github.com/NillerMedDild/Enigmatica2Expert/files/2543436/crash-2018-11-02_18.00.42-client.txt)

**Screenshots**

**Additional context**

Does not happen in singleplayer, but does happen for at least 3 people on my server
Server stays running fine after the boat is placed but client crashes everytime it is loaded

**Comment by NillerMedDild** [comment]
Did this happen to be a BoP boat?

**Comment by jonasmh10** [comment]
I am pretty sure it was a regular oak boat but once I get home I'll take some time and test several types

**Comment by jonasmh10** [comment]
[BOP boat.txt](https://github.com/NillerMedDild/Enigmatica2Expert/files/2550304/BOP.boat.txt)
[IC2 electric boat.txt](https://github.com/NillerMedDild/Enigmatica2Expert/files/2550305/IC2.electric.boat.txt)
[mc oak boat.txt](https://github.com/NillerMedDild/Enigmatica2Expert/files/2550306/mc.oak.boat.txt)
[motorboat.txt](https://github.com/NillerMedDild/Enigmatica2Expert/files/2550307/motorboat.txt)
these are the boats i tried and the logs.
to me it looks like any boat

**Comment by NillerMedDild** [comment]
Cool, I'll look into it, thanks :)

**Comment by NillerMedDild** [comment]
Seems to be a common problem:
https://github.com/Glitchfiend/BiomesOPlenty/issues/1262

**Comment by jonasmh10** [comment]
looks like that fault was on my end, i redownloaded and setup the server from scratch and moved the world over and im no longer having the issue.
Sorry about that ^.^

**Comment by NillerMedDild** [comment]
No worries, it doesn't seem like you did anything wrong.

I'm glad it's fixed!
