### ISSUE TITLE
"Script Block" Generates as part of structure. Can do everything a command block can, and more.

### ISSUE THREAD

**Issue by SuperKael** [NillerMedDild/Enigmatica2Expert#367]
**Issue Description**

As part of the world-gen structure shown in the screen shot, I found a "Script Block" from Recurrent Complex (reccomplex:spawn_script). It appears to be akin to a command block with extra features. It can be mined with a pickaxe, and it's completely usable in survival mode. I confirmed by using it to spawn a zombie.

**Modpack version (Do not use "latest")**

Version 1.41

**Logs**

No applicable logs.

**Screenshots**

![2018-11-05_14 15 45](https://user-images.githubusercontent.com/10406707/48021086-aee30600-e105-11e8-99ff-df8a438d3db2.png)

**Additional context**

My world was created with cheats enabled. (I only use them to enabled keepInventory, because I prefer to play that way). This may effect why I am able to use the script block. Either way, it probably shouldn't generate there ready for the taking...

**Comment by NillerMedDild** [comment]
Thanks for the report :)
Do you happen to still be near the structure? It's name would be very helpful to have.
I believe you can use the command /#whatisthis to get the name while inside the structures bounds.

**Comment by SuperKael** [comment]
It's a "ChurchGraveyardRuins". I found the script block out on the grass around it somewhere, can't remember where exactly.

**Comment by NillerMedDild** [comment]
Cool, thanks!

**Comment by NillerMedDild** [comment]
I reported it :) I'll close the issue, since it's out of our hands.

**Comment by Ivorforce** [comment]
@SuperKael I had a look at the structure, and to me it looks like neither of the script blocks should be able to spawn (they should all disappear on structure generation).
Do you remember where exactly the script block was?

**Comment by SuperKael** [comment]
If you had asked me when I posted this, probably. It's now been over 4 months... I haven't played Enigmatica in about 3. All I remember, is that it was just randomly out in the grass, and it had nothing written in the command slot in its UI.

**Comment by Ivorforce** [comment]
Ohh I think it's actually a bug in the ruins transformer then! Thanks for the report, I should be able to fix this.
