### ISSUE TITLE
Crash when loading game, new install. 

### ISSUE THREAD

**Issue by littlejamo** [NillerMedDild/Enigmatica2Expert#368]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Desciption**

After installing the pack im greeted with a "Initializing game
java.lang.NoClassDefFoundError: net/ilexiconn/llibrary/server/core/api/LLibraryCoreAPI" on load error. This happens on both 1.41 and 1.40

**Modpack version (Do not use "latest")**
1.41 and 1.40

**Logs**

If applicable, please upload your crash report, or latest.log to [hastebin](https://hastebin.com/egunakuqig.rb).

**Screenshots**

**Additional context**

**Comment by NillerMedDild** [comment]
Reinstall, and make sure you're using Forge 1.12-14.23.5.2768 for modpack version 1.41.

**Comment by NillerMedDild** [comment]
Any new info?

**Comment by littlejamo** [comment]
Yes, sorry was at work, reinstalled again and changed the forge version to 2768 and it is working now, thanks
