### ISSUE TITLE
Replace ComputerCraft with CC: Tweaked

### ISSUE THREAD

**Issue by Jakeb89** [NillerMedDild/Enigmatica2Expert#369]
To replicate this bug, write a computercraft program with the following code:

```
rednet.open("top")
rednet.receive(5)
```

This throws an "expected number, got number" error. This bug essentially prevents a good deal of computercraft networking techniques, and has stalled my project to automate extended crafting.

The bug has already been reported to computercraft... in _January_, so I'm not really expected it to be fixed there. Is there any chance it could be fixed within this modpack?

**Comment by Jakeb89** [comment]
My game takes far too long to launch (20-30min) to test myself. : (I cc'd the email to a friend with a better computer,  asking him to try it. Sent via the Samsung Galaxy S® 6, an AT&T 4G LTE smartphone
-------- Original message --------From: Niels Pilgaard Grøndahl <notifications@github.com> Date: 11/7/18  11:25 PM  (GMT-08:00) To: NillerMedDild/Enigmatica2Expert <Enigmatica2Expert@noreply.github.com> Cc: Jakeb89 <jakeb89@gmail.com>, Author <author@noreply.github.com> Subject: Re: [NillerMedDild/Enigmatica2Expert] (Computercraft)
  Rednet.receive(timeout) causes error (#369) Could you replace ComputerCraft with CC: Tweaked and see if the issue persists? You can get it here: https://minecraft.curseforge.com/projects/cc-tweaked

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/NillerMedDild/Enigmatica2Expert","title":"NillerMedDild/Enigmatica2Expert","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/NillerMedDild/Enigmatica2Expert"}},"updates":{"snippets":[{"icon":"PERSON","message":"@NillerMedDild in #369: Could you replace ComputerCraft with CC: Tweaked and see if the issue persists? You can get it here: https://minecraft.curseforge.com/projects/cc-tweaked"}],"action":{"name":"View Issue","url":"https://github.com/NillerMedDild/Enigmatica2Expert/issues/369#issuecomment-436898030"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/NillerMedDild/Enigmatica2Expert/issues/369#issuecomment-436898030",
"url": "https://github.com/NillerMedDild/Enigmatica2Expert/issues/369#issuecomment-436898030",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [NillerMedDild/Enigmatica2Expert] (Computercraft) Rednet.receive(timeout) causes error (#369)",
"sections": [
{
"text": "",
"activityTitle": "**Niels Pilgaard Grøndahl**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@NillerMedDild",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"NillerMedDild/Enigmatica2Expert\",\n\"issueId\": 369,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"NillerMedDild/Enigmatica2Expert\",\n\"issueId\": 369\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/NillerMedDild/Enigmatica2Expert/issues/369#issuecomment-436898030"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 407897382\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by Jakeb89** [comment]
Friend with the better computer here. Loaded up a local creative world, and
CC:Tweaked does not appear to have this issue, based on the quick test
jakeb89 had me run.

I did have a concern: would replacing that on an existing world cause
block/item ID issues with existing blocks/items?

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by NillerMedDild** [comment]
It would not, CC: Tweaked is simply a fork of ComputerCraft with more features and bugfixes :) I already did it on Enigmatica 2 without issues. I'll make the change for the next update.

**Comment by NillerMedDild** [comment]
Thanks for testing it btw!
