### ISSUE TITLE
Tinker's Complement hammer crash

### ISSUE THREAD

**Issue by givepiesachance** [NillerMedDild/Enigmatica2Expert#37]
#### Issue Description
The game crashes when I equip a tinker's complement hammer (the ex nihilo one, not the 3x3 mining one).  The crash occurs as soon as I put the hammer in my hands.

#### Modpack version (Do not use "latest")
1.20

#### Your most recent crash report or log file where the issue was present

https://pastebin.com/S67zm1Nc

**Comment by NillerMedDild** [comment]
The issue has been fixed, will be in the next update :)
