### ISSUE TITLE
CraftTweaker Incorrect Item Names

### ISSUE THREAD

**Issue by GeoTerra** [NillerMedDild/Enigmatica2Expert#371]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
Two item names in Tinker I/O have changed, causing the TinkersConstrct.zs script to error out. Offending lines are 108 and 109 (at least, those are the line numbers for me). Name changes follow. I have already fixed these in my local copy of the pack.

tinker_io:speed_upg --> tinker_io:speedupg
tinker_io:solid_fuel --> tinker_io:solidfuel

**Modpack version (Do not use "latest")**
Version 1.42a

**Logs**

N/A

**Screenshots**

N/A

**Additional context**
N/A

**Comment by GeoTerra** [comment]
Ah, my mistake. I must've been on auto-pilot when I updated to E2E v1.42a and was looking through the mods list.

My sincerest apologies.

**Comment by NillerMedDild** [comment]
I know that feeling :P no worries, thanks for the report anyway.
