### ISSUE TITLE
Immersive Engineering Razor Wire does not break

### ISSUE THREAD

**Issue by M3wM3w** [NillerMedDild/Enigmatica2Expert#372]
**Issue Description**
Immersive Engineering Razor Wire is unbreakable. Even with wire cutters.
Only TNT was able to break it.

**Modpack version (Do not use "latest")**
1.41

**Comment by Chunkey** [comment]
I can confirm this is still an issue on 1.42a.

**Comment by NillerMedDild** [comment]
Thanks :) I'll look into it.

**Comment by drakkensong21** [comment]
Are you using the wire cutters to try and brake them

**Comment by drakkensong21** [comment]
Never mind im dumb

**Comment by NillerMedDild** [comment]
Fixed, most likely by the latest Tool Progression update.

**Comment by FlyingThunder** [comment]
To any confused lost soul stumbling over this while googling this issue: You need to destroy it with the Immersive Engineering "Engineer´s Wire Cutters"
