### ISSUE TITLE
Duplication

### ISSUE THREAD

**Issue by madkingdiamond** [NillerMedDild/Enigmatica2Expert#375]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
 In the tinker's crafting station. If 2 people grab the item being crafted at the same time it duplicates the item.

**Modpack version (Do not use "latest")**
1.41 (I don't know if this is solved in newer versions as we will be updating today)

**Logs**

If applicable, please upload your crash report, or latest.log to [hastebin](https://hastebin.com/).

**Screenshots**

**Additional context**

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
It has been reported a long time ago, doesn't look like it will be fixed tbh.
https://github.com/SlimeKnights/TinkersConstruct/issues/3460

**Comment by NillerMedDild** [comment]
The exact same logic applies though. An inventory contains an item, two players take that item at the same time, thus duping it.
