### ISSUE TITLE
Game crash after update version

### ISSUE THREAD

**Issue by anthonyL05** [NillerMedDild/Enigmatica2Expert#376]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
I use the twitch lancher and make the update. Since when i open the game i can play just a litle (the game crash near directly if i dont open it) or after i open my inventory ( i try to open a chest or me system and the game crash when i close them).
I try to anderstand the log but i didnt know what kind of problem can cause this issu.

try for helping me to solve this issu.

**Modpack version (Do not use "latest")**

version 1.42a

**Logs**

https://pastebin.com/LmzT9wAs

**Screenshots**

**Additional context**

**Comment by NillerMedDild** [comment]
Reset your keybindings and try again, or simply reinstall the pack :)

**Comment by NillerMedDild** [comment]
Please let me know if it works.

**Comment by anthonyL05** [comment]
thx by reinstall the pack it work after! i only make refresh the pack not reinstall the full pack.

**Comment by NillerMedDild** [comment]
Cool :)
