### ISSUE TITLE
Wrenching any tier of crafter from RFTools with a crescent hammer destroys the crafter

### ISSUE THREAD

**Issue by Celebrimbatch** [NillerMedDild/Enigmatica2Expert#379]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Question or Issue**
Wrenching up a crafter (any tier) completely destroys the crafter in question when using a crescent hammer

**Modpack Version**
1.41

**Additional Context**

**Comment by NillerMedDild** [comment]
This was just fixed luckily :) Thanks for the report anyway.
