### ISSUE TITLE
Astral Resonating Wand not Showing Rock Crystals

### ISSUE THREAD

**Issue by scotty9090** [NillerMedDild/Enigmatica2Expert#38]
#### Issue Description
Holding the resonating wand at night, I'm not seeing any "plumes" that indicate the presence of rock crystal ore.  I finally switched to creative and flew all over the map, to see if I was just getting unlucky and still no luck.

Is this disabled in the pack or am I missing something else?

#### What you expected to happen
Expected to see indications of rock crystal while holding the resonating wand

#### Modpack version (Do not use "latest")
1.20

**Comment by NillerMedDild** [comment]
Due to a bug in the config of Astral Sorcery, Rock Crystal generation was turned off. 
They will spawn again in the next update.
