### ISSUE TITLE
CC bundled redstone output not reaching enderio cables

### ISSUE THREAD

**Issue by Jakeb89** [NillerMedDild/Enigmatica2Expert#381]
I'm currently trying to output bundled redstone signal to an EnderIO cable using ComputerCraft.

![image](https://user-images.githubusercontent.com/1346278/48369888-9e361100-e66c-11e8-93e6-a40b6346e07e.png)
![image](https://user-images.githubusercontent.com/1346278/48369929-c02f9380-e66c-11e8-95b5-44170a7d84df.png)

If I'm doing this incorrectly, please let me know how, but as far as I can tell the EnderIO conduit just doesn't accept bundled redstone signal from computercraft.

Note: Outputting a generic on/off redstone signal using brown input and output conduits did work.

**Comment by Jakeb89** [comment]
...no? That's just me resetting it to off on all colors before I try to
turn on brown.

**Comment by NillerMedDild** [comment]
https://github.com/dan200/ComputerCraft/issues/581

**Comment by NillerMedDild** [comment]
The folks at EnderIO's decided to stop supporting ComputerCraft a few months back, as it was getting harder and harder to do.
