### ISSUE TITLE
Multiplayer Advanced Rocketry not showing any planet

### ISSUE THREAD

**Issue by Celebrimbatch** [NillerMedDild/Enigmatica2Expert#382]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
In multiplayer we have a rocket set up, fueled with a guidance computer but when we view the planet list it shows no planets other than Earth so we can't go to Luna for Dilithium, however in singleplayer with the exact same set up Luna is there.

**Modpack version (Do not use "latest")**
1.41

**Logs**
/advRocketry planet list
lists all the planets for the multiplayer server

If applicable, please upload your crash report, or latest.log to [hastebin](https://hastebin.com/).

**Screenshots**
https://i.imgur.com/o53sJCA.png - Multiplayer server

https://i.imgur.com/HhbXd9L.png - Singleplayer 

**Additional context**

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.
Is your server using SpongeForge?

**Comment by Celebrimbatch** [comment]
Aye it is using Sponge.

**Comment by NillerMedDild** [comment]
Damn I thought so. I cannot reproduce this issue without Sponge.

**Comment by NillerMedDild** [comment]
Do any planets generate?

**Comment by Celebrimbatch** [comment]
Aye running the command shows the planets in that list but when looking in the planet select screen no planets are there :/

**Comment by NillerMedDild** [comment]
Replace your advancedRocketry.cfg file's contents with that of the link below:
https://gist.github.com/NillerMedDild/1c3172f8b81890086fafc45b7b5f8c6d

It should be done on both client and server - I hope it works :)

**Comment by Celebrimbatch** [comment]
Would all players need to change their configs? We have a lot of players on the server so that might be an issue

**Comment by NillerMedDild** [comment]
I'm not sure to be honest, possibly.

**Comment by Celebrimbatch** [comment]
The server owner has applied the new config on the server and I've done the same to my client the issue is still persistent :/

**Comment by NillerMedDild** [comment]
Damnit :(

**Comment by Celebrimbatch** [comment]
Any other ideas to try and get this working? ;-;

**Comment by Celebrimbatch** [comment]
Do the planets have permissions?

**Comment by Celebrimbatch** [comment]
From a recent issue on the AdvancedRocketry Github https://github.com/zmaster587/AdvancedRocketry/issues/1439 
there appears to be a temporary fix, will come back here once we've tried it to see if it works.

**Comment by Celebrimbatch** [comment]
Just looking again it looks like that's a code patch so you might need to edit the pack to include that fix, as it is right now we need to wait for a fix :/

**Comment by NillerMedDild** [comment]
It looks like you could apply the fix for your server, and that would be it.

**Comment by Celebrimbatch** [comment]
How would we apply the fix to the server? I'm not the server owner actually haha

**Comment by NillerMedDild** [comment]
Your server owner would have to do it.
