### ISSUE TITLE
Quantum Entangloporters exploding.

### ISSUE THREAD

**Issue by SuperKael** [NillerMedDild/Enigmatica2Expert#389]
**Issue Description**

The Quantum Entangloporters keep randomly exploding... Sometimes on world load, other times for seemingly no reason at all. When this occurs, there is no real block damage or anything. The Quantum Entangloporter dissapears, and there is an explosion particle effect and sound.

**Modpack version (Do not use "latest")**

Version 1.42a

**Logs**

No applicable logs.

**Screenshots**

Hard to catch a screenshot when it happens at complete random, and I have been unable to reliably reproduce it...

**Additional context**

Most frequently, it is the entangloporter connected directly to my NuclearCraft fusion reactor that explodes. However, there have been a couple incidents where entangloporters that are receiving power from the reactor, rather than sending, explode.

**Comment by NillerMedDild** [comment]
Errr... what. Quantum Entangloporters don't even have an explode feature.

**Comment by SuperKael** [comment]
I know they aren't supposed to... but they definitely are. I just got back on after leaving the game running overnight, and I came back to find that my void miner had shut down because the entangloporter on my reactor exploded again. The problem definitely exists, but I have no clue why... :/ Really sorry about the vague issue, but I didn't know what else to do.

**Comment by NillerMedDild** [comment]
Alright, I'll look into it :)

**Comment by SuperKael** [comment]
Thanks! And sorry for the undoubtedly very difficult issue.

**Comment by NillerMedDild** [comment]
I'm hoping it's some weird easter egg :P Could I get some screenshot of the setups where the Quantum Entangloporter has previously exploded?

**Comment by SuperKael** [comment]
The main offender. I think this one has blown up 4 times?
![2018-11-18_13 46 06](https://user-images.githubusercontent.com/10406707/48676704-721d0300-eb38-11e8-9825-a127c576405a.png)
Blew up once. I carved out part of my wall so that you can see that it's connected to the Matter Fabricator.
![2018-11-18_13 46 21](https://user-images.githubusercontent.com/10406707/48676705-72b59980-eb38-11e8-8c95-c4c58a97abe3.png)
Used to have one here, no longer do. Imagine the Crafting Unit is the Entangloporter. It blew up once.
![2018-11-18_13 46 35](https://user-images.githubusercontent.com/10406707/48676706-72b59980-eb38-11e8-8a32-402a0e1891fd.png)
Once again, used to have one here. I since replaced it with an energy trashcan, since I no longer need power from the fission reactor.
![2018-11-18_13 46 49](https://user-images.githubusercontent.com/10406707/48676707-72b59980-eb38-11e8-9f6b-a69c11bd603f.png)

**Comment by NillerMedDild** [comment]
https://github.com/aidancbrady/Mekanism/issues/5199

**Comment by tyler489** [comment]
Hmm do you have enderio machines near them?

**Comment by NillerMedDild** [comment]
Answer from the Mechanism repository: Exploding is an IC2 thing. You're probably putting too much power through the Quantum Entangloporter, as far as IC2 is concerned.

**Comment by SuperKael** [comment]
Hm... That's very weird, although I suppose that makes more sense than anything else. Is the explosion somehow conducting through the entangloporter network? o_O

**Comment by SuperKael** [comment]
I guess I may as well close this now, since it's not really relevant anymore. Thanks for your time.
