### ISSUE TITLE
Immersive Engineering Pumpjack stuck

### ISSUE THREAD

**Issue by JordanGalbas** [NillerMedDild/Enigmatica2Expert#39]
Everything is hooked up perfectly, I tried it on creative with the same set up and it worked like a charm, but for some reason, when I try to do the same thing in my survival game, it will pump one crude oil bucket then stop working even if its full of power. What I do right now is I destroy one of the block of the pumpjack then put it back and it will again pump only one bucket then get stuck again.

I use a HV capacitor with HV cable for power and the capacitor is fully charged.

**Comment by NillerMedDild** [comment]
Why did you delete the issue template? It's there for a reason.

Maybe the reservoir you've found contains multiple fluids.

**Comment by NillerMedDild** [comment]
Closed due to inactivity.
