### ISSUE TITLE
IC2 Compressor Lapis Block

### ISSUE THREAD

**Issue by Jomeaga** [NillerMedDild/Enigmatica2Expert#390]
**Issue Description**
Can no longer run lapis through the IC2 compressor for Lapis Blocks

**Modpack version (Do not use "latest")**
1.42a

**Comment by NillerMedDild** [comment]
I believe this will be fixed by updating IC2 in the next update, as they made a caching feature for their recipes, but added it before it was functional.

**Comment by NillerMedDild** [comment]
Reported here: https://bt.industrial-craft.net/view.php?id=2445
