### ISSUE TITLE
IC2 Machines disappearing

### ISSUE THREAD

**Issue by ImberProduct** [NillerMedDild/Enigmatica2Expert#396]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
After some time any IC2 Machine is just disappearing without writing something in the log.

**Modpack version (Do not use "latest")**
1.42a ( edited)

**Logs**

**Screenshots**

**Additional context**

The Machines which this happends are Ic2 Macerator and Ic2 Generator. Yes they are powered and chunkloaded. This happends 3 times already, but never when u where looking at them. it is just that u turn arround and look back that they dissapeard in the process.

**Comment by NillerMedDild** [comment]
There is no version 1.4, which version are you on? :)

**Comment by ImberProduct** [comment]
Sry, m8 gave me the wrong number

https://imgur.com/a/839qqKF

**Comment by NillerMedDild** [comment]
Which machine? How is it getting power? Is it chunkloaded? How often does it occur?

**Comment by ImberProduct** [comment]
The Machines which this happends are Ic2 Macerator and Ic2 Generator. Yes they are powered and chunkloaded. This happends 3 times already, but never when u where looking at them. it is just that u turn arround and look back that they dissapeard in the process.

**Comment by NillerMedDild** [comment]
Could they have blown up?
