### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by MattyyyG** [NillerMedDild/Enigmatica2Expert#397]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
Server crash after nighttime starts

**Modpack version (Do not use "latest")**
1.42a

**Logs**

If applicable, please upload your crash report, or latest.log to [hastebin](https://hastebin.com/).
https://hastebin.com/axamirolig.sql
**Screenshots**

**Additional context**

Pretty much at the start of the pack, only 2 players on the start of the 2nd night, started lagging heavily and then crashed the server.

**Comment by NillerMedDild** [comment]
That's.. odd. It appears some worldgeneration is going wrong.

Set the `max-tick-time` to -1 in `server.properties` :)

**Comment by NillerMedDild** [comment]
Did you resolve your issue?
