### ISSUE TITLE
Possibly add Equivalent Exchange

### ISSUE THREAD

**Issue by bluntzultimat3** [NillerMedDild/Enigmatica2Expert#398]
So a silly idea but worth asking for it nonetheless, why don't we add EE2 to the pack as an endgame mod, gated behind the very end game mods.

It would be fun to have it and mess around with it once your end game, that's really the only reason why haha

**Comment by NillerMedDild** [comment]
I'm sorry but no :) I feel like that's been done a hundred times before, and wouldn't offer much in terms of gameplay.

**Comment by NillerMedDild** [comment]
Oh, and EE2 isn't on 1.12.2. I'm assuming you meant Project E :)

**Comment by bluntzultimat3** [comment]
Yeh that's what I meant lol, not long out of a surgery so heads messed up haha. It would be more for end game messing around with stuff, like have it locked behind quests or something

**Comment by bluntzultimat3** [comment]
Also, another idea. Can we get acceleration wands added to the pack hahahaha

**Comment by bluntzultimat3** [comment]
Not tps effectively haha, think of the poor servers man. The poor servers 😂

**Comment by NillerMedDild** [comment]
Nope!

**Comment by bluntzultimat3** [comment]
Damn haha, I think acceleration wand is a good shout though
