### ISSUE TITLE
world loading crash

### ISSUE THREAD

**Issue by Egorzhill** [NillerMedDild/Enigmatica2Expert#399]
***Issue Description***

Minecraft crashing while map is loading

***Modpack version***

1.42a 

***Logs***

(not full) https://hastebin.com/kigomikoqe.md
(full log) [2018-11-24-1.log](https://github.com/NillerMedDild/Enigmatica2Expert/files/2612211/2018-11-24-1.log)

***Additional context***

Allocated 6 gb of mem. If it caused by "advRocketry/planetDefs.xml" can i just delete this file, without corrupting world?

**Comment by NillerMedDild** [comment]
It appears a file has corrupted. Delete `/E:/KUBACHGIVNO/Instances/Enigmatica%202%20Expert/saves/New%20World-/advRocketry/planetDefs.xml` and relaunch :)
