### ISSUE TITLE
Wood gear applied energistics conflict recipe (1.03a)

### ISSUE THREAD

**Issue by Electrofried** [NillerMedDild/Enigmatica2Expert#4]
#### Issue Description

Wood gears from applied energistics conflicts with other recipe

#### What you expected to happen

Craft wood gears

#### Modpack version (Do not use "latest")

Latest 1.03a

#### Your most recent log file where the issue was present

No need for log, easy to reproduce. Current work around is to use forestry work table for conflicts.

[pastebin/gist/etc link here]

**Comment by NillerMedDild** [comment]
Thanks for the report, fixed in dev.
