### ISSUE TITLE
Black Hole Unit Autocrafting

### ISSUE THREAD

**Issue by bluntzultimat3** [NillerMedDild/Enigmatica2Expert#400]
## Thank you for helping us improve. #####

**Issue Description**

As the title says, the black hole unit gets stuck on autocraft with AE2

**Modpack version (Do not use "latest")**

1.42a

**Logs**

N/A

**Screenshots**

https://i.imgur.com/gIOy3Uq.png

**Comment by NillerMedDild** [comment]
Try in 1.43.
