### ISSUE TITLE
Woot?!

### ISSUE THREAD

**Issue by bluntzultimat3** [NillerMedDild/Enigmatica2Expert#401]
**Is your feature request related to a problem? Please describe.**

Im always frustrated when you have a server and there are loads of people join, play for so long then leave, most of the time after they make a mob farm. Which causes lag, yes a small amount but it adds up

**Describe the solution you'd like**

Can we get the mod Woot added to the pack, more for server's stability than anything else

**Additional context**

https://minecraft.curseforge.com/projects/woot

I suggest if this is added to crank the power usage up also?

**Comment by NillerMedDild** [comment]
I doubt Woot would help on server lag, unless ofcourse all the players are awful at making sure mobs/items are removed. To be honest, I don't like the concept of Woot at all, and don't see a need for it in the pack.
