### ISSUE TITLE
IC2 Items + Crafting Tables = Problems

### ISSUE THREAD

**Issue by mtimyself** [NillerMedDild/Enigmatica2Expert#402]
**Issue Description**
When placing an IC2 item (e.g. non-insulated copper cable) inside a TC crafting table the client crashes.
A pair of scissors disappears and other nasty things happen for other items.
Using a Workbench from Cyclic placing a copper cable inside and walking away does not result in a crash but the GUI can not re-opened.
The only one we found to be working is the vanilla table

**Modpack version (Do not use "latest")**
1.43

**Logs**
https://pastebin.com/X6yGB6qX

**Screenshots**

N/A

**Additional context**

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

Also, excellent title xD

**Comment by NillerMedDild** [comment]
https://github.com/CraftTweaker/CraftTweaker/issues/678

**Comment by NillerMedDild** [comment]
The issue was on my end, should be fixed now :)
