### ISSUE TITLE
Me capability adapter 

### ISSUE THREAD

**Issue by zaekeon** [NillerMedDild/Enigmatica2Expert#404]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Question or Issue**
Have you considered adding this mod to the pack so that ME cables can be used with compact machines?  It could be made semi expensive like a TE frame etc.

**Modpack Version**
1.43

**Additional Context**

https://minecraft.curseforge.com/projects/capability-adapter

**Comment by NillerMedDild** [comment]
Yes, I considered it and I added it several updates ago. It's in the pack.

**Comment by zaekeon** [comment]
Ah excellent.  I did not see it on the mod list in the description.  Thank
you!

**Comment by NillerMedDild** [comment]
Oh right, I need to update that. Thanks!
