### ISSUE TITLE
Game crash when overflowing inventory from bag of holding

### ISSUE THREAD

**Issue by bokke1010** [NillerMedDild/Enigmatica2Expert#406]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**

Game crashes when using either shift-drag or shift-double-click to quickly move items from bag of holding into inventory when amount moved is larger than available space in inventory.
(for example, shift-double-click 9 stacks of cobble into the inventory when you only have 6 empty places)

**Modpack version (Do not use "latest")**

1.43

**Logs**

No visible crash report in the crash-reports folder. If it can be somewhere else, please tell me

**Screenshots**

Not applicable

**Additional context**

Not applicable

**Comment by NillerMedDild** [comment]
I would like your latest.log instead of the crash report please :)

**Comment by bokke1010** [comment]
Too long for hastebin, linking the file via drive:
https://drive.google.com/file/d/1VbroCUAdi45CsioiBci-J9uFDUdsdBMw/view?usp=sharing
Latest only generates after the instance is closed, right? (otherwise, this might not be the right log)

**Comment by NillerMedDild** [comment]
I'd like the file itself, or that you upload it it gist.github.com then - For security reasons, I don't want to download a file.
Latest.log generates while the instance runs, from start to finish.

**Comment by bokke1010** [comment]
While you do not need to download a txt with drive to read it, I understand your concerns.
Besides, it was the incorrect log then anyways, this should be the correct one:
https://gist.github.com/bokke1010/14f2d4e719fb77b33214fc2c8a21b240

**Comment by NillerMedDild** [comment]
So... there's no crash in that log :P

**Comment by bokke1010** [comment]
Just made sure everything was well documented on my end:

- Managed to easily reproduce the crash

- Confirmed the game produces no crash report (crash-reports folder has no new files)
![capture](https://user-images.githubusercontent.com/15060976/48984336-bdb44b80-f0fa-11e8-94cf-22de67d7751a.PNG)

- confirmed the latest log was the one with the issue
https://gist.github.com/bokke1010/f3ba380806e89f1fa4f77cfdb999ebbb

**Comment by NillerMedDild** [comment]
Alright, it makes a bit more sense when it becomes non-responsive. I'll report it to Extra Utils and hope for the best :)

**Comment by NillerMedDild** [comment]
https://github.com/rwtema/Extra-Utilities-2-Source/issues/228 Someone else reported it \o/

**Comment by Ricket** [comment]
This is listed as fixed in the latest changelog, but to be clear it's not actually fixed right?
