### ISSUE TITLE
Flux Network's 

### ISSUE THREAD

**Issue by bluntzultimat3** [NillerMedDild/Enigmatica2Expert#407]
**Is your feature request related to a problem? Please describe.**

I'm frustrated with trying to get a quantum entangaloper to do power transfer the way I want, all the messing around with side config ect. Power cells just don't have enough threw put and conduits lag the server way to bad

**Describe the solution you'd like**

I know it's been spoken about before but I really think it's a good idea to add flux Network's to the pack? Would help with so many different issues people have :) 

**Additional context**

Will send you a bottle of whisky from Scotland if you do ;)

**Comment by NillerMedDild** [comment]
Tempting, I'll think it over :)

**Comment by bluntzultimat3** [comment]
Why thank you good sir :)

**Comment by zaekeon** [comment]
Thank you.  This would help with issues I’m encountering as well.

**Comment by bluntzultimat3** [comment]
I've started having issues with power transfer myself now also...

**Comment by NillerMedDild** [comment]
I've decided I will add Flux Network, but implementing it will probably take a while, as I'm very busy with irl atm :)

**Comment by bluntzultimat3** [comment]
Yaaayyyyyyy haha and hope everything okay buddy :(

**Comment by NillerMedDild** [comment]
Everything is fine, I'm just entering the final weeks of my exam period - Thanks for the concern :D

**Comment by bluntzultimat3** [comment]
Well good luck my friend :D You will do fine ;) and no worries haha

**Comment by bluntzultimat3** [comment]
Also, on the note of adding a mod, Acceleration wand? COUGH COUGH

or torcherino with a modified recipe to use like a benotite? I prefer this method <---

**Comment by drakkensong21** [comment]
There are already ways to speed up ticks in the pack

**Comment by bluntzultimat3** [comment]
Like what haha?

**Comment by drakkensong21** [comment]
There is an astral sorcery ritual that does that iirc

**Comment by NillerMedDild** [comment]
Yep, the Horologium ritual from Astral Sorcery.

**Comment by NillerMedDild** [comment]
I won't be adding more tick acceleration option, it's an unsafe feature.

**Comment by bluntzultimat3** [comment]
But really we only have one aha?

**Comment by NillerMedDild** [comment]
As far as I know, yep.

**Comment by bluntzultimat3** [comment]
That's not enough haha

**Comment by drakkensong21** [comment]
why would niller want to add more mods that do the same thing

**Comment by bluntzultimat3** [comment]
Granted the torcherino is only that but still aha... Make it stupidly expensive like using ultimate ingots haha

**Comment by TheWiz4rdZ** [comment]
There is the Time in a Bottle from Random Things as well, and it is extremely cheap to craft one of them

**Comment by bluntzultimat3** [comment]
i tried the time in a bottle but that is nothing automatable aha :( Im looking for something that i can set it down and use without worry. it saves me having to use a bunch of thermal mediators with loads of pipes running fluids everywhere... making heavy lag for the server

**Comment by NillerMedDild** [comment]
The lag from a tick accelerator would be far worse, unless your setup is extremely bad.

**Comment by bluntzultimat3** [comment]
Well I would need 6 thermal mediators per machine so each would be piped up plus the maga crucibles to keep up with all of them so even more pipes and power pipes aha

**Comment by bluntzultimat3** [comment]
can we get this added in 1.45 stable btw? or is it still in the works

**Comment by NillerMedDild** [comment]
Still in the works

**Comment by bluntzultimat3** [comment]
No worries 👍
