### ISSUE TITLE
Sponge causing server to continuously crash

### ISSUE THREAD

**Issue by sonic1238** [NillerMedDild/Enigmatica2Expert#409]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**

i am trying to install sponge on my server so my players can use /home set and such, but installing sponge makes the server stay in a startup loop, always crashes,

**Modpack version (Do not use "latest")**

i've tried latest(Enigmatica 2: Expert 1.43) and even Enigmatica 2: Expert 1.42a but they both result in the server crashing 

**Logs**
https://hastebin.com/tadunekeli.sql - This is what i got from the crash report from the server

**Screenshots**

**Additional context**

**Comment by NillerMedDild** [comment]
Removing the player.data of `CelestialPhantom` should remedy the issue :)
