### ISSUE TITLE
tinkers construct/ic2 crash

### ISSUE THREAD

**Issue by Rubijox** [NillerMedDild/Enigmatica2Expert#412]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Question or Issue**
Game crashing when placing  ic2 tin/copper cables(insulated and non insulated) in a tinkers construct crafting station
i haven't tested other types of cables yet but i assume the same thing will happen too.

Crafting works just fine using a regular crafting table, so ill use that instead for now.

**Modpack Version**
1.43

**Additional Context**
I am playing on a server, the client crashes while the server stays up, when i log back in the items are on the ground near the crafting station

Here are the crash reports i got
https://pastebin.com/CkLqAcsb
Optifine removed: https://pastebin.com/zE3tBJQf

**Comment by Rubijox** [comment]
well, i guess this is a copy of https://github.com/NillerMedDild/Enigmatica2Expert/issues/402 , sorry i missed that when i looked

**Comment by NillerMedDild** [comment]
No worries :)
