### ISSUE TITLE
server desync

### ISSUE THREAD

**Issue by FrankyixH** [NillerMedDild/Enigmatica2Expert#414]
**Issue Description**
Playing on a rented server
I have extreme delay (1-2 minutes) when opening inventorys, taking damage etc

**Modpack version**
First 1.42a, now 1.44

**Additional context**
We are playing the pack on a server.
It ran fine for a week. Suddenly i have extreme desync with the server: when i open a inventory for example it opens up about 2 minutes later. Same with opening machines, taking damage, chat messages and i see the position of a friend im playing with also delayed. He has no issues at all and sees my actions in real time.
After updating the pack from 1.42a to 1.44 it was fine for about 2 hours and then started again as 10 sec delay and is now up again to about 1-2 minutes.

I tried restarting my game, my pc, reinstalling the game, reinstalling the server, restarting the server but nothing seems to work.

I would be very happy if you know a solution

**Comment by NillerMedDild** [comment]
Sounds like your internet connection is unstable.

**Comment by FrankyixH** [comment]
thanks for the fast response
usually not, i have a speed of about 13 mb/s constantly and while this dsync appears discord and music streaming work fine
also turning everything else off changes nothing

**Comment by NillerMedDild** [comment]
Cool, good luck :) You're testing on the server, right?

**Comment by FrankyixH** [comment]
yeah sure
ok appearently minecraft does indeed use up my complete connection, we'll try removing our mobfarm and some machines, that should fix it.
I have never experienced desync or lag this bad in any other modpacks, so i just assumed it was a modpack-issue.
Thanks for your help :)
This can be closed

**Comment by NillerMedDild** [comment]
It is somewhat modpack related, I'm trying to fix the overuse of network bandwidth :)
