### ISSUE TITLE
Creosote oil can uses not showing in jei

### ISSUE THREAD

**Issue by Rubijox** [NillerMedDild/Enigmatica2Expert#415]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
The Creosote oil can from forestry (<forestry:can:1>.withTag({Fluid: {FluidName: "creosote", Amount: 1000}})) doesnt show its uses for regular crafting when you press U on it in your inventory, the only recipe showing is one for the Bottler,
The cans themselves also dont show at all in jei, not any of them, not even the empty ones

The item can still be used in recipes using creosote even though recipes are hidden

**Modpack version (Do not use "latest")**
1.44

**Logs**

If applicable, please upload your crash report, or latest.log to [hastebin](https://hastebin.com/).

**Screenshots**

https://i.imgur.com/C0gY409.png
https://i.imgur.com/uDzeQdj.png
**Additional [context**]

**Comment by NillerMedDild** [comment]
They're indeed hidden from JEI. I don't know why they don't show usage, but I suspect it's a design choice and not a bug, to reduce the amount of redundant JEI entries.
