### ISSUE TITLE
Crash on World Load

### ISSUE THREAD

**Issue by Issidro23** [NillerMedDild/Enigmatica2Expert#42]
#### Issue Description
After loading a world in single player (new or existing,) the game crashes.
#### What you expected to happen
The world to load.
#### Modpack version (Do not use "latest")
1.20
#### Your most recent crash report or log file where the issue was present

https://gist.github.com/Issidro23/f78678932588fe75d0c5c1df3803ccc8

**Comment by Issidro23** [comment]
I re-downloaded the pack and was able to create a new world without crashing. I still wasn't able to load into my old world until I copied over the planetDefs.xml file located in the Instances/Enigmatica 2 Expert/saves/New World/advRocketry folder from the world I created after a fresh install.

Not sure if I should close this as I am new to github and don't know the proper etiquette.

**Comment by NillerMedDild** [comment]
The planetDefs.xml file has a tendency to corrupt for some reason, as you found out. Nice you fixed it yourself!

In this case, the crash log would be the file to link to, not the latest.log, but extra points for effort :p
Generally I find that It's up to you whether to close an issue or not, unless it's reopened.

Anyway, I appreciate the report, and welcome to Github!
