### ISSUE TITLE
Storage Scanner RFTOOLS

### ISSUE THREAD

**Issue by SuperFurias** [NillerMedDild/Enigmatica2Expert#420]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
RFTOOLS Storage Scanner eat items

**Modpack version (Do not use "latest")**
1.44

**Logs**
IDK
If applicable, please upload your crash report, or latest.log to [hastebin](https://hastebin.com/).
Nothing
**Screenshots**
Nothing
Nothing
**Additional context**
Storage scanner RFTOOLS eat items when, For example, An item have two items possible to craft an item. Example:
Macerator. You can craft it with Electronic Circuit or with Basic Control Circuit. If you try to craft in the Storage Scanner but you have 1 Basic Control Circuit (and 0 Electronic Circuits) The storage scanner try to craft the item but somehow it can not complete the crafting, it removes the rest of the items from the inventories but you do not get the macerator
Help me

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
https://github.com/McJtyMods/RFTools/issues/1748

**Comment by NillerMedDild** [comment]
Which blocks are you using as storage?

**Comment by SuperFurias** [comment]
Storage crates and modular storages

**Comment by NillerMedDild** [comment]
I suggest switching to only Modular Storages or vanilla-style chests. 
I was not able to reproduce the issue.
