### ISSUE TITLE
Duplication with IC2 Compressor

### ISSUE THREAD

**Issue by SuperFurias** [NillerMedDild/Enigmatica2Expert#421]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
The Compressor from IC2 transform a lapis lazuli piece into a lapis lazuli block.

**Modpack version (Do not use "latest")**
1.44

**Logs**
no
If applicable, please upload your crash report, or latest.log to [hastebin](https://hastebin.com/).

**Screenshots**
no

**Additional context**
Please fix again

**Comment by NillerMedDild** [comment]
Thank you for the report, it has been reported to the mod developer :)
https://bt.industrial-craft.net/view.php?id=2451

**Comment by NillerMedDild** [comment]
Closed because there's nothing more I can do, it will be fixed by the mod dev.

**Comment by NillerMedDild** [comment]
I received a report that this wasn't fixed, but it is.
