### ISSUE TITLE
OpenComputers Microchip (Tier 3) should be craftable using nuggetDiamond

### ISSUE THREAD

**Issue by ToasterKoishi** [NillerMedDild/Enigmatica2Expert#422]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**

Microchip (Tier 3) from OpenComputers can only be crafted using `chipDiamond`. A compacting drawer will default to breaking down diamonds into Extended Crafting diamond nuggets, which only oredict into `nuggetDiamond`. However, in a crafting table, a diamond is crafted into Thermal Foundation diamond nuggets, which oredict into both `nuggetDiamond` and `chipDiamond`.

My most immediate problem was apparently not being able to craft the microchip using the diamond nuggets in my ME system (storage bus on a drawer). Closer inspection of the oredict names revealed the problem.

I see three possible solutions:
- Make the microchip craftable with `nuggetDiamond`
- Make compacting drawers break diamonds into Thermal Foundation nuggets by defaut
- Add `chipDiamond` to Extended Crafting nugget oredict

**Modpack version (Do not use "latest")**

1.44

**Logs**

If applicable, please upload your crash report, or latest.log to [hastebin](https://hastebin.com/).

**Screenshots**

**Additional context**

**Comment by NillerMedDild** [comment]
Thank you for the thorough report :) I will combine option 1 and 2 that you propose.

**Comment by NillerMedDild** [comment]
The Microchip Tier 3 already accepts `nuggetDiamond`.
I changed the Compacting Drawer conversion to thermalfoundation as suggested.
