### ISSUE TITLE
Crash twice in 3 hours, but don't know why... (You can look my stream redif, if needed)

### ISSUE THREAD

**Issue by Fireztonez** [NillerMedDild/Enigmatica2Expert#424]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
The modpack crash twice, in about 3 hours, the first time, I have not do anything, and the game crash, and the second time I just do somes craft in the Tinker Crafting table, for the Machine Case fro Industrial Forgoing... I never crash with the 1.42a (Before I upgrade the modpack)...

**Modpack version (Do not use "latest")**
1.44

https://gist.github.com/Fireztonez/f7f5f9db25a8553eb791d871733d4bc3
https://gist.github.com/Fireztonez/783c5e6a17906b04d5e4b54e3b044202

If applicable, please upload your crash report, or latest.log to [hastebin](https://hastebin.com/).

No screenshot, but if you whant there have my redif from twitch: https://www.twitch.tv/videos/344838144
(First crash at 00h07 and the second at 03h47, if you look the hours at the bottom of the stream...)

**Additional context**
I think this is 2 crash caused by the same bug, so I have put both in the same issue, but I'M not really sure, what is the cause for that bug, sorry...

Fireztonez

**Comment by NillerMedDild** [comment]
This looks like a JEI bug, I'm hoping updating will fix it ^^ We're a few versions behind.

**Comment by NillerMedDild** [comment]
Scratch that, it does not appear to be JEI. I'll investigate.

**Comment by Fireztonez** [comment]
Ok, thank's NillerMedDild...

I wonder personally if is not caused by the Extra Utils 2 Transfer Nodes and Transfer Pipes. I used in the world. I don't really know why, but I have a felling that there have an issue with it... After I can be wrong, we have absolutely no proof of any kind about that, this is just a felling...

**Comment by NillerMedDild** [comment]
Does this issue still occur?
