### ISSUE TITLE
Handheld Crafting Table vs Crafting Table on a Stick

### ISSUE THREAD

**Issue by MorganSimic** [NillerMedDild/Enigmatica2Expert#425]
**Is your feature request related to a problem? Please describe.**
I noticed, that the Handheld Crafting Table from Extended Crafting probably does not use FastWorkbench for its crafting. Also if one likes to add Crafting Tweaks for themselves, the Handheld Crafting Table does not support that afaik. So batch crafting with the handheld crafter can be extremly annoying due to lagging out everytime you shift click craft something.

**Describe the solution you'd like**
Consider switching the available handheld crafting device to the Crafting Table on a Stick from Actually Additions. This does for sure use FastWorkench and supports crafting tweaks.

**Additional context**
This is only a very minor tweak, with no actual content change but only backend peformance improvement for early stages of the game. I just noticed that and found that very annoying and wanted to point that out. Mostly the situation is fine as is. So if you don't want to change this it is perfectly fine, since i can see that it could also be confusing for some people if this is switched.

**Comment by NillerMedDild** [comment]
Good idea, I'll switch them, thanks!
