### ISSUE TITLE
ExU2 Enchanter Item dupe

### ISSUE THREAD

**Issue by MaucnAD** [NillerMedDild/Enigmatica2Expert#426]
**Issue Description**
Enchanting an x number of items won't enchant one item from the stack but the full stack, while only consuming one of said item. I'm guessing this is because usually enchantable items aren't stackable?

**Modpack version (Do not use "latest")**
1.44

**Logs**
**Screenshots**
https://gyazo.com/collections/470b9318695c4c6beeaff8b4ba16e08c

**Additional context**
- I am using sieve meshes which might be relevant since they are the only enchantable thing stackable as far as I know
- This only happens with the enchant recipe, both the lapis and the nether star one. NOT with the magical wood, enchanted ingot etc. ones
- It doesn't matter how much lapis is in there
- It happens with all sieve types. 
- It doesn't matter which speed upgrades are in there.

**Comment by NillerMedDild** [comment]
There's nothing I can do to fix the issue other than wait.
