### ISSUE TITLE
Soft Refined Storage Support

### ISSUE THREAD

**Issue by NillerMedDild** [NillerMedDild/Enigmatica2Expert#428]
Add Refined Storage expert-ified recipes.

**Comment by Beannsss** [comment]
1 Thing to warn about Refined storage for anyone wanting to add it: It does not deal well with items that are seperated by NBT. I added refined storage when I got to ae2 gate, and it's worked pretty well so far. However, things such as Forestry circuits, and basically everything mekanism are not handled too well in it's autocrafting system. (i.e. quantum entangloporter craft will result in "missing item: Intricate Circuit Board").

**Comment by KaneHart** [comment]
Refined Storage is powerfully cheap. I hope you gate it much further then AE2 because it's quite a easy / cheap mod.

**Comment by kythorn** [comment]
Dear Mr. Niller,

May I please inquire as to your intended usage for this as some of the recipes seem to collide with similar AE2 recipes? Are we supposed to remove AE2, or just add RS in parallel?

I know I can use the forestry worktable to choose between conflicting recipes, but what about automation?

**Comment by NillerMedDild** [comment]
I didn't even think about the recipe conflicting, Woops! I'll get that fixed. The purpose of this script is to tweak RS if anyone wants to use it over AE.
