### ISSUE TITLE
Astral Problem

### ISSUE THREAD

**Issue by SuperFurias** [NillerMedDild/Enigmatica2Expert#430]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
I can't craft Anything with Astral Sourcery

**Modpack version (Do not use "latest")**
1.44

**Logs**
N/A
If applicable, please upload your crash report, or latest.log to [hastebin](https://hastebin.com/).

**Screenshots**
http://prntscr.com/lsr2ir
(Petal Apotechary)

**Additional context**
I try everything, but i cant craft anything with Astral

**Comment by drakkensong21** [comment]
Are you playing on a server and did you craft the table your self

**Comment by SuperFurias** [comment]
No, i'm not playing on a server and i did the luminous crafting table by me (with the... RFTOOLS storage scanner crafting)

**Comment by SuperFurias** [comment]
OMG YOU SAVE MY LIFE, i try to craft it with the crafting table (vanilla) and works

**Comment by SuperFurias** [comment]
SHITTY RFTOOLS STORAGE SCANNER

**Comment by NillerMedDild** [comment]
I recommend you use the Discord for support issues SuperFurias, and please be civil.

**Comment by NillerMedDild** [comment]
Thank you for the help Drakken :)
