### ISSUE TITLE
Ender IO tier progression

### ISSUE THREAD

**Issue by Chiiruno** [NillerMedDild/Enigmatica2Expert#432]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
N/A

**Additional context**
I noticed that the Ender IO progression in this mod pack doesn't include "enhanced" machines such as the Enhanced SAG Mill or the Enhanced Alloy Smelter, any chance we can get that implemented?

**Comment by Chiiruno** [comment]
For reference: https://www.reddit.com/r/feedthebeast/comments/8vs9uy/e1r3cz8/

**Comment by NillerMedDild** [comment]
The mid tier is already way faster than normally, I think adding another tier would be too strong - I don't want to overshadow the other mods too much ^^

**Comment by NillerMedDild** [comment]
16.5 times faster :P I don't think that'd really add anything to the pack, other than annoy the people who have automation setup with the current tier, sorry :) I appreciate the suggestion though.
