### ISSUE TITLE
More End-game

### ISSUE THREAD

**Issue by bluntzultimat3** [NillerMedDild/Enigmatica2Expert#433]
**Is your feature request related to a problem? Please describe.**

Managed to finish the pack in under a week, just looking for some more things to do really. 

**Describe the solution you'd like**

Add more things to do to reach end game? Maybe change some recipes to be harder or something 

**Additional context**

**Comment by NillerMedDild** [comment]
How many hours did it take before you had the Creative Vending Upgrade? I've never heard of anyone completing it in under 180 hours.

**Comment by bluntzultimat3** [comment]
Wouldnt be able to tell you in hours how quick we done it but it was about a week play time overall... That sounds like a challenge to me ;)

**Comment by NillerMedDild** [comment]
You can check out time played on the server leaderboard, available through the inventory (top left corner).
But damn, that is impressive. I deem the modpack feature complete, I will not be adding more contents, other than QoL improvements.
