### ISSUE TITLE
Crash on joining server

### ISSUE THREAD

**Issue by bluntzultimat3** [NillerMedDild/Enigmatica2Expert#434]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**

When joining a server, you error in screenshots area. 

**Modpack version (Do not use "latest")**

1.44

**Logs**

If applicable, please upload your crash report, or latest.log to [hastebin](https://hastebin.com/).

Can get logs if needed to help debugginig

**Screenshots**

https://i.imgur.com/38ZVpCh.png

**Additional context**

Not just me that has this error, while in server and someone joins, the join and leave instantly then need to rejoin..

**Comment by NillerMedDild** [comment]
Thank you for the report. I need your `latest.log` file to troubleshoot the issue.

The `latest.log` file can be found in the `logs` folder of the Enigmatica modpack folder.

**Comment by bluntzultimat3** [comment]
Getting that for you just now buddy :)

**Comment by KaneHart** [comment]
It's also an issue in 1.45 /u/NillerMedDild
https://pastebin.com/bTU6SQJR

There was no server error at all it seems to be some sort of first time connect to the server sends a large packet /nbtdata? It's fine after but if they reboot their client it happens all over again sadly.  Really annoying.

**Comment by KaneHart** [comment]
Just got a server error this time joining up after rebooting the client:
https://pastebin.com/Qv2SPnBj

**Comment by KaneHart** [comment]
For sure not. In fact this happen the first time using it as is of a fresh 1.45 server / client on Linux.

**Comment by t3rraz** [comment]
i have the same problem, but only the first connect fails, the next connect works. so its not dramatic. it began here on version 1.44

**Comment by GoldenKeyboard** [comment]
#https://github.com/zmaster587/AdvancedRocketry/issues/760

**Comment by NillerMedDild** [comment]
Thanks for the link GoldenKeyboard. I'll keep this open until it can be tested on 1.46

**Comment by NillerMedDild** [comment]
Any update? Does this still occur?

**Comment by KaneHart** [comment]
No error anymore when connecting with the latest version.
