### ISSUE TITLE
Dupe Bug.

### ISSUE THREAD

**Issue by GoldenKeyboard** [NillerMedDild/Enigmatica2Expert#435]
You can dupe lapis lazuli using an ic2 compressor; I assume this is not intentional.
https://i.gyazo.com/f5997268b0463c6ca27657aec2f098c1.png

**Comment by drakkensong21** [comment]
Dupe of #186

**Comment by drakkensong21** [comment]
Dupe of #421

**Comment by NillerMedDild** [comment]
Duplicate of #390
