### ISSUE TITLE
Remove Quark Trash Icon From Inventory

### ISSUE THREAD

**Issue by KaneHart** [NillerMedDild/Enigmatica2Expert#437]
We have the other Trash can in the Interface and the quark one is very dangerous for accidental drag and drop. 

Config: quark.cfg
Line 793:
        B:"Enable Trash Button"=true
to
        B:"Enable Trash Button"=false

Example of what it looks like in game:
https://i.imgur.com/BF4DFQI.png

**Comment by drakkensong21** [comment]
Why this is user error not modpack error

**Comment by NillerMedDild** [comment]
I agree that it's a hazard.
