### ISSUE TITLE
Slow Elite Infuser Factory

### ISSUE THREAD

**Issue by TheMineGeek** [NillerMedDild/Enigmatica2Expert#439]
**Issue Description**

Elite infusing factory is going way slower than normaly

**Modpack version (Do not use "latest")**

Enigmatica 2 Expert 1.44

**Logs**

This get spammed in my console. That's a very small part of the whole output : https://pastebin.com/JjS7PL9h

**Additional context**

I'm using auto craft with me interface. Don't know if it could be related.
Factory is ugpraded with 8x Speed and 8x Energy

Thanks for the modpack. Absolutely love it

**Comment by TheMineGeek** [comment]
Totaly related. I don't know which exact craft was causing this but I was also trying to craft hv solar panel :)

**Comment by NillerMedDild** [comment]
I'll close this as it's pretty much a duplicate. I'm working on resolving it :)
