### ISSUE TITLE
Modpack crashing when entering the nether

### ISSUE THREAD

**Issue by Ciberbago** [NillerMedDild/Enigmatica2Expert#44]
#### Issue Description
I entered the nether with my tconstruct sledge hammer in hand to get some crushed netherrack, then the game crashed. And now I can't enter my world anymore.

#### What you expected to happen
Not to crash

#### Modpack version (Do not use "latest")
1.20

#### Your most recent crash report or log file where the issue was present
https://pastebin.com/U7CEpsg5

**Comment by NillerMedDild** [comment]
Should be fixed in the next version - You can fix it by using NBTExplorer to remove the item from your inventory.
