### ISSUE TITLE
Modular Machinery recipes don't show up anymore in JEI

### ISSUE THREAD

**Issue by Basedgod199** [NillerMedDild/Enigmatica2Expert#442]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Question or Issue**
As title says, I can no longer see modular machinery recipes in jei. Prior to latest update (1.18) I was able to. now when I click on it, its blank. To clarify, I mean the recipes that the machine is able to do, not the blueprint itself. (see screenshot)

**Modpack Version**
1.18

**Additional Context**

![2018-12-18_23 06 02](https://user-images.githubusercontent.com/32063145/50204531-09cd6700-031a-11e9-9fb7-16d951cbdd62.png)

**Comment by NillerMedDild** [comment]
Known issue
https://github.com/HellFirePvP/ModularMachinery/issues/133

Thank you for the report :)

**Comment by Basedgod199** [comment]
Is there any way to fix it? or somehow i could otherwise see the recipes?

**Comment by NillerMedDild** [comment]
Revert to 1.17 and take screenshots of the recipes, then update :)
