### ISSUE TITLE
Run /ct conflict

### ISSUE THREAD

**Issue by shade28** [NillerMedDild/Enigmatica2Expert#446]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
71 Conflicting recipes and how to find and fix them.
while playing version 1.18, I went to craft a compressed grinder from sky resources. it requires compressed sticks, and I noticed that they were uncraftable due to recipe conflicts. I've dealt with conflicting recipes in the past when I developed my own pack so decided to track down the issues. I checked discord and your bug tracker, found version 1.19 of the pack, installed the latest and ran the conflict command again. no changes. So I wanted to at least bring these conflicts to your attention and how to fix them. 

crafttweaker has many very useful commands. but in this case we want 
/ct conflicts
This writes a textfile to the pack directory labeled crafttweaker.log In it lists large amounts of information about what crafttweaker is doing, but after running this command it prints all recipe conflicts at the bottom.  I attached a pastebin link to 1.19's conflict report. On line 4559 it says:
"[SERVER_STARTED][SERVER][INFO] Conflicting: 71"
followed by details on what recipes actually conflict. most of the conflicts are things like vanilla chests vs mod specific chests, however knowing and using this command feels like a very good thing to know.
Hopefully this information helps. Keep up the great work.

**Modpack version (Do not use "latest")**
1.19

**Logs**

If applicable, please upload your crash report, or latest.log to [hastebin](https://hastebin.com/).
https://pastebin.com/gt0Wcntv

**Screenshots**

**Additional context**

**Comment by NillerMedDild** [comment]
I'm aware of the command, thank you.

**Comment by NillerMedDild** [comment]
I did so intentionally so I don't forget to run it :)
