### ISSUE TITLE
IC2 crafting recipe not working

### ISSUE THREAD

**Issue by Balabarm** [NillerMedDild/Enigmatica2Expert#447]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
Tried to craft a LV-Transfromer but the recipe is not working. Tried the Vanilla crafting table aswell.

**Modpack version (Do not use "latest")**
1.46

**Logs**

If applicable, please upload your crash report, or latest.log to [hastebin](https://hastebin.com/).

**Screenshots**
![screenshot 73](https://user-images.githubusercontent.com/46071406/50376104-d552f700-0608-11e9-9e77-268109e69a43.png)
![screenshot 75](https://user-images.githubusercontent.com/46071406/50376128-324ead00-0609-11e9-8b24-df19941dbf00.png)

**Additional context**
I'm playing the Modpack without any other Mod or any changes

**Comment by NillerMedDild** [comment]
Thank you for the report, there's a typo in the recipe :P fixed for next update. I suggest you cheat one in.
