### ISSUE TITLE
Game crash while loading world

### ISSUE THREAD

**Issue by Mrsfoxy** [NillerMedDild/Enigmatica2Expert#448]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
I've updated modpack today and since then wasn't able to open my single world, game just crash whenever I try to load it

**Modpack version (Do not use "latest")**
1.46

**Logs**

If applicable, please upload your crash report, or latest.log to [hastebin](https://hastebin.com/).

https://pastebin.com/nxp83m3x
Since log is way too long I've managed to upload only last part of it, sorry, but if needed can try to somehow upload whole thing
**Screenshots**

**Additional context**

**Comment by NillerMedDild** [comment]
Remove the file `/C:/Users/musel/Documents/Curse/Minecraft/Instances/Enigmatica 2 Expert/saves/V3/advRocketry/planetDefs.xml` - Please let me know if it fixes your issue :)

**Comment by Mrsfoxy** [comment]
Yes, it helped! Thank you very much! :)

**Comment by NillerMedDild** [comment]
Sure thing :)
