### ISSUE TITLE
Disable Metal block recipes that aren't meant to be used

### ISSUE THREAD

**Issue by GeekBeam** [NillerMedDild/Enigmatica2Expert#449]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
the Ex  Compressum auto compressor will compress metal ingots into non-thermal expansion versions of the metal blocks,  notably tin into ic2 tin, lead into ic2 lead, and so on.

**Modpack version (Do not use "latest")**

E2:expert 1.46

**Logs**

If applicable, please upload your crash report, or latest.log to [hastebin](https://hastebin.com/).

**Screenshots**

**Additional context**

**Comment by NillerMedDild** [comment]
Thanks for the report, I'll get that fixed :)

**Comment by NillerMedDild** [comment]
https://github.com/blay09/ExCompressum/issues/263

**Comment by ArbitraryHubris** [comment]
[Examples](https://imgur.com/a/PoIFXux)
