### ISSUE TITLE
Unable to cast copper pickaxe head

### ISSUE THREAD

**Issue by Turmfalke2** [NillerMedDild/Enigmatica2Expert#45]
hi,
It is entirely possible that I am just to stupid for this, but I am trying get a pickaxe with copper mining level. For that I have followed the quest chain and got my self a tinkerer's smeltery and a bucket of lava.  
Now I have got my self a  smeltery with 2 ingots worth of molten copper and a pickaxe head clay cast in the casting table. However no amount of clicking on the faucet seems to trigger it to cast the actual pickaxe head. According to JEI I should be able to do that and I can't find any information in the quest book that the recipe has been changed/removed. 

Version 1.20

![2018-05-01_20 09 40](https://user-images.githubusercontent.com/5174562/39486218-abddeda8-4d7b-11e8-9d5e-8315411a7d13.png)
![2018-05-01_20 09 51](https://user-images.githubusercontent.com/5174562/39486228-b3148ce4-4d7b-11e8-870e-869d9c48e39d.png)

**Comment by NillerMedDild** [comment]
Are you close to the world spawn?

Try restarting the server (or SP).

**Comment by Turmfalke2** [comment]
@NillerMedDild not really, something like ~500 blocks away or so?

Restarting somehow fixed it. Is that a tinkerer's issue, am I likely to encounter that bug again?

**Comment by NillerMedDild** [comment]
It's very rare afaik @Turmfalke2, but I still haven't tracked down the cause :/
