### ISSUE TITLE
Replace EIO machine casing in Impulse hopper recipe 

### ISSUE THREAD

**Issue by MorganSimic** [NillerMedDild/Enigmatica2Expert#451]
**Is your feature request related to a problem? Please describe.**
The Impulse hopper from EIO is good automation tool for some specific tasks but is gated behind EIO casings. I think this not appropriate for the benefit it provides.
**Describe the solution you'd like**
Consider a different gating for the impulse hopper. Maybe Iron casings or something like that.

**Additional context**

**Comment by NillerMedDild** [comment]
Thanks for the suggestion, I agree.
