### ISSUE TITLE
Cannot connect to LAN

### ISSUE THREAD

**Issue by enderger** [NillerMedDild/Enigmatica2Expert#453]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
We cannot connect to an open LAN world. 

**Modpack version (Do not use "latest")**
1.46

**Logs**

N/A

**Screenshots**

No screenshots are available, but the errors we get are:

- Internal Server Error
- Disconnected
- The overcomplicated way of saying a "timed out" error

**Additional context**

The LAN is hosted on a properly-configured Linux computer and we tried to connect from a properly-configured Windows computer

**Comment by NillerMedDild** [comment]
I would guess the Firewall is blocking. 
This is a support question, not a bug report, please refer to the Discord channel if necessary :)

**Comment by NillerMedDild** [comment]
Additionally, I really recommend that you use a dedicated server setup, as LAN worlds have issues with quests.
