### ISSUE TITLE
Extra Utilities Furnace Crashing game

### ISSUE THREAD

**Issue by CloudConstructor1** [NillerMedDild/Enigmatica2Expert#456]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
If the Extra Utilities Furnace is running, still has an internal inventory, and you shift click to top off inventory my game simply locks up. I have to close it via Task manager. Im guessing because i have to manually close the program, I dont ever get a crash log. If inventory is empty and of course therefore not running, you can shift click all day long.

**Modpack version (Do not use "latest")**
1.46

**Logs**

If applicable, please upload your crash report, or latest.log to [hastebin](https://hastebin.com/).

**Screenshots**

**Additional context**

 Wasnt sure if this was a pack issue or a mod issue but i dont get this issues with 2 other packs i currently play that has Extra Utilities. If you could direct me to a possible log, id be happy to upload it. Thank you.

**Comment by GoldenKeyboard** [comment]
Can recreate issue with 100% reliability.
Seems to be the same issue we had with the golden bag of holding.
Recommend disabling it until issue can be resolved.

**Comment by NillerMedDild** [comment]
Do you propose disabling Extra Utilities @GoldenKeyboard?

This issue has been reported on the Extra Utilities issue-tracker, thank you for the report.
https://github.com/rwtema/Extra-Utilities-2-Source/issues/155

**Comment by CloudConstructor1** [comment]
I know i dont know anything about coding and how mods are made and interact with each other. But i do know the 2 other packs i play that i have no issues with EU2, both dont have Inventory Tweaks. Just a thought.

**Comment by NillerMedDild** [comment]
Disabling Extra Utilities will be gamebreaking for everyone, not just those who shift click into inventories :/

**Comment by GoldenKeyboard** [comment]
I'll do some digging into the pack and see what is causing the issue.

**Comment by NillerMedDild** [comment]
Thank you very much.

**Comment by CloudConstructor1** [comment]
> Disabling Extra Utilities will be gamebreaking for everyone, not just those who shift click into inventories :/

after i found the bug and could reproduce before reporting it, i instantly made hoppers for it. lol still super early game.

**Comment by GoldenKeyboard** [comment]
So
The bad news is that EU2 causes a crash even when it is the only mod enabled.

**Comment by NillerMedDild** [comment]
That's good news in my book!

**Comment by GoldenKeyboard** [comment]
Downgrading to version 1.9.4 resolves the issue

**Comment by GoldenKeyboard** [comment]
Versions above actually delete the stack instead of crashing (which is better?)

**Comment by NillerMedDild** [comment]
Yep :P #354

**Comment by KingIonTrueLove** [comment]
I would like to add, that as long as this wasn't fixed recently (I'm too afraid to try), that I think the issue seems to happen with any small extrautils inventory. I have had the game hang a couple times when trying to top off a mini chest.

**Comment by NillerMedDild** [comment]
Yep, you're right.

**Comment by NillerMedDild** [comment]
There's nothing I can do to fix the issue other than wait.
