### ISSUE TITLE
Unconscious removal of many recipes.

### ISSUE THREAD

**Issue by OneEyeMaker** [NillerMedDild/Enigmatica2Expert#457]
Firstly, thank you for great modpack!
Secondly, I found issue with many (regular crafting) recipes and cause of it.
While editing recipes via CraftTweaker, to remove recipes you use ```recipes.remove(...)``` function.
Method ```recipes.remove(...)``` attempts to remove **_all_** regular crafting recipes.
In cases, when item has both **shaped** and **shapeless** (marked with crossed arrows in JEI) recipes, this method makes impossible to craft certain (sub-)items (based on damage and especially, on NBT).
Items I found affected by this issue:
- All charms from Cyclic (unable to repair ones due to removed shapeless recipe);
- All dense and vacuum versions of *opaque* ducts from ThermalDynamics.

I'm sure, there are other items affected by this issue (but I didn't find ones yet).

Solution:
Use methods ```recipes.removeShaped(...)``` and ```recipes.removeShapeless(...)``` respectively instead of ```recipes.remove(...)``` to avoid such problems. And beware of use of ```recipes.remove(...)``` in cases, when item has both shaped and shapeless recipes.

Modpack versions: 1.45 - 1.46

**Comment by NillerMedDild** [comment]
I am aware of how recipe removal works, the use of `recipes.remove` is intentional.
