### ISSUE TITLE
Exchangers Not Doing Mining Level

### ISSUE THREAD

**Issue by TwilightPSN** [NillerMedDild/Enigmatica2Expert#46]
Issue Description:
When trying to use the max tier exchangers to replace blocks you get told that it is above the mining level when per tooltips it isnt

Modpack version (Do not use "latest")
1.20

**Comment by NillerMedDild** [comment]
I've asked the mod author for an option to increase mining levels further than 4, so I'm hoping this will be fixed soonish - Thanks for the report.
