### ISSUE TITLE
Server Crash when Loading IE Revolver

### ISSUE THREAD

**Issue by dnulho** [NillerMedDild/Enigmatica2Expert#461]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
Playing a Multiplayer Game the Server Crashes when a Player tries to open the IE revolver to load cartridges into it.

**Modpack version (Do not use "latest")**
1.46

**Logs**
Revolver Crash Log 
[crash-2018-12-26_06.53.08-server.txt](https://github.com/NillerMedDild/Enigmatica2Expert/files/2709652/crash-2018-12-26_06.53.08-server.txt)
Revolver Cut Debug Log
(As server crashes and immediatly restarts, moving Latest.log to Debug-1. Shows ~5 min back from the crash.)
[debug-1.log](https://github.com/NillerMedDild/Enigmatica2Expert/files/2709662/debug-1.log)
Speedloader Crash Log
[crash-2018-12-26_07.08.41-server.txt](https://github.com/NillerMedDild/Enigmatica2Expert/files/2709687/crash-2018-12-26_07.08.41-server.txt)
If you want the Debug Log for the Speed Loader, or any other log files, let me know.

If applicable, please upload your crash report, or latest.log to [hastebin](https://hastebin.com/).

**Screenshots**
- NA -

**Additional context**
This error has happened 3 separate times, across 2 different players, and happens when they try to open the Revolver by Shift+Right Clicking. Same behavior occurs when attempting to open a Speed Loader.

**Comment by NillerMedDild** [comment]
The issue has been resolved in a new update of Immersive Engineering, thank you for the report.
