### ISSUE TITLE
Actually Additions worms disappearing

### ISSUE THREAD

**Issue by Natrukei** [NillerMedDild/Enigmatica2Expert#462]
**Issue Description**
The worms provided by actually addition dissapear every time I close Minecraft.
After loading back in to the world my farmland is tilled, but dry.

**Modpack version**
1.46
Happens in various forge versions (2768 and 2778) 

Maybe its due to actually additions being outdated, but I don't know

**Comment by NillerMedDild** [comment]
Actually Additions Worms are configured to last 5000 ticks.
