### ISSUE TITLE
Suggestion: jersey steak should be nerfed

### ISSUE THREAD

**Issue by hihi9190** [NillerMedDild/Enigmatica2Expert#463]
**Question or Issue**
Jersey steak is dropped from Jersey cows (animania) and they currently give Max hunger, saturation and instant health. For the ease of obtaining jersey steak makes it overpowered. Imo good food should also involve a difficult recipe and require the use of many ingredients.

**Modpack Version**
1.46

**Additional Context**
May vary but my world is roaming with these cows making it a very easy source of food.

**Comment by NillerMedDild** [comment]
Animania animals are usually both hard to find and maintain, so I think the payoff is fair. Breeding them is a chore aswell. Enjoy the uber food :D
