### ISSUE TITLE
Extra Utilities GP Generation II quest description

### ISSUE THREAD

**Issue by xob** [NillerMedDild/Enigmatica2Expert#464]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
The quest description for the Extra Utilies "GP Generation II" quest is wrong. It says "Obtaining any of the 3 mills will complete this quest", but the quest is set up to require all 3 mills (Logic: AND).

The description should either say "Obtaining all 3 mills will complete this quest", or the logic should be set to OR to fit the current description.

**Modpack version (Do not use "latest")**
Enigmatica 2 Expert 1.45

**Logs**
Not applicable.

**Screenshots**
Not necessary.

**Additional context**
I first observed the issue when I got to that part of the quest book, and had already obtained 2 Water Mills as a quest reward, and 10 Fire Mills from a loot chest. The are indeed detected as complete. The only missing mill is the Lava Mill. Reading the quest description, I came here to report the issue.

**Comment by NillerMedDild** [comment]
The task logic is OR, the quest logic is AND, they're seperate things :)

**Comment by xob** [comment]
But it didn't complete the quest for me, even though I completed 2/3 tasks. From the description, I would've expected it to mark the quest as complete.

As it is, I would have to craft a Lava Mill to complete the quest, even though it says "crafting ANY of the 3 mills".

Am I understanding things wrong?

**Comment by NillerMedDild** [comment]
Ah my bad, I assumed the quest completed since you said `The are indeed detected as complete.`, but I guess you only meant the tasks. You can't pick a Loot Chest even though you have 2/3, correct?

**Comment by xob** [comment]
Correct. Re-reading my bug report, I should have been more verbose. The Water Mill and Fire Mill tasks are marked as Complete, the Lava Mill task is not (and should not) be marked as Complete. The quest itself is not Complete'ing, and I am unable to pick a Loot Chest from it.

**Comment by NillerMedDild** [comment]
Cool, I'll have a look at it, thanks.

**Comment by xob** [comment]
This... might have been one of those weird Better Questing bugs. It might have maybe been because I had completed the tasks before the quest got unlocked. Maybe it has issues with OR tasks when they get completed before the quest unlocks. Who knows.

I used commands to reset the task completion status, then I put the Fire Mills back in my inventory, and the quest completed automatically.

**Comment by NillerMedDild** [comment]
Oh well, I appreciate the report anyway!
