### ISSUE TITLE
Invalid IC2 recipes

### ISSUE THREAD

**Issue by Yalgrin** [NillerMedDild/Enigmatica2Expert#465]
**Issue Description**

A few IC2 recipes are missing some recipe components (or at least they show up in JEI like this) like Reactor Vessel requiring just 4 pieces of stone or LV Transformer built from 2 tin cables & copper coil.

**Modpack version (Do not use "latest")**

Expert 1.46

**Additional context**

Caused by typos in ore dictionary entries in IndustrialCraft2RecreatingRecipes.zs script. LV Transformer requires `ore:plankWod` and Reactor Vessel requires `ore:platLead`. There is possibly more typos, I haven't checked the whole file.

**Comment by NillerMedDild** [comment]
Thank you for the report, I'll get the Reactor Vessel fixed! The `ore:plankWod` has been fixed previously.
