### ISSUE TITLE
Tiny Piles of Lead Dust does not have a compression recipe.

### ISSUE THREAD

**Issue by GoldenKeyboard** [NillerMedDild/Enigmatica2Expert#466]
Lead Dust does not have a compression recipe from tiny piles of lead dust created via IC2 thermal centrifuge.

I believe this is not intended due to all the other dust recipes having a compression recipe.

https://i.gyazo.com/57140a893a73a21316174341bbbd5094.png

**Comment by NillerMedDild** [comment]
Thank you for the report, I'll get that fixed.
