### ISSUE TITLE
Adding: OpenGlasses & OpenSecurity (for consistency)

### ISSUE THREAD

**Issue by KirinDave** [NillerMedDild/Enigmatica2Expert#467]
**Is your feature request related to a problem? Please describe.**
Currently OpenComputers is installed and a very useful tool for automation, but it is missing some common mods that it is paired with. This only only creates a feature deficit Compared to ComputerCraft+Plethora, but it also breaks a lot of programs that have cool AR and multiplayer features, as well as removing the possibility of an OpenSecurity mob farm.

**Describe the solution you'd like**
In the next version of the pack, please add [OpenGlasses](https://minecraft.curseforge.com/projects/openglasses) and [OpenSecurity](https://minecraft.curseforge.com/projects/opensecurity). There won't be any other integration requirements.

**Additional context**
Part of the reason OpenGoggles in particular is so much fun is that unlike the Neural Interface from Plethora, the OpenGoggles let you place geometry in the world in real time. This leads to really cool results (such as an programmable way to scan for entities).

**Comment by NillerMedDild** [comment]
I think both those mods will remain unused by 99.9% of the player base, I'm not sure they're worth the overhead tbh.

**Comment by KirinDave** [comment]
Does more of the player base use Plethora?

**Comment by NillerMedDild** [comment]
Plethora is smaller, and yes, more people use ComputerCraft.

**Comment by KirinDave** [comment]
Sorry about that, my daughter pwapped my phone before I could edit that comment. 

OpenSecurity isn't essential, but a lot of great stuff happens with OpenGlasses and it introduces its overhead in the lua interpreter, so if someone doesn't use it it's limited to the impact of registering the recipe and NEI registry.

**Comment by NillerMedDild** [comment]
That I can live with!

**Comment by NillerMedDild** [comment]
OpenGlasses 1 or 2?

**Comment by NillerMedDild** [comment]
Still waiting ^^
