### ISSUE TITLE
[question] is it a intended mechanic about casting plates?

### ISSUE THREAD

**Issue by NarigudoBR** [NillerMedDild/Enigmatica2Expert#469]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Question or Issue**
is it a intended mechanic about casting plates in a ticon smeltery?

**Modpack Version**
1.4.6

**Additional Context**

**Comment by NillerMedDild** [comment]
Yes.
