### ISSUE TITLE
Crash in AE2 with fuzzy matching

### ISSUE THREAD

**Issue by omglolbah** [NillerMedDild/Enigmatica2Expert#470]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
Putting TiC tools in an exporter/storage bus with fuzzy card then adding a broken tool to the system causes a crash.
https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/3768/
A fix is available (rv6.stable build 6 of AE2)

**Modpack version (Do not use "latest")**
1.46

**Logs**
**Screenshots**
**Additional context**

Fairly old (6 months) bug that was fixed just a few days ago. Eager to see the latest version included so I can resume playing the pack!

**Comment by NillerMedDild** [comment]
I can't believe it's fixed o_o
