### ISSUE TITLE
IC2 LV-Transformer recipe broken

### ISSUE THREAD

**Issue by Omegapsychosis** [NillerMedDild/Enigmatica2Expert#471]
Currently you are unable to craft an IC2 LV-Transformer due to an error in the script file IndustrialCraft2RecreatingRecipes.zs

"//	LV-Transformer
	recipes.remove(<ic2:te:77>);
	recipes.addShaped(<ic2:te:77>, [
		[<ore:plankWod>, tinCableIns, <ore:plankWod>],
		[<ore:plankWod>, <ic2:crafting:5>, <ore:plankWod>],
		[<ore:plankWod>, tinCableIns, <ore:plankWod>]
	]);"

Should be.....

"//	LV-Transformer
	recipes.remove(<ic2:te:77>);
	recipes.addShaped(<ic2:te:77>, [
		[<ore:plankWood>, tinCableIns, <ore:plankWood>],
		[<ore:plankWood>, <ic2:crafting:5>, <ore:plankWood>],
		[<ore:plankWood>, tinCableIns, <ore:plankWood>]
	]);"

Version 1.46

**Logs**

No log necessary.

**Screenshots**

**Additional context**

**Comment by NillerMedDild** [comment]
Duplicate of #447
