### ISSUE TITLE
Ore Dictionary Random Things Glowing Mushroom to Nuclearcraft Glowing Mushroom.

### ISSUE THREAD

**Issue by KaneHart** [NillerMedDild/Enigmatica2Expert#476]
Could you add them to the same Ore Dictionary. Sadly we can't craft any items in Random Things as the current config settings is set to disable Glowing Mushrooms from spawning in Caves in Random Things.

If we could ore Dictionary the 2 then it would fix it easily or have a recipe where they convert over is also a possible fix from NuclearCraft to Random Things version.

**Comment by NillerMedDild** [comment]
Sure thing :)
