### ISSUE TITLE
Switch to "The One Probe" instead of "Waila/Hwyla/Wawla" stuff

### ISSUE THREAD

**Issue by Dark-Matter-001** [NillerMedDild/Enigmatica2Expert#478]
Just like JEI replaced NEI, The One Probe is the newer, better, all in 1 solution to all the old WAILA stuff.

https://minecraft.curseforge.com/projects/the-one-probe

It has a cleaner, less obstructive and more informative UI.  I first encountered it in FTB Beyond for 1.7.10 and since then its been the UI info mod for all FTB packs and much preferred to the old style of WAILA.  The only tweak it may need is to turn background color off for an even cleaner interface.

Examples of the difference: https://imgur.com/a/DPnmOMo

**Comment by NillerMedDild** [comment]
I prefer WAILA :)
