### ISSUE TITLE
Biomass

### ISSUE THREAD

**Issue by JFMillerUSA** [NillerMedDild/Enigmatica2Expert#479]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [I try to use IndustrialCraft2 Biomass in Forestry Still]

**Describe the solution you'd like**
To be able to use IC2 Biomass in Forestry Still

**Additional context**

**Comment by NillerMedDild** [comment]
They aren't the same, and they're not meant to be :)
