### ISSUE TITLE
Advanced Carpenter uses materials, but does not craft the Crafting Core

### ISSUE THREAD

**Issue by QuDubz** [NillerMedDild/Enigmatica2Expert#480]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**

I have now tried the Extended Crafting, Crafting Core recipe in the Advanced Carpenter twice.

Both times it recognizes the recipe and starts the craft and uses the materials, but no crafting core arrives in the output.

**Modpack version (Do not use "latest")**

1.46

**Logs**

If applicable, please upload your crash report, or latest.log to [hastebin](https://hastebin.com/).

**Screenshots**

**Additional context**

**Comment by NillerMedDild** [comment]
You need to give it more energy per tick, possibly with a higher level input port.
