### ISSUE TITLE
A way to convert IC2’s Hot Spring Water to BoP’s Hot Spring Water

### ISSUE THREAD

**Issue by TheWiz4rdZ** [NillerMedDild/Enigmatica2Expert#481]
**Question or Issue**
Since the IC2 HS water turns into regular water after a short time, and there’s no way to keep it as HS water, I’ve thought that it would be nice to implement a custom recipe to turn it into BoP HS water or make it’s crafting process create BoP HS water instead.

**Modpack Version**
1.46

**Additional Context**
I play on a server with a 3000 blocks radius to the world border with no Mystic Groove biomes inside of it (TT_TT)

**Comment by NillerMedDild** [comment]
Absolutely not, the rare chance of finding BoP Hot Spring Water is plenty OP :)

**Comment by TheWiz4rdZ** [comment]
Shoot, just because I love it’s texture xD (I kinda agree with you, despite it)
