### ISSUE TITLE
IC2 Machines/Wires suddenly stop connecting to any power sources or cables

### ISSUE THREAD

**Issue by mr-cats** [NillerMedDild/Enigmatica2Expert#485]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**

Randomly, IndustrialCraft 2 machines and cables will stop connecting to any cables or power sources, including ic2 cables themselves. For example, a line of copper cables will stop being connected to each other, and will just be a string of the cable "cores" along the ground. Machines will not connect automatically or manually to ic2 cables or mekanism cables. The CESU will connect automatically to mekanism cables but as soon as cable receives a block update, it will disconnect. 

**Modpack version (Do not use "latest")**

v1.46

**Logs**

No crash logs

If applicable, please upload your crash report, or latest.log to [hastebin](https://hastebin.com/).

**Screenshots**

[Screenshots w/ descriptions](https://imgur.com/a/KQjrlAG)

**Additional context**

It appears this issue can be (unreliably) triggered by closing a world and reopening the world without restarting the client, or by leaving a single player game paused for a while (speculative). Restarting the client temporarily fixes the issue.

**Comment by NillerMedDild** [comment]
I'm afraid this issue has been present in IC2 for a long time, I don't think it will be fixed :/
Does it only happen in a certain chunk, or is it anywhere? Does chunkloading help?

**Comment by mr-cats** [comment]
That's unfortunate. It seems to happen anywhere, as it was affecting multiple machine setups I had, but I had only tried it in chunks that were chunkloaded. I suppose restarting the client will have to do for a while.

**Comment by NillerMedDild** [comment]
Hmm... Try unloading it? :P

**Comment by mr-cats** [comment]
I'll give that a shot if the issue happens again. Could we get Ding! in the pack?
