### ISSUE TITLE
Crash upon opening PSI menu/book/tutorial

### ISSUE THREAD

**Issue by Leon1236** [NillerMedDild/Enigmatica2Expert#489]
**Issue Description**
Upon opening PSI menu/tutorial book game crashes. Tried different key binds, still the issue

**Modpack version (Do not use "latest")**

1.46

**Logs**
Crash report
https://hastebin.com/ifefedapom.rb

**Comment by Leon1236** [comment]
It crashes when Focusing rod is in main hand

**Comment by NillerMedDild** [comment]
Is this issue still present in 1.47?

**Comment by Leon1236** [comment]
> Is this issue still present in 1.47?
I am playing on the server. Haven't updated yet. Will test upon server update

**Comment by NillerMedDild** [comment]
Cool :)

**Comment by NillerMedDild** [comment]
Cannot reproduce in 1.47.
