### ISSUE TITLE
Atomic Dissembler is invisible after updating to 1.4.7

### ISSUE THREAD

**Issue by Amplefii** [NillerMedDild/Enigmatica2Expert#490]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**

**Modpack version (Do not use "latest")**

**Logs**

If applicable, please upload your crash report, or latest.log to [hastebin](https://hastebin.com/).

**Screenshots**

**Additional context**

**Comment by xob** [comment]
This issue is documented in the Mekanism github, https://github.com/aidancbrady/Mekanism/issues/5205

The suggested fix is to set `allowEmissiveItems` in `forge.cfg` to `false`. Not sure if this has repercussions on anything else.

**Comment by NillerMedDild** [comment]
Thank you @xob!

**Comment by KaneHart** [comment]
all I can say is my digital miner vanished >.> can't see it within the world.

**Comment by NillerMedDild** [comment]
Well that's annoying. Change the config server side?

**Comment by KaneHart** [comment]
I don't think it would effect it would it? They seem to vanished from the game 100% where these are visual bugs. The server side option should have 0 effect. Odd if no one elses vanished I guess it just bugged out sadly.

**Comment by NillerMedDild** [comment]
> They seem to vanished from the game 100% where these are visual bugs
What?

**Comment by KaneHart** [comment]
The digital Miners we had in our world have vanished as in not there at all since the 1.47 update. Some users are reporting visual bugs via BQ / JEI but some others said the digital miner had 100% vanished from the actual world itself as in not there.

The visual bug is just visual as far as I know and should not have impact/effect on server side settings.

**Comment by NillerMedDild** [comment]
Alright then.
