### ISSUE TITLE
Diamond Hoes Are Not Correctly Disabled.

### ISSUE THREAD

**Issue by GoldenKeyboard** [NillerMedDild/Enigmatica2Expert#491]
Diamond hoes are not correctly disabled.

https://gyazo.com/57b302d2b33506c67c6dfc69e74879c9
https://gyazo.com/bb9df3dbcc9bf557406bc528fb5b4832

It is missing from the tools to nerf section in Tools.zs.

Is this intentional?

**Comment by NillerMedDild** [comment]
I believe Diamond Hoes are able to harvest crops in a 5x5 area by right clicking, using some durability. If I remember correctly, I didn't want to disable that feature, so I left the Diamond Hoe unnerfed.

It's possible that it's just an oversight though :P

**Comment by NillerMedDild** [comment]
It should have been nerfed, thanks for the report.
