### ISSUE TITLE
FPS lag and personal crafting grid broken

### ISSUE THREAD

**Issue by ariosos** [NillerMedDild/Enigmatica2Expert#492]
Version 1.46

Description - There are occasional lag spikes, general low FPS, as well as the personal 2x2 crafting grid sometimes "forgets" recipes. I've also seen where it appears that crops are missing on farmland, but when I go to replant, the crop appears, then vanishes, as well as the item in my hand. Reloading fixes this (items re-appear in my hand), and the crafting grid issue. This seems random, so I really can't reproduce it.

Here's the log of my current gaming session (I noticed the lag spikes just recently, so they're towards the bottom of the log).
[latest.log](https://github.com/NillerMedDild/Enigmatica2Expert/files/2717460/latest.log)

I'm getting a constant 50-60 fps, with the FPS meter showing many red/yellow spikes.
![image](https://user-images.githubusercontent.com/7917753/50550480-b0313a80-0c3f-11e9-80f3-2090400e2ef2.png)

Also, I just noticed after taking the last screenshot, if I switch windows, the lag spikes are off the chart. So, I don't know if this is something wrong with the pack, or my PC (which is 7 years old at this point - 2600k for life!). The latter being why I think the game not syncing could possibly be something like memory failing?

Specs are in the above screenshot.
i7 2600k
ASRock z77 Extreme4 motherboard
16 Gigs RAM (about 12 Gigs allocated to Minecraft)
GTX 1070 video card
Game folder currently resides on a HD (I do have a SSD, but I'm not sure if I trust Minecraft mods and modpacks on it, but that's another story).

![image](https://user-images.githubusercontent.com/7917753/50550509-d525ad80-0c3f-11e9-8ad5-f990b94e7c5b.png)

**Comment by FunkyMoneyMan** [comment]
I can confirm that the 2x2 crafting grid in the inventory sometimes “forgets” ALL recipes and you have to relog to fix. Not super painful but annoying regardless.

**Comment by NillerMedDild** [comment]
Well damn. You wouldn't happen to be using Native Launcher aswell would you @FunkyMoneyMan?

**Comment by NillerMedDild** [comment]
Please let me know whether your issues have been resolved when possible OP :)

**Comment by FunkyMoneyMan** [comment]
No I use the twitch launcher @NillerMedDild. I get the glitch regardless what I use.

**Comment by ariosos** [comment]
Ok, I'm testing it now for a bit, but I'll be able to take a look more tomorrow evening.

**Comment by ariosos** [comment]
Still getting low FPS -
![image](https://user-images.githubusercontent.com/7917753/50553099-ca820d00-0c6d-11e9-97d1-e4c8107f08d6.png)
EDIT: Discovered vsync was on by default. I turned this off (vbo's is already on), and the fps improved.

I'm also getting double-text, too. 
![image](https://user-images.githubusercontent.com/7917753/50553119-12089900-0c6e-11e9-9280-c54b28d613e5.png)

But, I did notice before that the crafting grid would break after using the Part Builder to make a bunch of tough tool rods. The game would lag slightly. It hasn't done that yet, but I've only been playing for 5 minutes...

**Comment by SuperFurias** [comment]
Update java and put in the mod folder the optifine mod. I make 100+ fps with a 960M hahah

**Comment by NillerMedDild** [comment]
@SuperFurias Do not tell people to install Optifine.

**Comment by GoldenKeyboard** [comment]
Can you disable FoamFix and tell me if the problem still occurs?

**Comment by ariosos** [comment]
I'm still seeing lag spikes without foamfix. Also, entities (friendly mobs) seem to vanish in a golden lasso. I had 4 villagers in a golden lasso, and when I placed them down, they vanished.

![image](https://user-images.githubusercontent.com/7917753/50570246-6b48f900-0d50-11e9-9a00-80b8cd5dcd44.png)

**Comment by NillerMedDild** [comment]
That's a known and reported issue. Updating fixes it.

**Comment by ariosos** [comment]
I've upgraded to version 49, and still get the occasional lag spike. I haven't seen the recipe issue yet (although I updated the RandomPatches mod before v49, so maybe that fixed something?).

![image](https://user-images.githubusercontent.com/7917753/50725492-4811a700-10cc-11e9-88b0-dcebe5493382.png)

[1_5_2018_log.zip](https://github.com/NillerMedDild/Enigmatica2Expert/files/2729582/1_5_2018_log.zip)

**Comment by NillerMedDild** [comment]
Alright, I will close this for the time being.

**Comment by NillerMedDild** [comment]
Yeah they can be quite taxing.
