### ISSUE TITLE
Update 1.47 Expert Server does not start anymore

### ISSUE THREAD

**Issue by Athrader** [NillerMedDild/Enigmatica2Expert#493]
**Modpack version (Do not use "latest")**
Version 1.47
Tried to update from 1.46 to 1.47

**Logs**
https://hastebin.com/adipowiciq.rb

I updated from version 1.46 to 1.47. I copied the manifest.json into the folder and replaced the mods.
After that i started ServerStart.bat - here it starts all over and gives everytime it starts again a crashreport.

**Comment by Athrader** [comment]
So i tried this way. Now at it stops at the installation part where it should download forge:
This will not go further. Do you know where the problem is? Thanks in advice

Downloading FORGE (step 1 of 2). This can take several minutes, please be patien
t...
Attempting to download "https://files.minecraftforge.net/maven/net/minecraftforg
e/forge/1.12.2-14.23.5.2781/forge-1.12.2-14.23.5.2781-installer.jar... this can
take a moment, please wait."

**Comment by Athrader** [comment]
Downloaded it manualy.

**Comment by NillerMedDild** [comment]
Works fine for me, maybe the Forge server was temporarily down.
