### ISSUE TITLE
Metal Press not making gears

### ISSUE THREAD

**Issue by NarigudoBR** [NillerMedDild/Enigmatica2Expert#494]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
when triying to insert into  the metal press with a hopper, it doesn't accept it(yes, i checked the metal press and the material) and the jei says it's a valid recipe( but it doesn't work at all)
*note: only happens with the gear press*

**Modpack version (Do not use "latest")**
1.4.7

**Logs**

If applicable, please upload your crash report, or latest.log to [hastebin](https://hastebin.com/).

**Screenshots**
![2018-12-30_21 16 42](https://user-images.githubusercontent.com/5056170/50552348-408b7180-0c78-11e9-999d-3e387ad05515.png)

![2018-12-30_21 16 49](https://user-images.githubusercontent.com/5056170/50552350-4bde9d00-0c78-11e9-9616-0f17df79a8eb.png)

![2018-12-30_21 16 53](https://user-images.githubusercontent.com/5056170/50552352-51d47e00-0c78-11e9-8ed3-cd2dc78c050e.png)

**Additional context**

**Comment by NarigudoBR** [comment]
there's actually a problem with minecraft hopper and the structure when inserting to make gears

**Comment by NillerMedDild** [comment]
The gear recipes accept 4 ingots only, the Hopper can only move 1 at a time.
