### ISSUE TITLE
Sticks/Plank recipe changed

### ISSUE THREAD

**Issue by NossDreadna** [NillerMedDild/Enigmatica2Expert#496]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
Recipe for sticks and planks changed. I believe unintentional. additional notes below.

**Modpack version (Do not use "latest")**
1.47

**Logs**
**Screenshots**

![image](https://user-images.githubusercontent.com/46271799/50553188-7f103480-0c56-11e9-8d3f-7783a5efbb28.png)

**Additional context**
Some recipes state old values are obtainable; with in hand crafting and crafting-table-on-a-stick, no joy. I believe this to be a possible issue with current automated systems, since it wasn't mentioned in the patch notes, I suspect it was intentional.

**Comment by NossDreadna** [comment]
I believe this to be a possible issue with current automated systems, since it wasnt mentioned in the patch notes, I suspect it was intentional.

**Comment by NossDreadna** [comment]
Update: MC locked up at save twice. I am using Twitch, if that matters. I am looking into the stability issue (not normal for me) but the instability may be the cause of the issue noted above. Will post results of next successful save.

**Comment by NossDreadna** [comment]
CRITICAL POINT! Expert version...

**Comment by NossDreadna** [comment]
Deleted Twitch pack, Used Twitch to re download and issue persisted.

**Comment by KaneHart** [comment]
We also have this issue. For example 8 Logs = 8 Planks but not actually craftable. Maybe client / server files desynced?

**Comment by NossDreadna** [comment]
I think the issue may be that a mod accidentally modified the value for wood to be half that of what it is in vanilla, if not, then at least the old recipes need to be removed...

**Comment by NillerMedDild** [comment]
That is not the case NossDreadna, I modified the plank recipes.

**Comment by NossDreadna** [comment]
Ok, Thank you for clarifying. I will focus on documenting the recipe discrepancies. Should we delete this post or use it for the new focus of "recipes not usable"

**Comment by NillerMedDild** [comment]
Is this happening on a server @NossDreadna?

**Comment by NossDreadna** [comment]
no, Singleplayer from Twitch Launcher

**Comment by NillerMedDild** [comment]
Did you remove any mods?

**Comment by NossDreadna** [comment]
but as the first picture indicates, there are some recipes that simply cannot be used
no mods altered or removed

**Comment by NillerMedDild** [comment]
Ah. That's a visual bug. Some mod is adding the unnerfed recipes, I then remove it, but somehow JEI isn't notified anymore.
