### ISSUE TITLE
Thaumcraft 6 Infernal Furnace Bonus Output Unification

### ISSUE THREAD

**Issue by skillrax** [NillerMedDild/Enigmatica2Expert#498]
Only nuggets that can be compressed via 3x3 crafting are the nuggets from other mods and vanilla. Silver/Copper for example have no essentia and no recipe.

**Comment by NillerMedDild** [comment]
Thaumcraft Nuggets readded :)

**Comment by NillerMedDild** [comment]
It seems Unidict is making sure the Thaumcraft nuggets cannot be used. 

Would you mind getting me the "code name" of the nuggets you're havin trouble with? You can get it by holding the nugget in your hand and using the command `/ct hand`

**Comment by skillrax** [comment]
Heres the codes for Silver, Copper, and lead respectively. 
<thaumcraft:nugget:3>
<thaumcraft:nugget:1>
<thaumcraft:nugget:4>

All 3 appear to have OreDict entries under "nuggetSilver", "nuggetCopper", and so forth. 

The thermal foundation silver nugget (<thermalfoundation:material:194>) is also under the ore dict entry "nuggetSilver".

**Comment by NillerMedDild** [comment]
Much appreciated!
