### ISSUE TITLE
Duplication Issue

### ISSUE THREAD

**Issue by Salnex** [NillerMedDild/Enigmatica2Expert#5]
#### Issue Description
Using a wrench on a IC2 machine to disassemble a machine for the first time in awhile causes both the contents and the machine itself to duplicate. Immediately replacing and breaking again does not duplicate again. Some condition I haven't been able to work out must be met before they will duplicate again. The Chunk is loaded with FTB Utlities. The IC2 machines are powered with basic Mechanism cables.
#### What you expected to happen
Only one set of items drops
#### Modpack version (Do not use "latest")
1.03a

[pastebin/gist/etc link here]

**Comment by NillerMedDild** [comment]
Thanks for reporting this - I'm fairly certain I have it fixed in dev, but it's hard to reproduce.
