### ISSUE TITLE
needing titanium to get titanium

### ISSUE THREAD

**Issue by Bickers07** [NillerMedDild/Enigmatica2Expert#50]
#### Issue Description
you get given 16 titanium ingots for the advanced rocketry gate quest but you need more then that to get to the planets that contain titanium you need
9 ingots for rocket assembly machine
6 for 2 engines for your rocket to get to Luna
17 for space station builder(as you need to build a rocket assembler as well)
4 for the warp core
totalling to 36 ingots making the quest line unbeatable 
#### What you expected to happen
not needing titanium till you can mine it
#### Modpack version (Do not use "latest")
1.20
#### Your most recent crash report or log file where the issue was present
no crash

**Comment by NillerMedDild** [comment]
Titanium Ingots are craftable.

**Comment by Bickers07** [comment]
might want to add that its craftable in the arc furnace to the JEI info page as the recipe is pretty well hidden

**Comment by NillerMedDild** [comment]
Fair enough :)

**Comment by NillerMedDild** [comment]
You do realize it says `Obtainable through the Arc Furnace.` right?
