### ISSUE TITLE
everything rest 

### ISSUE THREAD

**Issue by 11lavey** [NillerMedDild/Enigmatica2Expert#500]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
when i updated to version 1.47 the pack rest everything and i lost my world

**Modpack version (Do not use "latest")**
version 1.47

**Logs**

If applicable, please upload your crash report, or latest.log to [hastebin](https://hastebin.com/).

**Screenshots**

**Additional context**

**Comment by NillerMedDild** [comment]
I'm guessing you updated to a new instance. Your world is in the old instance.
