### ISSUE TITLE
FPS boosting

### ISSUE THREAD

**Issue by SuperFurias** [NillerMedDild/Enigmatica2Expert#502]
**Is your feature request related to a problem? Please describe.**
Nothing. You can add the "Optifine" mod to the pack?
I always use it, and I notice a big difference in fps. But when I update the pack I'm forced to redo it and put it, could you do it?
**Describe the solution you'd like**
Add a mod xd
**Additional context**
I love optifine XD

**Comment by NillerMedDild** [comment]
No, absolutely not. I'm not allowed to legally, and I wouldn't add it if I was.
