### ISSUE TITLE
Client crash when Joining Server

### ISSUE THREAD

**Issue by maginator** [NillerMedDild/Enigmatica2Expert#503]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
When Joinen on my Server that I have Updated from Version 1.45 to 1.48 then my Client Crash.

**Modpack version (Do not use "latest")**
1.48

**Logs**
Crash Repo: https://gist.github.com/maginator/4c24d1cd3fc3398a5f94e213f72640ac
Latest log (Server and Client): https://gist.github.com/maginator/d61593eafa47aad2a0d6f67f83c11384 

If applicable, please upload your crash report, or latest.log to [hastebin](https://hastebin.com/).

**Screenshots**

**Additional context**

I added Redstone Paste v1.7.5

**Comment by NillerMedDild** [comment]
Can you reproduce this on a fresh install of 1.48?

**Comment by maginator** [comment]
Ah fresh install dosent help. When i use my World no new generated then it crash with the same issue. I also try to remove Redstone paste but this dosent change anything

**Comment by NillerMedDild** [comment]
Thank you for testing it :)

**Comment by NillerMedDild** [comment]
You can safely use version 1.47

**Comment by maginator** [comment]
Oki do you have an idear what the problem is?

**Comment by NillerMedDild** [comment]
Yes, a bug in Astral Sorcery, it has been fixed but I'm unable to update for a day or two.

**Comment by maginator** [comment]
yeah ok no problem
