### ISSUE TITLE
Crash with Tinkers I/O interactions

### ISSUE THREAD

**Issue by PiggyWhiskey** [NillerMedDild/Enigmatica2Expert#505]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
Crash when lever is turned on next to Tinkers I/O Smart Basin
Ender Fluid Conduit above Basin (From Drain)
Transfer Node below Basin (To Diamond Chest)
Lever next to Basin (Crash when turned on, and when re-loading game)

Basin has Redstone upgrade.
Fluid Conduit has "Enabled with Redstone High"

**Modpack version (Do not use "latest")**
1.46

Updated to 1.47: Crashed again

1.48 is on Github, but not Curseforge, so couldn't test

**Logs**

Crash log: https://paste.ee/p/qVTM5
If applicable, please upload your crash report, or latest.log to [hastebin](https://hastebin.com/).

**Screenshots**

**Additional context**

**Comment by NillerMedDild** [comment]
I will however investigate the repercussions further

**Comment by PiggyWhiskey** [comment]
For the moment I'm disabling Tinkers IO to remove the block and then load the pack again.

What's the trigger? 
I had a lever attached to the basin before adding the transfer node, 
Just don't put the transfer node on the basin?

**Comment by NillerMedDild** [comment]
Yep, it's the transfer node.

**Comment by PiggyWhiskey** [comment]
Noted, thank you for the very very fast response

**Comment by NillerMedDild** [comment]
Huh, apparently it does not cause corruption to update, so fixed in next update.
