### ISSUE TITLE
A use for large amounts of top-tier magic items: Convert to UU-Matter

### ISSUE THREAD

**Issue by OmaiGrundles** [NillerMedDild/Enigmatica2Expert#506]
One of my only complaints with this pack is that it seems once you got the few things you need in each magic mod, you never need to look into automating it. It would be nice to have *some* incentive, even if its a small one, for top-tier magic automation.

So the crazy idea came to my head: Allow the conversion of really hard-to-get-in-bulk magic items into small amounts of UU-Matter. even 1 mB for a void ingot, gaia ingot, greed rune, etc could be a fun alternative to recyclers and the mass fab, especially considering that all you need for UU-matter anyway is mostly just energy (and if the recyclers still take water bits, you don't even need to deal with cobblegen).

I mean it doesn't have to be UU-Matter, it just would be nice to have some reason to be crazy and automate some of the harder magic things in the pack, and I don't think Void Ingot Singularities would be fair to anyone who Isn't crazy.

I mean what else am I supposed to do with my thaumcraft rift-generating rig I made? :P

**Comment by NillerMedDild** [comment]
I like the idea, I'll see what I can do :)

**Comment by NillerMedDild** [comment]
I'm afraid I don't have time to work on this, sorry.
