### ISSUE TITLE
Stuck in bed.

### ISSUE THREAD

**Issue by HeavyDeception** [NillerMedDild/Enigmatica2Expert#508]
**Issue Description**
When sleeping with a sleeping bag (Cyclic) and a Sleep Charm (Dark Utilities) I get stuck sleeping the leave bed button dose not work.

**Modpack version (Do not use "latest")**
Version-1.47 Forage-14.23.5.2781

**Logs**
No Logs are left I have to force minecraft to close.

**Screenshots**

Nothing really to show.

**Additional context**

It dose not happen 100% of the time but it more frequent than it should be.
I not having the charm the same thing still happens.

**Comment by OneEyeMaker** [comment]
I can corfirm this issue with Sleeping Charm (from Dark Utilities) and vanilla bed.
On version of modpack 1.45 - 1.46 this problem occurs too.

**Comment by NillerMedDild** [comment]
Thank you for the report.
Does it happen without the Sleep Charm?

**Comment by GoldenKeyboard** [comment]
This is a vanilla bug

**Comment by GoldenKeyboard** [comment]
https://bugs.mojang.com/browse/MC-103299

**Comment by NillerMedDild** [comment]
I am aware, RandomPatches fixes that bug.

**Comment by GoldenKeyboard** [comment]
Oof. Send me your latest.log @HeavyDeception

**Comment by Ktanaqui** [comment]
Hey Niller! Just wanted to pop in and give you a teensy bit more information...
The SO and I were actually having this issue. Except, without the sleep charm. 

Ours basically went like this:
Devices: Two Windows 10 Laptops, Fiber (1G), Local LAN Host AND Local Server Host
-> SO tries running LAN host OR Local Server from his laptop and playing. 8GB allotted to client, not sure what he has allotted to the server. I know it doesn't appear to be maxing it. (24GB laptop)
-> SO local host connects to server (or is already in on LAN)
-> I connect directly to him via internal static IP

-> Results #1: Passing through Nether portal sporadically turns us invisible to the other. (whoever passed through is invisible... regardless of the direction) Relog fixes this issue. 
-> Result #2: If you are invisible and/or recently passed through the portal, sleeping results in being stuck in bed. 


We shifted the server over to an extra laptop (Lenovo Thinkpad). Also 24GB laptop. All it's doing is running the server and our security cameras. With both of us connecting to that laptop instead, it seems to have resolved these issues entirely for us.

**Comment by HeavyDeception** [comment]
This is the only one I have as it doesn't crash my game i'm just stuck sleeping and the leave bed button dose not work.

<script src="https://pastebin.com/embed_js/ykXXJVm4"></script>

**Comment by GoldenKeyboard** [comment]
No, when you get the cannot leave bed glitch
Immediatly force close your game and give me the latest.log

**Comment by NillerMedDild** [comment]
Bed Patch is a part of RandomPatches now.  There's no need to close the game, you can just kick yourself.

**Comment by HeavyDeception** [comment]
@NillerMedDild I can't im in SP and have cheats turned off.

**Comment by HeavyDeception** [comment]
@GoldenKeyboard I will do just that. Also if this help everything in the game moves normally, mods will still try to kill me and my armor will still take the damage.

**Comment by TellyO3** [comment]
@HeavyDeception Esc > Open to lan > Enable cheats = true > Profit

**Comment by NillerMedDild** [comment]
Esc is useless when you're stuck in bed.

**Comment by HeavyDeception** [comment]
@GoldenKeyboard I happened again but it doesn't leave a crash log.

**Comment by HeavyDeception** [comment]
@NillerMedDild I looked there was nothing in the crash reports but i do see a log folder will look again.

**Comment by HeavyDeception** [comment]
@NillerMedDild Ok my bad its a folder called logs. Here ya go https://pastebin.com/raw/SyJfUGis

**Comment by NillerMedDild** [comment]
Please set Twitch to use your latest java, and see if the issue persist.
Change Launch Method in Twitch > Minecraft settings to Jar Launcher.

**Comment by GoldenKeyboard** [comment]
I've gone through the log file and I cannot find anything except the console being spammed with illegal move attempts.

**Comment by NillerMedDild** [comment]
Same here.

**Comment by Lexon78** [comment]
Same bug in 1.57
I try install "BedBugs-1.12-1.0.1.jar" and for now is OK (not sure that by OK always)

**Comment by NillerMedDild** [comment]
The mod Beg Bugs is a part of RandomPatches, so you're getting a false positive.

**Comment by Lexon78** [comment]
> The mod Beg Bugs is a part of RandomPatches, so you're getting a false positive.

Then not work to me.

**Comment by Hexxonite** [comment]
BUMP.
Can confirm this Bug still exists in 1.5.6 non Skyblock with Vanilla Bed.

Have been playing on a server for 30 Hours, suddenly since today this problem exists. None one is able to sleep on the server, some people cant leave their beds and it wont get day, just stays night.

**Comment by MaxNeedsSnacks** [comment]
This only happens after switching dimensions with the Mekanism Porter, we can't fix this unfortunately.

**Comment by Lexon78** [comment]
I am not use Mekanism porter. I use only Ender book and TiC Brown magic mechanic. If i sruck in bed, then i not see any extra button for kick me from bed.
I see "Leave bed" button but nothing happend if i press. Bug is in vanilla bed and sleeping bag too.

**Comment by NillerMedDild** [comment]
The command `/kickme` should do the trick

**Comment by SeseMueller** [comment]
The Bug still occurs in 1.64d. In vanilla bed with sleep charm.

**Comment by SeseMueller** [comment]
It also happens when you emote right before you wake up (without the sleep charm)
