### ISSUE TITLE
Quest book is now blank

### ISSUE THREAD

**Issue by kmork1** [NillerMedDild/Enigmatica2Expert#509]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
I updated my modpack to 1.47 and when i loaded my world I my quest book was blank

**Modpack version (Do not use "latest")**
1.47

**Logs**

If applicable, please upload your crash report, or latest.log to [hastebin](https://hastebin.com/).

**Screenshots**

https://imgur.com/a/pByiMPl

**Additional context**

unsure if its your problems or not

**Comment by NillerMedDild** [comment]
I'm afraid that simply happens sometimes.
Load in a backup of your worlds betterquesting folder, and run the command `/bq_admin default load`

**Comment by kmork1** [comment]
I figured that out just didn’t post thanks anyway

**Comment by NillerMedDild** [comment]
It is, the mod dev is working on fixing it. Which version did it happen on this time @jestingstud?
You can restore your quest progress from a backup, both the modpack and betterquesting itself stores backups.

**Comment by jestingstud** [comment]
This happend on 1.49 as of today.

**Comment by jestingstud** [comment]
awesome! thank you
