### ISSUE TITLE
Mekanism Personal Chest invisible in inventory

### ISSUE THREAD

**Issue by ElliClaw** [NillerMedDild/Enigmatica2Expert#511]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
Mekanism's Personal Chest appears as a block, but is invisible in the inventory. It also doesn't show an icon in Waila. The issue wasn't present the last time I played in version 1.4.5

**Modpack version (Do not use "latest")**
1.47

**Logs**

If applicable, please upload your crash report, or latest.log to [hastebin](https://hastebin.com/).

**Screenshots**

**Additional context**

**Comment by NillerMedDild** [comment]
Duplicate of #490 
Thanks anyway :)
