### ISSUE TITLE
NuclearCraft Machines get stuck until GUI is reopened

### ISSUE THREAD

**Issue by SeooY** [NillerMedDild/Enigmatica2Expert#512]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**

Some NuclearCraft machines will get stuck processing until their GUI is accessed. For example, a Melter with 4 Speed Upgrades melting Cobblestone, and the Fission Reactor with IC2 Enriched Iron.

**Modpack version (Do not use "latest")**

1.4.8

**Logs**

If applicable, please upload your crash report, or latest.log to [hastebin](https://hastebin.com/).

**Screenshots**

Here's a video of it happening: https://streamable.com/qbdt8

**Additional context**

Apparently it only happens when the power buffer the machine needs gets too high, as for example the Melter won't get stuck with Iron or Slime, but Cobblestone requires a larger power buffer.

**Comment by NillerMedDild** [comment]
I take it you mean IC2 Enriched Uranium?

**Comment by NillerMedDild** [comment]
Anyhow, thanks for the report, and the video is very helpful :)

**Comment by SeooY** [comment]
Yeah, it's Uranium, I had a derp there
