### ISSUE TITLE
ic2 machines not properly blacklisted from cardboard box

### ISSUE THREAD

**Issue by DrTasslehoff** [NillerMedDild/Enigmatica2Expert#514]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**

ic2 machines are invalidated when boxed but the config needs no metadata. If you include metadata it doesn't do anything. Config just needs to be "ic2:te" and it will blacklist all 89 of the blocks and fixing the issue. 

**Modpack version (Do not use "latest")**

1.47/1.48 as well as skyblock 1.19

**Comment by NillerMedDild** [comment]
Thanks Doctor!
