### ISSUE TITLE
Slimesling Recipes

### ISSUE THREAD

**Issue by FryoKnight** [NillerMedDild/Enigmatica2Expert#517]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**

The Blue, Purple, Orange Slimeslings, as well as the Congealed Bloodsling still use the default crafting recipe, instead of the one requiring the Bow and 2 Leads.

**Modpack version (Do not use "latest")**

Enigmatica 2: Expert - Version 1.48a

**Logs**

N/A

**Screenshots**

![2019-01-02_03 24 47](https://user-images.githubusercontent.com/33318750/50584730-5d25d600-0e3f-11e9-9661-a756dc6e07e5.png)
![recipes](https://user-images.githubusercontent.com/33318750/50584734-631bb700-0e3f-11e9-865d-18edfcb08dde.png)

**Additional context**

**Comment by NillerMedDild** [comment]
Huh, cool. I didn't know they added the other variants. 

Thanks for the report!
