### ISSUE TITLE
Game Crash

### ISSUE THREAD

**Issue by keremlov** [NillerMedDild/Enigmatica2Expert#518]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
i get crashes whenever i try to open a modpack please help
and sometimes i get blue screen of death

**Modpack version **
1.48
**LOGS**
 https://hastebin.com/biralojezi.makefile

**Comment by NillerMedDild** [comment]
Something is seriously messed up. Try updating your graphics drivers, using the latest 64-bit Java, and setting allocated RAM amount to 6GB - But only if your PC has 8GB of RAM or more.
