### ISSUE TITLE
IC2 Lithium is not Smeltable to Lithium Ingots

### ISSUE THREAD

**Issue by Vyraal1** [NillerMedDild/Enigmatica2Expert#52]
#### Issue Description
There's a recipe inconsistency where IC2 Lithium Dust is not smeltable into NuclearCraft Lithium ingots. Normally this wouldn't be an issue but Mekanism processing reverts to IC2's dustLithium. I can also use the Oredictionificator however figured you might wanted to keep recipes consistent.

#### What you expected to happen
All Lithium dusts would smelt into ingots.

#### Modpack version (Do not use "latest")
1.21

**Comment by NillerMedDild** [comment]
I do indeed, thanks for the report :)

**Comment by NillerMedDild** [comment]
I'm guessing the main thing you need is compatibility for the Mekanism Smelter right?
