### ISSUE TITLE
Transforming Blocks after crash

### ISSUE THREAD

**Issue by KriKri98** [NillerMedDild/Enigmatica2Expert#521]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**

I broke some Soggy Garden from Pam´s Harvestcraft. After picking up some drops the game crashed. After reload of the world some blocks turned into other blocks. Mostly modded changed. Game crashed a few seconds after joining it. 

**Modpack version (Do not use "latest")**
Version 1.48a

**Logs**
https://hastebin.com/aveyaviqeh.rb
If applicable, please upload your crash report, or latest.log to [hastebin](https://hastebin.com/).

**Screenshots**
![2019-01-02_14 41 28](https://user-images.githubusercontent.com/46320871/50594855-86c21a00-0e9e-11e9-9236-39b821f22f14.png)
![2019-01-02_14 52 14](https://user-images.githubusercontent.com/46320871/50594868-93df0900-0e9e-11e9-8b31-619d69b70d7f.png)

**Additional context**

**Comment by NillerMedDild** [comment]
Could you please reupload the crash log? The hastebin link is empty.

**Comment by NillerMedDild** [comment]
Nevermind, found the issue: https://github.com/HellFirePvP/AstralSorcery/issues/959
Hotfix incoming asap.
