### ISSUE TITLE
Flux Network's flux core not craftable

### ISSUE THREAD

**Issue by ErosM** [NillerMedDild/Enigmatica2Expert#522]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
It's impossible to craft Flux Core from Flux Network mod because the recipe requires a Flux Core to begin with

**Modpack version (Do not use "latest")**
Version 1.48a

**Logs**

If applicable, please upload your crash report, or latest.log to [hastebin](https://hastebin.com/).

**Screenshots**
![2019-01-02_15 57 42](https://user-images.githubusercontent.com/24549189/50597379-8c702d80-0ea7-11e9-8ee7-71f9bc17c287.png)

**Additional context**

**Comment by TheWiz4rdZ** [comment]
Look at the Sag Mill recipe, mate
