### ISSUE TITLE
Full Crash After loading in update

### ISSUE THREAD

**Issue by StephJ2Fan** [NillerMedDild/Enigmatica2Expert#523]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
I loaded up my game as normal. I loaded in my game. Everything seemed to be going great. It showed rain, and then 2 seconds later I got a server shutting down message and then the game completely crashed out

**Modpack version (Do not use "latest")**
1.4.8a minus the discord mod

**Logs**

https://pastebin.com/ymzs8DUi

**Screenshots**

**Additional context**

**Comment by NillerMedDild** [comment]
Update to 1.49, and let me know if that resolves it please :)

**Comment by StephJ2Fan** [comment]
That seems to have fixed it. I noticed the update after the crash but hadn't updated yet. LOL. Thank you!

**Comment by NillerMedDild** [comment]
Sure thing, glad it worked!
