### ISSUE TITLE
Decorative Blocks (Cathedral + XTones)

### ISSUE THREAD

**Issue by TheWiz4rdZ** [NillerMedDild/Enigmatica2Expert#524]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Question or Issue**
Was just thinking that it would be great if we had one or two mods to add some more variety on the Decorative side, in the form of a small, yet unknown mod, the chisel addon Cathedral, which adds some Dwarven related stuff, or/and in the form of a bigger mod, like XTones

**Modpack Version**
Latest ( ͡° ͜ʖ ͡°)
(Actually, 1.49 xD)

**Additional Context**
I’ve been using them on SP and thought that maybe you would like to add them as well to the pack :)

**Comment by NillerMedDild** [comment]
I would love to, but I'm trying to keep load times down :/ Sorry.

**Comment by TheWiz4rdZ** [comment]
No worries, mate. Just trying to make people enjoy this pack as much as I do :)

**Comment by NillerMedDild** [comment]
D'awww :P
