### ISSUE TITLE
Nuclear craft silicon

### ISSUE THREAD

**Issue by Leon1236** [NillerMedDild/Enigmatica2Expert#525]
**Issue Description**
Upon updating to 1.49 silicon from applied energetic was replaced with Nuclearcraft one.
You could get AE silicon from Material stonework factory and now you get only Nuclearcraft silicon.
Crafting of electrical steel is only possible with nuclearcraft silicon in Induction smelter, NC alloy furnace recipe works.
You can exchange AE silicon to NC silicon with extra steps.
Dont know if this is intentional or random occurrence.

**Modpack version (Do not use "latest")**
1.49

**Comment by NillerMedDild** [comment]
This is not intentional, thank you for letting me know :)

**Comment by NillerMedDild** [comment]
I'll add the missing Induction Smelter recipe.
