### ISSUE TITLE
JEI hang up

### ISSUE THREAD

**Issue by VashRatax** [NillerMedDild/Enigmatica2Expert#528]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
Game hangs up on JEI, then crashes after awhile. 

**Modpack version (Do not use "latest")**
1.49

**Logs**
https://hastebin.com/jezomudidi.sql
If applicable, please upload your crash report, or latest.log to [hastebin](https://hastebin.com/).

**Screenshots**

**Additional context**

**Comment by NillerMedDild** [comment]
Your hastebin link is empty, please re-upload :)

**Comment by GoldenKeyboard** [comment]
aused by: java.lang.OutOfMemoryError:

**Comment by GoldenKeyboard** [comment]
You are only allocating 2.7gb of ram for minecraft; which is not enough for the size of this modpack.
I recommend atleast 4gb and advise 8gb.
