### ISSUE TITLE
[Integrated dynamics/tunnels] Networks corrupting after server crash.

### ISSUE THREAD

**Issue by tonalom** [NillerMedDild/Enigmatica2Expert#529]
**Issue Description**

While playing on a server, I noticed that whenever the server suffered a crash, the interfaces from integrated tunnels seem to lose their function, in turn just saying "Network corrupted" in their interface. A solution for the issue is to just re-place either the interface or the cable connecting to it. I had a look through a crash report of the server, but found nothing related to the integrated tunnels.

**Modpack version (Do not use "latest")**

Version 1.4.9a

**Logs**

Looked through server crash report, nothing related to integrated tunnels to be found.

**Screenshots**

![snip](https://user-images.githubusercontent.com/40698635/50617398-535aac00-0eed-11e9-9169-f1204904e270.JPG)

**Additional context**

**Comment by NillerMedDild** [comment]
Please provider the server's latest.log :)
https://github.com/CyclopsMC/IntegratedDynamics/issues/648
