### ISSUE TITLE
Petal Apothecary & Runic Altar Uncraftable

### ISSUE THREAD

**Issue by TwilightPSN** [NillerMedDild/Enigmatica2Expert#53]
Botania Petal Apothecary & Runic Altar do not have a crafting recipe on pack version 1.22

Edit: the scipts for the recipes appear to be present but the recipes do not show up

**Comment by NillerMedDild** [comment]
Have you tried restarting the game? Redownloading the pack?

**Comment by TwilightPSN** [comment]
restarting my server seems to now have fixed this i had to restart the server like 5 times though

**Comment by NeosGhost** [comment]
I know this is closed but I got this issue today running pack version 1.49.

**Comment by NillerMedDild** [comment]
Did you craft the Luminous Crafting Table yourself?

**Comment by NeosGhost** [comment]
Yes I did. The problem went away after a server restart. Other thing noticed was the botania flowers had no particle effects while the recipe was not showing.

Thanks

**Comment by NillerMedDild** [comment]
Cool :)

**Comment by Miky691** [comment]
I'm having the same problem now on version 1.54 with the runic altar i have quitted and re-enterer the wolrd and that did not fix it. quitting and re opening the modpack fixed that

**Comment by shikyo13** [comment]
Just wanted to let you know this issue persists in 1.56, restarting MC did indeed resolve it and show the recipes.
