### ISSUE TITLE
Thorium ingots not stacking in furnace

### ISSUE THREAD

**Issue by tonalom** [NillerMedDild/Enigmatica2Expert#530]
**Issue Description**

When smelting thorium ore inside of a vanilla minecraft furnace, once an ingot is done processing, another one will not start processing until the first ingot is removed as they do not seem to stack inside the furnace. As soon as the ingots are moved into a different inventory however, they stack like normally.

**Modpack version (Do not use "latest")**

1.4.9a

**Logs**

No crash report available as the issue is not related to crashing.

**Screenshots**

<img width="254" alt="thorium github report 1" src="https://user-images.githubusercontent.com/40698635/50617601-6457ed00-0eee-11e9-85a6-c3ae24c68da2.png">
<img width="149" alt="thorium github report 2" src="https://user-images.githubusercontent.com/40698635/50617603-6752dd80-0eee-11e9-9c85-7ee31a477a68.png">

**Additional context**

**Comment by NillerMedDild** [comment]
I have no idea how to fix this :P

**Comment by JayRS152** [comment]
Can confirm. turbodiesel4598/NuclearCraft#455
