### ISSUE TITLE
Oredict Oil

### ISSUE THREAD

**Issue by valarnin** [NillerMedDild/Enigmatica2Expert#531]
**Is your feature request related to a problem? Please describe.**
Immersive Tech's oil is not possible to fully automate. The pumpjack must be moved when the chunk is depleted.

**Describe the solution you'd like**
Allow Thermal Foundation's oil to be used in its place/oredicted. This would allow for oil shale from Thermal Foundation to be used to get Lubricant via the Distillation Tower, and Oil Shale can be gotten from Industrial Foregoing's laser setup.

**Additional context**
Lubricant is required for various recipes from Advanced Rocketry's Rolling Machine.

**Comment by NillerMedDild** [comment]
Good idea.
