### ISSUE TITLE
NuclearCraft Fission Reactor Power Output Unconsistent

### ISSUE THREAD

**Issue by Newek** [NillerMedDild/Enigmatica2Expert#532]
**Issue Description**
 
The NuclearCraft Fission Reactor seems to transfer its energy at a slower rate than normal : even though my cable and powerbank could sustain the RF production, energy builds up in the reactor. I've tried with many cables and powerbank, but none of them seems to solve the issue.
I've also noticed that appart from NuclearCraft, everything works just fine (Ender IO and Mekanism powerbanks; Ender IO, Mekanism and Thermal Foundation ernergy conduits).

It seems the reactor only interact with nearby conduits once every few game ticks (around 3 or 4, difficult to count however) : the energy constantly builds up in the reactor, but each time it interacts with conduit, the buffer empties up, then the transfer stops (noticeable with Mekanism powerbank) and the energy builds up again. Du to this oscillation, the average transfer rate is indeed lower than normal.

I am pretty sure none of that was occuring before 1.47-1.46, since I've designed the reactor in my testing world, and tested it with powerbank attached to.

**Modpack version (Do not use "latest")**
1.49

**Screenshots**

Here's some screenshots of my setup, where we can see the issue :
![2019-01-03_00 08 15](https://user-images.githubusercontent.com/46331161/50617818-4f2f8e00-0eef-11e9-9c14-704b7ca93e48.png)
The Reactor is simply hooked up to a Ender IO Capacitor Bank with Cryo-Stabilized Fluxduct. The Capacitor Bank have a Max I/O of 100 kRF/t, with no output transfer.
![2019-01-03_00 08 04](https://user-images.githubusercontent.com/46331161/50617854-8c941b80-0eef-11e9-94ed-8fde6e426a07.png)
The average transfer rate on the capacitor bank stays between 14k and 18k RF/t, which is much slower than the 50k produced.

**Additional context**

**Comment by NillerMedDild** [comment]
Reported here: https://github.com/turbodiesel4598/NuclearCraft/issues/422

**Comment by NillerMedDild** [comment]
Fixed in his dev environment :)

**Comment by Newek** [comment]
Thank you !
