### ISSUE TITLE
Disable Animania flower eating

### ISSUE THREAD

**Issue by Natrukei** [NillerMedDild/Enigmatica2Expert#533]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
I placed 4 pure daisies and 1 endoflame.
A day later or so one of the daisies disappeared. Now, a few days late I only have 2 pure daisies left.

**Modpack version (Do not use "latest")**
1.46

**Logs**

This doen't result in a crash

**Screenshots**

I think it would not help much show the other plants

**Additional context**

I am playing on a server

**Comment by Natrukei** [comment]
Is decay on ALL botania flowers?

**Comment by NillerMedDild** [comment]
Decay is not on, but I believe some animals can actually eat Botania flowers. Could that be your issue?

**Comment by scotty9090** [comment]
Botania flowers can most definitely be eaten by Animania animals - and this includes the functional flowers IIRC.  They did a good job of ruining my nicely laid out Mystical Flower bed.

I need to do some testing to see if I can recreate, but I'm 99% certain that I watched an Animania goat eat my IC2 BatBox and a cable the other day.  Which could explain issues I've had in a previous playthrough with IC2 stuff randomly vanishing.  If I can recreate, I'll open an issue specifically on this, but I'm wondering if this block griefing feature for Animania should be disabled in general?
