### ISSUE TITLE
Add PackagedAuto

### ISSUE THREAD

**Issue by tornewuff** [NillerMedDild/Enigmatica2Expert#535]
**Is your feature request related to a problem? Please describe.**

Setting up AE2 autocrafting for "big" recipes that need to be made many times is a pain, e.g. the extended crafting pedestal craft recipes that make crafting ingredients like benitoite and anglesite, or the ultimate crafting table recipe that makes ultimate ingots. While you can work around this by using other crafting setups that aren't on-demand autocrafting, or by doing tricks with chained recipes using token items, it's still clunky and awkward and sometimes breaks if you don't have a dedicated crafting setup for each recipe.

**Describe the solution you'd like**

PackagedAuto lets you define recipes with up to 81 itemstacks in them, enough to even do the ultimate ingot recipe, and integrates nicely with AE2: it defines up to 9 different "recipe package" items for each recipe, containing up to 9 items each, and then a final recipe that takes all the packages and produces the output. The unpackager block just dumps all the individual ingredients into an inventory at once. This removes pretty much all the problems with trying to autocraft these recipes, and seems like a really nice addition to any pack that uses AE2 and has this type of recipe in the endgame. :)

**Comment by NillerMedDild** [comment]
I will look into it, it does indeed sound like a good addition.
