### ISSUE TITLE
Missing Crushed Cobalt Ore Recipe (IC2 Macerator Process)

### ISSUE THREAD

**Issue by TheWiz4rdZ** [NillerMedDild/Enigmatica2Expert#536]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
My IC2 Ore Processing got stuck and when I saw the buffer chest, there was only Cobalt Ore. Checked JEI for it's crushed form and the Macerator recipe was missing.

**Modpack version (Do not use "latest")**
Latest #gettriggeredNiller
(jk, I'm on 1.49)

**Logs**

If applicable, please upload your crash report, or latest.log to [hastebin](https://hastebin.com/).

**Screenshots**

**Additional context**

**Comment by NillerMedDild** [comment]
*is triggered*

**Comment by scotty9090** [comment]
"is triggered"

Me too. :)  This used to work in prior versions of the pack - is this a mod issue or a pack issue?

**Comment by NillerMedDild** [comment]
Pack issue.

**Comment by NillerMedDild** [comment]
I am unable to fix this issue, the recipe doesn't want to be registered for some reason.

**Comment by TheWiz4rdZ** [comment]
That is weird, maybe report to JAOPCA or IC2 devs?

**Comment by NillerMedDild** [comment]
https://bt.industrial-craft.net/view.php?id=2467
