### ISSUE TITLE
Config file case mismatches and a small tweak

### ISSUE THREAD

**Issue by tornewuff** [NillerMedDild/Enigmatica2Expert#537]
**Issue Description**

Several of the config files in the modpack have the wrong filename case, causing them to be ignored on Linux and a default config generated instead:

`integrationforegoing.cfg` should be `IntegrationForegoing.cfg`
`IndustrialForegoing.cfg` should be `industrialforegoing.cfg` (yes, opposite to each other..)
`enderio/EnderIO.cfg` should be `enderio/enderio.cfg`

It'd also be useful to add "AE2Stuff=AppliedEnergistics2" as a mod alias in the morphtool config (didn't want to make a whole other issue just for this).

**Modpack version (Do not use "latest")**

1.49

**Logs**

N/A

**Screenshots**

N/A

**Additional context**

**Comment by NillerMedDild** [comment]
Damnit, I did a case check only 3 months ago, damn mod devs :P Thanks for the report, I'll get it fixed.
