### ISSUE TITLE
Menril Berries

### ISSUE THREAD

**Issue by GoldenKeyboard** [NillerMedDild/Enigmatica2Expert#539]
Menril Berries currently give 4 hunger and 3 saturation and drop roughly 15 per tree.
I feel for an expert modpack that this is far too much and too easy to farm.

**Comment by drakkensong21** [comment]
Have you seen all the free food you get from loot chests

**Comment by GoldenKeyboard** [comment]
That doesn't relate to my suggestion?

**Comment by Linerunner99** [comment]
Go ahead... keep eating them. They give 0 nutrition... watch your debuffs pile up.

**Comment by NillerMedDild** [comment]
I decreased their drop chance.
