### ISSUE TITLE
BoP world generation crash

### ISSUE THREAD

**Issue by Qaz17** [NillerMedDild/Enigmatica2Expert#540]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
Server crashes when players start exploring/generating new chunks

**Modpack version (Do not use "latest")**

1.49

Similar thing was also happening in 1.46 (added crash log)

**Logs**

If applicable, please upload your crash report, or latest.log to [hastebin](https://hastebin.com/).

Crash log (from 1.49): https://hastebin.com/junixihara.rb
Crash log (from 1.46): https://hastebin.com/etekezadum.rb

**Screenshots**

**Additional context**

Only happens in overworld

**Comment by NillerMedDild** [comment]
Thank you for the report, I'll try to reproduce this asap.

**Comment by GoldenKeyboard** [comment]
OK, so looking into those crash files leaves me with a question:
Why is a mod's world gen trying to get the enum BOPTrees from a nether wart block.

**Comment by NillerMedDild** [comment]
That is a good question. Unfortunately the BoP Issue Tracker requires tons of information for bug reports, so it will have to be reproduced locally.

**Comment by Chiiruno** [comment]
I've been having periodic crashing in a server I'm playing using this modpack ever since 1.49, could this be related?
Seems to either happen with new chunks, or just on it's own.
The server will barely update anything to the client until it eventually restarts.

**Comment by NillerMedDild** [comment]
I would need your crash log to be able to tell.

**Comment by Chiiruno** [comment]
I'll ask the server owner.

**Comment by NillerMedDild** [comment]
That does sound related. It seems the crash is caused by Nether Wart.

**Comment by NillerMedDild** [comment]
I cannot reproduce this with BoP and JEI only.

**Comment by Kyrll** [comment]
I'm the server owner from before. Looking through the crash log it appears to be something different to this issue but it's still a crash. The server has crashed 10 times since we updated to .49 a few days ago, each log appears to be the same. Here's the latest one.
I know this should be on a separate issue tracker but eh.
[crash-2019-01-05_09.10.12-server.txt](https://github.com/NillerMedDild/Enigmatica2Expert/files/2729595/crash-2019-01-05_09.10.12-server.txt)

**Comment by Kyrll** [comment]
Huh, actually looking at the thing it looks like the crash occurs when a butterfly enters the twilight forest portal. Sorry for messing the thread up.

**Comment by NillerMedDild** [comment]
No worries :)

**Comment by Chiiruno** [comment]
The server hasn't crashed since we removed the twilight forest portal, which the butterflies were entering.
I can't rule out the two crashes being unrelated, but perhaps a new issue needs to be made so this one doesn't further get off-topic.

**Comment by NillerMedDild** [comment]
That's a good idea.

**Comment by NillerMedDild** [comment]
I'm beginning to think your world is corrupted @Qaz17 
I cannot reproduce this at all.

**Comment by Qaz17** [comment]
Shouldn't it then keep crashing if we go to the chunk that caused the crash? Server is playable till we explore and hit a random chunk, although it didn't happen for some time now.

Also as i mentioned it was also happening in 1.46, just then we were getting crashes about IC2 leaves (too bad I don't have those logs anymore)

If it happens again, I can post the log again.

**Comment by NillerMedDild** [comment]
Well no, it looks like the corruption self-corrects every time you encounter it... I guess :P

**Comment by Chiiruno** [comment]
I can reproduce a timeout (not sure about crash) where everything becomes super slow when going to a flower BoP biome.

**Comment by Chiiruno** [comment]
You'll have to ask @Kyrll.
