### ISSUE TITLE
Typo in IC2 recycler

### ISSUE THREAD

**Issue by phazingazrael** [NillerMedDild/Enigmatica2Expert#542]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Question or Issue**
More of a grammatical issue, not a high priority I'd imagine.
The quest for the Recycler in IC2 has a typo in the description where it says Scrab instead of Scrap.

**Modpack Version**
Expert 1.49

**Additional Context**
Copied down the full description for simplicity,

"The Recycler produces scrap if you feed it with items and power. **Scrab** can be used to drastically reduce the amount of power needed to produce UU Matter."

**Comment by NillerMedDild** [comment]
Woops, thanks!

**Comment by NillerMedDild** [comment]
Sigh, I even spelt it right a few words earlier.
