### ISSUE TITLE
AE2 voids pink slime & liquid meat

### ISSUE THREAD

**Issue by Cynder111** [NillerMedDild/Enigmatica2Expert#543]
Using the "ME Fluid Import Bus" on the "Mob Slaughter Factory" it drains the content but does not show up in the system. I tried the same with a tank of pink slime and the content disappear as well.  Creosote oil still works fine. same for water.

Modpack version: 1.49

No crash log

No screenshot

I updated from 1.46 straight to 1.49. Not sure if this causes problems.

P.S. I cannot reproduce the problem in SP.

**Comment by Cynder111** [comment]
Ok a server restart fixed the problem

**Comment by NillerMedDild** [comment]
I appreciate the report anyway :)
