### ISSUE TITLE
Un-hide different salt types in JEI

### ISSUE THREAD

**Issue by akvgergo** [NillerMedDild/Enigmatica2Expert#547]
**Is your feature request related to a problem? Please describe.**
In JEI only Mekanism salt shows up, hiding a lot of early game options (animalia and Pam's, for example) which could be an issue. Salt is fairly important early to mid-early game since it opens up a lot of different food varieties, and is fairly easy to automate except for the only recipe that shows up, which is the water + pot one that can't be automated until the player has access to autocrafters and/or autofilling mechanisms.

**Describe the solution you'd like**
Unhiding the different salt types would let the player know of other ways to get it, like the water filter from Pam's.

**Additional context**
*None*

**Comment by NillerMedDild** [comment]
Good point, will do.
