### ISSUE TITLE
Game Crash

### ISSUE THREAD

**Issue by hihi9190** [NillerMedDild/Enigmatica2Expert#548]
**Issue Description**
Crash a few seconds after loading world.

Edit: It was after using the Slime Slingshot (from tinker's construct) when I logged into the world

**Modpack version (Do not use "latest")**
1.49

**Logs**

https://hastebin.com/etebazivey.rb

**Comment by NillerMedDild** [comment]
Reinstall the modpack :) please let me know if it helps.

**Comment by pikminjm9** [comment]
Reinstalled and all is good now. Ty

**Comment by hihi9190** [comment]
No more issues after reinstalling, thanks :)

**Comment by NillerMedDild** [comment]
Awesome :D
