### ISSUE TITLE
 hippogriff can not fly

### ISSUE THREAD

**Issue by Designoutlaw** [NillerMedDild/Enigmatica2Expert#549]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**  Server kicks players riding hippogriff quoting "server does not allow flying"   with the enable flying server setting set to true.  The player is OP and still gets kicked.

**Modpack version (Do not use "latest")**  Version 1.46

**Logs**

Logs only state that it was forcibly closed by remote host. 

**Screenshots**

**Additional context**

**Comment by NillerMedDild** [comment]
Can you reproduce this on 1.49?
