### ISSUE TITLE
Integrated dynamics quest from book not working and achievments missing ?

### ISSUE THREAD

**Issue by Gayanfalor** [NillerMedDild/Enigmatica2Expert#550]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
quest from the ID book are not working and the achievments from the mod are misisng i remember there was many to do and here only 4 node ?

**Modpack version (Do not use "latest")**
1.49

**Logs**
My server admin said :"@Gayan With regards to the integrated dynamics challenges, there are some error messages in the server log:
`[20:42:58] [Server thread/ERROR] [FML]: Parsing error loading built-in advancement integrateddynamics:meneglin_basics/menril_production
com.google.gson.JsonSyntaxException: Unknown recipe 'integrateddynamics:menril_planks'
[20:42:58] [Server thread/ERROR] [FML]: Parsing error loading built-in advancement integratedtunnels:root
com.google.gson.JsonSyntaxException: Unknown recipe 'integratedtunnels:part_player_simulator_item'
[20:42:58] [Server thread/ERROR] [net.minecraft.advancements.AdvancementList]: Couldn't load advancement integrateddynamics:advanced_operations/logical_list_building: Task Advancement{parentId=integrateddynamics:logic_operations/logic_programming, display=net.minecraft.advancements.DisplayInfo@6cbd272d, rewards=AdvancementRewards{experience=0, loot=[], recipes=[], function=null}, criteria={criteria_0=net.minecraft.advancements.Criterion@6db1116b}, requirements=[[criteria_0]]}
..`"

If applicable, please upload your crash report, or latest.log to [hastebin](https://hastebin.com/).

**Screenshots**
Achievment page  https://images-ext-2.discordapp.net/external/njV5X0bx3vrIg6uQEUcMuZIzcXJv4dmDa2Tf2jHUGDg/https/puu.sh/CrwEP/f2eb3afb09.png?width=1276&height=676

**Comment by NillerMedDild** [comment]
Integrated Dynamics quests/advancements are messed up because I changed some recipes for it, it has no way of handling it.

**Comment by Gayanfalor** [comment]
oh ok, so its not a bug ^^, its not impacting the game so i still can use the mod without problem ?

**Comment by NillerMedDild** [comment]
Yep :)

**Comment by Cyprex** [comment]
How would I restore the advancements? Disabling IntegratedDynamics.zs seems to have no effect on them, and I couldn't find any other references to the mod in config+scripts

**Comment by NillerMedDild** [comment]
ID planks have their recipe altered through the plankWood oredict, in the MiscScripts :)

**Comment by Cyprex** [comment]
Thank you!
