### ISSUE TITLE
Creative wireless crafting terminal recipe broken

### ISSUE THREAD

**Issue by tornewuff** [NillerMedDild/Enigmatica2Expert#551]
**Issue Description**

The recipe for the creative wireless crafting terminal shows as only requiring a creative powercell, instead of a powercell plus a regular wireless crafting terminal.

(also, on updating to 1.49 my infinity booster card disappeared, because its ID changed when that item was moved to ae2wtlib, but I guess there's nothing easily to be done to avoid that - maybe the changelog should mention this though?)

**Modpack version (Do not use "latest")**

1.49

**Logs**

n/a

**Screenshots**

n/a

**Additional context**

**Comment by NillerMedDild** [comment]
Oh right, I forgot about that ^^'

**Comment by NillerMedDild** [comment]
Oddly enough, the recipe works just fine.

**Comment by NillerMedDild** [comment]
I added a tooltip ^^

**Comment by tornewuff** [comment]
I did cheat in a new Infinity Booster, yes ;)
