### ISSUE TITLE
Remove Luminous Crafting Table recipe, add tooltip

### ISSUE THREAD

**Issue by Lazarix** [NillerMedDild/Enigmatica2Expert#552]
**Issue Description**
Because of the fact that some of the astral sorcery items are craftable in vanilla tables, there is a problem with getting into astral sorcery.

If you craft the luminous crafting table on a vanilla bench, it will craft.
However, because you didn't do it at a floating crystal, the "your vision expands" and "you learned more about 'Exploration'" triggers don't proc.
[like this](https://i.imgur.com/uapZNcv.png)

This means that you get problems like #238 and #430. You can't proceed through astral sorcery without proccing those gates, which you can only do at a floating crystal.

Once you craft the luminous crafting table at a floating crystal, everything is fine and it will then let you craft recipes inside the luminous crafting table.

**Modpack version 1.49**

**Comment by NillerMedDild** [comment]
Thanks for letting me know, I was not aware of this.
