### ISSUE TITLE
Blacklist Ex Nihilo Creatio from Carry On

### ISSUE THREAD

**Issue by knord1** [NillerMedDild/Enigmatica2Expert#553]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**

CarryOn and ExNihilo sieve shift-right-click conflict.
Unable to plop out the sieve mesh from sieves.

**Modpack version (Do not use "latest")**

1.49

**Logs**

**Screenshots**

**Additional context**

I fixed this by adding CarryOn blacklist for "exnihilocreatio:block_sieve".

**Comment by NillerMedDild** [comment]
The default keybinding for CarryOn is right shift, did you change it to left shift?

**Comment by knord1** [comment]
I used default settings.
CarryOn: Shift+right-click "pick thing up"
ExNihi: Shift+right-click "plop out mesh from sieve".

CarryOn takes priority.


I am using Swedish keyboard layout (if that can have any influence).


And since the sieve can be harvested with your fists I think CarryOn might be a less then useful.

**Comment by NillerMedDild** [comment]
Damn, I guess I must've set the keybinding wrong. I'll blacklist sieves - Thank you for the report.
