### ISSUE TITLE
Server Instability

### ISSUE THREAD

**Issue by zEnry185** [NillerMedDild/Enigmatica2Expert#556]
**Question or Issue**
I'm hosting a server, but it lags quite often, but I'm unable to understand the reason.
The world is almost new (about 24h) so there are not many objects that could cause lag.

**Modpack Version**

Enigmatica 2 Expert 1.49

**Additional Context**

The hardware is:
CPU: Xeon Gold 6140 (18c/36t)
RAM: 32Gb DDR4

It uses less than the 10% of the CPU and 5.5-6Gb of RAM.

[21:28:30] [Server thread/WARN] [minecraft/MinecraftServer]: Can't keep up! Did the system time change, or is the server overloaded? Running 14490ms behind, skipping 289 tick(s)
> [21:28:42] [Server thread/WARN] [minecraft/MinecraftServer]: Can't keep up! Did the system time change, or is the server overloaded? Running 8318ms behind, skipping 166 tick(s)
> [21:29:11] [Server thread/WARN] [minecraft/MinecraftServer]: Can't keep up! Did the system time change, or is the server overloaded? Running 16261ms behind, skipping 325 tick(s)
> [21:29:15] [Server thread/WARN] [minecraft/MinecraftServer]: Can't keep up! Did the system time change, or is the server overloaded? Running 3861ms behind, skipping 77 tick(s)
> [21:29:40] [Server thread/WARN] [minecraft/MinecraftServer]: Can't keep up! Did the system time change, or is the server overloaded? Running 14603ms behind, skipping 292 tick(s)
> [21:29:51] [Server thread/WARN] [minecraft/MinecraftServer]: Can't keep up! Did the system time change, or is the server overloaded? Running 6893ms behind, skipping 137 tick(s)
> [21:30:18] [Server thread/WARN] [minecraft/MinecraftServer]: Can't keep up! Did the system time change, or is the server overloaded? Running 15683ms behind, skipping 313 tick(s)
> [21:30:22] [Server thread/WARN] [minecraft/MinecraftServer]: Can't keep up! Did the system time change, or is the server overloaded? Running 3920ms behind, skipping 78 tick(s)
> [21:30:48] [Server thread/WARN] [minecraft/MinecraftServer]: Can't keep up! Did the system time change, or is the server overloaded? Running 15106ms behind, skipping 302 tick(s)
> [21:30:52] [Server thread/WARN] [minecraft/MinecraftServer]: Can't keep up! Did the system time change, or is the server overloaded? Running 4180ms behind, skipping 83 tick(s)
> [21:31:20] [Server thread/WARN] [minecraft/MinecraftServer]: Can't keep up! Did the system time change, or is the server overloaded? Running 15516ms behind, skipping 310 tick(s)
> [21:31:24] [Server thread/WARN] [minecraft/MinecraftServer]: Can't keep up! Did the system time change, or is the server overloaded? Running 3986ms behind, skipping 79 tick(s)
> [21:31:52] [Server thread/WARN] [minecraft/MinecraftServer]: Can't keep up! Did the system time change, or is the server overloaded? Running 17221ms behind, skipping 344 tick(s)
> [21:31:57] [Server thread/WARN] [minecraft/MinecraftServer]: Can't keep up! Did the system time change, or is the server overloaded? Running 4256ms behind, skipping 85 tick(s)
> [21:32:26] [Server thread/WARN] [minecraft/MinecraftServer]: Can't keep up! Did the system time change, or is the server overloaded? Running 16858ms behind, skipping 337 tick(s)
> [21:32:30] [Server thread/WARN] [minecraft/MinecraftServer]: Can't keep up! Did the system time change, or is the server overloaded? Running 4157ms behind, skipping 83 tick(s)
> [21:32:59] [Server thread/WARN] [minecraft/MinecraftServer]: Can't keep up! Did the system time change, or is the server overloaded? Running 16873ms behind, skipping 337 tick(s)
> [21:33:03] [Server thread/WARN] [minecraft/MinecraftServer]: Can't keep up! Did the system time change, or is the server overloaded? Running 4013ms behind, skipping 80 tick(s)
> [21:33:37] [Server thread/WARN] [minecraft/MinecraftServer]: Can't keep up! Did the system time change, or is the server overloaded? Running 20121ms behind, skipping 402 tick(s)
> [21:33:42] [Server thread/WARN] [minecraft/MinecraftServer]: Can't keep up! Did the system time change, or is the server overloaded? Running 4425ms behind, skipping 88 tick(s)
> [21:34:14] [Server thread/WARN] [minecraft/MinecraftServer]: Can't keep up! Did the system time change, or is the server overloaded? Running 18922ms behind, skipping 378 tick(s)
> [21:34:18] [Server thread/WARN] [minecraft/MinecraftServer]: Can't keep up! Did the system time change, or is the server overloaded? Running 4159ms behind, skipping 83 tick(s)
> [21:34:51] [Server thread/WARN] [minecraft/MinecraftServer]: Can't keep up! Did the system time change, or is the server overloaded? Running 19981ms behind, skipping 399 tick(s)
> [21:34:55] [Server thread/WARN] [minecraft/MinecraftServer]: Can't keep up! Did the system time change, or is the server overloaded? Running 4331ms behind, skipping 86 tick(s)
> [21:35:23] [Server thread/WARN] [minecraft/MinecraftServer]: Can't keep up! Did the system time change, or is the server overloaded? Running 15967ms behind, skipping 319 tick(s)
> [21:35:28] [Server thread/WARN] [minecraft/MinecraftServer]: Can't keep up! Did the system time change, or is the server overloaded? Running 4209ms behind, skipping 84 tick(s)
> [21:35:58] [Server thread/WARN] [minecraft/MinecraftServer]: Can't keep up! Did the system time change, or is the server overloaded? Running 17925ms behind, skipping 358 tick(s)
> [21:36:02] [Server thread/WARN] [minecraft/MinecraftServer]: Can't keep up! Did the system time change, or is the server overloaded? Running 4593ms behind, skipping 91 tick(s)

**Comment by t3rraz** [comment]
ist possible, your CPU is too weak ? 2.3 GHz, i think Minecraft uses Only 1-2 CPU Cores, so your CPU is Good, but not for Minecraft? I run our Server on a I 7700K with 4.5 GHz, works Smooth. And Ram i have 16 But, for this Pack i use 8 GB

**Comment by NillerMedDild** [comment]
Minecraft can only utilize 1 CPU Core, so that is probably what is causing you trouble, as t3rraz suggests. 
What is the TPS of the server?

Sometimes a newly generated world will generate something tick intensive in the spawn chunks, making the server laggy almost immediately. I suggest installing Tick Profiler and LagGoggles, and trying to find the cause of lag :)
