### ISSUE TITLE
Uranium 238 as Extreame reactor fuel

### ISSUE THREAD

**Issue by Leon1236** [NillerMedDild/Enigmatica2Expert#557]
With lots of machine processes going around the base, it is wired to see tinkers smeltery that is producing uranium ingots to be placed in ER . If it is possible to add option for Uranium 238 as one of reactor fuels that would be awesome. Same goes as all the ingotUranium Oredictionary items.

**Comment by NillerMedDild** [comment]
Thank you for the report, I will look into it :)

**Comment by NillerMedDild** [comment]
I'm afraid it's not possible to configure which fuels work.
