### ISSUE TITLE
Pams saplings cant be placed on biomes o plenty grass

### ISSUE THREAD

**Issue by Cealian** [NillerMedDild/Enigmatica2Expert#558]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**

I tried to place down the Jackfruit Sapling from pams down on biomes o plenty Silty Grass in the prarie biome and it didnt work, But was able to place it down on regular vanilla dirt/grass blocks

**Modpack version (Do not use "latest")**

1.49

**Logs**

If applicable, please upload your crash report, or latest.log to [hastebin](https://hastebin.com/).

**Screenshots**

**Additional context**

**Comment by NillerMedDild** [comment]
https://github.com/MatrexsVigil/harvestcraft/issues/272
