### ISSUE TITLE
Copper/Tin/Lead/Silver Nuggets not properly Unified

### ISSUE THREAD

**Issue by FryoKnight** [NillerMedDild/Enigmatica2Expert#559]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Question or Issue**
Silver bigots will not craft into Silver Ingots if crafted into a 3×3 Pattern unless they are from Thermal Foundation.
Ice & Fire, Thaumcraft 6, and Immersive Engineering's silver nuggets will not make ingots unless melted down, or converted.

**Modpack Version**
Version 1.49

**Additional Context**
Proof can be submitted later (currently away from home).

Edit: Spelling correction

**Comment by NillerMedDild** [comment]
How did you obtain the nuggets from the other mods?

**Comment by FryoKnight** [comment]
I got the Ice & Fire nuggets from the Piles of Silver that spawn in Ice Dragon nests (or the ones you craft)

**Comment by NillerMedDild** [comment]
Cool. Only Thermal nuggets are supposed to be obtainable, the recipes are removed to disable the cycling of ingredients in JEI.

**Comment by FryoKnight** [comment]
Yeah. Though the thing is that the nuggets are obtainable in other ways if not careful...

Also... Salt... It is sooooooo annoying to make. I am guessing you disabled the other salts/recipes? If so, could you at least add in a recipe to craft fresh water + pot to make salt (the default recipe for Pam's Harvest)

**Comment by NillerMedDild** [comment]
I'll look into it: https://github.com/NillerMedDild/Enigmatica2Expert/issues/565
The Water + Pot recipe should work though.

**Comment by FryoKnight** [comment]
Water Bucket + Pot does work.
Frsh Water (obtained from crafting a hater bucket) + Pot does not work.
Portable Tank (Water) + Pot also does not work.
