### ISSUE TITLE
issues with recipe completion in 1.22

### ISSUE THREAD

**Issue by croftyraider** [NillerMedDild/Enigmatica2Expert#56]
I've begun the early game, starting in on the industrial craft section so I can get some ore doubling going. After collecting some resin and smelting it to make rubber, I was unable to craft tin cables. Restarting the game solved the issue.

After that, I went on and made the generator, but ran into the same issue, this time with copper cables, when attempting to craft the circuit for the macerator.

This will get very tedious quickly if I have to restart after every quest is completed.

**Comment by croftyraider** [comment]
After restarting I was able to make the copper cables, but now the next recipe in the chain will not craft - I cannot craft the circuit. *sigh*

There are no messages in the logs except for the thaumcraft ones caused by pausing the game.

**Comment by NillerMedDild** [comment]
You will unfortunately need to reinstall the modpack. Just curious, are you using MultiMC?

**Comment by NillerMedDild** [comment]
#40

**Comment by croftyraider** [comment]
Yes I am using MultiMC - just read through the linked issue so I'll see about reinstalling and see what that does. Very strange behavior :(

The Twitch launcher is pretty nasty, but maybe the trick here is to install the pack with that, and also using MultiMC and then compare the two installs and see what's different... Maybe that will shed some light on the problem.

**Comment by NillerMedDild** [comment]
Ah yeah, that'd be a good idea. Are you testing it, or would you like me to do it?

**Comment by merendero** [comment]
I also had an issue with cable crafting. Using the Engineer's Wire Cutter with a copper plate uses the Cutter completely instead of its durability. Using a shear works fine.

**Comment by croftyraider** [comment]
I tested with the Twitch client an started a world in creative mode, crafted a tin cable with rubber without issue. After exiting I compared the two installs and saw nothing at all (important) different between them.

Thinking a bit more, I recalled that I have custom launch settings for minecraft from the voxcpw thread where he suggests some performance enhancements for minecraft. On a whim I tried disabling them. A secondary issue which I had been seeing is "chest lag" where I would shift click something into a chest and it would show up in a free slot instead of merging with an existing stack. I figured it was some mod related issue, but when running WITHOUT the performance options it stopped happening.

In your other thread you talk about client/server getting out of sync - that would explain the recipe issue as well as the chest issue (I'm guessing a bit, bit it makes sense to me). So maybe the GC options are harmful for this pack instead of good.

Anyway, going to keep using MultiMC but now without those options and see how it goes.

**Comment by NillerMedDild** [comment]
@merendero Do not piggyback other people's issue report, your issue is completely unrelated to this, and fixed in the next update.

**Comment by NillerMedDild** [comment]
I appreciate you testing it out Crofty! What were the additional java arguments?

**Comment by croftyraider** [comment]
I gave up - I switched to the twitch launcher after finding out how to make it use a more recent java so I'm going to play with that. No clue where the issue lies I'm afraid :(

**Comment by NillerMedDild** [comment]
Me neither, this is above my paygrade :P
