### ISSUE TITLE
Minecolonies?

### ISSUE THREAD

**Issue by Wntermute** [NillerMedDild/Enigmatica2Expert#563]
**Is your feature request related to a problem? Please describe.**
Not related to a problem.. Just a suggestion.

**Describe the solution you'd like**
Add Minecolonies to Enigmatica 2 (currently running Expert 1.49) in a balanced way.

**Additional context**
Maybe add it in somewhere Tier 1.5 or so.

**Comment by NillerMedDild** [comment]
I don't think Minecolonies fits into this pack anywhere, and it adds considerable additional load to the game. Thanks for the suggestion anyhow.
