### ISSUE TITLE
Garden Cloche/Advanced Thermionic Fabricator Recipe

### ISSUE THREAD

**Issue by timn123** [NillerMedDild/Enigmatica2Expert#564]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**

The Garden Cloche normally requires 2 treated planks, LV wire connector, ejector upgrade and a heavy engineering block. However, the recipe calls for 4 treated planks when crafting it through the Advanced Thermionic Fabricator. 

**Modpack version (Do not use "latest")**
1.48a

**Logs**

N/A

**Screenshots**

https://imgur.com/a/XDjAAPA

**Additional context**
I tested it with 2, but as the recipe shows it needs 4. 

This might've been fixed in 1.49, so don't yell at me :P

**Comment by NillerMedDild** [comment]
It's not a bug it's just an added cost :)

**Comment by NillerMedDild** [comment]
But thank you for the report!

**Comment by timn123** [comment]
Fair enough!
