### ISSUE TITLE
Remove XU2 Sound Muffler Quest

### ISSUE THREAD

**Issue by NillerMedDild** [NillerMedDild/Enigmatica2Expert#567]
**Notes**
Things to keep in mind when completing the task, possible solutions etc.

**Additional context**
Add any other context or screenshots about the task here.

**Comment by lexx1191** [comment]
already version 1.54, and this quest is still not fixed

**Comment by NillerMedDild** [comment]
Use the command `/bq_admin default load`

**Comment by lexx1191** [comment]
thank.
