### ISSUE TITLE
Temporarily Remove MagicalPsi due to a Crash

### ISSUE THREAD

**Issue by NillerMedDild** [NillerMedDild/Enigmatica2Expert#568]
**Notes**
Things to keep in mind when completing the task, possible solutions etc.

**Additional context**
Add any other context or screenshots about the task here.

**Comment by ArbitraryHubris** [comment]
1.50a on both client and server work correctly.  Magical Psi causes no client crashes.

**Comment by NillerMedDild** [comment]
This issue was just made so people wouldn't make duplicate ones while I made 1.50a hotfix, but thank you Arbitrary :)
