### ISSUE TITLE
No Grave upon Death in Deep Dark

### ISSUE THREAD

**Issue by NillerMedDild** [NillerMedDild/Enigmatica2Expert#569]
**Notes**
Things to keep in mind when completing the task, possible solutions etc.

**Additional context**
Add any other context or screenshots about the task here.

**Comment by xoxfaby** [comment]
http://shr.cx/M0pP.png

"A suitable location for the grave wasn't found."

exact text that shows. 

I think it might be try to give you your items back but they don't drop since you are already dead.

**Comment by xoxfaby** [comment]
Also if you run into this issue. /tmg_restore your_name latest will give you your items back.

**Comment by NillerMedDild** [comment]
https://github.com/M4thG33k/TombManyGraves2/issues/45
