### ISSUE TITLE
Update JEI to the Beta versions

### ISSUE THREAD

**Issue by Nagapito** [NillerMedDild/Enigmatica2Expert#570]
Would it be possible to get JEI updated to the latest beta versions?

The bookmark feature is kinda cool by itself but on an expert pack, when we are still manual crafting an item with 20 steps... Bookmarks becomes almost a requirement!

Thanks

**Comment by NillerMedDild** [comment]
That is unfortunately impossible at the moment, as the beta versions break Modular Machine JEI integration. I'm waiting for MM to update.
