### ISSUE TITLE
Server Crashes on load

### ISSUE THREAD

**Issue by enderger** [NillerMedDild/Enigmatica2Expert#571]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
The server crashes on loading.

**Modpack version (Do not use "latest")**
1.49

**Logs**

If applicable, please upload your crash report, or latest.log to [hastebin](https://hastebin.com/).
!! Full log exceeded hastebin max size !! 
https://gist.github.com/enderger/153667f1fece8dc43f3c6ea6060cc977 

**Screenshots**

**Additional context**

It started when checking a recipe that I cannot remember with JEI.

UPDATE: The mentioned fixes did not work

**Comment by NillerMedDild** [comment]
What happens if you restart it?

**Comment by enderger** [comment]
It crashes again. The log is from the re-load

**Comment by NillerMedDild** [comment]
Alright. Try deleting the journeymap folder, aswell as the planetDefs.xml found under world/advRocketry

**Comment by enderger** [comment]
I am starting the server up without the journeymap folder, I'll add my findings once the server is back online, or both have been deleted

**Comment by enderger** [comment]
I have found that the world folder does not contain the culprit

**Comment by enderger** [comment]
I restored a backup and the pack still crashed. It is something in the files outside of the world folder

**Comment by NillerMedDild** [comment]
That I can't help much with. Is the crash log the same?

**Comment by enderger** [comment]
Yes
And the files are the provided server files, with the culprit being within the folder.
I'll try applying the world to a fresh set of server files.

**Comment by enderger** [comment]
appending the world to a new server failed.

**Comment by NillerMedDild** [comment]
In the journeymap folder there should be a log, please post that.

**Comment by enderger** [comment]
I found a fix! Removing journeymap from the server fixes the issue.

**Comment by enderger** [comment]
https://hastebin.com/alixecococ.css

**Comment by NillerMedDild** [comment]
10 lines?

**Comment by enderger** [comment]
Can't sit for 10 minutes holding r-click again. That is the error portion of the crash

**Comment by NillerMedDild** [comment]
Ctrl + A highlights the entire file.

**Comment by NillerMedDild** [comment]
That snippet is absolutely useless.

**Comment by enderger** [comment]
https://gist.github.com/enderger/86f7b2ad6b12c7313c27fede744220a4

**Comment by NillerMedDild** [comment]
Do you happen to have any IC2 Miners?

**Comment by enderger** [comment]
No

**Comment by NillerMedDild** [comment]
Shit, I'm out of ideas then. Unfortunately that crash-report doesn't say anything useful.

Either load a backup, or try updating to 1.50. Sorry.

**Comment by enderger** [comment]
This is running a backup

**Comment by NillerMedDild** [comment]
Oh right. A backup didn't work, and a fresh install of the server files with said backup didn't work. Are you able to run a completely fresh server, without a world?

**Comment by enderger** [comment]
That would be correct

**Comment by whitenet** [comment]
i have this same problem couple days ago but for me i just change max-tick-time=0 and increase ram to MAX_RAM=6G and server stop crash
