### ISSUE TITLE
Crash after last update 07.01.2019

### ISSUE THREAD

**Issue by Tapes** [NillerMedDild/Enigmatica2Expert#573]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**

After the last update 07.01.2019 the game just crash

**Modpack version (Do not use "latest")**

v1.50

**Logs**

https://pastebin.com/bmzASAaD

**Screenshots**

**Additional context**

Help =)

**Comment by NillerMedDild** [comment]
Remove Magical Psi from both server and client :)
