### ISSUE TITLE
world crashing shortly after creation

### ISSUE THREAD

**Issue by Jibbur** [NillerMedDild/Enigmatica2Expert#575]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
Created a new world to play this pack and found a village immediately, while still looting this village game crashed out. Upon reloading world game crashed within a few seconds. I believe this was around sunset and it appears that the crash was related to rendering a zombie.

**Modpack version (Do not use "latest")**

1.50

**Logs**

If applicable, please upload your crash report, or latest.log to [hastebin](https://hastebin.com/).

https://hastebin.com/xipakideki.rb

**Screenshots**

**Additional context**
As this was right at the start of the game, within the first 10 minutes after several times reloading the same world and even attempting to use the repair profile feature on Twitch Launcher I decided to start over with the same seed and recreated the world. Same bug after about 5-10 minutes I think, probably around sunset. Log is from this recreation.

**Comment by eneqcho** [comment]
Remove MagicalPsi, for some reason rendering the focusing chestplate crashes the game.

**Comment by Jibbur** [comment]
that fixed it, guess I will just have to wait for an update to use psi...

**Comment by Ravalli03** [comment]
Yea, I'm getting the same crash but 1.50 changelog says MagicalPsi was removed, but is still installed in the pack.

**Comment by NillerMedDild** [comment]
Due to how Twitch handles self-installed mods, MagicalPsi only gets removed for some. I will hotfix asap.
