### ISSUE TITLE
Server Crash : Ticking Entity

### ISSUE THREAD

**Issue by LuQ3** [NillerMedDild/Enigmatica2Expert#578]
**Issue Description**
One of the players was in the Nether. He had to log out of the server but when he tried to log in again a few minutes later, the server crashed. It happened the second time to the same player and only him.

**Modpack version (Do not use "latest")**

1.49

**Logs**

1. https://hastebin.com/dekonuqobi.rb
2. https://hastebin.com/usukadujaq.rb
3. https://hastebin.com/etehujacef.rb

**Screenshots**

NONE

**Additional context**

Additional mods:
-LagGoggles 1.12.2-4.1
-NetherPortalFix 1.12.1-5.3.17
-Login Shield 1.12.2-3-g7c6e7ac

/----------------------------------------------------------------------------------------------------------------

1)
I deleted only this player's files (/world/playerdata/) from the server and then uploaded other from the previous backup. It worked for ~24h

2)
This is only happening for one player. The remaining players log in to the server normaly .
After entering the nether by another person who uses the same portal everything works

3)
"/cofh killall" did't help

**Comment by NillerMedDild** [comment]
Hm, strange issue. There's a config in the Forge config to remove retiring entities, set that to true, and please let me know if the issue gets fixed :)
