### ISSUE TITLE
Add Crafting Tweaks

### ISSUE THREAD

**Issue by Dasl0ki** [NillerMedDild/Enigmatica2Expert#582]
Hi,

i think adding Crafting Tweaks to the modpack would be a nice addition. I'm so used to it beeing in nearly every modpack and was wondering why it's not in here.

I added it myself manually, but I think it would be a nice additon for everyone. Going trough past issues I see a lot of people who added it themselves, so i tought might as well could be in there out of the box.

BR
Loki

**Comment by NillerMedDild** [comment]
I think it would remain unused by the majority of players, and only serve as additional GUI clutter, so I'm afraid it's going to be a no. Thanks for the suggestion anyway :)
