### ISSUE TITLE
Update better questing mod

### ISSUE THREAD

**Issue by bluelightning32** [NillerMedDild/Enigmatica2Expert#583]
## Thank you for helping us improve. #####

**Question or Issue**

I'm trying to patch the invsync plugin to synchronize the per player better questing progress between nodes in my multiverse.

Until very recently the better questing storage model stuck the progress for every player under each quest node, instead of breaking it down by player then quest. There wasn't a good way to query progress by player either in the API, which I need to do in the invsync plugin.

Recently this was fixed in the mod, along with improving the network efficiency (it was sending everyone's progress to all players).

Are you going to upgrade to version BetterQuesting-3.5.282.jar or higher soon? Or should I use some gross hacks to get the per player progress with the current version?

**Modpack Version**

Enigmatica 2: Expert 1.50a

**Additional Context**

**Comment by NillerMedDild** [comment]
I hope to update to 282 within a week, it depends on the status of the experimental branch and the stability of 282.

**Comment by NillerMedDild** [comment]
That's very nice of you :) You can donate through this [link](https://www.paypal.com/cgi-bin/webscr?return=https://minecraft.curseforge.com/projects/enigmatica2expert?gameCategorySlug=modpacks&projectID=282744&cn=Add+special+instructions+to+the+addon+author()&business=niels.pilgaard%40hotmail.com&bn=PP-DonationsBF:btn_donateCC_LG.gif:NonHosted&cancel_return=https://minecraft.curseforge.com/projects/enigmatica2expert?gameCategorySlug=modpacks&projectID=282744&lc=US&item_name=Enigmatica+2%3a+Expert+(from+curseforge.com)&cmd=_donations&rm=1&no_shipping=1&currency_code=USD) :)

**Comment by Zekrom64** [comment]
As part of a server hosting team I would also recommend updating BetterQuesting to 282 or above. We've had several occasions where it will randomly fail to write the database of quest progress completely and wipe all the progress, forcing us to reload the database from a backup. 282+ seems to have a fix for this.

**Comment by NillerMedDild** [comment]
I will update to 284 soon.
