### ISSUE TITLE
Engineer's toolbox

### ISSUE THREAD

**Issue by Juanmam** [NillerMedDild/Enigmatica2Expert#585]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
I crafted an immersive engineering engineer's toolbox to store my tools, but when I tried to open it, the game crashes.

**Modpack version (Do not use "latest")**
Last time I checked it was at version 1.50 (Alfa), haven't checked the 1.50a

**Comment by GoldenKeyboard** [comment]
Can you give me the crashlog.

**Comment by Juanmam** [comment]
Checked on the newest version (1.50a) and couldn't seem to replicate the problem. I have no clue what might have change. I found two crashlogs, not sure if they are related to that problem. I will attach them anyways if that helps.

[crash-2019-01-02_19.27.05-server.txt](https://github.com/NillerMedDild/Enigmatica2Expert/files/2742619/crash-2019-01-02_19.27.05-server.txt)

[crash-2019-01-02_19.11.26-server.txt](https://github.com/NillerMedDild/Enigmatica2Expert/files/2742607/crash-2019-01-02_19.11.26-server.txt)

**Comment by NillerMedDild** [comment]
Glad it's fixed :)
