### ISSUE TITLE
Wireless RF heating coils do not get used crafting redstone-iron wiring

### ISSUE THREAD

**Issue by Nagapito** [NillerMedDild/Enigmatica2Expert#586]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**

When redstone-iron wirings are crafted, the wireless RF heating coils do not get consumed
If this is the inteded behaviour, maybe then add a tooltip to the item warning about this, so others dont do like me, craft a stack of heating coils to realise 4 were enough forever!

**Modpack version (Do not use "latest")**

1.49

**Logs**

If applicable, please upload your crash report, or latest.log to [hastebin](https://hastebin.com/).

**Screenshots**

**Additional context**

**Comment by FunkyMoneyMan** [comment]
That is intended that the rf heating coils don't get consumed. Sorry for the inconvenience....

**Comment by NillerMedDild** [comment]
Sure thing.
