### ISSUE TITLE
Random Server Crash when players explore

### ISSUE THREAD

**Issue by FryoKnight** [NillerMedDild/Enigmatica2Expert#587]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
When players start explore, the server randomly crashes.

**Modpack version (Do not use "latest")**
1.46, 1.47a, 1.49

**Logs**
[Crash Log](https://pastebin.com/Xjq90Gkm) on Pastebin.

**Screenshots**
N/A

**Additional context**
This normally occurs when people start exploring new Chunks, and when there is 2 or more players.

**Comment by Nazta** [comment]
It seems recurrent complex is trying to generate structures, but with several people exploring at once, and no pregenerated terrain.  It's taking too long so the server stops automatically after hanging for 60sec.

**Comment by NillerMedDild** [comment]
Yep, what Nazta said. Set player-tick-time to 0 in serverproperties :)

**Comment by FryoKnight** [comment]
> Yep, what Nazta said. Set player-tick-time to 0 in serverproperties :)

What is "player-tick-time" though?

**Comment by NillerMedDild** [comment]
`max-tick-time`

**Comment by NillerMedDild** [comment]
Yep :) my bad.
