### ISSUE TITLE
Forestry Circuit Boards break AE2 autocrafting

### ISSUE THREAD

**Issue by Targren** [NillerMedDild/Enigmatica2Expert#589]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**

Using Forestry circuit boards (true for all of Basic, Enhanced, Refined, and Intricate) as either a crafting ingredient in, or the result of, AE2 pattern processing crafting fails because the system doesn't recognize the circuit board.  It also allows you to request crafting the same item when it's already in storage (see screenshot below), which isn't normal behavior. 

* If the board is the result of the crafting, then the crafting doesn't acknowledge it appearing in the system, and waits forever (or until manually cancelled), despite the board appearing in the terminal.

* If the board is an ingredient, the autocrafter reports it as "missing" (or insists on crafting it unsuccessfully, if the above is also true). 

All of them use the "forestry:chipsets:X" identifer, and don't have any NBT when they're fresh off the assembly line (checked with "/ct hand")

**Modpack version (Do not use "latest")**

1.49

**Logs**

N/A

**Screenshots**

https://imgur.com/a/ecDCcH0

**Additional context**

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
I may have fixed this in the upcoming update, could you let me know?

**Comment by Targren** [comment]
Will do. Do you mean 1.50a, or the one coming after that?

**Comment by NillerMedDild** [comment]
1.51 :) It'll be up soon.

**Comment by Targren** [comment]
You got it.

**Comment by Targren** [comment]
Sadly, it does not seem to be the case. If you'll note in the screenshots, it still wants to craft another basic and reinforced (or w/e the orange ones are called) circuit board, despite having two of each already stocked.  

https://imgur.com/a/rFwthH7

**Comment by NillerMedDild** [comment]
Hmm. The old ones may be bugged out, could you redo one of the recipes and check? :x

**Comment by Targren** [comment]
Well, since it's you and you asked so nicely. ;) 

No dice, unfortunately. 

https://imgur.com/a/s3qW89k

**Comment by Targren** [comment]
Actually, I lied! 

Well, not really. I just didn't redo the crafting recipe. That seems to work now. Thanks!

**Comment by NillerMedDild** [comment]
Awesome!
