### ISSUE TITLE
Breaking an IronChest Shulker box with Global Traveler set to that box makes it swallow itself

### ISSUE THREAD

**Issue by xoxfaby** [NillerMedDild/Enigmatica2Expert#590]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**

Breaking an IronChest Shulker box with Global Traveler set to that box makes it disappear, presumably it's put in its own inventor.

**Modpack version (Do not use "latest")**

1.49

**Logs**

If applicable, please upload your crash report, or latest.log to [gist](https://gist.github.com/).

**Screenshots**

**Additional context**

**Comment by NillerMedDild** [comment]
That's not a bug, that's simply how Global Traveller works.

**Comment by xoxfaby** [comment]
If this was intended behavior it would happen with vanilla shulker boxes too. You are right that it's kinda how it's supposed to work, but the vanilla version dropping leads me to believe that the PlusTiC devs didn't want them to be able to swallow themselves and that is how they are supposed to work, meaning this is not how it should work and, if not a bug, is at least an unintended interaction between the 2 mods.

**Comment by xoxfaby** [comment]
That aside I don't don't think it's a good idea for items to be able to semi-delete themself staying in a permanent limbo where they can't be access but still take up disk and memory space.
