### ISSUE TITLE
Void Ore Miner Controller Tier 4 is unbreakable

### ISSUE THREAD

**Issue by Stians92** [NillerMedDild/Enigmatica2Expert#592]
**Issue Description**
Void Ore Miner Controller Tier 4 cannot be broken by a pickaxe with the correct mining level.

**Modpack version (Do not use "latest")**
1.50a

**Logs**

**Screenshots**
https://gyazo.com/dbb468f40314f5518559b456a3c5bb0e

**Additional context**
Crouch-right-clicking with the Assembler doesn't work either. Both Assembler and pickaxe worked fine on Tier 3. Forcibly breaking it with the Assembler takes as long as breaking it by hand, but it respawns just like when using a pickaxe. Breaking it with an empty hand made the Void Ore Miner Controller disappear completely, so I cheated in a new one.

**Comment by drakkensong21** [comment]
Are you on a server and did you craft the controller

**Comment by Stians92** [comment]
I am playing on singleplayer. I crafted the controller as an upgrade from my tier 3 one, did not use cheat mode until it actually disappeared.

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by Nazta** [comment]
Looks like the "you can't break it, since you don't own it" bug. Can be solved by clicking on it with an empty hand, or with the assembler rod, and it becomes breakable.

**Comment by Chiiruno** [comment]
Right click on it and then break it.
It's some permission thing.
