### ISSUE TITLE
Recipes of some Mystical Agriculture seeds aren't unified

### ISSUE THREAD

**Issue by OneEyeMaker** [NillerMedDild/Enigmatica2Expert#594]
**Issue Description**

Recipes of some Mystical Agriculture seeds (with tier >= 2) are not edited with CraftTweaker:
- End Seeds,
- Experience Seeds,
- Sulfur Seeds,
- Saltpeter Seeds,
- Quicksilver Seeds,
- Seeds, that produce mob drops.

and some other.
Recipes of these seeds should be moved to Astral Sorcery altars (like most recipes in Mystical Agriculture).

**Modpack version**

1.46 - 1.50a

**Screenshots**

![2019-01-11_08 08 54](https://user-images.githubusercontent.com/14104815/51021910-477d8280-159c-11e9-9554-c85e41bc4cff.png)

**Comment by NillerMedDild** [comment]
The reason they don't have new recipes is because I see them as too weak to require extra steps :)

**Comment by OneEyeMaker** [comment]
I think, at least End Seeds should be unified. End essence - main source of End Stone = good source of BoP gems and uranium (using Ex Nihilo).
For comparison, Nether seeds (which can be used the same way - produce ores through Ex Nihilo) are unified.
