### ISSUE TITLE
NuclearCraft RF storage inconsistent values

### ISSUE THREAD

**Issue by jbabcock** [NillerMedDild/Enigmatica2Expert#597]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
First two levels of NuclearCraft voltaic pile don't follow logical pattern for higher tiers.
Basic Voltaic Pile: 20,000,000 RF
Adv. Voltaic Pile: 500,000,000 RF (requires 3 basic to craft)
DU Voltaic Pile: 25,600,000 RF (requires 3 advanced to craft)
Elite Voltaic Pile: 102,400,000 RF (requires 3 DU to craft)

**Modpack version (Do not use "latest")**
1.50a

**Logs**

If applicable, please upload your crash report, or latest.log to [gist](https://gist.github.com/).

**Screenshots**

**Additional context**

**Comment by NillerMedDild** [comment]
Thank you for the report, fixed for next update :)
