### ISSUE TITLE
Uranium plate with hammer recipe is 1:1

### ISSUE THREAD

**Issue by MorganSimic** [NillerMedDild/Enigmatica2Expert#598]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
Title pretty much. You get one uranium plate with the hammer from one ingot, opposed to all other hammer plate recipes wich require two ingots for one plate. Not sure if intended or bug.

**Modpack version (Do not use "latest")**
1.50a

**Logs**

If applicable, please upload your crash report, or latest.log to [gist](https://gist.github.com/).

**Screenshots**

**Additional context**

**Comment by NillerMedDild** [comment]
Woops :P thanks!
