### ISSUE TITLE
Xnet gate quest not detecting xnet cable

### ISSUE THREAD

**Issue by Electrofried** [NillerMedDild/Enigmatica2Expert#6]
#### Issue Description
X net cable is net detected by xnet quest as it is looking for "blue network cable" and these are uncraftable. (they default as Xnet cable with no colour listed for blue)

#### What you expected to happen

Crafting the cable completes the quest

#### Modpack version (Do not use "latest")
1.03a
#### Your most recent log file where the issue was present
unrequired.
[pastebin/gist/etc link here]

**Comment by NillerMedDild** [comment]
Will fix asap, thank you.

**Comment by NillerMedDild** [comment]
Done!
