### ISSUE TITLE
Steel alloying in smeltery 

### ISSUE THREAD

**Issue by MorganSimic** [NillerMedDild/Enigmatica2Expert#602]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Question or Issue**
Steel can be alloyed in the smeltery with iron and coal. I think this is not intended and added by one of the recent TiCon updates probably.

**Modpack Version**
1.50a

**Additional Context**
Not fixed with 1.51 I think.

**Comment by JGuerndt** [comment]
That has been present as far back as version 1.46. Shows in JEI as a valid recipe. I only used a few times due to other methods being way faster.

**Comment by NillerMedDild** [comment]
Yep it's unintended, thanks :)
