### ISSUE TITLE
UU Matter cost for PCB vs Computer vs Turtle

### ISSUE THREAD

**Issue by JGuerndt** [NillerMedDild/Enigmatica2Expert#603]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
In the process of making my first Cyclic Automated User (in order to make the EU2 Mechanical User), I placed all available parts in the UU Scanner to see cost.

PCB component: 339.6 mB
Computer: 1.967 mB
Turtle: 8.217 B

As shown, there is a vast difference between the UU Matter cost of these items, namely the Computer being so low.

**Modpack version (Do not use "latest")**
1.46

**Logs**

If applicable, please upload your crash report, or latest.log to [gist](https://gist.github.com/).

**Screenshots**

![screen shot 2019-01-12 at 6 21 29 pm](https://user-images.githubusercontent.com/41530146/51080030-ab39a580-1699-11e9-9cee-420631038869.png)
![screen shot 2019-01-12 at 6 21 43 pm](https://user-images.githubusercontent.com/41530146/51080031-ad036900-1699-11e9-880b-213699853847.png)
![screen shot 2019-01-12 at 6 28 13 pm](https://user-images.githubusercontent.com/41530146/51080033-aecd2c80-1699-11e9-8f6c-09f37d66e39d.png)

**Additional context**

I believe the Computer should cost more UU Matter. There are only 7 iron ingots and a chest difference between the Computer and the Turtle, but that equates to over an eight bucket cost difference. :)

**Comment by NillerMedDild** [comment]
Those recipes were generated by ic2, I'm only responsible for a handful of them. I will not change the generated values, as there are thousands. Thanks for the report though!

**Comment by JGuerndt** [comment]
lol, very well understood. Those computers are just stupidly cheap, but that's fine for me :)

**Comment by NillerMedDild** [comment]
Most things are stupidly expensive, so I think it's nice some of the values are actually great, makes it worth scanning stuff :D
