### ISSUE TITLE
Modular Machine using crazy amount of energy

### ISSUE THREAD

**Issue by Ravalli03** [NillerMedDild/Enigmatica2Expert#604]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**

I setup a Advanced Metallurgic Fabricator to make  1 set of titanium ingots, it started to craft and used over 500mil RF before I stopped it from using anymore energy and no ingots were crafted. I'm not sure what's going on as the tool tip says it only requires 1mil RF to craft.

**Modpack version (Do not use "latest")**

1.51

**Logs**

If applicable, please upload your crash report, or latest.log to [gist](https://gist.github.com/).

**Screenshots**

**Additional context**

**Comment by OneEyeMaker** [comment]
Just use **_larger_** energy input hatch. You need to supply machines from Modular Machinery with energy at high rate.

**Comment by Ravalli03** [comment]
Is it a bug? I was supplying it with 25k rf per tick.

**Comment by NillerMedDild** [comment]
No, it needs 100.000 rf/t minimum.

**Comment by Ravalli03** [comment]
oh ok., got it.

**Comment by NillerMedDild** [comment]
There is now only 1 energy input, and that always works with all recipes.
