### ISSUE TITLE
/dank/null Deleting all block held with in but saying it has them.

### ISSUE THREAD

**Issue by HeavyDeception** [NillerMedDild/Enigmatica2Expert#605]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
The /dank/null is deleting the items form its inventory but its keeping that spot open and will let you place the block but you cant remove that item.

**Modpack version (Do not use "latest")**
1.51

**Logs**
There is no log dose not crash the game.
If applicable, please upload your crash report, or latest.log to [gist](https://gist.github.com/).

**Screenshots**
![error danknull](https://user-images.githubusercontent.com/20760785/51082261-21093580-16c9-11e9-89af-4cd8f36c3ae2.png)

**Additional context**
https://github.com/p455w0rd/DankNull/issues/151

**Comment by NillerMedDild** [comment]
Oh boy ><

**Comment by HeavyDeception** [comment]
@NillerMedDild I sent one to p455w0rd too just wanted to give you a heads up also.

**Comment by HeavyDeception** [comment]
@NillerMedDild There saying to do a roll back of the mod on there side.

**Comment by NillerMedDild** [comment]
Sigh, alright.

**Comment by ArbitraryHubris** [comment]
https://github.com/p455w0rd/DankNull/issues/151

**Comment by ArbitraryHubris** [comment]
@HeavyDeception well done, reporting here and to the mod author.  You saved me the trouble.

**Comment by NillerMedDild** [comment]
Agreed, thanks :D

**Comment by HeavyDeception** [comment]
@ArbitraryHubris I try guys.

**Comment by joakime** [comment]
Adding link to issue at p455w0rd/DankNull#151 (so others that find this issue can track the status of it at the mod author's repo)

**Comment by HeavyDeception** [comment]
@joakime I did that in the post.
