### ISSUE TITLE
New Scrap->Scrap Box Compacting Drawer Recipe (1.50 changelog) Not working

### ISSUE THREAD

**Issue by Targren** [NillerMedDild/Enigmatica2Expert#606]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**

1.50 Changelog mentions a scrap->scrap box recipe for compacting drawers. In 1.51, adding scrap to a compacting drawer just stores the scrap and locks out both "auxilliary" drawers. 

**Modpack version (Do not use "latest")**

1.51

**Logs**

N/A

**Screenshots**

https://imgur.com/a/RsY5kZ8

**Additional context**

**Comment by NillerMedDild** [comment]
Woops, I'll try again, thanks.

**Comment by NillerMedDild** [comment]
I didn't actually implement it on Expert, woops ^^'
