### ISSUE TITLE
Adv. Rocketry Satellites have full databanks upon reaching orbit. 

### ISSUE THREAD

**Issue by Targren** [NillerMedDild/Enigmatica2Expert#607]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**

When a Composition, Mass, or Optical satellite first reaches orbit, the satellite terminal reports 3.0k data immediately.  It's not just a visual bug, as the data can be downloaded and saved to data sticks. (See Screenshot album)

**Modpack version (Do not use "latest")**

1.51

**Logs**

N/A

**Screenshots**

https://imgur.com/a/C8D7Gih

**Additional context**

I'm not sure if this is intended behavior (though it was a nice surprise, considering how expensive the throw-away rockets are), as my knowledge of the mod is limited to what's in the quest book and a tutorial series from a very old, 1.10.2 version of the mod.

**Comment by NillerMedDild** [comment]
Satellite behaviour has always been wonky, I think we should consider this a feature :P
