### ISSUE TITLE
Quark inventory buttons placed wrong

### ISSUE THREAD

**Issue by Dasl0ki** [NillerMedDild/Enigmatica2Expert#611]
**Issue Description**
The "Merge", "Restock", "Deposit" buttons from Quark are placed wrong and partly over inventory slots

**Modpack version (Do not use "latest")**
1.51

**Logs**
None

**Screenshots**
![quark_bug](https://user-images.githubusercontent.com/14993611/51084340-0a45fb80-1728-11e9-9f2a-1102d4e7871e.png)

**Additional context**
Applies to vanilla chests, iron chest, tinkers chest.
Buttons are not visible on crates (AA and Immersive Engineering) (i think intended by the mod)

**Comment by NillerMedDild** [comment]
Woops, sorry about that.
