### ISSUE TITLE
Modular Machinery - JEI Structure Preview

### ISSUE THREAD

**Issue by Dasl0ki** [NillerMedDild/Enigmatica2Expert#613]
**Issue Description**
Modular Machinery preview in JEI does not display correctly. It seems ther correct structure is loaded in the background and is "dragable", but a black bar is covering 75% of the preview. However ingame preview works fine and can be used as workaround.

**Modpack version (Do not use "latest")**
1.51

**Logs**
None

**Screenshots**
![mm_jei](https://user-images.githubusercontent.com/14993611/51085178-cd810100-1735-11e9-8c6a-153f854378b5.PNG)

**Additional context**
Previous versions of the modpack did not had this preview as far as i can remember. Can't point out if this is JEI related or MM related.

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by MorganSimic** [comment]
From what I know it is an unfortunate interaction between how JEI sizes their screen and MM. I remember Hellfire saying that at the moment that can't really be fixed. But I might be wrong about that.

**Comment by JGuerndt** [comment]
It is annoying to switch to the large GUI to see the JEI preview, but there is the button on that tab to translate that to an in-world projection. That is a great if you wish to not change your GUI scale to see the JEI version of the preview.

**Comment by NillerMedDild** [comment]
Nothing we can do about it for now.
