### ISSUE TITLE
Make ExtraCells unstable/deprecated items uncraftable

### ISSUE THREAD

**Issue by psrcek** [NillerMedDild/Enigmatica2Expert#616]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
I put a wireless crafting terminal into my bauble slot and it crashed all the players that were nearby, now I can't join the server without crashing. It appears to be some rendering bug.

**Modpack version (Do not use "latest")**
1.51

**Logs**
[crash log](https://gist.github.com/psrcek/26ee7e152ca6db15e32f8815c873fc75)

**Screenshots**
n/a

**Additional context**
I added logistics pipes to the pack, but I don't think it has anything to do with this.
I suspect this to be a WCT bug, so: @p455w0rd

**Comment by NillerMedDild** [comment]
Will wait for his reply :)

**Comment by psrcek** [comment]
Correcttion: I did some testing, this only happens with a wireless universal terminal with a fluid terminal installed. and if I do have that, I can't even open the crafting terminal in it.

**Comment by p455w0rd** [comment]
This is an issue on the EC2 side of things. @BrockWS has fixed this in the version he posted on my discord server in the #extracells-2 channel. We don't have access to push updates to the EC2 Curse page unfortunately..we have plans, but for now, it's seriously best to just not use EC2

**Comment by NillerMedDild** [comment]
Damnit, that would mess up progression.
