### ISSUE TITLE
Forestry Crash with Chunk Analyzer

### ISSUE THREAD

**Issue by CalvinJJ** [NillerMedDild/Enigmatica2Expert#617]
**Issue Description**

When using the Random Things Chunk Analyzer in a chunk with Forestry leaf blocks, the game hard crashes when trying to scroll to that item in the analyzer results.

**Modpack version (Do not use "latest")**

1.51

**Logs**

[crash-report](https://gist.github.com/CalvinJJ/79d75a74aec8fafd243026c2d32c8b8a/)

**Additional context**

I've noticed that if I silk touch forestry leaves, in the inventory they're given the name "trees.grammar.type.leaves.type" and are unplaceable. [Possibly related to this issue in the Forestry GH.](https://github.com/ForestryMC/ForestryMC/issues/2336)

Setting "attemptRecoveryOnItemRenderException"=true in codechickenlib.cfg seems to stop the crash.

**Comment by NillerMedDild** [comment]
The issue you linked to does indeed look related, thanks for doing the research :)

`attemptRecoveryOnItemRenderException` sounds like an excellent config to enable either way.

**Comment by roboderpy** [comment]
because chunks analyzer don't collect NBT data from blocks (only /metanumber) and therefore forestry crash
