### ISSUE TITLE
Freezing

### ISSUE THREAD

**Issue by Luker3** [NillerMedDild/Enigmatica2Expert#618]
**Issue Description**

I just updated my modpack to version 1.5.1 and now when I use the Extra Utilities Crusher, my game freezes and I'm forced to close the program in order to keep playing. The background of the Crusher's GUI is frozen as well

**Modpack version (Do not use "latest")**

**Logs**

(Not registered as crash)

**Additional context**

This problem has only occured on a server; not in singleplayer.

**Comment by NillerMedDild** [comment]
Alright, known issue :)
