### ISSUE TITLE
Forestry Backpack Ice & Fire Compatibility (Fryoknight)

### ISSUE THREAD

**Issue by FryoKnight** [NillerMedDild/Enigmatica2Expert#620]
**Is your feature request related to a problem? Please describe.**
There is alot of items that are added by **_Ice and Fire_**, and I think it would be a good idea to add them to the Forestry Backpacks.

**Describe the solution you'd like**
Simply editing the config\forestry\backpacks.cfg
[I even went and did it for ya'h~
](https://pastebin.com/gG19P7sv) (Posted it there as it is very long)

**Additional context**

**Comment by NillerMedDild** [comment]
Nice work!
