### ISSUE TITLE
Death causes you to lose your extra invetory from Cyclic Extra Inv

### ISSUE THREAD

**Issue by ChrisLewisAG** [NillerMedDild/Enigmatica2Expert#621]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
On death the Extra Inventory you get from the Cyclic Mod dissappears forcing you to have to re-eat the cake.

**Modpack version (Do not use "latest")**
1.51

**Logs**
(Coudnt see anything in logs but can supply if needed)
If applicable, please upload your crash report, or latest.log to [gist](https://gist.github.com/).

**Screenshots**
(Can supply if needed)

**Additional context**

Couldnt see anything in the logs, but seems to be new since upgrading to 1.51, but havent experianced this pre the upgrade, if you need any further information please let me know happy to assit where i can

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
Do you happen to have a latest log from when it occured?

**Comment by Lothrazar** [comment]
Copying this here for visibility: 


a workaround that might help some of your players:

The items are not deleted they are still safe. What was deleted was the player capability, meaning the button in your inventory that opens the extension.

So if this bug happens to anyone, if they can simply eat a new Inventory Upgrade item to re-gain access to this screen and recover the items. At least this worked in my testing.

**Comment by ChrisLewisAG** [comment]
Ill grab you a log, which one do you need debug.log? happens 100% of the time so happy to get you a log :)

**Comment by NillerMedDild** [comment]
No thanks, I reproduced it and sent my log :)

**Comment by OmaiGrundles** [comment]
I would like to add that this also removed the permanent hearts from the cyclic heart containers the first time this happened. And for some reason the heart containers are not craftable(or show in JEI) anymore.. :(

**Comment by NillerMedDild** [comment]
I disabled them good sir, because they tend to get removed or prevent other health increases from working.

**Comment by OmaiGrundles** [comment]
Oh dang, thanks for that then, I would have been devastated if my health bonuses weren't applying correctly!

**Comment by Wntermute** [comment]
This also happens when using the home portal in The End after killing the dragon. I worked around that by using a DE Dislocator and/or Mekanism Teleporter. In either case, I added a recipe for it to my autocrafter.
