### ISSUE TITLE
Mineralis Ritual Improvements & Bug Fixes

### ISSUE THREAD

**Issue by NikkoScript** [NillerMedDild/Enigmatica2Expert#622]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
Mineralis Ritual from Astral Sorcery generate Ore from Vulpes Library ( Copper, Lead, nickel, tin, aluminium ), Ice and fire ( ruby, saphire and silver ) .

Moreover, it doesn't generate nuclearcraft ore ( lithium, magnesium, boron and thorium  except uranium) and generate mana infused ore. I don't know if this is intended. 

**Modpack version (Do not use "latest")**
1.49

**Logs**

If applicable, please upload your crash report, or latest.log to [gist](https://gist.github.com/).

**Screenshots**

**Additional context**
The config file in the config folder :  //config/astralsorcery/mineralis_ritual.cfg is the default file maybe this come from here ( the other file in this folder are unchanged too )

**Comment by NillerMedDild** [comment]
Would you be able to get me the code names of the ores it generates from Lib Vulpes and Ice & Fire? :) I need to remove their oredict tags to fix this. 

Duely noted about NC ores, will add them.

The Mana Infused is on purpose :)

**Comment by NikkoScript** [comment]
alumium libvulpes:ore0@9
tin : libvulpes:ore0@5
copper : libvulpes:ore0@4

nickel : immersiveengineering:ore@4

saphire : iceandfire:spahire_ore@0
silver : iceandfire:silver_ore@0

lead : nuclearcraft:ore@2
uranium : nuclearcraft:ore@4


I made some mistake , some ore are from immersive too but differ from the world gen.

**Comment by NillerMedDild** [comment]
Nice, I want to remove that aswell :)

**Comment by NikkoScript** [comment]
With the bugfix, other ore are generated : 

uranium ore : ic2:ressource:4
copper ore : nuclearcraft:ore:0
copper ore : nuclearcraft:ore:1
lead ore : ic2:ressource:2
alumium  :immersiveengineering:ore:1

It seem mineralis take the first available entry in Oredict.

I will try to list all unecessary entry and update this comment.

**Comment by NillerMedDild** [comment]
Perfect, thanks. I'll keep removing the oredict from the incorrect ores you get :D

**Comment by NikkoScript** [comment]
Here the line I add in the script  Oredict.zs

```
	<ore:oreTin>.remove(<forestry:resources:2>);
	<ore:oreTin>.remove(<ic2:resource:3>);
	<ore:oreTin>.remove(<nuclearcraft:ore:1>);
	<ore:oreTin>.remove(<mekanism:oreblock:2>);
	
	<ore:oreAluminum>.remove(<immersiveengineering:ore:1>);
	
	<ore:oreCopper>.remove(<immersiveengineering:ore:0>);
	<ore:oreCopper>.remove(<ic2:resource:1>);
	<ore:oreCopper>.remove(<forestry:resources:1>);
	<ore:oreCopper>.remove(<nuclearcraft:ore:0>);
	<ore:oreCopper>.remove(<mekanism:oreblock:1>);
	
	
	<ore:oreLead>.remove(<ic2:resource:2>);
	<ore:oreLead>.remove(<immersiveengineering:ore:2>);
	
	<ore:oreUranium>.remove(<ic2:resource:4>);
```

My magical quarry is happy now , Thanks

**Comment by NillerMedDild** [comment]
Excellent work, thank you!

**Comment by Lordkeren** [comment]
immersive engineering silver is also generated, added this line

<ore:oreSilver>.remove(<immersiveengineering:ore:3>);

modpack Version 1.56
