### ISSUE TITLE
Quantum Entangloporter craft requires soldered forestry circuit boards

### ISSUE THREAD

**Issue by DrTasslehoff** [NillerMedDild/Enigmatica2Expert#623]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**

All of the forestry circuits when crafted always have {T:#s} metadata aside from the Intricate circuit craft which should have {T:3s}. Soldering the circuitboard adds this along with a bunch of other data but enables it to craft the Mekanism quantum entangloporter. Without the data it does not work

**Modpack version (Do not use "latest")**

1.51

**Logs**

If applicable, please upload your crash report, or latest.log to [gist](https://gist.github.com/).

**Screenshots**

**Additional context**

**Comment by NillerMedDild** [comment]
Well that's an annoying change :P Thanks for letting me know!

**Comment by NillerMedDild** [comment]
I would much rather the Quantum Entangloporter ignored the NBT than enforce the NBT on crafting.

**Comment by xmiso** [comment]
That's weird. I just crafted one with circuits I had made minutes before.

**Comment by Ravalli03** [comment]
The Quantum Entangloporter also has an issue with the (middle) teleporter block, even tho I have them in the system it doesn't recognize it.

**Comment by NillerMedDild** [comment]
Did you place said teleporter block?
