### ISSUE TITLE
IE Wire throughput is to low

### ISSUE THREAD

**Issue by MorganSimic** [NillerMedDild/Enigmatica2Expert#624]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Question or Issue**
The RF/t limit for all the IE wires is wrong. Cables should be able to handle 8x the RF/t of an associated connector. The conmector values are buffed but wire values are default. This way you can't unify multiple connectors into one wire like you should be able to. This is really annoying when trying to build stuff with IE wiring.

**Modpack Version**
1.51

**Additional Context**

**Comment by NillerMedDild** [comment]
I did double the throughput, but I'll amp it up, thanks.
