### ISSUE TITLE
Tinker Tank no longer valid

### ISSUE THREAD

**Issue by Isolol** [NillerMedDild/Enigmatica2Expert#625]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
After updating to Enigmatica 2: Expert 1.51 the Tinker Tank is no longer valid in many configurations.

**Modpack version (Do not use "latest")**
Enigmatica 2: Expert v1.51
TConstruct v2.12.0.113

**Screenshots**

This is currently the only configuration it works in: https://i.imgur.com/45a2RQg.jpg

**Additional context**

TConstruct has fixed issue in: https://github.com/SlimeKnights/TinkersConstruct/issues/3719

**Comment by NillerMedDild** [comment]
Thanks for the report.

**Comment by Targren** [comment]
Possibly related, in case anyone else comes looking- I ran into the same issue with the Tinker's Furnace with the controller on the bottom layer (where it has been since I built it). Moving it up against the hollow inner chamber reactivated the multiblock.
