### ISSUE TITLE
Major Crash with AS & Extra Utilities? Server 1.51

### ISSUE THREAD

**Issue by KaneHart** [NillerMedDild/Enigmatica2Expert#626]
So I been trying my best to resolve this without much luck.

Crash Log:
https://pastebin.com/V5cL3BNt

So what is happening is when the server but not a instant crash but rather when the server gets rebooted then starts up LOL really annoying as hell.

I tried Posting here but it got closed:
https://github.com/HellFirePvP/AstralSorcery/issues/973

I have a report here as well:
https://github.com/rwtema/Extra-Utilities-2-Source/issues/262

**Comment by NillerMedDild** [comment]
Did you try removing the block at `2110,52,1377`?

**Comment by KaneHart** [comment]
I removed the entire region mate and yes the block originally. It just shifts to the ticking of other entities till there is none left.

See if this is an example of it when I first had it:
https://pastebin.com/cRRxS6DB

Really tired right now can't be much of help can barley stare at the monitor lol

**Comment by NillerMedDild** [comment]
I'm afraid I don't know the cause or a fix, I hope they help out at the XU tracker.

**Comment by KaneHart** [comment]
Yeah haha, I doubt it. I assume you wanted this here (till it's fixed) in case others might run into it. My server is down till it gets fixed as it keeps happening over and over after rollbacks :)

Thanks mate have a good day.

**Comment by NillerMedDild** [comment]
Sorry I can't be of more help at the moment.

**Comment by t3rraz** [comment]
what is when u start the Server without the ae2:stuff mod, and then put the mod back ? maybe u will lose some ae2 stuff, but better as no Server :P

**Comment by KaneHart** [comment]
AE2 stuff not actually causing the error. You are misunderstanding the log for a ticking entity

**Comment by valarnin** [comment]
Pretty sure removing ExUtils2 and restarting server would clear up the issue, and then tell players to not build ExUtils2 GP generating blocks anywhere near Astral Sorcery multiblocks.

The basic gist of that stack trace seems to be "Something causes block update near or adjacent to AS multiblock; AS checks to make sure the multiblock is still valid; AS calls improperly implemented method on ExUtils2 power generating block while trying to read its' NBT data".

**Comment by KaneHart** [comment]
I found actually deleting the AS data file fixed the issue. Removing and adding EU2 did not actually solve the issue. Once put back it crashed again. Even with every region nuked it still crashed. The one and only true fix was to nuke the AS data file. Sadly AS devs not interested in fixing it as their saying it's EU2 fault but sadly we know that dev is not going to do shit all.

**Comment by NillerMedDild** [comment]
Okay then.

**Comment by valarnin** [comment]
Interesting. Do you have the server start log post-removal of EU2, then the crash after adding back in? I'm really not sure how it could tick a crash for a TE that shouldn't have existed anymore.

It's important to note that the coordinates of the originating TE event that caused the crash (AE2Stuff inscriber) are irrelevant and the actual EU2 TE could be anywhere around an AS multiblock anywhere on the server. The TE generating the block/chunk update could be at -1000, -1000 but be causing the EU2 block at 500,500 to error out.

**Comment by KaneHart** [comment]
I do but once again your going based on Fake Information in the log. Because something ticked does not mean it crashed. Like I said the crash Happens with the entire region files removed... This is happening outside of world level. So removing EU2 and then adding it back in does not actually fix any issues. I have logs showing the same error just nothing ticking (fresh world besides data files copies).

It's actually how I ended up solving it by removing AS Data file. Something to do with bad deserialization with EU2.

**Comment by valarnin** [comment]
Sorry, I was checking the source related to this (and posting comments) via my phone and it wasn't very conducive to the conversation.

I'm going to go ahead and reply on the AS bug for this and point out that they may want to catch this error as well, since they're already catching (and throwing away without logging) the base Exception class in that code block: https://github.com/HellFirePvP/AstralSorcery/blob/master/src/main/java/hellfirepvp/astralsorcery/common/util/nbt/NBTHelper.java#L153
