### ISSUE TITLE
Make extended crafting tables size independent

### ISSUE THREAD

**Issue by fuj1n** [NillerMedDild/Enigmatica2Expert#627]
**Is your feature request related to a problem? Please describe.**
It is extremely annoying to have to make one of every tier of extended crafting table to craft lower-tier recipes rather than just using the max max tier when you get to it.

**Describe the solution you'd like**
Extended Crafting allows you to specify 0 for the tier of the craft instead of whatever the required tier is, which in turn will allow you to use any extended crafting table as long as the recipe fits, for example, I can use a 5x5 crafting table to make a 3x3 recipe.

**Additional context**
For example, I would be able to do something like this with the reactor controller (legacy) recipe
![image](https://user-images.githubusercontent.com/4004193/51168537-b68d0b00-18fd-11e9-8070-4141451c932b.png)

**Comment by NillerMedDild** [comment]
Done!
