### ISSUE TITLE
Crashing when "building terrain".

### ISSUE THREAD

**Issue by Mana97** [NillerMedDild/Enigmatica2Expert#628]
## Thank you for helping us improve. #####

**Issue Description**
When i try to start a world (when i have already played) the game crash on the building terrain screen. I've tryed to delete the journeymaps folder because on the log file there is written something about it, but this don't fixed the bug. One important point is that i've tried to create a new world: when creating a new world there was no crash at all and i've been able to play in this new world.
Thank's for the attenction.

**Modpack version (Do not use "latest")**
1.51

**Logs**

[latest.log](https://gist.github.com/Mana97/45c378bd1fc662d9ecab361fb16b494b#file-latest-log)

**Comment by NillerMedDild** [comment]
Delete this file: `C:/Users/Alessio/Documents/Curse/Minecraft/Instances/Enigmatica 2 Expert/saves/Works_/advRocketry/planetDefs.xml`
