### ISSUE TITLE
Xnet connector variants (blue, red, etc) don't have full name in recipe

### ISSUE THREAD

**Issue by TDSSS** [NillerMedDild/Enigmatica2Expert#632]
## Thank you for helping us improve. #####

**Issue Description**
The JEI recipe for Xnet controllers (Blue connector, red connector, etc.) only show up as 'controller' in the JEI recipe itself, but are called blue controller etc. in JEI, so under a different name.

**Modpack version (Do not use "latest")**
1.51

**Logs**
Don't think this is relevant

**Screenshots**
Search for 'blue controller' in JEI and you find:
![untitled](https://user-images.githubusercontent.com/32099540/51264779-8e61e280-19b7-11e9-97e0-2c3873d9176c.png)
click on it and you see:
![untitled2](https://user-images.githubusercontent.com/32099540/51264797-94f05a00-19b7-11e9-9171-f7c713c9993d.png)
And be confused by the name being different.
**Additional context**

Not a huge issue, but briefly confusing. Especially with the recipe that changes the color of a controller, which changes 'controller' into 'controller' with just the picture changing.

**Comment by NillerMedDild** [comment]
This is not within my control unfortunately, but I don't personally consider it a bug either. I appreciate the report though :)
