### ISSUE TITLE
Restricting Capturing of Boss-like Enemies (FryoKnight)

### ISSUE THREAD

**Issue by FryoKnight** [NillerMedDild/Enigmatica2Expert#633]
**Is your feature request related to a problem? Please describe.**
With how powerful Dragons, Gorgons, and Cyclops can be, it is kinda silly that unlike Withers, Ender Dragons, and other "boss creatures" you can simply imprison them in a tiny little ball. I recommand changing the config to restrict being able to capture said creatures from at least the following as they are easily acquired early game: **Monster Ball** (_Cyclic_), **Morb** (_Thermal Expansion_)

**Describe the solution you'd like**
For the Monster Balls:
`\config\cyclicmagic.cfg`
```
    magic_net {
        # Entities that cannot be captured.  (even without this, players and non-living entities do not work) [default: [minecraft:wither], [minecraft:ender_dragon], [minecraft:ender_crystal]]
        S:CaptureBlacklist <
            minecraft:wither
            minecraft:ender_dragon
            minecraft:ender_crystal
			iceandfire:icedragon
			iceandfire:firedragon
			iceandfire:dragonskull
			iceandfire:cyclops
			iceandfire:gorgon
			iceandfire:stonestatue
			iceandfire:stymphalianfeather
			iceandfire:myrmex_queen
         >
    }
```

For the Morbs:
`\config\cofh\thermalexpansion\morbs.cfg`
```
Blacklist {
    # List of entities that are not allowed to be placed in Morbs. Mobs without spawn eggs are automatically disallowed. [default: ]
    S:Blacklist <
		iceandfire:icedragon
		iceandfire:firedragon
		iceandfire:cyclops
		iceandfire:gorgon
		iceandfire:myrmex_queen
     >
}
```

**Additional context**
I tacked on Stone Statues and Dragon Skulls as they are meant to be dectortive, and Stymphalian Feathers as they are an attack in the Monster Ball config.
I also added the Myrmex Queen as well.

I feel that some forms of Creature Capture is ok with these mobs for late game farming, but Monster Balls only really need Snow to make and capture some of these normally difficult creatures to take on.

Also, on a side note, Dragons, Myrmex, Stymphalian and Deathworms can be captured at full health with a Golden Lasso. This is because they are programmed as "Passive Mobs" even though they are hostile.

**Comment by NillerMedDild** [comment]
Excellent report, thank you. I'll get this implemented asap.

**Comment by FryoKnight** [comment]
Wow, you are on the ball today! But thank you, one of my Server players noticed this and I thought it was a little silly that it was so easy to cram these boss creatures into tiny little balls.

Like, I would love to capture a Dragon in a Mob Imprisonment Tool, and make a grinding for Eggs, but those also require lots of Mob Essence, Power (both depending on the amount of health the creature has as max).
