### ISSUE TITLE
Mana Infused Gear not craftable in IE Metal Press

### ISSUE THREAD

**Issue by ArbitraryHubris** [NillerMedDild/Enigmatica2Expert#635]
**Issue Description**
JEI shows that 4 mana infused ingots in a metal press with the gear template will craft a mana infused gear.  The metal press will not accept the ingots.

Easy workaround is to use tinkers.

**Modpack version (Do not use "latest")** 1.51

**Comment by ArbitraryHubris** [comment]
actually, maybe it's a mistake on my part.  This is the first time I've tried to create a gear.  when I put the gear mold in the press, it won't pull tin either.

**Comment by ArbitraryHubris** [comment]
False report - just needed one more piece of conveyor and my input hopper on that.  Closing.

**Comment by NillerMedDild** [comment]
The issue is that the Gear creation takes 4 Ingots, and it will only accept them bundled up, not one at a time.

**Comment by ArbitraryHubris** [comment]
sorry I bugged you with a false issue.  I hoped I'd closed it fast enough that you wouldn't see it.

**Comment by NillerMedDild** [comment]
No worries! :)
