### ISSUE TITLE
Compact Machines - "Down" tunnel not placeable

### ISSUE THREAD

**Issue by Damit84** [NillerMedDild/Enigmatica2Expert#638]
There is a problem with the current "Compact Machines" Version in the mod pack. It is impossible to set a tunnel interface inside a CM dimension to the "down" setting. This is already a known bug in the CM github and the only fix for the moment seems to be a downgrade of the CM version.

Link to the CM github issue:
https://github.com/thraaawn/CompactMachines/issues/368
https://github.com/thraaawn/CompactMachines/pull/369

Modpack Version: 1.50 & 1.51 & 1.52 (probably even earlier since the bug is pretty old)

How to reproduce:
Inside a CM dimension click any wall block with a tunnel item. The first setting should be "down".

There is probably not a lot to be done about that problem but I just wanted to report it nonetheless.

**Comment by NillerMedDild** [comment]
Thank you for the report :)

**Comment by NillerMedDild** [comment]
Fixed in the mod.
