### ISSUE TITLE
Illumination Powder Starlight Crafting Engine Recipe Broken

### ISSUE THREAD

**Issue by valarnin** [NillerMedDild/Enigmatica2Expert#640]
**Issue Description**
The Illumination Powder recipe in the Starlight Crafting Engine is broken. The nitor in the recipe does not show and placing the expected recipe (according to https://github.com/NillerMedDild/Enigmatica2Expert/blob/master/scripts/modular_machinery/starlight_crafting_engine.zs#L33) in the input does not trigger the craft.

**Modpack version (Do not use "latest")**
1.50a, though I have verified that the recipe in the relevant script has not changed since this version.

**Screenshots**
![image](https://user-images.githubusercontent.com/6119598/51295042-bf580c80-19e3-11e9-8b17-58756a0a4c77.png)

**Additional context**

Might be because the nitor in the recipe has metadata assigned to it, whereas the actual nitor doesn't? I'm not sure here.

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.
