### ISSUE TITLE
Disable Pam's Garden Spreading, to Reduce World Clutter

### ISSUE THREAD

**Issue by ArbitraryHubris** [NillerMedDild/Enigmatica2Expert#641]
**Is your feature request related to a problem? Please describe.**
Pam's Harvestcraft gardens are highly prevalent in worldgen.  Then they spread.  They end up being a blight on the landscape as they take over.  There are plenty of gardens without spread.   It's unnecessary and ugly - totally subjective opinion. 

in config/harvestcraft.cfg set B:enablegardenSpread=false

**Comment by NillerMedDild** [comment]
Agreed :)
