### ISSUE TITLE
Forestry Circuits Still Bugged

### ISSUE THREAD

**Issue by Dark-Matter-001** [NillerMedDild/Enigmatica2Expert#642]
Looks like the same issue as #623 but in another recipe.

**Screenshots**

https://imgur.com/a/98RnTrQ

**Additional context**

Also tried a vanilla crafting table.

**Comment by NillerMedDild** [comment]
In version 1.52?

**Comment by Dark-Matter-001** [comment]
Yes.

A crafted forestry circuit has no NBT tags and it seems the recipe wants one.
https://imgur.com/a/9Jeort2

Crafted circuit wouldn't work but creative spawned circuit that spawns with some NBT tag does.

from line 78 of ModularMachinery.zs: <forestry:chipsets:3>.withTag({})
I guess that makes it require a tag?

**Comment by NillerMedDild** [comment]
God damnit >< guess I'll have to make the circuits be created with tags.
