### ISSUE TITLE
immersive engineering power production devices not working

### ISSUE THREAD

**Issue by dragonup1793** [NillerMedDild/Enigmatica2Expert#643]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Question or Issue**
all the immersive engineering power production device I have tried to use are producing 0 rf. both the thermal gen and the kinetic dynamo are giving 0 rf  

**Modpack Version**
1.52

**Additional Context**
when they are placed and connected to there respective power sources the read 0 rf /s

**Comment by NillerMedDild** [comment]
Did you connect anything to the Kinetic Dynamo, or place hot/cold blocks next to the Thermoelectric Generator?

**Comment by dragonup1793** [comment]
yes and yes there is nothing being output when there set up with water wheels and hot and closed blocks

**Comment by dragonup1793** [comment]
i connected 8 water wheels with lv connecter into a capacitor

**Comment by NillerMedDild** [comment]
Screenshots of the setups please :)
