### ISSUE TITLE
Thorium Block and Block of Uranium missing recipes for Compacting Drawer

### ISSUE THREAD

**Issue by xmiso** [NillerMedDild/Enigmatica2Expert#644]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Question or Issue**

Thorium Block and Block of Uranium don't have recipes in the Compacting Drawer. It would be really useful to have them (for storage and/or singularities)

**Modpack Version**

1.5.2

**Additional Context**

**Comment by NillerMedDild** [comment]
Thanks for the report, I'll get that implemented :)

**Comment by NillerMedDild** [comment]
![billede](https://user-images.githubusercontent.com/21295394/51338011-fb917880-1a88-11e9-9305-3531ff05617b.png)

Yes they do :P

**Comment by xmiso** [comment]
![2019-01-17_15 03 51](https://user-images.githubusercontent.com/46682682/51338695-4a2f1a80-1a69-11e9-9278-ccc50234a3ea.png)
What... they don't work for me.

**Comment by NillerMedDild** [comment]
Put the ingot in first.

**Comment by xmiso** [comment]
Oh... thank you!
