### ISSUE TITLE
Block of Cobalt from Smart Outputs is chiseled

### ISSUE THREAD

**Issue by xmiso** [NillerMedDild/Enigmatica2Expert#645]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**

Using the Basin Upgrade in the Smart Output and pouring Molten Cobalt on it makes a chiseled Block of Cobalt, which doesn't have Compacting Drawers recipes. Changing the block to the normal one would be really useful.

**Modpack version (Do not use "latest")**

1.5.2

**Additional context**

**Comment by NillerMedDild** [comment]
Thanks for the report, I'll get it fixed :)
