### ISSUE TITLE
Elytra item duping

### ISSUE THREAD

**Issue by Akatroj** [NillerMedDild/Enigmatica2Expert#646]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**

If you place Elytra from the Colytra mod in your off-hand, and right click, it will be equipped to the bauble slot without disappearing from your off-hand slot, thus duping the item.

**Modpack version (Do not use "latest")**

1.52

**Logs**

unrelated

**Screenshots**

![image](https://user-images.githubusercontent.com/46789820/51348196-56839980-1aa2-11e9-8d38-0ea12d5ce3eb.png)

**Additional context**

**Comment by NillerMedDild** [comment]
Yikes, thanks for the report.
