### ISSUE TITLE
item dupe with /dank/null and sieves

### ISSUE THREAD

**Issue by Paperweight82** [NillerMedDild/Enigmatica2Expert#647]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
/dank/nul duplicating blocks when used with ex nihilo creatio sieve. sieving works and produces drops but does not consume gravel or sand.
those are the only blocks i have tested this with, but i assume the same for all sievable blocks
i was using an enchanted diamond mesh on a basic sieve, and a MK5 /dank/null

**Modpack version (Do not use "latest")**
1.52

**Logs**

If applicable, please upload your crash report, or latest.log to [gist](https://gist.github.com/).

**Screenshots**

**Additional context**

**Comment by valarnin** [comment]
I reported this to the Ex Nihilo Creatio github a while ago.

https://github.com/BloodyMods/ExNihiloCreatio/issues/121

**Comment by NillerMedDild** [comment]
So placing blocks in the Sieve from the Dank/Null/ does not consume said block?

**Comment by NillerMedDild** [comment]
You can get the Sieve from Loot Chests.
