### ISSUE TITLE
Smart Output breaks instantly with hand

### ISSUE THREAD

**Issue by xmiso** [NillerMedDild/Enigmatica2Expert#648]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**

Smart Output breaks instantly with hand. It doesn't drop the Smart Output, but it does drop whatever was inside it. Accidentally broke a few of my Smart Outputs this way.

**Modpack version (Do not use "latest")**

1.5.2

**Additional context**

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
Confirmed, there's an open issue here:
https://github.com/gkbm2013/tinker-IO/issues/89
