### ISSUE TITLE
0/0 slot middle bag spawning in tcon crafting station

### ISSUE THREAD

**Issue by Eyebeats** [NillerMedDild/Enigmatica2Expert#649]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
When ever I open a tinkers construct crafting station a middle bag will spawn. with 0/0 slots and I cant do anything with it

**Modpack version (Do not use "latest")**
1.52

**Logs**
n/a

If applicable, please upload your crash report, or latest.log to [gist](https://gist.github.com/).

**Screenshots**

**Additional context**

NOTE: this issue is not the same as the others I have seen IE "arcane table" this issue is with the tcon crafting station

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
I can't seem to reproduce this.
