### ISSUE TITLE
Advanced Thermionic Fabricator

### ISSUE THREAD

**Issue by NeosGhost** [NillerMedDild/Enigmatica2Expert#650]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
Modular Machinery blueprint lists Block of Steel x8 but will only form with one version of Block of Steel eg Immersive Engineering #8679/8 block only no support for ore dict blockSteel. Checked with Thermal Expansion Steel #4690/0, IndustrialCraft 2 Steel #4097/8, and Mekanism Steel #8819/5.

**Modpack version (Do not use "latest")**
1.52

**Logs**

If applicable, please upload your crash report, or latest.log to [gist](https://gist.github.com/).

**Screenshots**

**Additional context**

Can use the chisel to switch to the block of steel from IE.

**Comment by NillerMedDild** [comment]
That is intentional :)

**Comment by NeosGhost** [comment]
sounds good thanks
