### ISSUE TITLE
Wireless RF Heating Coil not usable as fuel.

### ISSUE THREAD

**Issue by NeosGhost** [NillerMedDild/Enigmatica2Expert#651]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
When inserting into the fuel slot of vanilla furnace, mystical agriculture Ultimate Furnace, tinker's construct Heater, cooking for blockheads Oven it gets dropped on ground or returned to inventory.
 

**Modpack version (Do not use "latest")**
1.52

**Logs**

If applicable, please upload your crash report, or latest.log to [gist](https://gist.github.com/).

**Screenshots**

**Additional context**

Was working in version 1.48a...noticed when updating from that to 1.52
Thanks

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NeosGhost** [comment]
No problem if I can help let me know I have a few days of nothing to do. :)

**Comment by NeosGhost** [comment]
After breaking all the items involved and replacing them it magically works now...also cannot replicate in a new creative test word.. Thanks anyway :)

**Comment by NillerMedDild** [comment]
Thanks for handling it yourself :)
