### ISSUE TITLE
xp droplet to liquid

### ISSUE THREAD

**Issue by redgoblin88** [NillerMedDild/Enigmatica2Expert#652]
**Is your feature request related to a problem? Please describe.**
thermal expansion provides ways to make several powders which are used later on (blitz, blizz, balsaz and blaze)

in order to make these powders you need two of a certain item and experience however even though i am growing experience seeds and can turn them into player experience and then liquify that, i cannot turn the experience droplets directly into liquid xp

**Describe the solution you'd like**
i would like the ability to turn mystical agriculture experience essence into liquid experience. in my testing i have found that you get between 160 and 240mb of experience per droplet (using one and then converting it into liquid with the fluid transposer, done this about 8 times now)

if you were to make each experience droplet turn into 200 mb of liquid xp through the magma crucible or fluid transposer or any other machine which can liquify items then this would be extremely useul for automating the powders as exlained before

If the powders are automatable with this method, it would greatply improve making gelid cryotheum, tectonic petrotheum and aerotheum dust which are later-on items

**Additional context**
![2019-01-18_20 30 46](https://user-images.githubusercontent.com/13396472/51411492-fb17e100-1b5f-11e9-8034-f734e4e875ea.png)

something like... oh i dont know... :)

mods.thermalexpansion.Crucible.addRecipe(<liquid:experience>*200, <mysticalagriculture:xp_droplet>, 1600);

**Comment by NillerMedDild** [comment]
I'll look into it :)
