### ISSUE TITLE
UU value to wither skulls

### ISSUE THREAD

**Issue by redgoblin88** [NillerMedDild/Enigmatica2Expert#653]
**Is your feature request related to a problem? Please describe.**
as you may have seen, i am doing a 99.99% pure peaceful run which means not a single hostile mob, all the loot must come through some game mechanic either by vanilla, modded or other means as long as it is not /give.
(the 0.001% is from early on where i was forced to easy since industrial foregoing pink slimes are registered as hostile and would despawn in peaceful)

My problems however is slowly approaching where i'm forced to start fighting the wither however there's one huge problem... i cannot get wither skulls renewably...

i am almost into draconic evolution and almost at the level where i need nether star level of stuff

**Describe the solution you'd like**
would it be at all possible to add some stupid method to get renewable wither skulls or nether stars? i have already tested in a creative world and they have no UU value.

i mean, we can UU matter dragon hearts even though they spawn everywhere and can be respawned with vanilla end crystals now so why not wither boses?

**Additional context**
[none]

**Comment by NillerMedDild** [comment]
I'll look into it :)
