### ISSUE TITLE
Garden cloche not giving any outputs

### ISSUE THREAD

**Issue by audaciousSalix** [NillerMedDild/Enigmatica2Expert#654]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
My Garden Cloche seems to be working as normal, with power/water etc, and i can see the working bar going and the animation of the seed growing - but when it finishes, I get absolutely no output into the internal storage, nothing if i put a chest or drawer next to the output. It's like the output just disappears. This is happening with vanilla seeds, I tried with potatoes wheat and netherwart. I've broken and replaced the cloche and same issue

**Modpack version (Do not use "latest")**
Happened to me on both 1.51 and 1.52

**Logs**

If applicable, please upload your crash report, or latest.log to [gist](https://gist.github.com/).

**Screenshots**

**Additional context**

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by KingIonTrueLove** [comment]
Decided to place down a new garden cloche to text, energy conduit on top, pressure conduit for water on bottom. Works perfectly fine for me on 1.52

**Comment by audaciousSalix** [comment]
I am not still having the issue it seems - I didn't break the cloche this time as I did before, but wired it back into my RF (unplugged it as was wasting power when not working) and it didn't work, but when I took the seed out and gave it time for the power buffer to fill it seems to work fine. So must have just been a power deficiency issue, just was weird that it was still showing the animation for growing when it actually was not.
