### ISSUE TITLE
FTB Utilities /home No Permission to use

### ISSUE THREAD

**Issue by Redeye123** [NillerMedDild/Enigmatica2Expert#656]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
FTB Utilities command /home : People don't have permission to use it .

**Modpack version (Do not use "latest")**
1.52 Expert

**Logs**

If applicable, please upload your crash report, or latest.log to [gist](https://gist.github.com/).

**Screenshots**

**Additional context**

We run a server and we just updated to 1.52 before the update i set it up that people have 3 homes trough the ranks but suddenly they don't have access to the command i know cyclic has a /home too but just wanted to see if there are reports of it or not before disabling cyclics /home command.

**Comment by NillerMedDild** [comment]
The /home command from FTB Utilities is disabled by default, meaning it will be disabled whenever you update. You need to reapply all custom changes after updating.

I personally keep a folder of configs I've changed for the official servers, that makes updating easier :)
