### ISSUE TITLE
Game is hard crashing constantly upon pressing T

### ISSUE THREAD

**Issue by sammyfrost** [NillerMedDild/Enigmatica2Expert#657]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
Upon pressing T as I join my friends server my game crashes back to the launcher and I am unable to play and communicate with my friends.

**Modpack version (Do not use "latest")**

1.44

**Logs**
https://pastebin.com/FbkMZTVs
If applicable, please upload your crash report, or latest.log to [gist](https://gist.github.com/).

**Screenshots**

**Additional context**

**Comment by NillerMedDild** [comment]
Reinstall your instance :) Something got messed up with your keybinding configuration.
