### ISSUE TITLE
Reporting a crash (can't be replicated) #unimportant

### ISSUE THREAD

**Issue by treechain** [NillerMedDild/Enigmatica2Expert#659]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
Crashed after starting modpack, getting to title screen, quitting then starting modpack again.
Cannot replicate
Restarting the pack worked and the consecutive restart after also worked.

**Modpack version (Do not use "latest")**
1.52

**Logs**
https://gist.github.com/treechain/115dade631a8bd4e573002bea2972406

**Screenshots**
N/A

**Additional context**
For the file version of the gist:
[crash-2019-01-19_13.19.17-client.txt](https://github.com/NillerMedDild/Enigmatica2Expert/files/2775902/crash-2019-01-19_13.19.17-client.txt)

**Comment by NillerMedDild** [comment]
It was a bad install, Twitch issue :) thanks for the report.
