### ISSUE TITLE
Alloy smelter from nuclearcraft doesn't work

### ISSUE THREAD

**Issue by ecatherman** [NillerMedDild/Enigmatica2Expert#661]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
The alloy smelter from nuclearcraft does not work for several different alloys that I have tested.
invar
electrical steel [steel & silicon]
bronze

I can see these recipes in JEI.

**Modpack version (Do not use "latest")**
1.50a

**Logs**

No crash.

**Screenshots**
![image](https://user-images.githubusercontent.com/6530707/51433280-3b856680-1c15-11e9-8abe-6d3206e3f1be.png)

![image](https://user-images.githubusercontent.com/6530707/51433285-4fc96380-1c15-11e9-97be-f9ca609478e3.png)

![image](https://user-images.githubusercontent.com/6530707/51433275-201a5b80-1c15-11e9-935e-73615e6164f0.png)

**Additional context**

I have unlocked the quest for the alloy furnace.

**Comment by NillerMedDild** [comment]
Update.
