### ISSUE TITLE
Quest Progression Bug for IC2

### ISSUE THREAD

**Issue by treechain** [NillerMedDild/Enigmatica2Expert#662]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
The universal fluid cell is not available from JEI so the "Blast Furnace" quest in the IC2 progression tab cannot be completed easily. The creative tab still has the item.

**Modpack version (Do not use "latest")**
1.52

**Logs**

N/A

**Screenshots**

![1](https://user-images.githubusercontent.com/30122899/51433293-13920500-1c0d-11e9-90e5-420c620a89cf.PNG)
![b](https://user-images.githubusercontent.com/30122899/51433296-17258c00-1c0d-11e9-9a18-e663a0514cae.PNG)

**Additional context**

**Comment by redgoblin88** [comment]
It may be a minor mistake niller did when he tried to hide all of the fluid cells as JEI is picky when you choose to hide specific items with the same item ID

Have you tried the default recipe?
(T =Tin item casing, G = glass pane, N = nothing)

(N,T,N)
(T,G,T)
(N,T,N)

**Comment by NillerMedDild** [comment]
It's not a mistake, they're hidden on purpose to reduce lag. The quest states the recipe...

**Comment by wanybae** [comment]
How can we complete 'Blast Furnace' quest?

**Comment by NillerMedDild** [comment]
Craft the items?

**Comment by wanybae** [comment]
First yes.
If I can't craft Universal Fluid Cell, I cannot complete 'Blast Furnace' quest and next quests.

**Comment by NillerMedDild** [comment]
... read this issue please. Or the quest.

**Comment by wanybae** [comment]
Oh! My mistake
I am so sorry ><' I didn't realize there is the recipe for Universal Fluid Cell.

Thank you :)

**Comment by Frikkle** [comment]
But how can we craft the fluid cell then? :p

**Comment by wanybae** [comment]
You can read the ‘Blast Furnace’ quest. There is Universal Fluid Cell’s recipe.
