### ISSUE TITLE
Bauxite veins(Excavator) Still appear and work

### ISSUE THREAD

**Issue by KingIonTrueLove** [NillerMedDild/Enigmatica2Expert#663]
**Issue Description**
Even though they are supposed to be disabled in configs, you can still find bauxite veins, and get rutile from them.

Two instances where bauxite veins still appear and work. My world is super old so it could have happened before the veins were even disabled for all I know, but now I have confirmation from a discord user that it happens on newer worlds.

**Modpack version (Do not use "latest")**
1.52 (1.50 Was version that the world was generated for CodeMonkey, who knows how old mine is)

**Logs**

**Screenshots**
https://i.imgur.com/fHbWbAQ.png My world
https://i.imgur.com/FX4FSY1.png Codemonkey's Screenshot

**Additional context**
The config file immersiveengineering.cfg still has bauxite veins disabled (Zero on line 391, for 'vein size')

EDIT: Just made a brand new world, found bauxite vein on 4th sample, built an excavator and it still gives aluminum and rutile.

EDIT 2: Just realized that that config is for normal bauxite spawning, not the excavator veins. I swear when I checked the config files a month or so ago (searching for bauxite in the whole folder) there was a second config that explicitly disabled bauxite excavator veins, but I am unable to find it anymore.

**Comment by NillerMedDild** [comment]
Bauxite Ore generation and Bauxite Veins for the Excavator are two seperate things, Bauxite Veins for the Excavator are enabled on purpose.
