### ISSUE TITLE
Cyclic heart recipe missing

### ISSUE THREAD

**Issue by Dokend** [NillerMedDild/Enigmatica2Expert#664]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
Is the cyclic heart disabled because crafting recipe is missing?

**Modpack version (Do not use "latest")**

Enigmatica 2 Expert 1.52

**Logs**

If applicable, please upload your crash report, or latest.log to [gist](https://gist.github.com/).

**Screenshots**

**Additional context**

**Comment by NillerMedDild** [comment]
Yep!

**Comment by Dokend** [comment]
ah i see o well no more hearts for me they where active for a while and got hearts off them

**Comment by NillerMedDild** [comment]
You can still gain hearts from eating different foods :)

**Comment by Dokend** [comment]
Im at the point where it takes 50 foods per heart
