### ISSUE TITLE
Scannable config contains errors

### ISSUE THREAD

**Issue by esotericist** [NillerMedDild/Enigmatica2Expert#665]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
Several lines in the Scannable.cfg file are incorrect.

lines 133 through 138 refer to `Infused`, but since there are no oredict entries in that shape the selected colors do not apply to scanned crystals:
```
        oreInfusedAir=0xF7E677
        oreInfusedFire=0xDC7248
        oreInfusedWater=0x9595D5
        oreInfusedEarth=0x49B45A
        oreInfusedOrder=0x9FF2DE
        oreInfusedEntropy=0x545476
```

The Thaumcraft ore entries are in the form of `oreCrystal[Type]` and should instead be:
```
        oreCrystalAir=0xF7E677
        oreCrystalFire=0xDC7248
        oreCrystalWater=0x9595D5
        oreCrystalEarth=0x49B45A
        oreCrystalOrder=0x9FF2DE
        oreCrystalEntropy=0x545476
```

line 156 has a case error that causes Apatite to be considered a rare ore instead of a common one:
```
        OreApatite
```
and instead should be:
```
        oreApatite
```

**Modpack version (Do not use "latest")**
1.51 (but nothing in the 1.52 changes affects this, and the errors currently exist in the github master)

**Logs**

If applicable, please upload your crash report, or latest.log to [gist](https://gist.github.com/).

**Screenshots**

**Additional context**

**Comment by NillerMedDild** [comment]
Thanks for the report, and the fixes :)

**Comment by esotericist** [comment]
No problem. :) Thank you for your hard work on the pack!

**Comment by NillerMedDild** [comment]
My pleasure!
