### ISSUE TITLE
Celestial Altar Not Behaving Properly

### ISSUE THREAD

**Issue by SomeRandomPetey** [NillerMedDild/Enigmatica2Expert#668]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Question or Issue**
For some reason, the celestial altar will only work with the tier 2 altar rather than the tier 3 altar, which it is supposed to use.
**Modpack Version**
1.5.1
**Additional Context**

**Comment by NillerMedDild** [comment]
Screenshots would be very helpful :)

**Comment by SomeRandomPetey** [comment]
It was a bug with the server I was playing on, the bug is fixed :)
