### ISSUE TITLE
Psi Levelling Bugged

### ISSUE THREAD

**Issue by Jistoned** [NillerMedDild/Enigmatica2Expert#669]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Question or Issue**
It seems that progression within Psi is currently bugged with the version used, as the player is unable to progress past level 1 (gained from using a rod on redstone to turn it into psidust). As such, the Spell Constructor cannot be accessed (gives the message "You have no idea how to operate this), making it impossible to progress in the mod. Replicated the issue in both multiplayer (on a locally hosted server) and single player.

**Modpack Version**
1.56

**Additional Context**
This seems to be an ongoing issue, and is supposedly fixed in the latest version of Psi.
https://psi.vazkii.us/changelog.php#r1.1-70

On a side note, thanks for all your dedication and effort put into the modpack, really enjoying it!

**Comment by NillerMedDild** [comment]
Sadly I can't update yet, as the latest versions of Psi crash on load, because of a bug in Magical Psi.

**Comment by OneEyeMaker** [comment]
@Jistoned 
Did you clicked little arrow button on tutorial screen (in right bottom corner, when first level is selected)?
I also had similar "problem" until I found, that this hidden button should be pressed (everytime you gain new level).
