### ISSUE TITLE
[Suggestion] Consider Nerfing the Immersive Tech Turbine

### ISSUE THREAD

**Issue by Vyraal1** [NillerMedDild/Enigmatica2Expert#67]
#### Issue Description
Consider Nerfing Immersive Tech Turbines in terms of steam consumption, especially since it seems like the torque was buffed (and it's overall power production) was buffed. 

On default configs, the IT Turbine consumes about 50-51 mb/t of steam and outputs ~52k rf/t.

With E2E's configs, it outputs ~83k rf/t while using about 50 mb/t of steam.

![image](https://user-images.githubusercontent.com/26587049/39952545-fb24df96-5566-11e8-862d-bb9bc76722e2.png)

![image](https://user-images.githubusercontent.com/26587049/39952540-ead5cf74-5566-11e8-9fb8-0c82268d7a7d.png)

The mod is not very well balanced when it comes to the unofficial standard of 1 mb/t of steam = 2 rf/t set by Railcraft and what Thermal Expansion follows (however in comparison, Extreme Reactors does not adhere to this standard either, as Enderium Coil turbines can also do around 28k rf/t wiith only 2b/t of steam). Having the turbine in any pack that has any form of easy steam production eg. Advanced Generators, or in this case, Mekanism Thermoelectric Boilers, can easily break power production wide open, even beyond the powerful Mekanism Gas Burning Generators. 

Relative to the power production in the lategame, such as T6 ET Solars or large toroid NuclearCraft reactors, 83k its pretty small, however the turbine is pretty much accessible with only heavy engineering blocks. And Mekanism Thermoelectric boilers are pretty accessible as soon as you get Enriched Alloys and Steel.

![2018-05-11_21 53 43](https://user-images.githubusercontent.com/26587049/39952560-73b4cf0c-5567-11e8-9cef-4db98cfec61a.png)
Sample setup, resistive heater taking in 2k rf/t powers a thermoelectric boiler that produces 50 mb/t of steam. Normally this is power neutral or a power loss, but its busted wide open with IE Turbines low steam consumption rate.

I think the power output of the turbine is fine at the moment, however it definitely needs to consume more steam (and either buff the boilers that come with IE to be competitive with other options, or disable them entirely as they suck to begin with).

#### Modpack version (Do not use "latest")
Enigmatica: 1.23

**Comment by NillerMedDild** [comment]
Sounds like it really needs a nerf. How does 4000mb/t sound?

**Comment by NillerMedDild** [comment]
Which boilers are in IE? I only know of the Solar Tower.

**Comment by NillerMedDild** [comment]
I requested a config for the Boiler's output, fingers crossed :)
https://github.com/FerroO2000/Immersive-Tech/issues/58
