### ISSUE TITLE
Crash server & client when putting bottle of water into industrial foregoing potion brewer

### ISSUE THREAD

**Issue by Ricket** [NillerMedDild/Enigmatica2Expert#670]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**

I bumped into this bug: https://github.com/MinecraftModDevelopmentMods/Tesla-Core-Lib/issues/28#issuecomment-424061514
When I tried to insert a water bottle into a potion brewer (to extract the water from it). The comment I linked there, says "I have disabled the option fluidContainerBottles in EnderCore. I can't insert water bottles into the machine anymore, which I guess is intended behavior. At least it doesn't crash". Can you do the same thing in this pack?

**Modpack version (Do not use "latest")**

1.51

**Logs**

see linked issue

**Screenshots**

**Additional context**

**Comment by Ricket** [comment]
To repro this crash, drop a vanilla minecraft water bottle into this slot in the gui of the potion brewer:

![image](https://user-images.githubusercontent.com/196978/51447884-cfbffe00-1ce7-11e9-86bf-0ac7fc4010a0.png)

**Comment by NillerMedDild** [comment]
Will do :)
