### ISSUE TITLE
Upgraded Energy Input Hatch recipes missing

### ISSUE THREAD

**Issue by Altenius** [NillerMedDild/Enigmatica2Expert#671]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**

The Reinforced, Big, and Huge Energy Input Hatch are missing from JEI and are uncraftable.

Edit: the upgraded energy output hatches are missing as well.

**Modpack version (Do not use "latest")**

1.52

**Logs**

If applicable, please upload your crash report, or latest.log to [gist](https://gist.github.com/).

**Screenshots**

**Additional context**

**Comment by NillerMedDild** [comment]
That was mentioned in the changelogs.

**Comment by Altenius** [comment]
I don't see it mentioned in the changelog and I don't understand why this would be removed. Any recipe requiring more than 10RF/t is uncraftable in the modular machines.
