### ISSUE TITLE
quark marble wall uncraftable 

### ISSUE THREAD

**Issue by Dokend** [NillerMedDild/Enigmatica2Expert#672]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
Cant craft quark marble wall requires marble from quark and none spawns and cant chisel it either. 

**Modpack version (Do not use "latest")**
Enigmatia 2 Expert 1.52

**Logs**

If applicable, please upload your crash report, or latest.log to [gist](https://gist.github.com/).

**Screenshots**

**Additional context**

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.
