### ISSUE TITLE
Unify Coal Coke

### ISSUE THREAD

**Issue by FryoKnight** [NillerMedDild/Enigmatica2Expert#673]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**

Thermal Foundation's version of Coal Coke does not work in the Blast Furnace.

Crafting Coal Coke Blocks using Immersive Engineering Coal Coke yield Thermal Foundation's version, crafting them back into Coal Coke yield Thermal Foundation's version.
This effectively renders Coal Coke useless outside of burning normally if you craft blocks for storage or longer burn times.

**Modpack version (Do not use "latest")**

v1.52

**Logs**

N/A

**Screenshots**

**Additional context**

As a side note, people that are having this issue can use the Chisel from _**Chisel**_ in order to convert the blocks back to Immersive Engineering version.

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by FryoKnight** [comment]
Never mind... Seemed to have been something weird server side that was causing the issue where I could not put the _Thermal Foundation_ Coal Coke into the Blast Furnace.

Still slightly annoying though that you get _Thermal Foundation_ Coal Coke instead of _Immersive Engineering_'s, as you get it naturally and the 2 do not stack (for obvious reasons) without jumping through some hopes in order to make them a single stackable item...

**Comment by NillerMedDild** [comment]
Hmm true.

**Comment by FryoKnight** [comment]
I recommend going with _Immersive Engineering_ version of Coal Coke, seeing as it is more widely used by that mod. Evident by the only means of making it being the _Immersive Engineering_ Coke Oven, and that there is also Coke Dust added in also by _Immersive Engineering_.

Plus I think it's block form looks nicer. =w=
