### ISSUE TITLE
Minecraft crash when JEI is loading

### ISSUE THREAD

**Issue by Veyco00** [NillerMedDild/Enigmatica2Expert#675]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
My Minecraft crash when i try to load Enigmatica it's seem to come from the JEI recipes 

**Modpack version (Do not use "latest")**
1.52

**Logs**

If applicable, please upload your crash report, or latest.log to [gist](https://gist.github.com/).

**Screenshots**
![capture d ecran 2](https://user-images.githubusercontent.com/46900117/51487497-b2e90080-1da3-11e9-9a44-7cc4856fa797.png)

**Additional context**

**Comment by Veyco00** [comment]
I Also have that from the minecraft Launcher 
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Just Enough Items (jei)

**Comment by NillerMedDild** [comment]
You need to allocate more RAM to Minecraft, I recommend 6GB if your PC can handle it.

In the future, follow the issue template. Don't take a screenshot of your crash-report and send it, upload the crash-report and give me a link to it.
