### ISSUE TITLE
Revert defaultoptions/options.txt to difficulty:3

### ISSUE THREAD

**Issue by ArbitraryHubris** [NillerMedDild/Enigmatica2Expert#677]
**Issue Description**
Default options config in config/defaultoptions/options.txt now has difficulty set to 0 when it used to be 3.  I'm sure that this is not the experience intended for newly created worlds.  I may, however, not understand the impact correctly.

![](https://i.imgur.com/5OrEUKl.jpg)

**Modpack version (Do not use "latest")**
1.53

**Comment by NillerMedDild** [comment]
Err Woops. That's odd, I haven't updated the default options.

**Comment by NillerMedDild** [comment]
Hm. I just tested this on a completely new instance - The game starts in normal difficulty. It looks like the default options are ignored completely.
