### ISSUE TITLE
Forestry's Multi-Farm won't Harvest Pams Curry

### ISSUE THREAD

**Issue by flipwalker42** [NillerMedDild/Enigmatica2Expert#678]
**Question or Issue**
Pam's Harvestcraft Curry won't be harvested by a manual crop Forestry MultiFarm. Other Pam's items appear to be unaffected.

**Modpack Version**
1.53

**Additional Context**
Manually plant Curry plants, they mature, but won't get harvested automatically.

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
Looks like a lot of Pam's crops won't go in.

**Comment by NillerMedDild** [comment]
Reported on the Forestry tracker, here: https://github.com/ForestryMC/ForestryMC/issues/2358

**Comment by flipwalker42** [comment]
Ah, I see that. I had just found the giga pickle the other day and realized
it wouldn't go in either.I suppose I should have posted it on the Forestry
site rather than yours, my apologies, but thank you for looking into it!

**Comment by NillerMedDild** [comment]
No worries, it's good practice to report issues to the pack dev, as I could've done something to purposefully mess with it :)
