### ISSUE TITLE
Edited: Actually it works but with different blocks(what should be said in quest book)

### ISSUE THREAD

**Issue by NarigudoBR** [NillerMedDild/Enigmatica2Expert#679]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
when it's working there are particles around(but there are not!!). I waited hours ,but the wood and stone didn't got transformed(sadface). 

**Modpack version (Do not use "latest")**
1.53

**Logs**

If applicable, please upload your crash report, or latest.log to [gist](https://gist.github.com/).

**Screenshots**
![2019-01-21_23 25 23](https://user-images.githubusercontent.com/5056170/51506537-e80d4700-1dd3-11e9-9c6c-87601b80b1b5.png)

**Additional context**

**Comment by NarigudoBR** [comment]
this is how it should look like: 
![2019-01-21_23 43 54](https://user-images.githubusercontent.com/5056170/51507127-90240f80-1dd6-11e9-90ef-94957cf41eb5.png)

**Comment by NarigudoBR** [comment]
> Its arcane stone not normal stone and I think its infused wood not normal

So if it should be, why it's not said in the book?!!

**Comment by ArbitraryHubris** [comment]
it's a change made for the modpack so it doesn't show in the lexica botania.  It does show the right ingredients in JEI

**Comment by NarigudoBR** [comment]
> it's a change made for the modpack so it doesn't show in the lexica botania. It does show the right ingredients in JEI

it should be listed in the quest book also, instead of: "look at the lexica botanica for more details"

**Comment by NillerMedDild** [comment]
It is listed in the questbook, look under Livingrock and Livingwood. If you don't see it, use the update command `/bq_admin default load`
