### ISSUE TITLE
Can’t craft Golemancers bell

### ISSUE THREAD

**Issue by Cnights** [NillerMedDild/Enigmatica2Expert#68]

**Comment by NillerMedDild** [comment]
Which Crystals did you use?

**Comment by Cnights** [comment]
I used treated sticks and the standard rock crystals from astral sorcery that you mine up. Those show they are ore dicted.

**Comment by NillerMedDild** [comment]
Yeah they're supposed to be atleast - Fixed in next update, you'll only be able to use the normal Rock Crystals though.
