### ISSUE TITLE
A state where certain actions cannot be preformed after returning from the Nether.

### ISSUE THREAD

**Issue by lirannl** [NillerMedDild/Enigmatica2Expert#680]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Question or Issue**

Inability to do certain actions after returning from the nether (I haven't tested the End or any Advanced Rocketry dimensions

**Modpack Version**

1.53

**Additional Context**

I haven't tested whether the issue occurs while in the nether or only once back in the overworld, however, once back, I cannot access other "pages" of medium/large crates, and if I sleep, I cannot leave the bed - the buttons exist, they simply do not respond. Once in bed, I'm stuck in bed until I force close Minecraft and start it back up, which fixes the entire issue until the next time I go in the nether. The issue seems to occur even if I return without using the portal (such as using the brown magic ability of Tinker's). There may be more things that cannot be done in this state, I can only check up to a certain point (very early Thermal Expansion).

The issue does not occur when returning from a Compact machine.

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by MorganSimic** [comment]
The bed issue is an age old bug in Minecraft. It should be fixed by some form of bed patches. I'm not to familiar with the technicalities though. But you can use /kickme anytime you get stuck in bed to kick yourself from the server. That fixes the issue aswell and prevents a reboot. But I never heard of the other issues, the bed one happened to me on the server a while ago aswell.

**Comment by NillerMedDild** [comment]
It sounds similar to the after effects of dimension jumping marking you as dead.

**Comment by NillerMedDild** [comment]
I've tried fixing this multiple times, I'm afraid I'm unable to, at least at the moment.
