### ISSUE TITLE
Applied Energistics cell recipes 

### ISSUE THREAD

**Issue by gijsc1** [NillerMedDild/Enigmatica2Expert#685]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
the standard AE storage cell requires an iron chest, but the fluid cells still use the default recipe. The casings of these cells are interchangeable, so shift right clicking a fluid storage cell gives you the casing which can then be used to craft a regular storage cell using its default cost.
It makes no sense to have a more expensive recipe if the cheap version can still be used.
I would recommend to have all kinds of AE2 and extra cells storage cells use the same casing recipe, either with or without the iron chest.

**Modpack version (Do not use "latest")**
1.53

**Logs**

If applicable, please upload your crash report, or latest.log to [gist](https://gist.github.com/).

**Screenshots**

**Additional context**

**Comment by NillerMedDild** [comment]
Thanks for the report.
