### ISSUE TITLE
AE2 autocrafting voids materials when crafting Opinium Core (Mediocre)

### ISSUE THREAD

**Issue by xoxfaby** [NillerMedDild/Enigmatica2Expert#686]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**

As title states, crafting job is sent out and never happens, cancelling it all the materials are gone. 

**Modpack version (Do not use "latest")**

1.53

**Logs**

Nothing

**Screenshots**

**Additional context**

**Comment by NillerMedDild** [comment]
Thank you for the report. I need your `latest.log` file to troubleshoot the issue.

The `latest.log` file can be found in the `logs` folder of the Enigmatica modpack folder.

**Comment by xoxfaby** [comment]
I assume you need it from the server?

**Comment by xoxfaby** [comment]
There is nothing in the log when it happens.

**Comment by xoxfaby** [comment]
scratch the original issue ( maybe ? ) 

AE2 autocrafting was putting that materials into a nearby storage crate for some reason

http://shr.cx/Bo0w.png

<blockquote></blockquote>
