### ISSUE TITLE
(Question)Is resturbed mob spawner working?

### ISSUE THREAD

**Issue by NarigudoBR** [NillerMedDild/Enigmatica2Expert#688]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Question or Issue**

Is(extrautilities 2) resturbed mob spawner working?

**Modpack Version**

**Additional Context**

**Comment by NarigudoBR** [comment]
tried to do a pink slime one, but apparently it isn't working

**Comment by NillerMedDild** [comment]
Pink Slime is very very picky. I don't think you can use Resturbed Mob Spawners for them - You probably need the Industrial Foregoing one.
