### ISSUE TITLE
Making Survivalist Generator completes Extra Utilities 2 Gate quest.

### ISSUE THREAD

**Issue by JaiSachdeva** [NillerMedDild/Enigmatica2Expert#689]
**Issue Description**

I created a survivalist generator out of pretty early game RF requirements. And it completed the ExU2 gate quest and opened up ExU2 for me. 

**Modpack version 1.51**

**Comment by NillerMedDild** [comment]
Thanks for letting me know :)

**Comment by NillerMedDild** [comment]
I'm afraid this can't be fixed, due to how the Extra Utilities machines use NBT data.
