### ISSUE TITLE
NuclearCraft's Urnanium Ingots not being consumed by Extreme Reactor

### ISSUE THREAD

**Issue by gamercraft30x** [NillerMedDild/Enigmatica2Expert#69]
#### Modpack version (Do not use "latest")
1.35

#### Issue Description
The reactor will only consume the Immersive Engineering uranium ingots.

-Liz

**Comment by NillerMedDild** [comment]
The Expert pack is currently on version 1.23, did you mean to report this at the normal pack's issue tracker?

**Comment by gamercraft30x** [comment]
I did yes, sorry about that.

**Comment by gamercraft30x** [comment]
Yes, I was using Thermal Expansions' Redstone Furnace to smelt the uranium ore and the furnace no longer produces the regular uranium as of the most recent update, 1.35. It now produces the Uranium Oxide Ingot.

**Comment by NillerMedDild** [comment]
The Redstone Furnace is bugged at the moment, it produces stuff from the wrong mods, working on fixing it :)
You may be able to change the Uranium Oxide Ingot by dropping it in the world.

**Comment by gamercraft30x** [comment]
OK thank you for your help, much appreciated.

**Comment by NillerMedDild** [comment]
Sure thing, thanks for reporting it.

**Comment by NillerMedDild** [comment]
It turns out the mistake was on my side, sorry about that :)
