### ISSUE TITLE
Can't get the cardoard box with content out of the me system

### ISSUE THREAD

**Issue by NarigudoBR** [NillerMedDild/Enigmatica2Expert#690]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
you can get the cardboard box empty in and out, but the ones with a block, you can't get out of the me system.

**Modpack version (Do not use "latest")**
1.53

**Logs**
nope, no log is generated for this action
If applicable, please upload your crash report, or latest.log to [gist](https://gist.github.com/).

**Screenshots**
![2019-01-22_15 32 44](https://user-images.githubusercontent.com/5056170/51553831-ff434780-1e5a-11e9-94dc-8d5eff8d130a.png)

**Additional context**

**Comment by NillerMedDild** [comment]
That's a longstanding issue I'm afraid, no fix in sight. You can get it out with an I/O Port and a Storage Bus on a chest with high priority.

**Comment by NarigudoBR** [comment]
Thx
