### ISSUE TITLE
More Exploration

### ISSUE THREAD

**Issue by RegulusImpact99** [NillerMedDild/Enigmatica2Expert#692]
Sorry this is literally my first time using git hub so hopefully I'm doing this right.  I would like to suggest more exploration for E2E. I personally love just exploring the world going into ruins and searching for treasure. I feel like E2E could use some more of this. 

Also it would be cool if we could build a colony. I don't remember the mod name but there's one that lets you build like gaurds, lumberjacks, etc...

Anyway a version of E2E with these in the progression would be really cool imho. Thanks for reading!

**Comment by NillerMedDild** [comment]
Welcome to GitHub :D

The progression is set and I will not be adding a major mod like MineColonies into it at this point, plus I don't think village building fits the expert theme at all.

More exploration is a good idea though, I'll see what I can come up with :)

**Comment by NillerMedDild** [comment]
I'm sorry but I will not be working on this.
