### ISSUE TITLE
Make Unique Ores Available from Orbital Laser Drill

### ISSUE THREAD

**Issue by mike347** [NillerMedDild/Enigmatica2Expert#693]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
The Advanced Rocketry orbital laser drill does not seem to produce anything other than vanilla ores.
No Dilthium, rutile/titanium, etc. etc.
Possible to add this?
Possibly make the orbital laser drill itself require a silk touched rutile/titanium, and/or other ores only available on other planets so that players have to mine there manually at least once before building the drill?

**Modpack version (Do not use "latest")**

1.50a

**Logs**

If applicable, please upload your crash report, or latest.log to [gist](https://gist.github.com/).

**Screenshots**

**Additional context**

**Comment by NillerMedDild** [comment]
I thought I had added that already tbh :P Sure thing! 

May I see a screenshot of your Orbital Laser Drill setup? I've never seen it in action :)

**Comment by mike347** [comment]
It really looks rather plain, it has no actual laser or particle effects...but here's my space station with laser drill under construction in orbit of Titan.
https://imgur.com/a/4yLxdOS

**Comment by NillerMedDild** [comment]
The Space Station looks really cool though, thanks for sharing!

**Comment by NillerMedDild** [comment]
The list of ores you can get from Orbital Laser Drilling as of 1.54:

oreIron
        oreGold
        oreCopper
        oreTin
        oreRedstone
        oreDiamond
		oreIridium
		oreTitanium
		oreDiamond
		oreEmerald
		oreAstralStarmetal
		oreDimensionalShard
		orePlatinum
		oreMithril
		oreDilithium

**Comment by Shirkit** [comment]
In 1.56 the "oreDimensionalShard" that the drill is mining has a broken texture, and when you place it on the world it crashes. Also, it has no uses and can't be smelted or processed.

**Comment by NillerMedDild** [comment]
Could you update to 1.58 and check if it still happens? :)

**Comment by Shirkit** [comment]
Can confirm that on 1.58 it still mines broken texture, no uses Dimensional Shard Ore that crashes when placed.

**Comment by NillerMedDild** [comment]
Thanks!
