### ISSUE TITLE
Pech's keep on crashing my Minecraft

### ISSUE THREAD

**Issue by dadaemon** [NillerMedDild/Enigmatica2Expert#694]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
During random moments when a Pech is in my mob spawn/kill room my Minecraft locks up and is unresponsive. When trying to close the application it crashes. It always crashes with "Description: Ticking Entity"

**Modpack version (Do not use "latest")**
Version: 1.53

**Logs**
Latest log: https://gist.github.com/dadaemon/9b656189247d8430871790b8ce324fb7
Previous ones: https://gist.github.com/dadaemon/482b2c87e9782ac70052d4b4e249e451
All logs show the same location of the Pech (in my mob spawn room.)

Can add more logs if needed but all come down to the same error and same entity.

**Screenshots**
Screenshot of empty mob spawn room: https://imgur.com/a/79lmR8j

**Additional context**
When my mob spawn is "off" (by lighting up the room) I haven't had any issues. The room is a 11x11x3 box with cursed earth. Inside are vector plates pushing mobs into the center 3x3 which are filled with Player Traps. The items are being picked up by a Cyclic Item Collector. (It is possible that the storage was full and therefor a lot of items were lying on the ground.)

After restarting everything works fine again until there is a new Pech spawned that has this issue. Note: This does not happen with all Pech's!

I have also seen this error mentioned in the Thaumcraft GitHub - https://github.com/Azanor/thaumcraft-beta/issues/1577 - So this is probably not a true bug for this pack, but just wanted to let you and others know.

**Comment by NillerMedDild** [comment]
Damn, I thought this bug had been fixed a long time ago. Sadly Thaumcraft is no longer being maintained, so we can only fix the symptom instead of the bug.

Replace the contents of the file `forge.cfg` found in the `config` folder with the content of this pastebin link https://pastebin.com/wK8E2ME3

That will remove the erroring entities instead of crashing.

**Comment by dadaemon** [comment]
Thanks for the quick reply! I have changed my config.

For anyone looking to fix this without changing your whole forge.cfg, search for below options and change them to true.

```
    # Set this to true to remove any Entity that throws an error in its update method instead of closing the server and reporting a crash log. BE WARNED THIS COULD SCREW UP EVERYTHING USE SPARINGLY WE ARE NOT RESPONSIBLE FOR DAMAGES.
    B:removeErroringEntities=true

    # Set this to true to remove any TileEntity that throws an error in its update method instead of closing the server and reporting a crash log. BE WARNED THIS COULD SCREW UP EVERYTHING USE SPARINGLY WE ARE NOT RESPONSIBLE FOR DAMAGES.
    B:removeErroringTileEntities=true
```

**Comment by NeosGhost** [comment]
Bump thanks niller

**Comment by NillerMedDild** [comment]
@NeosGhost What's up?
