### ISSUE TITLE
Cooking for Blockheads #No Filter Crash

### ISSUE THREAD

**Issue by blichte1** [NillerMedDild/Enigmatica2Expert#695]
Version 1.53

When using the Cooking for Blockhead #no filter book and clicking on the recipe for Forestry Ambrosia, the server crashes, but does not bring down the game entirely. Perhaps remove the recipe?

**Comment by NillerMedDild** [comment]
The issue template is there for a reason, don't delete it. I need the crash report, as the issue template stated.

**Comment by blichte1** [comment]
Ok. Apologies for deleting the template. I will get you the crash report as soon as I can -- it will be some time next week.

**Comment by blichte1** [comment]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**

As per my previous description, when using the Cooking for Blockheads #no filter book and clicking the recipe for Forestry Ambrosia the game crashes ("Connection Lost...") out to a searching for server screen in the Minecraft app (I assume this might be because the world is treated as a server in the internal workings of Minecraft, but to be sure, I am not running this on a server).  Re-logging into the world using normal single player mode and everything is ok. The crash is repeatable and consistent.

**Modpack version (Do not use "latest")**

1.53

**Logs**

Please see latest.log attached.
[latest.log](https://github.com/NillerMedDild/Enigmatica2Expert/files/2800389/latest.log)


**Screenshots**

N/A

**Additional context**

The error works both when the #no filter book is in hand and on recipe table. Please let me know if there's any other question...

**Comment by NillerMedDild** [comment]
Much much better, thank you :)

**Comment by NillerMedDild** [comment]
It cannot be reproduced atm.
