### ISSUE TITLE
Slime Saplings should generate the corresponding slime blocks in the phytogenic insolator.

### ISSUE THREAD

**Issue by awebneck** [NillerMedDild/Enigmatica2Expert#696]
**Is your feature request related to a problem? Please describe.**
Blue and Purple Tinker's Construct slime saplings - when used in a TE phytogenic insolator - generate congealed green slime blocks, ignoring the color of the sapling. This is frustrating as my expectation would be that they'd generate the corresponding colored slime (at similar or varying rates, depending on balance).

**Describe the solution you'd like**
I'd like Blue and Purple Tinker's Construct slime saplings to generate the corresponding colored slime block / balls in the phytogenic insolator rather than only green ones.

**Additional context**
![2019-01-24_09 59 13](https://user-images.githubusercontent.com/153561/51690531-7ba26b80-1fbe-11e9-920b-f6e23a452928.png)

**Comment by NillerMedDild** [comment]
I'll get that fixed :)

**Comment by NillerMedDild** [comment]
The output is correct, the Phytogenic Insolator gives you the logs, not the leaf drops.
