### ISSUE TITLE
Mekanism cardboard box on Matter fabricator bugged out

### ISSUE THREAD

**Issue by BanzaiRun** [NillerMedDild/Enigmatica2Expert#697]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
When moving a matter fabricator with the Mekanism cardboard box, the placed block is invalid

**Modpack version (Do not use "latest")**
1.53 (Release)

**Logs**

If applicable, please upload your crash report, or latest.log to [gist](https://gist.github.com/).

**Screenshots**

**Additional context**
Probably me being a derp and this is already well known. Perhaps there's a blacklist it could be added to?

**Comment by NillerMedDild** [comment]
It is blacklisted, it just doesn't respect the blacklist for some reason :p yep it's known

**Comment by NillerMedDild** [comment]
Will do :D thanks for the report.
