### ISSUE TITLE
Marble cant be chiseled

### ISSUE THREAD

**Issue by HSavageheart** [NillerMedDild/Enigmatica2Expert#698]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
Normal Marble not being able to Chisel

**Modpack version (Do not use "latest")**
1.53

If applicable, please upload your crash report, or latest.log to [gist](https://gist.github.com/).

**Screenshots**
![image](https://user-images.githubusercontent.com/47013090/51711618-d96d9c80-202c-11e9-901d-136081c07194.png)

Not able to chisel marble for building

**Comment by NillerMedDild** [comment]
Did you actually try or did you just check JEI?

**Comment by HSavageheart** [comment]
yea checked only JEI my bad.

**Comment by NillerMedDild** [comment]
No worries.
