### ISSUE TITLE
Crash report: java.lang.NoSuchFieldError: partialTicks. please help, my world just crashes everytime i open it.

### ISSUE THREAD

**Issue by Hunglyer** [NillerMedDild/Enigmatica2Expert#699]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**

**Modpack version (Do not use "latest")**

**Logs**

If applicable, please upload your crash report, or latest.log to [gist](https://gist.github.com/).

**Screenshots**

**Additional context**

**Comment by Discomanco** [comment]
The template is there to be used, not to be ignored.
Please use it correctly in a new issue
