### ISSUE TITLE
Thermal dynamics fluiduct recipe unchanged (Balance)

### ISSUE THREAD

**Issue by Electrofried** [NillerMedDild/Enigmatica2Expert#7]
#### Issue Description
Thermal dynamics fluiducts (not opaque) only require copper and glass to craft, this seems out of place with the rest of the thermal pipes requirements in the pack. 
#### What you expected to happen
Perhaps some slightly harder glass or plates be required to craft? 
#### Modpack version (Do not use "latest")
1.03a
#### Your most recent log file where the issue was present

[pastebin/gist/etc link here]

**Comment by NillerMedDild** [comment]
They can't move much other than water, so I left them out of the balancing.
