### ISSUE TITLE
Regular Crashes in the Overworld

### ISSUE THREAD

**Issue by koncan5** [NillerMedDild/Enigmatica2Expert#700]
**Question or Issue**

I am having regular crashes in the overworld.

**Modpack Version**

1.53, but existed in 1.47

**Additional Context**

Wish I could give some, but these crashes seem to happen randomly with no connection, I've even crashed in the nether instantly after a death but before respawning.

[crash-2019-01-25_16.24.47-server.txt](https://github.com/NillerMedDild/Enigmatica2Expert/files/2794773/crash-2019-01-25_16.24.47-server.txt)

**Comment by NillerMedDild** [comment]
I'm afraid the crashlog isn't helpful, try using Jar launcher instead of Native - It's an option in the Twitch App's Minecraft settings.

**Comment by ArbitraryHubris** [comment]
It may be a red herring, but it's never advised to have vastly different max and min sizes for java applications.  Java just doesn't handle the freedom well.  

Try setting your min and max to the same value:

Current values:
`-Xmx7991m -Xms256m`

Try:
`-Xmx7991m -Xms7991m`
