### ISSUE TITLE
Receipt overwrite - thermal dynamics

### ISSUE THREAD

**Issue by knord1** [NillerMedDild/Enigmatica2Expert#701]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
The sub-ducts for thermal dynamics have the same receipt as the main duct.
ex. Dense Itemduct is not craftable since it uses the same receipt as Itemduct.

(or this might be intentional?)

**Modpack version (Do not use "latest")**

1.53

**Logs**

**Screenshots**

**Additional context**

**Comment by MorganSimic** [comment]
Did you check all the pages in JEI? When you click one you get all the recipes for all duct types. There should be one for each of dense and vacuum ducts. JEI handles that a bit weird or Thermal does provide the information a bit weird. Don't know.

**Comment by knord1** [comment]
It seems to be the "Dense itemduct (opaque)" that is missing.

All other dense are showing up.

And of course I only clicked the opaque itemduct so I never saw the translucent version.

Thank you for the help, MorganSimic.

**Comment by NillerMedDild** [comment]
The Dense/Vacuum versions of Opaque Ducts are indeed disabled, due to their price being significantly lower than the non-opaque variety.
