### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by emresdas1** [NillerMedDild/Enigmatica2Expert#704]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
not really sure whats going on, I can play for around an hour or sometimes less before the game freezes and stops responding

**Modpack version (Do not use "latest")**
1.5.1

**Logs**

If applicable, please upload your crash report, or latest.log to [gist](https://gist.github.com/).

**Screenshots**

**Additional context**
i dont understand why this happens but its annoying and i want help.

**Comment by NillerMedDild** [comment]
I need the crash report to help you.

**Comment by emresdas1** [comment]
How would I get the crash report, idk where I would look

**Comment by NillerMedDild** [comment]
If you're using the Twitch App, `C:\Users\UserName\Documents\Curse\Minecraft\Instances\Enigmatica 2 Expert\crash-reports`
