### ISSUE TITLE
Thaumc Tinkerer smokey quarts 

### ISSUE THREAD

**Issue by Dokend** [NillerMedDild/Enigmatica2Expert#705]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**

Smokey quarts in Thaumonomicon can't be completed stuck on completion. 

**Modpack version (Do not use "latest")**
Enigmatica 2 Expert 1.53

**Logs**

If applicable, please upload your crash report, or latest.log to [gist](https://gist.github.com/).

**Screenshots**
https://imgur.com/a/t4ZXHih

**Additional context**

**Comment by NillerMedDild** [comment]
This is a known issue, the research has not been properly implemented yet I'm afraid.
