### ISSUE TITLE
Buff NuclearCraft Fission Reactors (Double output)

### ISSUE THREAD

**Issue by Miisi** [NillerMedDild/Enigmatica2Expert#706]
**Is your feature request related to a problem? Please describe.**

I don't think the amount of energy they produce is enough. They take a lot of materials to build and are quite hard to keep up running (you need a steady supply of uranium/thorium/whatever) in comparison to the Fusion Reactor from the same mod (or other cheaper alternatives). 

**Describe the solution you'd like**

Buffing the amount of RF/t they produce may incentive players to use them. Adding a by-product from end/mid-tier depleted fuel to the Anglesite recipe could work too.

**Additional context**

**Comment by NillerMedDild** [comment]
I don't know about adding by-products, the Fission reactions are a bit convoluted as it is :P but I do agree they could use a buff.

**Comment by xmiso** [comment]
What I meant was that maybe adding something made from processing end-tier depleted fuel (Californium-252 for example) to the Anglesite recipe might incentive players to use a Fission Reactor. 

I think that some recipes use the Californium RTG, but Californium-250 can be found in Dragon Lairs, which makes Fission Reactors a bit useless :p

**Comment by NillerMedDild** [comment]
Ah I See. I'll think about it :)
