### ISSUE TITLE
Adding magic bees/career bees

### ISSUE THREAD

**Issue by jestingstud** [NillerMedDild/Enigmatica2Expert#707]
**Is your feature request related to a problem? Please describe.**
Not related to any known problems.

**Describe the solution you'd like**
Seeing how Forestry and Gendustry are already on the pack it would be cool to have more options for bee's by adding in Magic Bees mod and Career Bees mod.

**Additional context**

**Comment by NillerMedDild** [comment]
That would require extensive tweaking, to ensure bee products aren't obtainable before their normal counterpart. It's too much work to be worth it imo, sorry.

**Comment by jestingstud** [comment]
nah it's all good was just an idea but i understand. Thank you for responding though.

**Comment by Risa-G** [comment]
If I were to make balancing changes for an the mod addition and submit it as a PR, would adding extra bees be something on the table?

**Comment by NielsPilgaard** [comment]
I'm afraid not, no.
