### ISSUE TITLE
The tiny piles of dust for most metals yield more thaumcraft aspects then the normal dust themselves

### ISSUE THREAD

**Issue by Bucho831** [NillerMedDild/Enigmatica2Expert#708]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**

**Modpack version (Do not use "latest")**

**Logs**

If applicable, please upload your crash report, or latest.log to [gist](https://gist.github.com/).

**Screenshots**

**Additional context**

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
So when you say most metals, you mean only Iron? :P
