### ISSUE TITLE
Basic Lithium Ion Battery Easier Recipe

### ISSUE THREAD

**Issue by CalvinJJ** [NillerMedDild/Enigmatica2Expert#709]
**Issue Description**

The Basic Lithium Ion Battery in NuclearCraft requires 4 elite plating to craft. This seems a bit off, as they crafts into the advanced batteries, which require advanced plates, then DU batteries which require DU plates, then elite batteries which require... elite plates again. So, I'm guessing the basic batteries should require basic plating, or at least something else more in line with the progression of the upgraded batteries.

These are fairly inauspicious power storage blocks that don't seem to be used in anything else as far as I can tell. Given the level of complexity in producing some of other required materials, the amount of storage they provide seems appropriate for their tier.

**Modpack version (1.53)**

**Logs**

**Screenshots**

**Additional context**

**Comment by NillerMedDild** [comment]
I'll get that fixed, thanks for the report :)
