### ISSUE TITLE
IC2 Basic Machine Casing breaks down into 8 iron ingots

### ISSUE THREAD

**Issue by ArbitraryHubris** [NillerMedDild/Enigmatica2Expert#711]
![](https://i.imgur.com/R20aS9g.jpg "IC2 Casing to Iron Ingots")

I'm not sure if this is a bug or a feature.  I do think it's very easy for someone to mistakenly think they're breaking down an iron block rather than an ic2 basic casing.  

**Modpack version (Do not use "latest")**
1.53

**Comment by ArbitraryHubris** [comment]
for some strange reason, the basic casing is often placed in the crafting terminal crafting area after shift-clicking the product of a recipe into your inventory, even when the casing is not part of the recipe you're crafting.

**Comment by NillerMedDild** [comment]
It's intended :)

The item left in the crafting area clitch might be fixed soon, I know there has been an attempt atleast.
