### ISSUE TITLE
Cobalt Blocks in Mekanism Ore Processing Recipe Chain

### ISSUE THREAD

**Issue by wb808tec** [NillerMedDild/Enigmatica2Expert#712]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
Block of cobalt used in Mekanism ore processing chain

**Modpack version (Do not use "latest")**
Enigmatica 2 Expert 1.53
 

**Logs**

If applicable, please upload your crash report, or latest.log to [gist](https://gist.github.com/).

**Screenshots**
https://imgur.com/a/U4sjbxp

**Additional context**

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by OneEyeMaker** [comment]
@NillerMedDild 
Related issue:
Cobalt block has wrong OreDictionary entries: ```oreArdite``` and ```oreCobalt```.
I think that causes incorrect recipes with Mekanism.

**Comment by ObsCracker** [comment]
Not only Mekanism recipes but almost all (Thermal Expansion, Actually Additions, Integrated Dynamics, ...)
