### ISSUE TITLE
Tick Accelerating causing crash

### ISSUE THREAD

**Issue by Basedgod199** [NillerMedDild/Enigmatica2Expert#713]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
Using time in a bottle on a pulverizer is crashing my game. not entirely sure why as removing the block from my setup (see screenshot) works just fine while being tick accelerated.

**Modpack version (Do not use "latest")**

1.53

**Logs**
https://pastebin.com/Ch1p1nQu - Crash Report

If applicable, please upload your crash report, or latest.log to [gist](https://gist.github.com/).

**Screenshots**

![2019-01-27_15 16 05](https://user-images.githubusercontent.com/32063145/51808261-853e0480-2246-11e9-9aa5-273f2c08c914.png)

**Additional context**

**Comment by NillerMedDild** [comment]
It looks like the attached itemduct is doing the crashing, I'll report the bug asap :)

**Comment by NillerMedDild** [comment]
The mod dev will not be fixing this I'm afraid.
