### ISSUE TITLE
Add the Gas Conduits mod

### ISSUE THREAD

**Issue by OmaiGrundles** [NillerMedDild/Enigmatica2Expert#718]
**Is your feature request related to a problem? Please describe.**
I personally have been trying to avoid AE2 in this pack as sort of a stupid challenge, but other than that, there isn't really a good way to move gasses around, as xnet is... unreliable at best when it comes to gasses. 

**Describe the solution you'd like**
A few weeks ago a mod called Gas Conduits was released, an addon for EnderIO that adds gas conduits! It has 60k downloads and nobody has mentioned any issues with the mod, so it seems pretty stable.

**Additional context**
Link: https://minecraft.curseforge.com/projects/gas-conduits
I could test it for a while on my own world if you want.

**Comment by btbenedi** [comment]
+1

This is one of the last things in my base using mekanism pipes/tubes/cables. These conduits would remove that.

**Comment by NillerMedDild** [comment]
I will be adding this for 1.54
