### ISSUE TITLE
Redstone/Glowstone No Longer Smeltable in TiC Smeltery

### ISSUE THREAD

**Issue by ObsCracker** [NillerMedDild/Enigmatica2Expert#719]
**Issue Description**
EnderIO Energy Conduits can be crafted easyly in early stages of the game with not even reaching EnderIO gate. The Conductive Iron Ingot and Energetic Alloy Ingot can be made using the Tinker's Smeltery allowing to make conduits in early game

**Modpack version (Do not use "latest")**
1.53

**Logs**

N/A

**Screenshots**

N/A

**Additional context**

N/A

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.
