### ISSUE TITLE
No quest and no party on server

### ISSUE THREAD

**Issue by Karghast** [NillerMedDild/Enigmatica2Expert#721]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**

I started a server with a friend, he can join and we can play normally, but when we open the "quest book", we see nothing, the questbook is empty and there is no way we can see the quests. I also tried to reinstall the server, the modpack, forge, and also tried another version of the game and server (i tried both 1.53 and 1.52 versions). Meanwhile i can do quests if i'm playing offline.

 I also noticed that we cannot create and join a party toghether, when i click the "create a party" button, nothing happens. Have someone any idea on how to fix that? Thank you.

**Modpack version (1.53)**

**Logs**

If applicable, please upload your crash report, or latest.log to [gist](https://gist.github.com/).

**Screenshots**
![minecraft questbook](https://user-images.githubusercontent.com/47146062/51911221-90716b80-23d1-11e9-93ce-d97b6c6fe551.png)

![minecraft test party](https://user-images.githubusercontent.com/47146062/51911222-90716b80-23d1-11e9-99ce-62f28a5422ec.png)
**Additional context**

**Comment by NillerMedDild** [comment]
That's odd - Is it a LAN game or dedicated server?
Either way, `/bq_admin default load` should make the quests reappear, but I don't know about the party.

**Comment by NillerMedDild** [comment]
Maybe 1.54 fixes it :P

**Comment by Karghast** [comment]
> That's odd - Is it a LAN game or dedicated server?
> Either way, `/bq_admin default load` should make the quests reappear, but I don't know about the party.

I downloaded the server pack from the website of the modpack, then i set it up and started on my PC. 
BTW the /bq_admin default load won't work, it tells me that the command is unknown.

**Comment by NillerMedDild** [comment]
If that command is unknown the server is not setup correctly. Did you follow the instructions on the download page?

**Comment by Karghast** [comment]
> If that command is unknown the server is not setup correctly. Did you follow the instructions on the download page?

I think i did, but at this point i doubt it. Where can i find the instructions for the server setup? Thanks

**Comment by NillerMedDild** [comment]
## Installing

- Download the zipfile.
- Extract it to an empty folder.
- If you want to change RAM usage, Java arguments etc, see the "settings" file.
- Double click "ServerStart". The window that appears will guide you through the rest.

## Updating

- Make a backup of your server folder.
- Remove the config, mods, schematics and scripts folders. If you've made custom configurations and/or mod changes, make sure these are reapplied after the last step.
- Extract the zip into your server folder and overwrite.

Note: This will override your settings changes, so make sure to change them back afterwards, if needed. If you don't want to override the settings file, you can change the forge version in it manually.


Feel free to contact me if you need any help, preferably on Discord.
Credit to the AllTheMods Team, for their ServerStart script.

**Comment by Karghast** [comment]
> ## Installing
> * Download the zipfile.
> * Extract it to an empty folder.
> * If you want to change RAM usage, Java arguments etc, see the "settings" file.
> * Double click "ServerStart". The window that appears will guide you through the rest.
> 
> ## Updating
> * Make a backup of your server folder.
> * Remove the config, mods, schematics and scripts folders. If you've made custom configurations and/or mod changes, make sure these are reapplied after the last step.
> * Extract the zip into your server folder and overwrite.
> 
> Note: This will override your settings changes, so make sure to change them back afterwards, if needed. If you don't want to override the settings file, you can change the forge version in it manually.
> 
> Feel free to contact me if you need any help, preferably on Discord.
> Credit to the AllTheMods Team, for their ServerStart script.

I tried again with your instructions and i cannot see the quest as before. i don't know what i'm doing wrong, i don't touch the other files, i just write the IP in the server file and start the server. Am i doing something wrong?

I also noticed that when i enter the server, i do not spawn with the questbook in my inventory, meanwhile if i start an offline world i do spawn with it.

**Comment by NillerMedDild** [comment]
How do you start the server? 
Please stop quoting, it makes the email preview hard to read :)

**Comment by Karghast** [comment]
Sorry for the quote.
At first when i download the server, i run the "ServerStart.bat" file, i let him complete and then i edit the "Server.properties" file just adding my IP, then i run the "minecraft_server.1.12.2.jar", i let him complete and i can enter the server from the game, when i do all this, my quests are not available as told before.

**Comment by NillerMedDild** [comment]
Okay, you're launching a vanilla server. The ServerStart.bat is what you need to use to actually start the server. If you need to launch a jar file, launch the forge universal file.
