### ISSUE TITLE
Add magnum torches or similar

### ISSUE THREAD

**Issue by Tsuyurin** [NillerMedDild/Enigmatica2Expert#722]
**Is your feature request related to a problem? Please describe.**
In addition to automating and progressing through the expert quests, a big part of my enjoyment comes from building a nice base. However, it's frustrating to hide powered lanterns everywhere to prevent mob spawning in areas of the base that are deliberately dimly lit for aesthetic reasons. And the Aversion Obelisk is terribly far down the tech tree and inconvenient to run for what is mostly getting rid of nuisance mob spawns.

**Describe the solution you'd like**
I'd love to see magnum torches or a similar mod added and preferably placed somewhere reasonably early in the progression tree. After e.g. Quantum Armor mobs aren't much of a threat, so being able to get rid of mob spawns in your base in convenient fashion is more of a quality of life improvement for builders.

As an alternative, the Aversion Obelisk could be tweaked to be available earlier, but this is less convenient and only useful if it works with loot capacitors (else the range would be a pittance).

**Additional context**

**Comment by DanielSchuerhoff** [comment]
Last playthrough of E2E I build a small mobfarm early, got quantum armor pretty fast (1-2 days of chunkloading) and then scavenged like 11 candles in a few hours by just flying around and looting about 40 villages, which I used to secure the 9x9 chunk area of my base (1/3 is actually a pretty decent chance). Sure it's a lil bit hard, but then again this is a progression modpack, in which I think the peace candle is pretty reasonably balanced.
Crafting a peace candle? Maybe that would fit Thaumcraft's theme with a big-ass dangerious infusion. That would probably not be too cheap to keep in balance with the obelisks from EnderIO, but then again you could skip the exploration that way :)

However, just some thoughts. I aint the dev or anyone who can decide anything ¯\_(ツ)_/¯

**Comment by NikkoScript** [comment]
Astral sorcery Lucerna ritual is buffed in E2:E it prevent mob spawning around 256 block in every direction without any focused lens, you can reach more 600 meter with 5 lens ...

**Comment by Tsuyurin** [comment]
Astral Sorcery... I had completely forgotten it had a way to do the same. I've been stuck on a low tier altar because I was stuck on lenses, but may have to find a way to force more progress for this purpose. Thanks.

**Comment by NillerMedDild** [comment]
I think set-and-forget mob spawn blockers are too easy for an expert pack, I think Powered Lanterns and Peace Candles are a bit OP as it stands :)
