### ISSUE TITLE
Flux JEI

### ISSUE THREAD

**Issue by blarghhh** [NillerMedDild/Enigmatica2Expert#726]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
JEI still shows that throwing redstone into lava gives flux. 

**Modpack version (Do not use "latest")**
1.22

**Logs**

If applicable, please upload your crash report, or latest.log to [gist](https://gist.github.com/).

**Screenshots**

**Additional context**

**Comment by NillerMedDild** [comment]
Checking if I actually disabled before filing another issue, I asked here: https://github.com/SonarSonic/Flux-Networks/issues/278

**Comment by BanzaiRun** [comment]
No reply from SS then?
Flux no longer "craftable" in lava now either. (I'm sure it was pre 1.56)

**Comment by NillerMedDild** [comment]
Nothing yet no, is the JEI entry still there? :P

**Comment by BanzaiRun** [comment]
I'm SURE that's rhetorical ;)

It's not like anyone would be hurting for black quartz when flux networks become viable anyway /shrug

**Comment by blarghhh** [comment]
> Nothing yet no, is the JEI entry still there? :P

yeah. the recipe is still in JEI. but the recipe doesnt work anymore. version 1.24

**Comment by MaxNeedsSnacks** [comment]
Created a PR on JETIF that should hopefully fix this once merged (or once the JETIF author finds a better solution) ^^

**Comment by NillerMedDild** [comment]
Oh what would I do without you :P

**Comment by MaxNeedsSnacks** [comment]
Completed by Lykrast in Lykrast/JETIF#7

**Comment by Lykrast** [comment]
[Newest JETIF update](https://minecraft.curseforge.com/projects/jetif/files/2690473) just fixed that.
