### ISSUE TITLE
Replicator issues

### ISSUE THREAD

**Issue by Kolve82** [NillerMedDild/Enigmatica2Expert#727]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
Ic2 tiny pile of plutonium cant be replecated anymore. shows it needs unlimited amount of uu matter

**Modpack version (Do not use "latest")**
1.54

**Logs**

If applicable, please upload your crash report, or latest.log to [gist](https://gist.github.com/).

**Screenshots**

![plut](https://user-images.githubusercontent.com/47182640/51987506-efeb7c00-24a2-11e9-93c4-8e0d5c2dbd22.jpg)

**Additional context**

**Comment by NillerMedDild** [comment]
That must've been changed by the mod author, I do not control the uu matter amount for that - nor do I see a reason to revert it :)
