### ISSUE TITLE
Blood magic not being chunk loaded

### ISSUE THREAD

**Issue by Lazarix** [NillerMedDild/Enigmatica2Expert#728]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
Blood magic not being chunk loaded

**Modpack version 1.54**

So I found out today that blood magic isn't being chunk loaded.
It could be that, or it could be cursed earth not chunk loading.

Scenario:
I have a cursed earth mob farm attached to a well of suffering.
I am using another spell to generate lava from LP.
I know that I have a net positive LP generation from the mob farm. When in my base, all is good.
I chunk loaded everything with ftb utils within a 9 chunk radius, encompassing everything in my base.
Went searching for the end portal which is quite far away from my base. Got nausea.
Went back to my base, found my LP was very low but again started going up. Stayed there for a bit and nausea went away.
Rinse and repeat.
IC2 chunk loader also doesn't make a difference.

**Comment by NillerMedDild** [comment]
Thanks for the report, I'll investigate the issue.

Just to make sure, you're powering the IC2 Chunkloader, and you have selected which chunks to load from it's GUI, correct?

**Comment by Lazarix** [comment]
> 
> 
> Thanks for the report, I'll investigate the issue.
> 
> Just to make sure, you're powering the IC2 Chunkloader, and you have selected which chunks to load from it's GUI, correct?

Correct.
I can confirm that my primary method of chunk loading is via FTBU, and all chunks are claimed and chunkloaded.

**Comment by NillerMedDild** [comment]
Cursed Earth should keep them alive even when a player isn't around.

**Comment by Lazarix** [comment]
Any update on this issue? Thanks

**Comment by NillerMedDild** [comment]
Other than the fact that it works for some people, I haven't found anything useful yet :(

**Comment by NillerMedDild** [comment]
Still nothing, it seems that chunk loading is just hit-and-miss.
