### ISSUE TITLE
Thermionic Fabricated recipe cheaper then advanced

### ISSUE THREAD

**Issue by KyleCulp** [NillerMedDild/Enigmatica2Expert#729]
**Is your feature request related to a problem? Please describe.**
The recipe for Garden Cloches in the Thermionic Fabricator and the Advanced Thermionic Fabricator are exactly the same, except the regular Thermionic Fabricator requires two treated planks, while the advanced one requires 4 treated planks. 

**Describe the solution you'd like**
To change it to 2, or one. 

**Additional context**
From what I've seen the Advanced Thermionic Fabricator recipe's are cheaper to do, so I'm not sure if this is intentional. If it is, sorry for bugging ya

Edit: Github didn't show me related issues, so I searched after posting and found this. Sorry I relied on githubs features
https://github.com/NillerMedDild/Enigmatica2Expert/issues/564

**Comment by NillerMedDild** [comment]
Thanks for the report anyway :)
