### ISSUE TITLE
Ruby Ore

### ISSUE THREAD

**Issue by Tntdruid** [NillerMedDild/Enigmatica2Expert#732]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**

Been mining whit my Digital Miner in overworld for 4h now, not seen any ruby ore??

JEI says it spawn in overworld

**Modpack version (Do not use "latest")**
1.53, tested in 1,54 same

**Logs**

If applicable, please upload your crash report, or latest.log to [gist](https://gist.github.com/).

**Screenshots**

**Additional context**

**Comment by NillerMedDild** [comment]
You get Rubies from Sifting.

**Comment by OneEyeMaker** [comment]
@Tntdruid 
Ores from Biomes O' Plenty generate in specific biomes:
Ruby - in desert biomes,
Sapphire - in oceans;
Malachite - in marshy biomes, etc.
