### ISSUE TITLE
Seed Oil Unification

### ISSUE THREAD

**Issue by jesp1999** [NillerMedDild/Enigmatica2Expert#733]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
The seed oil from thermal expansion and the seed oil from forestry are not interchangeable in the carpenter, nor are they able to be converted using the fluid dictionary converter. This creates difficulty in speeding up the production of impregnated sticks and other ingredients requiring seed oil.

**Modpack version (Do not use "latest")**
1.54

**Logs**

If applicable, please upload your crash report, or latest.log to [gist](https://gist.github.com/).

**Screenshots**

**Additional context**

**Comment by NillerMedDild** [comment]
I'll look into it :)

**Comment by MorganSimic** [comment]
I also did look into it briefly and i think there is no easy way to unify this. AFAIK there is nothing like an oredict for fluids. So this would require another set of recipes of all the existing ones but with Thermal seed oil. Or change all Thermal stuff to produce Forestry seed oil or the other way around. And imo none of the last both options are really feasible. Changing thermal to forestry seed oil would be doable but still quite a lot of work. I think it comes down to if Niller wants to have a 3rd set of recipes for impgregnated sticks and the likes.

**Comment by MorganSimic** [comment]
A possible easy solution to this problem might be setting up a conversion via the Fluid Dictonary converter. I just learned you can pseudo-oredict fluids with that via craft tweaker.
https://crafttweaker.readthedocs.io/en/latest/#Mods/Industrial_Foregoing/FluidDictionary/

**Comment by NillerMedDild** [comment]
That would be a manual conversion for the player though, I'd rather have it work seamlessly.

**Comment by NillerMedDild** [comment]
I went with manual conversion, because I'm lazy :P
