### ISSUE TITLE
Add IC2 Advanced Machines

### ISSUE THREAD

**Issue by KyleCulp** [NillerMedDild/Enigmatica2Expert#734]
**Is your feature request related to a problem? Please describe.**
N.A

**Describe the solution you'd like**
I'd like IC2 Advanced Machines to be added. I understand it was just updated to 1.12.2, so maybe wait for bugs or something? I'm not up to date with all of that

**Additional context**
https://minecraft.curseforge.com/projects/advanced-machines

**Comment by NillerMedDild** [comment]
I'll look into it, thanks for the request :)

**Comment by NillerMedDild** [comment]
I decided I will not be adding this mod unfortunately, IC2 is a tier 1 mod within the pack, it shouldn't have faster machines than it does currently :)
