### ISSUE TITLE
Startup Crash with 1.54

### ISSUE THREAD

**Issue by chezpaul** [NillerMedDild/Enigmatica2Expert#735]
Game won't even start anymore since 1.54

[https://pastebin.com/eTWkAD8w](https://pastebin.com/eTWkAD8w)

**Comment by NillerMedDild** [comment]
Huh, that's odd. It's crashing because Compact Machines is using an invalid dimension ID, but it isn't. Try reinstalling, and please report back :)

**Comment by NillerMedDild** [comment]
It does :P always 144, hasn't changed recently.
