### ISSUE TITLE
/dank/null voids items

### ISSUE THREAD

**Issue by dragoniil1** [NillerMedDild/Enigmatica2Expert#738]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
if the /dank/null interface is opened (the inventory) and you pick up items that should go in it they dont and they simply get voided no matter how many itmes you have

for example put 10 cobblestone in the /dank/null drop a stack of cobble on the ground and when you try to pick it up and have the /dank/null opened it gets voided

**Modpack version (Do not use "latest")**

1.54

**Logs**

If applicable, please upload your crash report, or latest.log to [gist](https://gist.github.com/).

**Screenshots**

**Additional context**

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by scarfkitten** [comment]
Oh hey, I can actually add to this one! It seems that it _does_ add to the null but it takes an inventory update or a relog (something like trying to sort your inventory with invtweaks) in order to reflect the changes. Might be an issue with the null's special inventory overlay thing itself, because often if you obtain a mass of items while in the null's inventory it doesn't seem to update properly.

**Comment by dragoniil1** [comment]
> Oh hey, I can actually add to this one! It seems that it _does_ add to the null but it takes an inventory update or a relog (something like trying to sort your inventory with invtweaks) in order to reflect the changes. Might be an issue with the null's special inventory overlay thing itself, because often if you obtain a mass of items while in the null's inventory it doesn't seem to update properly.

well i tried reloading the game or the invtweaks and the items didn't come back they were permanently deleted

**Comment by NillerMedDild** [comment]
Are you absolutely certain this happened on modpack version 1.54?

**Comment by dragoniil1** [comment]
> Are you absolutely certain this happened on modpack version 1.54?

yes, if you want i can send a video with the steps...but i will do the same thing i explained above, is easy to replicate

**Comment by NillerMedDild** [comment]
So you say, but scarfkitten was unable to. I'll test it when I get time.

**Comment by NillerMedDild** [comment]
I can't reproduce the issue.
