### ISSUE TITLE
[Request] Add Random Tweaks

### ISSUE THREAD

**Issue by dclay1983** [NillerMedDild/Enigmatica2Expert#740]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Question or Issue**
Could you add Random Tweaks to the pack or if some other mod does this, a mod that allows sounds to be reloaded separate from textures. I often find myself leaving modded Minecraft running, as it takes almost 20 minutes to load up, while I look something up online. This can sometimes break my sound if a video is launched, causing me to have to reload the game as it is faster than reloading the textures.

**Modpack Version**

Enigmatica 2: Expert 1.54

**Additional Context**

I know Random Tweaks adds a lot of OP options, that I would prefer were not in the pack, but it is the only mod I know of that adds an ability to reload sounds in Minecraft.

**Comment by NillerMedDild** [comment]
https://minecraft.curseforge.com/projects/sound-reloader that should do it :D I would rather not add it to the pack, but I believe it's clientside only, so you can just add it yourself.

**Comment by dclay1983** [comment]
Oh, thank you. I didn't know that was a thing.
