### ISSUE TITLE
Buff Advanced Rocketry Metal Working Machines

### ISSUE THREAD

**Issue by TDSSS** [NillerMedDild/Enigmatica2Expert#742]
**Is your feature request related to a problem? Please describe.**
It seems rather strange that the Lathe, a machine from a tier 4 mod, is just as good at making rods as the Immersive Engineering Metal press (technically it is even 'worse' since it also need some lubricant to function at all). Both just turn one metal ingot into two rods.

(The same can, kind of, be applied to the rolling machine and making metal plates, but since it also makes other things (tanks and metal sheets) it's at least not pointless. It could be buffed to produce more plates too though)

The quest book recommends building those machines early to cut down on material costs, which IMO is rather pointless since at that point you really should have an IE metal press set up. I highly doubt anyone is still using engineer's hammers to manually make plates at that point, or using the manual rod recipe.

**Describe the solution you'd like**
Since it is a much higher tier of machine fulfilling the same function, it ideally should be better at doing what it does, I'd like to see the lathe make more output with the same amount of input, i. e. making 3 rods from one ingot.

**Additional context**

**Comment by NillerMedDild** [comment]
Thank you for the suggestion, I will implement this.
