### ISSUE TITLE
Add a recipe for the Crystal Cluster, unlocking the tier 6 blood altar

### ISSUE THREAD

**Issue by OmaiGrundles** [NillerMedDild/Enigmatica2Expert#744]
**Is your feature request related to a problem? Please describe.**
The crazy thing is that even though the tier 6 altar is actually still supported in blood magic, the final piece needed (crystal cluster) is not craftable or obtainable. Unlocking the tier 6 altar would allow more runes to be used, and also the creation of the transcendent blood orb.

**Describe the solution you'd like**
Adding in some difficult recipe for the crystal cluster could be pretty rewarding for the big blood magic users. As for what the recipe would be... 

**Additional context**
The tier 6 altar does unlock the use of the dusk inscriber, but NOT the diviner so good luck figuring out the actual ritual's pattern if there is any hidden ones there. That recipe may need to be disabled just in case there is something weird there.

**Comment by NillerMedDild** [comment]
The current maintainer of Blood Magic has expressed that he would prefer if pack devs do not give access to tier 6, as that part of the mod is not fleshed out at the moment.
