### ISSUE TITLE
Unable to add Radiation Shielding to QuantumSuit

### ISSUE THREAD

**Issue by Calgor** [NillerMedDild/Enigmatica2Expert#745]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
Crafting recipe involving QuantumSuit suggests that by combining any piece of the armour (head, torso legs or boots) with Light, Medium or Heavy Radiation Shielding in a shapeless recipe (even in the character crafting inventory) it should combine into what I presume would result in a radiation shielded version, although the interface doesn't explicitly say anything about rad shielding on it but hey... Instead it seems to do nothing when added to any crafting window including inventory, table, bench or ME.

The items in the inventory appear to be valid as I can use the option to add to a crafting window the components in hand.

Seems to work for other pieces of armour such as vanilla armour, Immersive Engineering, even Twilight Forest armour but not QuantumSuit.

I don't think it's gated away behind a quest achievement somewhere though happy to be shown wrong if so.

**Modpack version (Do not use "latest")**
Enigmatica2Expert 1.52

**Logs**

None

**Screenshots**

Current screenshot from JEI crafting suggestion advising that it should combine into something
![radiationshielding quantum](https://user-images.githubusercontent.com/38385428/52127692-b9d90400-262a-11e9-80af-206a6fa7c734.PNG)

Actual results when trying to do anything with it.
![radiationshielding quantumnorad](https://user-images.githubusercontent.com/38385428/52127690-b9d90400-262a-11e9-8eec-085822a15a67.PNG)

**Additional context**

NA

**Comment by NillerMedDild** [comment]
Did you try with unpowered Quantum Armor? :)

**Comment by Calgor** [comment]
I did indeed. Loaded up a single player sandbox, world. Took the base power suit torso that JEI gives you and the end result is zip.

![2019-02-01_18 14 33](https://user-images.githubusercontent.com/38385428/52141491-cfabf080-264d-11e9-9395-434e2f4c8000.png)
![2019-02-01_18 14 31](https://user-images.githubusercontent.com/38385428/52141492-d0448700-264d-11e9-9d91-344cb601f985.png)

**Comment by NillerMedDild** [comment]
Alright, thanks. I guess IC2 armor just doesn't like to be modified :/

**Comment by NeosGhost** [comment]
I believe the thought of the ic2 devs was since the suit has built in enhancements it does not need enchantments. Iirc you cant even enchant the quantum set with just vanilla and ic2 loaded.

**Comment by NillerMedDild** [comment]
Yep that sounds about right.
