### ISSUE TITLE
Industrial Foregoing farms don't work

### ISSUE THREAD

**Issue by Akeeru** [NillerMedDild/Enigmatica2Expert#746]
**Issue Description**
Plant Gatherer does not harvest trees and plants.
Plant Sower does plant any sapling and seeds

**Modpack version (Do not use "latest")**
1.54

**Logs**

**Screenshots**

**Additional context**

**Comment by NillerMedDild** [comment]
Did you supply them with energy, saplings, etc? Screenshots of the setup would be helpful.

**Comment by Akeeru** [comment]
Yes, I supply them with energy, sapling/seeds.
I destroyed and place the machines again and it did not work, but I only heard the sound.

**Solved**
When you change in team setting __Required Level for Block Editing__ to __Member__, you must too change __Fake Player Status__ to __Member__

**Comment by NillerMedDild** [comment]
Good catch :)
