### ISSUE TITLE
Add Railcraft

### ISSUE THREAD

**Issue by Mihnea229** [NillerMedDild/Enigmatica2Expert#747]
Is your feature request related to a problem? Please describe.
N.A

Describe the solution you'd like
I'd like Railcraft to be added. I understand it was just updated to 1.12.2, so maybe wait for bugs or something? I'm not up to date with all of that.

Additional context
.https://minecraft.curseforge.com/projects/railcraft/files

**Comment by mindcloud69** [comment]
Ditto I have already added it manually, but I would love official support.

**Comment by NillerMedDild** [comment]
I would love to add Railcraft, but it would make the modpack too hard to run. I have trouble running it as it is, so it's a no :/
