### ISSUE TITLE
Can't scan ic2 uranium fuel rods for replication

### ISSUE THREAD

**Issue by aerde** [NillerMedDild/Enigmatica2Expert#749]
All related to uranium fuel from IC2, including fuel rods, cannot be scanned and replicated. So it is now impossible to fully automate uu-matter production. Scanner just don't accept these items.

Modpack version 1.54

**Comment by NillerMedDild** [comment]
How exactly does that make automated UU-matter production impossible?

**Comment by NillerMedDild** [comment]
Anyhow, that was changed in IC2, and I don't see any reason to bring it back. You can easily automate Uranium production and the processing of it into Fuel Rods.
