### ISSUE TITLE
Crashing With Automation

### ISSUE THREAD

**Issue by Angelos33** [NillerMedDild/Enigmatica2Expert#75]
#### Issue Description
Crashing when i get the ME system to craft Advanced Rocketry structure frames 
#### Modpack version (Do not use "latest")
Modpack version 1.24
#### Crash Report
https://pastebin.com/MAvHPnhq

**Comment by NillerMedDild** [comment]
You'll have to replace the Transfer Node you're using with something else I'm afraid.
