### ISSUE TITLE
Add Just Enough Calculation

### ISSUE THREAD

**Issue by KyleCulp** [NillerMedDild/Enigmatica2Expert#750]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
I'd like Just Enough Calculation to be added. I'm tired of putting a full list of items I require in notepad, this mod would fix that. Can't be too heavy either

**Additional context**
https://minecraft.curseforge.com/projects/just-enough-calculation

**Comment by kythorn** [comment]
+1

**Comment by NillerMedDild** [comment]
I decided not to add it I'm afraid, I'm afraid it would result in bloat more than anything.
