### ISSUE TITLE
Add a recipe for the Flux Sponge

### ISSUE THREAD

**Issue by xmiso** [NillerMedDild/Enigmatica2Expert#751]
**Is your feature request related to a problem? Please describe.**
Thaumcraft 6's Flux Rifts mechanics are horrible IMO. I don't find fun in Thaumcraft anymore since they were added. The fact that they can just appear (even with little Warp) and destroy your base ruins everything great in Thaumcraft.

**Describe the solution you'd like**
Add a recipe for the Flux Sponge. Maybe not using end-game Thaumcraft stuff, but Botania, Astral Sorcery and Blood Magic items. 

**Additional context**

**Comment by OneEyeMaker** [comment]
@xmiso 
There is alternative: *Causality Collapser*. This item is hidden by research. To unlock one you need to get high level of flux (this unlocks 'Flux' research) and scan Crystal Clusters.
This item (Causality Collapser) can be tossed into rift to close it.

**Comment by xmiso** [comment]
The Casuality Collapser is a bit mid-late game in Thaumcraft, meaning that any Flux Rift that generates before getting to that point will completely destroy everything.

**Comment by OneEyeMaker** [comment]
@xmiso 
I don't agree with you. I've crafted 2 Causality Collapsers in early-game (right after unlocking Infusion).
And it's pretty cheap (IMHO) - niter, alumentum, redstone and some Thaumcraft crafting components.

**Comment by NillerMedDild** [comment]
I will not be adding this I'm afraid.
