### ISSUE TITLE
IC2 not working inside Compact Machines

### ISSUE THREAD

**Issue by Coder266** [NillerMedDild/Enigmatica2Expert#752]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Question or Issue**

Nothing from IC2 seems to work inside the Compact Machines. The machines don't connect to mekanism's universal cables, they don't receive power from mekanism's energy cubes and the IC2 cables don't connect between each other or to machines.

**Modpack Version**

1.54

**Additional Context**

The machines and cables work just fine outside the Compact Machine and downgrading the pack to 1.53 fixed the issue

**Comment by Coder266** [comment]
After a while playing in 1.53 it happened again and restarting the world fixed it

**Comment by MaxNeedsSnacks** [comment]
Is it working now in the latest version (currently 1.58)?

**Comment by MorganSimic** [comment]
At least for me it is working perfectly fine. I have an IC2 oreprocessing setup running in a compact machine probably since at least 1.56 and it is running without issues. No disconnects from cables, nothing.

**Comment by MorganSimic** [comment]
I have tested numerous IC2 machines and numerous mekanism power supplying methods in compact machines and have run into no issues whatsoever. And since there was no response from the original author anymore or any other reports of this happening, i think i will close this issue for now.

**Comment by NillerMedDild** [comment]
Thanks Morgan!
