### ISSUE TITLE
Mod Immersive Engineering achievments

### ISSUE THREAD

**Issue by Kalthor1** [NillerMedDild/Enigmatica2Expert#755]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
The Achievments from Immersive Engineering "The Upgrade"does not unlook, because the steel ingot is only from Thermal Expansion and not from Immersive Engineering

**Modpack version (Do not use "latest")**
1.44

**Logs**

If applicable, please upload your crash report, or latest.log to [gist](https://gist.github.com/).

**Screenshots**

**Additional context**

**Comment by NillerMedDild** [comment]
There's not much I can do about that really, nor do I feel that it needs fixing. Sorry.
