### ISSUE TITLE
Extra Cells 2 - Deuterium/Tritium disappearing when storage cells 100% full

### ISSUE THREAD

**Issue by kernelstubbs** [NillerMedDild/Enigmatica2Expert#756]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Question or Issue**

Extra Cells 2 - Deuterium/Tritium disappearing when storage cells 100% full

**Modpack Version**

1.53

**Additional Context**

When I import Deuterium or Tritium to AE2 Extra Cells (have tested 1K and 16K) once it reaches 100% full, the gas is no longer visible in the gas terminal.  It will sometimes continue to export but randomly the reactor will stop after running out of fuel but then fill back up again.

**Comment by NillerMedDild** [comment]
ExtraCells is currently very buggy, hopefully it updates soon :)

**Comment by Vercci** [comment]
I know this is a bit late, but you can use the rotary condenser to turn the gas you do have into a liquid version, then use the officially supported fluid system from AE2. Nuclearcraft can handle the liquid versions of those two gases in the version of E2E I'm using and you're running a newer one than that so it shouldn't be broken.

Plus the fluid cells have much better capacity than the equivalent gas cells. I believe I've gone from 30 64k cells filled with Tritium, Deuterium and DT Fuel to 10 64k fluid cells and I'm nowhere near full on the fluid cells.

**Comment by MaxNeedsSnacks** [comment]
I would just recommend following Vercci's suggestion here, ExtraCells is currently horrendously buggy and the next release *might* fix **some** of that, but definitely not everything.
