### ISSUE TITLE
Creative cell recipe broken

### ISSUE THREAD

**Issue by BronzCodex** [NillerMedDild/Enigmatica2Expert#757]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
The Creative cell recipe seems broken in 1.54. It doesn't accept the resonant energy cells (No matter if full or empty) not in SP, nor MP

**Modpack version (Do not use "latest")**
1.54

**Logs**

If applicable, please upload your crash report, or latest.log to [gist](https://gist.github.com/).

**Screenshots**
https://imgur.com/a/sjJ453E

**Additional context**

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
Have you tried restarting the game and/or server?

**Comment by NillerMedDild** [comment]
![billede](https://user-images.githubusercontent.com/21295394/52175004-18be8a80-279d-11e9-93f1-963b81475510.png)
Works for me :)

**Comment by BronzCodex** [comment]
Mm, did you cheat the cells in or actually make them with conversion kits?

**Comment by NillerMedDild** [comment]
I made them with Conversion Kits.

**Comment by BronzCodex** [comment]
![2019-02-03_10 33 36](https://user-images.githubusercontent.com/47284466/52175138-7653d680-279f-11e9-9eee-de13a692bc01.png)

**Comment by NillerMedDild** [comment]
It told me the same thing.

**Comment by NillerMedDild** [comment]
Do the Ultimate Mekanism Cells have NBT data?

**Comment by BronzCodex** [comment]
In MP yes, in SP no.

**Comment by NillerMedDild** [comment]
Alright, that's most likely the issue. I cheated mine in, they have no NBT data. I'll get it fixed for 1.55 :)

**Comment by NillerMedDild** [comment]
Actually I haven't been able to reprodue the error, still. May I see a screenshot of your table with the ingredients, not just JEI?

**Comment by takarabako** [comment]
I tried with brand new created and upgraded cells. In JEI it shows missing cells. However, if you manully fill 81 slots it still not showing output, but you can actually grab the "air" output slot out and it becomes the creative cell.
