### ISSUE TITLE
Gitignore entry for world

### ISSUE THREAD

**Issue by Ricket** [NillerMedDild/Enigmatica2Expert#758]
I keep my servers in git so that I track all changes. I always added `world/` to the gitignore because I backup the world separately. Then I started FTB Revelation, and a while into it, I couldn't find Black Quartz Ore anywhere underground.

Long story short, they disabled the mod's built in generation of the ore and used CoFH oregen instead. The ore gen configuration is in `config/cofh/world/..`.

That folder was ignored because of my gitignore rule. I fixed it to have a leading slash (`/world/`) and then it only matched my world folder and not the config world subfolder. Then I had to go through some pain of setting up retrogen...

Thought I'd share this so you can avoid that pain. It took me hours to root cause why the ore was missing. I highly recommend leading slashes on gitignore entries now, only leaving them off where I intentionally want to ignore the pattern across all subfolders.

**Comment by NillerMedDild** [comment]
I hadn't thought about that at all, thank you :D I'm sure that would've caused me trouble down the line.

**Comment by Ricket** [comment]
(to be clear, I wrote this because your gitignore has a `world/` [line that maybe should be fixed](https://github.com/NillerMedDild/Enigmatica2Expert/blob/master/.gitignore#L82) to `/world/`)
