### ISSUE TITLE
Prevent clobbering of Opaque Itemduct variants

### ISSUE THREAD

**Issue by Wizarth** [NillerMedDild/Enigmatica2Expert#759]
**Issue Description**
The variants of the Oqaque Itemduct (Dense, Vacuum) have their recipies set to the same as that of the base Oqaue Itemduct. This makes them uncraftable.

**Modpack version (Do not use "latest")**
1.54

**Screenshots**

I can't get a screenshot that shows JEI giving the same recipe for all the Itemduct variants.

_After change_
https://imgur.com/a/uYwmuAf

**Fix**
In scripts/ThemalDynamics.zs, set the NBTMatch parameter when calling remove on the recipe.

```diff
--- scripts/ThermalDynamics.orig.zs     2019-02-03 13:24:01.255610200 +1100
+++ scripts/ThermalDynamics.zs  2019-02-03 13:26:55.808457700 +1100
@@ -18,7 +18,7 @@
        [<ore:plateElectrum>, <ore:plateElectrum>, <ore:plateElectrum>]]);

 # Itemduct Opaque
-       recipes.remove(<thermaldynamics:duct_32:1>);
+       recipes.remove(<thermaldynamics:duct_32:1>, true);
        recipes.addShapedMirrored("Itemduct Opaque",
        <thermaldynamics:duct_32:1> * 12,
        [[null, null, null],
```

**Comment by NillerMedDild** [comment]
Opaque Itemduct dense/vacuum variants are disabled on purpose. The clear Itemducts still have the variants because they're more expensive.
Thanks for the report and fix anyhow!
