### ISSUE TITLE
Manasteel helmet of revealing can upgrade straight to terrasteel helmet of revealing

### ISSUE THREAD

**Issue by dmsummers** [NillerMedDild/Enigmatica2Expert#760]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**

By crafting a manasteel helmet of revealing, you can upgrade it straight to a terrasteel helmet of revealing, completely bypassing the need to create the psimetal and elementium helms.

**Modpack version (Do not use "latest")**

1.54

**Logs**

N/A

**Screenshots**

![2019-02-02_21 19 03](https://user-images.githubusercontent.com/12475311/52172240-1c1c2c80-2731-11e9-9a7c-1e9d7f22fe67.png)

**Additional context**

N/A

**Comment by NillerMedDild** [comment]
Woops, thanks for letting me know!
