### ISSUE TITLE
Checkboxes

### ISSUE THREAD

**Issue by FireFeet55** [NillerMedDild/Enigmatica2Expert#761]
I have just started playing Enigmatica 2 Expert mode and have run across a problem with the very first quest, entitled "Welcome". The quest is a checkbox quest where all you have to do is check the box to continue. But my game will not allow me to check the box. It doesn't give me the option. I am up to date with the Forge versions and just downloaded the modpack a short while ago. Any help would be appreciated.

**Comment by NillerMedDild** [comment]
Well that's alarming. Could you try with a different GUI scale?

**Comment by FireFeet55** [comment]
Tried the different GUI scales. I have restarted and loaded the packs again, to no avail. I somehow got lucky and was able to get past the first checkbox. And so the other quests work. Just let sure why only my checkbox quests aren't working

**Comment by NillerMedDild** [comment]
Our current version of Better Questing has some issues with Task types, so I guess this could be one of them.

**Comment by scribbler957** [comment]
The weird BQ behavior can be dealt with by dragging the scroll bar for the reward selection box, even if there's none. Haven't had the chance to try it on a checkbox though.
