### ISSUE TITLE
EU2 Wireless Heating Coil Dupe Bug

### ISSUE THREAD

**Issue by koncan5** [NillerMedDild/Enigmatica2Expert#762]
**Issue Description**

When crafting Redstone-Iron Wiring, completing the craft (regardless of shift click or not) does not use up the heating coils. Not sure if intended, could be like buckets.

**Modpack version (Do not use "latest")**

1.53

**Logs**

N/A

**Screenshots**

![2019-02-03_19 08 34](https://user-images.githubusercontent.com/25295999/52174445-ad4dda80-27e7-11e9-99f9-c48f087a73a2.png)
![2019-02-03_19 08 44](https://user-images.githubusercontent.com/25295999/52174446-ade67100-27e7-11e9-82ff-1a381210431c.png)

**Additional context**

Tested using both FastWorkbench crafting table and Tinkers crafting station.

**Comment by NillerMedDild** [comment]
It is intended :) Thanks for the report.
