### ISSUE TITLE
Game crash after opening guidance computer

### ISSUE THREAD

**Issue by beulemann** [NillerMedDild/Enigmatica2Expert#765]
**Issue Description**

Minecraft crashed after opening guidance computer (configured planet id card earth in it)

**Modpack version (Do not use "latest")**

1.54

**Logs**

https://gist.github.com/beulemann/4358a7e8686eac6ec5df9b8b0564d583

**Screenshots**

none

**Additional context**

First occured after the start of the rocket.
Restarted game, rocket gone.
Assembled new one. This time it happens before start.

**Comment by beulemann** [comment]
Update:
After another restart. Both Rockets at the same launchpad.
Disassembled them, Reassembled. Fly to the moon, Change ID Card, Return to Overworld.
All Fine.
Trying to change ID Card to Luna, Opening guidance comper. => crash

**Comment by TDSSS** [comment]
I've noticed some crashes when interacting with AR rockets too, either when checking the guidance computer or when checking storage crates that are part of them.

Can't quite reproduce them every time though.

**Comment by kythorn** [comment]
Are you playing on a server? If so, I think it's likely related to https://github.com/NillerMedDild/Enigmatica2Expert/issues/787

**Comment by NillerMedDild** [comment]
The issues seem to have the same root cause, but 2 different mods crashing :P 

Could you try to reproduce the issue with this version of AR @beulemann ?
[AdvancedRocketry-1.12.2-1.5.0-universal.jar.zip](https://github.com/NillerMedDild/Enigmatica2Expert/files/2842616/AdvancedRocketry-1.12.2-1.5.0-universal.jar.zip)

**Comment by NillerMedDild** [comment]
Link to the issue 
https://github.com/zmaster587/AdvancedRocketry/issues/1509

**Comment by beulemann** [comment]
> The issues seem to have the same root cause, but 2 different mods crashing :P
> 
> Could you try to reproduce the issue with this version of AR @beulemann ?
> [AdvancedRocketry-1.12.2-1.5.0-universal.jar.zip](https://github.com/NillerMedDild/Enigmatica2Expert/files/2842616/AdvancedRocketry-1.12.2-1.5.0-universal.jar.zip)

A bit busy in the moment.
Going to give it a try after the weekend.

**Comment by Tntdruid** [comment]
My game is crashes, @Direwolf20 has the same crash in his latest Let's Play EP

**Comment by Tntdruid** [comment]
AdvancedRocketry-1.12.2-1.5.0-universal.jar.zip fix all my crash!
