### ISSUE TITLE
Arrows from Cursed Skeletons don't despawn

### ISSUE THREAD

**Issue by dragoniil1** [NillerMedDild/Enigmatica2Expert#766]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**

Arrows from Cursed Skeletons don't despawn and they are keep building up

**Modpack version (Do not use "latest")**

1.54

**Logs**

If applicable, please upload your crash report, or latest.log to [gist](https://gist.github.com/).

**Screenshots**

https://imgur.com/a/EOUGbRU

**Additional context**

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.
