### ISSUE TITLE
Cobalt/Ardite/Lithium Dust Unification

### ISSUE THREAD

**Issue by MorganSimic** [NillerMedDild/Enigmatica2Expert#768]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
While working on the Plate Presser recipes i noticed some not unified oredusts. First of all, Lithium Dust is unified to IC2 lithium dust but in JEI there exist 2 other variants, one from Mek, one from NC. The other ones are Cobalt/Ardite dust. Almost all machines put out ExNihilo dusts but they are not listed in JEI, not even hidden, they are just missing. Only Cobalt/Ardite dust in JEI is from EIO and that is produced by ID squeezers.

**Modpack version (Do not use "latest")**
1.54

**Logs**

If applicable, please upload your crash report, or latest.log to [gist](https://gist.github.com/).

**Screenshots**

**Additional context**
I looked at the UniDict config but i'm not to familiar with it to find a quick fix for this issue. But i highly suspect that it is unidicts doing, hiding the ExNihilo stuff from JEI.

**Comment by NillerMedDild** [comment]
Damnit, I'll look into configuring UniDict better :P
