### ISSUE TITLE
Mekanism And Nuclearcraft Sulfuric Acid Not Interchangeable 

### ISSUE THREAD

**Issue by iamgeorgeclooney** [NillerMedDild/Enigmatica2Expert#772]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
To get the draconium crystal for ultimate crafting table you need to use Mekanism sulfuric acid in the chemical dissolution chamber, but to make the chemical dissolution chamber you need a bucket of Nuclearcraft Sulfuric Acid in the crafting recipe, seems very weird to have to set up two almost identical systems to get the exact same liquid 

Maybe add a way to condensentrate or Decondensentrate  using the Rotary Condensentrator to switch between liquids

**Modpack version (Do not use "latest")**
1.54

**Logs**

If applicable, please upload your crash report, or latest.log to [gist](https://gist.github.com/).

**Screenshots**

https://imgur.com/SNhd39G

https://imgur.com/cPS9DIO

https://imgur.com/SNhd39G

**Additional context**

**Comment by NillerMedDild** [comment]
That is an oversight, thank you for letting me know :)

**Comment by NillerMedDild** [comment]
Recipe for Chemical Dissolution Chamber fixed.
