### ISSUE TITLE
Add Hint to key Thaumcraft items that they need to be unlocked first

### ISSUE THREAD

**Issue by MorganSimic** [NillerMedDild/Enigmatica2Expert#773]
**Is your feature request related to a problem? Please describe.**
I've seen now multiple times in the Discord that people don't know how to get Mirrored Glass for example. The fact that it is craftable in the Arcane Crafting engine confuses many players, because it is the only recipe in JEI before it is unlocked through Thaumcraft. It leads to the assumption they need the engine to progress.

**Describe the solution you'd like**
Add a tooltip or JEI info, that the item can be crafted normally once you have unlocked it through research in Thaumonomicon, to circumvent confusion due to the crafting engine. Specifically the mirrored glass since it is needed for AS. Not sure how much it is needed on other stuff.

**Additional context**

**Comment by NillerMedDild** [comment]
Good idea, I'll do that :)
