### ISSUE TITLE
disk usage freezing

### ISSUE THREAD

**Issue by antrobot1234** [NillerMedDild/Enigmatica2Expert#774]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
minecraft freezes on random for 1-5 minutes and uses all disk transfer speed (3-6MB/s)

**Modpack version (Do not use "latest")**

1.54

**Logs**

If applicable, please upload your crash report, or latest.log to [gist](https://gist.github.com/).
https://gist.github.com/antrobot1234/e8bc18c9e45730a25a0f1593f641b1e7
**Screenshots**

**Additional context**

**Comment by NillerMedDild** [comment]
Thanks for the report.

How much RAM does the server you're on have allocated?

**Comment by antrobot1234** [comment]
6gb ram

**Comment by NillerMedDild** [comment]
Can you reproduce it in SP? It kinda looks like your internet speed is throttling your connection.

**Comment by NillerMedDild** [comment]
Oh it's a LAN world, not a dedicated server?

**Comment by antrobot1234** [comment]
Yes. It’s a world I’m hosting via lan and forwarded via hamachi to play with a friend of mine.

**Comment by NillerMedDild** [comment]
That pretty much explains it. Your PC has tons of operations to take care of, you're most likely overburdening it.

**Comment by antrobot1234** [comment]
then why is it freezing for minutes on end and running fine the rest of the time instead of running slow in general

**Comment by NillerMedDild** [comment]
There could be a number of reasons. The world doesn't save all the time, I don't know how often LAN worlds save. I highly recommend that you get yourself a dedicated server.

**Comment by antrobot1234** [comment]
if i could prove this happens in Singeplayer too, would you re-open the issue?

**Comment by NillerMedDild** [comment]
Yep absolutely.

**Comment by antrobot1234** [comment]
https://gist.github.com/antrobot1234/e3d76bd09ca05817b6258067885313ad
singleplayer freezing proof

**Comment by NillerMedDild** [comment]
There is nothing in that log that proves that you're freezing. There is mention of a chunk that is taxing to render, but that's about it. Try increasing allocated RAM to 7GB, and add these java arguments:
`-XX:+UseG1GC -Dsun.rmi.dgc.server.gcInterval=2147483646 -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M`
