### ISSUE TITLE
clay bucket water not dictionaried with listAllwater

### ISSUE THREAD

**Issue by draeath** [NillerMedDild/Enigmatica2Expert#775]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**

Clay buckets of water aren't in the oredict 'listAllwater' and is not valid for these, and I can't think of any reason (beyond gating) for this.

If this is not intended, this can be rectified by adding this to `OreDict.zs` or similar:

```
<ore:listAllwater>.add(<claybucket:claybucket:1>);
```

**Modpack version (Do not use "latest")**

1.54

**Logs**

N/A

**Screenshots**

N/A

**Additional context**

Pam's has a few recipes which require buckets of water, or her own water item (irrelevant to this report). For example, salt and dough require it. This prevents any recipes involving bread from being used until normal buckets are available.

**Comment by draeath** [comment]
Note: the water + pot recipe that sent me looking for this eats the clay bucket, and you'd need to do more fiddling to fix that. Not sure if this is worth the bother, honestly...

**Comment by NillerMedDild** [comment]
It's not in there because the container is abnormal, adding it would make more issues than it would solve, as you point out yourself :)
Thanks for the report anyhow.
