### ISSUE TITLE
IC2 Fuel Rods say Infinite Buckets of UU

### ISSUE THREAD

**Issue by CloudConstructor1** [NillerMedDild/Enigmatica2Expert#777]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
I had a fully automated system producing quad fuel rods from UU for my UU producting facility.
I noticed today that im missing 1 million buckets of UU from my demon drum. Yes ONE MILLION+
buckets. Whether the change was by you or the IC2 mod itself, it was your responsiblity to note this change in the change log. I could have saved all the UU from being eaten by the replicator since the QUAD rod now says INFINITE UU. The scanner may not be able to scan it anymore but if it was already saved and in a replicator, it would just constantly drain UU. Thank you for wasting over 800 hrs of UU production.

**Modpack version (Do not use "latest")**
1.54

**Logs**

If applicable, please upload your crash report, or latest.log to [gist](https://gist.github.com/).

**Screenshots**

**Additional context**

**Comment by NillerMedDild** [comment]
While I am sorry for the loss of your UU matter, you cannot expect me to check the generated UU-matter values every update. The values were changed by IC2, it was not mentioned in their changelog.

I hope you can cheat your losses back in.
