### ISSUE TITLE
Unable to craft Coal coke from Coke block

### ISSUE THREAD

**Issue by jamzam90** [NillerMedDild/Enigmatica2Expert#778]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
Coal coke is unable to be crafted from the coke block

**Modpack version (Do not use "latest")**

1.54

**Logs**

If applicable, please upload your crash report, or latest.log to [gist](https://gist.github.com/).

**Screenshots**

**Additional context**

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

As a temporary solution, you should be able to chisel it into another variant, and craft that into Coal Coke.

**Comment by NillerMedDild** [comment]
Thanks for doing the legwork @scarfkitten :D
