### ISSUE TITLE
Add Re-sound mod

### ISSUE THREAD

**Issue by NikkoScript** [NillerMedDild/Enigmatica2Expert#779]
**Is your feature request related to a problem? Please describe.**
Sometime Minecraft Sound just stop working, A reload is necessary wich can be painfull with the loading time .

**Describe the solution you'd like**
This mod : 
https://www.curseforge.com/minecraft/mc-mods/resound
Add the possibility to reload only the sound system with F3+S.

**Additional context**

**Comment by NillerMedDild** [comment]
The sound reload issue is so limited that I am hesitant to add a mod to patch it. I will consider it.

**Comment by NikkoScript** [comment]
Indeed it's limited i just wanted to let you know this mod exists and might be usefull for some people, I add it maybe other user can add it too if the encounter the issue.
