### ISSUE TITLE
I have a question buffs from spice of life?

### ISSUE THREAD

**Issue by Dokend** [NillerMedDild/Enigmatica2Expert#780]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Question or Issue**
What are the max buffs you get from having your 5 food groups maxed?
I currently get toughness, strength II, and resistances II.  Is that all or am i doing something wrong?

**Modpack Version**

Enigmatica 2 expert 1.54

**Additional Context**

**Comment by NillerMedDild** [comment]
That is all :)
