### ISSUE TITLE
Singleplayer world version 1.54 crash while loading world

### ISSUE THREAD

**Issue by KCtops100** [NillerMedDild/Enigmatica2Expert#781]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
When loading single player world, not creating a new world, after it says "loading world, building terrain", the game randomly crashes.  Any ideas? A crash report does not generate, but a log is attached.  Appreciate the help in advance

**Modpack version (Do not use "latest")**
1.54

**Logs**
https://gist.github.com/KCtops100/768e8dcae922fb3bb76d95b2f72a37f8 
If applicable, please upload your crash report, or latest.log to [gist](https://gist.github.com/).

**Screenshots**

**Additional context**

**Comment by NillerMedDild** [comment]
Delete this file: `C:\Users\Kyle\Documents\Curse\Minecraft\Instances\Enigmatica 2 Expert\saves\New World\advRocketry\planetDefs.xml`

**Comment by NillerMedDild** [comment]
It's a pretty frequent issue, that has a chance of happening when a world is closed incorrectly.

**Comment by KCtops100** [comment]
Thank you!
