### ISSUE TITLE
Ore Dictionary/Unify Immersive Engineering and IC2 Distilled Water

### ISSUE THREAD

**Issue by hresad** [NillerMedDild/Enigmatica2Expert#782]
**Is your feature request related to a problem? Please describe.**
IE Distilled Water can't be used for crafting IC2 Coolant and that looks more like an oversight rather than an intentional balancing decision.

**Describe the solution you'd like**
Ore dictionary/unify the two or provide a way to convert them.

**Additional context**

**Comment by MorganSimic** [comment]
99% will not be happening. See #724

**Comment by hresad** [comment]
Ah, I searched before posting this but didn't find that.

**Comment by NillerMedDild** [comment]
We appreciate the report regardless - I'd rather have ten redundant issues than miss a bug :D
