### ISSUE TITLE
Pattern terminal doesnt require Items 

### ISSUE THREAD

**Issue by jonnytest1** [NillerMedDild/Enigmatica2Expert#783]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
I just updated from 1.5.1 to 1.5.4 and now my ae pattern terminal doesnt require the items to be in the ae network (I also checked : both server and client ae2 config had this enabled oO )

this is also a problem sine it doesnt default to items that are already available

**Modpack version (Do not use "latest")**
1.5.4

**Logs**

If applicable, please upload your crash report, or latest.log to [gist](https://gist.github.com/).

**Screenshots**

**Additional context**

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NikkoScript** [comment]
This isn't the mod added Just Enough Energestic causing this behavior ?

**Comment by NillerMedDild** [comment]
It is, but it is intended to use items available in the system first.

**Comment by Wntermute** [comment]
This isn't a bug, it's a feature. All the Pattern Terminal does is program patterns for the autocrafters. If you try to start a craft without all the required items, the UI will tell you so.

**Comment by NillerMedDild** [comment]
Cannot replicate the issue, it seems to default to items that are within the system.

**Comment by jonnytest1** [comment]
can you try with mekanism advanced circuit boards in the system putting a recipe that can use both the ic2 ones and the mkanism ones ?

**Comment by jonnytest1** [comment]
it also doesnt recognize crafting patterns as input

**Comment by NillerMedDild** [comment]
Which recipes require crafting patterns?

**Comment by jonnytest1** [comment]
in the ae version from before you could set up a crafting pattern for an item and it would use that item for a crafting pattern that fits even if it doesnt exist in the ae system

**Comment by TemperedFool** [comment]
With the new behavior, you can create a whole string of patterns before having to load them in your interfaces; this seems much better than the previous system of make base pattern, load in interface, make next tier, load, on and on. My only complaint at all is the one you cite (it choosing IC2 circuits rather than Mekanism), which should be solvable via enable substitutions?
