### ISSUE TITLE
Add TiCon's clear glass to glass cycling recipes

### ISSUE THREAD

**Issue by MorganSimic** [NillerMedDild/Enigmatica2Expert#785]
**Is your feature request related to a problem? Please describe.**
Tinker's clear glass is annoyingly hard to make since it can only be obtained by casting liquid glass in a casting basin.

**Describe the solution you'd like**
I'm not sure if that should be a thing or not but maybe make glass be able be cycle through all of the three variants, vanilla glass, EIO quite clear glass and TiCon clear glass.

**Additional context**

**Comment by NillerMedDild** [comment]
To be honest I always found it charming that Clear Glass is so hard to obtain, it makes builds with it that much cooler :P

**Comment by NillerMedDild** [comment]
Cool :)
