### ISSUE TITLE
IE Assembler Issues

### ISSUE THREAD

**Issue by KriKri98** [NillerMedDild/Enigmatica2Expert#786]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**

Some recipes shown in NEI that they should be craftable in the IE Assembler but the Assembler doesn´t craft them. Crafter Tier 3 doesn´t craft them either.

**Modpack version (Do not use "latest")**

Version 1.54

**Logs**

If applicable, please upload your crash report, or latest.log to [gist](https://gist.github.com/).

**Screenshots**

![2019-02-05_17 22 06](https://user-images.githubusercontent.com/46320871/52287636-d5b21200-296a-11e9-953d-edcf8a167c2b.png)
![2019-02-05_17 24 58](https://user-images.githubusercontent.com/46320871/52287885-5244f080-296b-11e9-8e79-a3cdcd671a97.png)
![2019-02-05_17 26 56](https://user-images.githubusercontent.com/46320871/52287861-46f1c500-296b-11e9-9b7e-a94dd895a28d.png)
![2019-02-05_17 24 42](https://user-images.githubusercontent.com/46320871/52287876-4ce7a600-296b-11e9-8318-c16ed385cce5.png)

**Additional context**

The recipes are from Pam´s Harvestcraft. I tried to automate Ploughman´s lunch. Other recipes worked in the Crafter Tier 3 and Assembler.

**Comment by NillerMedDild** [comment]
The internal inventory of your Crafter Tier 3 is full, and the recipe is set to output into the internal buffer, so that's the reason. The Assembler I will investigate, but I have an idea that you need to use the right-most recipe first, then middle if you want to chain recipes.

**Comment by KriKri98** [comment]
I realised that too and changed the inventory so that every crafting ingredient is there. Still no crafting.

**Comment by KriKri98** [comment]
I used the Assembler before for cake automation for Botania. Sugar recipe is on the left and cake is in the middle slot. It works fine. Even if i needed the right slot for chain recipes then it would at least craft the salt into its output slot.

**Comment by MorganSimic** [comment]
I assume the issue is as before, that the salt recipe is requiring a bucket of water or now fresh water specificly and not 1 bucket of water as a fluid. This is why the assembler can not craft it. You could try making fresh water and craft salt from that but I think that will have the same issue.

**Comment by KriKri98** [comment]
Tried that just now. The Assembler can craft the Fresh Water from a water bucket (its own internal tank) but even with the Fresh Water it doesn´t craft the salt.

**Comment by MorganSimic** [comment]
Okay, that's good news. At least somewhat. That means the salt recipe is weird somehow. I remember there being issues with that before. I know that my rf tools crafter does craft salt with a pot and fresh water without any problems

**Comment by KriKri98** [comment]
I would guess it´s the Pam´s cooking devices that are the problem here.

**Comment by KriKri98** [comment]
I tried the salt recipe in the Crafter Tier 3 with Fresh Water and the Pot, but it didn´t craft that either.

**Comment by MorganSimic** [comment]
For me it does work fine. Just tried that now. Recipe is programmed for pot and fresh water and set to ExtC. Works like a charm.

**Comment by KriKri98** [comment]
Ok, so i changed my Grape Juice to consume All Items and output to Output slots. That worked.

**Comment by NillerMedDild** [comment]
I can't get the Assembler working either, I seem to remember this kind of recipe just being a limitation of the Assembler.

**Comment by Terpo** [comment]
I had the same problems a few days ago and found something in the repo of Immersive Engineering. 

In short: Astral Sorcery adds some NBT stuff to items so that the Assembler and other blocks get problems with crafting of reusable items.

https://github.com/BluSunrize/ImmersiveEngineering/pull/3330
The discussion was placed in this issue: https://github.com/BluSunrize/ImmersiveEngineering/issues/3122
