### ISSUE TITLE
Advanced Rocketry SMP Client-side crashes

### ISSUE THREAD

**Issue by kythorn** [NillerMedDild/Enigmatica2Expert#787]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**

AR causes client side crashes in an SMP environment

**Modpack version (Do not use "latest")**

v1.54

**Logs**

If applicable, please upload your crash report, or latest.log to [gist](https://gist.github.com/).

https://gist.github.com/kythorn/b5a5a335c160aaae331671d23ace9211

**Screenshots**

N/A

**Additional context**

In an SMP environment, a client-side crash is experienced when interacting with AR Rockets when performing activities involving accessing inventories, or trying to install/configure guidance chips.

I also ran into this testing a different pack, it looks like an Advanced Rocketry / Mekanism interaction that only manifests on servers.

ZMaster already has an experiment build out to address this, You may want to keep an eye on their issues to incorporate the fix into E2E. 

https://github.com/zmaster587/AdvancedRocketry/issues/1509
https://github.com/Vyraal1/FTB-Interactions/issues/369
https://github.com/aidancbrady/Mekanism/issues/5271

**Comment by NillerMedDild** [comment]
That's one hell of a report, thanks for letting me know!
