### ISSUE TITLE
Biomes O´Plenty Ores dont generate on default settings

### ISSUE THREAD

**Issue by Scoaex** [NillerMedDild/Enigmatica2Expert#788]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
Biomes O´Plenty Ores (Rubyte,Peridot,...) dont generate on default World Settings.
I know that you can get them through Sieving aswell, but why shouldnt they spawn in Vanilla Biomes?

**Modpack version (Do not use "latest")**
1.54

**Logs**

If applicable, please upload your crash report, or latest.log to [gist](https://gist.github.com/).

**Screenshots**

**Additional context**

**Comment by NillerMedDild** [comment]
The BoP Generation type is what actually turns the ore generation on.
