### ISSUE TITLE
Observatory block from Advanced Rocketry not craftable

### ISSUE THREAD

**Issue by DrSpyse** [NillerMedDild/Enigmatica2Expert#789]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**

It is impossible to craft the Observatory multiblock from advanced rocketry because the actual observatory block is not craftable. The machine frame is replaced with a missing texture thing in JEI.

**Modpack version (Do not use "latest")**

1.54

**Logs**

If applicable, please upload your crash report, or latest.log to [gist](https://gist.github.com/).

**Screenshots**

**Additional context**

**Comment by NillerMedDild** [comment]
Thanks for the report :)

**Comment by NillerMedDild** [comment]
https://github.com/zmaster587/AdvancedRocketry/issues/1511
