### ISSUE TITLE
UU-Matter Value for Machine Structure

### ISSUE THREAD

**Issue by power-spike** [NillerMedDild/Enigmatica2Expert#792]
**Is your feature request related to a problem? Please describe.**
Currently Most gates have a UU Matter Value for their main item (the gated item, i.e:- steel casing, iron case).

Currently the Machine Structure (The Gated item) from Advanced Rockery does not have a UU-Matter value.

**Describe the solution you'd like**
Add a UU Matter Value for the Machine Structure (and perhaps the Advanced machine Structure).

**Additional context**
None.

**Comment by power-spike** [comment]
(Please note - This is for the Skyblock version currently - Just realized you have a dedicated repo for skyblock)

**Comment by NillerMedDild** [comment]
The Machine Structures would be too easy to make with UU-matter :)
