### ISSUE TITLE
Veinmined Hill Cherry Leaves

### ISSUE THREAD

**Issue by MayhemGang** [NillerMedDild/Enigmatica2Expert#793]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
Veinmined Hill Cherry Leaves with a silk touch osmium-allumite mattock,
crashes every time I open my inventory now.

**Modpack version (Do not use "latest")**
1.54
**Logs**
Literally the crash logs aren't even generated. 
**Screenshots**

**Additional context**

**Comment by MayhemGang** [comment]
EDIT:
Found crash report finally, had to dig around, but just found nothing.
So I replicated the glitch to get the report.
https://pastebin.com/yu6R5g9f

**Comment by NillerMedDild** [comment]
Thanks for the report, it appears to be this issue: https://github.com/ForestryMC/ForestryMC/issues/2336

**Comment by MayhemGang** [comment]
I even tried dying and grabbing my stuff back, didn't work. I think I should just try to set a keybind, move my items out somehow, and make sure not to get that "glitched" thing in my inventory again.
It is risky, since if I accidentally bring it to my hotbar, i will never be able to play again in that world.

**Comment by MayhemGang** [comment]
If this is fixed in the updates, would that mean I will be able to play in the same world? Or should I give up hope?

**Comment by MayhemGang** [comment]
Issue seems to be fixed(not the bug itself), there is a solution
Use MCEdit2 to delete/convert the items into known non-broken items
