### ISSUE TITLE
Add Witherproof Glass Recipe

### ISSUE THREAD

**Issue by OmaiGrundles** [NillerMedDild/Enigmatica2Expert#794]
**Is your feature request related to a problem? Please describe.**
This is an extremely small issue but..

I was working on a small wither farm in my base, and I wanted to actually be able to see the withers be killed, kind of like some madman's fish tank. Unfortunately the illumination wand's warding ability does not seem to work on transparent blocks(and there isn't anything in AS configs to change that), and the witherproof glass from mystical agriculture is not craftable.

**Describe the solution you'd like**
Again this is a pretty small thing, but it would be nice to add a recipe for the witherproof glass for those of us who want to watch withers die... for some reason.

**Additional context**
I mean unless you can somehow get the illumination wand to work on transparent blocks... :)

**Comment by NillerMedDild** [comment]
Sure thing, I'll make a recipe for the glass.

**Comment by MorganSimic** [comment]
Just FYI, Hardened Glass from Thermal is witherproof.

**Comment by NillerMedDild** [comment]
IT IS?!

**Comment by MorganSimic** [comment]
Yes, if nothing major has changed the last few months it is.
