### ISSUE TITLE
Add hint about getting titanium in the JEI page for Rutile Ore

### ISSUE THREAD

**Issue by OmaiGrundles** [NillerMedDild/Enigmatica2Expert#795]
**Is your feature request related to a problem? Please describe.**
Now this is probably just some result of how my mind works, but it took me ages to actually figure out how the proper way to get titanium ingots was. I thought for months that I had to progress to advanced rocketry to get it because the description for Rutile ore states 'only available in other planets'.

The reason I never found out how to get Titanium ingots the normal way is because my mind never even conceived of the possibility of the ingots being obtainable without the ore. This led to me assuming that the secret way of getting Rutile was actually a configuration issue and reported on it a while back because I thought it was such a late-game resource.

It wasn't until I realized that I *needed* titanium to even get off-planet that I had to ask the discord for help because I was so confused on how I was supposed to even get the darn things 'properly'

**Describe the solution you'd like**
Adding a note about titanium ingots being obtainable in the page for Rutile ore would help clear the issue for people like me who never thought about the possibility of the Ingot being made the way it is in this pack.

**Additional context**
Nothing additional to say other than I have been loving this pack, have 200+ hours in it, and to keep up the amazing work. 😄

**Comment by NillerMedDild** [comment]
I'll see what I can do, it is confusing atm :)

**Comment by NillerMedDild** [comment]
Changed the JEI Description to `Rutile Ore only generates on other planets, but Titanium Ingots are craftable.`
