### ISSUE TITLE
Nitrogen JEI Hint

### ISSUE THREAD

**Issue by Lohoydo** [NillerMedDild/Enigmatica2Expert#796]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
Nitrogen is required to make the cubic boron nitride for the Resonant Cell Frame, however I cannot find a way to make Nitrogen.  JEI only lists the Fluid Transposer and Squeezer as ways to obtain it... but you already have to have a tank etc. containing it.

Interestingly, for some reason the Fluid Transposer recipes for extracting Nitrogen from any creative tier tanks report an output of a creative tank filled with Uranium Slurry.

**Modpack version (Do not use "latest")**
1.54

**Logs**

If applicable, please upload your crash report, or latest.log to [gist](https://gist.github.com/).

**Screenshots**

**Additional context**

**Comment by Rdjrjqouqcu** [comment]
If you search in JEI for nitrogen there's a Nuclearcraft Nitrogen Collector. It is the only way to produce nitrogen. I don't know if it's possible to add it to the recipe list for nitrogen so it is clearer.

**Comment by Lohoydo** [comment]
At the very least, it should be possible to add in a JEI note like there is for things like Ludicrite Ingot (which just says the block is craftable)

**Comment by NillerMedDild** [comment]
I'll look into it :)
