### ISSUE TITLE
Consistent week long crashing with no answers. 

### ISSUE THREAD

**Issue by HolRye** [NillerMedDild/Enigmatica2Expert#797]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Unknown, persistent crash upon loading game. No issues beforehand, just one day crashed and now immediately crash upon entering the server. I had my friend stand next to me, and my character spawned in for about 10 seconds, and them dissipated immediately. I've looked everywhere to find a solution, but to no avail. Please help. **

**Enigmatica2Expert 1.54**

Here is a shortened crash report:

The game crashed whilst unexpected error
Error: java.lang.UnsupportedOperationException

**
[crash-2019-02-02_17.42.54-client.txt](https://github.com/NillerMedDild/Enigmatica2Expert/files/2838770/crash-2019-02-02_17.42.54-client.txt)
**

** I don't have any, and there isn't enough information for them to tell much**

**No other problems except being unable to play on the server. I had been playing for about 2 weeks with no issues, and this started last Friday. I think maybe /Killing my character might help if its due to where my characters position is, or if there is some kind of bugged item in my inventory causing the issue. Either way, any help is greatly appreciated, as Love this server and the people on it. If anymore information is needed, please let me know. It also might have something to do with thaumcraft, since the crash occurred the first time in my thaumcraft base, and I haven't stayed connected long enough to leave the area**

**Comment by scarfkitten** [comment]
Try changing the highlighted option in codechickenlib.cfg? 
https://i.imgur.com/cTxU1XC.png

Also, try not to store a bunch of complicated items like mob capture tools and weapons etc in a dev/null - use a backpack or something. Judging by the crash log, it doesn't like the devnull trying to render something in the null in addition to rendering a mekanism factory.

Failing that, try getting your friend to break/remove all mekanism machines in the nearby area, that might give you enough time to fix the devnull.

**Comment by NillerMedDild** [comment]
You need to remove your Dank/Null with NBTExplorer, and I highly recommend not putting things like animal containers in there. Only put regular blocks in.

**Comment by NillerMedDild** [comment]
https://github.com/p455w0rd/DankNull/issues/155

**Comment by HolRye** [comment]
I forgot to say thanks for the help! so, thanks for the help!
