### ISSUE TITLE
constantly being slammed with 1 specific error message in the logs

### ISSUE THREAD

**Issue by antrobot1234** [NillerMedDild/Enigmatica2Expert#798]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
my game logs are being clogged with 1 specific error message that, while it isn't lagging me, is making my life a chore for actually finding other issues
**Modpack version (Do not use "latest")**
1.54
**Logs**
If applicable, please upload your crash report, or latest.log to [gist](https://gist.github.com/).
[error in question](https://gist.github.com/antrobot1234/0b5bb3930fd80f77ae51d0112242779a)
**Screenshots**

**Additional context**

**Comment by NillerMedDild** [comment]
I've tried to get this fixed without luck in the past, no luck yet.
