### ISSUE TITLE
Atomic disassembler has no mining level, can't break stone.

### ISSUE THREAD

**Issue by Electrofried** [NillerMedDild/Enigmatica2Expert#8]
#### Issue Description
Atomic disassembler seems to have no mining level, and as such can't even break stone.
#### What you expected to happen
Be able to break up to a certain level of ore/stone with the item
#### Modpack version (Do not use "latest")
1.03a
#### Your most recent log file where the issue was present

[pastebin/gist/etc link here]

**Comment by NillerMedDild** [comment]
Will fix, thank you.

**Comment by NillerMedDild** [comment]
Done!
