### ISSUE TITLE
Immersive Petroleum pump-jack not working and Advanced Rocketry rolling machine not recognizing lubricant 

### ISSUE THREAD

**Issue by Neoxes64** [NillerMedDild/Enigmatica2Expert#80]
#### Issue Description 
(See title) Pump-jack only pumping one bucket before needing to be broke and reformed. Rolling machine not working in general. It also seems to think water is lubricant in the tank but, still will not craft with either

#### Crash Report N/A

[pastebin/gist/etc link here]

**Comment by Lukas45** [comment]
Pump Jack needs a Fluid Pipe down to bedrock to function
And AR has had a lot of issues lately, as a mod. Hopefully they'll get it fixed soon

**Comment by NillerMedDild** [comment]
Please make seperate issues for -seperate issues- in the future.

To clarify, did you supply the Rolling Machine with Lubricant for crafting?

**Comment by Neoxes64** [comment]
Thanks for the heads up with the pump I will try that and yes I tried both water and lubricant for crafting. I will also endeavor to keep the issues separate from now on my bad.

**Comment by Lukas45** [comment]
We heard from our other server members having the same issue with the Rolling Machine - Advanced Rocketry is acting up a lot these last versions

**Comment by Neoxes64** [comment]
I was wondering though will there be any other way to make the Advanced rocketry sheets in the meantime? Without them you can't make some of the Advanced rocketry items such as tanks and satellites.

**Comment by NillerMedDild** [comment]
The recipes will use water in update 1.26 - Apparently the Rolling Machine is hardcoded to only accept water.
