### ISSUE TITLE
Death from self-sacrifice dagger does not create grave, all items lost

### ISSUE THREAD

**Issue by omglolbah** [NillerMedDild/Enigmatica2Expert#800]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
Dying to the self-sacrifice dagger from blood magic creates no grave, no inventory snapshot that can be restored but spawns the player with an empty inventory.

**Modpack version (Do not use "latest")**
1..54

**Logs**
Journeymap logs the death and creates a waypoint, that is all that is in the log.

**Screenshots**
**Additional context**
This has happened twice for me now, last time was right after a backup so not a big deal, but this time I lost 6 hours of work (I log off the single-player world when doing certain other things, so no backup was triggered as no session was longer than the default 2 hour backup interval)
I would consider this a rather high risk bug and would consider disabling the graves mod or at the very least put a big warning in the changelog regarding it. As a mitigation I've dropped my backup interval to 0.5 to avoid the impact should this happen again.

**Comment by scarfkitten** [comment]
Just an FYI if you experience item loss due to graves not spawning in the future, try the command "/tmg_restore [playername] latest" - there's even a neat little tip in the loading screen tips for this! Obviously doesn't work if you're not an op or don't have cheats enabled, but you can open the world to LAN to enable cheats to get around that.

**Comment by NillerMedDild** [comment]
Damn, that sucks, I'll investigate :)

**Comment by omglolbah** [comment]
tmg_restore does not work because the mod never picks up the death at all.

What I ended up doing was restore the 6 hour old backup to a new world name, join the world, do /kill to generate a fresh death snapshot, log out and back into world where I lost stuff and did the reload. That let me keep the world but restore just the inventory so a bit of a workaround to lessen impact.

From what I know Blood magic hookes the death function to apply some debuffs when you respawn to avoid people just spam-dying to fill the altar.

**Comment by draeath** [comment]
You should be able to port over your player dat file from a backup, this would put you back in the world at that same position you were on at that time with the old inventory content.

**Comment by NillerMedDild** [comment]
https://github.com/WayofTime/BloodMagic/issues/1351

**Comment by Frikkle** [comment]
> WayofTime/BloodMagic#1351

This seems to have been merged.

**Comment by NillerMedDild** [comment]
We'll have to see, it's marked as possible fixes.

**Comment by MaxNeedsSnacks** [comment]
Sounds good to me
