### ISSUE TITLE
Zombie Generator VS Frank'n'Zombie Generator

### ISSUE THREAD

**Issue by Shadow59ru** [NillerMedDild/Enigmatica2Expert#801]
**Is your feature request related to a problem? Please describe.**
Zombie Generator with Octadic Capacitor generates 480RF/t
Frank'n'Zombie Generator with Octadic Capacitor generates 180RF/t

**Describe the solution you'd like**
Tweak Frank'n'Zombie Generator. It's more expensive.

**Additional context**

**Comment by NillerMedDild** [comment]
I'll get that done :)
