### ISSUE TITLE
Memory leak 

### ISSUE THREAD

**Issue by Tawnyman** [NillerMedDild/Enigmatica2Expert#802]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Question or Issue**

There seams to be a memory leak

**Modpack Version**

1.54

**Additional Context**

After playing for about 5-6 hours this happens

![image](https://user-images.githubusercontent.com/19567087/52437284-4a02d600-2b62-11e9-9749-6967c4ad5ee1.png)

The lowest it go's is in the mid 80' closing and relaunching the pack gets 

![image](https://user-images.githubusercontent.com/19567087/52438089-335d7e80-2b64-11e9-82b8-1b6a22337fc5.png)

to

![image](https://user-images.githubusercontent.com/19567087/52438120-440df480-2b64-11e9-983a-a22c14a1ee59.png)

Is there anything I can update or any settings I can change to help with this?

**Comment by NillerMedDild** [comment]
Hey o/ 
There are a few things you can do, the most efficient would be to use these java parameters:
`-XX:+UseG1GC -Dsun.rmi.dgc.server.gcInterval=2147483646 -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M`

Without those parameters, allocating too much RAM can actually cause memory leaks.

**Comment by Tawnyman** [comment]
These are what I am using at the moment when getting the leak

-Xmx9216m -Xms256m -XX:PermSize=256m -Dminecraft.applet.TargetDirectory="C:\Users\christopher\Documents\Curse\Minecraft\Instances\Enigmatica 2 Expert" -Dfml.ignorePatchDiscrepancies=true -Dfml.ignoreInvalidMinecraftCertificates=true -Duser.language=en -Duser.country=US -XX:+UseG1GC -Xmx9G -Xms4G -Dsun.rmi.dgc.server.gcInterval=2147483646 -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M

If no one else is having problems like this could it be a bad install of the pack or java?

**Comment by NillerMedDild** [comment]
Your parameters are setting allocated RAM twice for some reason. Anyway, try reducing the RAM allocated. Increasing it would probably delay the leak further, but decreasing could remove it.

**Comment by Tawnyman** [comment]
Dropping my ram to 6g seams to have fixed the leak Thank you very much for the help :) The twitch launcher was responsible for the ram being allocated twice as it added some of its own parameters that I missed.

**Comment by NillerMedDild** [comment]
Glad to hear it, thanks for the update :)
