### ISSUE TITLE
Dupe Thaumcraft Amber

### ISSUE THREAD

**Issue by dclay1983** [NillerMedDild/Enigmatica2Expert#805]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
You can duplicate Amber by making a block of amber out of 4 amber, running it through a SAG Mill for 9 amber dust, and using the enrichment chamber to make it Amber. This gives 9 amber from 4.

**Modpack version (Do not use "latest")**
1.54

**Logs**

NA

**Screenshots**
![2019-02-08_11 35 27](https://user-images.githubusercontent.com/17584306/52491757-d1b60800-2b95-11e9-8ec6-56404adb7177.png)

![2019-02-08_11 35 37](https://user-images.githubusercontent.com/17584306/52491780-dda1ca00-2b95-11e9-9d95-c7801437c3d6.png)

![2019-02-08_11 35 48](https://user-images.githubusercontent.com/17584306/52491786-e1355100-2b95-11e9-94c7-5ac32d35bdd3.png)

**Additional context**

**Comment by NillerMedDild** [comment]
Thank you, I'll get that fixed :)

**Comment by NillerMedDild** [comment]
I decided to remove Amber Dust entirely.
