### ISSUE TITLE
Not Sure if intended or not, but with Nuclear Craft you can turn Charcoal into Coal

### ISSUE THREAD

**Issue by kaedenrussell** [NillerMedDild/Enigmatica2Expert#806]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
Using the Preasurizer from Nuclear Craft you can turn Graphite dust into Coal, but you can make graphite out of charcoal. I don't know if this is intended, because it seems an easy way to gets tons of coal and coal coke before you would get access to stuff like Digital Miner and Mystical Agriculture. 

**Modpack version (Do not use "latest")**
1.53

**Logs**

If applicable, please upload your crash report, or latest.log to [gist](https://gist.github.com/).

**Screenshots**

**Additional context**

**Comment by NillerMedDild** [comment]
It is intended, thanks for checking :)
