### ISSUE TITLE
Thermal Expansion Resevoir can not put its liquid inventory into Drums from Extra Utilities 2

### ISSUE THREAD

**Issue by kaedenrussell** [NillerMedDild/Enigmatica2Expert#807]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
This is a Mod Issue between Thermal Expansion and the Drums from Extra Utilities 2.
The Reservoir from thermal expansion usually puts all of its liquid inventory into an applicable take if you right click on that tank. It doesn't work this way for drums and when you put it on empty mode and try to empty its inventory into an Extra Utils 2 Drum it will put a bucket in and then when you click to put another bucket in, it take the first bucket out. This means you can not put more than one bucket into a drum from a Thermal Expansion Reservoir

**Modpack version (Do not use "latest")**
1.53

**Logs**

If applicable, please upload your crash report, or latest.log to [gist](https://gist.github.com/).

**Screenshots**

**Additional context**

**Comment by NillerMedDild** [comment]
That sounds like an annoying bug, I'll see what I can do.

**Comment by NillerMedDild** [comment]
It's meant to work that way apparently.
https://github.com/rwtema/Extra-Utilities-2-Source/issues/10

**Comment by kaedenrussell** [comment]
Ah I see, that is  just an unfortunate coding issue that doesn't seem to
have a simple solution. So drums don't work with any multi bucket storage
items, you just have to pipe into them
