### ISSUE TITLE
Quantumsuit Bodyarmour Recipe Jetpack 

### ISSUE THREAD

**Issue by blarghhh** [NillerMedDild/Enigmatica2Expert#808]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
The recipe for the QuantumSuit BodyArmour doesnt allow fully charged jetpacks.

Charged lapotron crystal and flux-infused is okay.

**Modpack version (Do not use "latest")**
1.23

**Logs**

N/A

**Screenshots**

**Additional context**

**Comment by NillerMedDild** [comment]
Thanks for the report, I'll fix it asap.

**Comment by NillerMedDild** [comment]
I see this report was meant for E2:ES, moving it
