### ISSUE TITLE
Metal press crash

### ISSUE THREAD

**Issue by Miky691** [NillerMedDild/Enigmatica2Expert#809]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
My game crashed when i placed any kind of ingot in a hopper connected to the immersive engineering metal press. If i try to open the world my game immediatly crashes again. I had been doing this for quite a while and only now this error occurred. This error happened with an iron ingot and then i checked on another world with different ingots and this happened again.The press was set up for making plates.

**Modpack version (Do not use "latest")**
1.54

**Logs**

If applicable, please upload your crash report, or latest.log to [gist](https://gist.github.com/).
[crash-2019-02-10_13.50.40-server.txt](https://github.com/NillerMedDild/Enigmatica2Expert/files/2848900/crash-2019-02-10_13.50.40-server.txt)

**Screenshots**

**Additional context**

**Comment by Miky691** [comment]
the problem fixed itself somehow but now the metal press works at normal speed

**Comment by Miky691** [comment]
i downloaded a cofig files from enigmatica 2 expert and pasted them in my files and that fixed it but i still don't know what caused the problem since i din't change any immersive engeneering cofig

**Comment by NillerMedDild** [comment]
A bad install I suppose? Glad it's working 👍
