### ISSUE TITLE
(question) thermal expansion sawmill

### ISSUE THREAD

**Issue by NarigudoBR** [NillerMedDild/Enigmatica2Expert#811]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Question or Issue**
is it supposed to get half of the output of a mekanism sawmill?
ex. 1 wood = 3 planks while in mk sawmill: 1 wood = 6 planks. both with 100% sawdust

**Modpack Version**
1.54

**Additional Context**

![2019-02-10_15 19 41](https://user-images.githubusercontent.com/5056170/52536886-5005dc00-2d47-11e9-959e-90a16391166f.png)

**Comment by NillerMedDild** [comment]
Please use the search function.
#791
