### ISSUE TITLE
Integrated Dynamics Squeezer support for Aluminum and Osmium

### ISSUE THREAD

**Issue by Kallado** [NillerMedDild/Enigmatica2Expert#812]
**Is your feature request related to a problem? Please describe.**
I've been using the Integrated Dynamics Squeezer for early game ore doubling, but it's a bit inconsistent in what ores it processes. It's able to process all the early game ores with the exception of aluminum and osmium.

**Describe the solution you'd like**
Add squeezer recipes for Aluminum ore and Osmium ore.

**Additional context**
N/A

**Comment by NillerMedDild** [comment]
Sure thing :)
