### ISSUE TITLE
Nutrition Server Issues

### ISSUE THREAD

**Issue by Kortako** [NillerMedDild/Enigmatica2Expert#813]
**Issue Description**

I'm playing on my own private server with 2 other friends, and we each have fairly high (>90%) nutrition values for all of our nutrition categories.  When only 2 of us are logged in, all is fine, but if the third logs in what will often happen is the Nutrition buffs will expire for some of us, and we'll lose any extra hearts granted by that except for the ones you get for eating 10 types of food.  If one of us logs out, then the nutrition starts "recalculating" and we get our buffs/hearts back.

**Modpack version (Do not use "latest")**

1.54

**Logs**

N/A

**Screenshots**

I can add screenshots if needed, but I need to wait until all of us are on the server at the same time for it to happen again.

**Additional context**

This happens fairly often when all of us are online and even a server restart won't fix this.  It seems to only happen when the third player joins, and it doesn't seem to be any player in particular causing it.  I'm pretty sure this only happens on a server as far as I'm aware, and I've noticed at least one other person mentioning the same issue on the Discord support channel.

**Comment by NillerMedDild** [comment]
I'll report this on the Nutrition issue tracker - Would you mind if I ping you over there, so you can answer any question the dev might have?

**Comment by NillerMedDild** [comment]
https://github.com/WesCook/Nutrition/issues/139

**Comment by Isolol** [comment]
We've also had this happen a few times, but it doesn't seem to be limited to just a third person joining/leaving. Sometimes it's the 4th or even the 2nd person. It removes all SoL hearts as well.

**Comment by NillerMedDild** [comment]
Hmm if it removes SoL hearts it's probably not a Nutrition issue.

**Comment by Isolol** [comment]
My apologies, I was corrected to state that it is only the nutrition buffs that disappear. SoL hearts seem to stay.

**Comment by NillerMedDild** [comment]
Oh okay :P

**Comment by Soyfya** [comment]
I've also had this problem with my siblings (version 1.55). Just got to astral attunement so I'll see if I can figure out if health gained through that is messed up too, but I doubt it will be. Also, I suspect that hearts added by Pam's "eat 10 different things" is working properly, although I may have found another bug there (gotta check to make sure I'm not just crazy).

**Comment by Zidane3838** [comment]
I have a similar issue with my health... almost every time I log in I'm down a bar or two of health. Here's my health & hunger at full... not really sure how much health that is though...
![2019-02-21_13 02 13](https://user-images.githubusercontent.com/1594255/53194527-2c5d5400-35d9-11e9-8d65-a7d6e34afeeb.png)
