### ISSUE TITLE
Black Quartz blocks to Black quartz

### ISSUE THREAD

**Issue by Cooper1dog** [NillerMedDild/Enigmatica2Expert#814]
I was having storage issues as I set up early-mid game so I compressed a bunch of resources into blocks including Black Quartz. Now I am unable to craft Black Quartz from Black Quartz Blocks.

I am requesting that Black Quartz be craftable from Black Quartz Blocks.

Does this seem feasible and reasonable?

**Comment by MorganSimic** [comment]
What version are you on? This should have been resolved in 1.42a and closed issue #349.

**Comment by MorganSimic** [comment]
I see. It wasn't fixed on a crafting level but on storage drawer level. I also think backcrafting should be possible without a drawer. But for now, with a compacting drawer you can get black quartz from blocks.

**Comment by NillerMedDild** [comment]
Well that's odd, I'll get it fixed :)
