### ISSUE TITLE
Completing Gate: applied energistics without the controller block

### ISSUE THREAD

**Issue by HSavageheart** [NillerMedDild/Enigmatica2Expert#815]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
while playing i was able to unlock the AE gate without the controller.
sadly i dont know how i unlocked it. i am on a server witout OP or any perks.
hoping that this could be fixed in the future.

**Modpack version (Do not use "latest")**
1.54

![download](https://user-images.githubusercontent.com/47013090/52555389-d4a93680-2de9-11e9-87e0-057e4fc95c4f.png)
![download3](https://user-images.githubusercontent.com/47013090/52555390-d541cd00-2de9-11e9-8d0d-84f4c303bbb0.png)

**Comment by NillerMedDild** [comment]
Did you have an Energy Acceptor?

**Comment by HSavageheart** [comment]
yea

**Comment by HSavageheart** [comment]
used it for the growth accelerator

**Comment by NillerMedDild** [comment]
That would be the reason, there's a little arrow in the bottom corner to the right, if you click it it will show you the other task.

**Comment by HSavageheart** [comment]
but that doesnt make sence

**Comment by HSavageheart** [comment]
why adding the controller if the acceptor is in the recipe

**Comment by NillerMedDild** [comment]
It doesn't make sense no, it's from a time where the Energy Acceptor wasn't a part of the Controller recipe. I'll get it fixed :)

**Comment by HSavageheart** [comment]
ok xD
