### ISSUE TITLE
Cyclic Hydrator creates same result from any input (Temp fix for Sponge recipe)

### ISSUE THREAD

**Issue by Saquesh** [NillerMedDild/Enigmatica2Expert#817]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
The Hydrator from Cyclic only creates white wool regardless of input.

Steps to reproduce:
Place any item into the recipe slot in the Hydrator, output will be white wool.

Tested with:
Wool, Soul sand, Slimeball, Prismarine

How discovered:
Was attempting to make "Sponge", wool kept getting used up first and turned into white wool. Moved different item to top left slot (soul sand), it was consumed and output was white wool

**Modpack version (Do not use "latest")**
1.54

**Logs**

If applicable, please upload your crash report, or latest.log to [gist](https://gist.github.com/).

**Screenshots**

**Additional context**

**Comment by Saquesh** [comment]
The Hydrator from Cyclic only creates white wool regardless of input.

Steps to reproduce:
Place any item into the recipe slot in the Hydrator, output will be white wool.

Tested with:
Wool, Soul sand, Slimeball, Prismarine

How discovered:
Was attempting to make "Sponge", wool kept getting used up first and turned into white wool. Moved different item to top left slot (soul sand), it was consumed and output was white wool

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
Damn, the Hydrator is broken O_O

**Comment by NillerMedDild** [comment]
https://github.com/Lothrazar/Cyclic/issues/1059

**Comment by HSavageheart** [comment]
cant the recipe be changed like in order to make the sponge lets use yellow rockwool if its still in thermal

**Comment by HSavageheart** [comment]
untill cyclic fixes it

**Comment by NillerMedDild** [comment]
Sure thing

**Comment by spdkils** [comment]
It just gets stuck on the last recipe used. Break the block, place it again, or restart the server...

**Comment by NillerMedDild** [comment]
Temp fix is done.
