### ISSUE TITLE
Better Questing Loot Chests produce Dungeon Loot

### ISSUE THREAD

**Issue by KCtops100** [NillerMedDild/Enigmatica2Expert#818]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
Hello,  I am having loot chest problems with better questing.  Instead of getting the modpack configured loot, I am getting the dungeon loot (which I assume is default).  Appreciate the response in advance.

**Modpack version (Do not use "latest")**
1.54

**Logs**

If applicable, please upload your crash report, or latest.log to [gist](https://gist.github.com/).

**Screenshots**

**Additional context**

**Comment by NillerMedDild** [comment]
The command `/bqs_loot default load` will fix it :)
