### ISSUE TITLE
Crash loading world whenever Compact Machines is used

### ISSUE THREAD

**Issue by Mystborn0828** [NillerMedDild/Enigmatica2Expert#82]
#### Issue Description
If I make a Compact Machine of any size and put anything in it, the next time I save and exit I'm no longer able to load up the world, it crashes with the same error every time (linked below).  If there is a compact machine with nothing in it the crash does not occur.  

#### Modpack version (Do not use "latest")
Enigmatica 2: Expert Version 1.25

#### Crash Report
https://pastebin.com/eehDsKcX

**Comment by NillerMedDild** [comment]
Why did you close this issue?

**Comment by Mystborn0828** [comment]
Sorry I forgot to explain why I closed it. Discovered the issue was related to a specific mod I had added that wasn’t in Enigmatica, so it’s not your problem.

**Comment by NillerMedDild** [comment]
Ah alright.
