### ISSUE TITLE
Update Astral Sorcery to Latest

### ISSUE THREAD

**Issue by Eifekk** [NillerMedDild/Enigmatica2Expert#821]
**Is your feature request related to a problem? Please describe.**
Astral sorcery structure are very very bugged on servers using sponge, most structures don't workk in most places. you have to move them over and over till you find somewhere they do. and you crash when drawing a constellation with spyglass
**Describe the solution you'd like**
Update to latest Astral release which fixes a lot of sponge incompatibilities 
**Additional context**

**Comment by NillerMedDild** [comment]
I will :)
