### ISSUE TITLE
Ultimate Tier Installer from mekansim used wood planks instead of steel casing

### ISSUE THREAD

**Issue by Bentenmaru** [NillerMedDild/Enigmatica2Expert#822]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**

Ultimate Tier Installer requires wood planks to be crafted instead of like the other tier installer that requires a steel casing

**Modpack version (Do not use "latest")**

1.54

**Logs**

If applicable, please upload your crash report, or latest.log to [gist](https://gist.github.com/).

**Screenshots**

**Additional context**

**Comment by NillerMedDild** [comment]
The Ultimate Tier Installer can't upgrade Factories, which is why it is significantly cheaper than the others :)
