### ISSUE TITLE
Add Pam's Beegrub to IF Protein Reactor

### ISSUE THREAD

**Issue by MorganSimic** [NillerMedDild/Enigmatica2Expert#823]
**Is your feature request related to a problem? Please describe.**
Other than trading and some select cooking they have no good use. 

**Describe the solution you'd like**
See title. I think it would be appropiate.

**Additional context**
Maybe even add listAllMeatRaw, i think that encompasses most if not all meat type items in the game.
https://crafttweaker.readthedocs.io/en/latest/#Mods/Industrial_Foregoing/ProteinReactor/

**Comment by NillerMedDild** [comment]
listAllMeatRaw seems like a good idea, sure thing. Thanks.
