### ISSUE TITLE
Lithium dust with Macerator

### ISSUE THREAD

**Issue by felixkraas** [NillerMedDild/Enigmatica2Expert#825]
**Is your feature request related to a problem? Please describe.**
IC2's macerator seems to be the only grinding machine that cannot create lithium dust from lithium ingots. Building a separate machine just for lithium dust is nit really practical. 

**Describe the solution you'd like**
Add a recipe for Lithuim Dust for the macerator.

**Comment by NillerMedDild** [comment]
Thanks for the suggestion, I'll add it.
