### ISSUE TITLE
Game Crash

### ISSUE THREAD

**Issue by manwhowantssayTY** [NillerMedDild/Enigmatica2Expert#827]
**Issue Description**
Crash after open world/start game.

**Modpack version (Do not use "latest")**
Enigmatica 2 Expert version: 1.54

**Logs**
https://gist.github.com/manwhowantssayTY/869144580bea8c592e977cd2286dd6fe
[latest.log](https://github.com/NillerMedDild/Enigmatica2Expert/files/2867331/latest.log)

**Comment by NillerMedDild** [comment]
Delete this file: `E:\Games\TwitchMinecraft\Instances\Enigmatica 2 Expert\saves\Old\advRocketry\planetDefs.xml` :)

**Comment by manwhowantssayTY** [comment]
Oh..Its works. I am open the world, but quest book clear :<
What i am need to do?
Thank you for help!

**Comment by manwhowantssayTY** [comment]
I found fix.

bq_admin load.

Oh... I am return all my achivements by bq_admin complete with id's.
Thank you!
good luck
