### ISSUE TITLE
Animania imbalanced foods

### ISSUE THREAD

**Issue by XavierNero** [NillerMedDild/Enigmatica2Expert#829]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Question or Issue**
Horse meat and seems overpowered, easy to cook, giving full hunger, and 20 saturation, which is higher in hunger and saturation than a lot of late game cooking in harvest craft and leaves a lot of other recipes moot, is this by design? 

**Modpack Version**
1.54

**Additional Context**

**Comment by NillerMedDild** [comment]
That is intentional, because they're hard to breed. The value is too much though, I'll give you that. I'll check if I can change it.

**Comment by XavierNero** [comment]
Thanks, I'll agree it should he higher than vanilla mobs, but I do think the ratio makes me feel I wasted time investing in pams and cooking for blockheads when a guy with a early game tinkers sword is providing better food easily

**Comment by NillerMedDild** [comment]
I'm afraid I can't balance it's values, and I don't think it's so broken that I need to remove it. It does after all only take care of one nutrient :)

**Comment by XavierNero** [comment]
Fair enough, thanks for looking
