### ISSUE TITLE
Rocket Fuel Compression Dynamo Compatibility

### ISSUE THREAD

**Issue by Dark-Matter-001** [NillerMedDild/Enigmatica2Expert#832]
The new rocket fuel recipe in 1.54+ seems a bit unrealistic.  The only rocket I know of that uses tar in reality are hybrid rockets that burn tar and nitrous oxide.

Now since people have probably already build systems to make the new recipe, I'm not saying get rid of it but perhaps add some alternatives with higher mb yield depending on difficulty to make that also mimic real rocket fuels?

#1:  The V2 rocket and other early liquid fueled rockets used Ethanol and liquid oxygen.  Forestry and Immersive engineering both add Ethanol.  This would provide a plant based alternative.  If added this should be the lowest yield as it would be easier to make.

#2:  Several modern rockets (Falcon 9, Soyuz for example) burn RP1 (refined kerosene) and liquid oxygen.  Thermal Foundation's Refined fuel looks like the closest substitute for RP1 and continues from the manufacturing chain that produces the Tar needed for the current new rocket fuel recipe.  Therefore a refined fuel + oxygen = rocket fuel recipes should have a equal  yield as it skips the refining step needed for bitumen, but requires an extra refining step itself.

#3: Next gen rockets are moving to liquid methane + liquid oxygen fuels (SpaceX's Raptor engine and Blue Origin BE-4).  While there is no methane in the pack, Nuclear Craft fluoromethane maybe be the best substitute as several Chemical Rocket/Propellant Hazards documents come up when googling it.  The crafting chain needed to make it looks the most difficult for sure, so if added should produce the highest yield of rocket fuel.

One other thing, that perhaps should be its own request, is then what to do with all the extra rocket fuel?  You only need to go to a plant once to setup a method of teleportation to it.  So perhaps adding rocket fuel as a fuel for various fuel generators (like the compression dynamo etc..) will make it worth continuing to produce?

**Comment by NillerMedDild** [comment]
I like the ideas, but I don't think it would be fair to change the recipe again, especially not right after the last change. Also, Refined Fuel is a valid fuel as it is, albeit without oxygen.

I will be adding Rocket Fuel to the Compression Dynamo though :)
