### ISSUE TITLE
Item duplication with AdvRocketry

### ISSUE THREAD

**Issue by MaxNeedsSnacks** [NillerMedDild/Enigmatica2Expert#833]
**Modpack version**
1.55

**Can the issue be reproduced?**
Yes, quite easily. Steps:

1. Get any **1** ingot of metal that can be made into plates in the Rolling Machine (as well as some lubricant).
2. Make **8** plates in the rolling machine.
3. Smelt down the plates in e.g. a Magma Crucible (for 1 ingot each)
4. Use an Ingot Former to cool down the Molten Metal.
5. 100mB of Lubricant = 7x any metal ingot confirmed.

**Logs**
N/A

**Issue**
As shown above, it's quite easy to octuple any metal ingot you have using just a lubricant (and power). I do like how you can get a ton of plates / rods / stuff from justone ingot once you actually have the materials to do so (aka to actually get a rolling machine and stuff), however, this is obviously not intended behaviour, so I thought I'd point it out.

**Comment by NillerMedDild** [comment]
I did not think this through :P thanks, guess I'll revert the recipes.

**Comment by NillerMedDild** [comment]
Do you mind checking if Metal Sticks can be melted down?

**Comment by MaxNeedsSnacks** [comment]
You mean because you can get those with the Lathe without Lubricant? Nah, already checked, don't worry :P

(I think I gotta revert the changes manually for a second my friend has already made 2000 titanium and he won't stop HALP)

**Comment by NillerMedDild** [comment]
Thanks!

[RollingMachine.zip](https://github.com/NillerMedDild/Enigmatica2Expert/files/2872348/RollingMachine.zip)

Unzip that into `config/advRocketry` = HALP :P
