### ISSUE TITLE
Overlapping Solar Systems

### ISSUE THREAD

**Issue by MaxNeedsSnacks** [NillerMedDild/Enigmatica2Expert#834]
**Modpack version**
1.55

**Can the issue be reproduced?**
Yes, all of them can be reproduced fairly easily

**Logs**
N/A

**Issue**
Since I already reported one issue with AdvRocketry today, I figured I might as well get some other (mostly minor) things out of the way that aren't thaaat important, but still just worth reporting.

- The star systems in the Planet Selector GUI overlap (except for our solar system). I think you simply forgot to change the coordinates on some of these in the XML.
~~- Hostile mobs can still spawn on, say, Mars, but they immediately suffocate due to lack of oxygen and quickly litter the planet's surface with drops during night time (this one may actually be a major bug because the dropped items make the server lag over time.)~~ Duplicate of #380, whoops!
- There seems to be some desync issue when you teleport to / from AdvRocketry dimensions using Mekanism (portable) teleporters. Other forms of teleportation seem to be fine though, e.g. I tested the Draconic Evolution Dislocator.
- This last one may just be me, but Advanced Rocketry in general seems to be causing a little bit of tick lag. I'm gonna install Lag Goggles and inspect stuff further.

**Comment by NillerMedDild** [comment]
1) Woops, fixed, thanks!

2) Duplicate of #380 

3) Dimensional transport can and often is buggy, I'm unable to get the various issues with it fixed it seems

4) Mkay

**Comment by siber-cat1** [comment]
The first issue is still present in 1.56, as Proxima Centauri and HD 42176 still have the same coords. 

Might I recommend the following diff for the stars? It puts them all in different directions, changes their colors to better match our stars, and adds a black hole, so the black hole generator is usable.
[e2e-planetDefs.diff.txt](https://github.com/NillerMedDild/Enigmatica2Expert/files/2898520/e2e-planetDefs.diff.txt)

**Comment by NillerMedDild** [comment]
I'm not too fond of adding a Black Hole at this point, but the coordinate changes would be fine.

Did you verify that the Solar Systems still overlap in a new game?

**Comment by MaxNeedsSnacks** [comment]
Yup, they were still overlapping, just checked ingame. Fixed in my PR
![image](https://user-images.githubusercontent.com/12750501/53334519-5ffdee00-38f9-11e9-8d97-44fa5bf9d459.png)
