### ISSUE TITLE
Reintroduce / Expertify "Airtight Seal" enchantment

### ISSUE THREAD

**Issue by MaxNeedsSnacks** [NillerMedDild/Enigmatica2Expert#835]
**Modpack version**
1.55

**Can the issue be reproduced?**
Yes (It's more of a suggestion / question though)

**Logs**
N/A

**Issue**
Okay, I swear this is going to be my last issue for the day (and it just so happens to be related to AdvRocketry *again*), but when you disabled the internal AR recipes when fixing #441, you also removed the Airtight Seal recipes AR adds to armour sets. With that said, I actually felt like Airtight Seal was a bit of a cheesy recipe anyway because of how easy it was to get (half a titanium ingot and a diamond isn't that bad this late into the game), so **if** you unintentionally removed it and plan on reintroducing it, this may actually be a good time to "expertify" the recipe (also, for your own sanity's and JEI clarity's sake, just have **one** recipe that outputs an Airtight Seal book instead of painstakingly adding it for each piece) if you intend to do so.

If this removal was intentional, though, feel free to just close this issue, I already made like 16 enchanted books with the Actually Additions lens and leather chestplates :P

**Comment by NillerMedDild** [comment]
Damn you :P

You're correct, this one is unintentional as well! I'm liking the idea of a recipe for the enchanted book, I'll add it.

**Comment by MaxNeedsSnacks** [comment]
I might try my hands at an "expertified" version of the Airtight Seal recipe today, do you have any suggestions as to what it could / should require?

**Comment by NillerMedDild** [comment]
Oh sorry, I made the recipe before I read your comment.

# Airtight Seal Enchant
	recipes.addShapedMirrored("Airtight Seal Enchant", 
	<minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: 28 as short}]}), 
	[[<ore:plateTitaniumAluminide>, <advancedrocketry:pressuretank:3>, <ore:plateTitaniumAluminide>],
	[<advancedrocketry:pressuretank:3>, <advancedrocketry:blocklens>, <advancedrocketry:pressuretank:3>], 
	[<ore:plateTitaniumAluminide>, <advancedrocketry:pressuretank:3>, <ore:plateTitaniumAluminide>]]);

**Comment by MaxNeedsSnacks** [comment]
Ah alright, don't worry

If I could add something minor though, I sort of feel like this recipe should require pressurized tanks (as in, the blocks) just because of how large the capacity of the internal oxygen tanks actually is (from what I recall it's about 10 hours which is really just... shenanigans)

**Comment by NillerMedDild** [comment]
Sure, works for me.
