### ISSUE TITLE
Cyclic Harvester harvests pumpkin and melon stems

### ISSUE THREAD

**Issue by xob** [NillerMedDild/Enigmatica2Expert#836]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
In a pumpkin or melon farm, the Cyclic Harvester block is harvesting the stems as well as the blocks, which means that such a farm basically cannot grow anything, as the stem gets harvested long before anything can grow.

There is a config for Cyclic, `S:HarvesterBlacklist`, that by default should include `minecraft:*_stem`. However, in Enigmatica 2 Expert, the blacklist does not contain stems. Adding it back to the blacklist fixes the issue.

**Modpack version (Do not use "latest")**
Enigmatica 2 Expert 1.55

**Logs**
Not applicable.

**Screenshots**
Not applicable.

**Additional context**
No additional context.

**Comment by NillerMedDild** [comment]
Thanks for the report and fix :)
