### ISSUE TITLE
ae2 dense cable only sending 8 channels

### ISSUE THREAD

**Issue by zzyzzyzzx** [NillerMedDild/Enigmatica2Expert#837]
**Modpack version**
1.55

**Can the issue be reproduced?**
unknown

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Issue**
i updated to 1.55 and decided i wanted some of my machines to be on their own side of my controller, so i pop down a dense cable, and pop a p2p on it, run my enderio conduits from one side to the other (like i have for many other builds) and then i hook up the other side with another dense cable and some interfaces, at this point the dense cable
![2019-02-16_13 48 56](https://user-images.githubusercontent.com/5864802/52905694-81bcee00-31f2-11e9-81c5-4b8b6a4b8e22.png)
can only "see" 8 channels

If this is a feature request, feel free to delete the template.

**Comment by NillerMedDild** [comment]
So you're using 8 channels? What is the issue exactly?

**Comment by zzyzzyzzx** [comment]
sorry, currently there is 10 interfaces hooked up, you can see the last 2 are not getting channels the ones with the "red box" in them

**Comment by DrTasslehoff** [comment]
This is normal AE2 behavior. While your dense cable can transfer 32 channels the interfaces will only transfer 8. You need to actually use cables rather than just a large line of interfaces if you actually want more channel usage
