### ISSUE TITLE
Advanced Rocketry Quests - Use Oredict for Coils, Motors, Engines

### ISSUE THREAD

**Issue by Dark-Matter-001** [NillerMedDild/Enigmatica2Expert#838]
So by the time you make it to the Advanced Rocketry quest line, you will easily be able to make the second tier coil/motor or even 3rd+.   Having to make the bottom tier coils/motors for the quest when you'll never use them is a bit of a waste.  Other packs solve this by using the oredict for coils/motors instead.

-Coils are: blockCoil
-Motors are: blockMotor

With the Liquid Fueled Engine required by the quest; I made an Advanced Rocket Engine instead.  Once again I had to make, and never use, the basic version to complete the quest.  These 2 don't already have oredict names so you'd have to add your own via MineTweaker.

**Comment by NillerMedDild** [comment]
I'll get that fixed, thanks :)

**Comment by BattleNachos** [comment]
What is the highest tier coil?  Titanium or Iridium?

**Comment by NillerMedDild** [comment]
Iridium.
