### ISSUE TITLE
Request: non-vanilla dyes usable on non-vanilla shulker boxes

### ISSUE THREAD

**Issue by FredMSloniker** [NillerMedDild/Enigmatica2Expert#839]
At present, while you can use non-vanilla dyes (floral powder, for instance) to dye shulker boxes, you can't use them on the iron/diamond/crystal/etc versions added by Iron Chest; only vanilla dyes work on those. Could you add this feature?

**Comment by NillerMedDild** [comment]
I'll look into it.

**Comment by NillerMedDild** [comment]
I'm not going to add this, it's simply too much work for too little :)
