### ISSUE TITLE
Draconium Ore Broken Recipe

### ISSUE THREAD

**Issue by zMultiKiller** [NillerMedDild/Enigmatica2Expert#842]
**Modpack version**
1.55

**Can the issue be reproduced?**
unknown

**Issue**
the Draconium Ore that comes from a tier 6 void-ore miner no longer can be inputted into Mekanism machines to Triple/Quad opr turn into Slurry. The nether and end versions can however.

This seems to be caused by the fact that overworld Draconium Ore no longer has a oredict on them. (not shown in JEI and no longer mined by digital miners)

**Comment by NillerMedDild** [comment]
Ah right, I'll get that fixed, thanks.

**Comment by MorganSimic** [comment]
Beware, DE itself changed something with their oredicting around.

**Comment by NillerMedDild** [comment]
They reverted that change luckily

**Comment by NillerMedDild** [comment]
This can't be fixed, the ore will not accept <ore:oreDraconium>

**Comment by Nazta** [comment]
I fixed it by removing the entries for draconium in the oredict CT script. 
The oredict dump confirms the normal 3 versions back

**Comment by NillerMedDild** [comment]
Did you also remove `<ore:oreDraconium>.remove(<draconicevolution:draconium_ore:32767>);`?

**Comment by Nazta** [comment]
Yes, and I couldn't find any references to it in the oredict dump.

**Comment by NillerMedDild** [comment]
Oh good! I guess the mod dev fixed it. Thanks for the info.

**Comment by Nazta** [comment]
The latest updates changelog says this was fixed, but the issue is still present, and the lines in OreDict.zs are still there in the client and server downloads.

**Comment by NillerMedDild** [comment]
Yeah I messed up ^^'
