### ISSUE TITLE
Mod Request: JourneyMapFixer (server pack only)

### ISSUE THREAD

**Issue by MaxNeedsSnacks** [NillerMedDild/Enigmatica2Expert#845]
**Modpack version**
1.55

**Can the issue be reproduced?**
Yes

**Logs**
Example: [2019-02-17-4.log.gz](https://github.com/NillerMedDild/Enigmatica2Expert/files/2873087/2019-02-17-4.log.gz)

**Issue**
I'm pretty sure it's already a known issue in this pack that the console keeps getting spammed with
`EncoderException`s by JourneyMap when a player switches dimensions. (known mod issue, see TeamJM/JourneyMap#42)

Today I learned though that there's actually been an addon released to [CurseForge](https://minecraft.curseforge.com/projects/journeymapfixer) which fixes this issue serverside and I therefore thought it may be a good addition to the server pack.

**Comment by NillerMedDild** [comment]
I know about it, but that fix should be incorporated into Journeymap soon, there's been some activity on their issue tracker recently.

**Comment by NillerMedDild** [comment]
I did add it to the server files a few times, but I just keep forgetting ^^'

**Comment by MaxNeedsSnacks** [comment]
Ah, alright then ^^

Other people have been suggesting it won't be fixed for 1.12 anymore (and instead incorporated in 1.13) that's why I suggested to re-add it
