### ISSUE TITLE
MalisisDoors request

### ISSUE THREAD

**Issue by l3ackEyeD** [NillerMedDild/Enigmatica2Expert#846]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
If its not to heavy on the server. I would want it, to get the Design of my base on the next level

**Additional context**
https://minecraft.curseforge.com/projects/malisisdoors

**Comment by NillerMedDild** [comment]
It is pretty heavy unfortunately :/

**Comment by scribbler957** [comment]
How heavy is it? Just curious, I added it to my SSP game for pretty. I might have to start switching to Little Tiles so I can chisel doors instead.

**Comment by NillerMedDild** [comment]
Heavy enough I suppose.
