### ISSUE TITLE
TE Induction Furnance doesn't accept Fused Glass to make Hardened Glases

### ISSUE THREAD

**Issue by VBodrov** [NillerMedDild/Enigmatica2Expert#85]
#### Issue Description
TE Induction Furnance doesn't accept Fused Glass (Ender IO) to make Hardened Glases
#### Modpack version (Do not use "latest")
1.25

**Comment by NillerMedDild** [comment]
Fused Quartz can be used in place of Hardened Glass though, so that recipe is kinda useless. 

I do see it in JEI though, and I can't craft it either, but since it's a pointless recipe, I will not fix it.

**Comment by VBodrov** [comment]
Platinum Hardened Glass is substitute for machine chasis in Modular Machines.

**Comment by NillerMedDild** [comment]
Then use one of the multiple other recipes for it.

**Comment by Kenshij** [comment]
Hardened Glass is the best wither prison, yes i can craft copper hardened glass with the other recipe, its only annoying to dig through bug report to read thats not a bug but a feature ...

**Comment by NillerMedDild** [comment]
To be honest I thought the mod dev would have fixed it by now, but since that isn't the case I'll look into it.

**Comment by NillerMedDild** [comment]
This is impossible for some reason, even with explicit CraftTweaker recipes.

**Comment by john13210** [comment]
version 1.80 and it still doesnt accept fused quartz in induction furnace btw

**Comment by NillerMedDild** [comment]
> 
> 
> This is impossible for some reason, even with explicit CraftTweaker recipes.

I know :P

**Comment by toastonrye** [comment]
v1.82

I just came here to report this issue, but it looks like it's not possible to fix this with craft tweaker?

I am trying to make Hardened Enderium Glass in the induction furnace with enderium blend and fused quartz, which works according to the JEI, but it appears the Thermal Expansion induction furnace won't allow the fused quartz to be inserted.

**Comment by NillerMedDild** [comment]
Correct :)
