### ISSUE TITLE
Add black quartz to lapidary calibration augment 

### ISSUE THREAD

**Issue by MorganSimic** [NillerMedDild/Enigmatica2Expert#855]
If that is even possible. Couldn't find any craft tweaker documentation of that. If not please close this issue. Otherwise I think it would be a neat addition. 
Other additions would include, AS aquamarine and certus quartz.

**Comment by MaxNeedsSnacks** [comment]
It's definitely possible, the @ZenMethod you'd be looking for then would be `addGemFuel(IItemStack stack, int energy)`

https://github.com/jaredlll08/ModTweaker/blob/4e78fddbbddf4f5add21a6dbfb5e82617f422822/src/main/java/com/blamejared/compat/thermalexpansion/dynamos/NumisticDynamo.java#L27-L30

**Comment by MaxNeedsSnacks** [comment]
So far I added Black Quartz, Aquamarines and Certus Quartz. Any other suggestions?
