### ISSUE TITLE
Request: Vulpes Libraries Machine Structures Added To Replicator

### ISSUE THREAD

**Issue by LoneGrey** [NillerMedDild/Enigmatica2Expert#856]
As of currently the Vulpes Libraries Machine Structures are not able to be duplicated by means of UU Matter. It takes a large amount of time to make them by hand and I personally have not found a decent way of auto crafting them. Far easier to craft machine casings, like Steel Casing from Mekanism have been added to the Replicator, why can't Machine Structures be added.

**Comment by DrTasslehoff** [comment]
See #792 it won't be added to the UU process. You can easily set up recipes to automate it all with AE2 so you do not need to do it all by hand

**Comment by MaxNeedsSnacks** [comment]
Honestly, once you figure out a way to get Rosin, Slag and Cinnabar automatically, these Machine Structures are actually pretty easy to make.

I personally just used a cloche with wood seeds to make spruce wood passively which would then go through the Resin Funnel -> Fractionating Still line in a Compact Machine to make Rosin.

And for Cinnabar, anything that automatically mines Cinnabar Ore (plus a decent supply of Cryotheum) will do. (or alternatively gold / redstone ore)

And Rich Slag is even easier, you could just constantly make e.g. Compasses and melt them down with Sand and you have a decent chance of getting Rich Slag (at the cost of 1 Redstone lost per Compass)
