### ISSUE TITLE
Cant create a world

### ISSUE THREAD

**Issue by Surawsome** [NillerMedDild/Enigmatica2Expert#858]
**Modpack version**
1.56

**Can the issue be reproduced?**
Yes

**Logs**
N/A

**issue**
I am unable to make a world. It hangs on loading world and then crashes. I've tried re installing the pack multiple times but I still have the same issue.

**Comment by MaxNeedsSnacks** [comment]
Does it produce any sort of crash log you could give here (or just your latest.log otherwise)

**Comment by Surawsome** [comment]
Was able to fix it by adding way more ram
