### ISSUE TITLE
Chemical reactor airtight seal enchant

### ISSUE THREAD

**Issue by Waisse** [NillerMedDild/Enigmatica2Expert#86]
#### Issue Description

AR Chemical Reactor doesn't apply airtight seal enchantment

#### Modpack version (Do not use "latest")

1.25

https://github.com/zmaster587/AdvancedRocketry/issues/874

**Comment by Waisse** [comment]
I also can't apply airtight seal enchant to quantum armor with book + anvil.

https://i.imgur.com/aSJrCBx.png

Work fine with regular iron armor : 

https://i.imgur.com/yCBmLIK.png

**Comment by NillerMedDild** [comment]
Quantum Armor isn't enchantable.
