### ISSUE TITLE
Unify Sulfur

### ISSUE THREAD

**Issue by Wntermute** [NillerMedDild/Enigmatica2Expert#860]
**Modpack version**
1.55

**Can the issue be reproduced?**
Yes

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Issue**
Every process that makes Sulfur (ore:dustSulfur) makes Thermal Expansion Sulfur except:
 - 3x Mystical Agriculture essence makes 8x IC2 Sulfur Dust
 - 1 Blaze Rod in an Immersive Engineering Crusher makes 4 Blaze Powder (and 1 Immersive Engineering Sulfur Dust 50% of the time)

If this is a feature request, feel free to delete the template.

**Comment by NillerMedDild** [comment]
This'll be easy to fix thanks to your leg-work :D Thanks for the report.
