### ISSUE TITLE
Complement!

### ISSUE THREAD

**Issue by Kuktar** [NillerMedDild/Enigmatica2Expert#861]
I wanted to let yall know how much i am enjoying this pack. I was playing FTB continuum for the last couple months and this was a HUGE breath of fresh air. Keep up the good work! I just updated to 1.59 server and client 1.56 and the change in the questbook really through me off lol so i strated a new world. Is this somthing that will happen often?

**Comment by NillerMedDild** [comment]
I'm glad you're having fun :D

The added Blood Magic quests threw you off? 
Quests aren't added often, but it does happen on occasion.
