### ISSUE TITLE
Request: More Modular Machinery Structures

### ISSUE THREAD

**Issue by Abeswastaken** [NillerMedDild/Enigmatica2Expert#862]
I would like to request new structures for the Modular Machinery mob. I have really enjoyed the pack, my first expert pack. 

I have specifically enjoyed the Modular Machinery automation and would like to have more mods to use with this, Specifically:

AE2 -- Add Inscriber and Crystal Growth Chamber functions. Maybe add some more mid to late game required building blocks, in exchange for being able to skip having to "print" circuits in the inscriber
(1 Diamond + 1 Silicon + 1 Redstone = Engineering Processor) 
Add a Stack crafting function for "printing gold, diamond, and certus"

For the Growth chamber, same speed as a growth chamber, however, double the output?
Maybe add a "faster" way to craft late game storage components, allow for X# of blocks of diamond, gold, certus, (all the required resources to craft it, without the previous steps)

Actually Additions -- Empowering. While I automated with the normal empowerer and later found that extended crafting is far faster, I would still enjoy another challenge. 
Allow for Empowering, with the use of Empowered Oil, allowing the use of a good automated empowered oil setup. (other than power) 

Atomic Reconstructor-- when Autocrafting a large order, for end game items, the atomic reconstructor can easily be backed up. Allow for Reconstruction of items in exchange for some fluid from the Distillation Tower? (Gas or Desial, or both?) 

And the same with AE2, add mid to late game building block requirements 

Botania? A sideline here, I am currently working my way through the Draconic Evolution quest tab, and I have noticed very little Botania required in the end game. Maybe change Wavern Energy Core from a Destabilized Redstone to a crafted using tier 3 runes? 
But give us a Modular Machine to help Autocraft these, double the output of each craft, however, remove the returned runes for higher tiers. add to the structure each of the end game flowers we crafted for quest rewards!

Thank you for such a great pack.

**Comment by NillerMedDild** [comment]
While your ideas are great, I won't be implementing them. It would take far too much work for methods that are already set in stone. I will be using Modular Machinery a lot more in future packs, but I consider the production of E2E done.
