### ISSUE TITLE
Unhide Overclocked Generator JEI Category

### ISSUE THREAD

**Issue by Unnoen** [NillerMedDild/Enigmatica2Expert#863]
**Modpack version**
1.56

**Can the issue be reproduced?**
Yes.

**Logs**
https://pastebin.com/nBkwVDvd

**Issue**
The JEI recipe category "xu2_machine_extrautils2:generator_overclock" doesn't exist and causes a crash.

To fix this, go to the scripts folder, open JEICategories.zs and delete the line containing "xu2_machine_extrautils2:generator_overclock" from the array. (Line 20)

**Comment by NillerMedDild** [comment]
I don't have this issue, did you change anything in the modpack?

**Comment by Unnoen** [comment]
Nothing changed. However OpenJ9 JVM is in use. 

I believe it's to do with OpenJ9's more aggressive error checking/AOT compiling. While Hotspot may skip over it, OpenJ9 will report the error to avoid possible issues in the future.

While it's not crashing in Hotspot, it should be fixed to avoid it possibly popping in it.

(I wrote up infomation on OpenJ9 in Minecraft [here](https://www.reddit.com/r/feedthebeast/comments/as6p87/java_vms_and_you_how_to_reduce_your_ram_and_cpu/))

**Comment by NillerMedDild** [comment]
TODO: Rerun JEICategories and verify the existance or lack of `xu2_machine_extrautils2:generator_overclock`

**Comment by Unnoen** [comment]
I took the liberty of rerunning `/ct jeiCategories` and these are the results: https://pastebin.com/Wn6ufW40

I did notice that not all of the categories are listed when they were hidden by the script, so I had to remove that to get the full results.

**Comment by NillerMedDild** [comment]
I appreciate it, thank you!
