### ISSUE TITLE
Garden Cloche lost items

### ISSUE THREAD

**Issue by Dokend** [NillerMedDild/Enigmatica2Expert#864]
**Modpack version**
Input version here
Enigmatica 2 Expert
1.56
**Can the issue be reproduced?**
Yes/no/unknown
yes
**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Issue**
Input short description of the issue here
When Garden Cloche is broken with Pam's HarvestCraft tomatoes all items are lost excluding the cloche.  

If this is a feature request, feel free to delete the template.

**Comment by NillerMedDild** [comment]
The items aren't in the Cloche when it's placed back down?

**Comment by Dokend** [comment]
nope all gone including the dirt

**Comment by NillerMedDild** [comment]
I don't know if I'd call this a bug to be honest.

**Comment by Dokend** [comment]
well its only the tomatoes from pams so far wheat, potatoes, and lettuce all drop so ikd as well.

**Comment by NillerMedDild** [comment]
Thanks for the report :)
