### ISSUE TITLE
When trying to open the draconic evolution information tablet, it can't download the manifest

### ISSUE THREAD

**Issue by hotdog218** [NillerMedDild/Enigmatica2Expert#867]
**Modpack version**
v1.5.6

**Can the issue be reproduced?**
Yes

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Issue**
Input short description of the issue here
Opening the draconic evolution information tablet opens the Project Intelligence page, (dont know why I think the default draconic is fine), and project intelligence can't download anything it needs. 

It looks like there are 2 .'s at the end of the url that cause it to not work. If you go to https://pi.brandon3055.com/manifest.json everything works fine, but https://pi.brandon3055.com/manifest..json is a 404 page.

I don't know how to change this manually, all help is appreciated.

https://i.gyazo.com/488ec12f6f02624e51ee51724fa8cc48.png

If this is a feature request, feel free to delete the template.

**Comment by NillerMedDild** [comment]
It works fine for me, how did you find that url? :)

**Comment by NillerMedDild** [comment]
And you had an internet connection at the time?

**Comment by Zidane3838** [comment]
Yes I was connected to a server at the time.

**Comment by NillerMedDild** [comment]
Fair enough :P I'll get this reported asap.

**Comment by brandon3055** [comment]
Its not the URL. You can blame the the MC font for the confusion. If you look closer the second dot is actually part of the J. 
Please turn on "devLog" in Brandon's core config and post your console log after a field download.

**Comment by Bulluk** [comment]
Greetings, 

Same issue here.

Here is the the LOG with devLog enabled.

https://pastebin.com/YYsfwSaR

**Comment by Tntdruid** [comment]
Same for me fail to download, internet works fine

**Comment by The-Night-Fox** [comment]
Has this been fixed? having the same issue

**Comment by bblay** [comment]
Is there a workaround for this please? (Enigmatica 2)

**Comment by lekutree** [comment]
install vanillafix
