### ISSUE TITLE
Modular Storage - FPS Loss + Search Field laggy

### ISSUE THREAD

**Issue by Kiyaku** [NillerMedDild/Enigmatica2Expert#868]
**Modpack version**
1.55

**Can the issue be reproduced?**
Yes

**Issue**
Opening the Modular Storage UI from RFTools causes a huge loss in FPS. On top of that, on a server, the input field also behaves weird, doesn't recognize key input sometimes or deletes previously typed letters.

Here is a small video to demonstrate: https://streamable.com/78exg 

Note the FPS in the corner when i look at the storage. Even without items inside it goes down by a lot. While not recording, my in-game FPS go up to around 150, but go down to 15-20 when opening the modular storage interface. At the end of the video you can see my trying to type "Steel Plates" but it keeps overriding keys or deleting them, unless i type very slowly. 

(Also pinging @McJty)

**Comment by NillerMedDild** [comment]
Can you reproduce the issue with only RFTools? :)

**Comment by Kiyaku** [comment]
As in, an empty instance that just contains RFTools? Will give it a shot!

**Comment by Kiyaku** [comment]
Alright just tried it out with just RFTools, no JEI or anything either, and yeah seems to have some big fps loss as well. 

By default, my fps hovered around ~250, opening the UI lowered it to around 100 ish. After inserting several stacks of items and switching to grid view, fps went down to 50. 
Also it seems like using the "generic type" sorting filter lowers it even further for me (went between 30-50). So more of an issue with RFTools, not the pack. 

I tried this with forge 7781.

**Comment by NillerMedDild** [comment]
Excellent, thanks for testing.

**Comment by NillerMedDild** [comment]
I'm afraid I do not have time to troubleshoot this issue, nor report it properly.
