### ISSUE TITLE
loot boxes overpowered?

### ISSUE THREAD

**Issue by Kuktar** [NillerMedDild/Enigmatica2Expert#869]
**Modpack version**
1.69 server
1.56 client

So i am a couple hours into the quest line and i got some legendary loot from the BQ loot boxes. one of wich is called the californium RTG. It completed a advancment called "End of the Line". It is nuclearcraft challenge.

I have noticed alot of the stuff in the loot boxes is just way overpowered (at least in an expert pack, Is there a way (other than not opening the loot boxes) I can replace the loot boxes in the quests? I am going to look into how to go about it in the meantime just in case there is a simple edit or somthing.

I want to complete the challenges myself :P

https://imgur.com/gallery/Dk8w8cR

**Comment by Kuktar** [comment]
Ok so i was able to modify the default loot table using the wiki instructions. I just replaced all the weight:1 items with random harvestcraft foods.

Loving this modpack. I wont close this becuase maybe you have a better solution or nobody commented about how much insane amounts of thought and time went into that loot table. I can only image how much effort the questing part of this pack took...... it pained me just to change a couple lines lol.

Godspeed!

**Comment by NillerMedDild** [comment]
The quests and loot took hundreds of hours ><

I personally think the loot is fine as it is, the legendary rewards are incredibly rare.

Cool that you could change it yourself :)

**Comment by Kuktar** [comment]
I appreciate the reply. Maybe i just got super lucky. I got 3 legendaries just going through the tinkers quests (about 20 quests into world). It was the 300RFt californium RTG and a wyvern bow and wyvern armor piece. I dont think the draconic stuff was bad at all. The californium rtg is game breaking for me though. it is a mobile power source that never runs out (if you take the time to produce it in my opinon it is fantasticly rewarding. But getting it from building a smeltery on day 10 is just a bit much for me :P.

I made sure to cover my ass becuase i could tell A LOT of effort went into the quests, The rewards are 100x better then the continum rewards btw. They have a team of 20 people and didnt come close to your questing rewards!

**Comment by NillerMedDild** [comment]
The Tinkers' quests were made incorrectly, the loot chests from it have a much higher chance to drop legendaries than the normal ones :/ I'm guessing you meant to make this issue on the regular Enigmatica 2 issue tracker btw.

I don't think FTB actually has 20 people :P but I appreciate the compliment either way, thank you!
