### ISSUE TITLE
Make Chemical Reactor less... useless?

### ISSUE THREAD

**Issue by MaxNeedsSnacks** [NillerMedDild/Enigmatica2Expert#871]
**Modpack version**
1.56

**Can the issue be reproduced?**
?

**Logs**
N/A

**Issue**
Since the removal of the default chemical reactor recipes for both the Airtight Seal enchantment and Rocket Fuel, the entire machine has become pretty much useless, except for maybe clearing out carbon cartridges (which you might as well just throw away once they're empty since they're ridiculously easy to craft), however, it's still both mentioned in the Quest Book and also, countless players have probably already built the structure, pretty much wasting their hard-earned materials.

With how useless the machine is currently looking, there is really no reason to keep it in the quest book (or by extension in the pack), however maybe you might find some uses for it (i sure couldn't... yet). I just figured I'd point it out 👍

**Comment by NillerMedDild** [comment]
I'll see what I can come up with :)
