### ISSUE TITLE
Advanced Rocketry space suit won't charge

### ISSUE THREAD

**Issue by Rodg88** [NillerMedDild/Enigmatica2Expert#872]
**Modpack version**
1.56

**Issue**
Using an AR gas charge pad, filled with NC oxygen, while wearing a freshly crafted AR space suit, doesn't charge the space suit's oxygen tanks. And Mek oxy/liquid oxy isn't even accepted by the charge pad 

![2019-02-21_02 12 43](https://user-images.githubusercontent.com/2611674/53101865-b62c0380-357e-11e9-80bd-d525d0f3fa93.png)

**Comment by MaxNeedsSnacks** [comment]
Did you install High Pressure Tanks into the Chestpiece with the Suit Workstation?

**Comment by Rodg88** [comment]
No, but in the config the spacesuit is set to store some oxygen without any addons: 
(spaceSuitO2Buffer=30)

**Comment by NillerMedDild** [comment]
I'm pretty sure that's with tanks installed. Please install High Pressure Tanks and see if the issue persists.

**Comment by Rodg88** [comment]
Yeah, adding tanks let it charge. Maybe it's a new change in AR that it requires tanks now, as even on the AR wiki it says the default suit can hold a bit of oxygen without tanks
