### ISSUE TITLE
MystAgrad Cloche Compat mod re-written

### ISSUE THREAD

**Issue by Rodg88** [NillerMedDild/Enigmatica2Expert#873]
Was just looking at MystAgrad Cloche Compat's curse page and noticed it's been re-written: https://minecraft.curseforge.com/projects/ie-cloche-compat

Just thought it might have gone unnoticed as there's no 'update' button since it's a new mod, so thought I'd let you know.

**Comment by NillerMedDild** [comment]
Thanks for the info :)
