### ISSUE TITLE
Rutile accessable on Luna

### ISSUE THREAD

**Issue by Bentenmaru** [NillerMedDild/Enigmatica2Expert#874]
**Modpack version**
1.56

**Can the issue be reproduced?**
Yes/no/unknown

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Issue**
according to JEI you can only find Rutile Ore on 4 planets...but i find it on Luna in lots of quantities

If this is a feature request, feel free to delete the template.

**Comment by NillerMedDild** [comment]
That is intentional, don't mind JEI :P
