### ISSUE TITLE
Mekanism Electrolytic Separator Quest

### ISSUE THREAD

**Issue by MayhemGang** [NillerMedDild/Enigmatica2Expert#875]
**Modpack version**
Most recent 1.56

**Can the issue be reproduced?**
Yes

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Issue**
The quest is not recognized, I tried various methods of crafting and energy, but it is just not recognized. Seems to be an NBT data problem.

If this is a feature request, feel free to delete the template.

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by MaxNeedsSnacks** [comment]
Can confirm crafting a Separator does not complete the quest, trying to find out what causes it rn

**Comment by MaxNeedsSnacks** [comment]
Okay, the "ignoreNBT" flag simply had to be set to true.

Probably not gonna start a PR just for a one liner, but uhhh yeah

**Comment by NillerMedDild** [comment]
yeah :P

**Comment by MaxNeedsSnacks** [comment]
nvm turns out I **did** start a PR for a simple one liner, because there were a couple of them actually lol
