### ISSUE TITLE
Recurrent Complex becomes unusable for large worlds

### ISSUE THREAD

**Issue by Zekrom64** [NillerMedDild/Enigmatica2Expert#877]
**Modpack version**
1.54

**Can the issue be reproduced?**
Yes

**Logs**
N/A

**Screenshots**
![image](https://user-images.githubusercontent.com/13003285/53140519-941c8c00-3552-11e9-972f-23c0d27a0d9d.png)

**Issue**
Recurrent Complex became unusable for our server with a large world due to a design flaw where it saves the structure data for an entire dimension in a single file. This includes coordinates for every chunk it has generated and every structure. On our world the structuredata file grew to 161MB in the overworld and was well over 4GB when the server tried to load it. Preferrably a different mod could be used for generated structures.

**Comment by NillerMedDild** [comment]
I will not be swapping out generation mods, I don't see the need to be honest. I've never encountered this issue, or even heard of it, and I've run a lot of servers with Recurrent Complex. It should however be safe to remove it from the server.
