### ISSUE TITLE
Neutronium Seed too easy

### ISSUE THREAD

**Issue by Zidane3838** [NillerMedDild/Enigmatica2Expert#878]
**Modpack version**
1.5.6

**Issue**
The Neutronium Seeds from Mystical Agradditions are way too easy to make compared to the other tier 6 seeds. Neutronium Seeds use supremium while the others (even inferium seeds) use insanium etc.

**Comment by NillerMedDild** [comment]
They're easy to make because Neutronium is basicly just a time gate, and I'd like to cut down on those :)

**Comment by MaxNeedsSnacks** [comment]
Ah, that seems fair. Should I revert that commit?

**Comment by NillerMedDild** [comment]
Yes please.
