### ISSUE TITLE
Seed oil conversion is missing TE oil to forestry oil

### ISSUE THREAD

**Issue by MorganSimic** [NillerMedDild/Enigmatica2Expert#879]
**Modpack version**
1.56

**Can the issue be reproduced?**
Yes

**Issue**
Seed oil conversion was added to fix #733 but only the conversion from forestry to TE. It also needs to be the way around. The other way is also the more useful one I suppose.

If this is a feature request, feel free to delete the template.

**Comment by Rodg88** [comment]
Same with sulfuric acid, you can't go from Mekanism to NC

**Comment by MaxNeedsSnacks** [comment]
The reason for that latter one is because NC is a fluid while Mekanism's is a gas.

Is the other way possible though? If so... odd

**Comment by Rodg88** [comment]
Mek has a liquid version too, which is why NC -> Mek works. Just need to use the rotary condensentrator to change between them.

**Comment by MaxNeedsSnacks** [comment]
Ah, alright. Might add Cross Compat to my fork then.

**Comment by NillerMedDild** [comment]
Oh, I just assumed the Fluid Dictionary would add the reverse recipe aswell, my bad :)

**Comment by NillerMedDild** [comment]
That'd be nice Max!
