### ISSUE TITLE
Arcane Crafting Engine -- Ordo Crystal vanishing

### ISSUE THREAD

**Issue by fabrossmann** [NillerMedDild/Enigmatica2Expert#881]
**Modpack version**
1.56

**Can the issue be reproduced?**
Yes

**Issue**
One of our users is reporting that, his Arcane Crafting Engine is not working, because the ordo crystal in the middle is vanishng.

He reproduced this error 3 times. At the 3rd time, he even waited, then after around 1 minute the ordo crystal in the middle vanished.

**Comment by NillerMedDild** [comment]
I think this could be because of high flux in the area - Can you/he try to build it another location please?

**Comment by fabrossmann** [comment]
You were right, the high flux destroyed them and after the user changed the location, the machine worked fine. 
Still, thanks for the quick answer and thank you for creating the modpack. :)

**Comment by NillerMedDild** [comment]
You're welcome :D

**Comment by TemperedFool** [comment]
So another reason to hate Flux, as this is happening to me. Does the MM generate flux itself?

**Comment by NillerMedDild** [comment]
Nope
