### ISSUE TITLE
Fracionating Still not Working

### ISSUE THREAD

**Issue by SantaSeal** [NillerMedDild/Enigmatica2Expert#882]
**Modpack version**
1.5.6

**Can the issue be reproduced?**
Yes

**Logs**
//

**Issue**
Unable to pump Sap into the Fractionating Still. Tried different pipes and different worlds.

If this is a feature request, feel free to delete the template.

**Comment by Bentenmaru** [comment]
> 
> 
> **Modpack version**
> 1.5.6
> 
> **Can the issue be reproduced?**
> Yes
> 
> **Logs**
> //
> 
> **Issue**
> Unable to pump Sap into the Fractionating Still. Tried different pipes and different worlds.
> 
> If this is a feature request, feel free to delete the template.

you aren't meaning resin instead by chance? as you cant process sap inside a Fracionating Still
