### ISSUE TITLE
Add boss related quests

### ISSUE THREAD

**Issue by Miky691** [NillerMedDild/Enigmatica2Expert#883]
This modpack is great; i'm really enjoying it and i really appreciate the work you've done making it.
Something that, in my opinion, could make it a little bit better is adding some boss related quests.
Like twilight forest could have his own quests gate; maybe also quests for wither boss, ender dragon and chaos guardian.
I personally would really appreciate this feature so i would be extremely thankful if you considered my suggestion.

**Comment by NillerMedDild** [comment]
To be completely honest, I'm tired of making quests - I've made well over 1500 at this point, so I'm a bit burned out. But boss quests would be a nice addition. I'll keep the issue open in the hope that I'll get it done, but no promises :)

**Comment by Kuktar** [comment]
What about collaborating with other modpack teams. I know FTB continuum had a quest page called mandatory hoarding. It had quests to get the heads of all the bosses in the pack and even quests to get uber amounts of resources. 

Not sure if they are copyrighted or need permission but if you could just copy paste the boss quests it might not be that simple but tfox is a nice dude and loves collaborating. Let there 1000 hours of work save you 599 hours of work. 

And this modpack questing is amazing so far.

**Comment by NillerMedDild** [comment]
They are copyrighted, I would need explicit permission, but more to the point - I have no interest in adding quests from other modpacks, I think it would make me seem lazy, and undermine the work I have done.

**Comment by Kuktar** [comment]
I couldnt agree more! Maybe use them as a template if you decided to make
boss quest lines. Just please God dont use there layout. Its literally just
a grid pattern and is oh so boring to look at lol.

Christopher Kuhn,
Semper Fidelis

**Comment by NillerMedDild** [comment]
I'm sorry but I will not be working on this.

**Comment by Iwitrag** [comment]
:(
