### ISSUE TITLE
Some Mekanism machines do not get power after reloading the pack

### ISSUE THREAD

**Issue by imVidzz** [NillerMedDild/Enigmatica2Expert#884]
**Modpack version**
1.56

**Can the issue be reproduced?**
Yes

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Issue**
Everytime I reload the pack, some Mekanism machines stop getting power from enderIO conduits until broken and placed back. They are always the exact same machines .I recently moved my stuff around and the only one suffering from the bug is a Basic Enrichment Factory. The other one I have in the base works just fine and I can't recall what the other machines that had this happen were. It has happened before and after the last update to 1.56

**Comment by NillerMedDild** [comment]
It's sadly just a limitation with EnderIO/Mekanism interaction - The pipe/machine needs a block update to get set correctly.
