### ISSUE TITLE
Nether Seeds

### ISSUE THREAD

**Issue by Zidane3838** [NillerMedDild/Enigmatica2Expert#885]
Could Nether Seeds be changed to need Nether Cluster (mysticalagriculture:crafting_2) instead of essenceTier2/Nether Wart Block /shrug... The Dye Seeds (mysticalagriculture:dye_seeds) use their Dye Cluster (mysticalagriculture:crafting_1). It would make the nether cluster not completely useless :^)

**Comment by NillerMedDild** [comment]
Well for that to work I would have to remake the Nether Cluster, and the result would be pretty much the same :P
