### ISSUE TITLE
Invulnerability timer way too low

### ISSUE THREAD

**Issue by Beetrootmonkey** [NillerMedDild/Enigmatica2Expert#886]
**Modpack version**
1.56 Expert

**Can the issue be reproduced?**
Yes

**Issue**
For some strange reason, after being hit I can instantly be hit again. That means that any melee mob will give me 5-10 hits per second, and dots will kill me in under a second (ic2 radiation, magma blocks, but not drowning or fire damage). It's reproducable with and without armor.

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by Beetrootmonkey** [comment]
I managed to reproduce the issue in a new world as well as in a new and clean installation of the pack. I'm wondering how this hasn't been an issue for anyone else.

**Comment by NillerMedDild** [comment]
Me too O_O

**Comment by MaxNeedsSnacks** [comment]
Probably because most of them have 50+ hearts

(also may i just take this second to say - rip cyclic heart containers, i wouldve loved to automate you to get like... rose gold / golden hearts)

**Comment by NillerMedDild** [comment]
Fixed in next version :)
