### ISSUE TITLE
Rustic Fruit Juices are awful in a Biogas Engine

### ISSUE THREAD

**Issue by pkmnfrk** [NillerMedDild/Enigmatica2Expert#887]
**Modpack version**
Expert 1.56

**Can the issue be reproduced?**
Yes

**Logs**
Nothing seems relevant in the logs. But here is a video:

https://cdn.discordapp.com/attachments/504103234072477717/548313125183684660/Enigmatica2Expert_2019-02-21_8_16_42_PM.mp4

**Issue**
Rustic's Fruit Juices don't seem to work very well in Biogas Engines. It seems to consume an entire buckets worth in the span of less than a second. I tested with other fuels, and it seems to behave normally.

Liquid|Broken
-|-
Apple Juice|Yes
Grape Juice|Yes
Wildberry Juice|Yes
Ironberry Juice|Yes
Fruit Juice (Forestry)|No
Honey (Forestry)|No
Water|No
Milk|No

**Comment by NillerMedDild** [comment]
I'm afraid I have no control over that :(
