### ISSUE TITLE
Add NBT reset to entangled singularities (for autocrafting purposes)

### ISSUE THREAD

**Issue by MaxNeedsSnacks** [NillerMedDild/Enigmatica2Expert#888]
**Modpack version**
1.56

**Can the issue be reproduced?**
Yes

**Logs**
N/A

**Issue**
Due to the way processing recipes work (in both AE and PackagedAuto), autocrafting Anglesite currently is... a nuisance, to say the least. When requesting a package that requires a Quantum Entangled Singularity, for example, it won't recognise any singularities you made for the simple reason that they are all tuned to a frequency (and therefore have some nbt data). The easiest way to solve this from a packmaker's standpoint would be to just add a crafting recipe that removes the NBT from the singularity, as that one SHOULD (hopefully) work without nagging about a missing singularity

**Comment by MaxNeedsSnacks** [comment]
There should probably also be an info page in JEI warning the players about the singularities losing their functionality when used for the Anglesite.

**Comment by TemperedFool** [comment]
This is basically the same as the following issue from Skyblock that I filed:

https://github.com/NillerMedDild/Enigmatica2ExpertSkyblock/issues/378

General consensus is it's an interesting issue to auto-craft around (having just set it up myself), and I don't think Niller will want to change it ^_^

**Comment by MaxNeedsSnacks** [comment]
Ah yeah, sorry, I don't keep track of the E2ES repo since most of them are moved over here anyways. Gonna leave this issue open for now just in case Niller *does* plan to implement something (he most likely doesn't though looking at your issue), but if not, it's not really that big of a deal (except for me not being able to just use the recipes from shift-click anymore >:c)

**Comment by NillerMedDild** [comment]
I'm afraid it's a no here as well :P

**Comment by BanditSan** [comment]
> **Modpack version**
> 1.56
> 
> **Can the issue be reproduced?**
> Yes
> 
> **Logs**
> N/A
> 
> **Issue**
> Due to the way processing recipes work (in both AE and PackagedAuto), autocrafting Anglesite currently is... a nuisance, to say the least. When requesting a package that requires a Quantum Entangled Singularity, for example, it won't recognise any singularities you made for the simple reason that they are all tuned to a frequency (and therefore have some nbt data). The easiest way to solve this from a packmaker's standpoint would be to just add a crafting recipe that removes the NBT from the singularity, as that one SHOULD (hopefully) work without nagging about a missing singularity

Removing NBT tag from Quantum Entangled Singularity will simply make then not work. so that is bad idea. Best fix for this issue is just use Singularity for Anglesite recipe not the Quantum Entangled Singularity
