### ISSUE TITLE
Aluminum can't be processed in the small plate presser

### ISSUE THREAD

**Issue by MorganSimic** [NillerMedDild/Enigmatica2Expert#889]
Little typo, my fault, PR incoming to fix this.

**Comment by NillerMedDild** [comment]
Cool!

**Comment by MorganSimic** [comment]
Is fixed with #891 . I haven't figured out yet how to link issues with commits to say fixed via x. But here it is.

**Comment by NillerMedDild** [comment]
You can do that with `closes #issuenumber`, the words close and closes are recognized.

**Comment by MorganSimic** [comment]
Okay thank you. I'll do that if I ever fix something again.

**Comment by NillerMedDild** [comment]
Fingers crossed :D
