### ISSUE TITLE
Xnet controller crash

### ISSUE THREAD

**Issue by Neoxes64** [NillerMedDild/Enigmatica2Expert#89]
#### Crash Report : 
[crash-2018-06-03_08.29.24-client.txt](https://github.com/NillerMedDild/Enigmatica2Expert/files/2065945/crash-2018-06-03_08.29.24-client.txt)

[pastebin/gist/etc link here]

**Comment by Lukas45** [comment]
Happens with most RFTools machines right now. 1.26c is awaiting approval, with a fix.
