### ISSUE TITLE
Bloodmagic normal HellfireForge recipe not hidden and still active

### ISSUE THREAD

**Issue by Crusaderkvw** [NillerMedDild/Enigmatica2Expert#890]
**Modpack version**
Version 1.56 (Latest as of the moment of writing this)

**Can the issue be reproduced?**
I guess so, just try to create the forge.

**Issue**
It's really all said in the title and the screenshot already. Also experienced this with a couple other "gated" recipes still allowing the normal one to be used. Might want to look into it.

https://imgur.com/gallery/l48n1nR

Edit: when trying to create the forge via the gated recipe it doesn't want to craft: https://imgur.com/gallery/jvJLnqu

**Comment by MorganSimic** [comment]
I highly supsect your scripts are broken. Do you get some error messages when starting up the world? And did you change something in the pack? Added and especially disabled/removed mods?

**Comment by Crusaderkvw** [comment]
**** yeah.... going to cancel this post. The only thing I disabled was the AE2 channels, but i'll look into it some more. going to close this one straight away -_-

**Comment by MorganSimic** [comment]
Yep, there is your issue. Removing the controller breaks scripts.
