### ISSUE TITLE
Ear defenders bug

### ISSUE THREAD

**Issue by ElLocoRemo** [NillerMedDild/Enigmatica2Expert#892]
**Modpack version**
1.56

**Can the issue be reproduced?**
Yes

**Issue**
Immersive Engineering ear defenders don't reduce the sound of mekanism machines if you put them on when you're close to a running machine. If you get far enough for the chunk with the machine to unload and then return, the sound will be muffled.

**Comment by NillerMedDild** [comment]
Mekanism uses a different sound mechanic, not much we can do about it I'm afraid. You can disable machine sounds in the config :)
