### ISSUE TITLE
crashing on load

### ISSUE THREAD

**Issue by bcxtcreepper** [NillerMedDild/Enigmatica2Expert#893]
**Modpack version
1.12.2

**Can the issue be reproduced?**
unknown

**Logs**

	
**Issue**
crashing on load
[crash-2019-02-23_17.43.26-client.txt](https://github.com/NillerMedDild/Enigmatica2Expert/files/2896976/crash-2019-02-23_17.43.26-client.txt)

If this is a feature request, feel free to delete the template.

**Comment by NillerMedDild** [comment]
Reinstalling should fix it :)
