### ISSUE TITLE
Better Questing mod requires re-opening quest before claiming reward.

### ISSUE THREAD

**Issue by PiggyWhiskey** [NillerMedDild/Enigmatica2Expert#895]
**Modpack version**
1.56 Client only

**Can the issue be reproduced?**
Yes

**Issue**
1. Quest completed (Or click "Detect")
2. Select Reward
3. "Claim" button greyed out
To Solve
4. Click "Back"
5. Click completed Quest
6. Actually claim reward.

This has shown on several YT'rs and SSP but I couldn't find an issue on here or Better Questing github

I also wasn't sure if it was a config issue, or what changed in the last version or two.

If this is a feature request, feel free to delete the template.

**Comment by NillerMedDild** [comment]
Thanks for the report. This is a known issue, tracked here: https://github.com/Funwayguy/BetterQuesting/issues/520
