### ISSUE TITLE
Exception in server tick loop  java.lang.AbstractMethodError: Method com/rwtema/extrautils2/tile/TilePower$1.func_185929_b(Ljava/lang/String;)Lcom/google/common/base/Optional; is abstract

### ISSUE THREAD

**Issue by Quantum001** [NillerMedDild/Enigmatica2Expert#896]
**Modpack version**
E2E 1.56 and 1.54

**Can the issue be reproduced?**
Presumably so if extra utilities has a bug in their code.

**Logs**
https://gist.github.com/Quantum001/f3225e28dd959eeabc7a4a79f096235f

**Issue**
Extra Utilities 2 crashes server. Searched around a bit and found this as well. https://github.com/rwtema/Extra-Utilities-2-Source/issues/262

Server gets stuck in crash loop. The crash logs lead you down a rabbit hole pointing to different ticking entities. Removing these entities doesn't solve the crash. Eventually the logs point to simple blocks as causing the crash. Also deleting the section of the region file the logs point to does not solve the issue.

**Comment by NillerMedDild** [comment]
Interesting issue title xD 
Last time this was reported, the issue was an XU2 Water Generator next to an AS block.

**Comment by NillerMedDild** [comment]
Did you manage to fix it?

**Comment by domi1819** [comment]
I ran into this issue as well, and it is now fixed in Astral Sorcery 1.10.12.
