### ISSUE TITLE
JEI says destabilised redstone available on Europa, but it isn't

### ISSUE THREAD

**Issue by Rodg88** [NillerMedDild/Enigmatica2Expert#899]
**Modpack version**
1.56

**Issue**
The JEI listing of planets you can find destabilised redstone ore on is outdated, it says it's available on Europa, but in the configs it's not set to generate there.
![2019-02-24_21 12 10](https://user-images.githubusercontent.com/2611674/53297872-153c9180-3879-11e9-97b3-634d245b985b.png)

I guess the worldgen profile needs updating, or dim 106 could be added to the destabilised redstone entry in the 16_advanced_rocketry_planets_ore config.

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by blarghhh** [comment]
as of 1.24 E2:ES, JEI still lists europa as a destination for destabilized redstone.
![2019-04-12_06 48 50](https://user-images.githubusercontent.com/6789845/55998034-250c1a00-5cef-11e9-8a27-6b86360f55df.png)

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
Wrong issue tracker @blarghhh :)
