### ISSUE TITLE
Connecting other mods item transport exu transfer nodes will crash a server.

### ISSUE THREAD

**Issue by Electrofried** [NillerMedDild/Enigmatica2Expert#9]
#### Issue Description
Connecting exu transfer nodes with mek logistics pipes or xnet will cause the server to go in to a crash loop. (this is probably an EXU2 issue but I stick here for your reference)

#### What you expected to happen
I am not entirely sure what they were expecting to happen, but even placing mek logistics pipes beside an exu node will cause the crash. 
#### Modpack version (Do not use "latest")
1.4.0
#### Your most recent log file where the issue was present
[crash-2018-02-01_08.38.05-server.txt](https://github.com/NillerMedDild/Enigmatica2Expert/files/1690663/crash-2018-02-01_08.38.05-server.txt)
[crash-2018-02-02_09.02.58-server.txt](https://github.com/NillerMedDild/Enigmatica2Expert/files/1690664/crash-2018-02-02_09.02.58-server.txt)

[pastebin/gist/etc link here]

**Comment by NillerMedDild** [comment]
Thanks for bringing this to my attention, however the Extra Utilities 2 github isn't maintained, not much to do :/
