### ISSUE TITLE
Impossible to craft some things

### ISSUE THREAD

**Issue by Dani20000** [NillerMedDild/Enigmatica2Expert#900]
**Modpack version**
1,56 (the issue reappears also in some older versions)

**Can the issue be reproduced?**
Yes

**Issue**
Is impossible to craft any collector crystal and the oil generator (and is obviously impossible to make the rispective quests)

**Comment by NillerMedDild** [comment]
What makes you say it's impossible to craft Collector Crystals?

Reload the quests with `/bq_admin default load`

**Comment by TemperedFool** [comment]
I just crafted a collector crystal earlier I SB - should be 2 Resonant gems, 2 illumination powder, 2 stardust, and an attuned crystal.

**Comment by TemperedFool** [comment]
Is your crystal attuned?

**Comment by Dani20000** [comment]
No, it wasn't attuned... i'm sorry.
But the canola oil generator isn't craftable anyway.
I tried to see how was crafted in the actually additions manual, but nothing...
![oil generator](https://user-images.githubusercontent.com/22727783/53340905-7496b200-390a-11e9-9fd2-5f3f53711c99.jpg)


I also tried to see all the things crafted with iron casing or canola... no way.

**Comment by MaxNeedsSnacks** [comment]
Oh yeah, the Oil Gen has been disabled in favour of the Compression Dynamo, that's intentional

**Comment by scribbler957** [comment]
I haven't been able to get the Creative Builder's Wand to craft.
