### ISSUE TITLE
Optifine 1.12.2-HD-U-E3 crashes game in final stages

### ISSUE THREAD

**Issue by Ghost942** [NillerMedDild/Enigmatica2Expert#901]
**Modpack version**
1.56

**Can the issue be reproduced?**
Yes

**Logs**
https://pastebin.com/NBfhp13Y

**Issue**
Optifine 1.12.2-HD-U-E3 is not supported in current version. E3 is the latest version in the 1.12.2 version of Minecraft. This mod has worked before in version 1.53 of E2E. Please let me know if you require more information.

**Comment by NillerMedDild** [comment]
The crash report you linked has nothing to do with Optifine, it crashed because you have insufficient RAM allocated :)

Does it work if you allocate 6GB of RAM?

**Comment by Ghost942** [comment]
Allocating more than 6GB of RAM did solve this issue.

Strange how Twitch defaulted things back to the Native Launcher and 3GB of RAM. Not sure on that, but that's out of your hands. Closing issue.
