### ISSUE TITLE
Nickel is missing from the small plate presser

### ISSUE THREAD

**Issue by MorganSimic** [NillerMedDild/Enigmatica2Expert#902]
**Modpack version**
1.56

To fix this code should go into smallplatepresser.xml . Not sure on Nickel dust metadata.
`<Recipe timeRequired="0" power ="0">
		<input>
			<oreDict>oreNickel</oreDict>
		</input>
		<output>
			<itemStack>thermalfoundation:material 2 69</itemStack>
		</output>
	</Recipe>`

**Comment by NillerMedDild** [comment]
Cool, thanks!

**Comment by MaxNeedsSnacks** [comment]
Confirmed that the metadata is correct and added Nickel Dust to my PR. Thanks!
