### ISSUE TITLE
Twilight Forest Metal Coins

### ISSUE THREAD

**Issue by MorganSimic** [NillerMedDild/Enigmatica2Expert#903]
As it stands right now, you can get quite a huge amount of those metals, but they all have little to no use beisdes some niche application and ultimate ingot crafting. I was thinking about if it was possible to add coin variants for those metals. Or something to give them an additional use besides voiding/storing. I'm not sure how feasible this is but it was an idea that came to my mind yesterday when i saw those metals piling up in my system.

**Comment by NillerMedDild** [comment]
I'm pretty sure that's achievable with JAOPCA, good idea :)

**Comment by MaxNeedsSnacks** [comment]
Maybe Fiery Ingots could be of use in machines that have to do with melting down things, for example?

**Comment by NillerMedDild** [comment]
I'd like if the Twilight-compat is optional, to limit the strain on E2E servers, so preferably no integration into existing recipes.

**Comment by MaxNeedsSnacks** [comment]
Ah yeah, true, it has been messing with my TPS when I went there.

There must be some good way to integrate it into optional stuff though... hmm

**Comment by MaxNeedsSnacks** [comment]
I think I've found a way to make Twilight Forest metals more useful while keeping them optional to the actual pack progression.

What if the Twilight Forest metals were in some way used for EnderIO enhanced machines (since they have no recipe right now), so for example for the enhanced chassis and / or the machines themselves. From what I can tell, the main benefit of the enhanced machines is their speed, so that could be a nice optional thing for impatient players (like myself :P) to get

**Comment by NillerMedDild** [comment]
Hmm.. I don't know, the "normal" tier EnderIO Machines are fast af as it is.

**Comment by MaxNeedsSnacks** [comment]
That's true. I'm actually kind of wondering how ridiculously fast the enhanced would be now though

**Comment by MorganSimic** [comment]
Tbh, I think coins would be just enough. Just a little something to use it for if you want. Most people probably just don't care and void it anyways. What I could think of would be molten fiery metal as smeltery fuel if that isn't a thing already. But other than everything else is probably way over the top.

**Comment by dnarik** [comment]
You could add an alloying recipe for Ironwood + Fiery = 2 Iron + Charcoal, don't how useful it would be - I am far from getting a single piece of Fiery ingot

**Comment by NillerMedDild** [comment]
JAOPCA does not have Twilight Forest compatibility sadly, there's no good way of doing this.
