### ISSUE TITLE
RFTools Screen should be added to Carry On blacklist

### ISSUE THREAD

**Issue by Exadi** [NillerMedDild/Enigmatica2Expert#907]
**Modpack version**
1.56

**Can the issue be reproduced?**
Yes

**Logs**
Not applicable

**Issue**
Opening its GUI requires shift-right click so - unless you rebind the Carry On key or blacklist it - it gets picked up instead. It keeps its modules when broken anyway so there's no need for Carry On. Also: https://github.com/Tschipp/CarryOn/issues/158

**Comment by NillerMedDild** [comment]
Thanks for the report, fixed in dev :)
