### ISSUE TITLE
Hard but optional final quests

### ISSUE THREAD

**Issue by Miky691** [NillerMedDild/Enigmatica2Expert#908]
Greetings 
This is the second "quest" request i make in a short delay of time.
I know you told me that you're tired of making quests but what i'm asking isn't really a quest but more of some "goals" to add at the very end of the pack.
Basically i'd like to have something to do after the chapter "bragging rights" (hoping i wrote that right).
Basically some really hard goals like build and automate a max size reactor from extreme reactros and other stuff like that. What i'm asking is basically the book you recive when you complete the entirety of the quest book in the pack project ozone.
I think this would be really fun and could be "optional" since you've already completed the quest book.
I understand that you are tired of making quests so i perfectly understand if you don't want to do this the pack is already amazing as it is!
Sorry for bothering you again in such a short time.

**Comment by NillerMedDild** [comment]
I appreciate the suggestion, I may use it in a modpack down the line, but not for E2E :)
