### ISSUE TITLE
Uranium Essence from Mystical Agriculture is creating Refined Uranium Ingots

### ISSUE THREAD

**Issue by NillerMedDild** [NillerMedDild/Enigmatica2Expert#909]
Modpack
Enigmatica 2 Expert

Version
1.54

Can it be reproduced?
Yes

Logs
N/A

Issue
The Uranium Essence from Mystical Agriculture is creating Refined Uranium Ingots from IC2 instead of the Uranium Ingots from Immersive Engineering

**Comment by scribbler957** [comment]
It doesn't seem to affect anything. I mean, you can use IC2 Uranium in place of IE Uranium for crafting and in extreme reactors.

**Comment by CalvinJJ** [comment]
NC Fission reactors only accept IE ingots and not the IC2 ones. Also if you have both a Mystical Agriculture and void mining setup, it seems silly to have two different stacks of Uranium.
