### ISSUE TITLE
mousetweaks Isuue

### ISSUE THREAD

**Issue by fusedshadow89** [NillerMedDild/Enigmatica2Expert#91]
#### Issue Description

####enigmatica 2: expert version 1.26b

#### The game crashed whilst guicontainer.getslotatposition() threw an exception when called from mousetweaks.
The game crashed whilst guicontainer.getslotatposition() threw an exception when called from mousetweaks.
Error: java.lang.reflect.InvocationTargetException

[pastebin/gist/etc link here]

**Comment by Lukas45** [comment]
It was a bug with Alpha versions of McJty mods.
Version 1.26c has been released, and fixes this.
And in the future, attach the full crash log, not just parts of it ;)
