### ISSUE TITLE
Astral Sorcery Sky Rendering in Space

### ISSUE THREAD

**Issue by scribbler957** [NillerMedDild/Enigmatica2Expert#910]
I'd like to see the various planet/space dimensions added to the AS list partly so I can move my main base to a spaceship and partly cause I think it would look cool to see all my constellations floating around me.

**Comment by NillerMedDild** [comment]
That would overwrite the Advanced Rocketry sky.

**Comment by scribbler957** [comment]
Even with the AS weak rendering option?

**Comment by NillerMedDild** [comment]
I didn't know that was a thing ^^'

**Comment by NillerMedDild** [comment]
Done, just need to test it. Thanks for the suggestion!

**Comment by scribbler957** [comment]
Sweet. Can't wait for the update. Thanks.

**Comment by MaxNeedsSnacks** [comment]
(for future reference btw i think you need to explicitly say **closes** #xxx for the issue to be closed by the commit)

**Comment by NillerMedDild** [comment]
Right, it's still open because it's untested :)
