### ISSUE TITLE
Unification Error Megathread

### ISSUE THREAD

**Issue by MaxNeedsSnacks** [NillerMedDild/Enigmatica2Expert#913]
# This is a thread compiling users' unification problems into one issue for the sake of clarity.
## Please read this before contributing!

- Please tell me which item you were trying to craft and how.
- If possible, please also provide item / recipe IDs, it makes things a hell of a lot easier to fix for me ^^
- Please avoid duplicates in this thread, including those of already existing issues

That's all for now. I'm gonna try to fix these as soon as I see them and add them to a PR you can soon check out and review for yourself.

(Now, if you'd excuse me, I'm going to go through some items myself and see whether I can find any errors with unification)

**Comment by MaxNeedsSnacks** [comment]
Looks like I accidentally removed Mystical Agriculture Sulfur unification when reverting 6ccd331 in #880, whoops! I'll be readding that real quick.

**Comment by NillerMedDild** [comment]
Good idea :D

**Comment by MaxNeedsSnacks** [comment]
Just added Uranium unification (closing #909) to the mix and also changed Amber Essence to output Thaumcraft amber, just seems more sensible to have it output that.

**Comment by NillerMedDild** [comment]
Sweet!

**Comment by Wntermute** [comment]
Here are a few:
 - IF laser yields IC2 Copper Ore that isn't OD'd to oreCopper
 - Also yields IC2 Tin Ore that isn't OD'd to oreTin
 - NuclearCraft and IC2 both have items called Uranium 235 and Uranium 238, why not combine them? (Preferably the safe-to-handle NC one ^_^)
 = FluidDict the various liquid honeys (Animania, Forestry, BoP, Rustic)
 = For some reason, I ended up with tons of Rustic and HarvestCraft beeswax that couldn't be made into Forestry
 - The Klein Bottle recipe. My automation keeps using my Clear Glass for other things and I unsuccessfully tried to DEUNIFY Clear Glass.

The ones marked with a = I managed to CraftTweak into my server.

PS. I also managed to work around the NuclearCraft Alloy Furnace automation issue with the Fused Quartz recipe by adding one using 2 Nether Quartz and 2 Black Quartz, it kept putting all the nether quartz for the 2+2 recipe into one slot.

**Comment by MaxNeedsSnacks** [comment]
@Wntermute the IF laser shouldn't yield IC2 ores, I checked through the laser config and in-game JEI tooltips and it doesn't seem to. Can you try confirming that in a new world?

**Comment by MaxNeedsSnacks** [comment]
I also just checked and apparently Rustic honey simply... isn't a thing when other honeys are around. I tried picking up the Rustic honey and it auto-turned into BoP honey ^^

**Comment by MaxNeedsSnacks** [comment]
Considering the clear glass one, I'm not sure whether I should change that since having Clear Glass OD'd as blockGlass might help for example players in the earlier game stages as a way to get glass more quickly through the smeltery

**Comment by NillerMedDild** [comment]
I would prefer if you didn't Max :)

**Comment by MaxNeedsSnacks** [comment]
Had a hunch, honestly, wouldn't make sense to remove Clear Glass from that OD. Guess @Wntermute will just have to find another way to not waste it then :P

**Comment by NillerMedDild** [comment]
Like disabling substitutes :)

**Comment by MorganSimic** [comment]
Also the liquid honey stuff is already done a few updates ago. I did merge all liquid honey obtaining ways into forestry honey. If you could point out exact cases where honey isn't unified that would be great @Wntermute.
Also The IF meat ore processing puts out ic2 dusts. I'm not sure if changing that is possible at all. Haven't run into any issues though.

**Comment by Wntermute** [comment]
OK, I started a new single-player world, set up a laser in creative and chunkloaded the chunk, left it running all day while I looked around for other possible sources of IC2 ore. After a plethora of hours, 0 IC2 copper/tin and it had barely filled half of one page of a Large Storage Crate. 

I *DID* however find IC2 Ingots in village/dungeon crates, so it's possible I got some from there. Either way, they don't work in the Mekanism ore processing chain I have set up and won't go into my already existing drawer w/ OD upgrade.

As for the honey, I'm pretty sure it was Rustic honeycomb + Centrifugal Separator that prompted me to make a workaround. It's possible it was in 1.47 (where I started), 1.49, or 1.53. I just updated to 1.55 the day before 1.56 came out and so I'm holding off on 1.57 to update again.

And to clear up (pun intended) the request for the Clear Glass.. I'm not looking to have you deunify it.. Just unify the Klein Bottle recipe to use ore:blockGlass. That's about the only thing I had trouble with and have seen require the Clear variety. (Haven't gotten to Quite Clear yet, still need titanium)

**Comment by MorganSimic** [comment]
Thanks, i will take a look. In theory that should work now, as I did implement that aswell.

**Comment by NillerMedDild** [comment]
The Klein Bottle recipe is meant to be annoying, sorry :P

I thought I removed the ic2 ingots from dungeon loot, damn.

**Comment by MorganSimic** [comment]
I tested rustic honeycombs with all methods of obtaining honey from them and they all yield Forestry honey as intended. My unification was merged in 1.55, so if you tried before you will have run into issues. Now it is working fine. To get the official fix, you may need to revert your internal changes depending on what exactly you did.

**Comment by MaxNeedsSnacks** [comment]
From what I can gather, he only added the various Honeys to the fluiddict converter (just like i did in the pr) so that shouldn't cause any issues hopefully

**Comment by MorganSimic** [comment]
That's all fine. I don't think that conversion was necessary, because all producable honey is forestry honey now. Maybe for animnia and bop honey. I didn't touch animania honey since I now nothing about it and it doesn't seem to have any processing attached to it. And you can obtain bop honey still through nether hive worldgen. So if you really want to you can use that.

**Comment by Wntermute** [comment]
Do we need two sawdusts with the same recipes?
<thermalfoundation:material:800> & <mekanism:sawdust>

**Comment by MaxNeedsSnacks** [comment]
I might add Sawdust to the UniDict forced entries, just for the sake of not clogging up your ME

**Comment by Wntermute** [comment]
OK, get this.. Moved the IC2 ores out of my RS system into a chest and left it running most of the day.. 2 new IC2 Copper and Tin ores. Maybe readding them to ore:oreCopper/ore:oreTin.. Or add a recipe to turn them into the normal Copper and Tin. Best you can do is x2 via Manufactory and I have a nice x3 Mekanism system set up.

Don't know what to say, the Mekanism laser is my current source of ore since I haven't mined other than clearing out a room to make ghasts to get chunks.

**Comment by NillerMedDild** [comment]
Err Melanin Laser for ores? Do you mean IF?

**Comment by Wntermute** [comment]
Oops, yes.. It's been a long day. It's that one instead of the Void ore miner, which I haven't set up yet

**Comment by NillerMedDild** [comment]
fixed :D

**Comment by MorganSimic** [comment]
Mekanism crusher does output Mekanism diamond dust instead of IC2 diamond dust. It is usuable for all intends and purposes but is confusing, since it doesn't show up anywhere in JEI.

**Comment by Kallado** [comment]
Mekanism crusher produces EnderIO Lapis Lazuli Powder, not IC2 Lapis Lazuli Dust like other similar processes. They're still OD'd to each other, so nothing is broken. I'm just assuming that the powder is meant to be disabled completely.

**Comment by MaxNeedsSnacks** [comment]
I don't think there's much more unification to do here, if anyone still has any issues, feel free to open a new issue / PR or just comment on here
