### ISSUE TITLE
FlatColoredBlock Missing Colors

### ISSUE THREAD

**Issue by BanditSan** [NillerMedDild/Enigmatica2Expert#919]
**Modpack version**
1.56

**Can the issue be reproduced?**
Yes

**Issue**
Cannot craft any yellow block from FlatColoredBlock mod. Don't know which other color might be missing but im sure where is issue.

`    I:HUE_SHADES=16`
`    I:HUE_SHADES_GLOWING=16`
`    I:HUE_SHADES_TRANSPARENT=16`

Default values for this mod are 32 and when i set them to default value yellow block is craftable.

**Comment by NillerMedDild** [comment]
Changing that value will add significant additional loading time.

**Comment by BanditSan** [comment]
Did not noticed any loading time difference after changing value to 32. My PC is not lattest and greatest or you talking about some literally potato pc load times? :)

**Comment by NillerMedDild** [comment]
Nope. By significant I mean 5-10 seconds.

**Comment by BanditSan** [comment]
5-10 soconds is significant?

**Comment by NillerMedDild** [comment]
Yes.

**Comment by MaxNeedsSnacks** [comment]
For me it would be since the "5-10" seconds on your average PC is about 30 on mine lul

(and that's with 6gb of ram to the pack and a 7600k)

**Comment by BanditSan** [comment]
So why then even have this mod in a pack when it's half missing stuff?

**Comment by MaxNeedsSnacks** [comment]
Still offers a nice wide range of... well, flat coloured blocks. Also I mean, perhaps 24bit won't cause that much of a difference, but it's just too inefficient to have 32*32*32 different blocks (AND their chisels and bits counterparts AND the facades AND structuralducts)

**Comment by NillerMedDild** [comment]
Fine.

**Comment by NillerMedDild** [comment]
Edit: Changing this can change the colours of existing FlatColouredBlocks, I will not make the change.
