### ISSUE TITLE
[Suggestion] Buildcraft

### ISSUE THREAD

**Issue by Angelos33** [NillerMedDild/Enigmatica2Expert#92]
#### For feature/mod requests, feel free to delete this template
Considering adding buildcraft because of the gate system. It helps with automation in late game.
#### Crash Report

[pastebin/gist/etc link here]

**Comment by NillerMedDild** [comment]
I'm afraid I won't be adding BuildCraft in the near future, I don't think it has anything the pack needs. I suggest you use XNet, Integrated Dynamics or RFTools Control for intricate redstone.
