### ISSUE TITLE
Crash when loading client

### ISSUE THREAD

**Issue by Paancake** [NillerMedDild/Enigmatica2Expert#921]
**Modpack version**
1.56

**Can the issue be reproduced?**
Yes

**Logs**
https://pastebin.com/h2tsNLvS

**Issue**
Client CTD while loading

**Comment by NillerMedDild** [comment]
"Caused" by OpenJ9 being a bit tricker happy on the crashes. This issue is fixed in dev, and you can fix it yourself by removing the line `"xu2_machine_extrautils2:generator_overclock",` from the `scripts/JEICategories` file.
