### ISSUE TITLE
Client kicked and unable to rejoin - Better Questing?

### ISSUE THREAD

**Issue by mtimyself** [NillerMedDild/Enigmatica2Expert#922]
**Modpack version**
1.56

**Can the issue be reproduced?**
Yes

**Logs**
https://pastebin.com/tn6XHib0

**Issue**
Some players have kicked a member from their Better Questing party, got booted from the server and are unable to rejoin, even after client restart.
I included the section of the lastest.log that refers to the connection attempt.

**Comment by mtimyself** [comment]
Restoring data from backup to the ~/world/betterquesting folder has solved the issue.

**Comment by NillerMedDild** [comment]
Cool, it sounds like a fairly nasty bug though.
