### ISSUE TITLE
Portable Fluid ME drive causes crash in ME chest if piped.

### ISSUE THREAD

**Issue by wireman642** [NillerMedDild/Enigmatica2Expert#923]
**Modpack version**
1.55 Beta

**Can the issue be reproduced?**
Yes, on the specified version. Will attempt to reproduce on 1.56.

**Logs**
https://paste.ee/p/rP2Oo

Should be the correct crash log.

**Issue**
If a portable fluid ME drive is put in a ME Chest and a Extra Utilities 2 pipe imports a fluid NOT in the drive and the drive has space for the fluid, game hard crashes. On reloading the world, game locks up. World can be repaired by using McEdit and removing the entity data for the ME Chest but the player will lose the fluid drive and it's contents.

I had a drive with BioGas and Lava, an ME Chest with the drive in it, an accidental attachment of my EU2 pipe with running water, and had a hard crash after 3 seconds. Reloading the world would start loading blocks onto the screen but would freeze when loading the ME drive/EU2 pipe area. Work around fix is to remove the entity data using MCEdit.

If this is a feature request, feel free to delete the template.

**Comment by wireman642** [comment]
Confirmed on 1.56. Issue is the ME chest itself. Putting the Portable fluid Drive in the Disk Drive rack thing doesn’t cause the issue. 

Issue occures when ANY fluid stored in the cell is exported directly (via fluid conduit to the ME chest) or via Fluid export bus. Tested with biogas, water, and lava.

**Comment by MaxNeedsSnacks** [comment]
Stacktrace says it's a StackOverflow, so probably some sort of infinite recursion somewhere. Reporting this to the EC tracker.
