### ISSUE TITLE
thaumcraft disappearing seals

### ISSUE THREAD

**Issue by ognjen92** [NillerMedDild/Enigmatica2Expert#924]
**Modpack version**
1.56

**Can the issue be reproduced?**
Yes

**Logs**
[latest.log](https://github.com/NillerMedDild/Enigmatica2Expert/files/2921550/latest.log)
**Issue**
every time i log in into game my thaumcraft seals  disappear and i have to place them again, i tried moving them to different chunks but its same again.

If this is a feature request, feel free to delete the template.

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
I can't replicate this I'm afraid.

**Comment by pauldwrona** [comment]
I noted the same issue, but the seals only seemed to disappear when placed on a tile entity (plant, farmland, etc) but not when placed on a static block. So far this has been stable, not sure how to resolve storing items with golems without placing the seal on a tile entity, will have to do some testing myself.
