### ISSUE TITLE
Mekanism Digital Miner unable to find / mine Destabilized Redstone Ore

### ISSUE THREAD

**Issue by xob** [NillerMedDild/Enigmatica2Expert#925]
**Modpack version**
Enigmatica 2 Expert 1.56

**Can the issue be reproduced?**
Yes

**Logs**
Not applicable

**Issue**
The Mekanism Digital Miner is unable to find (and therefore mine) Thermal Foundation's Destabilized Redstone Ore, whether matching using an oreDict filter or an itemStack filter, even with fuzzy mode enabled.

I recognize that this is an issue with Mekanism itself (or the way Thermal Foundation is doing this ore), but I figured having an issue in the modpack's github would be useful for others who run into this problem.

To reproduce: go to Stella, plop down a Digital Miner, and try to mine Destabiliezd Redstone Ore.

**Comment by xob** [comment]
I found a way for the Digital Miner to mine Destabilized Redstone Ore, but I had to use a very generic oreDict filter. I used the `*ore*` oreDict filter, and it did mine Destabilized Redstone Ore, along with every other ore.

So I guess there is a way for it to work, it's just that I wasn't able to ask the Digital Miner to specifically mine only this ore by using an itemStack filter or a more specific oreDict filter (like `*Clath*`)

So, while this is not a complete solution, I am closing the issue as this is a workaround and it does work.

**Comment by NillerMedDild** [comment]
It's still a super weird bug :P Glad you found a workaround.

**Comment by NillerMedDild** [comment]
Changing Mekanism version to DZ fixed it properly :)

**Comment by unlimitedsola** [comment]
@NillerMedDild This issue still exists in 1.81a (which is the latest version when this is posted). Tried to filter `oreClathrate` and shows count 0.

**Comment by NillerMedDild** [comment]
In which dimension?

**Comment by unlimitedsola** [comment]
@NillerMedDild I've tried `oreClathrateGlowstone` in Mercury and `oreClathrateRedstone` in TerraNova. both of them did not work.

**Comment by NillerMedDild** [comment]
I'm sorry to hear that :/ Sadly Mekanism only fixes critical issues on 1.12 now, so there's not much we can do.
