### ISSUE TITLE
Replicator cost of Reactor Glass

### ISSUE THREAD

**Issue by Nutarama** [NillerMedDild/Enigmatica2Expert#926]
Not really a crash-related bug so not super serious, but "Reactor Glass (Legacy)" can be scanned in the scanner, but for some reason requires 436.4 B of UU-Matter to replicate.  That's a LOT of Buckets of UU-Matter.  The Reactor Casing (Legacy) can also be scanned but costs only 5.459 mB, despite effectively being the same but opaque.

I'm thinking the recipe should at least be reduced to 436.4 mB, maybe even to 43.64 mB (I don't know the way the amounts are generated (script or by hand?) but the current cost seems to obviously be a bug.  As it's not an IC2 item, I assume the value is yours to control as the modpack author.

**Comment by NillerMedDild** [comment]
That is a generated UU-matter value, I don't change those for the most part :)

**Comment by Nutarama** [comment]
Hmm, have to wonder why it generated that way then. the recipe is just a casing and two fused quartz blocks.

**Comment by NillerMedDild** [comment]
Fused Quartz is considered very expensive I guess.
