### ISSUE TITLE
Empowered Canola Seed Compat

### ISSUE THREAD

**Issue by NillerMedDild** [NillerMedDild/Enigmatica2Expert#927]
Empowered Canola Seed should be craftable in DE Fusion and EC Combination

**Comment by MaxNeedsSnacks** [comment]
May do this real quick if you haven't already ^^

**Comment by NillerMedDild** [comment]
I haven't, that'd be nice :)

**Comment by MaxNeedsSnacks** [comment]
Whoops, I just did it to my local instance instead, hold up.

What's the cost for Empowered Canola Seeds again btw?

**Comment by NillerMedDild** [comment]
Sounds about right.

**Comment by MaxNeedsSnacks** [comment]
There we go, that should do it ^^
