### ISSUE TITLE
vanilla and new crafting recipes showing both time

### ISSUE THREAD

**Issue by BlackHoleTON618** [NillerMedDild/Enigmatica2Expert#929]
**Modpack version**
Iatest

**Can the issue be reproduced?**
dont know

**Logs**

**Issue**
i have vanilla and modpack crafting recipes at the same time 

If this is a feature request, feel free to delete the template.

**Comment by MaxNeedsSnacks** [comment]
Can you actually craft the "removed" recipes?

**Comment by MorganSimic** [comment]
Your scripts are broken. That can have a some different causes. Did you change something in the modpack? Removed mods, disabled mods or did change configs? Disabling channels in AE config comes to mind in particular.

**Comment by BlackHoleTON618** [comment]
yes i can craft removed and edited mods both and it's not edited it is on latest version and i didint delete or added anything I download modpack from twitch

**Comment by NillerMedDild** [comment]
Try re-installing the modpack.

**Comment by BlackHoleTON618** [comment]
i did it i deleted my all Minecraft and re download modpack and  forge its not working is it a bug ? or i have to pick  normal mode or expert mode in game because my modpack is enigmatica 2 expert

**Comment by MorganSimic** [comment]
It's not a bug. It works just fine, so you are doing something wrong, we just have to figure out what. Just to make sure, you did delete the profile on the twitch launcher and then installed it with the twitch launcher again and nothing else?

**Comment by BlackHoleTON618** [comment]
yes i did exactly what you said and now it crushed

**Comment by MorganSimic** [comment]
Please share a crash report then. Copy it to hastebin.com or gist.github.com and link it.

**Comment by BlackHoleTON618** [comment]
i spent 8 hours to remove every crafting recipe and i put enigmatica 2 ones all i have is enigmatica 2 recipes but there is 1 problem left flux core cannot be crafted because i need flux core to make flux cores

**Comment by MaxNeedsSnacks** [comment]
The flux core recipe is intentional, check the other recipes: You can only get your first flux core through sag milling a dimensional transceiver

**Comment by BlackHoleTON618** [comment]
thank you what if i add mods to enigmatica 2 expert like ender zoo abyssalcraft animalium will recipes affected ?

**Comment by MaxNeedsSnacks** [comment]
shouldn't change anything

**Comment by MaxNeedsSnacks** [comment]
In fact there's "soft support" for a couple of mods from what I can tell so if you for example added Refined Storage there's modified recipes for that
