### ISSUE TITLE
missing texture

### ISSUE THREAD

**Issue by RandAlThorn** [NillerMedDild/Enigmatica2Expert#931]
**Modpack version**
1.56

**Can the issue be reproduced?**
Yes

Minor Issue**
Both advanced motor and enhanced motor from vulpes library are missing textures in AE2 Crafting pattern. As i mentioned above, this is a minor issue and not even sure it is a modpack or mod issue but figured id pass it along.

**Comment by NillerMedDild** [comment]
Thanks for the info :) do the crafting patterns still work?

**Comment by Tntdruid** [comment]
They get texture when you place and pick them up, patterns works fine

**Comment by RandAlThorn** [comment]
yes the patter still works fine. just a texture hiccup.
