### ISSUE TITLE
HEADS UP. Twitch update 3/3/2019

### ISSUE THREAD

**Issue by Kuktar** [NillerMedDild/Enigmatica2Expert#932]
So twitch just made a change to the way Minecraft is stored in regards to windows environment. Just a heads up it used to be stored 

C:\Users\kuktar\Documents\Curse\Minecraft\Instances\Enigmatica 2 Expert

Now when you load twitch after the update it looks like Minecraft disappeared. That is because it's looking at this new directory. 

C:\Users\kuktar\Documents\Twitch\Minecraft\Instances\Enigmatica 2 Expert

they change the root folder name from curse to twitch.

If you want to retain all your settings and stuff from the previous version just copy the old Minecraft folder.

I know this is the issue tracker but i wanted to let everyone know if possible.

**Comment by MaxNeedsSnacks** [comment]
Think this should be (temporarily) pinned and / or tagged with "Information" so people coming to this issue tracker notice this quickly.

I was actually surprised myself when my Instances suddenly ended up in two different folders lol

**Comment by NillerMedDild** [comment]
Thanks for the info, pinned :)
