### ISSUE TITLE
Corail Tombstone instead of TMG (tomb many graves)

### ISSUE THREAD

**Issue by Kuktar** [NillerMedDild/Enigmatica2Expert#933]
So a mod that is lesser known but amazing gravestone mod is called corail tombstone. Instead of a paper with coordinates, it gives you a key to access your grave with the metadata being the coordinates.  

The best part of the modpack is the crafting element. you can make a key with 1 ender pearl to teleport you to your grave. there is also a soulbound aspect of it you can craft. It is just got so many options. its actualy a really amazing gravestone mod.

food for thought.

I just made it to my exploring phase. got a water mill setup and completed all the immersive quests. took me all weekend to acomplish this :P love this modpack!

**Comment by NillerMedDild** [comment]
I prefer TMG for the autofill from grave feature, but thanks for the suggestion :)
