### ISSUE TITLE
draconium ore from void ore miner 6 is unprocessable

### ISSUE THREAD

**Issue by cosmosgenius** [NillerMedDild/Enigmatica2Expert#935]
**Modpack version**
1.57

**Can the issue be reproduced?**
Yes

**Issue**
The draconium ore(Base Ore) which we get from void ore miner 6 was previously process-able in mechanism machine. I was able to triple the output before. Now it seems the machines don't accept the ore. This includes the Nuclearcraft Manufactory.

If this is a feature request, feel free to delete the template.

**Comment by NillerMedDild** [comment]
Dammit, I un-commented some incorrect code it seems :P Sorry about that.

**Comment by cosmosgenius** [comment]
Is there anything i can do from my side to fix this?

**Comment by NillerMedDild** [comment]
[OreDict.zip](https://github.com/NillerMedDild/Enigmatica2Expert/files/2926340/OreDict.zip)
Unzip that into your scripts folder and overwrite :)

**Comment by cosmosgenius** [comment]
Thanks a bunch!!! Its working now.

**Comment by NillerMedDild** [comment]
Sure thing, thanks for testing it ^^
