### ISSUE TITLE
Add Loot Capacitor Tooltips

### ISSUE THREAD

**Issue by NillerMedDild** [NillerMedDild/Enigmatica2Expert#936]

**Comment by Tfarcenim** [comment]
Author here let me know if any issues pop up

**Comment by NillerMedDild** [comment]
Will do :D

**Comment by MaxNeedsSnacks** [comment]
@Tfarcenim If I may suggest something very minor, Loot Capacitor Tooltips currently has a hard dependency on the monolithic EnderIO installation on CurseForge. That might be something you should change because some folks prefer the modular installation ^^

**Comment by Tfarcenim** [comment]
alright, I'll change the dependency in the next release

**Comment by Tfarcenim** [comment]
https://github.com/Tfarcenim/lootcapacitortooltips/commit/a48291165bf198f57df38223069521506d591a58

**Comment by MaxNeedsSnacks** [comment]
Oh I actually meant that only for the uploads to CurseForge, does CurseForge actually check through the @Mod annotation?

**Comment by Tfarcenim** [comment]
no, but the @mod may not work for modular installs, but as long as the capacitors exist it won't crash, next version will have hard dep removed
