### ISSUE TITLE
Crash at Game Launch 1.5.7

### ISSUE THREAD

**Issue by KCtops100** [NillerMedDild/Enigmatica2Expert#937]
**Modpack version**
1.5.7

**Can the issue be reproduced?**
Unknown

**Logs**
https://gist.github.com/KCtops100/7b00a767429fda7a7a06f0c3853a26cc

**Issue**
Fresh from the 1.5.7 update of the modpack, launching my game crashes after ~20 seconds of loading time.

Appreciate the help in advance!

**Comment by NillerMedDild** [comment]
That crash is usually caused by outdated graphics drivers, try updating them, and please let me know if it solves you issue :)
