### ISSUE TITLE
Mekanism Enrichment Chamber Quest Line 

### ISSUE THREAD

**Issue by eLLL1337** [NillerMedDild/Enigmatica2Expert#938]
**Modpack version**
Enigmatica 2: Expert 1.57

**Can the issue be reproduced?**
Yes

**Issue**
i build the Enrichment Chamber but the quest doesnt detect the chamber.
even a cheated chamber does not work.

Is there a way to activate this task with a command or something?

best regards

**Comment by MaxNeedsSnacks** [comment]
This might just be another NBT data problem, can you try placing and breaking it real quick?

**Comment by eLLL1337** [comment]
does not work sadly

**Comment by MaxNeedsSnacks** [comment]
Was worth a shot. Can you send me a screenshot where you're hovering over the quest item and holding down control? I want to see whether there's a way for you to get this legitimately

**Comment by MaxNeedsSnacks** [comment]
I mainly want to see the NBT data of the item that the quest wants

**Comment by eLLL1337** [comment]
yeah, with shift+h and then take a screenshot..
![2019-03-04_23 03 52](https://user-images.githubusercontent.com/48225726/53766086-29643c80-3ed2-11e9-877b-7bc1dc928289.png)

**Comment by MaxNeedsSnacks** [comment]
Does it have any NBT data, though? ![image](https://user-images.githubusercontent.com/12750501/53766134-531d6380-3ed2-11e9-9b65-907933e9b4ef.png)

**Comment by eLLL1337** [comment]
{mekData:{}} in the quest.
and the chamber in my inventory shows like this:
![2019-03-04_23 09 06](https://user-images.githubusercontent.com/48225726/53766244-a1cafd80-3ed2-11e9-91f3-2618f20a4464.png)

**Comment by MaxNeedsSnacks** [comment]
Ah alright, the problem is the same as with the Electrolytic Separator then.

For now use /bq_admin complete <the quest id, pretty sure that's right next to the quest name when you hover over it in the chapter> <your username> to force-complete it.

Sorry for the troubles, I missed an ignoreNBT on that one ^^'

**Comment by eLLL1337** [comment]
thank you very much :) mistakes happen :>
no problem!

**Comment by MorganSimic** [comment]
The quest worked previously so this is also caused by the Mek fork switch I mentioned in #939.

**Comment by MrPoro1** [comment]
I am having the same problem but I can't figure the quest ID out. Pressing control over quest does nothing. Could you guys help?

**Comment by gzcwnk** [comment]
I have this problem also.

**Comment by gzcwnk** [comment]
How can I see the ID? no keys mentioned work?  :(

**Comment by NillerMedDild** [comment]
press F3 + H to see the more detailed info

**Comment by NillerMedDild** [comment]
but you should use the command `/bq_admin default load`

**Comment by gzcwnk** [comment]
I do not have permission to run that command

**Comment by NillerMedDild** [comment]
Open your world to LAN, enable cheats

**Comment by gzcwnk** [comment]
The server is open to the world

**Comment by NillerMedDild** [comment]
Then ask the owner of the server to update and run that command.

**Comment by gzcwnk** [comment]
To which version? this is 1.58

**Comment by NillerMedDild** [comment]
To the latest version, 1.59a. 
This issue tracker is for bug reports, not support, please go to the Discord channel instead.

**Comment by gzcwnk** [comment]
So I'll need support for discord, LOL....oh joy.

**Comment by NillerMedDild** [comment]
I think you misunderstood me. 

GitHub is for reporting bugs, if you need help you should go to the Discord channel instead.

**Comment by gzcwnk** [comment]
I am in NZ I cant get support in real time, the rest of the world is asleep

**Comment by NillerMedDild** [comment]
I think it's pretty obvious that I'm awake, I'm talking about the support channel for Enigmatica
https://discord.gg/edx6pk
