### ISSUE TITLE
TODO: Fix Mekanism Quest Line's NBT problems

### ISSUE THREAD

**Issue by MaxNeedsSnacks** [NillerMedDild/Enigmatica2Expert#939]
**Modpack version**
1.57

**Can the issue be reproduced?**
Yes

**Issue**
Some Mekanism quest items still have the "mekData:{}" on them, causing some issues when claiming them. I'm currently working on too many different things to get this done, but if anyone else wants to step up and do it, that'd be appreciated. This issue is pretty much just here to "raise awareness" that there's still a problem with the questline.

**Comment by MorganSimic** [comment]
The problem also is that some tags were changed around with switching to another Mek fork. So some stuff is now crafted without tags, some stuff is. So you have to be really careful with this quests. Cheating in the item may not be the same nbt tag as crafting it. Be aware of that.
