### ISSUE TITLE
Wither Skulls 

### ISSUE THREAD

**Issue by Darkstone158** [NillerMedDild/Enigmatica2Expert#940]
This is a Feature request for a different way to get wither skull right now the only way to get them from what I could see it is to kill wither skeletons do you think you could add top tier magical crops seed for them or have 8 drops of evil around a normal skeleton skull

**Comment by DrTasslehoff** [comment]
They cost 50mb of UU each to replicate.

**Comment by NillerMedDild** [comment]
I don't think it needs additional recipes :)
