### ISSUE TITLE
RFTools powercell overflowing

### ISSUE THREAD

**Issue by darwithe** [NillerMedDild/Enigmatica2Expert#941]
**Modpack version**
Enigmatica 2 Expert 1.57

**Can the issue be reproduced?**
Yes

**Logs**
N/A

**Issue**
The recent change to the RFTools powercell (Issue #852 ) results in an integer overflow(positive number flips to negative number) in the cell hive with just a handful of Advanced Powercells.

**Comment by NillerMedDild** [comment]
Sorry about that, I didn't think the networks would overflow so easily. What are you hoping to get from this issue?

**Comment by darwithe** [comment]
Err a reversion so I don't have to manually do it every update? 
Sorry I guess I should have been more clear, this isn't just "Oh no, my power is suddenly negative and needs to recharge before things work again", it's also "My cell hive stopped accepting or distributing power because it thinks it has negative capacity." I suppose technically I could drop down more Adv. Powercells so it loops back around again, but I was getting weird results from my redstone power cutoffs too, and frankly having to constantly watch that I don't accidentally overflow again sounds un-fun.

**Comment by NillerMedDild** [comment]
I won't revert the change, the Creative Powercells needed the buff.

What you can do, is reduce the amount of Powercells you have per channel/network to make sure the total power capacity is less than `2147483647`RF. I'll report the issue to hopefully get it fixed though.

**Comment by NillerMedDild** [comment]
https://github.com/McJtyMods/RFTools/issues/1214

**Comment by darwithe** [comment]
That's less than 6 Adv. Powercells per network which is way to low. I did some more testing and it's wierd, sometimes it is constrained, and then suddenly it flips negative and then the network locks up, it's really really inconsistant.

Anyway best solution I've found is to drop 1369: I:advancedFactor back to 4. But buff 1390:     I:rfPerTick up to 250000. That results in the same 1mrf/t from a creative cell as the factor 40 does but doesn't risk ruining cell networks. The only downside I can see for this is that it buffs the regular Powercell to the point you no longer need Adv. Powercells as much. But frankly the recipe for Adv. Powercell compared to regular Powercell is so cheap that the effect is fairly minimal.

**Comment by NillerMedDild** [comment]
Good point, I'll make the change.

**Comment by MorganSimic** [comment]
I'm not sure why the overflowed network stopped working. Mine is just runnning fine even with negative energy numbers. I have 2 networks, both overflowed. Input and output works just fine on both networks. What i could see is redstone monitoring breaking because of that.
