### ISSUE TITLE
IC2 Replicator costs 

### ISSUE THREAD

**Issue by WarlowAus** [NillerMedDild/Enigmatica2Expert#942]
**Modpack version**
1.56

**Can the issue be reproduced?**
unknown

**Logs**
n/a

**Issue**
actually additions small storage crate costs 32 full buckets of UU matter to replicate.
Compacting drawer costs 8.2 full buckets of UU matter to replicate.
crystal memory costs 433.4 full buckets.

It was the same in earlier editions too so I don't think it's new.

Are these intended costs? I get that sometimes you might prefer to steer a player towards automating in other ways, but it seems like a mistake as you'd have probably just disabled them if it was intentional.

https://imgur.com/a/hDglVXs

Some screenies, in case something odd specifically with my situation and you think I'm crazy.

Apologies, I'm not sure of the etiquette  in reporting issues via github

If this is a feature request, feel free to delete the template.

**Comment by WarlowAus** [comment]
To clarify, most items cost <100 milibuckets of UU matter which contrasts pretty well

**Comment by NillerMedDild** [comment]
Welcome to GitHub :D your etiquette is just fine!

The vast majority of UU-matter values are created by an algorithm from IC2, I only made a handful of them. So you'll find some odd values here and there. I believe Wheat is 7 buckets :P

I'm not going to start patching the generated UU-matter values, as there are thousands.
