### ISSUE TITLE
Fixing advancement loading issues

### ISSUE THREAD

**Issue by Cyprex** [NillerMedDild/Enigmatica2Expert#943]
I'm considering fixing the advancement loading issues, as far as I can tell there are three ways to approach this:
* Include fixed copies of broken advancements in the data/advancements folder of a world folder.
  The issue with this is ensuring the files are in newly created worlds, are there mechanisms to do this?
* Modify the advancements in the mod jars
  I could probably write a small script that requires 7z which would replace the original advancement jsons with modified ones, but are we even able to ship modified jars?
* Try to fix whatever causes the exceptions, in the case of the integrated dynamics menril_production quest it tries to unlock a recipe(in the vanilla recipe book?) removed by the scripts. This particular case would probably be fixed by adding a dummy recipe with the ID "integrateddynamics:menril_planks", but I'm not sure how to add recipes with the integrateddynamics: scope.

**Comment by MaxNeedsSnacks** [comment]
Option No. 2 is already a solid no from Curseforge, unfortunately. Modified jars are not allowed.

Also I think Triumph can overwrite advancements so you could use that... don't quote me on this tho

**Comment by Cyprex** [comment]
I feel like using Triumph (which requires a coremod) would add more complexity than adding files to the data/advancements folder for newly created worlds, even if it turns out a mod is necessary to do this.

**Comment by NillerMedDild** [comment]
Attempted fix number 3 with `recipes.addShapeless("integrateddynamics:menril_planks", <integrateddynamics:menril_planks>, [<integrateddynamics:menril_log>]);`

**Comment by NillerMedDild** [comment]
No fix found after numerous attempts.
