### ISSUE TITLE
extrautils 2 pressing T no longer works

### ISSUE THREAD

**Issue by niklas2233** [NillerMedDild/Enigmatica2Expert#944]
pressing T no longer works after version 1.57. nothings happens but it worked before the update

**Comment by NillerMedDild** [comment]
Did you check if the keybinding is still T?

**Comment by niklas2233** [comment]
yes http://prntscr.com/mtposy

**Comment by NillerMedDild** [comment]
Cool, what about restarting the pack?

**Comment by niklas2233** [comment]
nope still doesn't work

**Comment by NillerMedDild** [comment]
Cool, I'll look into it, thanks for reporting.

**Comment by irotha** [comment]
Try removing Bibliocraft inventories nearby, we had made some Bibliocraft chests to start since the recipe was easier. 
When nearby Bibliocraft chests something like [https://pastebin.com/ci073Q8P](url) spams the server logs(or your clients if SP) when you attempt to search
Same issue as [https://github.com/Nuchaz/BiblioCraft/issues/601](url)

**Comment by niklas2233** [comment]
nope there is none bibliocraft blocks that i can find

**Comment by MaxNeedsSnacks** [comment]
Does this issue still persist on 1.58?

**Comment by niklas2233** [comment]
yes

**Comment by MaxNeedsSnacks** [comment]
What kind of inventory are trying to look through, anyway?

**Comment by niklas2233** [comment]
storage crates from actually addition

**Comment by MaxNeedsSnacks** [comment]
Weird... I just tested it on a small storage crate at least, and had no problem...

**Comment by niklas2233** [comment]
weird i just tried it aswell and it works on a new save but not on my old one

**Comment by MaxNeedsSnacks** [comment]
What blocks do you have near your storage crate?

**Comment by MaxNeedsSnacks** [comment]
There's some blocks from certain blocks that apparently break it

**Comment by niklas2233** [comment]
mostly furnace and tinker tool stuff

**Comment by MaxNeedsSnacks** [comment]
Is the console getting spammed with any error?

**Comment by niklas2233** [comment]
dont know, dont have a console

**Comment by MaxNeedsSnacks** [comment]
Can't reproduce the issue, sorry :/

**Comment by niklas2233** [comment]
Where is the console?

**Comment by MaxNeedsSnacks** [comment]
It should normally just open as a window when you start playing. Also everything in the console output is stored in the latest.log

**Comment by niklas2233** [comment]
Okey will check it
