### ISSUE TITLE
Mekansm/ Tinker's Construct Fuel tank crash

### ISSUE THREAD

**Issue by codyaha** [NillerMedDild/Enigmatica2Expert#945]
**Modpack version**
1.57

**Can the issue be reproduced?**
Yes

**Logs**
The game crashed whilst rendering block entity
The game crashed whilst rendering block entity
Error: java.lang.IllegalStateException: Not building!

**Issue**
While trying to craft Mekanism Fuel/ liquid tanks into Tinkers Construct Crafting stations, the crafting station fails to render and then causes the game to crash.

**Comment by NillerMedDild** [comment]
I can't really fix this issue, you just have to use another crafting table.
