### ISSUE TITLE
Thermoelectric Generator produce nothing

### ISSUE THREAD

**Issue by maginator** [NillerMedDild/Enigmatica2Expert#947]
**Modpack version**
1.56

**Can the issue be reproduced?**
Yes

**Logs**

**Issue**
The Thermoelectric Generator from IE Produce no Power I try different setups but nothing work. Maybe i'm stupid and do everything wrong but yea :D

![2019-03-06_18 27 54](https://user-images.githubusercontent.com/19614585/53900909-dc9d7480-403d-11e9-8552-3aae4a467197.png)

If this is a feature request, feel free to delete the template.

**Comment by NillerMedDild** [comment]
Are the IE Energy Cells set to output on the side with Capacitor Banks on?

**Comment by maginator** [comment]
Yes and down is Blue as Input

**Comment by NillerMedDild** [comment]
I'm not sure if IE and EnderIO are able to interact with eachother's energy types directly, can you try with a Fluxduct between the Thermoelectric Generator and the Capacitor Bank please?

**Comment by maginator** [comment]
Yea I try it it dosent work. It seems that the Thermoelectric Generator doesnt produce any power

**Comment by MorganSimic** [comment]
I see what is wrong. Cold and hot need to be on opposite sides of each other. You have hot opposite of hot, cold opposite of cold. It needs to be for example, water opposite of lava.

**Comment by maginator** [comment]
Oh okay thank you anderen Sry for Thema issue
