### ISSUE TITLE
In Control! Disallow Mobs on Planets without Oxygen

### ISSUE THREAD

**Issue by NillerMedDild** [NillerMedDild/Enigmatica2Expert#948]
**Modpack version**
Input version here

**Can the issue be reproduced?**
Yes/no/unknown

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Issue**
Input short description of the issue here

If this is a feature request, feel free to delete the template.

**Comment by MorganSimic** [comment]
If your are at it already, you could also prevent EmberRootZoo mobs from spawning inside Compact Machines. I'm not 100%  InControl allows for that but i'm pretty sure. This is the most annoying thing about EmberRootZoo. They plague machines and there is nothing you can do.

**Comment by NillerMedDild** [comment]
Ah right! Can you remember it's ID?

**Comment by MorganSimic** [comment]
The Dimension ID or what do you mean? Also i should read better there is already #135. My bad.

**Comment by MorganSimic** [comment]
The Dimension ID for Compact Machines is 144.
