### ISSUE TITLE
new feature idea (quests)

### ISSUE THREAD

**Issue by DoorLord2** [NillerMedDild/Enigmatica2Expert#949]
#**Modpack version**
enigmatica 2 expert 1.57 

i'd like to see more quests in blood magic tab with quick description on every each quest (bacause blood magic guide book isn't realy helping). 
By "more" quests i mean adding sigils, rituals and so on...

**Comment by NillerMedDild** [comment]
I will most likely not make any more quests.

**Comment by DoorLord2** [comment]
yeah, but i find myself in some sorf of circle.. asking myself "what is that sigil for (talking also about sigils from animus) ? or what does this ritual do ? if there won't be any more quests in the book then some description of sigils or rituals will help a lot.

**Comment by NillerMedDild** [comment]
This is an expert pack, I'm not going to explain every single thing. You can craft it and try it out for yourself, or just google it.
