### ISSUE TITLE
Wrenching rftools Storage module deletes it.

### ISSUE THREAD

**Issue by Bigmanvegas** [NillerMedDild/Enigmatica2Expert#95]
#### Issue Description
When I wrenched a rftools modular storage block to pick it up with either crescent hammer or  smart wrench it just deletes it without dropping anything.

using the caryon mod on it works as intended.
#### Modpack version (Do not use "latest")
Ver. 1.26c

**Comment by NillerMedDild** [comment]
https://github.com/McJtyMods/RFTools/issues/1776
https://github.com/tyra314/ToolProgression/issues/33
