### ISSUE TITLE
TiC and PlusTiC tools can't by repaired in Powered Diamond Anvil now

### ISSUE THREAD

**Issue by Lexon78** [NillerMedDild/Enigmatica2Expert#951]
**Modpack version**
1.57

**Can the issue be reproduced?**
Yes

**Issue**
In Patch 1.57 no more can't be repaired Laser Gun from Plus TiC and Hammer from TiC in Powered Diamond Anvil (from Cyclic). I try Item Repairer from Actually Addition and this block can repair Hammer from TiC, but no Lasser Gun from Plus TiC.

If this is a feature request, feel free to delete the template.

**Comment by MaxNeedsSnacks** [comment]
This is (more or less) a duplicate of Lothrazar/Cyclic#1080, a fix has already been suggested, but yet to be implemented by Lothrazar

**Comment by NillerMedDild** [comment]
Dammit, I was hoping this was intentional :P guess we'll wait for the fix.

**Comment by MorganSimic** [comment]
I had a devious idea. The diamond anvil is just a way better Item Repairer the thing from AA. And that thing is expensive as heck. Make the anvil require that thing for crafting. Just a thought. ;)

**Comment by NillerMedDild** [comment]
ohohohoh!

**Comment by NillerMedDild** [comment]
https://github.com/NillerMedDild/Enigmatica2Expert/issues/955

**Comment by Wntermute** [comment]
There's also the lava-powered Magma Anvil.. I drained many a lava pool powering that thing.

**Comment by MaxNeedsSnacks** [comment]
Oh yeah @NillerMedDild apparently it *is* intentional by the way lol

**Comment by NillerMedDild** [comment]
Sweet!
