### ISSUE TITLE
Game freezes when i mine certain blocks

### ISSUE THREAD

**Issue by WubWubWeb** [NillerMedDild/Enigmatica2Expert#954]
**Modpack version**
1.57

**Can the issue be reproduced?**
unknown

**Logs**
Isn't pastebin but I hope this is fine
https://drive.google.com/open?id=1YJy1urBezH5xcn3f-2W-u0_YMijb1c6a

**Issue**
Basically, my game freezes every time I mine certain blocks. I can't for the life of me find out what the cause is and I'm seemingly the only person with this issue. The blocks I've had issues with are dirt and gravel but I haven't had the patience to test any more because of how long it takes to start up but if needed I'll do some more testing. The game seems to run in the background because I let it be for around 10 minutes and then force closed it. Then when I looked at the log I was killed by a zombie.

EDIT: I should add that I have 6Gb of RAM allocated to the game and that both my CPU and GPU are powerful enough to run other ~200 mods modpacks fine.

**Comment by NillerMedDild** [comment]
What is that log from? The server?

**Comment by WubWubWeb** [comment]
That's weird because I only recently updated java and the game hasn't made any complaints as of now. What I did do is switch to 64-bit java so maybe that's the cause of the problem.

I should also add that this seems to be the only modpack where this issue arrises.

**Comment by NillerMedDild** [comment]
32-bit Java would only allow you to allocate 2GB of RAM, and that wouldn't even launch this modpack. You're using 64-bit Java, version 1_8.51, the version bundled with Minecraft.

You need to go into Twitch settings, and either switch to Jar Launcher from Native Launcher, or input these Java arguments at the bottom: `-version:1.8+ -XX:+UseG1GC -Dsun.rmi.dgc.server.gcInterval=2147483646 -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M`

**Comment by NillerMedDild** [comment]
Please let me know if that resolves your issue, or if you need additional assistance.

**Comment by WubWubWeb** [comment]
That fixed it. I was afraid I'd never get to play this so thanks for taking the time to help me.

**Comment by NillerMedDild** [comment]
My pleasure :)
