### ISSUE TITLE
Diamond Anvil 

### ISSUE THREAD

**Issue by NillerMedDild** [NillerMedDild/Enigmatica2Expert#955]
Morgan: 
I had a devious idea. The diamond anvil is just a way better Item Repairer the thing from AA. And that thing is expensive as heck. Make the anvil require that thing for crafting. Just a thought. ;)

**Comment by MaxNeedsSnacks** [comment]
Oh that is... **that is evil**.

I love it.

Dropping **EVERYTHING** else I'm doin because that is good

**Comment by MorganSimic** [comment]
What have i done? Now people are going to hate me. But that's fine. I like it.

**Comment by NillerMedDild** [comment]
Welcome to modpack development :P

**Comment by MaxNeedsSnacks** [comment]
You know your suggestion is evil when an expert mode packdev rubs his hands in content while implementing it >:)

**Comment by Tarod7** [comment]
Super evil...

**Comment by Nemo4evr** [comment]
There is a special place in hell for that type of suggestions. . . I have volunteered to build it. . . for minimum wage also :-P
