### ISSUE TITLE
JEI Sticks recipe error

### ISSUE THREAD

**Issue by RGoblin** [NillerMedDild/Enigmatica2Expert#960]
**Modpack version**
1.57

**Can the issue be reproduced?**
Yes 

**Issue**
Error in JEI recipe making sticks. JEI shows 2 planks in line, but it must show 2 planks in column. Screenshot: [https://clip2net.com/s/40i8UWZ](url)

**Comment by NillerMedDild** [comment]
Incorrect, the Stick recipe is shapeless in this modpack.
