### ISSUE TITLE
Inventory tweaks don't work with Crafting Station (TC)

### ISSUE THREAD

**Issue by RGoblin** [NillerMedDild/Enigmatica2Expert#961]
**Modpack version**
1.57

**Can the issue be reproduced?**
Yes

**Issue**
Inventory tweaks don't work with crafting station from Tinkers construct. There's neither buttons showing in interface of crafting station, nor shortcuts working in there.
Screenshot with no buttons: [https://clip2net.com/s/40i9bBd](url)

**Comment by NillerMedDild** [comment]
Just as it should be :)

**Comment by RGoblin** [comment]
It's strange, because of in other modpacks it works)

**Comment by NillerMedDild** [comment]
You mean you can't sort the 9 slots the crafting table has, right?

**Comment by RGoblin** [comment]
I can't move an item with one shift-mouse-click from inventory to crafting table, in example... It's very useful...

**Comment by NillerMedDild** [comment]
I can move an item into the Crafting Station with shift click. That is not a feature from Inventory Tweaks though.

**Comment by MaxNeedsSnacks** [comment]
Crafting Tweaks adds that feature and it **should** under normal circumstances just... work

**Comment by NillerMedDild** [comment]
and Crafting Tweaks isn't in this pack ^^
