### ISSUE TITLE
Aspects AE2

### ISSUE THREAD

**Issue by Cooledynth** [NillerMedDild/Enigmatica2Expert#962]
**Modpack version**
1.57

**Can the issue be reproduced?**
unknown

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Issue**
When shift hovering over items in AE2 the UI expands to show where aspects from thaumcraft, but doesn't display the aspects on the item. It the works if the item is removed from storage.

If this is a feature request, feel free to delete the template.

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
https://github.com/Azanor/thaumcraft-beta/issues/1244

**Comment by NillerMedDild** [comment]
Doesn't look like it'll be fixed :/

**Comment by Cooledynth** [comment]
Damn, thanks for the help though :)
