### ISSUE TITLE
CRASHHHHHHHHHHHH

### ISSUE THREAD

**Issue by BlackHoleTON618** [NillerMedDild/Enigmatica2Expert#963]
**Modpack version**
1.56

**Can the issue be reproduced?**
unknown

**Logs**

[2019-03-09-6.log](https://github.com/NillerMedDild/Enigmatica2Expert/files/2948382/2019-03-09-6.log)

**Issue**
crash after loading the game
 Launched Version: 1.12.2-forge1.12.2-14.23.5.2781
i did not added and deleted any mods its just crashing after downloading the modpack first time

**Comment by NillerMedDild** [comment]
Re-download :)

**Comment by BlackHoleTON618** [comment]
its not fair its my 5 th downloading time please read that log its abaut the advanced rocketery

**Comment by NillerMedDild** [comment]
I'll have a look this evening. I'm guessing you're actually crashing while entering your world?

**Comment by NillerMedDild** [comment]
You're using Forge `1.12.2-14.23.5.2768` not `1.12.2-14.23.5.2781` as you should.
