### ISSUE TITLE
Mekanism Energized smelter quest not working

### ISSUE THREAD

**Issue by zhongjiedong** [NillerMedDild/Enigmatica2Expert#964]
**Modpack version**
1.57

**Can the issue be reproduced?**
Yes

**Logs**
-

**Issue**
Mekanism Energized Smelter not being recognised for quest completion

**Comment by NillerMedDild** [comment]
I know, I'll get it fixed asap :)

**Comment by webbster64** [comment]
**Modpack version**
1.58

**Can the issue be reproduced?**
yes

**Issue**
Hi
I did the update to version 1.58 but still the quest Energized Smelter doesn't work

**Comment by NillerMedDild** [comment]
Hm, dammit. I'll check it out again, worked just fine for me though.
