### ISSUE TITLE
repeat: JEI Sticks recipe error #960

### ISSUE THREAD

**Issue by RGoblin** [NillerMedDild/Enigmatica2Expert#965]
**Modpack version**
1.57

**Can the issue be reproduced?**
Yes

**Issue**
2  planks in line make a pressure plate: https://clip2net.com/s/40ipAql , so **recipe is not shapeless**.
>> Error in JEI recipe making sticks. JEI shows 2 planks in line, but it must show 2 planks in column. Screenshot: https://clip2net.com/s/40i8UWZ
>>NillerMedDild commented 6 hours ago: Incorrect, the Stick recipe is shapeless in this modpack.

**Comment by MaxNeedsSnacks** [comment]
The recipe is shapeless, except for one specific configuration.

There is no way to change the way JEI currently displays shapeless recipes.

Try **any** other configuration of two planks in a crafting table. It **will** make sticks

**Comment by RGoblin** [comment]
it make sticks in other shapes, I know about it, but JEI should be configurable to not show "wrong" recipes.

**Comment by NillerMedDild** [comment]
Wow, you just made a new issue. I'll make the recipe shaped -.-

**Comment by RGoblin** [comment]
>.<
