### ISSUE TITLE
Modular Storage "multipick"

### ISSUE THREAD

**Issue by RGoblin** [NillerMedDild/Enigmatica2Expert#966]
**Modpack version**
1.57
**Can the issue be reproduced?**
Yes

**Issue**
Shift-mouseclick in Modular Storage (RFTools) cause moving many items into inventory.
Before "shift-click": https://clip2net.com/s/40isbYx
After "shift-click": https://clip2net.com/s/40ishSm (look at inventory - it's all I get with one shift-mouseclick)

P.S. Yeah, It's me again, with greetings from cold-winter Russia :) Thanks for your modpack - it's great)

**Comment by NillerMedDild** [comment]
That's intentional :) It's a bit annoying at first, but you get used to it, sorta.

**Comment by RGoblin** [comment]
It's sad that you couldn't fix it... :(

**Comment by NillerMedDild** [comment]
Well it's not broken.

**Comment by RGoblin** [comment]
such behavior looks like it's broken, but it seems it's a mod problem, not yours.

**Comment by NillerMedDild** [comment]
Again, it's not a bug, it's a design choice.
