### ISSUE TITLE
Today's update 1.58 RFTools Advanced Powercells trouble

### ISSUE THREAD

**Issue by BattleNachos** [NillerMedDild/Enigmatica2Expert#967]
My setup is two advanced powercells.  One is being fed by my mek gas gen, that cell feeds a second advanced powercell.  That second powercell feeds 4 regular powercells via linked cards.  When I started my game today nothing had power, the advanced powercell fed by my gas gen had gone negative RF.  

I played around a bit and found that two powercells directly touching with one feeding the other will cause both to stop accepting rf.  Powercells can still feed into Imm. Eng. and EnderIO capacitors without issue.

I like having a central rf bank, but i guess it's not necessary w/ powercells.

**Comment by Darkstone158** [comment]
I'm having a similar issue with power I am using flux networks and every time i log back on to my world nothing has power and i  have to make a new flux channel for them to transfer power

**Comment by MaxNeedsSnacks** [comment]
@BattleNachos the powercell looping back to negative numbers **should** just be a cosmetic issue, you said it works in any other case right?

**Comment by BattleNachos** [comment]
@MaxNeedsSnacks It only works now that no two rftools powercells are physically touching eachother.

**Comment by xob** [comment]
I can confirm @Darkstone158's observations. I logged in and my base had no power at all. Everything is connected using Flux Networks. That destroyed my Fusion Reactor because the e-magnets were not powered anymore, it overheated and melted.

I'll be reverting back to 1.57, as for me this issue makes 1.58 unplayable.

**Comment by MaxNeedsSnacks** [comment]
Merging into #973
