### ISSUE TITLE
OreDict Mob Heads

### ISSUE THREAD

**Issue by gustavosouza1997** [NillerMedDild/Enigmatica2Expert#968]
**Modpack version**
1.57 (Server)

**Can the issue be reproduced?**
Yes

**Issue**
Hi, I'm currently playing the modpack on a server and noticed that you can OreDict other mobs head to the Wither Skull, I tested it using Dank Null and Drawer with the oredict upgrade, was that intentional?

**Comment by MaxNeedsSnacks** [comment]
I mean that definitely **shouldn't** be happening, I don't think it's intentional, lemme investigate that

**Comment by MaxNeedsSnacks** [comment]
Which oredict name are they all registered under atm?

**Comment by gustavosouza1997** [comment]
Updated the server to the 1.58 version and still could do it, I've made a short gif to show you:
[Bug Replication](https://im.ezgif.com/tmp/ezgif-1-6d57c1aa5f78.gif)

**Comment by MaxNeedsSnacks** [comment]
That /dank/null one should just be added to the OreDict blacklist.
