### ISSUE TITLE
Creative Wand Recipe Not Valid

### ISSUE THREAD

**Issue by AnorakThePrimordial** [NillerMedDild/Enigmatica2Expert#969]
**Modpack version**
1.58

**Can the issue be reproduced?**
Yes

**Issue**
The center item in the recipe is the unbreakable wand from not enough wands but the metadata value in the recipe does not match any of the wands available in survival and thus makes the recipe uncraftable. The recipe calls for id 0, the available survival wands are 12-14 indicating their tier of block placing.

**Comment by NillerMedDild** [comment]
It accepts any metadata, it just displays the first one.

**Comment by AnorakThePrimordial** [comment]
Before I made this issue, I tried the recipe on the latest version and it would not craft. The recipe *is* bugged

**Comment by NillerMedDild** [comment]
I can make it just fine, did you do anything special?

**Comment by AnorakThePrimordial** [comment]
Not that I am aware of. Since then, I reloaded the pack and for some reason now it is working though I am sure it wasn't earlier. I dont know what the cause was

**Comment by NillerMedDild** [comment]
Hm, alright :/
