### ISSUE TITLE
Draconic Armor Recipe

### ISSUE THREAD

**Issue by Angelos33** [NillerMedDild/Enigmatica2Expert#97]
#### Issue Description
The Draconic Armor Recipe doesn't seem to work. I checked all the items i placed on the pedestals. I checked in a test world to give the crafting core enough power but still it says in the crafting core no matching recipe. I don't know if i am missing something.
#### Modpack version (Do not use "latest")
Modpack Version 1.26c

**Comment by NillerMedDild** [comment]
I have this fixed in dev, the Mantle of the Stars doesn't work because of Weapon Levels altering its NBT atm.
