### ISSUE TITLE
Using builders wand on Ultimate induction cells converts them to basic cells

### ISSUE THREAD

**Issue by SweetestPumpkin** [NillerMedDild/Enigmatica2Expert#970]
**Modpack version**
Version 1.57

**Can the issue be reproduced?**
Yes

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Issue**
Using builders wand on Ultimate induction cells makes them into basic induction cells . This might be the case with every tier but i havent tried.

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by MorganSimic** [comment]
Don't use builder's wands on TE. I don't even know why that works. TE should not be build by the builders wand.

**Comment by SweetestPumpkin** [comment]
Tile Entities? I dont think induction cells are tile entities

**Comment by NillerMedDild** [comment]
They are :)

**Comment by MaxNeedsSnacks** [comment]
I think the "tier" on Induction Cells is stored within their NBT data as an item, so I can see how that would be cleared when placed with a Builders' Wand

**Comment by MaxNeedsSnacks** [comment]
Okay so this issue happens with both the BBW wand and the XU wand. There's an easy fix for the BBW one, which I'll PR in just a second, but as for the XU wand, I think this is just something that needs to be reported to the Extra Utilities and / or the Mekanism (fork?) issue tracker

**Comment by MaxNeedsSnacks** [comment]
Just found out the issue persists with the Cyclic wand as well, this is definitely an issue on the **Mekanism** side of things.

**Comment by NillerMedDild** [comment]
I don't think reporting to XU or Mekanism will change anything to be perfectly honest. I highly doubt Mekanism will change their NBT-based block system, and getting bug fixes in XU is practically impossible.

**Comment by MaxNeedsSnacks** [comment]
Welp, I'm just gonna submit the fixes to the best of my abilities then. :/

**Comment by NillerMedDild** [comment]
Thank you :)
