### ISSUE TITLE
Xnet connector costs a lot of uu

### ISSUE THREAD

**Issue by Namerian** [NillerMedDild/Enigmatica2Expert#971]
**Modpack version**
1.56

**Can the issue be reproduced?**
Yes/no/unknown

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Issue**
I am not sure if this is WAD or not but replicating an xnet connector costs 8 buckets of uu.

screenshot: https://imgur.com/uiMkw3V

If this is a feature request, feel free to delete the template.

**Comment by MaxNeedsSnacks** [comment]
That's a pre-generated UU value, chests cost a couple of buckets of UU each that's why this value is so inflated
