### ISSUE TITLE
Missing script updates in 1.58

### ISSUE THREAD

**Issue by xob** [NillerMedDild/Enigmatica2Expert#974]
**Modpack version**
Enigmatica 2 Expert 1.58

**Can the issue be reproduced?**
Unknown

**Logs**
Not applicable

**Issue**
Having just updated to 1.58, I went to update my Diamond Anvil autocrafting recipe because I saw it changed in the changelog. To my surprise, I saw that the recipe was still unchanged.

I investigated a little further, and I believe that my update did not grab the updates to files in the `scripts` folder. Looking at merged pull requests, I do not see the changes from #958 and #956 in my files.

If it is relevant, I am using the Twitch desktop app.

**Comment by MaxNeedsSnacks** [comment]
![image](https://user-images.githubusercontent.com/12750501/54087642-1a0f4400-4355-11e9-8eef-5a2e4540a6a9.png)

Yup, something's fishy here

**Comment by NillerMedDild** [comment]
Oh boy, I must've started my update script before pulling >< sorry about that. The changes are in my dev build atm and will be released with 1.59.
