### ISSUE TITLE
Cannot Summon wither boss

### ISSUE THREAD

**Issue by Joprebond** [NillerMedDild/Enigmatica2Expert#977]
**Modpack version**
1.5.8

**Can the issue be reproduced?**
Yes

**Issue**
Cannot summon wither boss. I used the standard vanilla means of summoning it and nothing happened. I then used the wither builder and got the same result. I then dropped into creative mode and tried to do 

/summon minecraft:wither 

I got a message saying object was successfully summoned and did not see the boss. I then went into a new server instance and did the same thing and i saw for a split second the boss was summoned then disappeared.

[latest.log](https://github.com/NillerMedDild/Enigmatica2Expert/files/2950200/latest.log)

**Comment by Discomanco** [comment]
Are you in Peaceful Mode? It sounds like you're in Peaceful Mode

**Comment by Joprebond** [comment]
Strange..... I usually leave my game in hard.... Somehow it got changed to peaceful. Thanks
