### ISSUE TITLE
Osmium Compresor quest - Can't complete

### ISSUE THREAD

**Issue by StrikerPro007** [NillerMedDild/Enigmatica2Expert#978]
**Modpack version**
1.57

**Can the issue be reproduced?**
Yes

**Logs**
there is no error log.

**Issue**
I have a problem with completing osmium compressor machine quest.
Before you started doing some test (does it matter that i added 3 mods: optifine, toolbelt and clearview?) - i haven't tried to deleting it yet.

i tried to making it from the ae2 system, then from normal crafting table, and nothing

**Comment by NillerMedDild** [comment]
Update to 1.58

**Comment by StrikerPro007** [comment]
still the same.. i was in need to change it via edit mode in questing, changing the ignore nbt to true:
![image](https://user-images.githubusercontent.com/32475975/54160351-95edb700-444f-11e9-80b1-fb9de1a26c33.png)

**Comment by DenaliNW** [comment]
Running 1.59a and having the same problem. Used Striker's fix to get around

**Comment by NillerMedDild** [comment]
You need to use the command "/bq_admin default load" to get quest changes. We already fixed this.
