### ISSUE TITLE
AE2 Wireless card works everywhere now

### ISSUE THREAD

**Issue by Rumple1028** [NillerMedDild/Enigmatica2Expert#981]
**Modpack version**
1.58

**Can the issue be reproduced?**
Yes

**Issue**
The AE2 Wireless card works everywhere without the infinity card now.

**Comment by MorganSimic** [comment]
Does it really work? I had occasions when i could open it but it would close immediately after that. But i also seem to recall this may have been the case previously that you could use it without infinity booster card, not sure.

**Comment by Rumple1028** [comment]
Yea It's weird, it worked for a little, then my game crashed from another bug and when I logged back in, it didn't work anymore
