### ISSUE TITLE
Mekanism ignores the client sounds off config setting

### ISSUE THREAD

**Issue by FnordMan** [NillerMedDild/Enigmatica2Expert#983]
**Modpack version**
Input version here1.58

**Can the issue be reproduced?**
Yes

**Issue**
Subject line says it all, friend also says that it ignores sound mufflers as well.

**Comment by NillerMedDild** [comment]
You need to restart the pack for the config to take effect I believe, did you?

**Comment by MorganSimic** [comment]
Previously the sound setting would take effect immediately. And i can confirm, Mekanism does not respect the settings. I did set the sound to zero and restarted the client but to no avail. Mekanism machines are still making sounds.
Quick look on the Meknica github revealed no issue of that sort yet.

**Comment by NillerMedDild** [comment]
Other than this change ofc :P
`Overhauled entire sound system to work reliably with mufflers; reduced size of sound files by 90%`

**Comment by FnordMan** [comment]
Honestly a better solution would be to switch back to the "original" Mekanism now that it's updating again.

**Comment by NillerMedDild** [comment]
...?
That wouldn't fix the issue.

**Comment by MaxNeedsSnacks** [comment]
I think the config option broke when switching to DZ actually

**Comment by NillerMedDild** [comment]
Ah ^^' But the sound being actually fixed would be preferable imo.

**Comment by metnavman** [comment]
Seconding this bug. Was about to make a new issue when a quick search showed this open issue! Nothing I've done with the Config has made the machines stop making noise.

**Comment by dizzyd** [comment]
Hi all - this was pointed out to me on the Mekanica discord. There was a check missing and the next release will have it incorporated. Let me know if you have any other questions!

**Comment by dizzyd** [comment]
@NillerMedDild - if there is a specific back release you'd like me to port this patch to, just let me know.

**Comment by NillerMedDild** [comment]
Good work, thanks!

**Comment by MaxNeedsSnacks** [comment]
This should be fixed upon release of 1.59 (that is if Niller updates Mekanica to at least [this version](https://minecraft.curseforge.com/projects/mekanica/files/2688692) or switches back to the "regular" Mekanism.)

**Comment by NillerMedDild** [comment]
We're staying with Mekanica at least for the time being, the support and response time is great.

**Comment by dizzyd** [comment]
We're releasing 1.1.0 tomorrow morning (GMT+7). It has this and a bunch of other fixes.

**Comment by MaxNeedsSnacks** [comment]
Got it, thanks!
