### ISSUE TITLE
Incorrect JEI Entry for Aevitas Constellation Paper

### ISSUE THREAD

**Issue by aaronproctor** [NillerMedDild/Enigmatica2Expert#984]
**Modpack version**
1.5.6

**Can the issue be reproduced?**
Yes

**Logs**
N/A

**Issue**
When viewing the recipe for the Aevitas Constellation Paper it shows the recipe for Discidia instead

**Comment by NillerMedDild** [comment]
Use the arrows to cycle through recipes.
