### ISSUE TITLE
Advanced Metallurgic Fabricator Recipes for Refined Obsidian/Glowstone

### ISSUE THREAD

**Issue by MorganSimic** [NillerMedDild/Enigmatica2Expert#986]
I have observed that even a fully upgraded osmium compressor is still quite slow when crafting large batches of refined obsidian or glowstone. Considering it doesn't have a factory upgrade and you need quite a bit of that stuff endgame i would propose adding a recipe to the advanced metallurgic fabricator as that seems to fit. I think this would bring the production speed of those materials in line with other endgame production. 
I would propose a recipe with just osmium ingots with the respective material, refined obsidian dust and glowstone. If a bit more expert-ness is needed it could require liquid osmium to mimic the behaviour of the osmium compressor but that could be a bit over the top.

**Comment by NillerMedDild** [comment]
It does have a Factory upgrade ^^

**Comment by MorganSimic** [comment]
Oops. My bad. I feel dumb now.

**Comment by NillerMedDild** [comment]
That's probably healthy from time to time :P
