### ISSUE TITLE
broken crafting recipe

### ISSUE THREAD

**Issue by niklas2233** [NillerMedDild/Enigmatica2Expert#987]
**Modpack version**
1.58

**Can the issue be reproduced?**
unknown

**Issue**

http://prntscr.com/mx84pp

is it supposed to be like this?

**Comment by NillerMedDild** [comment]
Don't just delete the issue template, fill it out.

Either you or the server you're on have incorrect scripts. 
Did you make any changes?

**Comment by niklas2233** [comment]
not that i know

**Comment by NillerMedDild** [comment]
In that case you should reinstall both server and client.

**Comment by niklas2233** [comment]
where is the files that changes the recipes?`

**Comment by MaxNeedsSnacks** [comment]
The recipe is definitely being removed on my test instance.

Probably just... Twitch being Twitch and not downloading stuff correctly... or Minecraft being Minecraft and not minecrafting correctly

**Comment by NillerMedDild** [comment]
Do you get any error messages on login?

**Comment by niklas2233** [comment]
yes about applied energistict controller cause i removed channels

**Comment by MaxNeedsSnacks** [comment]
See there's your issue. ^^

**Comment by niklas2233** [comment]
so that breaks everything?

**Comment by MaxNeedsSnacks** [comment]
If you want a storage network without channels just add Refined Storage, this pack has soft support for it, aka if you add it, recipes will be changed accordingly

**Comment by niklas2233** [comment]
cant i just remove the controller in the script?

**Comment by MaxNeedsSnacks** [comment]
The controller is needed for some other recipes in the pack, so you'd kinda be cheesing the progression by removing the custom recipe for it

**Comment by TemperedFool** [comment]
Why does everyone insist on disabling channels? It's such a terrible idea, and it's completely unnecessary...

**Comment by Kuktar** [comment]
It's players on an expert pack when they're either not experts or dont know
how to look stuff up lol

Christopher Kuhn,
Semper Fidelis
