### ISSUE TITLE
Supremium Axe/Sword is shown as enchantable in JEI / JER, but it isn't

### ISSUE THREAD

**Issue by BuggaNoia** [NillerMedDild/Enigmatica2Expert#988]
**Modpack version**
1.56

**Can the issue be reproduced?**
Yes

**Issue**
'Uses' for the Supremium Axe/Sword shows 'Enchantments' (JER), but if you (try to) put it in any enchanting device (Anvil, Enchantment Applicator) it isn't.

Entchanting works for the Intermedium Sword.

**Comment by MaxNeedsSnacks** [comment]
![image](https://user-images.githubusercontent.com/12750501/54287463-fb53bc00-45a5-11e9-99b7-a73fceba72b9.png)

Enchantments can still be added in an anvil, there's not much more we can do about this other than disabling the Enchantments tab entirely (which won't happen)

**Comment by BuggaNoia** [comment]
Strange: In my game (1.56/Sphax) the Anvil didn't allow the enchantment.

![grafik](https://user-images.githubusercontent.com/22343453/54297809-d9633500-45b7-11e9-9ba9-cf37cd25bdb8.png)

**Comment by MaxNeedsSnacks** [comment]
Is it a compatible enchantment?
