### ISSUE TITLE
Contents of chests/other kinds of inventories turning invisible

### ISSUE THREAD

**Issue by RefotsirkNged** [NillerMedDild/Enigmatica2Expert#99]
#### Issue Description
Items in any sort of chest or inventory goes invisible at times.
This happens both when nothing is being done to the chest inventory window, and when an action is being done.
The items do not really disappear, they only turn invisible. If i for example click on an item, it will still appear in my inventory, either after the chest inventory window is closed or when the items turn visible in the chest again.
I intentionally tried to change the default forge version, did nothing to solve the problem.
I have no idea which specific mod might cause this. It happens with all kinds of inventories.

This issue is not apparent in the major FTB modpacks, which is why i am making the bug report here : )
Do feel free to tell me to go away and report it somewhere else. I just dont know where :)

EDIT: I tried changing render algorithm thingy in betterFPS. Tried all of Riven's algorithm, and taylors teleports me around the map. So no luck there :(

#### Modpack version (Do not use "latest")
Modpack version: 1.26c, Forge version: 14.23.4.2707

**Comment by NillerMedDild** [comment]
https://github.com/NillerMedDild/Enigmatica2/issues/42#issuecomment-396594473

**Comment by NillerMedDild** [comment]
Did you try with Forge 14.23.4.2705?

**Comment by RefotsirkNged** [comment]
I did try with that version yes. A reinstall did not immediately fix it for me either, as suggested in the thread you linked : )

**Comment by NillerMedDild** [comment]
I only linked it to show correlation between two issue report, not for you to try something, I probably should've said that :P

**Comment by NillerMedDild** [comment]
Does this still occur in 1.29?

**Comment by RefotsirkNged** [comment]
Still happens on 1.29 :(

**Comment by NillerMedDild** [comment]
Damnit, I'm stomped.

**Comment by Barhandar** [comment]
Happening for me as well. Enigmatica 1.25 installed on MultiMC, Forge 14.23.3.2689, disabled DiscordSuite and Mouse Tweaks, added Schematica (+LunatriusCore) and CraftingTweaks. Additionally modified configs a bunch such as disabling Quark's texture overrides or removing Rustic from CarryOn's blacklist.

Same issue over at https://github.com/progwml6/ironchest/issues/142 indicates that it's _not_ exclusive to Enigmatica, and issue only appearing after some time in a world complicates testing for it. It also doesn't show anything in the game's logs. As I've noted there, it also happens with IE (alloy kiln) and TC (research table) inventories, but for some reason not Rustic's pots.

**Comment by NillerMedDild** [comment]
I'm guessing this still occurs?

**Comment by RefotsirkNged** [comment]
Just tried again, it still happens. This specific time it happened with a gold chest from i think the iron chests mod, but as mentioned it has happened with all kinds of inventories :)

**Comment by spiderkitten** [comment]
I'm not sure if this is related but I am having an issue where items are invisible, but not in chests. I've noticed it mostly in tinkers. Anything in my tinkers casting table and casting basin is invisible. I can see the item is being made, the liquid pouring into the table and the item appearing, but as soon as it gets to 100% complete the item and the casting mould are invisible. In the basin, I can see the liquid filling it up and the block cooling, but at 100% it is invisible. I'm using E2E 1.33 installed on Twitch client. I haven't disabled or added anything, it's a default install and it started happening pretty much right away, as soon as I built the tinkers smeltery. Within an hour or two of me starting to play the pack. Also, not sure if it is relevant or not but I just tried in the normal Enigmatica 2 and last week when I was playing it was NOT happening, but today after updating to version 1.43 it IS happening in the normal E2 pack.

**Comment by NillerMedDild** [comment]
@spiderkitten Completely unrelated, and I have closed several issues duplicate to yours. The change is even in the changelog.

**Comment by NillerMedDild** [comment]
No Optifine in this case though.

**Comment by RefotsirkNged** [comment]
A quick test shows me two things: 
On a fresh world in the newest version of E2E, i dont immediately see the issue. I tried using the exact same chest types/inventory types as in my save from when the issue initially appeared, and it still did not appear.
If i load the save from back then, it still happens. 

So maybe a fresh save fixes it? sucks for my old save of course, but i can live with it :) 
Of course i cannot be entirely sure whether or not the bug is actually fixed, as i only tried the specific inventories, and some random items, it might have been specific items and chest combinations causing the issue.
If i get the time ill play some more on the fresh save and report back :)

**Comment by MadCat64** [comment]
As a side note, I was in single player on v 1.34 when I had the problems and multiplayer for v 1.36 with no problems.
