### ISSUE TITLE
Automatic production of Alumite

### ISSUE THREAD

**Issue by SeanMcMillan** [NillerMedDild/Enigmatica2Expert#993]
I'm approaching the late game, and I need to make Alumite (in order to make Ludicrite.) There doesn't seem to be any way to make it other than in the smeltery.

I can make Osgloglass in the metallurgic fabricator, which is much easier to automate. Can we get a similar recipe for Alumite?

**Comment by MaxNeedsSnacks** [comment]
Alumite and Primal Mana can be automated using a Tinkers' Complement Alloy Tank ^^

**Comment by SeanMcMillan** [comment]
I wasn't sure if this was on purpose, or just an oversight!
