### ISSUE TITLE
mekanism quests cannot completed i even tried bq_admin default load command

### ISSUE THREAD

**Issue by BlackHoleTON618** [NillerMedDild/Enigmatica2Expert#999]
**Modpack version**
latest
 i cant do mekanism quests  
![2019-03-16_12 23 51](https://user-images.githubusercontent.com/45729798/54473275-38a28e80-47de-11e9-900e-ad25824b7fa6.png)
![2019-03-16_12 23 53](https://user-images.githubusercontent.com/45729798/54473276-38a28e80-47de-11e9-8d03-02b6f14e402c.png)
![2019-03-16_12 23 59](https://user-images.githubusercontent.com/45729798/54473277-38a28e80-47de-11e9-864b-dc98d6d2059a.png)
![2019-03-16_12 24 04](https://user-images.githubusercontent.com/45729798/54473278-38a28e80-47de-11e9-86b3-7b3612a4e126.png)
![2019-03-16_12 23 46](https://user-images.githubusercontent.com/45729798/54473279-393b2500-47de-11e9-91fa-5df2bca28da3.png)

**Comment by BlackHoleTON618** [comment]
do i have to use cheating commands to do that ?

**Comment by MaxNeedsSnacks** [comment]
The fix that fixes Mekanism quests hasn't been released yet, unfortunately, but yes, you can force-complete the quest with `/bq_admin complete <the quest id>` which requires cheats to be enabled

**Comment by Kuktar** [comment]
Or just go creative and grab the items with no NBT data.

Christopher Kuhn,
Semper Fidelis

**Comment by BlackHoleTON618** [comment]
i edited that quest and i choose the item that im holding

**Comment by CastielAngelow** [comment]
Honestly you can just go /bq_admin edit true
find quest you need to be re-done(repaired) and for Mekanism, you just need to look for that needed block and set setting value Ignore NBT Data to true from false. Thats it. ;)
It is becuse when you place Mekanism block etc., it write to NBT your UUID and similar so its NBT change. Thats really it + wait for fix :)

**Comment by MaxNeedsSnacks** [comment]
Closing as this will most likely be fixed with the next release, anyway.
